/* Questions de la semaine 19. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w19-d0': [
    { q: 'En finance et en bourse, que désigne-t-on par le terme "Matières premières" (ou Commodities) ?',
      options: ['Les usines qui fabriquent des voitures', 'Les brevets et droits d\'auteur', 'Des ressources naturelles brutes extraites, cultivées ou exploitées, qui sont uniformes et interchangeables (pétrole, or, blé, cuivre)', 'Les logiciels informatiques'],
      correct: 2, rationale: 'Ce sont les ingrédients de base de l\'économie mondiale. Elles sont classées en métaux (précieux/industriels), énergies (gaz, pétrole) et produits agricoles (soft commodities).' },
    { q: 'Lequel de ces actifs N\'EST PAS une "matière première" financière ?',
      options: ['Un baril de pétrole Brent', 'Une once d\'Or', 'L\'action de l\'entreprise Apple', 'Un boisseau de maïs'],
      correct: 2, rationale: 'Une action est un titre de propriété d\'une entreprise (une société). Une matière première est une ressource physique brute.' },
    { q: 'Comment les investisseurs particuliers (vous et moi) investissent-ils classiquement dans les matières premières en bourse ?',
      options: ['En achetant physiquement des tonnes de blé et de barils de pétrole pour les stocker dans leur jardin', 'En demandant un ticket à la mairie', 'Via des fonds indiciels spécifiques appelés ETC (Exchange Traded Commodities) qui répliquent le cours, ou en achetant les actions des entreprises qui extraient ces matières (ex : Total pour le pétrole)', 'Ils ne peuvent pas, c\'est interdit'],
      correct: 2, rationale: 'Acheter un ETF/ETC "Pétrole" permet de spéculer sur la hausse du baril sans avoir besoin de faire livrer un tonneau de pétrole brut dans son salon.' },
    { q: 'Quel est le profil de risque typique du marché des matières premières ?',
      options: ['Un risque zéro, c\'est une rente garantie', 'C\'est un marché extrêmement volatil et cyclique, car les prix dépendent de chocs imprévisibles (climat, guerres, pandémies, blocages de canaux maritimes)', 'Le prix baisse toujours avec le temps', 'C\'est un marché bloqué par l\'État'],
      correct: 1, rationale: 'Si la Russie coupe le gaz, le prix explose en 24h. Si une sécheresse frappe les USA, le prix du blé double.' },
    { q: 'Quel est l\'intérêt principal pour un bon gestionnaire d\'ajouter 5% de matières premières dans un portefeuille financier (au milieu des actions et obligations) ?',
      options: ['Pour la "Décorrélation" : les matières premières réagissent souvent différemment des actions ou de l\'immobilier face à un événement (si la bourse s\'effondre à cause d\'une guerre, le pétrole et l\'or vont, eux, souvent grimper)', 'Pour payer la taxe carbone', 'Pour diviser les impôts', 'Pour que la banque offre une prime'],
      correct: 0, rationale: 'Les matières premières agissent comme un stabilisateur (amortisseur) pour le portefeuille global lorsque l\'économie traditionnelle déraille.' },
    { q: 'Comment s\'appelle le marché financier ultra-spéculatif où professionnels et traders s\'échangent des matières premières non pas pour aujourd\'hui, mais pour une livraison future à un prix fixé d\'avance ?',
      options: ['Le marché noir', 'Le marché primaire', 'Le marché à terme (ou marché des contrats "Futures" / produits dérivés)', 'Le marché des devises (Forex)'],
      correct: 2, rationale: 'Une compagnie aérienne achètera du kérosène "pour dans 6 mois" afin de bloquer son prix et se protéger d\'une hausse soudaine. Le trader, lui, spéculera sur ce contrat.' },
    { q: 'Parmi les matières premières, l\'Or bénéficie d\'un statut "à part". Pourquoi ?',
      options: ['Il est consommé massivement par l\'agriculture', 'Il sert historiquement de "Monnaie" et de "Valeur refuge", sa demande dépendant plus de la peur des investisseurs que de son simple usage industriel ou de consommation', 'Il est radioactif', 'Il est illimité sur terre'],
      correct: 1, rationale: 'Contrairement au pétrole qui est brûlé, l\'or est stocké. Il rassure le monde entier quand l\'économie vacille.' },
    { q: 'Quel cartel géopolitique influence massivement le prix mondial du baril de pétrole en décidant d\'ouvrir ou de fermer les vannes de la production ?',
      options: ['L\'OMS', 'Le FMI', 'L\'OPEP (Organisation des Pays Exportateurs de Pétrole)', 'L\'Union Européenne'],
      correct: 2, rationale: 'En contrôlant l\'offre (la rareté), ce cartel dicte en grande partie le prix mondial de l\'énergie. (S\'ils produisent moins, le prix monte).' },
    { q: '(Challenge) Contrairement à une action (qui verse des dividendes) ou une obligation (qui verse des intérêts), quel est le grand "défaut" de l\'investissement strict en matière première (via un ETC physique) ?',
      options: ['Les ETC sont illégaux', 'Il oblige à prendre livraison du métal', 'La matière première est "stérile" : elle ne produit ni richesse, ni bénéfice, ni flux de trésorerie (aucun dividende). L\'investisseur ne s\'enrichit QUE si quelqu\'un veut lui racheter plus cher plus tard', 'Il faut payer l\'assurance santé de la mine'],
      correct: 2, rationale: 'Un lingot d\'or ou un baril de pétrole ne fabrique rien. C\'est l\'un des arguments des détracteurs de l\'or (comme Warren Buffett) face aux entreprises qui créent de la valeur.' },
    { q: '(Challenge) Pourquoi dit-on souvent que les matières premières protègent très bien un portefeuille contre une forte INFLATION ?',
      options: ['Parce que l\'inflation est très souvent CAUSÉE par la flambée des prix de ces mêmes matières premières (pétrole, blé). Avoir des matières premières en portefeuille permet de profiter directement de cette flambée qui ruine par ailleurs les consommateurs', 'Car elles font baisser les taux d\'intérêt', 'Car elles sont subventionnées par la BCE', 'Parce que le gouvernement limite leur prix'],
      correct: 0, rationale: 'L\'inflation de 2022 a été tirée par le gaz, le pétrole et les céréales. L\'investisseur qui détenait un ETC sur l\'énergie a fait des gains massifs, compensant l\'augmentation du prix de son plein d\'essence.' },
  ],
  'w19-d1': [
    { q: 'Qu\'est-ce que le dispositif CESU (Chèque Emploi Service Universel) ?',
      options: ['Un chèque pour acheter une voiture', 'Un chèque restaurant de l\'entreprise', 'Un dispositif simplifié de l\'URSSAF qui permet à un particulier de déclarer, payer et gérer facilement un salarié employé à son domicile (sans formalité comptable lourde)', 'Une taxe sur l\'emploi'],
      correct: 2, rationale: 'Le CESU calcule lui-même les cotisations sociales, édite les fiches de paie, et permet de sécuriser légalement le travailleur.' },
    { q: 'Quel est l\'énorme AVANTAGE FISCAL accordé par l\'État aux particuliers qui emploient et déclarent un salarié à domicile ?',
      options: ['L\'État rembourse la totalité du salaire', 'Un "Crédit d\'impôt" égal à 50 % des dépenses globales supportées dans l\'année (salaire net versé + cotisations sociales URSSAF)', 'Le droit de ne pas payer la taxe foncière', 'La TVA à zéro'],
      correct: 1, rationale: 'L\'État finance la moitié de votre femme de ménage ou de votre jardinier, afin de lutter contre le travail au noir.' },
    { q: 'Laquelle de ces prestations N\'EST PAS éligible au crédit d\'impôt pour "emploi à domicile" ?',
      options: ['Le ménage et repassage', 'Le soutien scolaire à domicile des enfants', 'Des travaux de construction ou de rénovation lourde (ex: électricité, mur, toiture)', 'L\'assistance aux personnes âgées ou handicapées'],
      correct: 2, rationale: 'Le crédit d\'impôt vise les services à la personne (quotidien, petits bricolages), et exclut les chantiers qui relèvent de l\'artisanat classique.' },
    { q: 'Comme il s\'agit d\'un "Crédit d\'impôt" (et non d\'une simple "réduction"), que se passe-t-il si le particulier qui emploie la femme de ménage N\'EST PAS IMPOSABLE (il a un petit revenu et un impôt à zéro) ?',
      options: ['L\'avantage est perdu', 'L\'État lui versera quand même les 50 % de l\'aide directement sous forme de chèque ou de virement bancaire sur son compte', 'Il devra payer les 50 % à la mairie', 'L\'avantage est mis en réserve pour ses enfants'],
      correct: 1, rationale: 'C\'est la beauté du "crédit" d\'impôt. Il profite à tout le monde, même aux ménages très modestes ou retraités non imposables.' },
    { q: 'Ce crédit d\'impôt très généreux est-il limité (plafonné) ?',
      options: ['Non, il est illimité', 'Oui, les dépenses sont généralement plafonnées à 12 000 € par an, ce qui donne un crédit d\'impôt maximum de 6 000 € (plafonds majorés si enfants ou invalidité)', 'Il est plafonné à 100 € par an', 'Uniquement si on gagne plus de 50 000 €'],
      correct: 1, rationale: 'Vous ne pouvez pas faire financer à 50% par l\'État du personnel de maison à temps plein 24h/24.' },
    { q: 'Ce dispositif de l\'emploi à domicile est-il soumis au "Plafond global des niches fiscales" ?',
      options: ['Il est interdit par la loi', 'Non, il échappe totalement au plafond', 'Seulement pour le jardinage', 'Oui, il rentre pleinement dans la limite globale des 10 000 € d\'avantages fiscaux cumulables par an et par foyer'],
      correct: 3, rationale: 'Si vous avez 6 000 € de crédit d\'impôt pour votre nounou, il ne vous reste "que" 4 000 € de place pour vos autres réductions (ex: Pinel).' },
    { q: 'Qu\'est-ce que la révolution du "CESU + (Avance Immédiate du crédit d\'impôt)" mise en place en 2022 par l\'URSSAF ?',
      options: ['L\'URSSAF paie 100 % du salaire', 'C\'est un crédit pour acheter une maison', 'Le particulier n\'a plus à faire l\'avance des frais pour attendre d\'être remboursé 1 an après : l\'URSSAF prélève directement sur son compte bancaire SEULEMENT le "reste à charge" de 50 %, la déduction fiscale se faisant en temps réel', 'Le salaire est payé en bons d\'achat'],
      correct: 2, rationale: 'C\'est un coup de boost magistral pour le pouvoir d\'achat mensuel. Si le salaire coûte 200€, vous ne déboursez que 100€ à la fin du mois.' },
    { q: 'Que risque un particulier qui "oublie" de déclarer son employé de maison (travail dissimulé / au noir) pour soi-disant économiser l\'URSSAF ?',
      options: ['Une simple lettre d\'avertissement', 'Un rappel à l\'ordre du maire', 'Le blocage de son compte en banque pendant un mois', 'Un redressement financier brutal de l\'URSSAF, des poursuites pénales (3 ans de prison, 45 000 € d\'amende), des risques d\'indemnisation à vie si la femme de ménage chute, ET la perte totale du droit au crédit d\'impôt de 50 %'],
      correct: 3, rationale: 'Compte tenu de l\'aide de 50% de l\'État et de la simplicité du CESU, le risque pris à faire travailler quelqu\'un au noir chez soi est irrationnel.' },
    { q: '(Challenge) Y a-t-il une limite spécifique PLUS BASSE (un sous-plafond) pour certaines tâches précises de la maison, comme le petit bricolage dit "hommes toutes mains" (ex: monter un meuble) ?',
      options: ['Non, c\'est plafonné à 12 000 € comme le reste', 'Seulement le dimanche', 'Oui, le petit bricolage est strictement plafonné à 500 € de dépenses par an (soit 250 € de crédit d\'impôt), pour ne pas concurrencer déloyalement les artisans', 'Le bricolage donne 100 % de crédit d\'impôt'],
      correct: 2, rationale: 'Monter un meuble Ikea ou accrocher un cadre est autorisé en CESU, mais pas de quoi refaire le salon. L\'assistance informatique a aussi un sous-plafond (3 000 €).' },
    { q: '(Challenge) Le crédit d\'impôt pour l\'emploi à domicile s\'applique-t-il si vous payez un jardinier pour tailler les haies de votre Résidence SECONDAIRE (maison de vacances) ?',
      options: ['Seulement si la maison de vacances est en France', 'Oui, la loi l\'autorise. L\'avantage fiscal porte sur les dépenses effectuées pour la résidence principale ET pour les résidences secondaires du contribuable', 'Non, c\'est exclusif à la résidence principale', 'La réduction tombe à 10 %'],
      correct: 1, rationale: 'Un ménage peut parfaitement déclarer le ménage de sa maison parisienne et l\'entretien du jardin de sa villa en Bretagne, dans la limite globale du plafond des 12 000 € de dépenses.' },
  ],
  'w19-d2': [
    { q: 'Quel est le principe de base du système de retraite par "Répartition" (le système français dominant actuel, géré par la Sécurité Sociale) ?',
      options: ['On place l\'argent en bourse sur un compte bloqué', 'Les cotisations prélevées sur les salaires des ACTIFS d\'aujourd\'hui servent à payer immédiatement les pensions des RETRAITÉS d\'aujourd\'hui (solidarité intergénérationnelle)', 'Le gouvernement paie tout sans prendre sur les salaires', 'L\'argent est investi dans la pierre'],
      correct: 1, rationale: 'C\'est le contrat social d\'après-guerre. Votre cotisation de ce mois-ci paie la retraite de votre grand-mère le mois prochain.' },
    { q: 'À l\'inverse, quel est le fonctionnement strict de la retraite par "Capitalisation" ?',
      options: ['Le travailleur épargne et place son propre argent sur un compte individuel, le fait fructifier sur les marchés financiers, et récupèrera SON propre capital (majoré des gains) lorsqu\'il prendra sa retraite', 'Les riches paient pour les pauvres', 'L\'État épargne l\'argent des impôts pour la vieillesse', 'C\'est un système de loterie'],
      correct: 0, rationale: 'C\'est un système individualiste (chacun pour soi). Si vos placements performent, vous serez un riche retraité. S\'ils s\'effondrent, vous serez un retraité pauvre.' },
    { q: 'Pourquoi le système français, 100% Répartition, se retrouve-t-il lourdement menacé par la "démographie" (le vieillissement de la population) ?',
      options: ['Parce que les gens partent trop tard', 'Car il y a de plus en plus de retraités qui vivent plus longtemps, et proportionnellement de moins en moins d\'actifs (jeunes) pour cotiser et financer leurs pensions', 'Car la natalité est trop forte', 'Parce que les robots remplacent les retraités'],
      correct: 1, rationale: 'Dans les années 60, il y avait 4 actifs pour 1 retraité. Aujourd\'hui, il y a environ 1,7 actif pour 1 retraité. L\'équation financière devient intenable.' },
    { q: 'Face à ce déséquilibre de la Répartition, que pousse le gouvernement français à faire en créant des produits comme le PER (Plan d\'Épargne Retraite) ?',
      options: ['Interdire le travail des jeunes', 'Supprimer la retraite de base', 'Maintenir la Répartition, mais encourager MASSIVEMENT les Français à se constituer, en complément, une retraite par "Capitalisation" individuelle pour pallier la future baisse inévitable des pensions de base', 'Privatiser l\'hôpital'],
      correct: 2, rationale: 'C\'est le système mixte. La base (répartition) assurera le minimum vital, votre capitalisation (PER/Assurance-vie) assurera votre confort.' },
    { q: 'Quel est l\'atout mathématique majeur de la Capitalisation lorsque l\'épargne démarre très tôt dans la carrière du travailleur ?',
      options: ['L\'exonération de la taxe foncière', 'La garantie de l\'État à 100 %', 'La prime gouvernementale', 'La puissance des "intérêts composés" : sur 40 ans de vie active, les rendements financiers réinvestis vont créer un effet boule de neige, démultipliant le capital final bien au-delà de l\'épargne versée'],
      correct: 3, rationale: 'Placer 150€ par mois pendant 40 ans à 6% génère un capital final énorme, dont la majorité est issue des intérêts boursiers.' },
    { q: 'Quel est le RISQUE inhérent et absolu pour le particulier dans un système de retraite par Capitalisation pur ?',
      options: ['Que l\'argent soit volé par la mairie', 'Il assume seul le "risque de marché" : si une crise financière mondiale (krach) éclate la veille de sa retraite, son capital peut s\'effondrer et son niveau de vie avec', 'Que le compte soit bloqué le week-end', 'L\'interdiction de travailler'],
      correct: 1, rationale: 'C\'est le drame vécu par beaucoup d\'Américains en 2008. Pour éviter ça, on "sécurise" (désensibilise) le portefeuille à l\'approche de la retraite.' },
    { q: 'Dans un produit de capitalisation, quelles sont les deux manières possibles de récupérer (liquider) son épargne arrivé à la retraite ?',
      options: ['Sous forme de dons associatifs', 'Exclusivement en actions de l\'entreprise', 'Sortir la totalité en "Capital" (en une fois ou en fractionné) OU transformer cette épargne en "Rente viagère" (un revenu garanti versé tous les mois jusqu\'au décès)', 'Il faut payer pour la récupérer'],
      correct: 2, rationale: 'Le nouveau PER français offre cette grande liberté de choix, qui était très attendue par les épargnants.' },
    { q: 'Quelle affirmation est FAUSSE concernant la retraite par capitalisation en France ?',
      options: ['Elle remplace totalement la Sécurité Sociale (régime de base) depuis 2023', 'L\'État encourage la capitalisation par la déduction fiscale des versements', 'Le PER est l\'outil phare de la capitalisation', 'L\'argent de la capitalisation est bloqué (sauf cas prévus) jusqu\'à la retraite'],
      correct: 0, rationale: 'C\'est totalement faux. Le système français reste fermement ancré sur la Répartition. La capitalisation n\'est qu\'un étage "supplémentaire" (facultatif).' },
    { q: '(Challenge) Aux États-Unis, le système de retraite repose énormément sur la capitalisation. Comment s\'appelle le célèbre compte d\'épargne retraite d\'entreprise américain ?',
      options: ['Le Livret A', 'Le 401(k)', 'Le Dow Jones', 'La Green Card'],
      correct: 1, rationale: 'C\'est l\'équivalent de notre PER Collectif. Le salarié US y verse une part de son salaire avant impôts, souvent "abondée" par son employeur (le "matching").' },
    { q: '(Challenge) Dans la théorie économique, quel est l\'effet positif de l\'épargne retraite par capitalisation sur l\'Économie réelle d\'un pays ?',
      options: ['Cela augmente le chômage', 'L\'argent épargné par des millions de futurs retraités est "injecté" sur les marchés, finançant ainsi massivement la dette des entreprises et de l\'État, favorisant l\'innovation et la création d\'emplois locaux', 'Cela ruine l\'État qui ne touche plus d\'impôts', 'Les entreprises doivent payer plus de cotisations'],
      correct: 1, rationale: 'Les fameux "fonds de pensions" mondiaux sont les plus gros actionnaires des entreprises. La France s\'est longtemps privée de cette force de frappe financière en refusant la capitalisation.' },
  ],
  'w19-d3': [
    { q: 'En France, lorsqu\'une personne donne un bien de son vivant (donation) ou transmet à son décès (succession), quel principe fiscal universel s\'applique au bénéficiaire ?',
      options: ['Une interdiction de vendre pendant 10 ans', 'L\'application d\'un abattement légal (une somme sans impôt), puis l\'application du "barème progressif" des droits de mutation sur la part qui dépasse l\'abattement', 'Un impôt fixe de 50 %', 'L\'exonération totale, il n\'y a pas d\'impôt sur les dons'],
      correct: 1, rationale: 'Le système fonctionne exactement comme l\'impôt sur le revenu : des tranches d\'imposition de plus en plus fortes.' },
    { q: 'Quel est le montant de "l\'abattement classique" dont bénéficie un ENFANT de la part de l\'un de ses PARENTS lors d\'une donation ?',
      options: ['31 865 €', '1 594 €', '152 500 €', '100 000 € (renouvelable tous les 15 ans)'],
      correct: 3, rationale: 'Un couple (deux parents) peut donc transmettre 200 000 € à son enfant sans aucun impôt, plusieurs fois dans sa vie si on s\'y prend tôt.' },
    { q: 'Une grand-mère veut faire une donation "classique" à son PETIT-ENFANT. Quel est le montant de l\'abattement légal sans impôt ?',
      options: ['31 865 €', '100 000 €', 'Il n\'y en a pas', '80 000 €'],
      correct: 0, rationale: 'L\'avantage fiscal se réduit quand on saute une génération, mais cela reste très utile pour aider les jeunes à s\'installer.' },
    { q: 'Outre l\'abattement classique, qu\'est-ce que "l\'Abattement pour Don Familial de Sommes d\'Argent" (anciennement loi TEPA/Sarkozy) ?',
      options: ['Un don pour la retraite', 'Un droit de donner sa maison sans notaire', 'Une exonération SUPPLEMENTAIRE de 31 865 €, cumulable avec l\'abattement classique, MAIS réservée exclusivement aux dons en argent liquide/virement, et soumise à des conditions d\'âge du donneur (<80 ans) et du receveur (>18 ans)', 'Un prêt de l\'État aux familles'],
      correct: 2, rationale: 'C\'est l\'outil parfait pour donner de la liquidité aux jeunes. Parent et enfant peuvent ainsi cumuler 100 000 + 31 865 = 131 865 € net d\'impôt.' },
    { q: 'Que se passe-t-il sur la somme qui DÉPASSE les abattements légaux ? (ex: un parent donne un appartement de 150 000 € à son fils)',
      options: ['La somme excédentaire (50 000 €) est confisquée par l\'État', 'La somme excédentaire sera taxée selon le barème progressif des droits de donation en ligne directe (pour les enfants, les tranches vont de 5 % à 45 %)', 'L\'excédent est imposé à 30 % (PFU)', 'L\'excédent est annulé'],
      correct: 1, rationale: 'L\'enfant paiera 5% sur la petite première tranche, 10% sur la suivante, puis 20% sur la majorité de ces 50 000 € (la tranche à 20% étant très large).' },
    { q: 'Vous n\'avez pas d\'enfants. Vous décidez de donner de l\'argent ou un appartement à votre CONCUBIN (union libre) ou à un AMI (tiers absolu). Quelle est la punition fiscale ?',
      options: ['Une amende pour fraude', 'Exonération s\'ils habitent avec vous depuis 10 ans', 'Il n\'y a pas d\'impôt entre amis', 'Après un micro-abattement de 1 594 €, la totalité de la donation subira des droits de succession/donation au taux de 60 %'],
      correct: 3, rationale: 'C\'est le taux spoliateur pour empêcher la transmission de patrimoine hors de la famille. Si vous donnez 100 000 € à votre ami, l\'État en prendra environ 60 000 €.' },
    { q: 'Quel est l\'abattement fiscal prévu pour une donation faite entre FRÈRES ET SŒURS (par exemple de son vivant) ?',
      options: ['100 000 €', '1 594 €', '31 865 €', '15 932 €'],
      correct: 3, rationale: 'Les transmissions latérales (entre la fratrie) sont très faiblement protégées par le fisc. Au-delà des ~16k, l\'impôt est violent (35 % à 45 %).' },
    { q: 'Lors d\'une donation, qui est LÉGALEMENT censé payer les droits (les impôts) au fisc ?',
      options: ['L\'État', 'C\'est obligatoirement le Donataire (celui qui REÇOIT le cadeau) qui est redevable de l\'impôt', 'L\'assurance', 'Le notaire de sa poche'],
      correct: 1, rationale: 'L\'impôt frappe celui qui s\'enrichit. Vous donnez la maison, c\'est l\'enfant qui doit sortir l\'argent de sa poche pour payer les impôts.' },
    { q: '(Challenge) Suite de la question précédente : le parent (Donateur) a pitié de son enfant et décide de PAYER LUI-MÊME les impôts de la donation. Quelle est la règle fiscale fabuleuse à ce sujet ?',
      options: ['Le paiement de cet impôt par le parent n\'est PAS considéré par le fisc comme une "donation supplémentaire". C\'est un pur cadeau gratuit qui booste la transmission', 'C\'est passible de prison', 'L\'impôt est doublé', 'Le notaire annule la vente'],
      correct: 0, rationale: 'Prendre à sa charge les frais et droits du donataire est un des plus beaux outils d\'optimisation fiscale en gestion de patrimoine.' },
    { q: '(Challenge) Quelle est l\'énorme anomalie fiscale (très favorable) lors d\'une "Donation de Compte-titres" (des actions en bourse) sur lequel vous avez une très forte plus-value latente (des gros gains non vendus) ?',
      options: ['Le CTO est saisi par la banque', 'L\'enfant paie la Flat Tax à votre place', 'La donation "purge" définitivement la plus-value latente. L\'impôt sur le revenu sur vos anciens gains boursiers est effacé, le compteur de l\'enfant repartant à zéro (à la valeur du jour du don)', 'La plus-value est taxée deux fois'],
      correct: 2, rationale: 'Donner des titres en très forte plus-value est un classique pour les riches contribuables. Ils transmettent leur patrimoine (qui peut être couvert par les 100k€ d\'abattement) tout en esquivant totalement la Flat Tax sur leurs gains historiques.' },
  ],
  'w19-d4': [
    { q: 'Que stipule la Loi issue de l\'ANI (Accord National Interprofessionnel) entrée en vigueur en 2016 concernant la santé en France ?',
      options: ['Que la mutuelle est interdite', 'L\'obligation pour TOUS les employeurs du secteur privé de souscrire et de proposer une complémentaire santé collective (Mutuelle d\'entreprise) à l\'ensemble de leurs salariés', 'Que les consultations chez le médecin généraliste sont gratuites', 'Que l\'État rembourse 100% des frais'],
      correct: 1, rationale: 'C\'est une immense avancée sociale qui a supprimé les situations précaires de millions de salariés du privé qui n\'avaient pas les moyens de se payer une mutuelle.' },
    { q: 'Quelle est la participation (le financement) MINIMALE que l\'employeur doit OBLIGATOIREMENT prendre à sa charge pour payer cette mutuelle collective ?',
      options: ['100 %', 'Il ne paie rien', '50 % du coût de la cotisation (le reste étant prélevé sur la paie du salarié)', '10 %'],
      correct: 2, rationale: 'De nombreuses conventions collectives ou patrons généreux montent à 60% ou 100%, mais le minimum légal est la moitié.' },
    { q: 'Un salarié, embauché en CDI à plein temps, a-t-il le droit de refuser (demander une dispense d\'affiliation) la mutuelle de sa nouvelle entreprise "parce qu\'il n\'en a pas envie" ?',
      options: ['Non, la souscription est en principe OBLIGATOIRE pour le salarié, sauf s\'il entre dans des cas de "dispenses" très stricts prévus par la loi', 'Oui, c\'est totalement libre', 'Seulement s\'il n\'est jamais malade', 'Uniquement après l\'accord du maire'],
      correct: 0, rationale: 'Le système fonctionne par "mutualisation" (les bien portants paient pour les malades). Si les jeunes en bonne santé pouvaient refuser, le système s\'effondrerait.' },
    { q: 'Lequel de ces motifs constitue un cas de DISPENSE légalement valable pour refuser la mutuelle d\'entreprise ?',
      options: ['Le salarié est déjà couvert "à titre obligatoire" par la mutuelle familiale d\'entreprise de son mari ou de sa femme (ayant droit)', 'Le salarié ne croit pas en la médecine', 'Le salarié a peur des hôpitaux', 'Le salarié gagne plus de 3 000 €'],
      correct: 0, rationale: 'L\'employeur ne va pas vous forcer à payer une mutuelle si vous êtes déjà obligé de payer l\'excellente mutuelle familiale de l\'entreprise de votre épouse.' },
    { q: 'L\'employeur a le choix du contrat d\'assurance, mais il doit respecter "le panier de soins minimum". Qu\'est-ce que cela signifie ?',
      options: ['Il faut payer l\'homéopathie', 'Le contrat doit obligatoirement inclure un niveau de couverture minimal fixé par la loi (prise en charge du ticket modérateur, du forfait journalier hospitalier, et minimums en optique/dentaire)', 'Le droit à 10 séances de massage', 'Des fruits gratuits au bureau'],
      correct: 1, rationale: 'L\'employeur ne peut pas souscrire un contrat "au rabais" qui ne rembourserait pas le minimum syndical à ses salariés.' },
    { q: 'Que permet la "Portabilité" de la mutuelle, introduite pour sécuriser les parcours professionnels ?',
      options: ['Permet à un salarié dont le contrat s\'achève et qui est indemnisé par France Travail (chômage) de conserver les garanties de la mutuelle de son ex-entreprise, GRATUITEMENT, pendant 12 mois maximum', 'D\'emmener sa mutuelle en vacances à l\'étranger', 'De la donner à son chien', 'De se faire soigner par Internet'],
      correct: 0, rationale: 'Le salarié licencié ne subit plus la "double peine" (perte de salaire + perte de couverture santé). C\'est un filet de sécurité majeur.' },
    { q: 'Qui paie la prime de mutuelle pendant cette année de "Portabilité" pour l\'ancien salarié au chômage ?',
      options: ['L\'État s\'en charge', 'Le salarié doit la payer de sa poche à la fin', 'Personne : le coût est mutualisé (inclus dans la prime payée par les salariés encore actifs dans l\'entreprise et par l\'employeur)', 'Pôle emploi (France Travail)'],
      correct: 2, rationale: 'C\'est la solidarité d\'entreprise. Vous payez aujourd\'hui un tout petit peu plus cher pour couvrir ceux qui sont partis au chômage.' },
    { q: 'Que se passe-t-il si un salarié DÉMISSIONNE de son entreprise sans motif légitime (pas de droit au chômage) ?',
      options: ['L\'entreprise doit le dédommager', 'Il bénéficie de la portabilité gratuite', 'Il perd le droit à la portabilité de la mutuelle. Son contrat s\'arrête à la date de rupture du contrat de travail', 'Il garde la mutuelle à vie'],
      correct: 2, rationale: 'La portabilité est strictement conditionnée à la prise en charge par l\'Assurance Chômage.' },
    { q: '(Challenge) Lors du départ en RETRAITE, l\'ancien salarié a le droit (Loi Évin) de demander à l\'assureur de "maintenir" son ancienne mutuelle d\'entreprise de manière individuelle. Mais quel est le piège lié au PRIX de cette couverture ?',
      options: ['Le prix baisse de 50 %', 'Le prix est gratuit', 'L\'ancien salarié doit payer 100% de la prime (l\'entreprise ne paie plus sa part de 50%). DE PLUS, l\'assureur a le droit d\'augmenter le tarif initial (+25% la 2ème année, +50% la 3ème année), rendant souvent ce contrat "Loi Évin" trop cher pour le retraité', 'L\'État paie la différence'],
      correct: 2, rationale: 'C\'est la "douche froide" du départ en retraite. La mutuelle qui coûtait 40€ par mois au salarié actif va soudainement lui coûter 150€ par mois à la retraite.' },
    { q: '(Challenge) FISCALITÉ : Sur la fiche de paie, la part de la mutuelle financée par l\'employeur (les fameux 50 %) est-elle un "cadeau" sans conséquence fiscale pour le salarié ?',
      options: ['Non ! La part payée par l\'employeur est considérée comme un "avantage en nature". Elle est RÉINTÉGRÉE dans le salaire net imposable de l\'employé, qui paiera donc de l\'Impôt sur le Revenu sur cette somme', 'Elle annule ses impôts', 'Oui, c\'est totalement défiscalisé (Zéro IR et zéro CSG)', 'Seulement si on dépasse 300 €'],
      correct: 0, rationale: 'L\'État considère que ce que l\'entreprise paie à votre place pour la mutuelle est comme une part de salaire. Cela gonfle donc le montant final de vos impôts annuels.' },
  ],
  'w19-d5': [
    { q: 'Quel célèbre adage anglo-saxon résume le critère numéro un pour réussir un investissement immobilier ?',
      options: ['"Acheter, louer, vendre"', '"Le risque, c\'est la vie"', '"Location, location, location" (L\'emplacement, l\'emplacement, l\'emplacement)', '"L\'argent n\'a pas d\'odeur"'],
      correct: 2, rationale: 'En immobilier, tout le reste (décoration, murs, locataires) peut être changé. La seule chose que vous ne pourrez JAMAIS modifier, c\'est l\'emplacement géographique du bâtiment.' },
    { q: 'Pourquoi l\'emplacement est-il le bouclier principal contre la fameuse "vacance locative" (le risque d\'avoir un logement vide) ?',
      options: ['Car un emplacement dynamique et bien desservi (hyper-centre, transports) garantira toujours un afflux de candidats locataires, même en temps de crise économique', 'Parce que l\'agence immobilière est proche', 'Car l\'emplacement bloque les loyers', 'Pour éviter la taxe foncière'],
      correct: 0, rationale: 'Un magnifique appartement perdu dans une campagne sans emplois ni étudiants restera vide. Un studio moyen au pied du métro à Lyon trouvera preneur en 24 heures.' },
    { q: 'Pour un investissement ciblant les "Étudiants" (petites surfaces), quel est le critère d\'emplacement discriminant (celui qui déclenche la signature) ?',
      options: ['La vue sur les montagnes', 'La proximité immédiate et la qualité de la desserte en transports en commun "lourds" (métro, tramway) menant aux universités ou au centre-ville animé', 'La présence de grands parcs pour enfants', 'La présence d\'un golf'],
      correct: 1, rationale: 'L\'étudiant n\'a souvent pas de voiture. Son obsession est le temps de trajet pour aller en cours et son accès à la vie étudiante nocturne.' },
    { q: 'Un bien vous est proposé à un prix cassé, avec une "rentabilité de 12 %", mais il est situé dans une ville en plein déclin démographique avec une usine qui vient de fermer. Quel est le piège ?',
      options: ['L\'État paiera le loyer', 'La rentabilité n\'est que théorique sur le papier (Excel). Dans la réalité, vous ferez face à des loyers impayés, à des squats, à la dégradation du quartier, et à l\'impossibilité totale de revendre le bien sans subir une perte en capital écrasante', 'Les impôts seront nuls', 'Il n\'y a aucun piège, c\'est une affaire en or'],
      correct: 1, rationale: 'La haute rentabilité masque un risque extrême. Personne ne veut acheter ni louer durablement dans une zone économiquement morte.' },
    { q: 'Qu\'est-ce que "l\'effet d\'anticipation" lié à un emplacement (ex: l\'annonce officielle du prolongement d\'une ligne de métro vers un quartier) ?',
      options: ['Les prix s\'effondrent à cause du bruit', 'Les prix de l\'immobilier dans la zone vont monter et s\'ajuster BIEN AVANT que les travaux ne soient terminés, dès que la certitude du projet urbain est connue des investisseurs', 'La mairie interdit les ventes', 'L\'État fixe un prix maximum'],
      correct: 1, rationale: 'L\'investisseur malin achète au moment de la rumeur ou de l\'annonce officielle, et encaisse la plus-value de valorisation (gentrification) de la zone quelques années plus tard.' },
    { q: 'Face à la cherté de l\'hyper-centre des grandes métropoles (ex: Paris, Lyon, Bordeaux), quelle stratégie d\'emplacement adoptent souvent les investisseurs de rendement ?',
      options: ['Cibler les "Villes de report" (ou 1ère et 2ème couronnes bien desservies) : des villes limitrophes où les prix sont plus bas mais qui bénéficient de la dynamique d\'emplois de la grande métropole voisine', 'Acheter des forêts', 'Abandonner l\'immobilier', 'Construire de nouvelles villes'],
      correct: 0, rationale: 'Le locataire chassé par les prix du centre de Bordeaux ira s\'installer dans une ville limitrophe accessible en Tramway. La demande y explose.' },
    { q: 'Faut-il toujours investir "à côté de chez soi" (dans sa propre rue) pour plus de sécurité et par facilité de gestion ?',
      options: ['Non, il faut séparer l\'affectif de l\'investissement. Si sa propre zone d\'habitation est un mauvais marché (bulle spéculative ou zone en déclin), un bon investisseur ira acheter plus loin pour trouver l\'équilibre rendement/risque', 'Oui, c\'est obligatoire pour la loi', 'Oui, pour ne pas payer l\'agence immobilière', 'C\'est la seule façon d\'éviter les impôts'],
      correct: 0, rationale: 'Le "biais de familiarité" pousse à acheter ce qu\'on connaît. Mais un actif financier s\'achète avec des chiffres, pas avec des émotions.' },
    { q: 'Lors du ciblage macro-économique d\'une ville (l\'emplacement large), quel indicateur "chiffré" est le plus rassurant pour un investisseur ?',
      options: ['Le nombre de cimetières', 'Un solde migratoire et démographique largement POSITIF (la population de la ville augmente de 1 à 2% par an) couplé à des créations nettes d\'emplois', 'La baisse continue de la population (tranquillité)', 'Le climat chaud'],
      correct: 1, rationale: 'Si la ville gagne des habitants (nouveaux salariés, étudiants), il faudra les loger. La pression locative sera forte, garantissant le succès de votre investissement.' },
    { q: '(Challenge) En urbanisme, comment s\'informer légalement sur l\'avenir de l\'emplacement exact d\'un immeuble (pour éviter qu\'une usine ne se construise devant sa fenêtre) ?',
      options: ['Il faut payer un détective', 'En demandant au voisin', 'En cherchant sur Google Earth', 'En consultant le PLU (Plan Local d\'Urbanisme) à la mairie, qui détaille les futures zones à urbaniser, les droits de construction, et les futurs projets de voirie de la parcelle ciblée'],
      correct: 3, rationale: 'Le PLU est public et gratuit. C\'est le livre de la "loi" du terrain. Un investisseur averti ne signe rien sans avoir vérifié le PLU.' },
    { q: '(Challenge) Lors du choix de l\'emplacement (hyper-centre vs banlieue éloignée), on fait souvent face au classique "Arbitrage Patrimonial vs Rendement". Quel est ce concept ?',
      options: ['Acheter en centre-ville (Emplacement Premium) coûte très cher : la rentabilité immédiate sera très mauvaise (Cash-flow négatif), MAIS la liquidité, la sécurité anti-impayés et la plus-value à terme seront maximales. L\'inverse est vrai pour la banlieue', 'L\'hyper-centre est réservé aux riches', 'Les agences refusent de vendre en banlieue', 'L\'État interdit le rendement en centre-ville'],
      correct: 0, rationale: 'L\'investisseur doit choisir son camp. Sécurité patrimoniale (Paris 8ème) ou Haut Rendement risqué (petite ville ouvrière de province).' },
  ],
};
