/* Questions de la semaine 22. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w22-d0': [
    { q: 'En économie et en finance, qu\'est-ce que "le marché" de manière générale ?',
      options: ['Uniquement l\'endroit où s\'échangent des actions d\'entreprises', 'Le lieu fictif ou physique où se rencontrent l\'offre (les vendeurs) et la demande (les acheteurs) pour échanger des biens, des services ou des capitaux', 'Un algorithme de l\'État pour fixer les prix', 'Une taxe sur les échanges commerciaux'],
      correct: 1, rationale: 'Qu\'il s\'agisse du marché de l\'immobilier, du marché de l\'art ou du marché boursier, la logique est toujours la confrontation entre ceux qui veulent vendre et ceux qui veulent acheter.' },
    { q: 'Quelle est la règle d\'or (la loi fondamentale) qui détermine les prix sur un marché libre ?',
      options: ['Si la demande dépasse l\'offre (beaucoup d\'acheteurs, peu de vendeurs), les prix ont tendance à BAISSER', 'Les prix sont toujours fixés par les banques centrales', 'Si l\'offre dépasse la demande (beaucoup de vendeurs, peu d\'acheteurs), les prix ont tendance à MONTER', 'Si la demande dépasse l\'offre (beaucoup d\'acheteurs pour un bien rare), les prix ont tendance à MONTER'],
      correct: 3, rationale: 'C\'est la loi de l\'offre et de la demande. La rareté face à l\'abondance d\'acheteurs fait exploser les prix.' },
    { q: 'En finance, qu\'est-ce que le "Marché Primaire" ?',
      options: ['Le marché de l\'occasion où les investisseurs s\'échangent des titres entre eux', 'Le marché du neuf : c\'est là que les nouveaux titres (actions, obligations) sont émis et vendus pour la première fois pour financer directement l\'entreprise', 'Le marché des matières premières (or, pétrole)', 'Le marché des particuliers uniquement'],
      correct: 1, rationale: 'Lors d\'une Introduction en Bourse (IPO), l\'entreprise lève de l\'argent sur le marché primaire.' },
    { q: 'Par opposition, qu\'est-ce que le "Marché Secondaire" ?',
      options: ['C\'est le marché de l\'occasion (la Bourse) : les investisseurs s\'y échangent des titres déjà existants. Cet argent ne va pas à l\'entreprise, il va au vendeur', 'Le marché des produits dérivés et spéculatifs', 'Un marché réservé aux professionnels', 'Le marché où les entreprises vendent leurs dettes'],
      correct: 0, rationale: 'Quand vous achetez une action Total sur votre PEA, vous donnez votre argent à un autre investisseur qui vous vend sa part, Total ne touche rien.' },
    { q: 'Sur un marché boursier, qui sont les acteurs appelés "Les Ours" (Bears) ?',
      options: ['Les investisseurs débutants qui se font piéger', 'Les investisseurs pessimistes qui anticipent une BAISSE du marché (et qui vendent ou parient à la baisse)', 'Les investisseurs optimistes qui achètent massivement', 'Les régulateurs du marché (comme l\'AMF)'],
      correct: 1, rationale: 'L\'ours attaque en donnant un coup de patte vers le bas. Un "Bear market" est un marché en chute.' },
    { q: 'À l\'inverse, qui sont "Les Taureaux" (Bulls) sur le marché ?',
      options: ['Les fonds vautours qui rachètent les entreprises en faillite', 'Les banques centrales qui injectent de la monnaie', 'Les investisseurs optimistes qui anticipent une HAUSSE du marché (et qui achètent)', 'Les entreprises qui dominent le marché'],
      correct: 2, rationale: 'Le taureau attaque de bas en haut avec ses cornes. Un "Bull market" est une période de forte croissance économique et boursière.' },
    { q: 'En théorie financière, qu\'est-ce que "l\'Efficience" du marché ?',
      options: ['Le fait qu\'un marché soit toujours ouvert 24h/24', 'La théorie selon laquelle les prix du marché reflètent instantanément et parfaitement TOUTES les informations disponibles (il serait donc impossible de "battre le marché" de façon prévisible)', 'Le fait que les prix soient toujours à la hausse', 'La rapidité des ordinateurs pour passer un ordre'],
      correct: 1, rationale: 'Si une entreprise annonce d\'excellents résultats, l\'efficience du marché fera que le prix de son action s\'ajustera à la hausse en quelques millisecondes.' },
    { q: 'Que caractérise un marché très "Liquide" ?',
      options: ['L\'impossibilité de vendre sans perdre d\'argent', 'Un marché où il y a énormément d\'acheteurs et de vendeurs, permettant d\'exécuter des transactions volumineuses presque instantanément sans faire décaler le prix', 'Un marché basé uniquement sur l\'eau ou le pétrole', 'Un marché réservé aux devises étrangères (Forex)'],
      correct: 1, rationale: 'Le marché des actions américaines est ultra-liquide. Le marché de l\'immobilier de campagne est très illiquide (peu d\'acheteurs).' },
    { q: '(Challenge) Qu\'est-ce qu\'une "Bulle spéculative" sur un marché ?',
      options: ['Un marché qui stagne pendant très longtemps', 'L\'effondrement immédiat des prix suite à une rumeur', 'La vente massive et paniquée d\'un actif par les investisseurs', 'Une hausse artificielle, démesurée et irrationnelle des prix d\'un actif, déconnectée de sa valeur fondamentale (réelle), souvent suivie d\'un krach (l\'éclatement de la bulle)'],
      correct: 3, rationale: 'La bulle internet des années 2000 ou la crise des subprimes de 2008 en sont les parfaits exemples. L\'euphorie (FOMO) prend le pas sur la raison.' },
    { q: '(Challenge) Que mesure la "Capitalisation boursière" d\'une entreprise sur le marché ?',
      options: ['Le nombre total d\'actions multiplié par le cours actuel de l\'action. Cela donne le "poids" ou la valeur totale de l\'entreprise sur le marché', 'Le montant d\'argent liquide dont dispose l\'entreprise à la banque', 'Le bénéfice net annuel de l\'entreprise', 'Le chiffre d\'affaires divisé par le nombre de salariés'],
      correct: 0, rationale: 'Si une entreprise a 10 millions d\'actions valant 10 € chacune, sa capitalisation boursière est de 100 millions d\'euros.' },
  ],
  'w22-d1': [
    { q: 'En fiscalité, qu\'est-ce qu\'une plus-value immobilière ?',
      options: ['Les travaux réalisés pour améliorer le bien', 'La différence positive entre le prix de VENTE d\'un bien immobilier et son prix d\'ACHAT initial (plus-value = enrichissement lors de la cession)', 'Le rendement des loyers sur une année', 'L\'augmentation de la taxe foncière'],
      correct: 1, rationale: 'Si vous achetez 150 000 € et revendez 200 000 €, votre plus-value brute est de 50 000 €.' },
    { q: 'La vente de quel type de bien immobilier est TOTALEMENT et EXCLUSIVEMENT EXONÉRÉE d\'impôt sur la plus-value (le vendeur ne paie aucun impôt sur ses gains) ?',
      options: ['La vente de la Résidence PRINCIPALE de l\'occupant', 'La vente d\'une résidence secondaire', 'La vente d\'un local commercial', 'La revente d\'un investissement locatif'],
      correct: 0, rationale: 'C\'est la niche fiscale préférée des Français. Tous les gains réalisés lors de la revente de la maison où l\'on vit habituellement sont nets d\'impôts.' },
    { q: 'Pour les autres biens (résidences secondaires, locatif), quel est le TAUX GLOBAL de taxation appliqué sur la plus-value immobilière nette (hors surtaxe éventuelle) ?',
      options: ['10 %', '19 %', '36,2 % (soit 19 % d\'Impôt sur le Revenu + 17,2 % de Prélèvements Sociaux)', '50 %'],
      correct: 2, rationale: 'C\'est un taux lourd, qui explique pourquoi le législateur a prévu des abattements avec le temps.' },
    { q: 'Heureusement, la loi prévoit des "abattements pour durée de détention". Plus on garde le bien longtemps, moins on paie d\'impôts. Au bout de combien d\'années d\'appartenance l\'IMPÔT SUR LE REVENU (les 19 %) est-il totalement effacé ?',
      options: ['5 ans', '15 ans', '22 ans', '30 ans'],
      correct: 2, rationale: 'Si vous revendez un appartement locatif 23 ans après l\'avoir acheté, la part "Impôt sur le revenu" de la plus-value tombera à zéro.' },
    { q: 'Le délai est cependant plus long pour effacer les fameux PRÉLÈVEMENTS SOCIAUX (17,2 %). Au bout de combien d\'années la plus-value est-elle ENFIN totalement nette de toute fiscalité (IR + Prélèvements) ?',
      options: ['10 ans', '22 ans', '30 ans', '40 ans'],
      correct: 2, rationale: 'Entre la 22ème et la 30ème année de détention, vous ne payez plus d\'impôt sur le revenu, mais vous payez encore un reliquat (dégressif) de CSG/CRDS.' },
    { q: 'Lors du calcul de la plus-value, le vendeur a le droit de DÉDUIRE des frais de son prix de Vente. Lesquels ?',
      options: ['La taxe foncière des 5 dernières années', 'Les frais de déménagement', 'Les factures de son électricité', 'Les frais liés à la vente, justifiés (ex : la commission de l\'agence immobilière si elle est à la charge du vendeur, les diagnostics obligatoires)'],
      correct: 3, rationale: 'On calcule l\'impôt sur l\'enrichissement RÉEL. L\'argent qui part à l\'agence n\'est pas de la plus-value pour le vendeur.' },
    { q: 'Inversement, le vendeur peut légalement MAJORER son prix d\'ACHAT initial (ce qui fait baisser mathématiquement la plus-value). Que peut-il ajouter ?',
      options: ['Les frais de notaire payés à l\'époque (soit au réel, soit avec un forfait de 7,5 %)', 'L\'inflation depuis la date d\'achat', 'Les impôts locaux payés', 'Les loyers impayés par ses locataires'],
      correct: 0, rationale: 'Acheter 100 000€ vous a coûté en réalité 107 500€ avec le notaire. Le fisc accepte d\'utiliser ce chiffre plus élevé comme base de calcul.' },
    { q: 'Toujours pour majorer ce prix d\'achat, si le bien est détenu depuis plus de 5 ans, quel forfait très avantageux le fisc accorde-t-il automatiquement pour les "TRAVAUX" sans exiger aucune facture ?',
      options: ['Une déduction forfaitaire de 10 000 €', 'Un forfait de 15 % du prix d\'achat', 'Le fisc exige 100 % des factures, le forfait n\'existe pas', 'Un forfait de 50 %'],
      correct: 1, rationale: 'Même si vous n\'avez fait que 1 000 € de peinture, si la maison valait 200 000 €, le fisc accepte de majorer votre prix d\'achat de 30 000 € au titre des travaux (après 5 ans de détention).' },
    { q: '(Challenge) Un impôt supplémentaire (la surtaxe) s\'applique parfois aux "grosses" plus-values immobilières. Quel est le seuil de déclenchement de cette surtaxe ?',
      options: ['S\'applique lorsque la plus-value NETTE IMPOSABLE dépasse 50 000 €', 'S\'applique pour tous les biens de plus de 1 million d\'euros', 'S\'applique lorsque la plus-value NETTE IMPOSABLE dépasse 10 000 €', 'Cette surtaxe a été supprimée en 2020'],
      correct: 0, rationale: 'Cette surtaxe varie de 2 % à 6 %. Elle vient lourdement frapper les vendeurs réalisant des plus-values éclairs.' },
    { q: '(Challenge) Il existe une petite exemption (niche fiscale) pour la revente d\'un bien immobilier QUI N\'EST PAS une résidence principale (ex: locatif). Quelle est la condition principale ?',
      options: ['Il faut vendre à un membre de sa famille', 'Il faut que le prix de cession (le prix de vente) soit inférieur à 15 000 € (par co-indivisaire)', 'Il faut le donner à une association après 5 ans', 'L\'exonération est accordée si l\'on vend pour payer l\'EHPAD'],
      correct: 1, rationale: 'Si vous revendez un tout petit box ou une place de parking de banlieue à 12 000 €, le fisc ne vous embêtera pas avec la plus-value. C\'est une mesure de simplification.' },
  ],
  'w22-d2': [
    { q: 'Quel est le principal argument fiscal (la "carotte") qui pousse les contribuables à ouvrir et alimenter un Plan d\'Épargne Retraite (PER) Individuel pendant leur vie active ?',
      options: ['Les sommes versées (versements volontaires) peuvent être DÉDUITES des revenus imposables du foyer, générant ainsi une baisse immédiate de l\'Impôt sur le Revenu', 'Les versements annulent le paiement de la taxe foncière', 'L\'État verse une prime de 1 000 € à l\'ouverture', 'Les fonds sont garantis sans risque de perte'],
      correct: 0, rationale: 'C\'est le moteur du PER. En plaçant de l\'argent pour vos vieux jours, l\'État vous récompense en effaçant l\'impôt que vous auriez dû payer sur cette somme.' },
    { q: 'La puissance de l\'économie d\'impôt générée par le PER dépend directement d\'un critère précis du contribuable. Lequel ?',
      options: ['Son âge', 'Le nombre d\'enfants qu\'il a', 'Sa Tranche Marginale d\'Imposition (TMI) : plus il est imposé fortement (ex: 30%, 41%, 45%), plus son économie d\'impôt sera importante', 'Son lieu de résidence'],
      correct: 2, rationale: 'Déduire 1 000 € de son revenu rapporte 410 € d\'économie d\'impôt à un cadre taxé à 41 %. Le même versement ne rapportera que 110 € d\'économie à un employé taxé à 11 %.' },
    { q: 'Cette déduction fiscale à l\'entrée est-elle illimitée ?',
      options: ['Non. Chaque année, la loi fixe un "Plafond d\'Épargne Retraite" (souvent égal à 10 % des revenus professionnels de l\'année précédente), au-delà duquel les versements ne sont plus déductibles', 'Oui, on peut effacer 100 % de ses impôts sans limite', 'Non, elle est bloquée à 500 € par an', 'Elle est limitée à la moitié du salaire'],
      correct: 0, rationale: 'Ce plafond est calculé par le fisc et inscrit sur votre avis d\'imposition.' },
    { q: 'Un contribuable n\'a pas versé d\'argent sur son PER pendant 3 ans. Que deviennent ses "plafonds" de déduction non utilisés ?',
      options: ['Ils sont définitivement perdus', 'Ils sont donnés à son employeur', 'Ils sont annulés l\'année d\'après', 'La loi permet de "reporter" (de conserver) ses plafonds non utilisés des 3 ANNÉES PRÉCÉDENTES, ce qui permet de faire un versement déductible massif la 4ème année'],
      correct: 3, rationale: 'C\'est un levier d\'optimisation fabuleux (le rachat de plafonds) suite à la revente d\'une entreprise ou la perception d\'une grosse prime.' },
    { q: 'Un couple (marié ou pacsé avec déclaration commune) peut-il optimiser son PER si l\'un des conjoints a un gros salaire et l\'autre ne travaille pas ?',
      options: ['Oui. Le couple a le droit de "Mutualiser" ses plafonds : le conjoint qui a le gros salaire peut utiliser le plafond d\'épargne retraite de son conjoint inactif pour augmenter massivement ses propres déductions', 'Non, la déduction est strictement personnelle et non transférable', 'Oui, mais seulement à la retraite', 'Uniquement s\'ils ont plus de 3 enfants'],
      correct: 0, rationale: 'Il faut cocher une case spécifique sur la déclaration de revenus. C\'est l\'un des rares cas de solidarité fiscale purement à la carte.' },
    { q: 'Est-on OBLIGÉ de déduire fiscalement ses versements sur le PER à l\'entrée ?',
      options: ['Oui, le système est bloqué', 'Uniquement pour les versements supérieurs à 10 000 €', 'Non. Il est possible d\'opter (de choisir) de NE PAS déduire ses versements à l\'entrée. Dans ce cas, on bénéficiera d\'une fiscalité très allégée à la sortie', 'Non, on peut demander à la mairie d\'annuler'],
      correct: 2, rationale: 'Cette option est vitale pour les contribuables non imposables (TMI 0 %). Déduire n\'aurait aucun intérêt pour eux, et ils se feraient taxer à la sortie. En renonçant à la déduction, ils protègent leur capital à la retraite.' },
    { q: 'Si un contribuable a dépassé le plafond de déduction de 10 000 € de la loi sur les "Niches Fiscales" (avec une aide à domicile et du Pinel), peut-il encore défiscaliser avec le PER ?',
      options: ['Non, le plafond est absolu', 'La banque bloque le versement', 'Oui. L\'avantage fiscal du PER (déduction de revenu) est totalement HORS du plafonnement global des niches fiscales de 10 000 €', 'Uniquement avec l\'accord des impôts'],
      correct: 2, rationale: 'Le PER est une "déduction d\'assiette" et non une réduction d\'impôt. Un riche contribuable peut donc cumuler le max des niches fiscales ET le PER.' },
    { q: 'Pour les indépendants (Travailleurs Non Salariés - TNS), le plafond de déduction du PER obéit à une règle spéciale héritée de l\'ancien contrat Madelin. Laquelle ?',
      options: ['Ils n\'ont le droit qu\'à 5 %', 'Leur plafond spécifique est souvent beaucoup plus HAUT que celui des salariés (pouvant atteindre plus de 80 000 € pour les gros revenus) afin de compenser la faiblesse de leur retraite de base', 'Ils ne peuvent déduire que la TVA', 'Ils sont obligés de verser 10 000 € par an'],
      correct: 1, rationale: 'L\'État sait qu\'un médecin libéral ou un artisan aura une petite retraite de la Sécu, il leur donne donc des moyens colossaux pour s\'en constituer une eux-mêmes avec le PER.' },
    { q: '(Challenge) Sur quel feuillet/case précis de la déclaration de revenus le contribuable doit-il indiquer ses versements volontaires déductibles ?',
      options: ['Sur la déclaration des plus-values (2074)', 'Dans les charges déductibles de la déclaration 2042 (cases 6NS, 6NT...)', 'Dans les revenus fonciers (2044)', 'Il n\'y a rien à déclarer, la banque s\'en occupe'],
      correct: 1, rationale: 'Bien que parfois pré-rempli par la banque, c\'est au contribuable de vérifier et d\'ajuster s\'il veut, par exemple, utiliser la mutualisation des plafonds du conjoint.' },
    { q: '(Challenge) Un enfant MINEUR est rattaché au foyer fiscal de ses parents. Peut-on ouvrir un PER à son nom et profiter d\'un avantage fiscal ?',
      options: ['OUI. Les parents pouvaient lui ouvrir un PER, verser dessus, et déduire cet argent de LEURS propres impôts (en utilisant le plafond plancher de l\'enfant). Attention, cette pratique est supprimée pour les mineurs depuis 2024', 'Non, un mineur ne paie pas d\'impôts', 'Oui, mais l\'argent est confisqué à sa majorité', 'OUI, c\'est un droit imprescriptible et toujours valable aujourd\'hui'],
      correct: 0, rationale: 'Le "PER Mineur" permettait aux parents très riches d\'effacer leurs impôts tout en bloquant un apport pour l\'achat de la résidence principale du jeune à 25 ans. La Loi de Finances 2024 a fermé cette niche (remplacée par le Plan d\'Épargne Avenir Climat).' },
  ],
  'w22-d3': [
    { q: 'En gestion de patrimoine, qu\'est-ce que le "Pacte Tontinier" (ou clause de tontine) ?',
      options: ['Une clause qui annule le mariage', 'Une taxe immobilière pour les résidences secondaires', 'L\'obligation de prêter de l\'argent à sa famille', 'Un contrat par lequel plusieurs personnes achètent un bien en commun, avec une clause prévoyant qu\'au décès de l\'un, sa part appartiendra rétroactivement aux survivants'],
      correct: 3, rationale: 'C\'est une "loterie" sur la vie. Le dernier vivant se retrouve propriétaire de l\'intégralité du bien, comme s\'il l\'avait acheté seul depuis le premier jour.' },
    { q: 'Quelle est l\'immense différence juridique entre l\'achat en "Indivision" et l\'achat avec un "Pacte Tontinier" lors d\'un décès ?',
      options: ['Il n\'y a aucune différence', 'Dans l\'indivision, la part du défunt va à ses héritiers (enfants). Avec la tontine, le bien sort totalement de la succession : la part va au survivant de la tontine, et les héritiers du défunt n\'ont droit à RIEN sur ce bien', 'La tontine oblige à vendre la maison', 'L\'indivision empêche les impôts, la tontine les double'],
      correct: 1, rationale: 'C\'est une arme patrimoniale lourde, souvent utilisée pour empêcher la belle-famille ou les enfants d\'une première union de mettre le survivant à la porte.' },
    { q: 'Une condition essentielle doit être respectée pour que la tontine soit juridiquement valable et ne soit pas requalifiée en "donation déguisée". Laquelle ?',
      options: ['L\'aléa : les acheteurs doivent avoir une espérance de vie similaire (âge et état de santé proches) au moment de l\'achat, et financer le bien proportionnellement. Personne ne doit savoir à l\'avance qui survivra à l\'autre', 'Ils doivent être mariés depuis 10 ans', 'Il faut payer l\'immeuble comptant', 'L\'un des acheteurs doit être malade'],
      correct: 0, rationale: 'Si un homme de 90 ans achète en tontine avec une femme de 30 ans, le juge (et le fisc) annulera la tontine pour fraude, car le résultat de la loterie est connu d\'avance.' },
    { q: 'Pour quel type de couples l\'achat immobilier avec Pacte Tontinier est-il LE PLUS stratégique (et souvent utilisé par les notaires) ?',
      options: ['Pour les couples mariés avec des enfants communs', 'Pour les concubins (union libre) sans enfant, car la loi ne les protège absolument pas lors d\'un décès (ils sont considérés comme des étrangers)', 'Pour des frères et sœurs qui se détestent', 'Pour un parent et son enfant'],
      correct: 1, rationale: 'Le concubin n\'hérite de rien par la loi. La tontine lui garantit de garder la pleine propriété de la maison de son couple si l\'autre décède (bien que la fiscalité reste un problème).' },
    { q: 'Pendant la vie du contrat (avant le décès), que se passe-t-il si les deux acheteurs en tontine se fâchent et que l\'un veut vendre sa part ?',
      options: ['Il peut vendre à qui il veut, quand il veut', 'Il force la vente au tribunal', 'Le pacte tontinier bloque tout : il faut obligatoirement L\'ACCORD UNANIME des deux parties pour vendre le bien ou annuler la tontine. Nul ne peut forcer l\'autre à vendre (contrairement à l\'indivision)', 'L\'État saisit la maison'],
      correct: 2, rationale: 'C\'est le grand danger de la tontine (la "prison" de la tontine). Si le couple se déchire, impossible de provoquer le partage en justice comme on le fait en indivision.' },
    { q: 'Fiscalement, que doit payer le CONCUBIN survivant (non marié, non pacsé) lorsqu\'il "récupère" la part de la maison de son concubin décédé grâce à la tontine (pour une résidence valant plus de 76 000 €) ?',
      options: ['Les droits de mutation (succession) à titre gratuit au taux ravageur de 60 % (car ils sont étrangers pour le fisc) sur la valeur de la part transmise', 'Il ne paie aucun impôt', 'Il paie la Flat Tax à 30 %', 'Il est exonéré par la mairie'],
      correct: 0, rationale: 'La tontine règle le problème juridique (il devient seul propriétaire), mais ne règle pas le problème fiscal. S\'il n\'a pas les liquidités pour payer les 60% d\'impôts, il devra vendre la maison.' },
    { q: 'Il existe cependant une EXCEPTION FISCALE où la part tontinière récupérée n\'est soumise qu\'aux droits de vente (droits de mutation à titre onéreux, environ 5,8 %) et non aux 60 %. Quelle est la condition ?',
      options: ['Il faut habiter à la campagne', 'Il faut que ce soit la résidence principale des acquéreurs ET que la valeur totale du bien au moment du décès soit INFÉRIEURE à 76 000 €', 'Il faut le demander poliment', 'Il faut que le bien soit neuf'],
      correct: 1, rationale: 'Autant dire qu\'aujourd\'hui, presque aucune maison ou appartement principal ne vaut moins de 76 000 €. Cette "faveur" fiscale est devenue obsolète avec l\'inflation immobilière.' },
    { q: 'Le survivant récupère la maison. Que peuvent faire les enfants (issus d\'une première union) du défunt, qui se voient totalement privés de cette maison dans l\'héritage ?',
      options: ['Ils peuvent annuler la vente', 'Ils exigent un loyer au survivant', 'Rien du tout. La tontine est un contrat aléatoire (et non une libéralité/donation). Le bien est réputé n\'avoir jamais appartenu au défunt, donc les enfants n\'ont aucun droit de réserve héréditaire dessus (sauf à prouver la fraude)', 'L\'État leur verse une compensation'],
      correct: 2, rationale: 'C\'est la violence du pacte tontinier. Juridiquement, on efface le défunt de l\'historique d\'achat. Il n\'y a donc rien à léguer à ses héritiers sur ce bien.' },
    { q: '(Challenge) Un couple marié a-t-il un intérêt à utiliser le pacte tontinier pour l\'achat de sa résidence principale ?',
      options: ['C\'est obligatoire pour tous les mariages', 'Très rarement. Le droit du mariage (régimes matrimoniaux, droit viager au logement, exonération fiscale totale) offre déjà des protections très puissantes, sans l\'inconvénient du blocage absolu de la tontine', 'Oui, pour ne pas payer la taxe foncière', 'Seulement s\'ils ont plus de 10 enfants'],
      correct: 1, rationale: 'La tontine est un outil "palliatif" pour ceux que la loi ne protège pas (concubins).' },
    { q: '(Challenge) Quelle est l\'alternative juridique souple (très prisée des concubins) permettant de se protéger mutuellement, d\'éviter l\'indivision, MAIS sans s\'enfermer dans le blocage absolu de la tontine ?',
      options: ['La SCI (Société Civile Immobilière) avec des clauses statutaires spécifiques (démembrement croisé de parts)', 'L\'achat en cash', 'Le contrat de mariage sous séparation', 'La location à vie'],
      correct: 0, rationale: 'La SCI permet de contourner les dangers de l\'indivision, d\'organiser la gérance, et de sécuriser le survivant, avec beaucoup plus de souplesse en cas de revente que la rigide tontine.' },
  ],
  'w22-d4': [
    { q: 'Que signifie le sigle PNO dans le domaine de l\'assurance immobilière ?',
      options: ['Prêt Non Opposable', 'Propriétaire Non Occupant', 'Provision Nationale Obligatoire', 'Prime aux Nouveaux Ouvriers'],
      correct: 1, rationale: 'Il s\'agit de l\'assurance destinée à l\'investisseur immobilier, c\'est-à-dire le propriétaire qui n\'habite pas dans le logement qu\'il possède (qu\'il le loue ou le laisse vide).' },
    { q: 'La souscription à une assurance PNO est-elle légalement OBLIGATOIRE ?',
      options: ['Oui, systématiquement pour toutes les maisons', 'Non, c\'est toujours facultatif', 'Uniquement pour les locations Airbnb', 'Oui, l\'assurance Responsabilité Civile PNO est OBLIGATOIRE (depuis la loi Alur de 2014) si le bien immobilier est situé dans une copropriété (immeuble)'],
      correct: 3, rationale: 'L\'objectif de la loi Alur est de s\'assurer que si un dégât des eaux venant de votre appartement ravage l\'immeuble, il y a bien un assureur solvable pour indemniser la copropriété.' },
    { q: 'Pourquoi un propriétaire bailleur doit-il souscrire une PNO alors que le locataire a déjà l\'obligation de s\'assurer de son côté (MRH locataire) ?',
      options: ['Pour payer l\'assureur en double', 'Pour pallier les défauts de l\'assurance du locataire (défaut d\'assurance, vacance entre deux locataires) et couvrir la responsabilité propre du propriétaire (ex: vice de construction du bâtiment)', 'C\'est exigé par le syndic pour payer les charges', 'Pour que le locataire ne puisse pas partir'],
      correct: 1, rationale: 'Le locataire est responsable de l\'entretien courant, mais si le tuyau de la colonne montante éclate dans le mur (vice du bâtiment), c\'est la responsabilité (et la PNO) du propriétaire qui interviendra, pas l\'assurance du locataire.' },
    { q: 'Que se passe-t-il (grâce à la PNO) lors d\'une période de "Vacance Locative" (l\'appartement est vide pendant 2 mois) s\'il y a un incendie d\'origine électrique ?',
      options: ['La mairie prend en charge', 'Le dernier locataire est tenu responsable', 'En l\'absence de locataire (et de son assurance), c\'est la PNO du propriétaire qui intervient pour indemniser la destruction du bien', 'Personne ne paie'],
      correct: 2, rationale: 'Sans PNO, un propriétaire qui a un bien inoccupé entre deux baux est totalement à découvert (sans assurance). S\'il y a le feu, il perd 100% de son capital.' },
    { q: 'Que couvre la garantie "Recours des voisins et des tiers", toujours présente dans un contrat PNO ?',
      options: ['Le tapage nocturne du locataire', 'La réparation du vol de la voiture du voisin', 'Les dommages (corporels ou matériels) causés aux voisins ou à l\'immeuble par un sinistre ayant pris naissance dans le logement de l\'investisseur et dont ce dernier est reconnu responsable', 'Le paiement des loyers des voisins'],
      correct: 2, rationale: 'Un dégât des eaux chez vous peut ruiner les 3 étages du dessous. L\'assurance PNO couvrira les milliers d\'euros de dommages chez les tiers.' },
    { q: 'La prime d\'assurance PNO (qui coûte environ 80 à 150 € par an pour un appartement standard) offre un excellent avantage FISCAL. Lequel ?',
      options: ['La prime est intégralement déductible des revenus fonciers (location nue au régime réel) ou des revenus BIC (location meublée), diminuant ainsi l\'impôt de l\'investisseur', 'Elle annule la CSG', 'Elle permet de doubler le loyer', 'Elle donne droit à un crédit d\'impôt de 500 €'],
      correct: 0, rationale: 'Comme les travaux ou les intérêts d\'emprunt, la cotisation PNO est une charge d\'exploitation reconnue par le fisc.' },
    { q: 'En assurance, qu\'est-ce que le "Trouble de jouissance" que la PNO peut couvrir pour le propriétaire ?',
      options: ['Le locataire qui s\'ennuie', 'L\'incapacité du propriétaire à louer son bien suite à un sinistre lourd (incendie). La PNO peut compenser, pendant quelques mois, la perte des loyers due à l\'inhabitabilité du logement', 'Le fait que l\'immeuble n\'ait pas de balcon', 'Une amende de la mairie'],
      correct: 1, rationale: 'Si la toiture s\'envole, le locataire cesse de payer le loyer. La garantie "perte de loyers suite à sinistre" sauve la trésorerie de l\'investisseur qui doit toujours rembourser son crédit.' },
    { q: 'Attention à ne pas confondre : la PNO de base vous rembourse-t-elle les impayés si le locataire décide simplement de ne plus payer son loyer le 1er du mois ?',
      options: ['Oui, toujours', 'Non. La PNO est une assurance "Dégâts/Responsabilité". Pour être couvert contre le locataire mauvais payeur, il faut un autre contrat spécifique : la GLI (Garantie Loyers Impayés) ou la garantie Visale', 'Uniquement après 6 mois', 'Oui, c\'est la même chose'],
      correct: 1, rationale: 'C\'est une confusion fréquente. La PNO couvre l\'eau et le feu, la GLI couvre le portefeuille et la procédure d\'expulsion.' },
    { q: '(Challenge) Un locataire part, il a cassé le lavabo. Il refuse de réparer. Que fait l\'assurance PNO classique ?',
      options: ['Elle rembourse le lavabo neuf', 'Elle paie un avocat', 'Elle n\'intervient généralement PAS pour les dégradations locatives ordinaires. C\'est le rôle du "Dépôt de garantie" (la caution) du locataire de financer cela', 'Elle annule le bail'],
      correct: 2, rationale: 'L\'assurance habitation ne gère pas le mauvais entretien ou le vandalisme locatif léger (sauf si une extension "dégradations immobilières" est souscrite).' },
    { q: '(Challenge) Qu\'est-ce que la "Convention IRSI" (qui a grandement simplifié la vie des PNO en cas de dégât des eaux dans un immeuble) ?',
      options: ['Une taxe sur l\'eau', 'Une norme électrique', 'Une convention entre assureurs qui désigne un seul "assureur gestionnaire" (souvent celui de l\'occupant, même si c\'est le locataire) pour organiser l\'expertise et indemniser directement les dommages mineurs (< 5000 €), évitant au propriétaire PNO des mois de bataille juridique', 'Un syndicat de locataires'],
      correct: 2, rationale: 'Avant l\'IRSI, le locataire, le propriétaire et le syndic de l\'immeuble se renvoyaient la responsabilité pendant un an. Maintenant, un seul assureur gère et paie, puis ils font leurs comptes entre eux.' },
  ],
  'w22-d5': [
    { q: 'Que signifie le statut "LMNP", très prisé par les investisseurs immobiliers pour son extraordinaire fiscalité ?',
      options: ['Logement Moderne Nouveau Propriétaire', 'Loueur en Meublé Non Professionnel', 'Location Mensuelle Négociée à Paris', 'Loueur du Marché National Privé'],
      correct: 1, rationale: 'C\'est le statut des propriétaires louant un bien fourni avec un mobilier complet (lit, plaques, vaisselle).' },
    { q: 'La "magie" du LMNP s\'exprime lorsqu\'on opte pour quel régime de déclaration aux impôts ?',
      options: ['Le régime Micro-Bic (forfait de 50 %)', 'Le régime des Revenus Fonciers', 'Le Régime Réel (avec l\'Amortissement)', 'Le régime agricole'],
      correct: 2, rationale: 'Le micro-BIC est simple, mais le Régime Réel est l\'outil qui permet aux investisseurs de gommer 100 % de leurs impôts immobiliers pendant des décennies.' },
    { q: 'En comptabilité LMNP, qu\'est-ce que "l\'Amortissement" ?',
      options: ['La baisse du loyer avec le temps', 'Le mécanisme qui permet de déduire chaque année, comme une charge, une fraction de la valeur d\'achat du bien immobilier (constatant son "usure" théorique dans le temps), ce qui fait mécaniquement baisser les bénéfices taxables', 'L\'annulation de la taxe foncière', 'Le remboursement accéléré du crédit à la banque'],
      correct: 1, rationale: 'L\'État considère qu\'un bâtiment s\'use. Même si vous n\'avez pas sorti de cash cette année, votre comptable inscrit cette "usure" (l\'amortissement) en face de vos loyers, ce qui annule votre bénéfice fiscal.' },
    { q: 'Peut-on "amortir" le TERRAIN sur lequel est construit l\'immeuble LMNP ?',
      options: ['Oui, le terrain s\'amortit sur 10 ans', 'Uniquement si on y plante des arbres', 'Non. La règle comptable stricte impose que la part correspondant au Terrain (souvent évaluée entre 10% et 20% de la valeur de l\'achat) ne s\'use jamais. Elle ne peut donc pas être amortie', 'Oui, tout est amortissable'],
      correct: 2, rationale: 'Le comptable devra séparer le prix d\'achat en "bâti" (amortissable) et en "foncier/terrain" (non amortissable).' },
    { q: 'Qu\'est-ce que la méthode "Par composants" exigée par le fisc pour amortir le bien LMNP ?',
      options: ['On amortit différemment le salon et la cuisine', 'L\'obligation de diviser la valeur du bâtiment en éléments distincts ayant des durées de vie différentes (Gros œuvre sur 50 ans, Toiture sur 25 ans, Électricité sur 15 ans) pour calculer l\'amortissement précis de chaque année', 'Une liste des locataires', 'C\'est le fait d\'acheter les meubles chez Ikea'],
      correct: 1, rationale: 'Cette complexité comptable rend l\'appel à un expert-comptable (spécialiste LMNP) quasiment indispensable.' },
    { q: 'Au régime Réel LMNP, que se passe-t-il avec les "Meubles" achetés pour garnir l\'appartement ?',
      options: ['Ils sont taxés à la TVA', 'On ne peut pas les déduire', 'Ils sont également amortis, mais sur une durée beaucoup plus courte (souvent entre 5 et 10 ans), ce qui génère de grosses charges déductibles les premières années', 'L\'État les rachète'],
      correct: 2, rationale: 'Le canapé, la table ou le lit perdent très vite leur valeur. Leur amortissement rapide est un énorme accélérateur pour baisser vos impôts dès la 1ère année.' },
    { q: 'Une règle LIMITATIVE et fondamentale bloque l\'amortissement. Laquelle ?',
      options: ['L\'amortissement est interdit après 5 ans', 'L\'amortissement comptable ne peut JAMAIS créer ou aggraver un DÉFICIT fiscal. Il ne peut faire baisser le résultat que jusqu\'à zéro (impôt à zéro). La part d\'amortissement non utilisée est alors mise en réserve (reportable indéfiniment)', 'Il ne s\'applique qu\'aux résidences principales', 'L\'amortissement fait augmenter la taxe d\'habitation'],
      correct: 1, rationale: 'Si loyers (100) - charges directes (60) = 40. Vous ne pouvez utiliser que 40 d\'amortissement cette année (pour arriver à 0 d\'impôt). S\'il vous restait 30 d\'amortissement, vous le gardez "en stock" pour l\'année prochaine.' },
    { q: 'Outre l\'amortissement, que pouvez-vous déduire (en régime Réel LMNP) pour faire baisser vos loyers imposables ?',
      options: ['Rien d\'autre', 'Uniquement les factures d\'eau', 'Absolument TOUTES les dépenses (charges) payées dans l\'année dans l\'intérêt de la location : intérêts du crédit, frais de notaire de l\'achat, taxe foncière, assurance PNO, frais de l\'expert-comptable, syndic, etc.', 'Les amendes de la route'],
      correct: 2, rationale: 'L\'addition des "Charges au réel" ET de "l\'Amortissement" est l\'arme fatale qui permet à l\'investisseur LMNP de ne payer aucun impôt sur ses loyers pendant 10 à 20 ans.' },
    { q: '(Challenge) Lors de la revente du bien après 10 ans, comment agit l\'anomalie fiscale incroyable du statut LMNP (qui le rend bien plus avantageux que le LMP ou l\'entreprise classique) ?',
      options: ['La revente est interdite', 'Sur le calcul de la plus-value de revente, les amortissements déduits pendant 10 ans NE SONT PAS réintégrés dans la valeur comptable. Le particulier bénéficie du régime ultra-favorable des plus-values privées (avec l\'abattement pour durée de détention)', 'L\'État demande le remboursement des impôts non payés', 'La plus-value est taxée à 60 %'],
      correct: 1, rationale: 'En comptabilité d\'entreprise classique, si vous avez amorti un bien à zéro, le revendre 100 000€ crée 100 000€ de plus-value très taxée. En LMNP, l\'État "oublie" (pour l\'instant) vos amortissements. Vous avez défiscalisé à l\'entrée ET à la sortie.' },
    { q: '(Challenge) Pourquoi est-il extrêmement conseillé d\'adhérer à un OGA (Organisme de Gestion Agréé) et de confier sa déclaration LMNP Réel à un expert-comptable ?',
      options: ['Pour avoir un diplôme', 'Sans OGA, vos bénéfices LMNP étaient, jusqu\'à récemment, majorés arbitrairement de 10 à 25 % par les impôts. De plus, 2/3 des frais comptables (jusqu\'à 915 €) sont remboursés sous forme de réduction directe d\'impôt', 'C\'est obligatoire pour louer', 'Pour annuler la taxe foncière'],
      correct: 1, rationale: 'L\'État vous paie quasiment votre expert-comptable pour s\'assurer que vos (très complexes) liasses fiscales LMNP sont correctement remplies.' },
  ],
};
