/* Questions de la semaine 11. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w11-d0': [
    { q: 'Quel adage résume le concept de diversification ?',
      options: ['"Un tien vaut mieux que deux tu l\'auras"', '"Qui ne tente rien n\'a rien"', '"L\'argent ne fait pas le bonheur"', '"Il ne faut pas mettre tous ses œufs dans le même panier"'],
      correct: 3, rationale: 'Répartir les risques évite la ruine globale.' },
    { q: 'Quel est l\'objectif de la diversification ?',
      options: ['Payer plus de frais de courtage', 'Rendre la déclaration d\'impôts plus complexe', 'Optimiser le ratio "Rendement / Risque" en réduisant l\'exposition à un risque spécifique sans sacrifier le rendement global', 'Devenir actionnaire majoritaire'],
      correct: 2, rationale: 'La chute d\'un actif a moins d\'impact.' },
    { q: 'Qu\'est-ce que la diversification "sectorielle" ?',
      options: ['Répartir ses investissements dans différents secteurs économiques (Santé, Tech, Énergie)', 'Acheter uniquement des actions de la Tech', 'Acheter des biens immobiliers dans la même rue', 'Changer de banque tous les ans'],
      correct: 0, rationale: 'Si l\'énergie chute, la santé ou la tech maintiennent le navire.' },
    { q: 'Qu\'est-ce qu\'une diversification par "classes d\'actifs" ?',
      options: ['Séparer son argent entre soi et ses enfants', 'Répartir le capital entre actions, obligations, immobilier et fonds euros', 'Ouvrir plusieurs assurances-vie identiques', 'Répartir son salaire sur le mois'],
      correct: 1, rationale: 'Ces classes ne réagissent pas pareil aux crises.' },
    { q: 'Qu\'apporte la diversification "géographique" ?',
      options: ['Des frais de douane', 'L\'obligation de payer des impôts partout', 'La protection contre le risque spécifique d\'une zone (ex: crise en Europe) en s\'exposant à la croissance d\'autres régions', 'Une baisse garantie du rendement'],
      correct: 2, rationale: 'Ne pas avoir 100% en France.' },
    { q: 'Les actifs idéaux à combiner doivent être "décorrélés". Cela signifie :',
      options: ['Leurs prix n\'ont pas tendance à bouger dans le même sens et avec la même force au même moment', 'Ils sont vendus par des courtiers ennemis', 'Ils coûtent le même prix', 'Ils sont exonérés de taxes'],
      correct: 0, rationale: 'Si deux actifs chutent ensemble, ils ne diversifient rien.' },
    { q: 'Quel produit financier est le "roi" de la diversification accessible ?',
      options: ['L\'ETF (Tracker) mondial (MSCI World)', 'L\'achat d\'un parking', 'Le Livret A', 'Le marché de l\'art'],
      correct: 0, rationale: 'Diversification mondiale instantanée sur plus de 1500 entreprises.' },
    { q: 'Qu\'est-ce que la "diversification d\'enveloppes fiscales" ?',
      options: ['Mettre son argent liquide dans plusieurs enveloppes physiques', 'Avoir différentes structures (PEA, Assurance-vie, livrets) pour cumuler leurs atouts et faire face aux changements de loi', 'C\'est de la fraude fiscale', 'L\'ouverture de comptes off-shore'],
      correct: 1, rationale: 'On se protège contre l\'instabilité fiscale.' },
    { q: '(Challenge) Quel est le risque de la "sur-diversification" ?',
      options: ['C\'est impossible', 'Elle rend les impôts incalculables', 'Elle oblige à embaucher un comptable', 'On dilue les meilleurs rendements, on multiplie les frais et le portefeuille devient illisible, sans que le risque ne baisse davantage'],
      correct: 3, rationale: 'Ajouter 200 actions n\'apporte presque plus de sécurité.' },
    { q: '(Challenge) L\'investissement programmé mensuel (DCA) est une forme de diversification. Laquelle ?',
      options: ['Sectorielle', 'Bancaire', 'Temporelle (lisser le risque du point d\'entrée)', 'En devises'],
      correct: 2, rationale: 'Acheter tous les mois permet de lisser la volatilité.' },
  ],
  'w11-d1': [
    { q: 'Comment appelle-t-on communément le Prélèvement Forfaitaire Unique (PFU) ?',
      options: ['La Flat Tax', 'La taxe Tobin', 'L\'impôt sur la fortune', 'Le prélèvement libératoire'],
      correct: 0, rationale: '"Flat" (plat/fixe) car ce taux est le même pour tout le monde, quels que soient les revenus, par opposition au barème "progressif" de l\'impôt sur le revenu.' },
    { q: 'Quel est le taux global (total) du PFU appliqué sur les revenus du capital ?',
      options: ['12,8 %', '17,2 %', '30 %', '41 %'],
      correct: 2, rationale: 'Le PFU ponctionne un peu moins d\'un tiers des gains financiers des contribuables.' },
    { q: 'De quoi est précisément composé ce taux de 30 % ?',
      options: ['30 % d\'impôt sur le revenu pur', '12,8 % d\'Impôt sur le Revenu (IR) et 17,2 % de Prélèvements Sociaux (CSG/CRDS)', '15 % pour l\'État et 15 % pour la Sécurité Sociale', '30 % de prélèvements sociaux'],
      correct: 1, rationale: 'Cette décomposition est importante car, dans certains cas d\'exonération d\'impôt sur le revenu, seule la part de 17,2 % s\'applique.' },
    { q: 'Lequel de ces revenus N\'EST PAS soumis au PFU de 30 % ?',
      options: ['Les dividendes d\'actions', 'Les intérêts d\'un compte à terme ou d\'un livret non réglementé', 'Les revenus fonciers (les loyers de l\'immobilier classique)', 'Les plus-values sur les cryptomonnaies (Bitcoin)'],
      correct: 2, rationale: 'La grande réforme de 2018 (Macron) a sorti le "capital mobilier" (l\'argent, la bourse) du barème progressif, mais l\'immobilier classique reste lourdement taxé au barème progressif de l\'impôt sur le revenu (TMI) + 17,2 %.' },
    { q: 'Le PFU (30 %) est le régime appliqué par défaut par l\'administration. Le contribuable a-t-il le droit de refuser le PFU ?',
      options: ['Non, c\'est obligatoire pour tous', 'Oui, il peut "opter" (lors de sa déclaration) pour l\'imposition au barème progressif de l\'impôt sur le revenu si cela est plus avantageux pour lui', 'Uniquement s\'il est au chômage', 'Seulement la première année de son investissement'],
      correct: 1, rationale: 'C\'est une option expresse. Il faut cocher la case 2OP sur sa déclaration de revenus pour renoncer au PFU et repasser à l\'ancien système.' },
    { q: 'Dans quel cas précis avez-vous INTÉRÊT à cocher la case pour renoncer au PFU (30 %) et choisir le barème progressif ?',
      options: ['Si vous êtes très riche (TMI à 45 %)', 'Si votre Tranche Marginale d\'Imposition (TMI) est de 0 % (non imposable) ou de 11 %', 'Si votre TMI est de 30 %', 'Le PFU est toujours meilleur dans 100 % des cas'],
      correct: 1, rationale: 'Si votre TMI est de 0 %, avec le barème, vous paierez 0 % (IR) + 17,2 % (PS) = 17,2 %. C\'est beaucoup plus avantageux que de laisser le fisc vous prendre les 30 % de la Flat Tax ! Même avec une TMI à 11 %, le total (28,2 %) reste inférieur à 30 %.' },
    { q: 'Si vous choisissez d\'opter pour le barème progressif (pour payer moins de 30 % d\'impôts sur un petit compte à terme), cette option s\'applique-t-elle uniquement à ce compte ?',
      options: ['Oui, on peut choisir produit par produit', 'Non, c\'est une option GLOBALE. Elle s\'appliquera à TOUS vos revenus du capital de l\'année (dividendes, plus-values boursières, assurance-vie).', 'Oui, mais seulement dans la même banque', 'L\'option n\'est valable que pour l\'immobilier'],
      correct: 1, rationale: 'Attention aux effets de bord. Si vous avez un gros dividende d\'un côté et un petit intérêt de l\'autre, renoncer au PFU appliquera votre TMI sur la totalité de vos gains de l\'année.' },
    { q: 'Les livrets d\'épargne réglementés (Livret A, LDDS, LEP) sont-ils soumis au PFU de 30 % ?',
      options: ['Oui, comme les autres comptes', 'Seulement sur la partie qui dépasse le plafond', 'Non, ils sont totalement exonérés d\'impôt sur le revenu ET de prélèvements sociaux (0 % de fiscalité)', 'Ils sont soumis uniquement aux 12,8 % d\'IR'],
      correct: 2, rationale: 'Les livrets réglementés par l\'État restent hors du champ de la fiscalité sur le capital.' },
    { q: '(Challenge) Lors de la perception d\'un DIVIDENDE, si l\'on opte pour le barème progressif (au lieu du PFU de 30 %), on bénéficie d\'un mécanisme fiscal très avantageux avant le calcul de l\'impôt. Lequel ?',
      options: ['L\'exonération totale du dividende', 'Un abattement de 40 % sur le montant du dividende', 'Un crédit d\'impôt de 1000 €', 'Le remboursement des frais de bourse'],
      correct: 1, rationale: 'Pour éviter la double imposition (l\'entreprise a déjà payé l\'impôt sur les sociétés), si vous choisissez le barème progressif, le fisc ne taxe que 60 % de votre dividende. (Attention : cet abattement de 40 % ne s\'applique pas si vous restez au PFU).' },
    { q: '(Challenge) Un autre avantage de cocher l\'option pour le barème progressif (renoncer au PFU) concerne la "CSG" (partie des prélèvements sociaux). Quel est cet avantage ?',
      options: ['La CSG est annulée', 'Une partie de la CSG (6,8 %) devient déductible de vos revenus imposables l\'année suivante', 'La CSG est plafonnée à 50 €', 'La CSG est payée par la banque'],
      correct: 1, rationale: 'Avec la Flat Tax à 30 %, aucune déduction de CSG n\'est possible. Avec le barème, une fraction de la CSG payée vient faire baisser vos revenus imposables l\'année d\'après.' },
  ],
  'w11-d2': [
    { q: 'Auparavant gérée par le RSI, qui gère aujourd\'hui la retraite de base des artisans et commerçants (TNS - Travailleurs Non Salariés) ?',
      options: ['La Mutualité Sociale Agricole (MSA)', 'La Sécurité Sociale des Indépendants (SSI), désormais totalement intégrée au régime général (l\'Assurance Retraite / Carsat)', 'Les mutuelles privées', 'La Caisse des Dépôts'],
      correct: 1, rationale: 'Pour simplifier la vie des indépendants et corriger les bugs historiques du RSI, leur système de retraite a été adossé au même organisme que celui des salariés du privé.' },
    { q: 'Le calcul de la retraite de BASE des artisans et commerçants est-il très différent de celui des salariés du secteur privé ?',
      options: ['Il est calculé sur le dernier chiffre d\'affaires', 'Depuis 1973, il est "aligné" sur celui des salariés : calculé sur la moyenne des 25 meilleures années, avec un taux plein à 50 %', 'Ils n\'ont pas de retraite de base', 'C\'est un forfait de 800 € pour tous'],
      correct: 1, rationale: 'Un commerçant fonctionne selon les mêmes règles (trimestres, décote, surcote) qu\'un salarié pour la partie "base".' },
    { q: 'Pour les Professions Libérales (médecins, avocats, architectes, consultants), l\'organisation est différente. Qui gère leur régime de base ?',
      options: ['La SSI', 'La CNAVPL (Caisse Nationale d\'Assurance Vieillesse des Professions Libérales), qui fonctionne par points dès la retraite de base', 'L\'Urssaf', 'La banque de France'],
      correct: 1, rationale: 'Contrairement aux commerçants, les libéraux ont un régime de base spécifique qui convertit directement leurs cotisations en points, et non en trimestres/moyenne de salaires.' },
    { q: 'Pour valider ses 4 trimestres de retraite dans l\'année, un indépendant (hors micro-entreprise) doit-il travailler toute l\'année ?',
      options: ['Oui, 12 mois obligatoires', 'Non, la validation des trimestres dépend uniquement du montant des cotisations versées (et donc du revenu déclaré), soit environ l\'équivalent de 600 heures de SMIC pour 4 trimestres', 'Non, l\'inscription au registre du commerce suffit', 'Les indépendants ne comptent pas en trimestres'],
      correct: 1, rationale: 'S\'il gagne assez en 3 mois, il valide ses 4 trimestres. Mais s\'il fait une mauvaise année sans revenu, il risque de ne valider aucun trimestre (sauf dispositif de cotisation minimale).' },
    { q: 'Qu\'est-ce que le statut "Assimilé Salarié" (ex: Gérant minoritaire de SARL, ou Président de SAS) pour la retraite ?',
      options: ['Il ne paie aucune charge', 'Le dirigeant est rattaché directement au régime de retraite des salariés (CNAV et Agirc-Arrco) et cotise exactement comme un salarié, mais sans avoir droit au chômage', 'Il est considéré comme un fonctionnaire', 'Il doit obligatoirement prendre une retraite privée'],
      correct: 1, rationale: 'Beaucoup d\'entrepreneurs choisissent la SAS plutôt que la SARL précisément pour bénéficier de cette meilleure protection retraite (Agirc-Arrco), bien que les cotisations soient beaucoup plus chères.' },
    { q: 'Pourquoi la pension de retraite finale d\'un indépendant (artisan, commerçant) est-elle souvent beaucoup plus faible que celle d\'un salarié ?',
      options: ['Parce que l\'État les pénalise', 'Parce que, pour maximiser leur revenu immédiat, beaucoup se versent de faibles rémunérations ou privilégient les dividendes (qui ne créent aucun droit à la retraite)', 'Parce qu\'ils partent à 55 ans', 'Parce que la loi limite leur pension à 1 000 €'],
      correct: 1, rationale: 'Le TNS paie moins de charges sociales qu\'un salarié. Revers de la médaille : en cotisant moins, il achète moins de droits, et sa retraite finale sera faible.' },
    { q: 'Quel dispositif (remplacé par le PER) a été créé pour permettre aux indépendants de se constituer une retraite par capitalisation tout en baissant leurs impôts ?',
      options: ['Le Livret A', 'Le contrat Madelin (aujourd\'hui intégré au PER Individuel)', 'L\'Assurance-vie classique', 'Le compte courant d\'associé'],
      correct: 1, rationale: 'L\'État encourage les TNS à épargner eux-mêmes pour leur retraite en leur permettant de déduire ces versements de leur bénéfice imposable.' },
    { q: 'Comment est validée la retraite d\'un Micro-entrepreneur (auto-entrepreneur) ?',
      options: ['Automatiquement, 4 trimestres par an', 'Il doit générer un chiffre d\'affaires minimum obligatoire (fixé par décret selon l\'activité) pour valider 1, 2, 3 ou 4 trimestres dans l\'année', 'Il ne cotise pas pour la retraite', 'La validation se fait selon le nombre de factures'],
      correct: 1, rationale: 'Un auto-entrepreneur qui déclare 0 € de chiffre d\'affaires n\'acquiert strictement aucun droit à la retraite cette année-là.' },
    { q: '(Challenge) Un artisan au réel (non micro-entrepreneur) réalise une année catastrophique avec un déficit (revenu à zéro). Va-t-il valider des trimestres de retraite cette année-là ?',
      options: ['Non, 0 revenu = 0 trimestre', 'Oui, car il est soumis à une "cotisation minimale obligatoire" pour la retraite de base, ce qui lui permet de valider 3 trimestres, même s\'il n\'a rien gagné', 'Oui, il valide 4 trimestres par solidarité', 'Il est radié de la Sécurité sociale'],
      correct: 1, rationale: 'C\'est le filet de sécurité des indépendants. Même en déficit, ils paient une cotisation plancher (environ 900€/an) pour ne pas créer de "trous" irrécupérables dans leur carrière.' },
    { q: '(Challenge) Qu\'est-ce que l\'obligation de déclaration du "Conjoint Collaborateur" ?',
      options: ['Le conjoint doit travailler gratuitement', 'Si le conjoint de l\'indépendant participe régulièrement à l\'activité, il doit obligatoirement opter pour un statut officiel (collaborateur, salarié, associé) afin de lui garantir la constitution de ses propres droits à la retraite', 'Le droit de partager le même bureau', 'L\'obligation de divorcer en cas de faillite'],
      correct: 1, rationale: 'La loi de 2022 est venue durcir cette règle pour éviter le drame des épouses/époux d\'artisans qui travaillaient toute leur vie sans percevoir de salaire, et se retrouvaient à 65 ans avec 0 € de retraite personnelle.' },
  ],
  'w11-d3': [
    { q: 'En droit de la transmission, qu\'est-ce qu\'un "présent d\'usage" ?',
      options: ['Un don fait à un étranger', 'Un cadeau de la vie courante fait à l\'occasion d\'un événement précis (Noël, anniversaire, mariage), dont la valeur est raisonnable et proportionnée à la fortune de celui qui l\'offre', 'Le fait de prêter sa maison pour les vacances', 'Un synonyme de l\'héritage'],
      correct: 1, rationale: 'Offrir une belle montre pour les 18 ans d\'un enfant ou un chèque pour un mariage constitue un présent d\'usage, tant que cela ne ruine pas le donateur.' },
    { q: 'Quelle est la grande différence fiscale entre un "présent d\'usage" et un "don manuel" (une donation d\'argent classique) ?',
      options: ['Le présent d\'usage est taxé à 20 %', 'Le présent d\'usage échappe totalement à l\'impôt (0 droit de donation) ET n\'a pas besoin d\'être déclaré à l\'administration fiscale', 'Il n\'y a aucune différence', 'Le présent d\'usage doit être fait devant notaire'],
      correct: 1, rationale: 'C\'est un acte de la vie sociale toléré par le fisc, qui ne le considère pas comme une véritable "donation" entamant le patrimoine.' },
    { q: 'Une grand-mère fait un chèque de 5 000 € à sa petite-fille. Quelle est la condition absolue pour que cela soit qualifié de "présent d\'usage" et non de donation ?',
      options: ['Que le chèque soit fait en janvier', 'Que le cadeau soit lié à un événement particulier (Noël, réussite au bac) ET que la somme (5 000 €) ne soit pas excessive par rapport au patrimoine et aux revenus de la grand-mère', 'Que la grand-mère ait moins de 80 ans', 'Que la petite-fille soit mineure'],
      correct: 1, rationale: 'Si la grand-mère a 1 million d\'euros de patrimoine, 5 000 € est un présent d\'usage. Si elle n\'a que 6 000 € sur son compte, c\'est une donation taxable.' },
    { q: 'Un père offre 20 000 € à son fils un mardi du mois d\'octobre "juste comme ça, pour lui faire plaisir". Est-ce un présent d\'usage ?',
      options: ['Oui, c\'est de l\'amour paternel', 'Non, car il n\'y a pas d\'événement particulier justifiant l\'usage (ni anniversaire, ni mariage). Ce sera requalifié en "don manuel" (soumis à l\'abattement ou à taxation)', 'Oui, car le montant est inférieur à 100 000 €', 'Non, car c\'est un mardi'],
      correct: 1, rationale: 'Le présent d\'usage exige impérativement une occasion familiale ou sociale (Noël, naissance, diplôme).' },
    { q: 'Le présent d\'usage est-il "rapportable" à la succession (doit-on le déduire de la part d\'héritage de l\'enfant lors du décès du parent) ?',
      options: ['Oui, toujours', 'Non, comme ce n\'est pas considéré comme une donation, le présent d\'usage ne sera jamais reconstitué ni réévalué lors du décès. C\'est définitivement acquis', 'Uniquement s\'il a pris de la valeur', 'Oui, avec des intérêts'],
      correct: 1, rationale: 'C\'est un avantage énorme pour éviter les conflits. Si vous offrez un présent d\'usage (ex: de l\'argent investi ensuite en bourse), les frères et sœurs ne pourront jamais rien réclamer dessus au moment de votre décès.' },
    { q: 'Sous quelle forme matérielle peut-on faire un présent d\'usage ?',
      options: ['Uniquement en espèces (billets)', 'Uniquement par chèque', 'Sous toute forme : virement bancaire, chèque, voiture, œuvre d\'art, montre de luxe, bijou', 'Uniquement avec des objets d\'occasion'],
      correct: 2, rationale: 'Offrir une voiture d\'occasion (5 000 €) pour l\'obtention du permis de conduire à son enfant est l\'exemple typique du présent d\'usage.' },
    { q: 'Que se passe-t-il si l\'administration fiscale contrôle le donateur, estime que le cadeau de 30 000 € était totalement démesuré (le donateur ne gagnant que le SMIC), et refuse la qualification de "présent d\'usage" ?',
      options: ['Le donataire (celui qui a reçu) va en prison', 'L\'argent est saisi par l\'État', 'Le fisc opère une requalification en "don manuel", exigeant la déclaration rétroactive, et potentiellement le paiement de droits de donation avec pénalités de retard', 'L\'État rembourse le cadeau'],
      correct: 2, rationale: 'Le fisc vérifie l\'appauvrissement. S\'il y a appauvrissement manifeste, c\'est une avance sur l\'héritage, donc soumis aux règles fiscales strictes.' },
    { q: 'Est-il possible de faire un présent d\'usage à un tiers (une personne qui n\'est pas de la famille, par exemple le fils d\'un ami) ?',
      options: ['Non, c\'est réservé aux enfants', 'Oui, les présents d\'usage ne sont pas restreints au cercle familial, à condition de respecter les mêmes règles d\'événement (ex: mariage de l\'ami) et de proportionnalité', 'Uniquement avec l\'accord d\'un juge', 'Oui, mais la limite est fixée à 50 €'],
      correct: 1, rationale: 'Offrir un beau cadeau de mariage à un ami ou un collègue est un présent d\'usage classique, échappant ainsi aux 60% d\'impôts sur les dons entre tiers.' },
    { q: '(Challenge) Dans le Code Civil ou le Code Général des Impôts, existe-t-il un plafond mathématique strict (un montant précis ou un pourcentage du revenu) définissant ce qui est proportionné pour un présent d\'usage ?',
      options: ['Oui, le plafond est fixé à 2 % du patrimoine', 'Oui, le plafond est de 3 000 € par an', 'Non, il n\'y a aucune règle mathématique ni plafond chiffré dans la loi. L\'appréciation se fait au cas par cas par les juges, "au jour de la remise" du cadeau', 'Oui, le plafond est fixé à 1 mois de salaire'],
      correct: 2, rationale: 'En général, les fiscalistes conseillent de ne pas dépasser 1 à 2 % du patrimoine global, mais la jurisprudence reste la seule maître. Ce qui est proportionné pour le PDG de LVMH ne l\'est pas pour un employé.' },
    { q: '(Challenge) Un père donne un "présent d\'usage" important (mais validé) à son fils. Son autre fille, jalouse, pourra-t-elle intenter une "Action en réduction" lors du décès en arguant que ce cadeau a entamé sa réserve héréditaire ?',
      options: ['Oui, la jalousie est un motif légal', 'Non. Le présent d\'usage n\'étant pas une donation, il n\'est pas réuni fictivement à la succession et ne peut donc pas amputer la réserve héréditaire de la sœur', 'Oui, le présent d\'usage ampute toujours la réserve', 'Oui, mais seulement si elle n\'a pas reçu le même cadeau'],
      correct: 1, rationale: 'C\'est la beauté du présent d\'usage. Il sort totalement des radars de la liquidation de la succession.' },
  ],
  'w11-d4': [
    { q: 'Qu\'est-ce que l\'assurance dépendance ?',
      options: ['Une assurance qui protège contre l\'addiction à l\'alcool ou au tabac', 'Un contrat de prévoyance qui garantit le versement d\'une rente viagère (ou d\'un capital) si l\'assuré perd son autonomie (vieillesse, maladie) et ne peut plus accomplir seul les actes de la vie quotidienne', 'Une assurance pour les enfants qui vivent chez leurs parents', 'Une complémentaire santé (mutuelle) classique'],
      correct: 1, rationale: 'Les frais liés à la dépendance (EHPAD, aide à domicile) coûtent très cher (2 500 à 3 500 €/mois). La retraite seule suffit rarement à les payer.' },
    { q: 'Sur quelle grille nationale (officielle) les assureurs français se basent-ils généralement pour évaluer le niveau de dépendance de l\'assuré ?',
      options: ['La grille de l\'OMS', 'La grille AGGIR (Autonomie Gérontologie Groupes Iso-Ressources)', 'Le barème des impôts', 'Le test de QI'],
      correct: 1, rationale: 'C\'est le barème national. Il évalue les capacités à se lever, s\'habiller, se laver, manger, etc.' },
    { q: 'Dans cette grille AGGIR, quels niveaux (GIR) correspondent à la "dépendance lourde ou totale" (qui déclenche la totalité de la rente de l\'assurance) ?',
      options: ['Les GIR 5 et 6', 'Les GIR 1 et 2', 'Le GIR 10', 'Uniquement le GIR 0'],
      correct: 1, rationale: 'La grille va de 6 (personne autonome) à 1 (dépendance totale nécessitant une présence continue). Les assurances se déclenchent souvent à partir du GIR 2, 3 ou 4 selon les options choisies.' },
    { q: 'Autour de quel âge est-il généralement recommandé (et financièrement optimal) de souscrire une assurance dépendance ?',
      options: ['À 20 ans', 'Entre 50 et 65 ans', 'À 85 ans (dès les premiers signes de maladie)', 'Le jour de la mise en EHPAD'],
      correct: 1, rationale: 'Avant 50 ans, le risque est très lointain. Après 70/75 ans, les primes d\'assurance deviennent prohibitives (très chères) ou l\'assureur refuse de vous couvrir pour raisons de santé.' },
    { q: 'Avant de vous accepter, que vous demande systématiquement l\'assureur lors de la souscription d\'un contrat dépendance ?',
      options: ['De fournir le nom de vos enfants', 'De passer le permis de conduire', 'De remplir un questionnaire médical (ou questionnaire de santé)', 'De faire une prise de sang mensuelle'],
      correct: 2, rationale: 'L\'assureur évalue le risque. Si vous avez déjà été diagnostiqué avec un début de maladie d\'Alzheimer, l\'assureur refusera catégoriquement la souscription.' },
    { q: 'Qu\'est-ce que le "délai de franchise" dans un contrat dépendance ?',
      options: ['Le temps pendant lequel on peut annuler le contrat', 'La période (ex : 90 jours) qui suit la constatation médicale de la dépendance et pendant laquelle la rente n\'est pas encore versée', 'La somme à payer au médecin expert', 'Le droit de changer d\'assurance'],
      correct: 1, rationale: 'L\'assureur veut s\'assurer que la perte d\'autonomie est définitive et non transitoire (ex: cloué au lit après une chute, mais qui guérira).' },
    { q: 'En matière de dépendance, qu\'est-ce que l\'APA (Allocation Personnalisée d\'Autonomie) ?',
      options: ['Une option de l\'assurance privée', 'Une aide financière versée par le Département (l\'État/Conseil Départemental) aux personnes de plus de 60 ans en perte d\'autonomie (GIR 1 à 4), permettant de payer l\'EHPAD ou l\'aide à domicile', 'Une pension de réversion', 'Le salaire des infirmières'],
      correct: 1, rationale: 'L\'APA est l\'aide publique. L\'assurance dépendance (privée) est un contrat que vous souscrivez pour venir compléter cette APA, qui est souvent insuffisante pour couvrir tous les frais.' },
    { q: 'Que se passe-t-il avec l\'assurance dépendance dite "à fonds perdus" (les contrats de prévoyance purs) si l\'assuré décède à 90 ans sans avoir jamais été dépendant ?',
      options: ['L\'assureur rembourse 100 % des cotisations aux héritiers', 'Les cotisations versées pendant des années sont conservées par l\'assureur. Ni l\'assuré ni ses héritiers ne récupèrent l\'argent', 'La rente est versée aux enfants à vie', 'L\'État saisit l\'assurance'],
      correct: 1, rationale: 'C\'est le principe de la mutualisation et de la prévoyance (comme l\'assurance auto : si vous n\'avez pas d\'accident, vous ne récupérez pas l\'argent). Les bien-portants paient pour les dépendants.' },
    { q: '(Challenge) Pour éviter cette frustration de "payer pour rien" (les fonds perdus), les assureurs ont développé des contrats de dépendance "mixtes" (ou vie/dépendance). Comment fonctionnent-ils ?',
      options: ['Ils s\'associent avec l\'assurance auto', 'Ce sont des contrats d\'Assurance-Vie : si vous êtes dépendant, vous touchez une rente viagère piochée sur votre capital. Si vous décédez sans être dépendant, le capital accumulé est transmis à vos héritiers', 'Le contrat est remboursé par la Mairie', 'On est remboursé en bons d\'achat'],
      correct: 1, rationale: 'C\'est beaucoup plus rassurant psychologiquement, car l\'argent n\'est jamais "perdu". Mais l\'effort d\'épargne initial requis est beaucoup plus important.' },
    { q: '(Challenge) Quel est le principal danger ou reproche fait aujourd\'hui aux contrats d\'assurance dépendance traditionnels (prévoyance) face à l\'inflation ?',
      options: ['Les rentes sont indexées sur le Bitcoin', 'Bien que les tarifs augmentent avec l\'âge et l\'inflation de la santé, le montant de la rente fixée lors de la souscription (ex : 1 000 €/mois) perd de son pouvoir d\'achat au fil des 20 années d\'attente', 'Les contrats sont annulés à 80 ans', 'Les assureurs obligent l\'assuré à choisir son EHPAD'],
      correct: 1, rationale: '1 000 € paient aujourd\'hui un bon tiers d\'un EHPAD. Dans 20 ans, ces mêmes 1 000 € ne couvriront peut-être plus qu\'un quart des frais, alors que le retraité aura payé de plus en plus cher sa cotisation.' },
  ],
  'w11-d5': [
    { q: 'Dans un projet d\'achat immobilier, qu\'appelle-t-on "l\'apport personnel" ?',
      options: ['Le salaire net mensuel de l\'emprunteur', 'La somme d\'argent (l\'épargne) dont l\'acheteur dispose déjà et qu\'il va injecter de sa poche dans le financement de son achat', 'L\'aide financière de la banque', 'La commission de l\'agent immobilier'],
      correct: 1, rationale: 'C\'est le "cash" que vous mettez sur la table. Le reste du prix sera financé par le crédit bancaire.' },
    { q: 'Aujourd\'hui (et particulièrement depuis le resserrement du crédit), pourquoi l\'apport personnel est-il quasi obligatoire pour obtenir un prêt ?',
      options: ['Parce que la loi l\'impose stricto sensu', 'Parce que les banques veulent que l\'emprunteur couvre lui-même a minima les "frais annexes" (frais de notaire, frais de garantie), afin de ne prêter de l\'argent que sur la valeur réelle (les murs) du bien', 'Pour payer les agios', 'Pour ouvrir un compte courant obligatoirement'],
      correct: 1, rationale: 'Si la banque saisit et revend la maison, elle récupère le prix de la maison, mais pas les taxes du notaire. Elle refuse donc de les financer et demande à l\'acheteur de les payer avec son apport.' },
    { q: 'Quel pourcentage minimum du prix d\'achat les banques exigent-elles "classiquement" en guise d\'apport personnel pour valider un dossier ?',
      options: ['1 %', '10 % (soit l\'équivalent des frais de notaire et de garantie)', '50 %', '100 % (la banque ne prête pas)'],
      correct: 1, rationale: 'Pour une maison à 200 000 €, il vous faudra au moins 15 000 à 20 000 € d\'apport pour couvrir les "frais dans le vide" (notaire, courtier, frais de dossier, caution).' },
    { q: 'Lequel de ces montages est interdit pour constituer votre "apport personnel" ?',
      options: ['Casser son Livret A', 'Demander une donation à ses parents', 'Contracter un prêt à la consommation (crédit conso) pour faire croire à la banque qu\'on a de l\'épargne', 'Utiliser la participation de son entreprise'],
      correct: 2, rationale: 'L\'apport doit être "sain" (de l\'épargne pure). Contracter un prêt conso augmente votre taux d\'endettement, fausse le dossier et est souvent un motif de refus ferme par la banque.' },
    { q: 'Quel est l\'impact d\'un apport personnel TRES FORT (ex: 20 % ou 30 % du prix du bien) sur la proposition de la banque ?',
      options: ['La banque refuse de prêter car elle ne gagnera pas assez', 'L\'emprunteur obtient un moins bon taux d\'intérêt', 'Le risque pour la banque étant minime, elle proposera un meilleur taux d\'intérêt (une "décote") et l\'emprunteur baissera ses mensualités et son coût total du crédit', 'L\'emprunteur paie plus de frais de dossier'],
      correct: 2, rationale: 'Plus vous mettez d\'apport, moins la banque prend de risques (LTV - Loan To Value faible). Elle vous "récompense" avec un taux préférentiel.' },
    { q: 'Qu\'appelle-t-on un financement "à 110 %" ?',
      options: ['Un crédit où l\'on paie 10 % d\'intérêts', 'Un crédit qui finance le bien (100 %) ET l\'agence immobilière (10 %)', 'Un crédit qui finance la totalité du prix du bien (100 %) PLUS les frais de notaire/garantie (10 %), signifiant que l\'acheteur a mis ZÉRO apport', 'Un prêt accordé sur 110 ans'],
      correct: 2, rationale: 'Très courant dans les années 2010, le crédit à 110% est devenu extrêmement rare aujourd\'hui, les directives du HCSF limitant ce type de dossiers.' },
    { q: 'Dans le cadre d\'un achat par un primo-accédant, un "Prêt à Taux Zéro" (PTZ) peut-il être considéré par la banque comme faisant partie intégrante de son apport personnel ?',
      options: ['Oui, beaucoup de banques assimilent le PTZ à un apport personnel (car c\'est un prêt aidé par l\'État), ce qui facilite l\'obtention du prêt principal', 'Non, c\'est strictement interdit', 'Oui, mais seulement si le PTZ dépasse 100 000 €', 'Le PTZ annule le besoin de faire un crédit'],
      correct: 0, rationale: 'C\'est le grand coup de pouce pour les jeunes ménages sans épargne. L\'aide de l\'État rassure la banque et solidifie le plan de financement.' },
    { q: 'Comment l\'apport personnel influence-t-il la capacité d\'endettement (le plafond des 35 %) ?',
      options: ['Il l\'influence négativement (il la réduit)', 'En injectant de l\'apport, on emprunte moins de capital. La mensualité baisse, ce qui permet à des acheteurs avec de petits salaires de ne pas dépasser le plafond d\'endettement de 35 %', 'L\'apport augmente les revenus déclarés', 'Il n\'y a aucun lien entre les deux'],
      correct: 1, rationale: 'L\'apport est l\'amortisseur de l\'endettement. Si la maison est trop chère pour vos revenus, l\'unique solution pour faire passer le dossier est d\'augmenter votre apport personnel.' },
    { q: '(Challenge) Lors d\'un investissement LOCATIF pur (pour louer), de nombreux investisseurs préfèrent historiquement emprunter "sans apport" (ou à 110 %). Pourquoi ?',
      options: ['Parce que c\'est obligatoire pour la loi Pinel', 'Pour profiter au maximum de "l\'effet de levier" du crédit et maximiser la déduction fiscale des intérêts d\'emprunt sur leurs revenus fonciers (afin de payer moins d\'impôts)', 'Pour éviter de payer le notaire', 'Parce que les banques l\'imposent'],
      correct: 1, rationale: 'En locatif, les intérêts du crédit se déduisent des loyers encaissés. Plus on emprunte (sans apport), plus on paie d\'intérêts, et moins on paie d\'impôts sur les loyers (tout en gardant son épargne placée ailleurs).' },
    { q: '(Challenge) Un acheteur dispose de 50 000 € sur son compte, ce qui représente 20 % du prix de la maison qu\'il vise. Doit-il injecter la TOTALITÉ de ces 50 000 € en apport personnel ?',
      options: ['Oui, la banque exige de vider tous les comptes', 'Non, il est crucial de garder une "épargne résiduelle" (ou épargne de précaution) pour faire face aux travaux imprévus, à l\'emménagement et aux coups durs (la banque l\'exigera d\'ailleurs souvent)', 'Oui, pour éviter de payer la taxe foncière', 'Non, il est interdit de mettre plus de 10 %'],
      correct: 1, rationale: 'Mettre "all-in" dans la maison est dangereux. Une chaudière qui lâche le premier hiver sans aucune épargne de côté mène tout droit aux difficultés financières. L\'analyse du banquier veillera à vous laisser un matelas de sécurité.' },
  ],
};
