/* Questions de la semaine 5. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w5-d0': [
    { q: 'En finance, à quoi correspond la notion de "risque" ?',
      options: ['Au risque de vol physique des billets', 'À la certitude de faire faillite', 'À l\'incertitude quant à l\'évolution de la valeur d\'un placement et à la probabilité de subir une perte en capital', 'Au fait de payer trop d\'impôts'],
      correct: 2, rationale: 'Le risque mesure la possibilité que le futur soit défavorable.' },
    { q: 'Lequel de ces placements présente un risque de perte en capital "nul" (garanti) ?',
      options: ['L\'immobilier locatif', 'Le Livret A', 'Un ETF (Tracker)', 'Les cryptomonnaies'],
      correct: 1, rationale: 'L\'État français garantit que la somme placée sera toujours récupérable intégralement.' },
    { q: 'Comment appelle-t-on l\'indicateur qui mesure les fortes variations de prix d\'un actif ?',
      options: ['La liquidité', 'Le rendement brut', 'Le taux d\'intérêt', 'La volatilité'],
      correct: 3, rationale: 'Plus un actif fait le "yoyo", plus il est volatil, et donc jugé risqué à court terme.' },
    { q: 'Quel est le rapport mathématique entre le risque et le rendement espéré ?',
      options: ['Plus on souhaite un rendement élevé, plus on doit accepter de prendre des risques', 'Moins on prend de risques, plus on gagne', 'Ils sont totalement indépendants', 'Le risque annule le rendement'],
      correct: 0, rationale: 'Le rendement est la "prime" qui rémunère la prise de risque.' },
    { q: 'Qu\'est-ce que le "risque de liquidité" ?',
      options: ['Le risque de perdre son argent liquide', 'Le risque que la bourse chute', 'La difficulté ou l\'impossibilité de revendre rapidement un actif à un juste prix (ex : immobilier)', 'La baisse des taux'],
      correct: 2, rationale: 'L\'immobilier est un marché "illiquide" car le délai de vente est long.' },
    { q: 'Face au risque, quel est le comportement d\'un investisseur ayant un profil "prudent" ?',
      options: ['Il investit tout sur un seul cheval', 'Il accepte des pertes de 20% si l\'espoir de gain est fort', 'Il ne jure que par la bourse', 'Il privilégie la protection absolue du capital, quitte à accepter un rendement très faible'],
      correct: 3, rationale: 'Le prudent est réfractaire au stress financier (fonds euros et livrets).' },
    { q: 'En quoi le "temps" est-il l\'antidote naturel au risque en bourse ?',
      options: ['Sur de longues périodes (10, 15 ans), les cycles économiques lissent la volatilité et diminuent le risque de perte', 'Le temps annule les impôts', 'Le temps bloque l\'argent', 'Plus on attend, moins il y a d\'actions'],
      correct: 0, rationale: 'Le risque d\'être en perte sur les marchés mondiaux diminue drastiquement sur 15 ans.' },
    { q: 'Quelle est la meilleure technique pour diluer le risque global (risque spécifique) de son portefeuille ?',
      options: ['La concentration', 'La diversification (répartir son capital sur différents secteurs et classes d\'actifs)', 'La prière', 'L\'emprunt bancaire'],
      correct: 1, rationale: 'Si vous achetez un ETF contenant 1 500 actions, la faillite d\'une seule sera invisible.' },
    { q: '(Challenge) Lors de l\'évaluation du risque d\'un investissement, qu\'est-ce que le SRRI (échelle de 1 à 7) ?',
      options: ['Le taux d\'intérêt servi', 'Le nombre d\'années de blocage', 'L\'indicateur synthétique de risque (1 = très faible, 7 = très élevé)', 'Les frais d\'entrée'],
      correct: 2, rationale: 'Ce chiffre est exigé par les régulateurs pour éclairer votre choix.' },
    { q: '(Challenge) Vous achetez votre maison dans 18 mois. Un conseiller vous propose un fonds classé 6/7 en risque. Que penser ?',
      options: ['C\'est un excellent conseil', 'Il devrait emprunter 10 000 € de plus', 'Le risque 6/7 est sans danger', 'C\'est une hérésie totale : un horizon de 18 mois est absolument incompatible avec un tel risque de perte'],
      correct: 3, rationale: 'L\'horizon très court dicte la prudence absolue (risque 1/7).' },
  ],
  'w5-d1': [
    { q: 'Quelle est la définition fiscale d\'un crédit d\'impôt ?',
      options: ['Une avance d\'argent que l\'État fait pour acheter une voiture', 'Une somme soustraite directement de l\'impôt à payer, et si cette somme dépasse l\'impôt dû, l\'État rembourse la différence au contribuable', 'Une remise sur la TVA', 'Un prêt bancaire garanti par les impôts'],
      correct: 1, rationale: 'C\'est un mécanisme très avantageux car même une personne non imposable peut percevoir cet argent sous forme de chèque/virement du Trésor Public.' },
    { q: 'Quelle est la grande différence mathématique entre une "réduction d\'impôt" et un "crédit d\'impôt" ?',
      options: ['Le crédit d\'impôt donne lieu à un remboursement de l\'excédent, la réduction d\'impôt ne rembourse jamais l\'excédent (l\'impôt tombe à zéro et le reste est perdu)', 'La réduction d\'impôt est remboursée, pas le crédit', 'Il n\'y a aucune différence', 'Le crédit d\'impôt ne s\'applique qu\'aux entreprises'],
      correct: 0, rationale: 'Crédit = gain financier garanti. Réduction = simple effacement de l\'impôt dû.' },
    { q: 'Lequel de ces dispositifs ouvre droit à un CRÉDIT d\'impôt (et non à une déduction ou une réduction) ?',
      options: ['Investir dans la loi Pinel', 'Faire un don à la Croix-Rouge', 'Les dépenses d\'emploi d\'un salarié à domicile (femme de ménage, jardinier) ou de frais de garde de jeunes enfants', 'Les versements sur un Plan Épargne Retraite (PER)'],
      correct: 2, rationale: 'L\'État utilise le crédit d\'impôt pour encourager le travail déclaré dans ces secteurs, même pour les ménages modestes non imposables.' },
    { q: 'Monsieur X ne paie aucun impôt sur le revenu (il n\'est pas imposable). Il a pourtant engagé des frais de garde pour son bébé qui lui donnent droit à 800 € de crédit d\'impôt. Que va-t-il se passer ?',
      options: ['L\'avantage est perdu car il n\'est pas imposable', 'Il obtient une réduction de taxe foncière', 'L\'État va lui verser 800 € sur son compte bancaire', 'L\'avantage est reporté pour l\'année où il sera imposable'],
      correct: 2, rationale: 'C\'est la force du crédit d\'impôt. N\'ayant aucun impôt à gommer, l\'intégralité du crédit lui est versée (souvent à l\'été) par l\'administration fiscale.' },
    { q: 'Le crédit d\'impôt pour emploi à domicile est-il soumis au "plafonnement global des niches fiscales" ?',
      options: ['Oui, il rentre dans la limite globale des 10 000 € d\'avantages fiscaux cumulables par an et par foyer', 'Non, il est hors plafond', 'Seulement pour les revenus supérieurs à 100 000 €', 'Oui, mais le plafond est de 50 000 €'],
      correct: 0, rationale: 'Comme la majorité des avantages fiscaux (Pinel, etc.), on ne peut pas dépasser 10 000 € d\'avantages au total sur une année fiscale.' },
    { q: 'Concernant l\'emploi à domicile, à quel pourcentage de vos dépenses s\'élève généralement le crédit d\'impôt ?',
      options: ['10 %', '33 %', '50 %', '100 %'],
      correct: 2, rationale: 'Si vous payez 2 000 € dans l\'année pour une femme de ménage (salaire + cotisations sociales), l\'État vous rend 1 000 € via le crédit d\'impôt.' },
    { q: 'Qu\'est-ce que "l\'avance de 60 %" versée par le fisc mi-janvier ?',
      options: ['Un cadeau de Noël du gouvernement', 'Le remboursement anticipé de 60 % des crédits et réductions d\'impôts récurrents (ex: emploi à domicile) dont vous avez bénéficié l\'année précédente, pour éviter les décalages de trésorerie', 'Une avance sur votre futur salaire', 'Une aide réservée aux retraités'],
      correct: 1, rationale: 'Sans cette avance, il faudrait attendre l\'été pour récupérer le crédit d\'impôt, ce qui pèserait lourd sur le budget mensuel des ménages.' },
    { q: 'Comment le "prélèvement à la source" mensuel sur votre salaire prend-il en compte vos crédits d\'impôt ?',
      options: ['Le taux de prélèvement est baissé tous les mois pour inclure le crédit d\'impôt', 'Il ne les prend pas du tout en compte : le taux de prélèvement est calculé hors réductions et crédits d\'impôts. D\'où la nécessité du versement de l\'avance en janvier et de la régularisation en été', 'Le crédit d\'impôt est versé à l\'employeur', 'Le prélèvement à la source est annulé si on a un crédit d\'impôt'],
      correct: 1, rationale: 'C\'est pour cela que même avec beaucoup de crédits d\'impôt, votre salaire est amputé chaque mois, et l\'État vous rembourse l\'avantage plus tard en "one-shot".' },
    { q: '(Challenge) Un foyer a un impôt théorique calculé à 500 €. Ils ont réalisé des dépenses donnant droit à 1 200 € de CRÉDIT d\'impôt, et d\'autres dépenses donnant droit à 400 € de RÉDUCTION d\'impôt. La réduction s\'applique en premier. Que se passe-t-il au final ?',
      options: ['Ils reçoivent 1 200 €', 'L\'impôt est effacé par la réduction, ils reçoivent 1 200 € en chèque', 'L\'impôt de 500 € est annulé (les 400€ de réduction effacent 400€, les 100€ restants sont effacés par le crédit). L\'État leur verse le solde du crédit, soit 1 100 €', 'Tout est perdu'],
      correct: 2, rationale: 'Le fisc applique d\'abord les réductions (qui sont perdues si excédent), puis les crédits d\'impôts (qui sont remboursables). 500 (impôt) - 400 (réduction) = 100 € d\'impôt restant. Puis les 1 200 de crédit épongent les 100 € et génèrent un chèque de 1 100 €.' },
    { q: '(Challenge) Afin d\'éviter l\'avance de frais, l\'URSSAF a mis en place "l\'Avance immédiate du crédit d\'impôt" pour l\'emploi à domicile. Comment cela fonctionne-t-il ?',
      options: ['L\'État paie 100% de la facture directement', 'Le particulier paie sa facture normalement, et l\'État le rembourse le lendemain', 'Le particulier ne paie à l\'organisme (ou à l\'URSSAF) que 50 % de la facture (son "reste à charge"). L\'URSSAF verse directement les 50 % du crédit d\'impôt manquants au salarié ou à l\'organisme', 'Le crédit d\'impôt est supprimé avec ce système'],
      correct: 2, rationale: 'C\'est une révolution de trésorerie. Au lieu de payer 100€ et d\'attendre 1 an pour récupérer 50€, le particulier ne décaisse que 50€ immédiatement.' },
  ],
  'w5-d2': [
    { q: 'Qu\'est-ce que l\'Agirc-Arrco ?',
      options: ['La caisse de retraite des fonctionnaires de police', 'Le régime de retraite complémentaire obligatoire des salariés du secteur privé (cadres et non-cadres)', 'Une assurance vie facultative', 'Le régime de base de la Sécurité sociale'],
      correct: 1, rationale: 'Un salarié du privé cotise obligatoirement à deux caisses : la CNAV (Retraite de base) et l\'Agirc-Arrco (Retraite complémentaire).' },
    { q: 'Contrairement au régime de base (qui se compte en trimestres), sur quel système repose l\'Agirc-Arrco ?',
      options: ['Un système par capitalisation boursière', 'Un système à points (les cotisations permettent d\'acheter des points)', 'Un système basé uniquement sur l\'âge', 'Un système de tirage au sort'],
      correct: 1, rationale: 'Chaque euro cotisé est converti en points qui s\'accumulent tout au long de la carrière sur le compte de l\'assuré.' },
    { q: 'Comment calcule-t-on le montant de la pension annuelle Agirc-Arrco au moment du départ à la retraite ?',
      options: ['On prend les 10 meilleures années de salaire', 'On multiplie le nombre total de points accumulés par la "valeur de service du point" en vigueur l\'année du départ', 'On divise le dernier salaire par deux', 'On multiplie les points par le SMIC'],
      correct: 1, rationale: 'Si vous avez 5 000 points et que le point vaut 1,41 €, votre pension complémentaire sera de 7 050 € bruts par an.' },
    { q: 'Quel est le principe de financement de l\'Agirc-Arrco ?',
      options: ['La capitalisation : votre argent est placé en bourse pour vous-même', 'La répartition : les cotisations des salariés en activité servent à payer immédiatement les pensions des retraités actuels', 'L\'impôt sur le revenu', 'Les taxes sur le tabac et l\'alcool'],
      correct: 1, rationale: 'Comme pour le régime de base, l\'Agirc-Arrco fonctionne sur la solidarité intergénérationnelle (les actifs paient pour les retraités).' },
    { q: 'Qu\'est-ce que la "valeur d\'achat du point" Agirc-Arrco ?',
      options: ['Le prix auquel on peut vendre sa retraite', 'La somme qu\'il faut cotiser pour acquérir un point de retraite', 'Le montant qu\'un point rapporte une fois à la retraite', 'La taxe prélevée sur chaque point'],
      correct: 1, rationale: 'C\'est le prix d\'achat pendant la vie active (ex: il faut environ 19 € de cotisations pour "acheter" 1 point).' },
    { q: 'Que se passe-t-il sur la complémentaire Agirc-Arrco si un salarié part à la retraite SANS avoir le "taux plein" au régime de base (il lui manque des trimestres) ?',
      options: ['L\'Agirc-Arrco lui donne le taux plein par solidarité', 'La pension Agirc-Arrco subira également une minoration (un coefficient d\'anticipation ou décote) définitive', 'Il perd la totalité de ses points', 'L\'Agirc-Arrco repousse le paiement de 5 ans'],
      correct: 1, rationale: 'Les deux régimes sont liés. Si vous avez une décote sur le régime de base, votre retraite complémentaire sera elle aussi rabotée.' },
    { q: 'Qui paie les cotisations Agirc-Arrco versées chaque mois ?',
      options: ['Uniquement l\'employeur', 'Uniquement le salarié', 'Elles sont réparties entre l\'employeur (part patronale, souvent environ 60%) et le salarié (part salariale, environ 40%)', 'L\'État'],
      correct: 2, rationale: 'Les deux parties contribuent à l\'acquisition des points du salarié. Cela apparaît distinctement sur la fiche de paie.' },
    { q: 'Les chômeurs indemnisés accumulent-ils des points Agirc-Arrco ?',
      options: ['Non, seuls les travailleurs accumulent des points', 'Oui, l\'Assurance Chômage verse des cotisations qui permettent au chômeur indemnisé d\'acquérir des points de retraite complémentaire', 'Oui, mais seulement pendant 3 mois', 'Seulement s\'ils étaient cadres'],
      correct: 1, rationale: 'Par solidarité, les périodes de chômage indemnisé, de maladie ou de maternité permettent (sous conditions) l\'attribution de points.' },
    { q: '(Challenge) Jusqu\'à récemment, l\'Agirc-Arrco appliquait un "Malus" (coefficient de solidarité de -10% pendant 3 ans) pour les salariés partant à taux plein. Qu\'en est-il aujourd\'hui ?',
      options: ['Le malus a été augmenté à 20%', 'Le malus a été supprimé pour les nouveaux retraités suite à la réforme des retraites de 2023 (afin de ne pas doublement pénaliser ceux qui doivent déjà travailler plus longtemps)', 'Le malus est devenu à vie', 'Le malus s\'applique désormais dès le premier jour de travail'],
      correct: 1, rationale: 'Les partenaires sociaux, gestionnaires de l\'Agirc-Arrco, ont acté la fin de ce malus de 10% fin 2023.' },
    { q: '(Challenge) Un cadre gagne 6 000 € bruts par mois (Tranche 2). Comment ses cotisations Agirc-Arrco sont-elles calculées par rapport à un salarié au SMIC (Tranche 1) ?',
      options: ['Le taux de cotisation est unique, ils paient la même chose', 'Le cadre cotise moins proportionnellement', 'Le cadre cotise sur la Tranche 1 (jusqu\'au Plafond de la Sécu) ET sur la Tranche 2 (la part du salaire qui dépasse le plafond), avec un taux de cotisation beaucoup plus élevé sur cette Tranche 2', 'Le SMIC ne permet pas d\'avoir l\'Agirc-Arrco'],
      correct: 2, rationale: 'Le système est conçu pour que les plus hauts revenus génèrent proportionnellement beaucoup plus de points (et paient beaucoup plus de cotisations) sur la part de leur salaire qui dépasse le Plafond de la Sécurité Sociale.' },
  ],
  'w5-d3': [
    { q: 'Comment appelle-t-on les règles de transmission du patrimoine lorsqu\'une personne décède SANS avoir rédigé de testament ?',
      options: ['La transmission universelle', 'La dévolution légale (ou succession ab intestat)', 'L\'usufruit', 'L\'expropriation'],
      correct: 1, rationale: 'C\'est la loi (le Code Civil) qui se substitue au défunt pour désigner les héritiers et répartir le patrimoine selon un ordre précis.' },
    { q: 'Quel est le tout PREMIER ordre d\'héritiers (celui qui a la priorité absolue sur tous les autres) ?',
      options: ['Les parents et grands-parents (les ascendants)', 'Les frères et sœurs (les collatéraux)', 'Les enfants et leurs propres enfants (les descendants)', 'L\'État'],
      correct: 2, rationale: 'S\'il y a des enfants, ils excluent automatiquement tous les autres membres de la famille (parents, frères/sœurs, cousins) de la succession.' },
    { q: 'Si le défunt n\'a PAS d\'enfants, qui constitue le DEUXIÈME ordre d\'héritiers appelé à la succession ?',
      options: ['L\'État (qui prend tout)', 'Uniquement les cousins germains', 'Les parents du défunt (ascendants privilégiés) et ses frères et sœurs (collatéraux privilégiés)', 'Les voisins'],
      correct: 2, rationale: 'En l\'absence de descendance, l\'héritage "remonte" vers les parents et s\'étale vers les frères et sœurs (qui se partagent la succession).' },
    { q: 'Quel est le principe fondamental de "l\'ordre" en droit des successions ?',
      options: ['Tous les ordres se partagent l\'héritage à parts égales', 'Le conjoint décide de l\'ordre', 'Un ordre supérieur exclut totalement et automatiquement les ordres inférieurs', 'L\'âge des héritiers détermine l\'ordre'],
      correct: 2, rationale: 'Si un héritier du 1er ordre (un enfant) est présent, les héritiers du 2ème ordre (parents/frères) n\'ont droit à rien.' },
    { q: 'Qu\'est-ce que le mécanisme de "représentation" dans une succession ?',
      options: ['L\'avocat représente le mort', 'Si un héritier (ex: un enfant du défunt) est déjà décédé avant la succession, ce sont ses propres enfants (les petits-enfants) qui prennent sa place et se partagent sa part d\'héritage', 'Le fait de signer les papiers chez le notaire par procuration', 'L\'obligation de garder le même nom de famille'],
      correct: 1, rationale: 'La représentation permet d\'éviter qu\'une branche de la famille ne soit lésée à cause d\'un décès prématuré.' },
    { q: 'Où se situe le "conjoint survivant MARIÉ" dans cet ordre des héritiers ?',
      options: ['Il est dans le 3ème ordre', 'Il a un statut particulier hors ordre : il n\'est jamais exclu et vient "en concours" (en partage) avec les héritiers de l\'ordre appelé', 'Il est exclu s\'il y a des enfants', 'Il prend tout dans 100% des cas'],
      correct: 1, rationale: 'Le conjoint marié a des droits spécifiques. Par exemple, s\'il y a des enfants, le conjoint hérite d\'une partie et les enfants de l\'autre.' },
    { q: 'Sans testament, si le défunt laisse un conjoint marié et des enfants issus EXCLUSIVEMENT de leur union (enfants communs), quel choix est offert au conjoint survivant ?',
      options: ['100% en pleine propriété ou rien', 'Soit 100% de la succession en "usufruit" (le droit d\'usage et de revenus), soit 1/4 de la succession en "pleine propriété"', '50% de la succession obligatoirement', 'Il n\'a aucun choix, l\'État décide'],
      correct: 1, rationale: 'C\'est le cas le plus classique. Souvent, le conjoint choisit l\'usufruit pour rester dans sa maison et conserver son train de vie jusqu\'à son décès.' },
    { q: 'En l\'absence de conjoint marié, de partenaire de PACS (avec testament) et d\'enfants, un défunt laisse ses deux parents et une sœur. Comment se répartit l\'héritage ?',
      options: ['Les parents prennent 100%', 'La sœur prend 100%', 'Chaque parent reçoit un quart (1/4 + 1/4 = 1/2), et la sœur reçoit la moitié restante (1/2)', 'L\'État prend la moitié'],
      correct: 2, rationale: 'C\'est la règle stricte du 2ème ordre. Si un seul parent était en vie, il prendrait 1/4 et la sœur 3/4.' },
    { q: '(Challenge) Au regard de l\'ordre des héritiers, y a-t-il une différence entre un enfant "légitime" (né de parents mariés) et un enfant "naturel" (hors mariage) ?',
      options: ['Oui, l\'enfant naturel hérite de la moitié', 'Oui, l\'enfant naturel est exclu', 'Non, depuis 2001, la loi consacre l\'égalité parfaite et absolue entre tous les enfants, peu importe l\'état civil de leurs parents', 'L\'enfant naturel doit payer plus de taxes'],
      correct: 2, rationale: 'Le droit français ne fait plus aucune distinction. Tous les enfants reconnus ont exactement les mêmes droits sur la succession de leur parent.' },
    { q: '(Challenge) Un homme décède. Il laisse sa nouvelle épouse, un enfant qu\'il a eu avec elle, ET un enfant issu d\'un premier mariage. Quel droit la loi accorde-t-elle à sa nouvelle épouse ?',
      options: ['Elle a le choix entre 100% usufruit ou 1/4 pleine propriété', 'Elle obtient obligatoirement 1/4 de la succession en pleine propriété, l\'option de l\'usufruit lui est fermée', 'Elle prend 50% de la succession', 'Elle est déshéritée au profit du premier enfant'],
      correct: 1, rationale: 'En présence d\'un enfant d\'un premier lit (non commun au couple), la loi supprime le choix de l\'usufruit pour éviter les conflits d\'intérêts sur le long terme entre un beau-parent et un bel-enfant.' },
  ],
  'w5-d4': [
    { q: 'Quel est le but principal du constat amiable d\'accident automobile ?',
      options: ['Payer directement l\'amende à la police', 'Relater précisément et factuellement les circonstances d\'un accident pour permettre aux assurances de déterminer les responsabilités', 'Désigner soi-même le coupable', 'Annuler son contrat d\'assurance'],
      correct: 1, rationale: 'Le constat n\'est pas un tribunal. C\'est une photographie des faits (qui faisait quoi, où, et comment) à un instant T.' },
    { q: 'Est-il légalement obligatoire de remplir un constat amiable sur les lieux d\'un accident matériel ?',
      options: ['Oui, sous peine de retrait de permis', 'Non, ce n\'est pas une obligation légale, mais c\'est le seul moyen conventionnel et incontestable de prouver les faits à son assureur', 'Oui, la police doit obliger à le faire', 'Uniquement sur l\'autoroute'],
      correct: 1, rationale: 'Refuser de faire un constat n\'est pas un délit (contrairement au délit de fuite), mais cela complique énormément l\'indemnisation.' },
    { q: 'De quel délai dispose un assuré pour envoyer le constat amiable à son assureur (en cas d\'accident matériel) ?',
      options: ['24 heures', '5 jours ouvrés', '14 jours', '1 mois'],
      correct: 1, rationale: 'Il faut prévenir son assureur rapidement. En cas de vol, le délai tombe à 2 jours, et passe à 10 jours en cas de catastrophe naturelle.' },
    { q: 'Que se passe-t-il sur le plan juridique une fois que le constat est signé par les deux conducteurs ?',
      options: ['On a 14 jours pour se rétracter', 'Les informations portées sur le recto deviennent irrévocables et opposables (on ne peut plus les modifier)', 'Le constat perd sa valeur s\'il pleut', 'Le conducteur A doit payer le conducteur B'],
      correct: 1, rationale: 'La signature scelle l\'accord sur les faits. Si vous vous rendez compte plus tard que vous avez coché la mauvaise case, il est généralement trop tard.' },
    { q: 'Est-ce le constat amiable qui désigne explicitement le conducteur en tort ?',
      options: ['Oui, dans la case "Coupable"', 'Non, le constat relève les faits. Ce sont les assureurs qui appliquent un barème de responsabilité (convention IRSA) basé sur les cases cochées', 'Oui, c\'est le conducteur qui signe en premier', 'C\'est la police qui coche la responsabilité'],
      correct: 1, rationale: 'Vous ne cochez pas "Je suis en tort", vous cochez "Je sortais d\'un parking". L\'assureur en déduit votre responsabilité à 100%.' },
    { q: 'Avez-vous le droit de refuser de signer le constat amiable si vous n\'êtes pas d\'accord avec la version du second conducteur ou le croquis ?',
      options: ['Non, c\'est interdit', 'Oui, il ne faut jamais signer un constat avec lequel on est en désaccord. Il faut remplir sa partie, l\'indiquer dans les observations, et envoyer son exemplaire seul', 'Oui, mais on perd l\'assurance', 'Seulement si on a des témoins'],
      correct: 1, rationale: 'Signer signifie valider les faits. Si l\'autre force le trait sur le croquis, ne signez pas. Relevez son immatriculation et trouvez des témoins.' },
    { q: 'Que devez-vous faire si l\'autre conducteur refuse de remplir le constat ou prend la fuite ?',
      options: ['Poursuivre le véhicule pour l\'arrêter', 'Relever sa plaque d\'immatriculation, chercher des témoins, porter plainte pour délit de fuite, et remplir seul un constat avec ces informations', 'Ne rien déclarer à l\'assurance car le constat n\'a qu\'une seule signature', 'Réparer les dégâts soi-même'],
      correct: 1, rationale: 'L\'assurance pourra utiliser l\'immatriculation et les témoignages pour retrouver l\'assureur du fuyard et exercer un recours.' },
    { q: 'L\'application smartphone "e-constat auto" (constat électronique) a-t-elle la même valeur juridique que la version papier ?',
      options: ['Non, c\'est juste un brouillon', 'Oui, elle a exactement la même valeur légale et accélère le traitement (à condition que ce soit un accident entre deux véhicules terrestres à moteur, immatriculés en France, sans blessé)', 'Uniquement pour les motos', 'Oui, mais il faut quand même envoyer le papier'],
      correct: 1, rationale: 'Lancé en 2014 par les assureurs français, le e-constat est très pratique pour éviter les ratures, et il intègre des photos.' },
    { q: '(Challenge) Lors de la rédaction du constat papier, une contradiction apparaît : les croix cochées dans la colonne centrale disent le contraire du croquis dessiné en bas. Que va retenir l\'assureur ?',
      options: ['L\'assureur annule le constat', 'L\'assureur retient toujours le croquis', 'En cas de contradiction, les croix (colonne centrale) priment juridiquement sur le croquis et sur les observations', 'L\'assureur donne 50/50 systématiquement'],
      correct: 2, rationale: 'C\'est le grand danger du constat. Beaucoup bâclent les croix pour faire un beau dessin. Si vous cochez "reculait" par erreur, le dessin montrant le contraire ne vous sauvera pas.' },
    { q: '(Challenge) Vous êtes arrêté à un feu rouge (Véhicule B). Un véhicule C vous percute par l\'arrière de façon violente. Sous le choc, vous êtes projeté en avant et vous percutez le véhicule A devant vous. Que devez-vous faire en termes de constats ?',
      options: ['Faire un seul constat à trois', 'Le véhicule C fait un constat avec A, vous (', 'ne faites rien', 'Vous devez remplir DEUX constats séparés : l\'un avec le véhicule A (choc à l\'avant), l\'autre avec le véhicule C (choc à l\'arrière)', 'Laisser A et C s\'arranger'],
      correct: 2, rationale: 'Un carambolage implique de définir les responsabilités pour chaque choc (choc reçu vs choc donné). L\'assureur démêlera ensuite la projection.' },
  ],
  'w5-d5': [
    { q: 'Que signifie l\'acronyme TAEG dans un crédit immobilier ?',
      options: ['Taux Annuel d\'Endettement Garanti', 'Taux Annuel Effectif Global', 'Taxe d\'Acquisition de l\'État sur les Garanties', 'Taux Ajustable d\'Emprunt Général'],
      correct: 1, rationale: 'Autrefois appelé TEG, c\'est la boussole incontournable pour comparer le coût de plusieurs prêts.' },
    { q: 'À quoi sert concrètement le TAEG pour l\'emprunteur ?',
      options: ['À déterminer la surface achetable', 'C\'est un outil de transparence qui permet de comparer le VRAI coût total de différentes offres de prêt, car il inclut tous les frais obligatoires (pas seulement les intérêts)', 'À payer le notaire', 'À calculer la plus-value immobilière'],
      correct: 1, rationale: 'Une banque peut vous appâter avec un taux d\'intérêt très bas, mais se rattraper avec une assurance et des frais de dossier très chers. Le TAEG révèle la vérité.' },
    { q: 'Comparé au taux nominal (le taux d\'intérêt de base du prêt), comment se situe le TAEG ?',
      options: ['Il est souvent inférieur', 'Il est toujours strictement égal', 'Il est systématiquement supérieur, puisqu\'il additionne le taux nominal et tous les autres frais liés au crédit', 'Il n\'a aucun lien avec le taux nominal'],
      correct: 2, rationale: 'Taux Nominal + Coût de l\'assurance + Frais de dossier + Garanties = TAEG.' },
    { q: 'Lequel de ces éléments N\'EST PAS inclus dans le calcul du TAEG d\'un crédit immobilier ?',
      options: ['Les frais de dossier bancaires', 'Le coût de l\'assurance emprunteur obligatoire (décès/invalidité)', 'Les "frais de notaire" (Droits de mutation et taxes liés à l\'achat du bien immobilier lui-même)', 'Les frais de garantie (hypothèque, caution Crédit Logement)'],
      correct: 2, rationale: 'Le TAEG évalue le coût du crédit, pas le coût de l\'achat. Les frais de mutation ne rémunèrent pas la banque ni le crédit, ce sont des impôts d\'État.' },
    { q: 'Qu\'est-ce que le "Taux d\'Usure" par rapport au TAEG ?',
      options: ['Le taux minimum auquel la banque accepte de prêter', 'C\'est le TAEG maximal (plafond légal fixé par la Banque de France) au-delà duquel il est formellement interdit à une banque d\'accorder un prêt', 'La pénalité pour remboursement anticipé', 'Le taux d\'usure de l\'appartement'],
      correct: 1, rationale: 'Le taux d\'usure protège l\'emprunteur contre des conditions financières abusives qui pourraient le ruiner.' },
    { q: 'Une banque vous propose un crédit. Le calcul montre que le TAEG dépasse le taux d\'usure actuel. Quelle est la conséquence immédiate ?',
      options: ['La banque augmente ses frais de dossier', 'Le prêt est automatiquement refusé (dossier bloqué), car prêter au-dessus de l\'usure est un délit', 'L\'emprunteur doit payer une amende', 'La durée du prêt est divisée par deux'],
      correct: 1, rationale: 'C\'est ce qui a causé de nombreux blocages de crédits en 2022 et 2023 : les taux bancaires remontaient vite, mais le plafond légal de l\'usure ne suivait pas assez vite.' },
    { q: 'Sur un document de prêt, l\'affichage du TAEG est-il facultatif ?',
      options: ['Oui, c\'est juste un indicateur commercial', 'Non, il est strictement obligatoire sur toute publicité, offre préalable et contrat de prêt, sous peine de nullité du taux', 'Uniquement pour les prêts de plus de 200 000 €', 'Oui, sauf si l\'emprunteur est courtier'],
      correct: 1, rationale: 'Si la banque fait une erreur mathématique substantielle ou omet le TAEG, le juge peut sanctionner la banque en remplaçant le taux du crédit par le taux d\'intérêt légal (très faible).' },
    { q: 'Comment un emprunteur peut-il faire baisser son TAEG de manière très efficace, sans renégocier le taux d\'intérêt de la banque ?',
      options: ['En supprimant les fenêtres de la maison', 'En ayant recours à la "délégation d\'assurance" (prendre une assurance emprunteur externe souvent 2 fois moins chère que celle de la banque)', 'En allongeant la durée du crédit à 30 ans', 'En cachant ses crédits à la consommation'],
      correct: 1, rationale: 'L\'assurance pesant très lourd dans le TAEG, trouver une assurance moins chère fera mécaniquement chuter le TAEG global (et permettra parfois de repasser sous le taux d\'usure).' },
    { q: '(Challenge) Un client passe par un courtier en crédit immobilier. Le courtier facture 1 500 € d\'honoraires pour le montage du dossier (frais obligatoires pour l\'obtention du prêt). Ces frais de courtage doivent-ils être intégrés dans le calcul du TAEG ?',
      options: ['Non, car ce n\'est pas la banque qui les facture', 'Oui, tous les frais obligatoires pour obtenir le prêt (même facturés par des tiers) doivent entrer dans le calcul du TAEG', 'Uniquement la moitié des frais', 'Non, le courtier est invisible pour la banque'],
      correct: 1, rationale: 'C\'est la règle d\'or du TAEG. Si vous êtes obligé de payer ce courtier pour avoir le prêt de cette banque, c\'est un coût du crédit, cela gonfle donc le TAEG.' },
    { q: '(Challenge) Sur quel capital se base le calcul des frais dans la formule mathématique du TAEG ?',
      options: ['Sur le prix affiché de la maison en vitrine d\'agence', 'Sur le revenu net annuel du foyer', 'Sur le capital effectivement emprunté (montant mis à disposition par la banque)', 'Sur le total du patrimoine de l\'acheteur'],
      correct: 2, rationale: 'Le TAEG reflète le coût de l\'argent prêté. Il se calcule donc sur la somme exacte que la banque va vous avancer (prix du bien + frais divers - apport personnel).' },
  ],
};
