/* Questions de la semaine 10. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w10-d0': [
    { q: 'En finance, qu\'est-ce que la "liquidité" d\'un actif ?',
      options: ['Un investissement basé sur la mer', 'Les impôts payés sur le Livret A', 'La facilité et rapidité à le transformer en cash sans risque majeur de perte de valeur', 'La dissolution d\'une entreprise'],
      correct: 2, rationale: 'Plus l\'argent est récupérable vite, plus l\'actif est liquide.' },
    { q: 'Lequel de ces actifs est le plus liquide ?',
      options: ['Le Livret A ou le compte courant', 'Une maison de 200 m²', 'Des parts de SCPI', 'Un tableau de maître'],
      correct: 0, rationale: 'Virement instantané disponible pour les dépenses.' },
    { q: 'Quel est le meilleur exemple d\'actif "illiquide" ?',
      options: ['Une action du CAC 40', 'L\'assurance-vie (fonds euros)', 'Le LDDS', 'Un placement en Private Equity ou l\'immobilier physique'],
      correct: 3, rationale: 'Vendre une maison prend des mois.' },
    { q: 'Quel est le "Triangle d\'or" (le trilemme) des placements ?',
      options: ['Banquier, Courtier, Assureur', 'Le compromis impossible entre Sécurité (garantie), Rendement élevé, et Liquidité immédiate', 'Acheter, Louer, Vendre', 'Impôts, Taxes, Cotisations'],
      correct: 1, rationale: 'Aucun placement ne réunit les 3.' },
    { q: 'Un investissement très rentable mais bloqué 10 ans convient-il à l\'épargne de précaution ?',
      options: ['Non, l\'épargne de précaution DOIT être liquide (disponible immédiatement) pour gérer les urgences', 'Oui, le rendement prime toujours', 'Seulement pour les jeunes', 'Oui, car les banques peuvent prêter l\'argent'],
      correct: 0, rationale: 'En cas de panne de voiture, on ne peut attendre 10 ans.' },
    { q: 'Contrairement à une idée reçue, quelle est la liquidité de l\'Assurance-vie ?',
      options: ['L\'argent est totalement bloqué pendant 8 ans', 'On ne peut retirer que 10 % par an', 'L\'argent est liquide : un retrait est possible à tout moment, les 8 ans ne concernent que la fiscalité', 'Il faut l\'autorisation du médecin'],
      correct: 2, rationale: 'L\'argent n\'est jamais bloqué.' },
    { q: 'En bourse, que signifie une action "très liquide" ?',
      options: ['L\'entreprise vend des boissons', 'C\'est une action qui perd de la valeur', 'C\'est une action échangée des millions de fois par jour, qu\'on peut acheter/vendre en un quart de seconde au prix du marché', 'C\'est une action gratuite'],
      correct: 2, rationale: 'Il y a toujours des acheteurs et vendeurs.' },
    { q: 'Quel est le coût de la liquidité ?',
      options: ['La baisse du rendement : l\'épargnant accepte d\'être très faiblement rémunéré pour le privilège de garder l\'argent disponible', 'Les frais de dossier', 'Les impôts doublent', 'La prime de risque'],
      correct: 0, rationale: 'La banque vous paie peu car elle ne peut pas placer cet argent à long terme.' },
    { q: '(Challenge) Lors d\'une panique bancaire ("Bank Run"), que se passe-t-il ?',
      options: ['La banque double les intérêts', 'Tous les clients veulent retirer en même temps. La banque n\'ayant pas assez de liquidités, elle risque la faillite', 'L\'État supprime l\'argent liquide', 'Le Livret A est confisqué'],
      correct: 1, rationale: 'Le système ne détient qu\'une fraction des dépôts en cash réel.' },
    { q: '(Challenge) Sur un Compte à Terme (CAT), quelle "contrepartie" acceptez-vous pour un meilleur rendement ?',
      options: ['Perdre son droit de vote', 'Payer des impôts mensuels', 'Vous bloquez (immobilisez) vos liquidités pendant une période précise (privation de liquidité)', 'Ne plus utiliser sa carte bancaire'],
      correct: 2, rationale: 'Casser le contrat avant l\'échéance entraîne des pénalités.' },
  ],
  'w10-d1': [
    { q: 'Qu\'est-ce qu\'une "niche fiscale" (officiellement appelée dépense fiscale) ?',
      options: ['Une taxe sur les animaux de compagnie', 'Un avantage fiscal légal (déduction, réduction ou crédit d\'impôt) accordé par l\'État pour inciter les contribuables à adopter un certain comportement (investir, consommer, créer de l\'emploi)', 'Un compte bancaire caché en Suisse', 'L\'exonération des impôts pour les entreprises'],
      correct: 1, rationale: 'L\'État accepte de percevoir moins d\'impôts en échange d\'un comportement utile à la société (ex: financer la construction de logements, employer du personnel à domicile, rénover thermiquement).' },
    { q: 'À combien est fixé le "plafond global des niches fiscales" par an et par foyer (la limite maximum d\'avantages fiscaux cumulables) ?',
      options: ['1 000 €', '10 000 €', '50 000 €', 'Il n\'y a pas de plafond'],
      correct: 1, rationale: 'Pour éviter que les contribuables les plus riches ne ramènent leur impôt à zéro en cumulant les investissements défiscalisants, la loi plafonne l\'avantage total à 10 000 € par an.' },
    { q: 'Lequel de ces investissements immobiliers est une célèbre niche fiscale permettant une "réduction d\'impôt" en échange de la location d\'un logement neuf sous plafonds de loyer ?',
      options: ['La loi Pinel', 'Le dispositif LMNP', 'Le crédit d\'impôt transition énergétique', 'La loi Macron'],
      correct: 0, rationale: 'L\'investisseur achète un logement neuf, s\'engage à le louer 6, 9 ou 12 ans à un loyer modéré, et l\'État lui accorde une réduction d\'impôt calculée sur le prix d\'achat du bien.' },
    { q: 'L\'emploi d\'un salarié à domicile (femme de ménage, soutien scolaire) relève-t-il des niches fiscales ?',
      options: ['Non, cela n\'a aucun impact sur les impôts', 'Oui, cela donne droit à un "crédit d\'impôt" égal à 50 % des dépenses engagées, soumis au plafond des 10 000 €', 'Oui, mais seulement si le contribuable est invalide', 'Oui, cela donne une déduction de 100 %'],
      correct: 1, rationale: 'C\'est la niche fiscale la plus utilisée par les Français, conçue pour lutter contre le travail au noir.' },
    { q: 'Quelle est la différence fondamentale entre "l\'optimisation fiscale" (l\'usage des niches) et la "fraude fiscale" ?',
      options: ['Il n\'y a aucune différence, les deux sont punis par la loi', 'L\'optimisation est réservée aux entreprises, la fraude aux particuliers', 'L\'optimisation consiste à utiliser en toute légalité les avantages prévus par la loi pour réduire son impôt. La fraude est la violation illégale de la loi (dissimulation de revenus)', 'L\'optimisation est une fraude de moins de 10 000 €'],
      correct: 2, rationale: 'Utiliser la loi Pinel ou faire un don pour baisser ses impôts est parfaitement légal et encouragé par l\'État. Cacher un compte à l\'étranger est un délit.' },
    { q: 'Certaines niches "ultra-marines" (investissement en Outre-Mer) ou "Sofica" (financement du cinéma) bénéficient d\'un plafond dérogatoire. À combien s\'élève ce plafond majoré ?',
      options: ['11 000 €', '18 000 €', '100 000 €', 'Il est illimité'],
      correct: 1, rationale: 'Pour inciter très fortement les capitaux à se diriger vers les DOM-TOM (Girardin) ou la production cinématographique (secteurs très risqués), l\'État repousse le plafond légal de 10 000 € à 18 000 €.' },
    { q: 'Les versements sur un Plan Épargne Retraite (PER) génèrent une déduction fiscale. Sont-ils soumis au plafond global des niches fiscales de 10 000 € ?',
      options: ['Oui', 'Non, ils sont "hors plafond global" (bien qu\'ils aient leur propre plafond spécifique calculé sur le revenu)', 'Oui, mais seulement pour les fonctionnaires', 'Seulement si on verse plus de 10 000 €'],
      correct: 1, rationale: 'C\'est un atout colossal pour les très gros contribuables qui ont déjà saturé leurs 10 000 € de réductions diverses (avec du Pinel et une femme de ménage, par exemple) : ils peuvent encore baisser leur impôt grâce au PER.' },
    { q: 'Les dons aux œuvres de bienfaisance (Croix-Rouge, Restos du Cœur) entrent-ils dans le plafond global des niches fiscales de 10 000 € ?',
      options: ['Oui', 'Non, la réduction d\'impôt pour don (à 66 % ou 75 %) échappe totalement au plafonnement des 10 000 €', 'Seulement pour les 100 premiers euros', 'Oui, et ils annulent les autres réductions'],
      correct: 1, rationale: 'L\'État ne veut surtout pas décourager la générosité publique. Un philanthrope peut donc donner sans se soucier du plafond des niches.' },
    { q: '(Challenge) Un célibataire paie 6 000 € d\'impôt sur le revenu par an. Il achète un dispositif Pinel qui lui génère 5 000 € de réduction d\'impôt par an, et il emploie une femme de ménage qui lui génère 6 000 € de crédit d\'impôt. Que va-t-il se passer l\'année prochaine ?',
      options: ['Il gagne 11 000 € nets de la part de l\'État', 'Il ne paie pas d\'impôt et reçoit un chèque de 5 000 €', 'Le total de ses avantages fiscaux étant de 11 000 €, le plafond légal va "couper" (écrêter) cet avantage à 10 000 €. Il perdra définitivement les 1 000 € de dépassement', 'Il ira en prison pour avoir dépassé le plafond'],
      correct: 2, rationale: 'L\'avantage est bloqué à 10k. Comme son impôt était de 6 000€, l\'État efface les 6 000€, et lui fera un chèque du reste de l\'avantage (4 000€). Mais les 1 000€ qui dépassaient le plafond de 10k sont perdus (non reportables).' },
    { q: '(Challenge) Un dispositif très ancien de "niche fiscale", réservé à l\'immobilier, est réputé pour ne subir absolument AUCUN plafonnement (les réductions ou déductions peuvent être illimitées). Lequel est-ce ?',
      options: ['La loi Pinel', 'La loi Malraux et le dispositif Monuments Historiques', 'Le LMNP (Loueur Meublé Non Professionnel)', 'Le Livret A'],
      correct: 1, rationale: 'Pour sauver le patrimoine architectural français en péril, l\'État permet aux très riches contribuables de déduire les (très lourds) travaux de restauration sans aucune limite de plafond.' },
  ],
  'w10-d2': [
    { q: 'Qu\'est-ce que la "pension de réversion" ?',
      options: ['La part de retraite que le gouvernement garde', 'Le versement d\'une partie de la retraite d\'un assuré décédé à son conjoint ou ex-conjoint survivant', 'Le remboursement des trimestres non utilisés', 'La retraite versée en cas d\'invalidité'],
      correct: 1, rationale: 'La réversion permet de protéger le niveau de vie du survivant qui perd subitement les revenus de son conjoint décédé.' },
    { q: 'Quelle est la condition STRICTE liée au statut conjugal pour avoir droit à la pension de réversion (dans le régime général des salariés et Agirc-Arrco) ?',
      options: ['Avoir vécu ensemble au moins 2 ans (concubinage suffit)', 'Être ou avoir été OBLIGATOIREMENT marié avec le défunt (le PACS et le concubinage sont exclus)', 'Être pacsé depuis 5 ans', 'Avoir des enfants ensemble (le mariage n\'est pas nécessaire)'],
      correct: 1, rationale: 'C\'est une des plus grandes discriminations légales actuelles. Les partenaires de PACS et les concubins n\'ont aucun droit à la réversion, même après 40 ans de vie commune.' },
    { q: 'Dans le régime de base (CNAV), y a-t-il une condition d\'âge pour que le survivant puisse toucher la réversion ?',
      options: ['Non, aucun âge (versement immédiat même si le conjoint a 30 ans)', 'Oui, le survivant doit être âgé d\'au moins 55 ans', 'Oui, il faut avoir 65 ans', 'Oui, 70 ans'],
      correct: 1, rationale: 'Si le survivant est plus jeune au moment du décès, il devra attendre son 55ème anniversaire pour faire la demande.' },
    { q: 'Dans le régime de base (CNAV), y a-t-il une condition de ressources (revenus) pour le survivant ?',
      options: ['Non, la réversion est due quel que soit le niveau de richesse', 'Oui, les revenus personnels du survivant ne doivent pas dépasser un certain plafond légal (environ 24 232 € brut/an pour une personne seule en 2024). Si ses revenus dépassent, la réversion n\'est pas versée (ou est réduite)', 'Uniquement sur les revenus immobiliers', 'Uniquement si on a des enfants'],
      correct: 1, rationale: 'Le régime de base considère la réversion comme une aide de solidarité. Si le survivant gagne déjà bien sa vie, la Sécurité sociale ne lui verse rien.' },
    { q: 'Quel est le taux de la pension de réversion dans le régime de base (Sécurité sociale / CNAV) ?',
      options: ['100 % de la retraite du défunt', '54 % de la retraite de base que percevait (ou aurait perçue) le défunt', '30 % de la retraite du défunt', 'Un montant fixe de 500 € par mois pour tout le monde'],
      correct: 1, rationale: 'Le survivant ne touche qu\'un peu plus de la moitié de la pension de base du défunt.' },
    { q: 'Concernant la retraite complémentaire des salariés du privé (Agirc-Arrco), quel est le taux de la pension de réversion ?',
      options: ['54 % (comme la base)', '60 % de la retraite complémentaire du défunt', '100 %', '0 % (l\'Agirc-Arrco ne fait pas de réversion)'],
      correct: 1, rationale: 'Le régime complémentaire est légèrement plus généreux sur le pourcentage que le régime de base.' },
    { q: 'L\'Agirc-Arrco (retraite complémentaire) applique-t-elle un plafond de ressources (limite de revenus du survivant) ?',
      options: ['Oui, le même que la Sécurité sociale', 'Oui, mais seulement pour les cadres', 'Non, la réversion Agirc-Arrco est versée SANS condition de ressources, quels que soient les revenus du conjoint survivant', 'Oui, si le survivant gagne plus que le SMIC'],
      correct: 2, rationale: 'C\'est une différence majeure. Un conjoint survivant qui travaille et gagne très bien sa vie se verra refuser la réversion de base (CNAV), mais touchera de plein droit la réversion complémentaire (Agirc-Arrco).' },
    { q: 'Le survivant doit-il demander la pension de réversion ou est-elle versée automatiquement au moment du décès ?',
      options: ['Elle est versée automatiquement par virement sous 10 jours', 'Elle n\'est JAMAIS automatique, le survivant doit obligatoirement en faire la demande formelle (dossier papier ou via Info-Retraite)', 'Automatique si le conjoint a plus de 60 ans', 'Automatique si c\'est la mairie qui la demande'],
      correct: 1, rationale: 'L\'administration ne présume pas de vos ressources (pour le régime de base) ni de vos autres mariages. Si vous ne demandez rien, on ne vous versera rien.' },
    { q: '(Challenge) Un défunt a été marié deux fois (un divorce, puis un remariage). Que se passe-t-il pour la pension de réversion ?',
      options: ['Seul le conjoint actuel la touche', 'Seule la première épouse la touche', 'Elle est supprimée', 'La pension de réversion est partagée entre le conjoint actuel et l\'ex-conjoint, au prorata exact de la durée de chaque mariage'],
      correct: 3, rationale: 'Si le défunt a été marié 20 ans avec l\'ex-épouse, et 10 ans avec la nouvelle épouse, la première touchera 2/3 de la réversion et la seconde touchera 1/3.' },
    { q: '(Challenge) Que se passe-t-il si la veuve (le survivant) se REMARIE après le décès de son époux ?',
      options: ['Rien ne change', 'Le régime de base (CNAV) maintient la réversion (mais les revenus du nouveau conjoint sont pris en compte pour le plafond), TANDIS QUE l\'Agirc-Arrco supprime DÉFINITIVEMENT sa réversion (même en cas de nouveau divorce)', 'Le régime de base supprime la réversion, l\'Agirc-Arrco la maintient', 'Toutes les réversions sont supprimées dans tous les régimes'],
      correct: 1, rationale: 'Le remariage annule les droits acquis sur le régime complémentaire Agirc-Arrco de l\'ex-conjoint décédé. Le PACS et le concubinage, en revanche, n\'annulent pas la réversion Agirc-Arrco.' },
  ],
  'w10-d3': [
    { q: 'Qu\'est-ce qu\'une "donation" en droit civil ?',
      options: ['Un prêt d\'argent sans intérêt entre amis', 'L\'acte par lequel une personne (le donateur) transmet gratuitement, de son vivant, la propriété d\'un bien à une autre personne (le donataire)', 'Le transfert d\'un bien après le décès', 'Une vente avec un rabais de 50 %'],
      correct: 1, rationale: 'À la différence du testament (qui prend effet au décès), la donation appauvrit le donateur immédiatement.' },
    { q: 'La donation est soumise au principe d\'irrévocabilité ("donner et retenir ne vaut"). Qu\'est-ce que cela signifie ?',
      options: ['Que l\'on peut reprendre le bien donné sous un délai de 14 jours', 'Qu\'une donation est définitive et immédiate. Le donateur ne peut pas changer d\'avis et récupérer le bien plus tard', 'Que seul l\'État peut l\'annuler', 'Que le donateur doit conserver une clé'],
      correct: 1, rationale: 'Sauf cas très rares et graves (ingratitude extrême, ou non-respect de conditions spécifiques), un don est irrévocable.' },
    { q: 'Une "donation simple" d\'un BIEN IMMOBILIER peut-elle se faire sur papier libre (don manuel) ?',
      options: ['Oui, s\'il y a des témoins', 'Oui, si on l\'envoie en recommandé', 'Non, toute donation immobilière exige obligatoirement un Acte Authentique rédigé par un notaire, sous peine de nullité absolue', 'Seulement si la maison vaut plus de 100 000 €'],
      correct: 2, rationale: 'Le don manuel (de la main à la main ou par virement) n\'est autorisé que pour l\'argent, les voitures ou les meubles. L\'immobilier doit passer par le notaire pour la sécurité juridique et la publication aux hypothèques.' },
    { q: 'Quel est le grand avantage de réaliser une donation de son vivant à un enfant (d\'un point de vue fiscal) ?',
      options: ['L\'enfant devient non imposable', 'Le parent bénéficie d\'une réduction d\'impôt sur le revenu', 'Utiliser l\'abattement fiscal de 100 000 € (zéro impôt) de son vivant, abattement qui se "recharge" intégralement tous les 15 ans', 'Annuler les dettes du parent'],
      correct: 2, rationale: 'Un parent peut donner 100 000 € à 50 ans, puis encore 100 000 € à 65 ans, puis encore à 80 ans, évitant ainsi d\'énormes droits de succession à son décès.' },
    { q: 'Qu\'est-ce qu\'une donation simple avec "réserve d\'usufruit" (ou démembrement de propriété) ?',
      options: ['Le parent donne la maison mais l\'enfant doit la louer', 'Le parent donne la Nue-Propriété (les murs) à l\'enfant, mais conserve l\'Usufruit (le droit d\'y habiter ou de toucher les loyers jusqu\'à sa mort)', 'Le parent donne les fruits du jardin mais garde la maison', 'L\'enfant habite la maison mais le parent peut le chasser'],
      correct: 1, rationale: 'C\'est le montage roi en gestion de patrimoine. Il permet de transmettre le patrimoine à moindre coût fiscal, tout en protégeant le parent donateur (qui ne peut pas être mis à la porte).' },
    { q: 'Si un parent fait un "don manuel" (ex: un virement de 50 000 €) à son enfant sans passer par un notaire, doit-il quand même le déclarer aux impôts ?',
      options: ['Non, c\'est privé et secret', 'Oui, le donataire (l\'enfant) doit obligatoirement déclarer ce don manuel aux impôts (formulaire 2735) dans le mois qui suit, pour faire courir le délai de 15 ans de l\'abattement', 'Uniquement si la banque le demande', 'Seulement si la somme dépasse 100 000 €'],
      correct: 1, rationale: 'Même s\'il n\'y a aucun impôt à payer (car inférieur à 100 000 €), la déclaration prouve la date du don et évite un redressement fiscal.' },
    { q: 'Quel est le danger juridique d\'une "donation simple" par rapport à une "donation-partage" si le parent a PLUSIEURS enfants ?',
      options: ['La donation simple coûte plus cher en notaire', 'Lors du décès, la valeur du bien donné en "donation simple" sera réévaluée à sa valeur au jour du décès (Rapport à la succession). Si le bien a pris beaucoup de valeur, l\'enfant avantagé devra indemniser ses frères et sœurs', 'La donation simple est interdite s\'il y a plusieurs enfants', 'Les impôts doublent'],
      correct: 1, rationale: 'Si vous donnez un terrain de 50k à un fils et 50k en cash à votre fille. 20 ans plus tard, au décès, le terrain vaut 200k, le cash a été dépensé. Le fils devra compenser sa sœur pour rétablir l\'équilibre (le rapport à la succession).' },
    { q: 'Pour contourner ce problème et figer définitivement les valeurs au jour de la donation (sans réévaluation au décès), quel type de donation faut-il faire devant notaire ?',
      options: ['Un don manuel', 'Une donation-partage (qui distribue et fige les lots entre tous les héritiers)', 'Un testament olographe', 'Une vente à l\'euro symbolique'],
      correct: 1, rationale: 'Contrairement à la donation simple, la donation-partage "cristallise" les valeurs. Il n\'y aura plus de comptes à faire entre frères et sœurs lors du décès.' },
    { q: '(Challenge) Outre l\'abattement classique de 100 000 €, qu\'est-ce que le "Don familial de sommes d\'argent" (aussi appelé dispositif Sarkozy/TEPA) ?',
      options: ['Un don d\'argent pour acheter une voiture', 'Un abattement spécifique SUPPLÉMENTAIRE de 31 865 € (pour un don en espèces/virement), cumulable avec les 100 000 €, à condition que le donateur ait moins de 80 ans et le donataire soit majeur', 'Le droit de prêter de l\'argent avec intérêts à sa famille', 'L\'obligation pour les enfants de payer l\'EHPAD'],
      correct: 1, rationale: 'Un parent de 60 ans peut donc donner, tous les 15 ans, à un enfant majeur : 100 000 € (abattement classique) + 31 865 € (don familial en argent) = 131 865 € sans aucun impôt.' },
    { q: '(Challenge) Un parent fait une énorme donation de son vivant à son ami, vidant ainsi son patrimoine. À son décès, il ne reste plus rien pour son fils. Que peut faire le fils ?',
      options: ['Rien, car une donation est irrévocable', 'Il attaque la banque', 'Il intente une "Action en réduction". La donation ayant "attaqué" sa Réserve Héréditaire légale (la part qui lui est due obligatoirement), le juge forcera l\'ami à indemniser le fils pour reconstituer sa réserve', 'Il hérite des dettes de l\'ami'],
      correct: 2, rationale: 'L\'irrévocabilité d\'un don n\'efface pas les règles d\'ordre public de la succession. On ne peut pas déshériter un enfant de son vivant par des donations excessives.' },
  ],
  'w10-d4': [
    { q: 'Qu\'est-ce qu\'une assurance "Protection Juridique" (PJ) ?',
      options: ['Une assurance qui vous paie un garde du corps', 'Un contrat d\'assurance qui vous informe sur vos droits, vous assiste dans la résolution amiable d\'un litige, et prend en charge les frais de justice (avocat, huissier, expert) en cas de procès', 'Une assurance qui paie vos amendes routières', 'Un contrat qui annule votre Responsabilité Civile'],
      correct: 1, rationale: 'La PJ est votre bouclier en cas de conflit avec un voisin, un vendeur, un artisan, ou votre employeur.' },
    { q: 'Quelle est la grande différence entre la garantie "Responsabilité Civile" (RC) et la "Protection Juridique" (PJ) ?',
      options: ['Il n\'y en a aucune, ce sont des synonymes', 'La RC indemnise la VICTIME d\'un dommage que vous avez causé. La PJ défend VOS intérêts si vous êtes victime (ou poursuivi pour autre chose) et paie vos frais de défense', 'La RC est pour la voiture, la PJ pour la maison', 'La PJ coûte 10 fois plus cher que la RC'],
      correct: 1, rationale: 'Si vous cassez la fenêtre du voisin, la RC paie le vitrier. Si vous achetez une voiture d\'occasion avec un vice caché et que le vendeur refuse d\'annuler la vente, la PJ paie l\'expert et l\'avocat pour le poursuivre.' },
    { q: 'Une assurance Protection Juridique va-t-elle systématiquement déclencher un procès au tribunal ?',
      options: ['Oui, c\'est obligatoire pour être remboursé', 'Non, la toute première étape (souvent obligatoire et la plus efficace) est la tentative de résolution à l\'amiable gérée par les juristes de la compagnie d\'assurance (courriers de mise en demeure, négociations)', 'Uniquement si les dommages dépassent 10 000 €', 'Seulement si la police intervient'],
      correct: 1, rationale: 'Plus de 70 % des litiges gérés par la Protection Juridique se règlent à l\'amiable grâce au poids et aux courriers des juristes de l\'assurance, évitant des années de procès.' },
    { q: 'Si le conflit va jusqu\'au tribunal, l\'assureur peut-il vous OBLIGER à prendre l\'avocat de la compagnie d\'assurance ?',
      options: ['Oui, c\'est lui qui paie, donc c\'est lui qui choisit', 'Non, la loi garantit le "libre choix de l\'avocat" par l\'assuré (même si l\'assureur peut vous en proposer un si vous n\'en connaissez pas)', 'Oui, sauf si l\'avocat de l\'assureur est malade', 'Vous n\'avez pas le droit à un avocat en PJ'],
      correct: 1, rationale: 'C\'est une règle d\'ordre public. Vous pouvez tout à fait prendre votre avocat habituel, l\'assurance remboursera ses honoraires.' },
    { q: 'Le remboursement des honoraires de votre avocat par l\'assurance Protection Juridique est-il illimité ?',
      options: ['Oui, c\'est le principe de l\'assurance', 'Non, il est strictement encadré par un barème contractuel avec des plafonds de remboursement (ex : 800 € pour le Tribunal d\'Instance, 1500 € pour la Cour d\'Appel). Tout dépassement est à la charge de l\'assuré', 'Oui, mais seulement en France', 'La PJ ne paie jamais l\'avocat, elle donne juste des conseils'],
      correct: 1, rationale: 'Si votre avocat "star" facture 3 000 € pour l\'affaire et que le barème de la PJ prévoit 1 000 €, vous devrez payer les 2 000 € de différence de votre poche.' },
    { q: 'Si un juge vous condamne à payer 5 000 € de dommages et intérêts à votre voisin, l\'assurance Protection Juridique paiera-t-elle ces 5 000 € ?',
      options: ['Oui, c\'est à ça qu\'elle sert', 'Non, JAMAIS. La PJ paie les frais de justice (avocat, huissier), mais elle ne paie jamais les condamnations, amendes ou dommages et intérêts prononcés contre vous', 'Oui, mais il y a une franchise de 10 %', 'Uniquement si vous n\'avez pas fait exprès'],
      correct: 1, rationale: 'C\'est une confusion fréquente. Si vous êtes condamné, la dette est pour vous. (Dans certains cas, votre Responsabilité Civile prendra le relais pour payer, mais pas la PJ).' },
    { q: 'Dans un contrat de Protection Juridique, qu\'est-ce que le "seuil d\'intervention" ?',
      options: ['Le nombre maximum de litiges par an', 'Le montant minimum que doit représenter le litige pour que l\'assureur accepte d\'intervenir (ex : la PJ ne bougera pas pour un litige de 50 € sur un achat internet, le seuil étant souvent fixé à 150 ou 200 €)', 'Le prix de l\'assurance', 'La distance entre votre maison et le tribunal'],
      correct: 1, rationale: 'Les assureurs fixent ce seuil pour éviter d\'ouvrir des dossiers lourds et coûteux (frais de gestion) pour des querelles de quelques euros.' },
    { q: 'Qu\'est-ce qu\'un "délai de carence" dans ce type de contrat ?',
      options: ['Une période sans assurance auto', 'Une période suivant la souscription (souvent de 6 à 24 mois) pendant laquelle certains litiges précis (ex: divorce, construction de maison, prud\'hommes) ne sont pas pris en charge', 'Le délai pour payer la cotisation', 'Le temps que met le juge pour répondre'],
      correct: 1, rationale: 'L\'assurance est basée sur l\'aléa (le hasard). Ce délai empêche un client qui sait qu\'il va divorcer le mois prochain de souscrire une PJ in extremis juste pour faire payer son avocat par l\'assureur.' },
    { q: '(Challenge) Vous avez un litige. Les juristes de la Protection Juridique estiment qu\'il n\'y a aucune chance de gagner au tribunal et refusent de financer l\'avocat. Êtes-vous bloqué ?',
      options: ['Oui, l\'assureur a le dernier mot', 'Non, vous pouvez lancer la procédure à vos frais. Si au final le juge vous donne raison, l\'assureur sera forcé de vous rembourser rétroactivement vos frais d\'avocat', 'Oui, il est interdit de prendre un avocat si l\'assureur refuse', 'L\'État paiera l\'avocat à la place'],
      correct: 1, rationale: 'C\'est une garantie légale. L\'assureur ne peut pas vous empêcher d\'aller au tribunal. S\'il se trompait sur vos chances de succès, il devra assumer ses obligations contractuelles après coup.' },
    { q: '(Challenge) Quel est le gros désavantage d\'avoir la Protection Juridique "incluse" dans son contrat Multirisque Habitation ou Auto, par rapport à un contrat de Protection Juridique "Autonome" (séparé) ?',
      options: ['La PJ autonome est moins chère', 'La PJ autonome ne couvre que l\'immobilier', 'La PJ incluse (garantie annexe) ne couvre généralement QUE les litiges liés à ce contrat (uniquement les accidents auto, ou uniquement l\'habitation). Le contrat "Autonome" couvre tous les domaines de la vie (internet, succession, divorce, travail, impôts)', 'La PJ incluse interdit de prendre un avocat'],
      correct: 2, rationale: 'Beaucoup pensent être bien couverts avec la PJ de leur assurance auto. Mais si vous avez un litige avec votre employeur (licenciement) ou un artisan venu refaire la cuisine, cette PJ auto ne vous servira à rien.' },
  ],
  'w10-d5': [
    { q: 'Dans l\'immobilier d\'habitation, comment appelle-t-on la période légale de réflexion accordée à l\'acheteur après la signature de l\'avant-contrat ?',
      options: ['Le délai de carence', 'Le délai de préemption', 'Le délai de rétractation (loi SRU / Macron)', 'Le droit d\'annulation perpétuel'],
      correct: 2, rationale: 'C\'est une protection d\'ordre public. Elle permet à l\'acheteur de "dormir dessus" et d\'annuler cet achat extrêmement engageant sans avoir à se justifier.' },
    { q: 'Quelle est la durée exacte de ce délai légal de rétractation ?',
      options: ['3 jours', '7 jours (c\'était l\'ancienne loi)', '10 jours incompressibles', '30 jours'],
      correct: 2, rationale: 'Depuis la loi Macron de 2015, le délai initialement prévu par la loi SRU est passé de 7 à 10 jours pour donner encore plus de temps à l\'acheteur.' },
    { q: 'Le VENDEUR bénéficie-t-il également de ce droit de rétractation de 10 jours après la signature du compromis ?',
      options: ['Oui, le contrat doit être équitable', 'Non, dès la signature du compromis (ou l\'acceptation ferme de l\'offre d\'achat), le vendeur est définitivement engagé et ne peut plus changer d\'avis', 'Uniquement si la maison vaut moins de 100 000 €', 'Oui, mais seulement pendant 3 jours'],
      correct: 1, rationale: 'La loi protège exclusivement le consommateur/acheteur. Le vendeur, lui, ne peut plus faire marche arrière, sous peine de poursuites judiciaires (vente forcée).' },
    { q: 'À partir de QUAND ce délai de 10 jours commence-t-il exactement à courir ?',
      options: ['Le jour de la visite de la maison', 'Le jour de la signature de l\'offre d\'achat', 'Le LENDEMAIN de la remise en main propre (chez le notaire) ou de la première présentation de la lettre recommandée contenant le compromis signé ET toutes ses annexes obligatoires', 'Le jour du déblocage des fonds'],
      correct: 2, rationale: 'Si la lettre recommandée arrive un mardi (présentation par le facteur), le jour 1 du délai commence le mercredi.' },
    { q: 'Comment l\'acheteur doit-il formuler sa demande de rétractation pour qu\'elle soit juridiquement valable ?',
      options: ['Par un simple SMS à l\'agent immobilier', 'Par un appel téléphonique au vendeur', 'Obligatoirement par Lettre Recommandée avec Accusé de Réception (LRAR), ou par remise en main propre contre décharge, adressée au vendeur ou au notaire', 'En allant au commissariat'],
      correct: 2, rationale: 'Le formalisme est strict pour prouver de façon irréfutable la date de la rétractation. Un simple e-mail n\'a pas de valeur légale sécurisée.' },
    { q: 'Que se passe-t-il financièrement si l\'acheteur se rétracte dans les temps (avant la fin du 10ème jour) ?',
      options: ['Il perd son dépôt de garantie (souvent 5 à 10% du prix)', 'Il récupère intégralement son dépôt de garantie dans un délai de 21 jours, sans avoir à verser la moindre indemnité ou pénalité au vendeur', 'Il doit payer les frais de notaire quand même', 'Il doit payer l\'agent immobilier'],
      correct: 1, rationale: 'Se rétracter pendant le délai légal est un droit absolu. L\'acheteur n\'a pas à se justifier et ne doit subir aucune sanction financière.' },
    { q: 'Que stipule la loi si le 10ème (et dernier) jour du délai tombe un dimanche ou un jour férié ?',
      options: ['Tant pis pour l\'acheteur, le délai s\'arrête la veille', 'La rétractation est prolongée de 30 jours', 'Le délai est prorogé (prolongé) jusqu\'au premier jour ouvrable (travaillé) suivant', 'Le contrat est annulé d\'office'],
      correct: 2, rationale: 'Si le 10ème jour est un dimanche, l\'acheteur a jusqu\'au lundi (23h59) pour envoyer sa lettre recommandée.' },
    { q: 'La loi SRU (le droit de rétractation de 10 jours) s\'applique-t-elle à TOUS les types de biens immobiliers ?',
      options: ['Oui, absolument tous (habitations, champs, usines)', 'Non, elle s\'applique EXCLUSIVEMENT aux immeubles à usage d\'habitation (résidences, appartements). Elle ne s\'applique pas aux locaux commerciaux, bureaux, ou terrains isolés', 'Uniquement aux biens neufs (VEFA)', 'Uniquement aux ventes aux enchères'],
      correct: 1, rationale: 'La loi vise à protéger le particulier qui cherche à se loger. L\'investisseur qui achète un local commercial agit en professionnel de l\'investissement et ne bénéficie pas de ce délai.' },
    { q: '(Challenge) Lors de la signature du compromis chez le notaire, il manque un document fondamental obligatoire (ex : le diagnostic Carrez, le DPE ou l\'état de la copropriété). L\'acheteur signe quand même le compromis. Que se passe-t-il pour le délai de 10 jours ?',
      options: ['Le délai démarre normalement', 'Le compromis est nul et l\'acheteur va en prison', 'Le délai de rétractation NE DÉMARRE PAS. Il ne commencera à courir que le lendemain du jour où le vendeur aura communiqué officiellement le document manquant à l\'acheteur', 'L\'acheteur perd son droit de rétractation'],
      correct: 2, rationale: 'C\'est la terreur des agents immobiliers et des notaires. Si un seul PV d\'assemblée générale manque, le délai ne court pas. L\'acheteur pourrait ainsi se rétracter 2 mois plus tard !' },
    { q: '(Challenge) Un acheteur professionnel (par exemple un marchand de biens dont c\'est le métier) qui achète un appartement (habitation) bénéficie-t-il du délai de rétractation de 10 jours de la loi SRU ?',
      options: ['Oui, la loi s\'applique au "bien", donc l\'habitation', 'Non, le Code de la construction et de l\'habitation précise que ce droit est strictement réservé à "l\'acquéreur NON PROFESSIONNEL"', 'Oui, mais seulement pendant 5 jours', 'Seulement s\'il achète sans crédit'],
      correct: 1, rationale: 'La loi estime qu\'un marchand de biens ou un promoteur a les compétences nécessaires pour estimer le bien lors de la visite. Il n\'a pas besoin d\'être "protégé" par ce délai de réflexion de 10 jours.' },
  ],
};
