/* Questions de la semaine 9. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w9-d0': [
    { q: 'Comment nomme-t-on la durée pendant laquelle on prévoit de laisser son capital placé ?',
      options: ['L\'usure', 'L\'horizon de placement (ou d\'investissement)', 'La décote', 'Le cycle de vie'],
      correct: 1, rationale: 'C\'est le premier curseur à régler.' },
    { q: 'Quelle est l\'influence du TEMPS sur le risque d\'un investissement boursier ?',
      options: ['Il lisse la volatilité (le risque de perte diminue à mesure que l\'horizon s\'allonge)', 'Il l\'augmente', 'Il le neutralise totalement', 'Il n\'a aucune influence'],
      correct: 0, rationale: 'Sur 15 ans, les cycles haussiers compensent les krachs.' },
    { q: 'Quel concept explique pourquoi "commencer tôt" prime sur "mettre beaucoup d\'argent" ?',
      options: ['L\'inflation', 'Le quotient familial', 'La Flat Tax', 'Les intérêts composés'],
      correct: 3, rationale: 'Les intérêts génèrent eux-mêmes des intérêts de façon exponentielle.' },
    { q: 'Face à l\'inflation, pourquoi le temps est-il le pire ennemi du Livret A ?',
      options: ['Car le taux baisse tous les jours', 'La banque clôture les vieux comptes', 'Sur le long terme, l\'inflation ronge le pouvoir d\'achat de la monnaie, rendant le capital perdant "réellement"', 'Les impôts augmentent'],
      correct: 2, rationale: 'La sécurité du Livret A masque un appauvrissement réel sur 20 ans.' },
    { q: 'Qu\'est-ce qu\'une stratégie d\'investissement "à court terme" ?',
      options: ['Placer un capital dont on a besoin dans moins de 3 ans sur un support sans risque', 'Investir pour la retraite', 'Acheter des actions très volatiles', 'Spéculer sur 10 ans'],
      correct: 0, rationale: 'L\'horizon court interdit la volatilité.' },
    { q: 'Un horizon très long (25 ans) autorise l\'épargnant à faire un choix fondamental :',
      options: ['Fermer tous ses comptes bancaires', 'Exiger le remboursement de ses impôts', 'Tout mettre sur un Livret Jeune', 'Accepter un haut niveau de risque pour viser un rendement beaucoup plus élevé sans craindre les crises passagères'],
      correct: 3, rationale: 'Le temps permet de surmonter les krachs.' },
    { q: 'Qu\'est-ce que "la prime de liquidité" liée au temps ?',
      options: ['Un cadeau de bienvenue', 'L\'impôt payé à la sortie', 'Le fait qu\'un investisseur exige un rendement plus élevé si on lui demande de bloquer son argent pour 10 ans plutôt qu\'1 an', 'Les frais d\'entrée'],
      correct: 2, rationale: 'Privation de liquidité = rémunération supérieure.' },
    { q: 'En France, comment le temps influence-t-il souvent la fiscalité d\'un investissement ?',
      options: ['Plus l\'investissement est conservé longtemps, plus la fiscalité s\'adoucit (abattements, exonérations)', 'Les impôts augmentent avec le temps', 'L\'âge annule la CSG', 'Le temps n\'a aucun impact fiscal'],
      correct: 0, rationale: 'PEA défiscalisé après 5 ans, Assurance-vie après 8 ans...' },
    { q: '(Challenge) Qu\'est-ce que la "gestion pilotée à horizon" (PER, Assurance-vie) ?',
      options: ['Le robot achète au hasard', 'Elle bascule automatiquement l\'épargne des supports risqués vers des supports garantis (fonds euros) à l\'approche de la retraite', 'C\'est un investissement dans l\'aviation', 'C\'est une obligation légale de tout vendre'],
      correct: 1, rationale: 'Cela protège le capital d\'un krach final.' },
    { q: '(Challenge) Qu\'est-ce que le "Market Timing" ?',
      options: ['C\'est la seule méthode qui marche', 'C\'est obligatoire dans un PEA', 'L\'heure d\'ouverture de la bourse', 'Tenter d\'anticiper le marché (entrer/sortir), une stratégie vouée à l\'échec face au temps long ("Time in the market")'],
      correct: 3, rationale: 'Rater les 10 meilleurs jours de hausse détruit la performance.' },
  ],
  'w9-d1': [
    { q: 'Qui est redevable de la Taxe Foncière ?',
      options: ['Uniquement le locataire', 'Le propriétaire du bien immobilier au 1er janvier de l\'année d\'imposition', 'L\'agence immobilière', 'Le syndic de copropriété'],
      correct: 1, rationale: 'C\'est l\'impôt lié à la propriété. Que le bien soit habité par le propriétaire, loué à un tiers, ou vide, c\'est au propriétaire de payer.' },
    { q: 'Suite à la récente réforme fiscale achevée en 2023, que s\'est-il passé concernant la Taxe d\'Habitation sur les résidences PRINCIPALES ?',
      options: ['Elle a été doublée', 'Elle est passée à la charge des propriétaires', 'Elle a été totalement supprimée pour 100 % des foyers français (sur leur résidence principale)', 'Elle est prélevée à la source chaque mois'],
      correct: 2, rationale: 'C\'était une promesse présidentielle majeure. Plus aucun locataire ni propriétaire ne paie de taxe d\'habitation pour son logement principal.' },
    { q: 'Dans quel cas la Taxe d\'Habitation reste-t-elle applicable et obligatoire aujourd\'hui ?',
      options: ['Pour les maisons de plus de 100 m²', 'Pour les résidences secondaires et les logements vacants (selon les communes)', 'Pour les logements loués en meublé de tourisme', 'Les deux réponses B et C sont justes'],
      correct: 3, rationale: 'La suppression ne concernait que la résidence principale. Les résidences secondaires et les investissements locatifs non affectés à l\'habitation principale longue durée sont toujours lourdement taxés.' },
    { q: 'Quelle date l\'administration fiscale prend-elle en compte pour déterminer qui doit payer ces impôts locaux pour l\'année en cours ?',
      options: ['La situation au 1er janvier de l\'année d\'imposition', 'La situation au 31 décembre de l\'année d\'imposition', 'La date d\'achat du bien', 'Le jour du paiement de la taxe'],
      correct: 0, rationale: 'Si vous étiez propriétaire d\'une résidence secondaire le 1er janvier 2024, et que vous la vendez le 5 janvier 2024, c\'est VOUS qui recevrez l\'avis de taxe d\'habitation et de taxe foncière à l\'automne pour toute l\'année.' },
    { q: 'Sur quelle base de calcul ("assiette") s\'appuient la Taxe Foncière et la Taxe d\'Habitation ?',
      options: ['Sur la valeur de revente de la maison (le prix du marché)', 'Sur les revenus de l\'occupant (son salaire)', 'Sur la "Valeur Locative Cadastrale" (le loyer théorique que le bien pourrait produire s\'il était loué), abattue de 50% pour la taxe foncière', 'Sur le nombre d\'habitants dans la maison'],
      correct: 2, rationale: 'Cette base est ensuite multipliée par des taux votés chaque année par les collectivités locales (communes, intercommunalités).' },
    { q: 'Que finance principalement la Taxe Foncière ?',
      options: ['Le déficit de la Sécurité sociale', 'Le budget de l\'État central', 'Le budget des collectivités territoriales (communes et intercommunalités : écoles primaires, voirie, équipements sportifs locaux)', 'Les allocations familiales'],
      correct: 2, rationale: 'C\'est le principal impôt local (surtout depuis la fin de la taxe d\'habitation). Son montant varie donc énormément d\'une ville à l\'autre selon les besoins de la mairie.' },
    { q: 'Lors de l\'achat d\'un bien immobilier NEUF (VEFA ou construction), de quel avantage en matière de Taxe Foncière peut bénéficier le propriétaire ?',
      options: ['Exonération à vie', 'Une exonération totale ou partielle de la part communale pendant les 2 premières années suivant l\'achèvement (sous réserve d\'avoir déposé la déclaration H1 dans les 90 jours et que la mairie l\'autorise)', 'Une prime de la mairie', 'Un remboursement par le constructeur'],
      correct: 1, rationale: 'C\'est une incitation à la construction, mais attention, de plus en plus de mairies suppriment cette exonération pour renflouer leurs caisses.' },
    { q: 'En cours d\'année, un propriétaire vend sa maison. Comment se gère la Taxe Foncière entre le vendeur et l\'acheteur ?',
      options: ['L\'acheteur paie toute l\'année', 'Légalement, c\'est le vendeur (propriétaire au 1er janvier) qui doit la payer au fisc. Mais en pratique, le notaire intègre dans le compromis une répartition "prorata temporis" : l\'acheteur rembourse au vendeur la part de l\'année où il sera propriétaire', 'Le notaire paie la taxe', 'La taxe est annulée l\'année de la vente'],
      correct: 1, rationale: 'Si la vente a lieu le 1er juillet, l\'acheteur donnera au vendeur la moitié du montant de la taxe foncière chez le notaire.' },
    { q: '(Challenge) Qu\'est-ce que la nouvelle obligation déclarative "Gérer mes biens immobiliers" (GMBI) imposée à tous les propriétaires par la Direction Générale des Finances Publiques (DGFiP) ?',
      options: ['L\'obligation de prendre des photos de son intérieur', 'L\'obligation de déclarer chaque année en ligne l\'identité exacte des occupants de chaque bien immobilier possédé, afin de permettre au fisc de savoir qui doit payer la taxe d\'habitation (résidence secondaire) ou la taxe sur les logements vacants', 'L\'obligation de déclarer le prix du loyer perçu', 'L\'obligation d\'inviter un inspecteur des impôts chez soi'],
      correct: 1, rationale: 'Suite à la fin de la taxe d\'habitation sur la résidence principale, le fisc a perdu la trace des occupants. Cette déclaration permet de cibler les fraudeurs ou les résidences secondaires.' },
    { q: '(Challenge) Un propriétaire de 78 ans possède sa résidence principale. Ses revenus sont très modestes (inférieurs au plafond légal). Quel droit spécifique a-t-il concernant la Taxe Foncière ?',
      options: ['Il paie double car il a fini de payer son crédit', 'Il est totalement exonéré de la taxe foncière sur sa résidence principale', 'Il doit la transmettre à ses enfants', 'La taxe est payée par la caisse de retraite'],
      correct: 1, rationale: 'Les personnes âgées de plus de 75 ans, sous conditions strictes de ressources, bénéficient d\'une exonération d\'office pour préserver leur pouvoir d\'achat.' },
  ],
  'w9-d2': [
    { q: 'Qu\'est-ce que le portail "Info Retraite" (info-retraite.fr) ?',
      options: ['Le site privé d\'une banque commerciale', 'Le portail officiel et gratuit inter-régimes, regroupant les informations des 35 régimes de retraite obligatoires français, de base et complémentaires', 'Un simulateur non officiel géré par des courtiers', 'Un site d\'information pour les retraités uniquement'],
      correct: 1, rationale: 'C\'est le point d\'entrée unique. Il simplifie la vie des Français en regroupant toutes les informations de carrière de toutes les caisses sur un seul espace sécurisé.' },
    { q: 'À qui est destiné l\'espace personnel sur Info Retraite ?',
      options: ['Uniquement à ceux qui vont partir à la retraite dans l\'année', 'Uniquement aux retraités pour télécharger leur attestation fiscale', 'À tous les actifs (dès le premier emploi) et à tous les retraités', 'Seulement aux salariés du privé'],
      correct: 2, rationale: 'Dès votre premier job d\'été, un compte est alimenté. Il est essentiel de s\'y connecter jeune pour vérifier ses trimestres.' },
    { q: 'Quel est le moyen le plus simple et sécurisé pour se connecter à son compte Info Retraite ?',
      options: ['Créer un identifiant et attendre un mot de passe par la poste', 'Utiliser FranceConnect (avec ses identifiants des impôts, de l\'Assurance Maladie ou de l\'Identité Numérique La Poste)', 'Se connecter avec son compte Facebook', 'Entrer simplement son numéro de Sécurité Sociale'],
      correct: 1, rationale: 'C\'est le dispositif de l\'État garantissant une identification stricte et sécurisée sans avoir à mémoriser un énième mot de passe.' },
    { q: 'Quel document essentiel, récapitulant l\'ensemble de votre carrière (trimestres, salaires, points), pouvez-vous télécharger à tout moment sur ce site ?',
      options: ['Votre contrat de travail initial', 'Votre Relevé de Carrière tous régimes', 'Vos anciennes fiches de paie numérisées', 'Votre solde tout compte'],
      correct: 1, rationale: 'Ce document est la "photographie" de vos droits acquis. C\'est à vous de vérifier qu\'il ne manque aucune année travaillée.' },
    { q: 'Qu\'est-ce que le simulateur "M@rel" disponible sur l\'espace Info Retraite ?',
      options: ['Un jeu vidéo sur le monde de l\'entreprise', 'Le simulateur officiel qui permet d\'estimer le montant de sa future retraite à différents âges de départ, en se basant sur les données réelles de sa carrière', 'Un outil pour simuler un licenciement', 'Un outil pour racheter des années d\'études gratuitement'],
      correct: 1, rationale: 'Cet outil croise vos droits déjà acquis avec une projection de votre fin de carrière pour vous donner un chiffre net très précis, selon que vous partiez à 64, 65 ou 67 ans.' },
    { q: 'Si vous constatez un trou dans votre relevé de carrière (un emploi d\'été oublié), à partir de quel âge l\'espace Info Retraite permet-il généralement de demander une "Correction de carrière" approfondie ?',
      options: ['18 ans', '30 ans', '55 ans', '64 ans'],
      correct: 2, rationale: 'Bien qu\'on puisse signaler un oubli avant, c\'est à partir de 55 ans que les régimes de retraite déclenchent les procédures officielles de régularisation (sur présentation de justificatifs comme les bulletins de salaire).' },
    { q: 'Concernant le départ à la retraite, quelle simplification majeure a été apportée par le portail Info Retraite ?',
      options: ['Il paie la première pension en double', 'Le service "Demander ma retraite" permet de faire une seule et unique demande en ligne, qui est ensuite automatiquement transmise à TOUS les régimes auxquels vous avez cotisé (base et complémentaires)', 'Il suffit d\'appuyer sur un bouton pour partir à 60 ans', 'Il n\'y a plus de paperasse, l\'employeur s\'occupe de tout'],
      correct: 1, rationale: 'Avant, un polyactif devait faire 3 dossiers papiers différents (Sécu, Agirc-Arrco, etc.). Aujourd\'hui, un seul dossier en ligne suffit.' },
    { q: 'Que contient le RIS (Relevé Individuel de Situation) que l\'on peut générer sur le portail ?',
      options: ['Le montant des impôts à payer l\'année prochaine', 'Une synthèse personnalisée des droits acquis, envoyée automatiquement par courrier ou disponible en ligne tous les 5 ans à partir de 35 ans', 'Le résumé de vos arrêts maladie', 'Le montant de votre épargne bancaire'],
      correct: 1, rationale: 'C\'est le document légal d\'information, très lisible, qui vous avertit sur les anomalies éventuelles de votre carrière.' },
    { q: '(Challenge) Récemment, une nouvelle catégorie de contrats a été ajoutée à l\'espace Info Retraite pour éviter que des milliards d\'euros ne soient oubliés par les Français. De quoi s\'agit-il ?',
      options: ['Les livrets A oubliés', 'L\'affichage de vos contrats de retraite SUPPLÉMENTAIRE (PER, PERCO, anciens articles 83 et Madelin) ouverts par vos anciens employeurs ou vous-même, dont vous auriez oublié l\'existence', 'L\'affichage des héritages non réclamés', 'Les comptes courants dormants'],
      correct: 1, rationale: 'Des millions de salariés oubliaient l\'existence de comptes retraite ouverts par leurs anciens patrons. Info Retraite les centralise désormais (service "Mes contrats épargne retraite").' },
    { q: '(Challenge) Le conjoint décède. Le survivant doit demander la "pension de réversion". L\'espace Info Retraite propose-t-il un service dédié ?',
      options: ['Non, il faut obligatoirement se déplacer en agence', 'Non, il faut un avocat', 'Oui, le service "Demander ma réversion" permet, comme pour la retraite classique, de faire une demande unique en ligne qui interroge tous les régimes du défunt', 'Oui, mais seulement si le couple était pacsé'],
      correct: 2, rationale: 'C\'est un gain de temps et d\'énergie énorme pour les personnes endeuillées, évitant de contacter de multiples caisses pour faire valoir ses droits de survivant.' },
  ],
  'w9-d3': [
    { q: 'En droit civil et immobilier, qu\'est-ce que l\'indivision ?',
      options: ['Un bien qui ne peut pas être coupé en deux', 'La situation juridique où plusieurs personnes sont propriétaires ensemble (co-propriétaires) d\'un même bien ou d\'un même patrimoine', 'Un contrat de location à plusieurs', 'L\'interdiction de vendre sa maison'],
      correct: 1, rationale: 'Chaque indivisaire possède une "quote-part" (ex: 50% ou 1/3) du bien, mais cette part est abstraite, elle ne correspond pas à une pièce physique de la maison.' },
    { q: 'Quelles sont les deux situations les plus courantes qui créent une indivision sans que les personnes ne l\'aient particulièrement souhaité (indivision subie) ?',
      options: ['L\'achat d\'une voiture et la location d\'un studio', 'Une succession (les enfants héritent ensemble de la maison des parents) et un divorce (le couple marié en communauté se sépare)', 'La création d\'une entreprise et l\'achat d\'un parking', 'Le voisinage et la copropriété'],
      correct: 1, rationale: 'Lors d\'un décès, avant le partage définitif, tous les héritiers sont propriétaires en indivision. C\'est souvent là que naissent les conflits.' },
    { q: 'Comment se nomment les personnes qui partagent la propriété dans cette situation ?',
      options: ['Les colocataires', 'Les usufruitiers', 'Les indivisaires', 'Les actionnaires'],
      correct: 2, rationale: 'Ils détiennent chacun des droits de même nature sur le bien.' },
    { q: 'Dans une indivision classique, quelle est la règle pour prendre la décision la plus grave : "VENDRE" le bien immobilier (acte de disposition) ?',
      options: ['Il suffit de la majorité absolue (51%)', 'L\'accord de l\'indivisaire le plus âgé suffit', 'Il faut obligatoirement l\'UNANIMITÉ (l\'accord de 100% des indivisaires)', 'C\'est le notaire qui décide seul'],
      correct: 2, rationale: 'C\'est le grand point de blocage de l\'indivision. Si trois frères possèdent un bien et qu\'un seul refuse de vendre, la vente amiable est bloquée.' },
    { q: 'Pour les actes "d\'administration" courante (faire des réparations, renouveler un bail d\'habitation), quelle règle de majorité s\'applique ?',
      options: ['L\'unanimité (100%)', 'La majorité des deux tiers (2/3) des droits indivis', 'Celui qui a la plus grosse part décide de tout', 'Le vote du maire'],
      correct: 1, rationale: 'La loi a assoupli la gestion courante. Attention, on parle des 2/3 des "droits" (les pourcentages de détention), pas forcément des 2/3 des "personnes".' },
    { q: 'Si une indivision se passe mal, que dit le célèbre article 815 du Code Civil ?',
      options: ['"La majorité a toujours raison"', '"Le bien appartient au premier occupant"', '"Nul ne peut être contraint à demeurer dans l\'indivision et le partage peut toujours être provoqué"', '"L\'indivision dure 99 ans"'],
      correct: 2, rationale: 'C\'est une règle d\'ordre public. Si vous voulez sortir de l\'indivision, personne ne peut vous obliger à y rester (vous pouvez forcer le partage ou la vente en justice).' },
    { q: 'Que peuvent faire des indivisaires qui s\'entendent bien pour organiser sereinement la gestion du bien (ex: maison de famille) sur le long terme ?',
      options: ['Créer une association loi 1901', 'Signer une "convention d\'indivision" devant notaire (pour une durée déterminée, max 5 ans renouvelable) fixant les règles de gestion et la répartition des frais', 'Vendre le bien au plus jeune', 'Rien, la loi interdit de s\'organiser'],
      correct: 1, rationale: 'Ce contrat permet de désigner un gérant, de prévoir qui utilise la maison en juillet ou en août, et comment se paient la taxe foncière et les travaux.' },
    { q: 'Si un des indivisaires veut vendre sa quote-part (ex: ses 25%) à un étranger à la famille, de quel droit bénéficient les autres indivisaires ?',
      options: ['Aucun droit, il vend à qui il veut', 'Du droit d\'expulsion de l\'étranger', 'Du droit de préemption : ils sont prioritaires pour racheter cette part aux mêmes prix et conditions', 'Du droit d\'augmenter le prix'],
      correct: 2, rationale: 'Le vendeur doit notifier ses co-indivisaires par acte d\'huissier. Cela permet de garder le bien "dans la famille" et d\'éviter qu\'un inconnu ne s\'immisce dans l\'indivision.' },
    { q: '(Challenge) Trois sœurs héritent d\'une maison (chacune a 33,3% des parts, soit 1/3). Deux veulent vendre (soit 66,6% des droits, donc les 2/3), la dernière s\'y oppose et bloque tout. Que peuvent faire les deux premières ?',
      options: ['Rien, l\'unanimité étant requise, le dossier est définitivement classé', 'Elles peuvent vendre leurs deux tiers à la mairie sans l\'accord de la dernière', 'Grâce à la loi de 2009, détenant au moins les 2/3 des droits indivis, elles peuvent aller devant le tribunal pour obtenir l\'autorisation judiciaire de forcer la vente aux enchères (licitation) du bien', 'Elles peuvent louer la maison de force'],
      correct: 2, rationale: 'Pour lutter contre les indivisions totalement bloquées par un héritier récalcitrant, la loi autorise la vente forcée si les demandeurs pèsent au moins les 2/3 de l\'indivision.' },
    { q: '(Challenge) Lors d\'un achat immobilier entre concubins, quelle est la grande alternative juridique à l\'achat en "indivision" (qui est précaire) ?',
      options: ['La tontine', 'L\'achat au nom d\'un seul', 'La création d\'une SCI (Société Civile Immobilière) : ce n\'est plus l\'indivision, c\'est la société (personne morale) qui est propriétaire de l\'immeuble, et les concubins détiennent des parts de la société', 'L\'hypothèque'],
      correct: 2, rationale: 'La SCI permet de contrer les règles rigides de l\'indivision. Les concubins rédigent des statuts sur-mesure (désignation d\'un gérant, règles de majorité adaptées) pour protéger le patrimoine.' },
  ],
  'w9-d4': [
    { q: 'À quoi sert l\'assurance scolaire ?',
      options: ['À indemniser les professeurs', 'À couvrir la responsabilité de l\'établissement scolaire', 'À protéger l\'enfant contre les dommages qu\'il pourrait CAUSER à d\'autres (Responsabilité Civile) et contre les dommages corporels qu\'il pourrait SUBIR (Garantie Individuelle Accident)', 'À payer les fournitures scolaires perdues'],
      correct: 2, rationale: 'L\'enfant blesse un camarade avec un compas (RC), ou se casse une dent en tombant tout seul dans la cour (Garantie Individuelle Accident).' },
    { q: 'L\'assurance scolaire est-elle légalement OBLIGATOIRE pour les activités scolaires OBLIGATOIRES (inscrites dans l\'emploi du temps, comme le sport au gymnase) ?',
      options: ['Oui, sinon l\'enfant est exclu', 'Non, elle est facultative (bien que vivement recommandée par l\'Éducation Nationale)', 'Uniquement en école privée', 'Seulement au collège'],
      correct: 1, rationale: 'En principe, l\'accès à l\'enseignement gratuit et obligatoire ne peut être soumis à une assurance. Mais en cas de pépin, les parents paieront de leur poche.' },
    { q: 'Dans quel cas l\'assurance scolaire devient-elle OBLIGATOIRE et exigée par le chef d\'établissement ?',
      options: ['Pour apprendre à lire', 'Pour participer à toutes les activités FACULTATIVES organisées par l\'école (cantine, études dirigées, sorties scolaires avec pique-nique, voyages linguistiques, classes de neige)', 'Pour utiliser le CDI', 'Pour monter dans le bus de ville'],
      correct: 1, rationale: 'Dès que la sortie dépasse les horaires habituels ou inclut un repas/nuitée, le directeur refusera l\'enfant s\'il n\'est pas couvert.' },
    { q: 'Sur le volet "Responsabilité Civile" de l\'enfant, l\'assurance scolaire n\'est-elle pas un doublon avec un autre contrat des parents ?',
      options: ['Non, elle est unique', 'Oui, elle fait très souvent doublon avec la garantie "Responsabilité Civile Vie Privée" incluse dans le contrat Multirisque Habitation (MRH) des parents, qui couvre déjà les enfants', 'Oui, avec l\'assurance auto', 'Oui, avec la complémentaire santé'],
      correct: 1, rationale: 'Beaucoup de parents ignorent que leur assurance habitation couvre déjà les dégâts matériels et corporels que leur enfant cause à l\'école. Il suffit de demander l\'attestation à l\'assureur habitation.' },
    { q: 'Quel est alors le véritable intérêt d\'acheter une assurance scolaire spécifique si la Responsabilité Civile est déjà couverte par l\'assurance Habitation ?',
      options: ['Pour avoir un beau cartable', 'Pour la "Garantie Individuelle Accident", qui intervient si l\'enfant se blesse TOUT SEUL (sans responsable identifié), ce que l\'assurance Habitation classique ne couvre souvent pas', 'Pour réduire ses impôts', 'Pour éviter les devoirs'],
      correct: 1, rationale: 'Si l\'enfant tombe seul des escaliers ou de la balançoire, c\'est cette garantie qui paiera les frais médicaux non remboursés (lunettes, orthodontie, invalidité, rattrapage scolaire à domicile).' },
    { q: 'Quelle est la différence entre l\'assurance "Scolaire" simple et l\'assurance "Extra-Scolaire" (souvent 10 à 20€ plus chère par an) ?',
      options: ['L\'extra-scolaire couvre le petit frère', 'L\'extra-scolaire couvre l\'enfant 24h/24, 365 jours par an, en tout lieu (à l\'école, au club de sport, en vacances, le week-end, au centre aéré)', 'L\'extra-scolaire couvre les professeurs', 'Il n\'y a aucune différence'],
      correct: 1, rationale: 'C\'est la couverture la plus complète, très utile pour les enfants qui font du sport en club ou partent en colo.' },
    { q: 'En cas de casse des lunettes de vue de l\'enfant (très fréquent à l\'école), l\'assurance scolaire intervient-elle ?',
      options: ['Jamais, c\'est à la mutuelle de payer', 'Oui, la plupart des contrats incluent un forfait (souvent entre 200 et 400 €) pour rembourser le bris de lunettes ou les frais de soins dentaires suite à un accident', 'Oui, mais seulement si c\'est la faute du professeur', 'L\'école rachète les lunettes'],
      correct: 1, rationale: 'C\'est souvent l\'argument numéro un des assureurs. Cela compense les faibles remboursements de la Sécurité sociale sur l\'optique ou les dents cassées.' },
    { q: 'Êtes-vous obligé de souscrire l\'assurance scolaire proposée (et distribuée) par l\'école ou par les associations de parents d\'élèves à la rentrée (ex: MAE, etc.) ?',
      options: ['Oui, le directeur l\'impose', 'Non, c\'est interdit', 'Non, les parents ont le libre choix de leur assureur. Ils peuvent souscrire auprès de leur propre compagnie d\'assurance ou de leur banque', 'Oui, si l\'enfant est en maternelle'],
      correct: 2, rationale: 'L\'école ne peut faire que des "propositions". Votre agent général habituel a souvent des offres tout aussi compétitives.' },
    { q: '(Challenge) Un enfant est victime de racket régulier (vol de cartable, blouson) sur le trajet de l\'école. Les assurances scolaires récentes couvrent-elles ce préjudice ?',
      options: ['Non, c\'est du ressort exclusif de la police', 'Oui, les contrats modernes intègrent souvent une garantie "Vol des effets personnels / Racket" avec dépôt de plainte, ainsi qu\'un soutien psychologique', 'Uniquement pour les téléphones portables', 'L\'école rembourse directement'],
      correct: 1, rationale: 'Face à l\'évolution de la société, l\'assurance scolaire s\'adapte en incluant des garanties contre le racket ou le cyber-harcèlement (protection juridique).' },
    { q: '(Challenge) Un enfant mineur (15 ans) provoque volontairement et sciemment un incendie dans son collège. L\'assurance scolaire (Responsabilité Civile) des parents paiera-t-elle les millions de dégâts ?',
      options: ['Oui, l\'assurance paie toujours pour les mineurs, même pour une faute intentionnelle, car les parents sont civilement responsables des actes de leurs enfants', 'Non, la faute intentionnelle annule toujours la garantie, les parents devront payer de leur poche à vie', 'L\'État paie à la place des parents', 'Le principal du collège est jugé responsable'],
      correct: 0, rationale: 'C\'est une subtilité juridique. La faute intentionnelle n\'est inassurable que pour soi-même. Un parent étant responsable "de plein droit" de son enfant mineur, son assurance RC couvrira les dégâts causés par la malveillance de l\'enfant (sauf clauses d\'exclusion très spécifiques).' },
  ],
  'w9-d5': [
    { q: 'Dans le langage courant, le compromis de vente et la promesse de vente sont des "avant-contrats". À quelle étape se situent-ils ?',
      options: ['Après l\'acte authentique', 'Pendant la première visite', 'Entre l\'acceptation de l\'offre d\'achat et la signature de l\'acte définitif chez le notaire (qui interviendra souvent 3 mois plus tard)', 'Au moment de payer les impôts'],
      correct: 2, rationale: 'L\'avant-contrat fige et sécurise l\'accord. Il permet de bloquer le bien le temps que la banque accorde le crédit et que le notaire vérifie l\'urbanisme.' },
    { q: 'Juridiquement, quelle est la définition exacte du "Compromis de vente" (Promesse synallagmatique de vente) ?',
      options: ['Seul le vendeur s\'engage', 'C\'est un acte par lequel LE VENDEUR s\'engage à vendre ET L\'ACHETEUR s\'engage à acheter. L\'engagement est réciproque et ferme ("le compromis vaut vente")', 'L\'acheteur peut changer d\'avis jusqu\'à la fin', 'Une simple réservation orale'],
      correct: 1, rationale: 'Synallagmatique signifie que les deux parties ont des obligations l\'une envers l\'autre. Sauf si le crédit est refusé, les deux sont tenus d\'aller au bout.' },
    { q: 'À l\'inverse, qu\'est-ce qu\'une "Promesse unilatérale de vente" (PUV) ?',
      options: ['Les deux s\'engagent', 'Seul le VENDEUR s\'engage de façon ferme à vendre à un prix fixé. L\'ACHETEUR, lui, ne s\'engage pas à acheter, il dispose d\'une "option" d\'achat qu\'il est libre de lever ou non dans un délai donné', 'Seul l\'acheteur s\'engage, le vendeur peut vendre à quelqu\'un d\'autre', 'Une vente forcée'],
      correct: 1, rationale: 'La PUV laisse en théorie plus de liberté à l\'acheteur. Il réserve le bien (il a l\'exclusivité), mais n\'est pas obligé d\'acheter au final.' },
    { q: 'Puisque la "Promesse unilatérale de vente" immobilise le bien au profit de l\'acheteur (sans qu\'il s\'engage à acheter), quelle contrepartie financière le vendeur exige-t-il ?',
      options: ['Un loyer mensuel', 'Le paiement de la totalité du bien immédiatement', 'Le versement d\'une "indemnité d\'immobilisation" (souvent 5 à 10% du prix). Si l\'acheteur décide finalement de ne pas acheter (hors conditions suspensives), le vendeur garde cette somme en dédommagement', 'Le paiement des frais d\'agence'],
      correct: 2, rationale: 'Le vendeur ne bloque pas sa maison gratuitement. Si l\'acheteur "lève l\'option", l\'indemnité se transforme en acompte sur le prix. S\'il renonce pour convenance personnelle, il perd son argent.' },
    { q: 'Dans un "Compromis de vente", comment s\'appelle la somme (généralement 5 à 10%) versée par l\'acheteur chez le notaire ?',
      options: ['L\'indemnité d\'immobilisation', 'Le pot-de-vin', 'Le dépôt de garantie (ou acompte)', 'La commission de l\'agent'],
      correct: 2, rationale: 'Dans un compromis, ce n\'est pas le prix d\'une exclusivité, c\'est un premier versement (acompte) sur le prix de vente définitif, pour prouver le sérieux de l\'engagement.' },
    { q: 'Si l\'une des parties refuse de signer l\'acte définitif après un COMPROMIS de vente (hors refus de prêt ou rétractation légale), que peut faire l\'autre partie ?',
      options: ['Rien, c\'est la vie', 'Saisir le tribunal pour forcer judiciairement l\'exécution de la vente (obliger l\'autre à acheter ou vendre) et réclamer des dommages et intérêts (clause pénale)', 'Brûler le compromis', 'Prendre la maison de force'],
      correct: 1, rationale: 'Le "compromis valant vente", un changement d\'avis injustifié de dernière minute entraîne des poursuites lourdes en justice.' },
    { q: 'En matière de formalisme, quelle obligation fiscale stricte s\'applique à la Promesse Unilatérale de Vente (réalisée sous seing privé), mais PAS au Compromis de vente ?',
      options: ['Payer la taxe d\'habitation', 'L\'obligation d\'être enregistrée auprès des impôts dans un délai de 10 jours suivant l\'acceptation par l\'acheteur (coût : environ 125 €), sous peine de nullité absolue de la promesse', 'La publication dans le journal local', 'Le paiement comptant de la TVA'],
      correct: 1, rationale: 'Ce formalisme lourd de la promesse unilatérale explique pourquoi, en province et entre particuliers/agences, le compromis (qui n\'a pas besoin d\'être enregistré) est beaucoup plus utilisé.' },
    { q: 'Que ce soit un Compromis ou une Promesse de vente, l\'acheteur (non professionnel) a-t-il droit au délai de rétractation de la loi SRU ?',
      options: ['Uniquement pour le compromis', 'Uniquement pour la promesse', 'Oui, dans les deux cas, l\'acheteur dispose d\'un délai de 10 jours incompressibles (après réception du contrat purgé de ses annexes) pour annuler sans aucun motif ni pénalité', 'Non, le délai de rétractation n\'existe pas en immobilier'],
      correct: 2, rationale: 'C\'est le socle de protection du consommateur immobilier en France. Peu importe la forme du contrat, l\'acheteur a 10 jours pour réfléchir.' },
    { q: '(Challenge) Le vendeur et l\'acheteur ont signé un compromis. L\'acheteur demande un crédit à sa banque mais reçoit un refus officiel (non-obtention de prêt). Que devient le dépôt de garantie de 10% séquestré chez le notaire ?',
      options: ['Le vendeur le garde, car la vente est annulée', 'L\'agence immobilière le garde', 'La condition suspensive de prêt (d\'ordre public) n\'étant pas réalisée, le compromis est annulé (caduc) et l\'acheteur récupère intégralement son dépôt de garantie', 'La banque récupère la somme'],
      correct: 2, rationale: 'L\'acheteur de bonne foi est protégé s\'il ne peut pas financer son projet. Attention, s\'il a fait exprès de saboter son dossier de prêt, le vendeur peut réclamer la somme.' },
    { q: '(Challenge) Existe-t-il l\'inverse d\'une promesse unilatérale de vente : c\'est-à-dire une "Promesse unilatérale d\'ACHAT" ?',
      options: ['Non, c\'est illégal', 'Oui, c\'est le contrat par lequel seul l\'ACHETEUR s\'engage à acheter (et verse souvent un acompte), alors que le vendeur est totalement libre de lui vendre ou non', 'C\'est un synonyme de l\'offre d\'achat', 'Oui, et le vendeur est engagé'],
      correct: 1, rationale: 'C\'est un contrat extrêmement rare et déséquilibré (souvent utilisé par les marchands de biens). C\'est très dangereux pour un particulier (il est bloqué, alors que le vendeur continue de chercher un meilleur prix).' },
  ],
};
