/* Questions de la semaine 25. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w25-d0': [
    { q: 'En finance, quel est le principe de base d\'un "fonds d\'investissement" (OPCVM) ?',
      options: ['Il s\'agit d\'un compte épargne géré par le maire', 'C\'est un produit réservé aux entreprises du CAC 40', 'Mutualiser (mettre en commun) l\'argent de milliers de particuliers pour investir massivement dans un grand nombre d\'actions ou d\'obligations, la gestion étant confiée à un expert professionnel', 'C\'est un logiciel qui trade tout seul'],
      correct: 2, rationale: 'Cela permet à un petit épargnant d\'accéder à la Bourse avec 100 €, en bénéficiant de la diversification et de l\'expertise d\'un gérant professionnel.' },
    { q: 'Quelles sont les deux grandes formes juridiques des fonds d\'investissement (OPCVM) en France ?',
      options: ['Les SARL et les SAS', 'Les SICAV (Sociétés d\'Investissement à Capital Variable) et les FCP (Fonds Communs de Placement)', 'Les livrets et les comptes à terme', 'Les PER et les PEA'],
      correct: 1, rationale: 'En achetant une SICAV vous devenez actionnaire, en achetant un FCP vous devenez copropriétaire du fonds. Dans la pratique quotidienne pour l\'épargnant, la différence est presque invisible.' },
    { q: 'Comment s\'appelle le prix (la valeur) d\'une part de fonds d\'investissement que vous achetez ou revendez ?',
      options: ['Le taux directeur', 'Le coupon', 'La Valeur Liquidative (VL)', 'Le dividende brut'],
      correct: 2, rationale: 'La VL est calculée en divisant la valeur totale de tous les actifs détenus par le fonds, par le nombre de parts en circulation. (Ex: le fonds vaut 1 million €, il y a 10 000 parts, la VL est de 100 €).' },
    { q: 'Quelle est la différence entre un fonds à "gestion active" et un fonds à "gestion passive" (ETF) ?',
      options: ['Le fonds passif n\'est ouvert que le week-end', 'Dans la gestion active, le gérant sélectionne lui-même les meilleures entreprises pour tenter de battre la moyenne du marché. Dans la gestion passive, l\'ordinateur se contente de copier un indice boursier', 'Il n\'y a aucune différence', 'La gestion active est interdite en Europe'],
      correct: 1, rationale: 'La gestion active nécessite des armées d\'analystes, ce qui justifie des frais de gestion beaucoup plus élevés que la gestion passive (ETF).' },
    { q: 'Qu\'appelle-t-on les "frais d\'entrée" (ou frais de souscription) d\'un fonds classique ?',
      options: ['Un pourcentage prélevé (ex : 2 %) une seule fois, au moment où vous investissez. Sur 1 000 € versés, seuls 980 € iront réellement travailler sur les marchés', 'L\'abonnement mensuel de la banque', 'Un impôt payé à l\'État', 'Une taxe qui vous est remboursée l\'année suivante'],
      correct: 0, rationale: 'Ces frais amputent violemment la performance de départ. Aujourd\'hui, les banques en ligne et les bons courtiers proposent souvent de réduire ces frais d\'entrée à 0 %.' },
    { q: 'Quel document normalisé de 2 ou 3 pages devez-vous OBLIGATOIREMENT lire avant d\'acheter un fonds (pour connaître ses frais, ses risques et sa stratégie) ?',
      options: ['Le Journal Officiel', 'Le Kbis', 'Le DICI (Document d\'Information Clé pour l\'Investisseur), aujourd\'hui appelé DIC (Document d\'Information Clé)', 'L\'avis d\'imposition du gérant'],
      correct: 2, rationale: 'C\'est la "carte d\'identité" réglementaire du fonds. Si la banque ne vous le fournit pas avant l\'achat, elle commet une faute grave.' },
    { q: 'Dans ce DIC, le niveau de risque du fonds est résumé par l\'indicateur SRI (anciennement SRRI). Quelle est l\'échelle utilisée ?',
      options: ['Une note de A à G', 'Une note sur 100', 'Une échelle chiffrée allant de 1 (risque et rendement faibles) à 7 (risque et rendement très élevés)', 'Un code couleur'],
      correct: 2, rationale: 'Un fonds monétaire (très sécurisé) sera classé 1/7. Un fonds investi sur des start-ups de la Tech américaine sera classé 6/7 ou 7/7.' },
    { q: 'Quelle est la fréquence habituelle de "liquidité" d\'un OPCVM classique (à quelle fréquence pouvez-vous acheter ou vendre des parts) ?',
      options: ['Tous les 10 ans', 'Quotidienne (tous les jours) ou hebdomadaire (une fois par semaine). La Valeur Liquidative est recalculée à cette même fréquence', 'Une seule fois par an, le 31 décembre', 'Uniquement à la retraite'],
      correct: 1, rationale: 'Contrairement à l\'immobilier, les parts de fonds d\'investissement boursiers sont très liquides. Si vous demandez la vente le mardi, vous aurez l\'argent dans la semaine.' },
    { q: '(Challenge) Certains fonds performants prélèvent des "Frais de surperformance". Pour protéger l\'investisseur des abus, un mécanisme est imposé : le "High Water Mark". De quoi s\'agit-il ?',
      options: ['La banque ne paie pas d\'impôts sur ses gains', 'Le gérant ne peut prélever ces frais bonus QUE si la valeur du fonds dépasse son "plus haut niveau historique". Il ne touchera pas de prime pour avoir simplement "rattrapé" une baisse de l\'année précédente', 'Les frais sont doublés s\'il pleut', 'Le fonds investit dans l\'eau'],
      correct: 1, rationale: 'Cela évite qu\'un gérant qui perd 20 % l\'année 1, et gagne 20 % l\'année 2, ne vous facture une prime de succès l\'année 2 alors que vous n\'avez même pas récupéré votre mise initiale.' },
    { q: '(Challenge) Qu\'est-ce qu\'une part de fonds dite "Clean Share" (très recherchée par les investisseurs avertis) par rapport à une part standard (dite "Retail") ?',
      options: ['Une part réservée aux entreprises de nettoyage', 'Une action qui ne paie pas de dividendes', 'C\'est illégal en Europe', 'C\'est une part du fonds "nettoyée" de toute rétrocommission (le gérant ne reverse rien à la banque qui vous vend le produit). Ses frais de gestion annuels sont donc beaucoup plus faibles'],
      correct: 3, rationale: 'Les banques vous vendent les parts "chargées" (ex: 2% de frais) car elles touchent 1% dessus en secret. Les "Clean shares" (souvent 0,8% de frais) sont l\'avenir de la transparence financière.' },
  ],
  'w25-d1': [
    { q: 'Quelle est la règle d\'or fiscale absolue concernant la vente de la Résidence Principale en France ?',
      options: ['La plus-value réalisée (le gain à la revente) est TOTALEMENT exonérée d\'impôt sur le revenu et de prélèvements sociaux, quel que soit son montant', 'Elle est taxée à 30 %', 'Elle est taxée, sauf si on rachète une autre maison', 'L\'exonération n\'est que de 50 %'],
      correct: 0, rationale: 'C\'est la plus célèbre et la plus puissante de toutes les niches fiscales françaises. Un gain d\'un million d\'euros sur sa résidence principale file net dans la poche du vendeur.' },
    { q: 'Comment le fisc définit-il la "Résidence Principale" pour accorder cette exonération magique ?',
      options: ['Le logement où résident habituellement et effectivement les membres du foyer fiscal (la majeure partie de l\'année)', 'N\'importe quelle maison achetée depuis 10 ans', 'Le logement où l\'on passe ses vacances l\'été', 'Le lieu où l\'on gare sa voiture'],
      correct: 0, rationale: 'Si vous avez deux maisons, la principale est celle où dorment les enfants pour aller à l\'école, celle reliée à votre travail et à votre feuille d\'impôt.' },
    { q: 'Faut-il OBLIGATOIREMENT réinvestir l\'argent de la vente dans une nouvelle résidence principale pour bénéficier de l\'exonération ?',
      options: ['Oui, dans un délai de 2 ans', 'Oui, mais seulement la moitié de l\'argent', 'Uniquement pour les plus-values dépassant 50 000 €', 'Non, vous pouvez utiliser l\'argent comme vous le voulez (faire le tour du monde, investir en bourse), l\'exonération est acquise d\'office'],
      correct: 3, rationale: 'C\'est une confusion très fréquente avec d\'autres dispositifs. Pour la résidence principale, l\'exonération est un droit inconditionnel lors de la vente.' },
    { q: 'Un propriétaire met sa résidence principale en vente, mais déménage (pour son nouveau travail) avant d\'avoir trouvé un acheteur. Le bien est donc vide. Conserve-t-il l\'exonération ?',
      options: ['Oui, le fisc tolère un "délai normal de vente" (souvent toléré jusqu\'à 1 an, voire plus selon le marché), À CONDITION que le bien soit resté totalement inoccupé depuis le déménagement', 'Non, l\'exonération est annulée le jour du déménagement', 'Seulement s\'il laisse ses meubles', 'Uniquement si la mairie est d\'accord'],
      correct: 0, rationale: 'L\'administration comprend qu\'on ne vend pas une maison en 2 jours. Tant que le bien était la résidence principale AU JOUR de la mise en vente, l\'exonération tient.' },
    { q: 'Un propriétaire vend sa maison et, LE MÊME JOUR, il vend un terrain nu attenant qui lui servait de grand jardin ou le garage situé en face. Ces dépendances sont-elles exonérées ?',
      options: ['Seule la maison est exonérée', 'Les dépendances sont exonérées à 50 %', 'Oui, les "dépendances immédiates et nécessaires" (caves, garages, jardin) vendues en même temps que la résidence principale bénéficient de la même exonération totale', 'Le garage oui, mais jamais le jardin'],
      correct: 2, rationale: 'Si vous vendez le garage 3 mois APRÈS la maison, ce sera en revanche considéré comme une vente de terrain/parking taxée à plein pot !' },
    { q: 'Une exception très spéciale a été créée pour la PREMIÈRE vente d\'une Résidence SECONDAIRE. À quelle condition stricte cette vente peut-elle être exonérée d\'impôts sur la plus-value ?',
      options: ['Si le vendeur l\'a eue en héritage', 'Si l\'acheteur est un de ses enfants', 'Si l\'argent sert à rembourser des dettes', 'Le vendeur ne doit pas avoir été propriétaire de sa résidence principale les 4 dernières années, ET il doit remployer l\'argent de la vente dans les 24 mois pour acheter (enfin) sa résidence principale'],
      correct: 3, rationale: 'Cela aide ceux qui n\'ont pas les moyens d\'acheter à Paris, ont investi en province, et vendent ce bien pour enfin s\'acheter un toit pour y vivre.' },
    { q: 'Vous possédez votre résidence principale au travers d\'une SCI (Société Civile Immobilière) avec votre conjoint. La vendez-vous avec l\'exonération ?',
      options: ['Oui, si la SCI est "transparente" (à l\'IR) et met gratuitement le bien à la disposition de ses associés pour leur résidence principale', 'L\'exonération est plafonnée à 10 000 €', 'Les impôts sont doublés en SCI', 'Non, une SCI est une entreprise, la plus-value est toujours taxée'],
      correct: 0, rationale: 'Le fisc "regarde à travers" la SCI familiale pour voir les personnes physiques qui y vivent réellement.' },
    { q: 'Une personne âgée quitte sa résidence principale pour entrer en EHPAD (maison de retraite médicalisée). Perd-elle l\'exonération pour la vente de sa maison ?',
      options: ['Non, elle conserve l\'exonération pendant un délai de 2 ans après son entrée en EHPAD, sous conditions (la maison doit rester vide et les revenus de la personne doivent être modestes)', 'L\'EHPAD devient propriétaire de la maison', 'Oui, la maison est taxée dès l\'entrée en EHPAD', 'Seulement si la maison est à Paris'],
      correct: 0, rationale: 'C\'est une mesure de protection sociale pour laisser le temps aux familles de vider et vendre la maison de l\'aïeul sereinement.' },
    { q: '(Challenge) Que se passe-t-il si, pendant le fameux "délai normal de vente" (la maison est vide le temps de trouver un acheteur), le propriétaire décide de la louer quelques mois sur Airbnb pour gagner un peu d\'argent ?',
      options: ['L\'État prend les revenus Airbnb', 'Il perd purement, simplement et définitivement l\'exonération au titre de la résidence principale. La revente subira l\'impôt classique sur la plus-value !', 'Rien, c\'est légal et encouragé', 'L\'exonération n\'est que de 50 %'],
      correct: 1, rationale: 'C\'est une erreur fatale. En la louant, même 2 semaines, la maison perd juridiquement son statut exclusif de résidence principale au moment de la signature chez le notaire.' },
    { q: '(Challenge) Un médecin utilise 30 % de la surface de sa résidence principale pour y installer son cabinet médical (qu\'il a affecté à son patrimoine professionnel pour le déduire fiscalement). À la revente de la maison, que se passe-t-il ?',
      options: ['Le fisc prend 100 % de la vente', 'La maison est totalement exonérée', 'Le notaire devra scinder la vente : 70 % de la plus-value sera exonérée (la partie habitation), mais les 30 % restants subiront la lourde imposition des plus-values professionnelles', 'L\'acheteur doit payer la taxe professionnelle'],
      correct: 2, rationale: 'Si vous avez passé 20 ans à déduire les murs de votre cabinet médical sur le compte de votre entreprise, le fisc récupèrera son "cadeau" à la revente.' },
  ],
  'w25-d2': [
    { q: 'Les périodes pendant lesquelles on est au chômage et indemnisé (par Pôle Emploi / France Travail) comptent-elles pour la retraite de base (Sécurité sociale) ?',
      options: ['Non, c\'est une année blanche', 'Uniquement si on a plus de 50 ans', 'Oui, elles permettent de valider des "Trimestres Assimilés" (pour chaque période de 50 jours de chômage indemnisé, on valide 1 trimestre)', 'La CAF paie les trimestres'],
      correct: 2, rationale: 'Le système français est solidaire. Il évite qu\'une période d\'inactivité involontaire ne détruise la durée d\'assurance de l\'assuré.' },
    { q: 'Ces trimestres "assimilés" de chômage sont-ils valables pour atteindre la durée requise permettant d\'avoir le "Taux plein" (50 %) à l\'âge légal (64 ans) ?',
      options: ['Oui, un trimestre assimilé a la même valeur qu\'un trimestre cotisé pour atteindre la durée totale d\'assurance et obtenir le taux plein', 'Uniquement pour la moitié de leur valeur', 'Seulement pour les femmes', 'Non, ils ne servent qu\'à faire joli sur le relevé'],
      correct: 0, rationale: 'Si la loi vous demande 172 trimestres au total, avoir 160 trimestres travaillés et 12 de chômage vous accorde parfaitement le taux plein.' },
    { q: 'En revanche, pour pouvoir partir en retraite de façon ANTICIPÉE via le dispositif "Carrières Longues", ces trimestres de chômage sont-ils pris en compte ?',
      options: ['Ils sont totalement exclus', 'Oui, mais cette prise en compte est PLAFONNÉE : la loi ne tolère qu\'un maximum de 4 trimestres de chômage indemnisé dans toute la carrière pour le décompte des trimestres "cotisés" exigés', 'Uniquement en cas de licenciement économique', 'Oui, en nombre illimité'],
      correct: 1, rationale: 'Le départ anticipé exige un effort de travail réel. Avoir passé 5 ans de sa vie au chômage vous disqualifie souvent pour la "Carrière Longue".' },
    { q: 'Qu\'en est-il de la Retraite Complémentaire (Agirc-Arrco) pendant une période de chômage indemnisé ?',
      options: ['L\'Agirc-Arrco est supprimée', 'Vous acquérez gratuitement des POINTS de retraite complémentaire, qui s\'ajouteront à votre compte, comme si vous étiez payé sur la base d\'un salaire journalier de référence', 'L\'assuré doit les payer de sa poche', 'Les points sont divisés par quatre'],
      correct: 1, rationale: 'Pôle Emploi prélève une petite part de cotisations sur vos allocations pour financer l\'achat de ces points complémentaires.' },
    { q: 'Que se passe-t-il pour vos trimestres de retraite si vous êtes au chômage, mais que vous n\'êtes PLUS indemnisé (vous arrivez "en fin de droits") ?',
      options: ['La validation des trimestres s\'arrête le jour même, la solidarité prend fin', 'Pôle Emploi annule les trimestres passés', 'La Sécurité Sociale valide gratuitement des trimestres de chômage non indemnisé pendant 1 an (voire jusqu\'à 5 ans maximum sous des conditions très strictes d\'âge et de cotisation passée)', 'L\'État vous donne la retraite immédiate'],
      correct: 2, rationale: 'Le filet de sécurité se prolonge encore un peu pour ceux qui ne retrouvent pas de travail (notamment les plus de 55 ans).' },
    { q: 'Peut-on être au chômage (toucher les allocations) ET percevoir en même temps une retraite à "taux plein" (cumul intégral) ?',
      options: ['C\'est interdit, la liquidation d\'une retraite à taux plein entraîne automatiquement l\'arrêt du versement des allocations chômage', 'Oui, c\'est légal', 'Uniquement les mois d\'été', 'Seulement si on demande l\'autorisation au maire'],
      correct: 0, rationale: 'Si France Travail (Pôle Emploi) découvre que vous avez tous vos trimestres pour la retraite à taux plein, ils vous radient et vous envoient à la Caisse de Retraite. On ne cumule pas les deux solidarités.' },
    { q: 'Si un senior de 61 ans est licencié et s\'inscrit au chômage, quelle garantie "protectrice" la loi lui offre-t-elle souvent jusqu\'à sa retraite ?',
      options: ['La gratuité des transports', 'Le chômage des seniors dure plus longtemps (jusqu\'à 27 mois, selon réformes). De plus, l\'Allocation de Solidarité Spécifique (ASS) peut parfois prendre le relais pour l\'amener sans trou jusqu\'à l\'âge de la retraite', 'Le droit de ne pas payer d\'impôts', 'Le doublement de ses indemnités'],
      correct: 1, rationale: 'Le chômage des seniors est un enjeu social majeur. Leurs règles d\'indemnisation sont généralement assouplies par rapport aux jeunes.' },
    { q: 'Dans le calcul du "Salaire Annuel Moyen" (les 25 meilleures années de votre carrière qui fixeront le montant de la pension de la Sécurité sociale), comment les indemnités de chômage sont-elles comptées ?',
      options: ['Elles sont ajoutées comme un salaire normal', 'L\'État ajoute un bonus de 10 %', 'Elles SONT EXCLUES. Bien que le chômage valide des trimestres, il ne génère aucun "salaire reporté". Les années de chômage "tirent" donc vers le bas la moyenne de vos 25 meilleures années', 'Elles sont multipliées par deux'],
      correct: 2, rationale: 'C\'est le revers de la médaille. Avoir des trimestres c\'est bien, mais une année avec 0€ de salaire inscrit fait mécaniquement baisser la pension finale.' },
    { q: '(Challenge) Qu\'est-ce que le dispositif du "Maintien des droits" au chômage pour les seniors de 62 ans ou plus ?',
      options: ['La possibilité de rester chômeur toute sa vie', 'Si un chômeur atteint la fin de ses allocations (fin de droits) à 62 ans ou plus, s\'il n\'a pas encore ses trimestres pour la retraite et s\'il a cotisé au moins 12 ans dans sa vie, Pôle Emploi "prolonge" son indemnisation jusqu\'à ce qu\'il atteigne le taux plein', 'L\'annulation de la décote de retraite', 'La prime de fin de carrière'],
      correct: 1, rationale: 'Ce "miracle" du droit social évite à des milliers de seniors usés par des carrières hachées de se retrouver au RSA juste avant la ligne d\'arrivée de la retraite.' },
    { q: '(Challenge) Lors de la signature d\'une Rupture Conventionnelle à 60 ans, le salarié touche une grosse "Indemnité de rupture". Pôle Emploi va-t-il l\'indemniser immédiatement ?',
      options: ['Non, Pôle Emploi appliquera un "délai de carence" (différé d\'indemnisation spécifique), qui peut repousser le premier paiement du chômage de plusieurs mois (jusqu\'à 150 jours) en fonction du montant des indemnités "supra-légales" perçues', 'L\'employeur paiera le chômage', 'Oui, dès le lendemain matin', 'Uniquement s\'il a pris un avocat'],
      correct: 0, rationale: 'Le senior qui pense faire le pont jusqu\'à la retraite avec son chômage doit intégrer qu\'il ne touchera rien de l\'État pendant les 5 premiers mois.' },
  ],
  'w25-d3': [
    { q: 'Qu\'est-ce que le "Mandat de Protection Future" (MPF) ?',
      options: ['Une assurance vie bloquée jusqu\'à 80 ans', 'Un contrat par lequel une personne saine d\'esprit organise À L\'AVANCE sa propre protection (ou celle de son enfant handicapé), en désignant librement la ou les personnes (mandataires) qui seront chargées de s\'occuper d\'elle et de son patrimoine le jour où elle n\'en sera plus capable (maladie, accident, vieillesse)', 'Une procuration bancaire ordinaire', 'Un testament pour choisir ses héritiers'],
      correct: 1, rationale: 'C\'est le contrat de la dignité. Au lieu que ce soit un juge qui choisisse qui va gérer votre vie, c\'est vous qui décidez, alors que vous avez encore toute votre tête.' },
    { q: 'Quelle est l\'immense différence entre un Mandat de Protection Future et les mesures classiques de Tutelle ou de Curatelle ?',
      options: ['Le mandat de protection future est organisé "sur-mesure", sans intervention ni contrôle permanent du Juge des Contentieux de la Protection (ex-juge des tutelles), offrant une gestion familiale douce et rapide', 'Le mandat coûte plus cher en impôts', 'Il n\'y a aucune différence, le juge décide toujours', 'La tutelle permet de conduire, pas le mandat'],
      correct: 0, rationale: 'La tutelle est judiciaire, longue à mettre en place et très infantilisante. Le MPF est un "contrat de confiance" de droit privé.' },
    { q: 'À quel moment très précis ce mandat (rédigé des années auparavant) va-t-il s\'activer et PRENDRE EFFET ?',
      options: ['Lorsque le médecin traitant habituel signe une lettre', 'Lorsqu\'un médecin "expert" (inscrit sur la liste du procureur de la République) certifie que le mandant ne peut plus pourvoir seul à ses intérêts, le mandat étant ensuite visé par le greffier du tribunal', 'À la date fixée dans le contrat (ex: à 80 ans pile)', 'Uniquement après le décès'],
      correct: 1, rationale: 'Il ne suffit pas que le fils dise "Papa perd la tête". Un protocole médical strict valide l\'incapacité avant de donner les clés du patrimoine au mandataire.' },
    { q: 'Sur quels "périmètres" d\'action (domaines) le mandat peut-il donner des pouvoirs au mandataire ?',
      options: ['Il peut porter sur la "Protection de la personne" (choix du lieu de vie, de l\'EHPAD, décisions médicales) ET/OU sur la "Protection du patrimoine" (payer les factures, gérer les comptes, louer la maison)', 'Uniquement sur les soins médicaux', 'Strictement sur l\'argent, la loi interdit de gérer la personne', 'Uniquement sur l\'héritage'],
      correct: 0, rationale: 'On peut même nommer la fille pour gérer la partie médicale (protection de la personne) et le fils banquier pour gérer l\'argent (protection du patrimoine).' },
    { q: 'Le mandat peut être rédigé sous "Seing privé" (sur papier libre ou formulaire Cerfa). Quelle est la grande limite des pouvoirs de ce format ?',
      options: ['Le mandataire ne peut agir que pendant 1 an', 'Le mandataire peut tout faire, sans exception', 'Les pouvoirs sont limités aux actes de gestion courante (payer le loyer). Pour VENDRE la maison du mandant (acte de disposition), l\'autorisation du Juge restera obligatoire', 'L\'argent de la banque est bloqué'],
      correct: 2, rationale: 'Le mandat sous seing privé est simple, mais ses pouvoirs sont faibles. Si le parent part en maison de retraite, vendre sa maison restera un calvaire judiciaire.' },
    { q: 'À l\'inverse, que permet le Mandat de protection future "Notarié" (réalisé par Acte Authentique chez le notaire) ?',
      options: ['D\'annuler la carte vitale', 'Le mandataire obtient des pouvoirs étendus. Il peut réaliser SEUL les actes de disposition importants (comme vendre la maison de famille ou faire des placements financiers), SANS demander l\'autorisation du juge', 'Le notaire prend toutes les décisions', 'De déshériter les enfants'],
      correct: 1, rationale: 'C\'est pour cette raison que le MPF notarié est extrêmement recommandé par tous les gestionnaires de patrimoine.' },
    { q: 'Peut-on annuler ou modifier un Mandat de Protection Future ?',
      options: ['Non, il est définitif dès la signature', 'Uniquement par décision du maire', 'Seulement après sa mise en œuvre', 'Oui, le mandant (celui qui l\'a rédigé) peut le révoquer ou le modifier librement TANT QU\'IL A ENCORE TOUTE SA TÊTE (avant l\'activation médicale du mandat)'],
      correct: 3, rationale: 'Si la confiance est rompue avec la personne désignée, le mandant déchire le mandat et en refait un autre.' },
    { q: 'Puisque le juge ne contrôle pas les comptes au quotidien, comment la loi évite-t-elle que le mandataire "vide les comptes" (fraude) de son parent devenu vulnérable ?',
      options: ['Le compte est bloqué à 1 000 €', 'Il ne peut pas utiliser la carte bancaire', 'La loi oblige le mandataire à faire un "Inventaire du patrimoine" à l\'ouverture, puis à rendre des "Comptes de gestion annuels" qui seront vérifiés par la personne désignée comme "Contrôleur" dans le mandat (ou par le notaire si acte authentique)', 'L\'État paie un avocat'],
      correct: 2, rationale: 'La confiance n\'exclut pas le contrôle. Nommer un contrôleur (ex: le frère du mandataire) garantit que l\'argent sert bien au bien-être du parent.' },
    { q: '(Challenge) Qu\'est-ce que le Mandat de protection future "Pour Autrui" ?',
      options: ['Des parents d\'un enfant mineur handicapé (ou lourdement malade) rédigent un mandat pour organiser à l\'avance la prise en charge et la gestion du patrimoine de cet enfant pour le jour où eux-mêmes décèderont ou ne pourront plus s\'en occuper', 'Donner ses organes', 'Protéger le chat de la maison', 'Nommer un tuteur pour les voisins'],
      correct: 0, rationale: 'C\'est l\'angoisse majeure des parents d\'enfants dépendants : "Qui s\'en occupera quand je serai mort ?". Ce mandat règle le problème avec une personne de confiance désignée à l\'avance.' },
    { q: '(Challenge) Une fois le Mandat de protection future "activé" par le médecin et le greffe, le mandant (le malade) perd-il tous ses droits civiques ?',
      options: ['Oui, il est frappé d\'incapacité totale', 'Il est déclaré mineur par la loi', 'Il doit être interné', 'Non. Contrairement à la tutelle, le MPF n\'est pas un régime d\'incapacité juridique privant le mandant de ses droits. Le mandant conserve ses droits, le mandataire agit simplement "en son nom" comme un super-représentant'],
      correct: 3, rationale: 'C\'est une grande marque de respect pour le malade. S\'il a encore quelques moments de lucidité, il peut théoriquement signer des contrats lui-même (sauf si le juge prononce une tutelle additionnelle).' },
  ],
  'w25-d4': [
    { q: 'En France, quelle est la première étape ABSOLUMENT OBLIGATOIRE pour que la garantie "Catastrophes Naturelles" (Cat Nat) de votre assurance s\'active ?',
      options: ['Avoir l\'autorisation du maire', 'Un dégât supérieur à 10 000 €', 'La publication d\'un Arrêté Interministériel de "Catastrophe Naturelle" au Journal Officiel, listant précisément les communes concernées et la période de l\'événement', 'Que le président en parle à la télévision'],
      correct: 2, rationale: 'Si ce décret de l\'État n\'est pas publié pour votre ville, l\'assurance refusera de faire jouer la garantie Cat Nat (même si votre maison est sous l\'eau).' },
    { q: 'Laquelle de ces garanties est toujours EXCLUE du régime des Catastrophes Naturelles (elle possède son propre régime d\'indemnisation classique) ?',
      options: ['La coulée de boue', 'L\'inondation', 'L\'effet du vent (Tempêtes, Ouragans, Cyclones) ou de la grêle', 'Le tremblement de terre'],
      correct: 2, rationale: 'C\'est le piège classique. Les toitures arrachées par le vent ou détruites par la grêle relèvent de la garantie classique "Tempête/Grêle/Neige" de l\'assurance. Pas besoin d\'attendre un décret ministériel.' },
    { q: 'La garantie Catastrophe Naturelle est-elle une option payante facultative à rajouter à son contrat habitation (MRH) ?',
      options: ['Oui, très chère', 'Non, la loi impose son inclusion OBLIGATOIRE dans tous les contrats d\'assurance dommages (multirisque habitation, assurance auto, assurance pro)', 'Seulement dans le sud de la France', 'Uniquement si la maison a plus de 5 ans'],
      correct: 1, rationale: 'Sur votre quittance, vous verrez qu\'une "surprime Cat Nat" légale de 20% est prélevée par obligation sur votre garantie dommages.' },
    { q: 'Depuis la récente réforme, de combien de temps dispose l\'assuré pour déclarer son sinistre à l\'assureur APRÈS la publication de l\'arrêté au Journal Officiel ?',
      options: ['3 jours', '10 jours', '30 jours maximum (le délai légal a été allongé)', '1 an'],
      correct: 2, rationale: 'Le gouvernement a porté le délai (qui était de 10 jours) à 30 jours pour soulager les victimes dont les vies sont ravagées et qui n\'ont pas la tête à la paperasse immédiate.' },
    { q: 'Quel est le système de la "Franchise" en cas de Catastrophe Naturelle ?',
      options: ['La franchise est décidée par l\'expert', 'C\'est une franchise LÉGALE, fixée par l\'État, identique pour tous et non rachetable par contrat. Actuellement, elle est de 380 € pour les habitations/autos (hors sécheresse)', 'Il n\'y a jamais de franchise', 'La franchise est de 10 % du prix de la maison'],
      correct: 1, rationale: 'Même si votre contrat stipulait une franchise incendie de 100 €, le code des assurances écrase votre contrat et vous impose les 380 € décidés par la loi.' },
    { q: 'Suite à la récente loi (loi Baudu), qu\'a décidé l\'État concernant le sort des victimes dont la maison devient inhabitable après la catastrophe ?',
      options: ['Ils doivent se débrouiller', 'La prise en charge des "Frais de relogement d\'urgence" (hôtel, location) devient obligatoire dans tous les contrats pour une durée minimale garantie (souvent 6 mois)', 'La mairie doit les loger à vie', 'Ils reçoivent des tentes'],
      correct: 1, rationale: 'Avant cette loi, certaines assurances "low cost" abandonnaient les victimes à la rue sans prendre en charge l\'hébergement pendant les longs mois de travaux.' },
    { q: 'Votre voiture est garée dans la rue. Une inondation la submerge et détruit le moteur. Votre assurance vous dit : "Le décret est paru, mais vous n\'êtes pas indemnisé". Pourquoi est-ce possible ?',
      options: ['Car l\'eau est douce', 'L\'eau n\'était pas assez haute', 'Vous n\'étiez assuré qu\'au "Tiers simple" (Responsabilité Civile pure). La garantie Cat Nat ne s\'active que sur les véhicules ayant au minimum une garantie Dommages (Vol, Incendie, Tous Risques)', 'La voiture a plus de 2 ans'],
      correct: 2, rationale: 'L\'inclusion de la garantie Cat Nat n\'est obligatoire que si vous avez souscrit à des garanties dommages. Si vous avez la formule minimale au Tiers de chez Tiers, la voiture est perdue.' },
    { q: 'Les dommages indirects (ex: les aliments perdus dans le congélateur suite à la coupure de courant provoquée par l\'inondation) sont-ils pris en charge par le régime légal des Cat Nats ?',
      options: ['Uniquement la viande', 'Non, la loi Cat Nat couvre les dommages DIRECTS. Les aliments (dommages indirects) relèvent des conditions classiques et des options de votre contrat (garantie perte de denrées)', 'L\'État envoie des bons d\'achat', 'Oui, au kilo'],
      correct: 1, rationale: 'L\'assureur indemnisera les murs trempés (Cat Nat), mais refusera souvent les biftecks si vous n\'avez pas l\'option spécifique dans votre contrat.' },
    { q: '(Challenge) Un sinistre majeur et très sournois ravage des dizaines de milliers de maisons en France (fissures énormes des murs) et relève du régime Cat Nat. Quel est ce phénomène, qui impose par ailleurs une franchise majorée de 1 520 € ?',
      options: ['La chute de météorites', 'Le gel profond', 'Le RGA : le Retrait-Gonflement des Argiles (sécheresse). La terre argileuse se rétracte en été et gonfle en hiver, cassant littéralement les fondations des maisons', 'Les tremblements de terre'],
      correct: 2, rationale: 'Ce "péril invisible" coûte des milliards aux assureurs. La procédure d\'indemnisation est un cauchemar technique nécessitant des années d\'expertises des sols (micropieux).' },
    { q: '(Challenge) Vous habitez en zone rouge inondable. Après deux inondations, votre assureur résilie votre contrat. Aucun autre assureur ne veut vous prendre. Que devez-vous faire ?',
      options: ['Vendre à la mairie pour 1 euro', 'Rouler avec une fausse assurance', 'Saisir le BCT (Bureau Central de Tarification). C\'est un organisme d\'État qui a le pouvoir "d\'OBLIGER" un assureur de votre choix à vous couvrir pour les garanties obligatoires, en fixant lui-même le tarif (souvent dissuasif mais légal)', 'Habiter sans assurance'],
      correct: 2, rationale: 'Personne ne doit être exclu de l\'assurance pour le risque habitation/auto. Le BCT rétablit l\'équité pour les "pestiférés" de l\'assurance.' },
  ],
  'w25-d5': [
    { q: 'Juridiquement, qu\'est-ce qu\'une "Copropriété" ?',
      options: ['Un immeuble appartenant à un seul grand propriétaire', 'Un hôtel avec plusieurs locataires', 'Un immeuble divisé en "Lots". Chaque lot comprend une partie PRIVATIVE (votre appartement exclusif) ET une "quote-part" (une fraction) des parties COMMUNES de l\'immeuble (le toit, les murs, l\'escalier, l\'ascenseur)', 'Une maison partagée en famille'],
      correct: 2, rationale: 'Vous n\'êtes jamais totalement maître chez vous en copropriété, car les murs porteurs de votre salon appartiennent en commun à tous les copropriétaires !' },
    { q: 'Qu\'est-ce que le "Règlement de copropriété" ?',
      options: ['Un simple conseil de voisinage', 'Le contrat fondamental (l\'acte juridique) qui fixe les règles de fonctionnement de l\'immeuble, définit les parties privatives/communes, et surtout, détaille la clé de RÉPARTITION DES CHARGES entre les propriétaires', 'Le règlement affiché dans le hall', 'La loi de la Mairie'],
      correct: 1, rationale: 'C\'est la loi de l\'immeuble. Si vous voulez transformer un appartement en cabinet dentaire ou en Airbnb, c\'est ce document qui vous l\'autorise ou vous l\'interdit.' },
    { q: 'Dans une copropriété, comment calcule-t-on le "poids" de votre vote aux assemblées et la somme que vous devez payer pour l\'entretien du toit ?',
      options: ['Le plus riche paie le plus', 'Un appartement = un vote, tout le monde paie la même chose', 'Grâce aux "Tantièmes" ou "Millièmes" : c\'est la quote-part des parties communes affectée à votre lot (selon sa superficie, sa consistance, sa situation). Si vous avez 100/1000èmes, vous paierez 10 % de la facture du toit', 'Par tirage au sort annuel'],
      correct: 2, rationale: 'Un T4 avec terrasse au dernier étage aura beaucoup plus de millièmes qu\'un studio au rez-de-chaussée. Il pèsera plus lourd lors des votes, mais paiera plus de charges.' },
    { q: 'On distingue les charges "Générales" (conservation de l\'immeuble) des charges "Spéciales". Quel est le critère pour répartir une charge spéciale (ex : les frais de l\'ascenseur) ?',
      options: ['La règle de "l\'Utilité" (réelle ou théorique) : un propriétaire au rez-de-chaussée sans cave ne paiera aucune charge d\'ascenseur, tandis que celui du 5ème étage paiera très cher', 'On divise par le nombre d\'habitants', 'Tout le monde paie, c\'est la solidarité', 'Seuls les propriétaires de plus de 60 ans paient'],
      correct: 0, rationale: 'Si un équipement n\'a aucune utilité, même théorique, pour un lot (ex: rez-de-chaussée pour l\'ascenseur), la loi (art. 10) interdit de lui faire payer la facture.' },
    { q: 'Le propriétaire reçoit "l\'appel de charges" trimestriel. Qui est responsable du paiement de la totalité de ces charges auprès du syndic ?',
      options: ['Le locataire et le propriétaire à 50/50', 'L\'agence immobilière', 'Uniquement la CAF', 'Exclusivement le Propriétaire (le copropriétaire). C\'est à lui seul de payer le syndic, quitte à récupérer ensuite "la part récupérable" auprès de son locataire'],
      correct: 3, rationale: 'Le syndic ne connaît pas le locataire. Si le locataire ne paie pas ses loyers, le propriétaire reste l\'unique débiteur vis-à-vis de la copropriété.' },
    { q: 'Parmi les charges payées par le propriétaire, certaines sont dites "Charges récupérables" (ou locatives). Qu\'est-ce que cela signifie ?',
      options: ['Des charges que la Mairie rembourse', 'Ce sont les charges qui profitent directement au locataire (ex: l\'eau, les ordures ménagères, l\'entretien ménager des couloirs, le contrat d\'entretien de l\'ascenseur). Le bailleur est autorisé par la loi à les facturer au locataire en plus du loyer', 'Les honoraires du syndic', 'La construction d\'un nouveau parking'],
      correct: 1, rationale: 'La liste des charges récupérables est fixée par décret (1987). Le bailleur ne peut rien inventer (ex: les honoraires du syndic ne sont jamais récupérables).' },
    { q: 'En location nue, comment le propriétaire facture-t-il concrètement ces "charges récupérables" à son locataire tout au long de l\'année ?',
      options: ['Il lui fait payer la totalité à Noël', 'Il lui facture une "Provision sur charges" mensuelle (une avance estimée). Une fois par an, il fait la "Régularisation des charges" en comparant l\'avance payée avec la facture réelle du syndic, et demande (ou rend) la différence', 'C\'est l\'État qui prélève le locataire', 'Le locataire paie directement le syndic'],
      correct: 1, rationale: 'Si le locataire a payé 50€/mois (600€/an) de provisions, et que le syndic justifie de 700€ de charges récupérables, le locataire devra faire un chèque de 100€ pour régulariser l\'année.' },
    { q: 'En copropriété, qui est le "Syndic" ?',
      options: ['Un avocat désigné par l\'État', 'Un copropriétaire élu pour faire la loi', 'Le mandataire de la copropriété (un professionnel ou un bénévole), désigné par l\'AG pour administrer l\'immeuble, tenir la comptabilité, recouvrer les charges et faire exécuter les travaux votés', 'Le juge du tribunal'],
      correct: 2, rationale: 'C\'est "l\'Intendant" de l\'immeuble. Il applique les décisions prises par les copropriétaires et veille à la santé du bâtiment.' },
    { q: '(Challenge) Qu\'est-ce que le "Fonds de Travaux" Loi Alur, obligatoire sur vos appels de charges ?',
      options: ['Une amende pour travaux illégaux', 'Une épargne obligatoire (minimum 5 % du budget prévisionnel annuel) prélevée sur tous les copropriétaires, pour créer un matelas de sécurité destiné à payer d\'éventuels gros travaux futurs (toiture, ravalement)', 'L\'argent de poche du syndic', 'L\'argent réservé pour peindre les volets'],
      correct: 1, rationale: 'Cette loi empêche les copropriétés de se retrouver ruinées le jour où il faut refaire la façade. Attention : l\'argent de ce fonds "appartient au lot". Si vous vendez, vous ne récupérez pas votre part du fonds.' },
    { q: '(Challenge) Un appartement est revendu en juin. Lors de l\'Assemblée Générale de mars, un énorme ravalement de façade de 10 000 € a été voté. L\'appel de fonds (le jour où il faut payer) a lieu en septembre. Qui doit légalement payer les 10 000 € ?',
      options: ['La mairie', 'Moitié le vendeur, moitié l\'acheteur', 'Le Vendeur, car c\'est lui qui a voté les travaux', 'C\'est ACHETEUR qui doit payer le syndic. La loi impose que c\'est celui qui est "propriétaire au moment de l\'exigibilité" (le jour de l\'appel de fonds) qui paie'],
      correct: 3, rationale: 'C\'est une règle comptable aveugle du droit de la copropriété. Bien évidemment, le notaire a le devoir de rédiger une clause privée entre le vendeur et l\'acheteur pour que le vendeur rembourse l\'acheteur s\'il s\'y était engagé à la vente !' },
  ],
};
