/* Questions de la semaine 4. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w4-d0': [
    { q: 'Quelle est la grande différence conceptuelle entre "épargner" et "investir" ?',
      options: ['C\'est exactement la même chose', 'L\'investissement est réservé aux millionnaires', 'Épargner rapporte plus', 'Épargner, c\'est mettre en sécurité. Investir, c\'est accepter une part de risque pour obtenir un meilleur rendement'],
      correct: 3, rationale: 'L\'épargne protège, l\'investissement fait travailler l\'argent.' },
    { q: 'Quelle enveloppe est massivement privilégiée en France pour investir à long terme grâce à ses avantages fiscaux sur la transmission ?',
      options: ['L\'Assurance-vie', 'Le Livret Jeune', 'Le compte courant', 'Le Plan d\'Épargne Logement (PEL)'],
      correct: 0, rationale: 'Elle permet d\'investir sur les marchés et offre des abattements en cas de décès.' },
    { q: 'Quel est le principe d\'un investissement en bourse (actions) ?',
      options: ['On prête de l\'argent à la banque', 'On parie sur le climat', 'On acquiert des parts de propriété d\'entreprises, pariant sur leur croissance et bénéfices', 'On achète de l\'or'],
      correct: 2, rationale: 'L\'actionnaire est copropriétaire de l\'entreprise.' },
    { q: 'Qu\'est-ce que "l\'effort d\'épargne" mensuel ?',
      options: ['Le temps passé à surveiller ses comptes', 'La somme financière prélevée chaque mois sur son budget courant pour l\'investir', 'Les impôts payés', 'Les frais bancaires'],
      correct: 1, rationale: 'Fixer cet effort permet de lisser l\'investissement de manière indolore.' },
    { q: 'Avant de réaliser son tout premier investissement risqué, quelle étape est indispensable ?',
      options: ['Emprunter à la consommation', 'Demander l\'accord de la mairie', 'Vider ses comptes courants', 'Avoir constitué une épargne de précaution solide (sur livrets)'],
      correct: 3, rationale: 'Le matelas de précaution évite d\'être forcé de vendre ses actions à perte en cas de coup dur.' },
    { q: 'Quel biais psychologique est le plus grand ennemi de l\'investisseur débutant ?',
      options: ['La panique et les émotions (vendre par peur quand ça baisse, acheter par euphorie quand c\'est haut)', 'La patience', 'Le calcul mental', 'La diversification'],
      correct: 0, rationale: 'En finance, il faut rester rationnel et conserver son cap à long terme.' },
    { q: 'Lorsqu\'on parle de "frais" d\'investissement (gestion, courtage), quel est leur impact ?',
      options: ['Ils sont remboursés par l\'État', 'Ils amputent directement la performance finale de l\'investissement', 'Ils sont indolores', 'Ils augmentent le rendement'],
      correct: 1, rationale: 'Minimiser les frais est l\'un des rares leviers de rentabilité garantis.' },
    { q: 'Pourquoi dit-on qu\'il faut investir "en accord avec son profil" ?',
      options: ['Pour des raisons de mode', 'C\'est une obligation légale', 'Parce qu\'un investissement trop volatil pour soi finira toujours par être revendu au pire moment par stress', 'Pour éviter les impôts'],
      correct: 2, rationale: 'Le meilleur investissement est celui qu\'on comprend et qu\'on arrive à conserver.' },
    { q: '(Challenge) Un investisseur loge des Unités de Compte (UC) dans son assurance-vie. Quel est le risque ?',
      options: ['Le risque de perte en capital est entièrement porté par l\'investisseur (la valeur fluctue avec les marchés)', 'Le rendement est fixe', 'Le capital est totalement garanti par l\'assureur', 'Les UC sont interdites en France'],
      correct: 0, rationale: 'Dans l\'assurance-vie, le moteur de performance (UC) nécessite d\'accepter le risque boursier.' },
    { q: '(Challenge) Qu\'est-ce que l\'investissement programmé (DCA - Dollar Cost Averaging) ?',
      options: ['Investir tout son capital le même jour', 'Investir en devises étrangères', 'Un prélèvement de l\'État', 'Investir une somme fixe à intervalles réguliers (ex: 100€/mois) pour lisser le coût d\'achat moyen'],
      correct: 3, rationale: 'C\'est la méthode idéale pour investir sereinement sans chercher "le bon moment".' },
  ],
  'w4-d1': [
    { q: 'Quel est le principe d\'une "déduction fiscale" ?',
      options: ['C\'est une somme que le fisc vous donne en espèces', 'C\'est un montant qui vient se soustraire de votre REVENU imposable brut, avant le calcul de l\'impôt', 'C\'est un montant qui se soustrait directement de l\'IMPÔT final à payer', 'C\'est la suppression de la TVA sur vos achats'],
      correct: 1, rationale: 'La déduction agit "en haut" du calcul : elle diminue la base sur laquelle sera calculé votre impôt.' },
    { q: 'Quel est le principe d\'une "réduction d\'impôt" ?',
      options: ['C\'est une baisse du revenu imposable', 'C\'est une remise accordée par les commerçants', 'C\'est une somme qui est déduite directement du montant de L\'IMPÔT calculé', 'C\'est l\'annulation automatique de tous les prélèvements sociaux'],
      correct: 2, rationale: 'La réduction intervient "en bas" du calcul. Une fois que l\'impôt est calculé, on soustrait directement la réduction de cette somme à payer.' },
    { q: 'Quelle est la différence majeure entre une "réduction d\'impôt" et un "crédit d\'impôt" ?',
      options: ['Aucune, ce sont des synonymes exacts', 'Le crédit d\'impôt ne concerne que les entreprises', 'Si la réduction est supérieure à l\'impôt dû, le solde est perdu. Si le crédit d\'impôt est supérieur, l\'État vous rembourse la différence', 'La réduction est remboursable, le crédit d\'impôt est perdu'],
      correct: 2, rationale: 'Si vous devez 500 € d\'impôts et avez une réduction de 800 €, votre impôt tombe à 0 € (les 300 € sont perdus). Si c\'est un crédit d\'impôt, l\'État vous fait un chèque de 300 €.' },
    { q: 'Pourquoi l\'impact financier d\'une "déduction" dépend-il de la Tranche Marginale d\'Imposition (TMI) du contribuable ?',
      options: ['Parce que la déduction est interdite pour les hauts revenus', 'Parce que gommer 1000 € de revenus rapporte plus d\'économies d\'impôt à quelqu\'un taxé à 41% (410 € gagnés) qu\'à quelqu\'un taxé à 11% (110 € gagnés)', 'Parce que la TMI fixe le prix des impôts locaux', 'Ce n\'est pas vrai, la déduction dépend de l\'âge'],
      correct: 1, rationale: 'La déduction efface vos derniers euros gagnés. Elle est donc particulièrement puissante pour les foyers fortement imposés (TMI à 30%, 41% ou 45%).' },
    { q: 'Lequel de ces mécanismes est une "déduction" fiscale ?',
      options: ['Faire un don à une association (Croix-Rouge, Coluche)', 'Employer une femme de ménage à domicile', 'Les versements volontaires sur un Plan Épargne Retraite (PER)', 'Investir dans la loi Pinel'],
      correct: 2, rationale: 'L\'argent versé sur le PER vient se déduire des revenus professionnels déclarés, faisant baisser la base imposable.' },
    { q: 'Lequel de ces mécanismes génère une "réduction d\'impôt" ?',
      options: ['Les frais professionnels (frais réels, indemnités kilométriques)', 'Les pensions alimentaires versées à un enfant majeur', 'Investir dans un dispositif immobilier Pinel', 'Les cotisations syndicales'],
      correct: 2, rationale: 'Le Pinel vous donne droit à un pourcentage du prix d\'achat du bien qui viendra se soustraire directement du montant de vos impôts annuels.' },
    { q: 'L\'efficacité d\'une réduction d\'impôt varie-t-elle selon votre TMI (Tranche Marginale d\'Imposition) ?',
      options: ['Oui, comme pour la déduction', 'Non, si la réduction est de 1500 €, elle enlève 1500 € d\'impôts à tout le monde, que l\'on soit riche ou modeste (tant que l\'on paie au moins 1500 € d\'impôts)', 'Oui, les TMI hautes ont des réductions doublées', 'Non, car la TMI s\'applique uniquement au quotient familial'],
      correct: 1, rationale: 'Contrairement à la déduction, la réduction agit sur l\'impôt final. Un euro de réduction = un euro d\'impôt en moins, pour tous.' },
    { q: 'Qu\'est-ce que le "plafond global des niches fiscales" ?',
      options: ['L\'interdiction d\'avoir une TMI supérieure à 45%', 'La limite fixée par l\'État (généralement 10 000 € par an) au montant total des avantages fiscaux (réductions et crédits d\'impôt) qu\'un foyer peut cumuler', 'Le nombre maximum de fenêtres dans un investissement Pinel', 'Le montant maximum que l\'on peut donner à ses enfants'],
      correct: 1, rationale: 'Pour éviter que les contribuables très aisés n\'effacent totalement leurs impôts en multipliant les investissements, l\'État a plafonné ces avantages.' },
    { q: '(Challenge) Monsieur Y a une TMI de 30%. Il décide de verser 2 000 € sur son Plan Épargne Retraite (mécanisme de déduction). Quelle économie d\'impôt "à la louche" va-t-il réaliser ?',
      options: ['2 000 €', '600 € (30% de 2000)', '0 €, car la déduction ne s\'applique qu\'au décès', '300 €'],
      correct: 1, rationale: 'En déduisant 2000 € de ses revenus, il évite de payer l\'impôt de sa tranche marginale (30%) sur cette somme. 2000 x 30% = 600 € d\'impôt en moins.' },
    { q: '(Challenge) Madame Z doit payer 800 € d\'impôt sur le revenu. Elle a fait des dons aux œuvres qui lui donnent droit à une réduction d\'impôt de 1 000 €. Elle a également des frais de garde d\'enfant qui lui donnent un crédit d\'impôt de 400 €. Que se passe-t-il ?',
      options: ['L\'impôt est effacé, et l\'État lui fait un chèque de 600 €', 'L\'impôt tombe à zéro. La réduction restante de 200 € est perdue. L\'État lui fait ensuite un chèque de 400 € pour son crédit d\'impôt.', 'Elle paiera 800 € et sera remboursée plus tard', 'Les dons s\'annulent avec les frais de garde'],
      correct: 1, rationale: 'Dans l\'ordre : l\'impôt de 800 € est épongé par les 1000 € de réduction (les 200 € restants de la réduction sont définitivement perdus). Le solde de l\'impôt est donc à zéro. Ensuite, l\'État lui verse ses 400 € de crédit d\'impôt en cash.' },
  ],
  'w4-d2': [
    { q: 'Qu\'est-ce que le "relevé de carrière" ?',
      options: ['Un document rédigé par l\'employeur pour justifier d\'un licenciement', 'Le CV officiel que l\'on transmet à Pôle Emploi', 'Un document récapitulatif édité par l\'Assurance Retraite qui retrace l\'ensemble des droits acquis (trimestres et revenus) tout au long de la vie professionnelle', 'Un contrat d\'assurance-vie'],
      correct: 2, rationale: 'C\'est le document clé qui sert de base au calcul de votre future pension de retraite et de votre date de départ.' },
    { q: 'À partir de quel âge un assuré peut-il consulter son relevé de carrière ?',
      options: ['Uniquement à partir de 55 ans', '2 ans avant la retraite', 'À tout âge, dès qu\'il a occupé son premier emploi déclaré, via son espace personnel en ligne (info-retraite)', 'Uniquement après sa mort pour ses héritiers'],
      correct: 2, rationale: 'Le suivi est continu. Il est vivement conseillé de le consulter régulièrement au cours de sa vie pour ne pas accumuler des erreurs.' },
    { q: 'Quelles périodes "oubliées" sont le plus souvent manquantes sur le relevé de carrière d\'un jeune actif ?',
      options: ['Les années de CDI à temps plein', 'Les jobs d\'été, petits boulots étudiants, stages rémunérés au-delà d\'un certain seuil ou services militaires', 'Les périodes de chômage de plus de 3 ans', 'Les années de détachement'],
      correct: 1, rationale: 'Les petits contrats, souvent anciens et gérés par de petits employeurs, peuvent comporter des erreurs de transmission de cotisations (numéro de sécu erroné, etc).' },
    { q: 'Qu\'est-ce que le RIS (Relevé Individuel de Situation) ?',
      options: ['Un bulletin de santé obligatoire', 'Un document d\'information sur la retraite, envoyé automatiquement tous les 5 ans à partir de 35 ans, regroupant les droits de tous les régimes (base et complémentaire)', 'Le relevé des impôts à la source', 'Une taxe sur la retraite'],
      correct: 1, rationale: 'C\'est un droit à l\'information légal pour permettre aux actifs de piloter leur fin de carrière.' },
    { q: 'Comment les informations (trimestres et salaires) remontent-elles jusqu\'à la caisse de retraite pour garnir le relevé de carrière ?',
      options: ['C\'est au salarié d\'envoyer ses fiches de paie tous les mois', 'Par le biais des déclarations sociales nominatives (DSN) effectuées obligatoirement par les employeurs auprès de l\'URSSAF/Caisses de retraite', 'Par un sondage annuel de l\'INSEE', 'Grâce aux relevés bancaires'],
      correct: 1, rationale: 'Le processus est automatisé. Cependant, des failles techniques ou des entreprises défaillantes peuvent causer des trous dans la carrière.' },
    { q: 'Que doit faire un assuré s\'il constate un "trou" (un emploi non comptabilisé) dans son relevé de carrière ?',
      options: ['Attendre 64 ans et demander une dérogation', 'Demander une régularisation de carrière auprès de sa caisse, en fournissant impérativement des preuves (fiches de paie, contrats de travail, attestations Pôle Emploi)', 'Poursuivre son employeur au pénal immédiatement', 'Rien, le trou se comble tout seul avec l\'inflation'],
      correct: 1, rationale: 'C\'est pour cette raison qu\'il est capital de conserver toutes ses fiches de paie (en version papier ou numérique sécurisée) jusqu\'à la liquidation de sa retraite.' },
    { q: 'Quelle est la conséquence d\'un trimestre non validé (oublié) sur le relevé de carrière lors du départ à la retraite ?',
      options: ['Il rallonge le temps de travail d\'un mois', 'Il peut entraîner une décote (baisse définitive de la pension) ou repousser la date à laquelle l\'assuré pourra partir à taux plein', 'Il annule la totalité de la pension', 'Il n\'a aucune conséquence si on est cadre'],
      correct: 1, rationale: 'Un trimestre oublié est un trimestre perdu pour le calcul. Cela impacte directement la durée d\'assurance.' },
    { q: 'Les périodes de chômage indemnisé figurent-elles sur le relevé de carrière ?',
      options: ['Non, seul le travail compte', 'Oui, elles sont généralement comptabilisées sous forme de "trimestres assimilés" (50 jours de chômage = 1 trimestre)', 'Oui, mais seulement pour la première année de travail', 'Uniquement pour les fonctionnaires'],
      correct: 1, rationale: 'Le système de retraite français est solidaire et valide des trimestres lors des périodes d\'inactivité involontaire (chômage, maladie).' },
    { q: '(Challenge) Bien qu\'on puisse signaler une erreur à tout moment, à partir de quel âge le service en ligne "Régulariser ma carrière" permet-il un traitement approfondi et officiel par les conseillers retraite ?',
      options: ['25 ans', '40 ans', '55 ans', '65 ans'],
      correct: 2, rationale: 'L\'assurance retraite concentre ses moyens d\'investigation officiels sur les assurés qui approchent de la retraite (à partir de 55 ans), moment où la reconstitution exacte devient prioritaire.' },
    { q: '(Challenge) Concernant les majorations de trimestres pour les enfants (maternité/éducation), sont-elles visibles sur le relevé de carrière d\'une mère dès la naissance de l\'enfant ?',
      options: ['Oui, le lendemain de l\'accouchement', 'Non, ces trimestres sont généralement validés et intégrés au relevé de carrière qu\'au moment du traitement du dossier de départ en retraite (ou via une mise à jour spécifique demandée)', 'Uniquement si la CAF donne son accord', 'Oui, mais seulement à la majorité de l\'enfant'],
      correct: 1, rationale: 'Les droits liés aux enfants nécessitent souvent de fournir le livret de famille à la caisse de retraite lors de la liquidation ou du bilan de carrière.' },
  ],
  'w4-d3': [
    { q: 'En l\'absence de testament, comment le partenaire de PACS survivant est-il considéré par la loi lors de la succession de son conjoint décédé ?',
      options: ['Comme un héritier naturel (il reçoit 50% du patrimoine)', 'Comme un héritier réservataire (il ne peut être déshérité)', 'Comme un tiers absolu (il n\'est pas un héritier légal et ne reçoit strictement rien)', 'Comme le propriétaire exclusif de tous les biens'],
      correct: 2, rationale: 'C\'est le grand piège du PACS. Sans testament, le partenaire survivant n\'a aucun droit dans la succession. Ce sont les enfants (ou les parents/frères/sœurs du défunt) qui héritent de tout.' },
    { q: 'En matière de "droits de succession" (impôts à payer sur l\'héritage), quelle est la fiscalité appliquée au conjoint survivant MARIÉ ?',
      options: ['Il paie 60% d\'impôts', 'Il paie 20% d\'impôts', 'Il bénéficie d\'une exonération totale (0 € de droits de succession)', 'L\'impôt dépend du nombre d\'enfants'],
      correct: 2, rationale: 'Depuis la loi TEPA de 2007, le conjoint marié survivant ne paie aucun impôt sur la part d\'héritage qu\'il reçoit.' },
    { q: 'Si un partenaire de PACS hérite grâce à un testament rédigé en sa faveur, quelle fiscalité lui sera appliquée ?',
      options: ['Il paiera 60% d\'impôts car le PACS n\'est pas le mariage', 'Il bénéficiera de la même exonération totale (0%) que les couples mariés', 'Il sera taxé sur la base de la tranche à 20%', 'Il devra payer une taxe d\'habitation majorée'],
      correct: 1, rationale: 'Fiscalement, le PACS et le Mariage sont identiques en cas de décès (0 impôt). Mais juridiquement, le PACS exige impérativement un testament pour transmettre.' },
    { q: 'Qu\'est-ce que le "droit temporaire au logement" dont bénéficie le conjoint survivant (marié ou pacsé) ?',
      options: ['Le droit d\'occuper le logement gratuitement pendant 1 an après le décès (frais pris en charge par la succession)', 'Le droit de revendre la maison en 2 mois', 'Le droit d\'aller à l\'hôtel aux frais de l\'État', 'Une taxe sur les résidences secondaires'],
      correct: 0, rationale: 'C\'est un droit d\'ordre public. Que l\'on soit marié ou pacsé, on ne peut pas être mis à la porte de la résidence principale pendant la première année suivant le décès.' },
    { q: 'Qu\'en est-il du "droit viager au logement" (droit de vivre dans le logement jusqu\'à la fin de ses jours) ?',
      options: ['Il s\'applique automatiquement pour le mariage et le PACS', 'Il peut être demandé par le conjoint marié, mais il N\'EXISTE PAS pour le partenaire de PACS', 'C\'est un droit réservé uniquement au PACS', 'Il a été supprimé en 2020'],
      correct: 1, rationale: 'Le conjoint marié a un droit d\'usage et d\'habitation à vie (sauf si privé par testament authentique). Le partenaire de PACS, passé l\'année de droit temporaire, peut être forcé à partir par les héritiers.' },
    { q: 'Concernant la retraite, le partenaire de PACS survivant peut-il toucher la "pension de réversion" (une part de la retraite du défunt) ?',
      options: ['Oui, dans les mêmes conditions que le mariage', 'Oui, s\'ils étaient pacsés depuis plus de 5 ans', 'Non, la pension de réversion est strictement réservée aux couples mariés (ou ex-conjoints divorcés)', 'Uniquement si le partenaire de PACS ne travaille pas'],
      correct: 2, rationale: 'Le PACS n\'ouvre aucun droit à la pension de réversion, ce qui constitue une différence sociale majeure.' },
    { q: 'Si un couple pacsé achète une maison ensemble (50/50), quelle est l\'action primordiale à réaliser pour se protéger mutuellement en cas de décès ?',
      options: ['Rien, le survivant récupérera d\'office les 50% du défunt', 'Rédiger des testaments croisés (chacun lègue sa part à l\'autre) pour éviter l\'indivision avec la belle-famille', 'Détruire le contrat de PACS', 'Souscrire un crédit à la consommation'],
      correct: 1, rationale: 'Sans testament, les 50% du défunt iront à ses parents/frères/sœurs ou enfants. Le survivant se retrouvera propriétaire de la maison avec sa belle-famille.' },
    { q: 'Le conjoint survivant MARIÉ est-il considéré comme un "héritier réservataire" ?',
      options: ['Non, jamais', 'Oui, mais uniquement si le défunt n\'a laissé AUCUN enfant ou descendant (dans ce cas, un quart du patrimoine lui est garanti)', 'Oui, il prend toujours tout le patrimoine', 'Uniquement si le couple était marié sous le régime de la communauté universelle'],
      correct: 1, rationale: 'Si le défunt n\'a pas d\'enfants, on ne peut pas déshériter totalement son époux(se) : 1/4 du patrimoine lui revient de droit. Si le défunt a des enfants, seuls les enfants sont réservataires.' },
    { q: '(Challenge) Un défunt était pacsé et avait 2 enfants d\'une première union. Il avait rédigé un testament léguant "tout son patrimoine" à sa nouvelle partenaire de PACS. Que va-t-il se passer ?',
      options: ['La partenaire de PACS reçoit 100% du patrimoine', 'Le testament est annulé par le juge', 'Les enfants étant réservataires (à hauteur de 2/3 pour deux enfants), la partenaire de PACS ne recevra que la "quotité disponible", soit 1/3 du patrimoine', 'La partenaire de PACS doit adopter les enfants pour hériter'],
      correct: 2, rationale: 'Le testament ne peut pas empiéter sur la réserve héréditaire des enfants. La partenaire de PACS ne récupèrera que la part libre (1/3).' },
    { q: '(Challenge) Par opposition au PACS et au Mariage, que se passe-t-il si deux personnes vivent en "Union libre" (concubinage) et se font un testament pour se léguer un bien ?',
      options: ['Ils bénéficient de l\'exonération d\'impôts s\'ils vivent ensemble depuis 3 ans', 'L\'héritier sera taxé à 60% sur la valeur du bien reçu (après un faible abattement de 1594 €)', 'Le testament est illégal en concubinage', 'Ils sont taxés à 20%'],
      correct: 1, rationale: 'Les concubins sont fiscalement des étrangers absolus. Si vous léguez un appartement de 200 000 € à votre concubin, il devra payer près de 120 000 € d\'impôts pour le garder.' },
  ],
  'w4-d4': [
    { q: 'La souscription à une assurance Multirisque Habitation (MRH) est-elle légalement obligatoire pour un propriétaire occupant une maison individuelle ?',
      options: ['Oui, dans tous les cas', 'Non, aucune assurance n\'est obligatoire pour une maison individuelle occupée par son propriétaire (bien que ce soit fortement recommandé)', 'Oui, si la maison vaut plus de 500 000 €', 'Non, sauf en zone inondable'],
      correct: 1, rationale: 'Si le propriétaire habite sa propre maison et n\'est pas en copropriété, il est libre de ne pas s\'assurer. Mais en cas d\'incendie, il perdra tout.' },
    { q: 'La souscription d\'une assurance est-elle obligatoire pour un propriétaire occupant un appartement en COPROPRIÉTÉ ?',
      options: ['Non, c\'est comme pour la maison individuelle', 'Oui, la loi Alur l\'oblige à s\'assurer au minimum pour la Responsabilité Civile (pour couvrir les dégâts causés aux voisins ou à l\'immeuble)', 'Oui, mais seulement la première année de l\'achat', 'Non, le syndic assure déjà tout l\'immeuble pour les parties privatives'],
      correct: 1, rationale: 'En copropriété, les risques de dommages causés aux autres (fuite d\'eau, départ de feu) sont immenses, la loi protège donc la collectivité.' },
    { q: 'En MRH, que couvre la "garantie dommages aux biens" ?',
      options: ['Uniquement les dégâts causés à la voiture du propriétaire', 'La protection de votre propre patrimoine (le bâti et/ou le mobilier) contre des périls comme l\'incendie, les dégâts des eaux, le vol ou les tempêtes', 'Uniquement la valeur du terrain', 'Le remboursement des crédits immobiliers'],
      correct: 1, rationale: 'C\'est le cœur du contrat MRH : l\'assureur vous indemnise pour réparer ou reconstruire VOTRE bien.' },
    { q: 'Qu\'est-ce que l\'option "Valeur de reconstruction à neuf" pour le bâti ?',
      options: ['L\'assureur remplace la vieille maison par un immeuble de 10 étages', 'En cas de sinistre total, l\'assureur ne déduit pas la vétusté (la dépréciation liée à l\'âge du bâtiment) et rembourse le prix exact de la reconstruction à neuf d\'un bien identique', 'Le fait de pouvoir revendre la maison plus chère', 'Une garantie qui ne s\'applique qu\'au mobilier de la cuisine'],
      correct: 1, rationale: 'Sans cette option (souvent limitée à 25 ou 33% d\'indemnité supplémentaire), si votre maison avait un vieux toit, l\'assureur déduirait son usure de l\'indemnisation.' },
    { q: 'Comment sont généralement gérées les dépendances (garage séparé, cabanon de jardin) dans un contrat MRH classique ?',
      options: ['Elles sont toujours incluses automatiquement sans limite de surface', 'Elles doivent faire l\'objet d\'une déclaration spécifique (surface, distance) à la souscription pour être couvertes', 'Il est interdit de les assurer', 'Elles sont assurées par la mairie'],
      correct: 1, rationale: 'Si vous construisez un garage dans le jardin 5 ans après votre emménagement sans le déclarer à l\'assureur, il ne sera pas couvert en cas d\'effondrement.' },
    { q: 'Qu\'est-ce qu\'une "clause d\'inhabitation" (ou clause de vacance) dans la garantie Vol d\'un contrat MRH ?',
      options: ['Une clause qui expulse le propriétaire', 'Une règle de l\'assureur qui suspend la garantie Vol si le logement est inoccupé au-delà d\'une certaine durée dans l\'année (souvent de 30 à 90 jours consécutifs)', 'Le fait de pouvoir prêter son logement à un inconnu', 'L\'interdiction d\'habiter le logement pendant les travaux'],
      correct: 1, rationale: 'Un logement vide attire les cambrioleurs et ralentit la détection des sinistres. Si vous partez faire un tour du monde de 6 mois, il faut prévenir l\'assureur !' },
    { q: 'Quel est l\'intérêt pour un propriétaire occupant de vérifier le "plafond de garantie Objets de valeur" ?',
      options: ['C\'est obligatoire pour obtenir un permis de construire', 'L\'assureur limite l\'indemnisation des bijoux, tableaux et métaux précieux à une somme précise. S\'ils sont sous-évalués à la souscription, le propriétaire sera mal indemnisé', 'Cela permet de baisser la taxe foncière', 'Pour prouver sa richesse à la banque'],
      correct: 1, rationale: 'Les objets de valeur (bijoux, or) font l\'objet d\'un plafond distinct du mobilier classique. Un coffre-fort ou des factures sont souvent exigés.' },
    { q: 'En cas de sinistre, le propriétaire devra souvent s\'acquitter d\'une "franchise". De quoi s\'agit-il ?',
      options: ['La prime annuelle du contrat', 'La part du sinistre qui reste financièrement à la charge de l\'assuré', 'Les honoraires de l\'expert', 'Le bonus accordé s\'il n\'y a pas eu de sinistre depuis 3 ans'],
      correct: 1, rationale: 'Si la franchise est de 200 € et que le dégât des eaux coûte 2000 € de réparations, l\'assureur versera 1800 €.' },
    { q: '(Challenge) Un propriétaire occupant subit le vol de son canapé acheté 2000 € il y a 5 ans. Son contrat prévoit un rééquipement en "valeur d\'usage". Que touchera-t-il ?',
      options: ['2000 € exactement', 'Le prix d\'un canapé neuf de l\'année en cours', 'La valeur du canapé neuf diminuée d\'un taux de vétusté (l\'usure due à ses 5 ans d\'âge), soit beaucoup moins que 2000 €', 'Rien du tout, les meubles ne sont pas couverts'],
      correct: 2, rationale: 'La valeur d\'usage prend en compte l\'âge du bien. Pour avoir un remplacement au prix du neuf, il faut avoir souscrit l\'option "Rééquipement à neuf".' },
    { q: '(Challenge) En cas d\'arrêté interministériel de "Catastrophe Naturelle" (ex: inondation majeure), la franchise imposée au propriétaire est-elle définie par son contrat d\'assurance ?',
      options: ['Oui, le propriétaire peut négocier une franchise à zéro euro', 'Non, la franchise est légale, imposée par l\'État et identique pour tous (actuellement 380 € pour les biens à usage d\'habitation)', 'C\'est le maire de la commune qui décide du montant', 'Il n\'y a jamais de franchise lors d\'une catastrophe naturelle'],
      correct: 1, rationale: 'Dans le régime des Cat Nat, l\'assureur ne peut pas appliquer la franchise contractuelle, il a l\'obligation d\'appliquer la franchise légale.' },
  ],
  'w4-d5': [
    { q: 'Qu\'est-ce que l\'assurance PNO (Propriétaire Non Occupant) ?',
      options: ['Une assurance pour les propriétaires qui n\'ont pas encore payé leur crédit', 'Un contrat d\'assurance habitation destiné au propriétaire (investisseur/bailleur) qui met son bien en location (ou le laisse vacant) et n\'y habite donc pas lui-même', 'L\'assurance obligatoire de l\'agent immobilier', 'Une garantie qui paie le propriétaire s\'il ne trouve pas de locataire'],
      correct: 1, rationale: 'Le PNO est le filet de sécurité du propriétaire bailleur, complémentaire à l\'assurance de son locataire.' },
    { q: 'La souscription d\'une assurance PNO est-elle obligatoire pour l\'investisseur bailleur ?',
      options: ['Non, c\'est toujours facultatif', 'Oui, depuis la loi Alur de 2014, elle est obligatoire (au moins pour la responsabilité civile) si le bien locatif est situé dans une copropriété', 'Uniquement pour les locaux commerciaux', 'Uniquement si le loyer est supérieur au SMIC'],
      correct: 1, rationale: 'Si vous possédez un appartement locatif dans un immeuble collectif, vous avez l\'obligation légale d\'avoir une assurance pour couvrir votre responsabilité envers les autres copropriétaires.' },
    { q: 'Pourquoi l\'investisseur doit-il s\'assurer en PNO alors que le locataire a déjà l\'obligation de prendre une assurance habitation (MRH locataire) ?',
      options: ['Pour payer deux fois l\'assureur', 'Pour couvrir le bien entre deux locataires (vacance), protéger la responsabilité du propriétaire (ex: vice de construction causant un dégât), et pallier un éventuel défaut d\'assurance du locataire', 'Pour contrôler si le locataire paie bien son loyer', 'C\'est faux, la PNO est interdite si le locataire est assuré'],
      correct: 1, rationale: 'Le locataire est responsable de ce qu\'il cause. Mais si le sinistre vient d\'un défaut de la plomberie encastrée, c\'est la responsabilité du propriétaire (et donc sa PNO) qui sera engagée.' },
    { q: 'Que couvre la "garantie recours des voisins et des tiers" incluse dans la PNO ?',
      options: ['Les frais d\'avocat si le voisin fait trop de bruit', 'Les dégâts causés aux voisins par un sinistre ayant pris naissance dans votre appartement locatif et dont vous êtes responsable en tant que propriétaire', 'Le vol de la voiture du voisin', 'Les loyers impayés par le locataire'],
      correct: 1, rationale: 'Si une canalisation vétuste pète chez vous et inonde les 3 étages du dessous, c\'est votre assurance PNO qui indemnisera les voisins.' },
    { q: 'Quel avantage fiscal offre l\'assurance PNO pour le propriétaire bailleur déclarant ses revenus fonciers au régime réel ?',
      options: ['La prime n\'a aucun impact fiscal', 'La prime d\'assurance PNO est 100% déductible des revenus fonciers (elle vient diminuer les loyers imposables)', 'Elle permet d\'annuler la taxe foncière', 'Elle donne droit à un crédit d\'impôt de 5 000 €'],
      correct: 1, rationale: 'Comme les intérêts d\'emprunt ou les travaux, la cotisation PNO est une charge d\'exploitation déductible.' },
    { q: 'Que se passe-t-il en cas de vacance locative (le logement est vide pendant 2 mois entre deux locataires) s\'il y a un incendie d\'origine électrique ?',
      options: ['Le voisin paie', 'Le dernier locataire est jugé responsable', 'Sans locataire assuré, c\'est uniquement la garantie de l\'assurance PNO du propriétaire qui indemnisera les dégâts du bien', 'L\'assurance de la banque rembourse le bien'],
      correct: 2, rationale: 'C\'est le rôle fondamental de la PNO : assurer la continuité de la protection du bien immobilier quand il n\'y a personne dedans.' },
    { q: 'En matière locative, qu\'est-ce que la GLI (Garantie Loyers Impayés) ?',
      options: ['Un synonyme de l\'assurance PNO', 'Une option complémentaire (ou un contrat à part) qui indemnise le propriétaire si le locataire cesse de payer son loyer, et qui prend en charge les frais de procédure d\'expulsion', 'Une assurance payée par le locataire pour le droit de louer', 'Un dépôt de garantie bloqué par la banque'],
      correct: 1, rationale: 'La GLI est une sécurité financière majeure pour l\'investisseur, exigeant en amont un contrôle rigoureux de la solvabilité du locataire.' },
    { q: 'Que couvre la garantie "Troubles de jouissance" souvent présente dans l\'assurance PNO ?',
      options: ['L\'absence de soleil sur le balcon', 'Le locataire qui refuse de partir à la fin du bail', 'Le recours du locataire contre le propriétaire si un sinistre (ex: incendie dû à une chaudière défectueuse) rend l\'appartement inhabitable, obligeant le propriétaire à le reloger', 'Les fêtes organisées par le locataire'],
      correct: 2, rationale: 'Le propriétaire doit fournir un logement "paisible". S\'il manque à cette obligation à cause d\'un sinistre relevant de sa responsabilité, la PNO le couvre.' },
    { q: '(Challenge) Un tuyau encastré dans le mur éclate et inonde l\'appartement locatif. Le locataire a sa MRH, le bailleur a sa PNO. En général, qui est responsable de ce type de canalisations ?',
      options: ['Le locataire, car il habite les lieux (MRH)', 'Le syndic de copropriété (Assurance immeuble)', 'Le propriétaire bailleur, car les tuyaux encastrés (inaccessibles) font partie du bâti, l\'entretien incombe au propriétaire (PNO)', 'La mairie'],
      correct: 2, rationale: 'Le locataire est responsable des joints, siphons et canalisations apparentes (entretien courant). Ce qui est encastré ou structurel relève du bailleur.' },
    { q: '(Challenge) Qu\'est-ce que la convention IRSI, qui facilite la vie de l\'investisseur et du locataire en cas de dégât des eaux ?',
      options: ['Un syndicat de défense des locataires', 'Une convention entre assureurs qui désigne "l\'assureur gestionnaire" (souvent l\'assureur de l\'occupant) pour s\'occuper de l\'expertise et indemniser rapidement les dégâts matériels inférieurs à 5000 € HT, sans chercher immédiatement un coupable', 'L\'obligation de repeindre les murs après 5 ans', 'Une taxe sur l\'eau'],
      correct: 1, rationale: 'L\'IRSI évite que l\'assurance locataire, l\'assurance PNO et l\'assurance de la copropriété ne se renvoient la balle pendant des mois pour un simple dégât des eaux.' },
  ],
};
