/* Questions de la semaine 6. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w6-d0': [
    { q: 'Comment définit-on le "rendement" d\'un placement financier ?',
      options: ['Le salaire du banquier', 'La perte enregistrée', 'L\'impôt payé sur la somme', 'Le revenu généré par un capital investi, exprimé en pourcentage annuel'],
      correct: 3, rationale: 'Investir 1 000 € et toucher 50 € donne un rendement de 5 %.' },
    { q: 'Lequel de ces placements affiche historiquement le meilleur rendement sur le très long terme ?',
      options: ['Les actions d\'entreprises (marchés boursiers)', 'Le Livret A', 'Le fonds en euros', 'L\'argent liquide'],
      correct: 0, rationale: 'En contrepartie du risque, les actions mondiales génèrent environ 7 à 9 % par an.' },
    { q: 'Qu\'est-ce qu\'un rendement "Nominal" (ou brut) ?',
      options: ['Le rendement qui va exactement dans votre poche', 'Le rendement calculé sans tenir compte de l\'inflation ni de la fiscalité', 'Le rendement des obligations uniquement', 'Un rendement négatif'],
      correct: 1, rationale: 'C\'est le chiffre vendeur affiché par les banques.' },
    { q: 'Qu\'est-ce que le rendement "Net de fiscalité" ?',
      options: ['Le taux brut affiché', 'Le rendement de l\'inflation', 'Le rendement restant une fois les impôts et prélèvements sociaux déduits', 'Le rendement perçu le premier mois'],
      correct: 2, rationale: 'C\'est la somme qui arrive réellement sur votre compte.' },
    { q: 'Quel indicateur représente l\'enrichissement véritable (pouvoir d\'achat) sur une année ?',
      options: ['Le rendement "Réel" (rendement Net moins l\'inflation)', 'Le taux de la BCE', 'Le taux brut affiché', 'Le CAC 40'],
      correct: 0, rationale: 'Gagner 5% nets quand l\'inflation est à 6%, c\'est perdre 1% de pouvoir d\'achat.' },
    { q: 'Pourquoi les frais de gestion d\'une enveloppe sont-ils cruciaux dans le calcul du rendement ?',
      options: ['Ils augmentent la performance', 'Ils sont remboursés par l\'État', 'Ils ne s\'appliquent qu\'une seule fois', 'Ils amputent silencieusement et lourdement le rendement chaque année'],
      correct: 3, rationale: '1% de frais annuels sur 20 ans représente des milliers d\'euros de manque à gagner.' },
    { q: 'En immobilier locatif, qu\'est-ce que le "rendement locatif brut" ?',
      options: ['Le loyer moins la taxe foncière', 'Le montant du prêt', 'Le ratio : (Loyers annuels encaissés / Prix d\'achat total) x 100', 'L\'argent de poche du propriétaire'],
      correct: 2, rationale: 'C\'est un indicateur rapide, mais trompeur car il oublie les charges.' },
    { q: 'En finance, peut-on avoir un rendement élevé avec un capital garanti ?',
      options: ['Non, il y a un arbitrage obligatoire : viser un rendement élevé exige de renoncer à la garantie du capital', 'Oui, le Livret A le permet', 'Oui, sur les comptes à terme', 'C\'est le principe du Loto'],
      correct: 0, rationale: '"Rendement élevé et sans risque" = arnaque garantie.' },
    { q: '(Challenge) Une action vaut 100 € et verse un dividende annuel de 4 €. Quel est le "rendement du dividende" ?',
      options: ['40 %', '10 %', '0,4 %', '4 %'],
      correct: 3, rationale: '(4 / 100) x 100 = 4 %.' },
    { q: '(Challenge) Face à une proposition affichant "10% de rendement cible", quel réflexe d\'analyse devez-vous avoir ?',
      options: ['Signer tout de suite', 'Chercher où se cache le risque massif justifiant un tel rendement (crédit, perte en capital)', 'Emprunter pour investir plus', 'Demander le même taux à son banquier'],
      correct: 1, rationale: 'Aucune surperformance n\'est gratuite, le risque doit être identifié.' },
  ],
  'w6-d1': [
    { q: 'Depuis la mise en place du prélèvement à la source, la déclaration annuelle des revenus au printemps est-elle encore obligatoire ?',
      options: ['Non, elle a été totalement supprimée', 'Oui, elle reste obligatoire pour régulariser la situation, appliquer les réductions/crédits d\'impôt et actualiser le taux de prélèvement', 'Uniquement pour les travailleurs indépendants', 'Seulement si on a eu une augmentation de salaire'],
      correct: 1, rationale: 'Le prélèvement à la source n\'est qu\'une "avance" payée tous les mois. La déclaration permet de faire le bilan exact de l\'année passée.' },
    { q: 'Au printemps de l\'année 2024, quels revenus avez-vous dû déclarer aux impôts ?',
      options: ['Les revenus estimés pour l\'année 2024 (Année en cours)', 'Les revenus perçus en 2023 (Année N-1)', 'Les revenus des 3 dernières années', 'Les revenus de 2022'],
      correct: 1, rationale: 'On déclare toujours avec un an de décalage, car c\'est le seul moment où l\'on connaît la totalité des revenus perçus sur l\'année civile écoulée (du 1er janvier au 31 décembre).' },
    { q: 'L\'administration fiscale propose une "déclaration pré-remplie" sur Internet. Quelle est la responsabilité du contribuable ?',
      options: ['Aucune, si c\'est pré-rempli c\'est que c\'est parfait', 'Il doit simplement cliquer sur "Valider" sans lire', 'Il a l\'obligation de vérifier les montants, de corriger les éventuelles erreurs et d\'ajouter les revenus ou charges manquants (dons, frais de garde, etc.)', 'Il doit tout effacer et tout retaper'],
      correct: 2, rationale: 'Les impôts pré-remplissent grâce aux employeurs et banques, mais ils ne savent pas si vous avez fait un don, embauché une nounou, ou touché un loyer non géré par agence.' },
    { q: 'Un jeune majeur de 19 ans, étudiant et sans revenu, a-t-il le droit de rester "rattaché" au foyer fiscal de ses parents ?',
      options: ['Non, dès 18 ans la séparation est obligatoire', 'Oui, un enfant majeur peut demander le rattachement (jusqu\'à 21 ans, ou jusqu\'à 25 ans s\'il poursuit des études)', 'Uniquement s\'il vit sous le même toit 365 jours par an', 'Seulement s\'il est boursier'],
      correct: 1, rationale: 'Le rattachement permet aux parents de conserver sa "part fiscale" (le quotient familial), ce qui est souvent avantageux pour faire baisser l\'impôt global du foyer.' },
    { q: 'Lequel de ces revenus perçus l\'année dernière NE DOIT PAS être reporté sur la déclaration de revenus car il est totalement exonéré ?',
      options: ['Le salaire du CDI', 'Les revenus d\'un investissement locatif', 'Les intérêts du Livret A et du LEP', 'Les allocations chômage'],
      correct: 2, rationale: 'L\'épargne réglementée est hors impôt. À l\'inverse, les salaires, loyers, chômage, et indemnités maladie doivent être déclarés.' },
    { q: 'Concernant les frais professionnels des salariés (trajets domicile-travail, repas), quelle est la règle par défaut appliquée par les impôts sur la déclaration ?',
      options: ['Une déduction forfaitaire automatique de 10 % (plafonnée) sur le salaire', 'Rien, il faut tout justifier au centime près', 'Une déduction de 50 %', 'Un forfait de 5 000 € pour tout le monde'],
      correct: 0, rationale: 'L\'État enlève d\'office 10% de vos salaires déclarés pour couvrir vos frais. Si vous roulez beaucoup, vous pouvez renoncer à ce forfait et opter pour les "Frais Réels" si le calcul (indemnités kilométriques) est plus avantageux pour vous.' },
    { q: 'Si un contribuable s\'aperçoit en septembre qu\'il a oublié de déclarer un crédit d\'impôt lors de sa déclaration du printemps, que peut-il faire ?',
      options: ['C\'est perdu, il doit attendre l\'année suivante', 'Il a un "droit à l\'erreur" et peut utiliser le service de correction en ligne (ouvert généralement d\'août à décembre) pour modifier sa déclaration a posteriori', 'Il doit payer une amende de 150 €', 'Il doit porter plainte contre les impôts'],
      correct: 1, rationale: 'L\'administration reconnaît le droit à l\'erreur (de bonne foi). La correction déclenchera l\'édition d\'un nouvel avis d\'imposition.' },
    { q: 'Quel document officiel l\'administration fiscale délivre-t-elle à l\'été (juillet/août) suite à la déclaration ?',
      options: ['L\'Avis d\'Imposition (ou avis de situation déclarative)', 'Le bulletin de paie', 'Un relevé bancaire', 'Une attestation de droits'],
      correct: 0, rationale: 'C\'est le sésame indispensable pour prouver ses revenus (pour louer un appartement, demander une aide sociale, ou obtenir un crédit).' },
    { q: '(Challenge) Un étudiant de moins de 26 ans fait des "jobs d\'été" (travail salarié). Doit-il déclarer et payer des impôts sur ces revenus ?',
      options: ['Oui, dès le premier euro gagné', 'Non, ces salaires étudiants (moins de 26 ans) bénéficient d\'une exonération d\'impôt dans la limite de 3 fois le SMIC mensuel (environ 5 200 €). Il ne déclare que la part qui dépasse ce seuil', 'Il doit les déclarer mais l\'employeur paiera l\'impôt à sa place', 'Les étudiants ne paient jamais d\'impôts'],
      correct: 1, rationale: 'Cette niche fiscale permet aux étudiants de travailler l\'été ou le week-end sans alourdir les impôts de leurs parents (s\'ils sont rattachés) ou les leurs.' },
    { q: '(Challenge) À l\'issue de la déclaration, il apparaît que les prélèvements à la source effectués l\'année dernière (2 500 € au total) étaient SUPÉRIEURS à l\'impôt final réellement dû (2 000 €). Que fait l\'État ?',
      options: ['L\'État garde la différence pour les frais de dossier', 'L\'État reporte le surplus sur l\'année suivante', 'L\'État rembourse la différence (500 €) au contribuable, généralement fin juillet par virement bancaire', 'L\'État augmente le taux de prélèvement'],
      correct: 2, rationale: 'Le prélèvement à la source est parfois "aveugle" (par exemple si vous vous êtes marié ou avez eu un enfant en cours d\'année). La déclaration rétablit la justice fiscale.' },
  ],
  'w6-d2': [
    { q: 'Qu\'est-ce que le "minimum contributif" (MiCo) dans le système de retraite français ?',
      options: ['Le RSA pour les personnes âgées', 'Un mécanisme qui garantit un montant minimum de retraite de base pour les salariés du privé ayant cotisé sur de petits salaires tout au long de leur vie', 'La somme minimum à payer pour racheter un trimestre', 'La pension versée aux personnes n\'ayant jamais travaillé'],
      correct: 1, rationale: 'Il a pour but de s\'assurer que ceux qui ont travaillé dur, mais avec de faibles revenus (comme au SMIC), obtiennent une retraite "décente".' },
    { q: 'Quelle est la différence majeure entre le Minimum Contributif (MiCo) et l\'ASPA (l\'ex-minimum vieillesse) ?',
      options: ['Il n\'y a aucune différence, ce sont deux noms pour la même chose', 'Le MiCo est une récompense pour avoir travaillé et cotisé, tandis que l\'ASPA est une allocation de solidarité pour les personnes âgées sans ressources (même sans avoir travaillé)', 'Le MiCo est payé par la CAF, l\'ASPA par l\'employeur', 'Le MiCo est réservé aux cadres'],
      correct: 1, rationale: 'L\'ASPA est un droit social soumis à condition de ressources. Le MiCo est un droit acquis par le travail et le paiement de cotisations.' },
    { q: 'Quelle est la condition sine qua non (obligatoire) pour qu\'un retraité puisse bénéficier du Minimum Contributif ?',
      options: ['Avoir au moins 3 enfants', 'Liquider sa retraite à "taux plein" (soit parce qu\'il a tous ses trimestres, soit parce qu\'il a atteint l\'âge d\'annulation de la décote, 67 ans)', 'Avoir été au chômage plus de 5 ans', 'Gagner plus que le SMIC'],
      correct: 1, rationale: 'Si vous partez à 62 ou 64 ans avec une décote (il vous manque des trimestres), vous n\'avez pas droit au MiCo pour réévaluer votre petite pension.' },
    { q: 'Faut-il faire une démarche spécifique pour demander le Minimum Contributif lors de son départ en retraite ?',
      options: ['Oui, un dossier de 10 pages à la préfecture', 'Non, si vous êtes éligible, la caisse de retraite le calcule et l\'applique automatiquement lors de la liquidation de votre pension', 'Oui, il faut passer au tribunal', 'Il faut le demander à son dernier employeur'],
      correct: 1, rationale: 'L\'ordinateur de la CNAV compare votre pension calculée avec la formule classique et le montant du MiCo, et vous verse le plus avantageux.' },
    { q: 'Le minimum contributif concerne quelle partie de votre retraite ?',
      options: ['La retraite complémentaire (Agirc-Arrco)', 'Uniquement la retraite de base (la Sécurité sociale / CNAV)', 'Les plans d\'épargne retraite (PER)', 'L\'assurance-vie'],
      correct: 1, rationale: 'Le MiCo vient rehausser la retraite de la Sécurité sociale. Votre complémentaire (Agirc-Arrco) s\'ajoutera ensuite par-dessus ce socle.' },
    { q: 'Que différencie le MiCo "de base" du MiCo "majoré" ?',
      options: ['Le majoré est pour les Parisiens', 'Le MiCo "majoré" offre un montant supérieur à ceux qui justifient d\'un minimum de 120 trimestres "cotisés" (travaillés), valorisant ainsi l\'effort de travail long par rapport aux trimestres assimilés (chômage, maladie)', 'Le majoré est pour ceux partis en préretraite', 'Le majoré double la pension'],
      correct: 1, rationale: 'Le gouvernement veut récompenser ceux qui ont réellement travaillé (et payé des cotisations) longtemps.' },
    { q: 'Quel a été l\'un des axes forts de la réforme des retraites de 2023 concernant ce Minimum Contributif ?',
      options: ['Sa suppression totale', 'Sa baisse de 10%', 'Sa revalorisation (jusqu\'à 100 € bruts de plus par mois pour une carrière complète au SMIC) pour garantir une pension minimale globale (base + complémentaire) autour de 1 200 € bruts / 85% du SMIC net', 'L\'obligation de le rembourser au décès'],
      correct: 2, rationale: 'C\'était la grande mesure "sociale" de la réforme : rehausser les petites pensions de ceux qui ont trimé toute leur vie au SMIC.' },
    { q: 'Le Minimum Contributif est-il versé en totalité si vous n\'avez pas la durée d\'assurance requise (le nombre de trimestres total) pour votre génération ?',
      options: ['Oui, le montant est fixe', 'Non, son montant est "proratisé" (réduit proportionnellement) en fonction du nombre de trimestres validés par rapport à la durée requise', 'Il est divisé par deux au-delà de 65 ans', 'Il est versé uniquement les années paires'],
      correct: 1, rationale: 'Si vous partez à 67 ans (taux plein automatique), mais avec seulement 100 trimestres validés sur les 170 requis, vous aurez droit au MiCo, mais il sera réduit proportionnellement (100/170).' },
    { q: '(Challenge) Existe-t-il un plafond global de revenus pour toucher le Minimum Contributif ?',
      options: ['Non, aucun plafond', 'Oui, la somme de TOUTES vos retraites (base rehaussée + complémentaires + autres régimes) ne doit pas dépasser un certain plafond mensuel (environ 1 367 € en 2024). Si ça dépasse, le MiCo est réduit d\'autant.', 'Uniquement un plafond sur le patrimoine immobilier', 'Le plafond est le salaire du Président'],
      correct: 1, rationale: 'Le MiCo est là pour aider les "petites" retraites. Si un salarié a une toute petite retraite de base mais une énorme retraite complémentaire (carrière mixte par ex), on plafonne.' },
    { q: '(Challenge) Un assuré part à la retraite. On lui calcule une retraite de base "naturelle" de 600 €. Le MiCo auquel il a droit est de 750 €. La caisse lui verse donc 750 €. Comment appelle-t-on la différence de 150 € ?',
      options: ['La prime de fin de carrière', 'Le complément de solidarité', 'Le complément au minimum contributif', 'La surcote'],
      correct: 2, rationale: 'L\'ordinateur affiche clairement cette ligne. La pension de base est de 600€, et la Sécu ajoute un "complément" de 150€ pour vous hisser au plancher légal du MiCo.' },
  ],
  'w6-d3': [
    { q: 'Si un défunt ne laisse aucun testament, qui a les droits de transmission les plus protecteurs selon la loi française ?',
      options: ['Le concubin (union libre)', 'Le partenaire de PACS', 'Le conjoint marié', 'Les trois ont exactement les mêmes droits'],
      correct: 2, rationale: 'Le mariage est le seul statut qui confère automatiquement au conjoint le rang d\'héritier légal. Sans testament, le PACS et le concubinage n\'offrent rien.' },
    { q: 'Le défunt laisse une épouse et des enfants nés de leur union (enfants communs). Quel choix l\'épouse survivante a-t-elle sur la succession (en l\'absence de testament) ?',
      options: ['100% en usufruit (le droit d\'usage) OU 1/4 du patrimoine en pleine propriété', '50% de la maison et rien d\'autre', '100% en pleine propriété obligatoirement', 'Elle n\'a droit à rien'],
      correct: 0, rationale: 'C\'est la règle d\'or des successions pour les familles traditionnelles. L\'usufruit lui permet de rester dans la maison et de toucher les loyers des autres biens jusqu\'à sa mort.' },
    { q: 'Le défunt laisse une épouse, mais aussi un enfant issu d\'une PREMIÈRE union. Quel droit a l\'épouse survivante ?',
      options: ['Elle garde le choix entre usufruit et pleine propriété', 'Elle a droit obligatoirement à 1/4 du patrimoine en pleine propriété. Le choix de l\'usufruit lui est supprimé par la loi', 'Elle est déshéritée', 'Elle a droit à 100% en usufruit'],
      correct: 1, rationale: 'La loi supprime l\'usufruit pour éviter qu\'un enfant d\'un premier lit ne soit obligé d\'attendre le décès de sa "belle-mère" (parfois plus jeune que lui !) pour récupérer son héritage.' },
    { q: 'Qu\'est-ce que le "droit temporaire au logement" du conjoint survivant (marié ou pacsé) ?',
      options: ['Le droit d\'occuper gratuitement la résidence principale pendant 1 an après le décès', 'Le droit de squatter la résidence secondaire', 'Le droit de vendre le logement en 3 mois', 'L\'obligation de quitter les lieux après les funérailles'],
      correct: 0, rationale: 'C\'est un droit d\'ordre public (on ne peut pas l\'enlever). Les frais liés à ce logement (loyers ou charges) pendant 1 an sont payés par la succession, donc par les héritiers.' },
    { q: 'Qu\'est-ce que le "droit viager au logement" ?',
      options: ['Le droit temporaire prolongé à 2 ans', 'Un droit réservé exclusivement au conjoint MARIÉ, lui permettant d\'occuper la résidence principale jusqu\'à sa propre mort', 'Un droit pour le partenaire de PACS', 'Le droit de louer la maison à un tiers'],
      correct: 1, rationale: 'Contrairement au droit temporaire, le droit viager n\'est pas automatique : le conjoint marié a 1 an pour le demander. Le partenaire de PACS n\'y a pas droit (sauf testament).' },
    { q: 'Fiscalement, combien de droits de succession (impôts) le conjoint survivant marié ou pacsé (avec testament) doit-il payer sur ce qu\'il hérite ?',
      options: ['20 %', '60 %', 'Il bénéficie d\'une exonération totale (0 € d\'impôt)', '5 % après un abattement'],
      correct: 2, rationale: 'Depuis la loi TEPA (2007), la transmission entre époux ou partenaires de PACS est totalement gratuite fiscalement, qu\'on hérite de 10 000 € ou de 10 millions d\'euros.' },
    { q: 'Le défunt n\'a pas d\'enfant. Il laisse son épouse et ses deux parents. Comment est répartie la succession (sans testament) ?',
      options: ['Les parents prennent tout', 'L\'épouse prend tout', 'L\'épouse reçoit la moitié (1/2) en pleine propriété, et chaque parent reçoit un quart (1/4)', 'L\'État prend l\'usufruit'],
      correct: 2, rationale: 'En l\'absence d\'enfants, l\'héritage remonte vers les parents (s\'ils sont vivants), mais le conjoint prend quand même au minimum la moitié.' },
    { q: 'Le conjoint marié est-il un héritier "réservataire" (qu\'on ne peut pas totalement déshériter) ?',
      options: ['Non, jamais', 'Oui, mais UNIQUEMENT si le défunt n\'a aucun enfant (ni petits-enfants). Dans ce cas, 1/4 du patrimoine lui est obligatoirement réservé', 'Oui, en toutes circonstances', 'Uniquement après 10 ans de mariage'],
      correct: 1, rationale: 'Si vous avez des enfants, seuls vos enfants sont réservataires (vous pourriez théoriquement déshériter votre épouse au profit de vos enfants). Sans enfant, l\'épouse devient réservataire.' },
    { q: '(Challenge) L\'épouse a opté pour "100% en usufruit" de la maison familiale. Les enfants sont donc "nus-propriétaires". L\'épouse peut-elle décider seule de VENDRE la maison pour en acheter une autre ?',
      options: ['Oui, c\'est elle qui habite dedans', 'Non, la vente d\'un bien démembré (usufruit/nue-propriété) nécessite l\'accord unanime de l\'usufruitier ET des nus-propriétaires (les enfants)', 'Oui, mais seulement si la maison vaut moins de 100 000 €', 'Non, elle n\'a même pas le droit de la louer'],
      correct: 1, rationale: 'L\'usufruit donne le droit de vivre dedans ou de louer pour en tirer les revenus, mais pas de vendre (ce droit d\'aliéner appartient aux nus-propriétaires et à l\'usufruitier conjointement).' },
    { q: '(Challenge) Un mari souhaite priver son épouse de son "droit viager au logement" (car ils sont séparés de fait mais non divorcés, et il veut léguer la maison à ses enfants). Comment doit-il procéder pour que ce soit légal ?',
      options: ['Une simple lettre sur la table de chevet suffit', 'Il ne peut pas, c\'est impossible', 'Il doit obligatoirement rédiger un testament authentique (dicté devant deux notaires, ou un notaire et deux témoins)', 'Il doit vendre la maison avant'],
      correct: 2, rationale: 'La loi protège tellement le logement de la famille que pour retirer ce droit viager au conjoint, un testament olographe (écrit seul) est nul. Il faut la solennité de l\'acte notarié.' },
  ],
  'w6-d4': [
    { q: 'Quelle est la seule garantie d\'assurance automobile légalement obligatoire en France pour pouvoir rouler ?',
      options: ['La garantie Tous Risques', 'La garantie Bris de glace', 'La garantie Responsabilité Civile (appelée communément assurance "au Tiers")', 'L\'assistance 0 km'],
      correct: 2, rationale: 'La loi vous oblige à pouvoir indemniser les autres si vous causez un accident (blessures, dégâts matériels au véhicule adverse).' },
    { q: 'Si vous êtes assuré "au Tiers" (la formule de base) et que vous êtes 100% RESPONSABLE d\'un accident qui détruit l\'avant de votre voiture, que rembourse votre assureur ?',
      options: ['Il rembourse les réparations de votre voiture', 'Il vous donne une voiture neuve', 'Il rembourse les dégâts du véhicule que vous avez percuté, mais ne vous rembourse RIEN pour les réparations de votre propre voiture', 'Il ne paie personne'],
      correct: 2, rationale: 'C\'est le principe du "Tiers". Ça protège les autres contre vous, mais pas votre propre matériel si vous êtes en tort.' },
    { q: 'Dans quel cas l\'assurance "Tous Risques" prend-elle tout son sens ?',
      options: ['Pour payer moins cher', 'Elle indemnise les dégâts matériels subis par VOTRE véhicule, même si vous êtes responsable de l\'accident, ou si le responsable n\'est pas identifié (délit de fuite)', 'Elle permet d\'annuler les contraventions', 'Elle vous dispense de faire le contrôle technique'],
      correct: 1, rationale: 'Le "Tous Risques" inclut la garantie "Dommages Tous Accidents". Si vous glissez sur du verglas et finissez seul dans le fossé, votre voiture sera remboursée.' },
    { q: 'Qu\'appelle-t-on souvent une assurance "Tiers Plus" (ou Tiers Étendu) ?',
      options: ['Une assurance pour les camionnettes', 'Une formule intermédiaire qui inclut la Responsabilité Civile, mais ajoute des garanties contre les risques subis sans que le véhicule roule : Vol, Incendie, Tempête et Bris de glace', 'Une assurance qui couvre 3 conducteurs', 'Une formule pour l\'étranger'],
      correct: 1, rationale: 'C\'est un excellent compromis pour une voiture de plus de 5 ans, qui n\'a plus une grosse valeur marchande, mais qu\'on veut protéger contre le vol ou la grêle.' },
    { q: 'Quelle garantie, souvent incluse mais parfois optionnelle, est absolument vitale pour couvrir les blessures corporelles du conducteur fautif ?',
      options: ['La protection juridique', 'L\'assistance dépannage', 'La Garantie Personnelle du Conducteur (ou corporelle du conducteur)', 'La valeur à neuf'],
      correct: 2, rationale: 'Si vous êtes responsable d\'un accident et finissez en fauteuil roulant, l\'assurance Responsabilité Civile paiera pour vos passagers, mais PAS pour vous. Seule cette garantie spécifique couvre VOS blessures.' },
    { q: 'Qu\'est-ce que la "franchise" lors d\'un accident matériel responsable (en Tous Risques) ?',
      options: ['Le prix du constat amiable', 'La somme qui reste à votre charge après l\'indemnisation de l\'assureur pour réparer votre véhicule', 'Le bonus gagné', 'Les frais de remorquage'],
      correct: 1, rationale: 'Si les réparations coûtent 1500 € et que votre franchise "dommages" est de 300 €, l\'assureur paiera 1200 € au garage.' },
    { q: 'Quel est l\'impact du coefficient de réduction-majoration (Bonus/Malus) sur le tarif de votre assurance ?',
      options: ['Aucun, le tarif est fixe', 'Il fait varier la prime de base : une année sans accident responsable fait baisser le coefficient (Bonus, la prime baisse), un accident responsable le fait augmenter (Malus, la prime grimpe fortement)', 'Il modifie le prix de l\'essence', 'Il augmente la durée du contrat'],
      correct: 1, rationale: 'Un jeune permis commence à 1,00. S\'il n\'a pas d\'accident, il gagne 5% par an, jusqu\'à atteindre un bonus maximum de 0,50 (la prime est divisée par deux).' },
    { q: 'En cas de sinistre total (voiture épave), si vous n\'avez pas souscrit d\'option spécifique, comment l\'expert évalue-t-il l\'indemnisation de votre véhicule ?',
      options: ['Au prix où vous l\'avez acheté, sur facture', 'Au prix du modèle neuf de l\'année', 'À sa Valeur de Remplacement À Dire d\'Expert (VRADE), c\'est-à-dire sa cote sur le marché de l\'occasion la veille de l\'accident', 'Au poids de la ferraille'],
      correct: 2, rationale: 'Une voiture perd sa valeur (vétusté) avec le temps et le kilométrage. Pour être remboursé au prix d\'achat, il faut avoir souscrit l\'option "Valeur à neuf" (souvent limitée aux 2 ou 3 premières années).' },
    { q: '(Challenge) Votre voiture (assurée "au Tiers") est garée sur un parking. À votre retour, la portière est enfoncée et le coupable a pris la fuite sans laisser de mot. Que va faire votre assurance ?',
      options: ['Elle va rembourser la portière moins la franchise', 'Elle ne vous remboursera strictement rien', 'Elle vous fera payer un malus', 'L\'État paiera via un fonds de garantie'],
      correct: 1, rationale: 'Le coupable n\'étant pas identifié, on ne peut pas faire marcher sa responsabilité civile. Et comme vous êtes assuré "au Tiers" (et non "Tous risques"), les dommages à votre propre véhicule ne sont pas couverts.' },
    { q: '(Challenge) Qu\'est-ce que la règle du "Prêt de volant" et ses conséquences ?',
      options: ['Il est interdit de prêter sa voiture en France', 'Si vous prêtez votre voiture à un ami occasionnellement et qu\'il a un accident responsable, votre assurance couvrira les dommages, MAIS vous paierez souvent une "franchise prêt de volant majorée" et le malus s\'appliquera sur VOTRE contrat', 'L\'ami doit payer son propre malus à son assurance', 'La voiture n\'est plus couverte'],
      correct: 1, rationale: 'L\'assurance suit le véhicule. C\'est donc le propriétaire du contrat qui assume l\'accident de la personne à qui il a confié les clés.' },
  ],
  'w6-d5': [
    { q: 'Que signifie l\'acronyme PTZ dans le financement immobilier ?',
      options: ['Prix Total Zéro', 'Prêt à Taux Zéro', 'Plan Territorial de Zonage', 'Prêt à Taux de Zénith'],
      correct: 1, rationale: 'C\'est un prêt aidé par l\'État où l\'emprunteur ne paie aucun intérêt bancaire (taux à 0%), seuls le capital et l\'assurance sont à rembourser.' },
    { q: 'Quelle est la condition sine qua non liée au statut de l\'acheteur pour bénéficier du PTZ ?',
      options: ['Il faut être marié', 'Il faut être "primo-accédant", c\'est-à-dire ne pas avoir été propriétaire de sa résidence principale au cours des deux dernières années', 'Il faut être retraité', 'Il faut avoir un enfant'],
      correct: 1, rationale: 'L\'aide de l\'État vise à faciliter l\'accès à la propriété de ceux qui louent depuis un moment.' },
    { q: 'Le PTZ peut-il financer 100 % de l\'achat d\'un bien immobilier ?',
      options: ['Oui, si le revenu est très bas', 'Non, il ne finance qu\'une partie de l\'opération (jusqu\'à 50 % maximum selon les cas) et doit obligatoirement être complété par un crédit immobilier classique et/ou un apport personnel', 'Oui, pour les biens neufs', 'Non, il est limité à 10 000 €'],
      correct: 1, rationale: 'Le PTZ est toujours un "prêt complémentaire". Il sert de levier pour faire baisser le coût total du financement.' },
    { q: 'Le PTZ est-il accordé à tout le monde sans distinction de salaire ?',
      options: ['Oui, le salaire ne compte pas', 'Non, il est octroyé "sous conditions de ressources". Le revenu fiscal de référence du foyer ne doit pas dépasser un plafond défini par l\'État', 'Uniquement à ceux qui gagnent plus de 3000 €/mois', 'Seulement aux étudiants'],
      correct: 1, rationale: 'C\'est une aide sociale, elle cible les ménages aux revenus modestes et intermédiaires.' },
    { q: 'Le zonage (Zones A, B1, B2,',
      options: ['est une notion clé du PTZ. Sur quoi se base-t-il ?', 'Sur la pollution de la ville', 'Sur la "tension" du marché immobilier local (Zone A = très tendue/chère comme Paris, Zone C = détendue/rurale), ce qui détermine les montants et les droits au PTZ', 'Sur le climat de la région', 'Sur le nombre d\'écoles'],
      correct: 1, rationale: 'Les plafonds de revenus et le montant du prêt accordé sont beaucoup plus élevés à Paris ou Montpellier (zones tendues) qu\'à la campagne.' },
    { q: 'Suite à la refonte du PTZ de 2024, pour quel type de biens "NEUFS" le PTZ est-il principalement réservé ?',
      options: ['Pour la construction de maisons individuelles partout en France', 'Pour l\'achat de logements neufs collectifs (appartements) situés en zones "tendues" (A et B1)', 'Pour l\'achat de châteaux', 'Pour l\'achat de caravanes'],
      correct: 1, rationale: 'L\'État a recentré l\'aide sur le logement collectif (pour éviter l\'étalement urbain) et dans les zones où la demande est la plus forte.' },
    { q: 'Quel avantage offre le mécanisme de "différé d\'amortissement" souvent inclus dans le PTZ ?',
      options: ['Il annule la dette après 5 ans', 'Il permet de ne commencer à rembourser le capital du PTZ qu\'après une première période (par ex 5, 10 ou 15 ans), allégeant ainsi les mensualités globales au début du projet', 'Il rembourse les frais de notaire', 'Il baisse le prix de l\'appartement'],
      correct: 1, rationale: 'Pendant la première phase, vous remboursez votre crédit classique. Une fois ce dernier (ou une partie) terminé, vous attaquez le remboursement du PTZ.' },
    { q: 'Outre le PTZ, qu\'est-ce que le Prêt Accession Sociale (PAS) ?',
      options: ['Un prêt à 0% illimité', 'Un prêt immobilier classique réglementé par l\'État (taux plafonné, frais de dossier limités), accordé sous condition de ressources, qui donnait historiquement droit aux APL Accession', 'Un prêt uniquement pour faire des travaux', 'Une aide de la mairie'],
      correct: 1, rationale: 'Le PAS est souvent utilisé comme "prêt principal" pour venir compléter le PTZ. Il offre une sécurité avec des taux encadrés.' },
    { q: '(Challenge) Un acheteur souhaite obtenir un PTZ pour acheter un bien dans "l\'ancien" (une maison déjà existante). Quelle est la condition drastique pour avoir le droit au PTZ dans ce cas ?',
      options: ['Que la maison soit en briques', 'Le bien doit être situé en zone détendue (B2 ou', 'ET l\'acheteur doit y réaliser des travaux d\'amélioration importants représentant au moins 25 % du coût total de l\'opération', 'Il suffit de repeindre les murs', 'Le PTZ dans l\'ancien est formellement interdit'],
      correct: 1, rationale: 'Pour dynamiser les centres-bourgs en déclin, l\'État finance l\'achat ancien uniquement s\'il y a un fort enjeu de rénovation (souvent énergétique).' },
    { q: '(Challenge) Le Prêt Action Logement (ex-1% Logement) est une autre aide à l\'achat. À qui s\'adresse-t-elle ?',
      options: ['Aux fonctionnaires uniquement', 'Aux retraités', 'Aux salariés d\'entreprises du secteur privé non agricole de plus de 10 salariés (sous conditions de ressources), permettant d\'obtenir un prêt complémentaire à taux réduit (proche de 1%)', 'Aux chômeurs'],
      correct: 2, rationale: 'Financé par une cotisation des employeurs, ce prêt complémentaire (souvent 30 000 ou 40 000 €) est un excellent coup de pouce pour les salariés éligibles.' },
  ],
};
