/* Questions de la semaine 17. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w17-d0': [
    { q: 'Que signifie le terme "Crowdfunding" ?',
      options: ['Le financement participatif : un grand nombre de personnes (la foule) financent un projet avec de petits montants, généralement via une plateforme en ligne', 'Une banque d\'investissement anglaise', 'Le financement par l\'État', 'Une taxe sur la foule'],
      correct: 0, rationale: 'Ce mécanisme a bouleversé la finance en permettant aux particuliers d\'investir directement dans des projets d\'entreprises (PME, immobilier) sans passer par la banque classique.' },
    { q: 'En crowdfunding, qu\'est-ce que le "Crowdlending" ?',
      options: ['Le don pur et simple à une association', 'L\'achat d\'actions (parts de capital) dans une start-up', 'Le prêt participatif : les investisseurs prêtent de l\'argent à une entreprise en échange d\'un taux d\'intérêt (souvent élevé) et d\'un remboursement du capital à terme', 'Le financement de cadeaux'],
      correct: 2, rationale: 'Vous agissez exactement comme une banque : vous accordez un crédit à une entreprise pour son développement.' },
    { q: 'Et qu\'est-ce que le "Crowdequity" ?',
      options: ['Le prêt immobilier', 'L\'investissement en capital : vous achetez des actions non cotées d\'une start-up ou PME, avec l\'espoir qu\'elle réussisse et de revendre vos parts avec une forte plus-value (ou de tout perdre)', 'Une assurance vie', 'Le financement de la sécurité sociale'],
      correct: 1, rationale: 'C\'est beaucoup plus risqué que le prêt, mais si la start-up devient le prochain Google, la plus-value sera colossale.' },
    { q: 'En France, quel secteur domine très largement le marché du crowdfunding grâce à ses rendements attractifs (souvent de 8 à 11 %) ?',
      options: ['Le cinéma', 'L\'agriculture', 'Le Crowdfunding Immobilier (financement de promoteurs immobiliers ou marchands de biens)', 'Le sport de haut niveau'],
      correct: 2, rationale: 'Les promoteurs ont besoin d\'énormément de liquidités (les fonds propres) très rapidement pour lancer les travaux de leurs immeubles, qu\'ils empruntent aux particuliers à des taux élevés.' },
    { q: 'Quel est le PRINCIPAL RISQUE pour un investisseur en crowdfunding immobilier (malgré le rendement alléchant de 10 %) ?',
      options: ['La baisse des impôts', 'Le risque de retard de chantier de plusieurs mois/années, voire le risque de défaut (faillite) du promoteur entraînant la perte totale du capital investi', 'Le risque que la maison soit trop belle', 'Le risque de liquidité de la plateforme'],
      correct: 1, rationale: 'Si la banque du promoteur coupe les vivres, ou si l\'immeuble ne se vend pas, le promoteur fera faillite et les particuliers (qui sont souvent les créanciers de dernier rang) perdront leur mise.' },
    { q: 'Face à ce risque, quelle est la liquidité de votre investissement en crowdfunding ?',
      options: ['On peut retirer l\'argent tous les jours', 'L\'investissement est très "illiquide" : l\'argent est bloqué (souvent de 12 à 36 mois) jusqu\'à la fin du projet (revente des appartements). On ne peut généralement pas revendre ses parts en cours de route', 'La banque rembourse en cas de besoin', 'L\'argent est bloqué pendant 30 ans'],
      correct: 1, rationale: 'Vous vous engagez sur la durée de vie du chantier. C\'est l\'inverse de la bourse.' },
    { q: 'Pour limiter les risques de fraude, sous quel agrément européen (ou français) les plateformes sérieuses de crowdfunding doivent-elles impérativement opérer ?',
      options: ['Le label Bio', 'L\'agrément PSFP (Prestataire de Services de Financement Participatif) délivré par l\'AMF', 'Le diplôme d\'architecte', 'La licence bancaire complète'],
      correct: 1, rationale: 'Cet agrément assure que la plateforme audite rigoureusement les projets avant de vous les proposer.' },
    { q: 'Quelle est la fiscalité par défaut applicable aux intérêts perçus (les gains) lors du remboursement d\'un projet de crowdfunding immobilier (prêt) ?',
      options: ['La Flat Tax (PFU) de 30 %', 'Exonération totale d\'impôts', 'Taxé à l\'impôt sur la fortune', 'Un prélèvement forfaitaire de 10 %'],
      correct: 0, rationale: 'Les intérêts gagnés sont traités comme des revenus du capital classiques (12,8% IR + 17,2% PS).' },
    { q: '(Challenge) Qu\'est-ce qui explique la "démocratisation" fulgurante de cette classe d\'actifs auprès des petits épargnants ?',
      options: ['C\'est obligatoire dans les banques', 'Le "ticket d\'entrée" (le minimum à investir) est très faible : de nombreuses plateformes permettent de prêter aux promoteurs à partir de 1 000 €, 100 €, voire dès 10 € pour certaines', 'L\'État garantit l\'argent', 'C\'est un jeu gratuit'],
      correct: 1, rationale: 'Avant, il fallait des millions pour prêter aux promoteurs. Aujourd\'hui, avec 1000€, on peut participer à la construction d\'un immeuble.' },
    { q: '(Challenge) Un investisseur dispose de 5 000 € pour du crowdfunding immobilier. Lequel de ces comportements est la "Règle d\'or" pour protéger son capital ?',
      options: ['Tout mettre (5 000 €) sur LE projet qui offre 12 %, pour maximiser les gains', 'Dépenser l\'argent', 'La diversification extrême : diviser son capital (ex: 50 fois 100 €) sur une multitude de projets, de promoteurs différents et de villes différentes, pour qu\'un défaut éventuel n\'efface pas la rentabilité des 49 autres', 'Investir uniquement au mois d\'août'],
      correct: 2, rationale: 'En crowdfunding, le défaut de paiement arrivera forcément un jour sur un de vos projets. La seule protection est que ce projet ne représente qu\'une part infime de votre portefeuille.' },
  ],
  'w17-d1': [
    { q: 'Quel célèbre impôt l\'IFI (Impôt sur la Fortune Immobilière) a-t-il remplacé en 2018 sous le mandat d\'Emmanuel Macron ?',
      options: ['La Taxe d\'habitation', 'L\'ISF (Impôt de Solidarité sur la Fortune)', 'La TVA', 'Les droits de succession'],
      correct: 1, rationale: 'La grande réforme a consisté à sortir les valeurs mobilières (comptes, bourse, entreprises) de l\'impôt sur la fortune pour les diriger vers l\'économie productive.' },
    { q: 'Comme son nom l\'indique, sur quelle "assiette" (type de biens) l\'IFI est-il exclusivement calculé ?',
      options: ['Le patrimoine global (voitures, tableaux, actions)', 'Uniquement sur la valeur nette du PATRIMOINE IMMOBILIER de l\'ensemble du foyer fiscal (maisons, appartements, parts de SCPI)', 'Seulement sur les résidences secondaires', 'Sur l\'argent dormant en banque'],
      correct: 1, rationale: 'Vous pouvez avoir 10 millions d\'euros en bourse sur votre compte-titres, vous ne paierez pas 1 euro d\'IFI. L\'IFI ne frappe que la pierre.' },
    { q: 'À partir de quel SEUIL de patrimoine immobilier NET (valeur des biens moins les dettes) un contribuable devient-il redevable de l\'IFI ?',
      options: ['100 000 €', '500 000 €', '1 300 000 €', '5 000 000 €'],
      correct: 2, rationale: 'Si la valeur de vos biens immobiliers mondiaux, déduction faite de vos crédits en cours, dépasse 1,3 million d\'euros au 1er janvier, vous entrez dans l\'IFI.' },
    { q: 'Un abattement légal très protecteur s\'applique sur l\'évaluation de votre Résidence Principale. De combien est-il ?',
      options: ['10 %', '30 %', '50 %', '100 % (la résidence principale est totalement exonérée)'],
      correct: 1, rationale: 'Si votre résidence principale (celle où vous vivez) vaut 1 000 000 € sur le marché, le fisc vous autorise à la déclarer seulement pour 700 000 € dans le calcul de l\'IFI.' },
    { q: 'Pourquoi précise-t-on que l\'IFI se calcule sur le patrimoine "NET" ?',
      options: ['Parce qu\'il faut le nettoyer', 'Car les dettes et crédits immobiliers (capital restant dû des emprunts, impôts locaux à payer) rattachés à ces biens immobiliers viennent EN DÉDUCTION de la valeur des biens, baissant ainsi la base taxable', 'Car on retire l\'inflation', 'C\'est une erreur, il se calcule sur le patrimoine brut'],
      correct: 1, rationale: 'Acheter une maison de 2 millions d\'euros avec un crédit de 1 million d\'euros donne un patrimoine net de 1 million. Vous n\'êtes donc pas à l\'IFI.' },
    { q: 'Vous détenez des parts de "pierre-papier" (SCPI, OPCI) logées dans votre assurance-vie. Sont-elles soumises à l\'IFI ?',
      options: ['Non, car elles sont dans l\'assurance-vie', 'Oui. La fraction de ces fonds ou actions qui est représentative de biens immobiliers DOIT être déclarée à l\'IFI, même logée dans une assurance-vie', 'Uniquement si vous les retirez', 'Non, ce sont des valeurs mobilières'],
      correct: 1, rationale: 'Le fisc traque l\'immobilier partout où il est caché. Les sociétés de gestion publient chaque année la "valeur IFI" de leurs parts pour aider les contribuables.' },
    { q: 'Une exception majeure permet à certains biens immobiliers d\'échapper TOTALEMENT à l\'IFI. Lesquels ?',
      options: ['Les châteaux', 'Les piscines', 'L\'immobilier affecté à l\'activité PROFESSIONNELLE principale du redevable (les murs de l\'usine de son entreprise, le cabinet du médecin)', 'Les locations meublées touristiques'],
      correct: 2, rationale: 'L\'outil de travail (les murs de l\'entreprise) est exonéré pour ne pas pénaliser les entrepreneurs et l\'activité économique du pays.' },
    { q: 'Le mécanisme du "barème" de l\'IFI a une particularité cruche. Une fois le seuil de 1 300 000 € franchi, à partir de quel montant commence-t-on à vous taxer rétroactivement ?',
      options: ['On taxe uniquement ce qui dépasse 1 300 000 €', 'On taxe à partir de 0 €', 'Le barème de l\'impôt s\'applique rétroactivement sur la tranche débutant à 800 000 € (et non sur ce qui dépasse 1,3 million)', 'On taxe sur 500 000 € fixe'],
      correct: 2, rationale: 'C\'est le fameux "effet de seuil". Tant que vous êtes à 1,29 million, vous payez 0. Dès que vous touchez 1,3 million, le fisc remonte en arrière et taxe tout le patrimoine situé entre 800k€ et 1,3M€.' },
    { q: '(Challenge) Lors d\'un démembrement de propriété (usufruit/nue-propriété) issu d\'une donation classique de son vivant, QUI doit déclarer le bien à l\'IFI ?',
      options: ['Le nu-propriétaire', 'C\'est divisé à 50/50', 'L\'usufruitier (celui qui a la jouissance du bien) DOIT DÉCLARER la maison pour sa valeur totale en PLEINE PROPRIÉTÉ, comme s\'il possédait l\'intégralité du bien. Le nu-propriétaire, lui, ne déclare rien', 'Personne'],
      correct: 2, rationale: 'La loi fiscale fait peser le fardeau de l\'IFI sur celui qui profite du bien. Donner la nue-propriété de ses biens à ses enfants ne permet donc pas de sortir à l\'IFI.' },
    { q: '(Challenge) Un investisseur fortuné achète un immeuble de 3 millions d\'euros en recourant à un "Prêt In Fine" (il ne rembourse que des intérêts pendant 15 ans, le capital reste intact). Historiquement, cela baissait l\'IFI. Depuis 2018, que dit la loi ?',
      options: ['Le prêt In Fine permet de ne pas payer d\'IFI', 'Le fisc force l\'emprunteur à rembourser le crédit', 'Pour le calcul de l\'IFI, le fisc "amortit" fictivement (linéairement) le prêt In Fine chaque année : la dette déductible diminue artificiellement chaque année, faisant gonfler mécaniquement le patrimoine net taxable à l\'IFI', 'La banque doit payer l\'IFI'],
      correct: 2, rationale: 'Le législateur a bouché cette célèbre niche fiscale de l\'ISF. L\'emprunteur In Fine ne peut plus déduire la totalité de sa dette sur la durée du prêt, son IFI augmentera donc d\'année en année.' },
  ],
  'w17-d2': [
    { q: 'Qu\'est-ce que le dispositif du "Cumul emploi-retraite" ?',
      options: ['Le fait d\'avoir deux emplois en même temps', 'Le fait de toucher le chômage à la retraite', 'La possibilité légale pour un retraité de reprendre (ou poursuivre) une activité professionnelle rémunérée TOUT EN percevant ses pensions de retraite', 'La suppression de la retraite si on travaille'],
      correct: 2, rationale: 'Que ce soit pour améliorer ses fins de mois ou par passion du métier, la loi autorise les retraités à retravailler.' },
    { q: 'Quelles sont les conditions strictes pour bénéficier du Cumul emploi-retraite INTÉGRAL (pouvoir gagner un salaire illimité en plus de sa retraite) ?',
      options: ['Il faut travailler à l\'étranger', 'Il faut travailler moins de 10 heures par semaine', 'Il faut obligatoirement avoir liquidé TOUTES ses retraites, avoir atteint "l\'âge légal", ET justifier du "Taux plein" (avoir la durée d\'assurance requise ou 67 ans)', 'C\'est accordé à tous les retraités'],
      correct: 2, rationale: 'Si vous remplissez ces critères, le gouvernement vous laisse totalement libre : votre salaire s\'ajoutera à 100% de votre retraite, sans aucun plafond.' },
    { q: 'Que se passe-t-il si un retraité veut reprendre le travail, mais qu\'il N\'A PAS le taux plein (ou n\'a pas atteint l\'âge légal pour d\'autres régimes) ?',
      options: ['Il lui est formellement interdit de travailler', 'Il est soumis au Cumul emploi-retraite PARTIEL (ou plafonné) : le total de ses revenus (Retraite de base + Nouveau Salaire) ne doit pas dépasser une certaine limite imposée par la loi (souvent l\'ancien salaire ou un plafond Sécu)', 'Il paie le double d\'impôts', 'Sa retraite de base est divisée par deux'],
      correct: 1, rationale: 'S\'il dépasse ce plafond légal, la caisse de retraite suspendra ou réduira le versement de sa pension.' },
    { q: 'Un salarié, qui n\'a pas le taux plein (cumul plafonné), part à la retraite et veut reprendre un emploi chez son MÊME (ancien) employeur. Quelle restriction subit-il ?',
      options: ['L\'employeur doit lui payer le double', 'Il doit observer un "Délai de carence" obligatoire de 6 mois après son départ en retraite avant de pouvoir retravailler dans cette même entreprise', 'C\'est interdit à vie', 'Il n\'y a aucune restriction'],
      correct: 1, rationale: 'Ce délai (valable uniquement pour le cumul plafonné chez le même employeur) vise à éviter les "fausses retraites" organisées avec le patron juste pour baisser le coût salarial.' },
    { q: 'Qu\'est-ce qui a MAJEUREMENT changé avec la réforme des retraites de 2023 concernant les cotisations payées par le retraité qui travaille (en cumul intégral) ?',
      options: ['Il ne paie plus aucune cotisation', 'Auparavant "à fonds perdus", ces cotisations de reprise d\'activité permettent DÉSORMAIS de créer de NOUVEAUX droits et de déclencher une "seconde pension de retraite" qui s\'ajoutera à la première à la fin définitive de son activité', 'Elles sont remboursées à sa famille', 'Elles sont affectées à l\'assurance chômage'],
      correct: 1, rationale: 'C\'est une révolution pour encourager l\'emploi des seniors. Travailler à la retraite n\'est plus "cotiser pour rien", cela augmentera la pension finale.' },
    { q: 'Cette "Seconde pension de retraite" (issue de la reprise d\'activité) est-elle illimitée ?',
      options: ['Non, elle est plafonnée à un montant annuel d\'environ 5 % du Plafond de la Sécurité Sociale (environ 2 300 € / an maximum d\'augmentation pour la retraite de base)', 'Oui, elle peut doubler la première retraite', 'Elle est bloquée à 50 €', 'Seulement si on a été cadre'],
      correct: 0, rationale: 'Bien que positive, la création de nouveaux droits reste encadrée pour ne pas exploser les budgets sociaux.' },
    { q: 'Pour bénéficier du Cumul emploi-retraite Intégral, une condition formelle (liée à la fin de carrière) s\'impose à l\'employé vis-à-vis de son patron. Laquelle ?',
      options: ['Il doit l\'inviter au restaurant', 'L\'employé doit officiellement "rompre" son contrat de travail (démission pour départ à la retraite, avec préavis) avec son employeur, même s\'il signe un nouveau contrat avec lui le lendemain', 'Il suffit de changer ses horaires', 'Il doit réduire son salaire'],
      correct: 1, rationale: 'C\'est une obligation légale pour liquider ses droits. On liquide d\'abord, on recrée un nouveau contrat de reprise d\'activité ensuite.' },
    { q: 'Quelle est la différence majeure entre la "Retraite Progressive" et le "Cumul Emploi-Retraite" ?',
      options: ['C\'est la même chose', 'Le cumul suppose de liquider définitivement sa retraite et retravailler. La retraite progressive s\'adresse aux "actifs" : on passe à temps partiel AVANT la retraite, et la caisse compense la perte de salaire par une fraction de la pension, tout en continuant à accumuler des trimestres', 'La progressive est pour les fonctionnaires', 'Le cumul est réservé aux agriculteurs'],
      correct: 1, rationale: 'La retraite progressive est l\'outil parfait (souvent dès 60 ou 62 ans) pour lever le pied en douceur (ex: travailler à 60%) sans perdre d\'argent, la retraite compensant les 40% manquants.' },
    { q: '(Challenge) Un retraité du régime général (salarié) prend le statut d\'auto-entrepreneur (activité indépendante/TNS) pour arrondir ses fins de mois. Le délai de carence de 6 mois s\'applique-t-il ?',
      options: ['Oui, le délai de 6 mois s\'applique à tout le monde', 'Non. Le passage d\'un régime à un autre (de salarié à indépendant) fait qu\'il n\'est soumis à AUCUN délai de carence ni plafond spécifique au régime général (s\'il s\'inscrit au bon régime)', 'Il doit attendre 2 ans', 'L\'auto-entreprise est interdite aux retraités'],
      correct: 1, rationale: 'C\'est une excellente astuce d\'optimisation. Devenir consultant indépendant à la retraite est très souple car on ne relève plus du salariat (selon les cas de cumul plafonné/intégral).' },
    { q: '(Challenge) Quelles cotisations sociales le retraité, reprenant une activité salariée, n\'est-il PLUS OBLIGÉ de payer sur sa fiche de paie (car le risque n\'existe plus pour lui) ?',
      options: ['Les cotisations maladie', 'Les cotisations chômage (Assurance chômage - bien que l\'employeur paie toujours sa part patronale par solidarité)', 'La CSG', 'L\'impôt sur le revenu'],
      correct: 1, rationale: 'Un retraité ayant liquidé ses droits n\'a plus droit au chômage s\'il perd ce nouvel emploi de reprise. Il est donc dispensé de la part salariale des cotisations chômage (un petit bonus sur le net !).' },
  ],
  'w17-d3': [
    { q: 'Quel est l\'autre nom juridique de la "Donation au dernier vivant" (DDV) ?',
      options: ['Le testament olographe', 'Le pacte de famille', 'La donation entre époux de biens à venir', 'L\'assurance vie'],
      correct: 2, rationale: 'Contrairement à une donation classique qui donne un bien immédiatement, la DDV ne prendra effet qu\'au décès du premier conjoint, sur les biens qu\'il possèdera à ce moment-là.' },
    { q: 'À qui ce dispositif est-il STRICTEMENT ET EXCLUSIVEMENT réservé ?',
      options: ['Aux concubins', 'Aux partenaires de PACS', 'Uniquement aux couples Mariés (époux)', 'Aux frères et sœurs'],
      correct: 2, rationale: 'C\'est un privilège absolu du mariage. Les personnes pacsées ou en union libre ne peuvent pas se faire une donation au dernier vivant (elles doivent utiliser un testament).' },
    { q: 'Quel est l\'objectif principal de la Donation au dernier vivant (DDV) ?',
      options: ['Payer moins d\'impôts locaux', 'Déshériter les enfants', 'Améliorer et augmenter massivement les droits (le choix d\'héritage) du conjoint survivant par rapport à ce que prévoit la loi par défaut, afin de le protéger au maximum', 'Divorcer plus vite'],
      correct: 2, rationale: 'Sans DDV, la loi protège le conjoint, mais la DDV lui donne "les pleins pouvoirs" sur le patrimoine pour maintenir son niveau de vie.' },
    { q: 'Un époux fait une DDV en secret chez le notaire pour protéger sa femme. Plus tard, ils se fâchent. Peut-il annuler cette donation sans lui dire ?',
      options: ['Non, une donation est toujours irrévocable', 'Uniquement si le juge l\'autorise', 'Oui. La DDV est révocable "ad nutum" (à tout moment, unilatéralement, et même en secret chez le notaire) par le donateur, tant qu\'il est en vie', 'Seulement avec l\'accord de ses enfants'],
      correct: 2, rationale: 'La DDV n\'est qu\'une promesse post-mortem. Pour éviter les drames lors des crises conjugales, la loi autorise l\'époux à retirer ce droit à sa femme sans même avoir à l\'en avertir.' },
    { q: 'Que se passe-t-il automatiquement concernant la DDV en cas de DIVORCE officiel ?',
      options: ['Elle est maintenue pour protéger l\'ex', 'Elle est automatiquement révoquée (annulée) de plein droit par le prononcé du divorce, sauf si l\'époux décide expressément de la maintenir', 'Elle est divisée par deux', 'Elle profite aux enfants'],
      correct: 1, rationale: 'La loi protège les époux étourdis qui auraient oublié d\'annuler leur DDV chez le notaire après un divorce difficile.' },
    { q: 'Si les époux ont des enfants issus UNIQUEMENT de leur couple (enfants communs), la DDV offre un 3ème choix inédit au conjoint survivant (en plus du 100% Usufruit ou 1/4 Pleine Propriété légaux). Lequel ?',
      options: ['Devenir propriétaire des enfants', 'La "Quotité disponible mixte" : 1/4 en Pleine Propriété (PP) PLUS les 3/4 restants en Usufruit. (Il est donc plein propriétaire d\'un quart et a la jouissance de tout le reste)', '50 % en pleine propriété obligatoirement', 'La vente forcée de la maison'],
      correct: 1, rationale: 'C\'est l\'option la plus protectrice possible. Le conjoint garde le contrôle absolu sur sa fin de vie.' },
    { q: 'Si le défunt a un enfant d\'une PREMIÈRE UNION (enfant non commun). Par défaut, la loi enlève au conjoint le droit d\'avoir l\'Usufruit de la maison. Que permet la DDV dans ce cas ?',
      options: ['De déshériter le premier enfant', 'D\'annuler la succession', 'Elle vient "réparer" la loi : grâce à la DDV, le conjoint survivant retrouve le droit de choisir 100 % en Usufruit, empêchant le premier enfant de le chasser de la maison', 'De donner la maison à l\'État'],
      correct: 2, rationale: 'C\'est dans le cadre des familles recomposées que la Donation au dernier vivant est la plus indispensable et la plus utilisée chez les notaires.' },
    { q: 'Fiscalement, quels sont les droits de succession à payer par le conjoint survivant sur ce qu\'il reçoit grâce à la DDV ?',
      options: ['20 %', '60 %', '0 % (Exonération totale, car il est le conjoint survivant, quelle que soit la part qu\'il reçoit)', '5 % après abattement'],
      correct: 2, rationale: 'La loi TEPA protège le conjoint. Même s\'il rafle l\'essentiel du patrimoine grâce à la DDV, il ne paiera pas 1 euro d\'impôt au fisc.' },
    { q: '(Challenge) Qu\'est-ce que l\'extraordinaire faculté de "Cantonnement" exclusive à la DDV ?',
      options: ['Exiler les enfants dans une autre ville', 'Payer les dettes de la famille', 'Le conjoint survivant peut décider de "trier" : il prend une partie de ce que lui offre la DDV (ex: la maison), et abandonne le reste (ex: l\'argent, l\'entreprise) pour que ça aille directement à ses enfants, SANS que ce soit considéré fiscalement comme une donation à ses enfants', 'Encercler la maison pour la protéger'],
      correct: 2, rationale: 'Le conjoint pioche "à la carte" selon ses besoins réels de vieux jours. Ce qui n\'est pas pris accélère la transmission aux enfants.' },
    { q: '(Challenge) Sous quelle forme juridique doit IMPÉRATIVEMENT être rédigée une Donation au dernier vivant ?',
      options: ['Sur papier libre signé sur la table de la cuisine', 'Par e-mail avec accusé de réception', 'Par un "Acte Authentique" obligatoirement rédigé et reçu par un notaire, qui l\'inscrira ensuite au fichier central des testaments (FCDDV)', 'Par un huissier'],
      correct: 2, rationale: 'Toute donation entre vifs (même de biens à venir) exige la solennité de l\'acte notarié pour vérifier le consentement libre et éclairé de l\'époux.' },
  ],
  'w17-d4': [
    { q: 'Dans les contrats de prévoyance, quelle est la définition stricte de "l\'Incapacité" (par opposition à l\'invalidité) ?',
      options: ['La perte d\'un membre', 'Un état TEMPORAIRE où l\'assuré, suite à une maladie ou un accident, est médicalement dans l\'impossibilité de travailler (l\'arrêt de travail classique)', 'Le refus de travailler', 'La mise à la retraite'],
      correct: 1, rationale: 'L\'incapacité est un arrêt de travail avec l\'espoir d\'une guérison. Si l\'état stagne sans guérison (consolidation), on basculera dans l\'invalidité.' },
    { q: 'Lorsqu\'un salarié du privé est en arrêt maladie (incapacité), quel est le premier organisme qui verse une indemnité de base ?',
      options: ['Pôle Emploi', 'La CAF', 'La Sécurité sociale, qui verse des Indemnités Journalières (IJ), correspondant généralement à 50 % du salaire journalier de base (avec un plafond assez bas)', 'La mairie'],
      correct: 2, rationale: 'Cette IJ de 50% fait perdre brutalement la moitié de son pouvoir d\'achat au salarié.' },
    { q: 'Quel est le délai de "Carence" de la Sécurité sociale pour un arrêt maladie classique (hors accident du travail) d\'un salarié du privé ?',
      options: ['0 jour (payé de suite)', '3 jours : les 3 premiers jours de l\'arrêt de travail ne sont pas payés par la Sécurité sociale', '10 jours', '30 jours'],
      correct: 1, rationale: 'Si vous avez la grippe pendant 4 jours, la Sécu ne vous paiera qu\'un seul jour. (De nombreuses entreprises prennent cependant ce délai à leur charge).' },
    { q: 'Face à cette perte de salaire, quel est le rôle du contrat de "Prévoyance Incapacité" ?',
      options: ['Payer les médicaments à la pharmacie', 'Verser une Indemnité Journalière COMPLÉMENTAIRE (souvent prise en charge via l\'employeur) pour maintenir le salaire de l\'employé à 80, 90 ou 100 % de son revenu net habituel', 'Licencier l\'employé', 'Remplacer l\'employé'],
      correct: 1, rationale: 'La prévoyance vient s\'empiler sur la Sécurité sociale pour que la maladie ne se transforme pas en ruine financière.' },
    { q: 'Qu\'est-ce que le "Délai de franchise" spécifique au contrat de Prévoyance privé ?',
      options: ['La période pendant laquelle on peut annuler le contrat', 'Le nombre de jours d\'arrêt de travail CONTINU qu\'il faut dépasser pour que l\'assureur commence à payer (ex : franchise de 30 jours, 60 jours ou 90 jours)', 'Le délai de remboursement de la poste', 'L\'obligation de se soigner en France'],
      correct: 1, rationale: 'Si la franchise est de 90 jours, les arrêts maladie de 2 semaines ne coûteront jamais rien à l\'assureur. Plus la franchise est longue, moins l\'assurance est chère.' },
    { q: 'Pourquoi la Prévoyance Incapacité est-elle absolument VITALE pour les Travailleurs Indépendants (TNS - artisans, commerçants, libéraux) ?',
      options: ['Parce que la loi les oblige à en prendre deux', 'Car, contrairement aux salariés très protégés par le code du travail et l\'entreprise, les indépendants ont des indemnités de base très faibles. Un long arrêt maladie sans prévoyance mène souvent à la faillite de l\'entreprise et du foyer', 'Parce qu\'ils sont souvent malades', 'Car ça baisse leurs impôts fonciers'],
      correct: 1, rationale: 'Un artisan malade ne rentre plus de chiffre d\'affaires mais doit continuer à payer ses charges fixes. Le contrat "Madelin/Prévoyance" est sa seule bouée de sauvetage.' },
    { q: 'En prévoyance (notamment pour les TNS), quelle est la différence entre une indemnisation "Forfaitaire" et "Indemnitaire" ?',
      options: ['Le forfaitaire est payé en liquide', 'L\'Indemnitaire ne couvre que la perte réelle prouvée (plafonnée au salaire). Le Forfaitaire verse la somme exacte prévue au contrat, même si le revenu de l\'assuré a baissé l\'année précédant la maladie', 'Il n\'y a aucune différence', 'L\'Indemnitaire est versé par l\'État'],
      correct: 1, rationale: 'Un indépendant a des revenus qui fluctuent. Avec un contrat forfaitaire (bien meilleur), s\'il est malade une "mauvaise année", il touchera quand même l\'indemnité haute qu\'il a signée au contrat.' },
    { q: 'L\'assurance paie vos indemnités d\'incapacité tous les mois. Pendant combien de temps MAXIMUM cette situation ("l\'Incapacité") peut-elle durer légalement/médicalement ?',
      options: ['1 mois maximum', 'À vie', 'Généralement 1 095 jours (soit 3 ans maximum). Ensuite, l\'assuré doit reprendre le travail, ou bien il bascule dans la case "Invalidité" si la consolidation est prononcée', 'Jusqu\'à la retraite'],
      correct: 2, rationale: 'La médecine considère qu\'après 3 ans, l\'état est stabilisé (en bien ou en mal). L\'incapacité temporaire prend fin.' },
    { q: '(Challenge) Un salarié est en "Mi-temps thérapeutique" (il retravaille à 50 % sur ordre du médecin après une grave maladie). Que fait l\'assurance Prévoyance ?',
      options: ['Elle coupe immédiatement toutes les allocations car il a repris le travail', 'Elle maintient le paiement complet à 100 %', 'Elle l\'indemnise proportionnellement (souvent 50 % de l\'indemnité prévue) pour compléter le demi-salaire versé par l\'employeur, favorisant ainsi une reprise douce du travail', 'Elle oblige l\'employeur à le licencier'],
      correct: 2, rationale: 'Le but est d\'encourager la réinsertion sans pénaliser financièrement le malade.' },
    { q: '(Challenge) Parfois, les contrats d\'assurance liés à l\'incapacité de travail d\'un indépendant incluent la "Garantie Frais Généraux". Qu\'est-ce que c\'est ?',
      options: ['Le remboursement du comptable', 'Pendant son arrêt maladie, l\'assurance lui verse son salaire (indemnité) PLUS une somme dédiée exclusivement au paiement de ses charges fixes d\'entreprise (loyer du local, électricité, leasing de la machine) pour éviter le dépôt de bilan', 'La prise en charge de ses repas', 'L\'achat d\'un nouveau bureau'],
      correct: 1, rationale: 'L\'artisan malade peut ainsi continuer à payer le loyer de son atelier pour rouvrir son entreprise le jour où il sera guéri.' },
  ],
  'w17-d5': [
    { q: 'En immobilier, à quoi sert le calcul de la "rentabilité" (ou rendement) ?',
      options: ['À connaître la superficie exacte de l\'appartement', 'À déterminer la commission de l\'agent immobilier', 'À évaluer la performance financière d\'un investissement en mesurant le rapport entre les revenus générés (loyers) et le capital investi (prix du bien)', 'À calculer la plus-value à la revente'],
      correct: 2, rationale: 'Cela permet de comparer mathématiquement l\'attractivité d\'un appartement avec un placement en bourse ou un Livret A.' },
    { q: 'Quelle est la formule mathématique simplifiée de la "Rentabilité Brute" ?',
      options: ['(Loyer d\'un mois / Prix d\'achat) x 100', '(Loyer annuel / Prix d\'achat du bien FAI) x 100', 'Prix d\'achat / Loyer annuel', 'Loyer annuel x 100'],
      correct: 1, rationale: 'C\'est l\'indicateur le plus utilisé dans les annonces immobilières car il gonfle artificiellement l\'attractivité du bien.' },
    { q: 'Un appartement acheté 100 000 € se loue 500 € par mois. Quelle est sa rentabilité BRUTE annuelle ?',
      options: ['5 %', '6 %', '50 %', '0,5 %'],
      correct: 1, rationale: '(500 € x 12 mois) = 6 000 € de loyers annuels. (6 000 / 100 000) x 100 = 6 % brut.' },
    { q: 'Quel est le défaut majeur de la "Rentabilité Brute" pour un investisseur sérieux ?',
      options: ['Elle est trop compliquée à calculer', 'Elle ne prend en compte aucune charge réelle (taxe foncière, assurance, charges de copropriété, travaux). C\'est un chiffre théorique totalement déconnecté de l\'enrichissement réel du propriétaire', 'Elle est interdite par la loi', 'Elle surévalue le prix d\'achat'],
      correct: 1, rationale: 'Un bien peut afficher 10% Brut et être un gouffre financier si les charges de copropriété (ascenseur, gardien) coûtent 3 mois de loyers.' },
    { q: 'Comment passe-t-on de la "Rentabilité Brute" à la "Rentabilité Nette de charges" ?',
      options: ['En déduisant les courses alimentaires du propriétaire', 'On soustrait des loyers annuels TOUTES les charges incombant au propriétaire (Taxe Foncière, assurance PNO, charges de copropriété non récupérables, frais de gestion), avant de diviser par le prix d\'achat global (notaire inclus)', 'En enlevant la commission d\'agence', 'En divisant le résultat par deux'],
      correct: 1, rationale: 'C\'est le vrai thermomètre immobilier. On prend les loyers qui restent réellement en poche à la fin de l\'année après avoir payé l\'entretien et l\'administration du bien.' },
    { q: 'Si l\'on pousse l\'analyse financière jusqu\'au bout, on cherche la "Rentabilité Nette-Nette" (ou Nette d\'impôts). Qu\'est-ce que c\'est ?',
      options: ['La rentabilité de la revente', 'C\'est la rentabilité Nette de charges, à laquelle ON SOUSTRAIT également l\'Impact Fiscal : l\'impôt sur les revenus fonciers/BIC et les prélèvements sociaux que le propriétaire devra payer sur ses loyers', 'Le loyer perçu sans déclaration', 'La rentabilité garantie par l\'État'],
      correct: 1, rationale: 'Un cadre fortement imposé (TMI 41%) peut voir une rentabilité nette de charges de 5% tomber à 2,5% nette-nette si la fiscalité n\'est pas optimisée (d\'où l\'importance du LMNP ou du Déficit Foncier).' },
    { q: 'Quel élément crucial de la vraie vie locative (l\'aléa) devez-vous inclure (provisionner) dans votre calcul de rentabilité sous peine d\'être lourdement déçu ?',
      options: ['Le prix du notaire', 'Le risque que la ville change de nom', 'La vacance locative (estimer que l\'appartement sera vide environ 1 mois tous les 2 ou 3 ans) et la provision pour réparations/vétusté (peinture, chaudière)', 'L\'amende pour bruit'],
      correct: 2, rationale: 'Un tableau Excel parfait (rempli à 100% sur 15 ans) n\'existe pas en immobilier. Les transitions de locataires créent des "trous" dans les loyers.' },
    { q: 'Lors du calcul du "prix d\'acquisition total" (le dénominateur de la formule), que faut-il obligatoirement ajouter au prix "net vendeur" de l\'appartement pour ne pas fausser le rendement ?',
      options: ['Les loyers futurs', 'Le prix des assurances', 'Les Frais d\'Agence (FAI), les Frais de Notaire (Droits de mutation), les éventuels frais de dossier bancaire ou de garantie, et les travaux initiaux prévus', 'Le salaire de l\'investisseur'],
      correct: 2, rationale: 'Si vous achetez 100 000€ "net vendeur", mais sortez en réalité 115 000€ pour payer le notaire, l\'agence et refaire la cuisine, votre rendement doit se calculer sur les 115 000€ d\'effort total.' },
    { q: '(Challenge) Qu\'est-ce que le T.R.I (Taux de Rendement Interne), l\'indicateur ultime prisé par les investisseurs professionnels ?',
      options: ['C\'est la rentabilité brute augmentée du prêt', 'C\'est un indicateur global qui intègre à la fois le rendement locatif annuel (cash flow), l\'effet de levier du crédit dans le temps, la fiscalité, ET la plus-value (ou moins-value) estimée à la revente à la fin de l\'opération', 'C\'est la taxe de rendement imposée par la mairie', 'C\'est le rendement exclusif des SCPI'],
      correct: 1, rationale: 'Un bien qui ne dégage aucun loyer (cash flow nul) mais qui est revendu 2 fois plus cher 10 ans plus tard (forte plus-value) aura un TRI excellent malgré une "rentabilité mensuelle" catastrophique.' },
    { q: '(Challenge) Vous achetez un petit appartement FAI : 100 000 € (plus 8 000 € de notaire = 108 000 €). Il se loue 500 € par mois (6 000 €/an). Vos charges incombant au propriétaire sont : 600 € Taxe foncière, 400 € Copropriété non récupérable, 200 € Assurance = 1 200 €/an. Quelle est la Rentabilité Nette de charges (environ) ?',
      options: ['4,4 %', '6 %', '5,5 %', '3 %'],
      correct: 0, rationale: 'Loyers nets de charges = 6 000 - 1 200 = 4 800 €. Prix d\'acquisition total = 108 000 €. Calcul : (4 800 / 108 000) x 100 = 4,44 %. (Le vendeur, lui, affichait fièrement un 6% Brut sur l\'annonce...).' },
  ],
};
