/* Questions de la semaine 3. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w3-d0': [
    { q: 'Qu\'est-ce que l\'inflation en termes économiques ?',
      options: ['La baisse du chômage', 'L\'augmentation des impôts', 'La hausse générale, durable et auto-entretenue des prix des biens et services', 'La baisse des prix dans les supermarchés'],
      correct: 2, rationale: 'Elle reflète une diminution du pouvoir d\'achat de la monnaie.' },
    { q: 'Quel indicateur statistique est utilisé en France pour mesurer l\'inflation ?',
      options: ['Le CAC 40', 'Le taux du Livret A', 'Le Produit Intérieur Brut (PIB)', 'L\'Indice des Prix à la Consommation (IPC) calculé par l\'INSEE'],
      correct: 3, rationale: 'L\'INSEE suit l\'évolution du prix d\'un "panier moyen" de biens et services.' },
    { q: 'Quel est l\'impact de l\'inflation sur 10 000 € laissés sur un compte courant sans rémunération ?',
      options: ['La valeur "réelle" (le pouvoir d\'achat de ces 10 000 €) diminue avec le temps', 'Le capital augmente nominalement', 'La banque supprime le compte', 'Il n\'y a aucun impact'],
      correct: 0, rationale: 'Si l\'inflation est de 5%, ces 10 000 € vous permettent d\'acheter beaucoup moins de choses l\'année suivante.' },
    { q: 'Face à l\'inflation, qui est généralement considéré comme "favorisé" ?',
      options: ['L\'épargnant qui garde des liquidités', 'Le rentier avec des revenus fixes', 'L\'emprunteur ayant contracté un crédit immobilier à taux FIXE', 'Le supermarché'],
      correct: 2, rationale: 'La mensualité reste identique, mais le "poids" de la dette dans son budget s\'allège.' },
    { q: 'Qu\'appelle-t-on le "rendement réel" d\'un placement financier ?',
      options: ['Le taux brut affiché par la banque', 'Le rendement net d\'impôts auquel on soustrait le taux d\'inflation', 'Le rendement de l\'immobilier', 'Les intérêts perçus en cash'],
      correct: 1, rationale: 'Si un placement rapporte 3% net et que l\'inflation est à 5%, vous vous êtes appauvri de 2%.' },
    { q: 'Quel rôle principal a la Banque Centrale Européenne (BCE) face à l\'inflation ?',
      options: ['Elle fixe les prix dans les magasins', 'Elle garantit un chômage à 0 %', 'Elle imprime les billets de monopoly', 'Elle doit maintenir la stabilité des prix, en visant une inflation proche de 2 % à moyen terme'],
      correct: 3, rationale: 'Une inflation modérée (autour de 2%) lubrifie l\'économie.' },
    { q: 'Quel est l\'outil principal utilisé par une Banque Centrale pour faire baisser l\'inflation ?',
      options: ['Augmenter ses taux directeurs (rendant le crédit plus cher pour refroidir la demande)', 'Baisser les impôts', 'Distribuer de l\'argent aux ménages', 'Supprimer les banques'],
      correct: 0, rationale: 'Si emprunter coûte cher, les ménages consomment moins, ce qui freine la hausse des prix.' },
    { q: 'En économie, quel est le contraire de l\'inflation ?',
      options: ['La stagflation', 'La déflation (baisse généralisée des prix)', 'L\'hyperinflation', 'La récession'],
      correct: 1, rationale: 'La déflation est un cauchemar économique car les consommateurs reportent leurs achats.' },
    { q: '(Challenge) Vous placez 5 000 € à 2%. L\'inflation est à 4%. Quel est l\'impact réel sur votre épargne ?',
      options: ['Votre pouvoir d\'achat a augmenté de 2%', 'Votre pouvoir d\'achat a stagné', 'Vous avez perdu 6%', 'Vous avez "perdu" environ 2% de pouvoir d\'achat (rendement réel négatif)'],
      correct: 3, rationale: 'Rendement nominal (2%) - Inflation (4%) = -2%.' },
    { q: '(Challenge) Quelle classe d\'actifs est souvent considérée comme la meilleure "protection" contre l\'inflation sur le très long terme ?',
      options: ['Les actifs tangibles (immobilier, actions d\'entreprises)', 'L\'argent liquide (cash)', 'Les obligations à taux fixe sur 20 ans', 'Les bons du trésor'],
      correct: 0, rationale: 'Les loyers sont indexés, et les entreprises solides augmentent leurs prix de vente.' },
  ],
  'w3-d1': [
    { q: 'Qu\'est-ce que la Tranche Marginale d\'Imposition (TMI) ?',
      options: ['Le taux moyen auquel tout le salaire est imposé', 'Le taux d\'imposition qui s\'applique à la part la plus élevée (les derniers euros) de vos revenus', 'Une taxe réservée uniquement aux chefs d\'entreprise', 'Le montant fixe que l\'on paie chaque mois aux impôts'],
      correct: 1, rationale: '"Marginale" signifie "à la marge". C\'est le taux qui frappera toute augmentation de revenu (une prime, un loyer supplémentaire).' },
    { q: 'Le système d\'imposition sur le revenu en France est dit "progressif". Qu\'est-ce que cela signifie ?',
      options: ['L\'impôt augmente avec l\'âge', 'Les revenus sont découpés en tranches, et chaque tranche est imposée à un taux de plus en plus élevé', 'Plus on gagne, plus on est remboursé par l\'État', 'Tout le revenu est imposé au taux de la tranche la plus haute atteinte'],
      correct: 1, rationale: 'Le premier bloc de revenus n\'est pas imposé (0%), le suivant l\'est un peu (11%), le suivant davantage (30%), etc.' },
    { q: 'Une idée reçue fréquente est : "J\'ai eu une augmentation, j\'ai sauté de tranche d\'imposition, je vais donc perdre de l\'argent au global". Est-ce vrai ?',
      options: ['Oui, le nouveau taux s\'applique à tout le salaire', 'Non, car seule la partie du revenu qui dépasse le seuil de la nouvelle tranche sera imposée à ce nouveau taux plus fort', 'Oui, car les impôts prennent 100% de l\'augmentation', 'Non, car les impôts sont annulés l\'année de l\'augmentation'],
      correct: 1, rationale: 'Une augmentation de salaire permet toujours de gagner plus d\'argent en net, même si l\'impôt augmente.' },
    { q: 'Si votre TMI est de 30 %, cela signifie-t-il que 30 % de tout votre salaire part aux impôts ?',
      options: ['Oui, c\'est exactement ça', 'Non, le pourcentage global de votre salaire prélevé par les impôts (Taux Moyen) est forcément inférieur à 30 %', 'Non, cela signifie que vous payez 30 € d\'impôts par mois', 'Oui, et même plus avec l\'inflation'],
      correct: 1, rationale: 'Comme vos premiers milliers d\'euros sont imposés à 0% puis à 11%, la moyenne totale (le taux moyen) sera toujours inférieure à votre taux marginal (30%).' },
    { q: 'Quelles sont (approximativement) les tranches d\'imposition actuelles en France ?',
      options: ['0 %, 10 %, 20 %, 50 %, 75 %', '0 %, 11 %, 30 %, 41 %, 45 %', '5 %, 15 %, 25 %', 'Il y a une tranche unique de 20 % pour tout le monde'],
      correct: 1, rationale: 'Ces pourcentages sont les taux applicables aux différents paliers de revenus nets imposables par part fiscale.' },
    { q: 'Pourquoi est-il indispensable de connaître sa TMI avant de faire un investissement locatif classique (sans défiscalisation spécifique) ?',
      options: ['Pour choisir la couleur des murs', 'Car les loyers nets seront taxés à votre TMI (auxquels s\'ajoutent les prélèvements sociaux)', 'Parce que la TMI fixe le montant de la taxe foncière', 'Pour prouver au locataire qu\'on est solvable'],
      correct: 1, rationale: 'Si votre TMI est de 30%, et avec 17,2% de prélèvements sociaux, près de la moitié (47,2%) des loyers imposables partira en impôts.' },
    { q: 'Quel est l\'impact d\'une "déduction fiscale" (ex: versement sur un Plan Épargne Retraite - PER) par rapport à votre TMI ?',
      options: ['L\'économie d\'impôt est déconnectée de la TMI', 'Plus votre TMI est élevée, plus l\'économie d\'impôt générée par la déduction sera forte', 'Plus votre TMI est basse, plus l\'économie d\'impôt sera forte', 'Le PER augmente la TMI'],
      correct: 1, rationale: 'Une déduction vient gommer les revenus de votre tranche la plus haute. Si vous déduisez 1000€ et que votre TMI est à 41%, vous économisez 410€. Si votre TMI est à 11%, vous n\'économisez que 110€.' },
    { q: 'Comment le quotient familial (le nombre de parts de votre foyer) influence-t-il votre TMI ?',
      options: ['Il multiplie la TMI par deux', 'Il n\'a aucun impact', 'Il permet de diviser le revenu du foyer, ce qui peut vous faire "redescendre" dans une tranche d\'imposition inférieure', 'Il annule les prélèvements sociaux'],
      correct: 2, rationale: 'C\'est pour cela qu\'à revenus égaux, un couple avec 3 enfants aura souvent une TMI (et un impôt) inférieure à un célibataire.' },
    { q: '(Challenge) Un célibataire (1 part) a un revenu imposable de 29 000 €. Sachant que la tranche à 11% va environ de 11 000 € à 28 000 €, et la tranche à 30% commence après 28 000 €. Quelle est sa TMI ?',
      options: ['0 %', '11 %', '30 %', '41 %'],
      correct: 2, rationale: 'Ses revenus dépassent le seuil des 28 000 €. Ses derniers euros (les 1 000 € situés entre 28k et 29k) sont imposés à 30%. Sa TMI est donc de 30%.' },
    { q: '(Challenge) Sur les gains financiers (actions, livrets non réglementés), un contribuable a le choix entre la Flat Tax (PFU à 30% : 12,8% d\'impôt + 17,2% taxes sociales) ou le barème progressif. Si sa TMI est de 11%, que doit-il choisir pour payer le moins d\'impôts ?',
      options: ['La Flat Tax, car c\'est toujours le meilleur choix', 'Le barème progressif (sa TMI 11% + 17,2% taxes sociales = 28,2% au total)', 'Le PFU, car le barème progressif double les taxes sociales', 'Cela revient strictement au même'],
      correct: 1, rationale: 'Avec une TMI à 11%, l\'imposition globale au barème sera de 28,2% (11 + 17,2), ce qui est inférieur aux 30% de la Flat Tax. Il aura donc intérêt à cocher l\'option pour le barème.' },
  ],
  'w3-d2': [
    { q: 'Qu\'est-ce que "l\'âge légal de départ à la retraite" en France ?',
      options: ['L\'âge auquel on est obligé de s\'arrêter de travailler', 'L\'âge minimum à partir duquel un assuré acquiert le droit de demander la liquidation de sa pension de retraite', 'L\'âge où l\'on obtient automatiquement sa retraite à taux plein', 'L\'âge auquel l\'employeur peut licencier sans motif'],
      correct: 1, rationale: 'C\'est la borne d\'âge inférieure. Avant cet âge (sauf exceptions), on ne peut pas ouvrir ses droits à la retraite.' },
    { q: 'Suite à la récente réforme des retraites (2023), vers quel âge légal le système français se décale-t-il progressivement ?',
      options: ['60 ans', '62 ans', '64 ans', '67 ans'],
      correct: 2, rationale: 'L\'âge légal, qui était de 62 ans, est progressivement repoussé pour atteindre 64 ans pour les générations nées à partir de 1968.' },
    { q: 'Qu\'est-ce que le "taux plein" pour le régime de base ?',
      options: ['Une retraite égale à 100% du dernier salaire', 'Le taux maximum de calcul de la pension (généralement 50 % du salaire annuel moyen), appliqué lorsqu\'on a réuni tous ses trimestres', 'Le fait de payer plein tarif ses cotisations', 'Une prime versée par l\'État lors du pot de départ'],
      correct: 1, rationale: 'Le taux plein garantit que votre retraite n\'est amputée d\'aucune décote.' },
    { q: 'Que se passe-t-il si une personne part à la retraite à l\'âge légal, mais qu\'il lui manque des trimestres ?',
      options: ['Elle obtient le taux plein par solidarité', 'Sa pension est repoussée d\'autant d\'années qu\'il manque de trimestres', 'Elle subit une "décote" (réduction) définitive sur le montant de sa pension', 'L\'employeur doit payer la différence'],
      correct: 2, rationale: 'La décote pénalise l\'assuré en baissant le taux de calcul de sa retraite à vie.' },
    { q: 'Quel est l\'âge du "taux plein automatique" (ou âge d\'annulation de la décote), âge auquel on obtient une retraite à taux plein MÊME s\'il manque des trimestres ?',
      options: ['62 ans', '64 ans', '65 ans', '67 ans'],
      correct: 3, rationale: 'À 67 ans, peu importe le nombre de trimestres validés, la caisse de retraite ne peut plus appliquer de décote. Le taux plein est garanti (mais la pension sera quand même proportionnelle au nombre de trimestres travaillés).' },
    { q: 'Qu\'est-ce que le dispositif "Carrières longues" ?',
      options: ['Un bonus financier pour ceux qui font de longues journées', 'La possibilité de partir à la retraite AVANT l\'âge légal si on a commencé à travailler très jeune (avant 16, 18, 20 ou 21 ans) et qu\'on a cotisé suffisamment de trimestres', 'L\'obligation de travailler jusqu\'à 70 ans', 'Un régime spécial réservé aux cadres supérieurs'],
      correct: 1, rationale: 'C\'est la principale exception à l\'âge légal. Ceux qui ont commencé tôt et ont une carrière complète peuvent partir de façon anticipée.' },
    { q: 'Si un salarié atteint l\'âge légal, a déjà tous ses trimestres pour le taux plein, mais décide de continuer à travailler, de quoi bénéficie-t-il ?',
      options: ['De la décote', 'De la surcote (une majoration définitive du montant de sa retraite pour chaque trimestre supplémentaire travaillé)', 'D\'une annulation de ses impôts', 'De rien, les cotisations sont perdues'],
      correct: 1, rationale: 'Continuer de travailler au-delà de l\'âge légal ET de la durée d\'assurance requise permet de gonfler sa pension (généralement +1,25% par trimestre supplémentaire).' },
    { q: 'Comment est calculé le "Salaire Annuel Moyen" (SAM) qui sert de base au calcul de la retraite dans le régime général (salariés du privé) ?',
      options: ['Sur la moyenne des 6 derniers mois de salaire', 'Sur la moyenne des 25 meilleures années de salaire (revalorisées de l\'inflation)', 'Uniquement sur l\'année la plus rémunératrice', 'Sur le SMIC en vigueur'],
      correct: 1, rationale: 'Contrairement aux fonctionnaires, la retraite du privé lisse les revenus sur une très longue période (les 25 meilleures années).' },
    { q: '(Challenge) Un assuré a 64 ans (l\'âge légal). Pour sa génération, il lui faut 172 trimestres pour le taux plein. Il n\'en a validé que 160. S\'il part maintenant, quelle règle s\'applique pour calculer sa décote ?',
      options: ['On lui retire 12% purs de sa pension', 'On compte le nombre de trimestres manquants (ici 12) et on applique un coefficient de minoration', 'On divise sa pension par deux', 'La décote est interdite à l\'âge légal'],
      correct: 1, rationale: 'La décote se calcule par trimestre manquant. La loi retient le chiffre le plus favorable entre : les trimestres manquants pour atteindre les 172, OU les trimestres manquants pour atteindre ses 67 ans.' },
    { q: '(Challenge) Quelle est la différence majeure de calcul du salaire de référence (pour la retraite de base) entre un salarié du privé et un fonctionnaire civil de l\'Etat ?',
      options: ['Le privé prend les 10 meilleures années, le public les 25 meilleures', 'Le privé prend les 25 meilleures années, le public prend généralement le traitement indiciaire des 6 derniers mois (hors primes)', 'Le privé inclut toutes les années, le public prend la meilleure année', 'Il n\'y a aucune différence'],
      correct: 1, rationale: 'C\'est une différence structurelle historique forte, même si la prise en compte (ou non) des primes vient souvent nuancer le montant final.' },
  ],
  'w3-d3': [
    { q: 'Quelle est la nature de la fonction d\'un notaire en France ?',
      options: ['C\'est un agent immobilier indépendant', 'C\'est un avocat spécialisé dans les divorces', 'C\'est un officier public et ministériel mandaté par l\'État pour conférer l\'authenticité aux actes', 'C\'est un fonctionnaire salarié par la mairie'],
      correct: 2, rationale: 'Bien qu\'exerçant en profession libérale, le notaire agit au nom de l\'État. Son sceau et sa signature donnent à l\'acte une force légale incontestable.' },
    { q: 'Le passage chez le notaire est-il obligatoire pour finaliser l\'achat ou la vente d\'un bien immobilier ?',
      options: ['Non, une poignée de main suffit', 'Non, un contrat rédigé par un agent immobilier (compromis) vaut acte définitif', 'Oui, car lui seul peut assurer la publication de l\'acte au Service de la Publicité Foncière (qui rend la vente opposable aux tiers)', 'Oui, uniquement si l\'acheteur prend un crédit'],
      correct: 2, rationale: 'Pour que le changement de propriétaire soit officiellement reconnu par l\'État et tous les tiers, l\'acte authentique est obligatoire.' },
    { q: 'Dans les fameux "frais de notaire" payés lors d\'un achat immobilier, qui perçoit réellement la majorité de l\'argent ?',
      options: ['Le notaire lui-même (rémunération)', 'L\'agence immobilière', 'L\'État et les collectivités locales (Droits d\'enregistrement et taxes)', 'La banque'],
      correct: 2, rationale: 'L\'appellation exacte est "Frais d\'acquisition". Environ 80% de la somme correspond à des taxes. La rémunération réelle du notaire (les émoluments) ne représente qu\'environ 10 à 15% du total.' },
    { q: 'Concernant les testaments, qu\'est-ce qu\'un "testament authentique" ?',
      options: ['Un testament écrit seul chez soi sur une feuille volante', 'Un testament dicté par le testateur au notaire, en présence de deux témoins (ou d\'un second notaire)', 'Un testament vidéo enregistré sur smartphone', 'Un testament obligatoirement écrit à la plume'],
      correct: 1, rationale: 'L\'acte authentique offre la sécurité maximale contre le risque de perte, de destruction ou de contestation, contrairement au testament "olographe" (écrit soi-même).' },
    { q: 'Lequel de ces actes de transmission nécessite OBLIGATOIREMENT l\'intervention d\'un notaire (sous peine de nullité) ?',
      options: ['Le don manuel d\'une somme d\'argent', 'La donation d\'un bien immobilier', 'L\'ouverture d\'une assurance-vie', 'La rédaction d\'un testament olographe'],
      correct: 1, rationale: 'Tout acte entraînant la mutation (changement de propriétaire) d\'un bien immobilier requiert un acte authentique notarié.' },
    { q: 'Que recouvre le "devoir de conseil" du notaire ?',
      options: ['L\'obligation de conseiller à son client l\'assurance la plus chère', 'L\'obligation légale d\'éclairer les parties sur la portée, les effets et les risques de l\'acte qu\'elles vont signer, en toute neutralité', 'Le droit de prendre les décisions à la place du client', 'Le devoir de ne conseiller que le vendeur d\'un bien'],
      correct: 1, rationale: 'Le notaire est un magistrat de l\'amiable. Il doit être neutre, impartial, et s\'assurer que l\'acte est équilibré et compris par les deux parties.' },
    { q: 'Dans le cadre d\'un décès, dans quel cas le recours à un notaire pour régler la succession est-il obligatoire ?',
      options: ['Le recours est obligatoire pour absolument tous les décès', 'Si le défunt possédait un bien immobilier, ou un patrimoine supérieur à 5 000 €, ou s\'il y a un testament/contrat de mariage', 'Uniquement si les héritiers ne s\'entendent pas', 'Uniquement s\'il n\'y a pas d\'enfants'],
      correct: 1, rationale: 'Dans ces cas, l\'acte de notoriété et les attestations immobilières doivent être rédigés par le notaire.' },
    { q: 'Quelle est la principale force de "l\'acte authentique" (notarié) par rapport à un "acte sous seing privé" (contrat classique) en cas de litige financier ?',
      options: ['Il coûte moins cher', 'Il a une "force exécutoire", c\'est-à-dire qu\'il permet de faire appel à un huissier pour saisir directement les biens du débiteur sans avoir à passer par un procès préalable', 'Il annule la dette', 'Il efface le casier judiciaire'],
      correct: 1, rationale: 'Un acte notarié de prêt, par exemple, vaut jugement. En cas de non-paiement, le créancier n\'a pas besoin de faire un procès long et coûteux pour récupérer son argent.' },
    { q: '(Challenge) Pourquoi les "frais de notaire" sont-ils différents entre l\'immobilier ancien (environ 7 à 8%) et l\'immobilier neuf (environ 2 à 3%) ?',
      options: ['Parce que les notaires facturent le double pour les vieilles maisons', 'Parce que l\'État perçoit moins de taxes (droits de mutation) sur le neuf pour encourager la construction', 'Parce qu\'il n\'y a pas de terrain dans le neuf', 'Parce que les frais d\'agence sont inclus dans l\'ancien'],
      correct: 1, rationale: 'L\'immobilier neuf bénéficie d\'une fiscalité allégée (Taxe de publicité foncière très réduite), la rémunération du notaire, elle, reste proportionnellement la même.' },
    { q: '(Challenge) Deux personnes se pacsent. Le recours au notaire est-il obligatoire ?',
      options: ['Oui, le Pacs est exclusivement notarié', 'Non, un Pacs peut être conclu en mairie, mais le notaire est fortement conseillé si le couple possède un patrimoine important ou souhaite aménager le régime de la séparation des biens par défaut', 'Non, un Pacs se fait uniquement sur Internet', 'Oui, s\'ils ont moins de 25 ans'],
      correct: 1, rationale: 'Le Pacs "sous seing privé" enregistré en mairie (ou tribunal) est gratuit, mais le Pacs notarié permet de rédiger une convention sur-mesure (notamment pour l\'indivision de biens).' },
  ],
  'w3-d4': [
    { q: 'Que signifie l\'acronyme MRH dans le monde des assurances ?',
      options: ['Mutuelle Remboursement Hospitalier', 'Multirisque Habitation', 'Maison Résidence Hôtelière', 'Mandat Responsabilité Civile'],
      correct: 1, rationale: 'C\'est le contrat d\'assurance global qui couvre le logement, le mobilier et la responsabilité civile des occupants.' },
    { q: 'La souscription à une assurance habitation (MRH) est-elle obligatoire pour un locataire d\'un logement vide (résidence principale) ?',
      options: ['Non, c\'est purement facultatif', 'Oui, la loi oblige le locataire à s\'assurer au minimum pour les risques locatifs', 'Seulement s\'il a des animaux domestiques', 'Uniquement si le loyer dépasse 1000 €/mois'],
      correct: 1, rationale: 'Le locataire doit remettre une attestation d\'assurance au propriétaire à la remise des clés et chaque année.' },
    { q: 'Que couvrent exactement les garanties minimales "risques locatifs" obligatoires ?',
      options: ['Les dommages matériels causés au logement loué par un incendie, une explosion ou un dégât des eaux', 'Le vol de l\'ordinateur du locataire', 'Les loyers impayés par le locataire', 'La panne du frigidaire du locataire'],
      correct: 0, rationale: 'Cette garantie de base vise à protéger le bien immobilier du propriétaire contre les gros sinistres dont le locataire serait responsable.' },
    { q: 'Que risque le locataire s\'il ne fournit pas d\'attestation d\'assurance MRH à son propriétaire ?',
      options: ['Une simple relance par e-mail sans conséquence', 'Le propriétaire peut résilier le bail (si une clause le prévoit) ou souscrire une assurance à la place du locataire en répercutant le coût (+ une majoration) sur le loyer', 'La prison avec sursis', 'Le locataire devient propriétaire du bien'],
      correct: 1, rationale: 'La loi Alur permet au propriétaire de protéger son bien si le locataire est défaillant sur son obligation d\'assurance.' },
    { q: 'La garantie "Recours des voisins et des tiers" est-elle comprise dans les risques locatifs de base obligatoires de la loi ?',
      options: ['Oui, toujours', 'Non, elle est facultative légalement, mais indispensable car sans elle, le locataire devra payer de sa poche les dégâts causés chez les voisins (ex: l\'eau qui coule à l\'étage inférieur)', 'Elle est interdite en France', 'Elle est payée par la mairie'],
      correct: 1, rationale: 'Les contrats MRH incluent heureusement quasi-systématiquement cette couverture pour éviter la ruine financière du locataire en cas d\'incendie qui se propage.' },
    { q: 'Le locataire est cambriolé, sa télévision et ses bijoux sont volés. La garantie de base "risques locatifs" le rembourse-t-elle ?',
      options: ['Oui, le vol est toujours inclus', 'Non, la garantie risques locatifs ne protège que le bâti (les murs)', 'Oui, mais seulement si la porte était ouverte', 'Le propriétaire doit rembourser la télévision'],
      correct: 1, rationale: 'Pour assurer ses propres biens (mobilier), le locataire doit souscrire des garanties complémentaires incluses dans le "multirisque" (garantie Vol, garantie Mobilier).' },
    { q: 'Une assurance MRH inclut très souvent la garantie "Responsabilité Civile (RC) Vie Privée". À quoi sert-elle ?',
      options: ['À couvrir les dommages corporels, matériels ou immatériels causés accidentellement à autrui par le locataire (ou ses enfants/animaux) dans la vie de tous les jours', 'À payer les amendes routières', 'À rembourser l\'employeur si le locataire casse du matériel au bureau', 'À annuler un contrat de mariage'],
      correct: 0, rationale: 'Si votre enfant casse les lunettes d\'un ami, ou si vous blessez quelqu\'un à vélo, c\'est cette RC de votre contrat MRH qui interviendra.' },
    { q: 'En cas de sinistre total (incendie) détruisant les meubles du locataire, comment l\'assurance évalue-t-elle le remboursement du mobilier ?',
      options: ['À son prix d\'achat initial systématiquement', 'Selon sa valeur d\'usage (avec application d\'une vétusté/décote liée à l\'âge) ou en "valeur à neuf" si le locataire a souscrit cette option spécifique', 'Au poids des objets', 'L\'assureur remplace physiquement les meubles lui-même'],
      correct: 1, rationale: 'Sans l\'option valeur à neuf, un ordinateur de 5 ans ne sera remboursé qu\'une fraction de son prix initial.' },
    { q: '(Challenge) Un appartement est loué en "colocation" à 3 étudiants. Comment doivent-ils gérer l\'assurance habitation ?',
      options: ['Chaque étudiant doit prendre une assurance sur la totalité de l\'appartement', 'Au moins un des colocataires doit obligatoirement être assuré pour les risques locatifs, mais il est recommandé qu\'ils soient tous sur le même contrat pour couvrir la RC de chacun', 'Les étudiants sont exonérés d\'assurance', 'C\'est le propriétaire qui est obligé de s\'assurer pour eux'],
      correct: 1, rationale: 'La loi impose la couverture du bien. Une seule attestation suffit au bailleur, mais pour des raisons de responsabilité entre eux, un contrat commun ou croisé est primordial.' },
    { q: '(Challenge) Depuis la loi Alur, le locataire d\'un logement MEUBLÉ (résidence principale) a-t-il les mêmes obligations d\'assurance que pour un logement vide ?',
      options: ['Non, le meublé n\'est soumis à aucune règle', 'Oui, l\'obligation de s\'assurer contre les risques locatifs a été étendue aux locataires de meublés (à titre de résidence principale)', 'Non, c\'est le syndic de copropriété qui paie', 'Oui, mais seulement pour les séjours de moins d\'un mois'],
      correct: 1, rationale: 'Avant 2014, le locataire en meublé n\'avait pas l\'obligation légale de s\'assurer (même s\'il restait responsable de ses actes). La loi a uniformisé la règle.' },
  ],
  'w3-d5': [
    { q: 'Qu\'appelle-t-on la "capacité d\'endettement" (ou capacité d\'emprunt) ?',
      options: ['La somme d\'argent qu\'on peut prêter à ses amis', 'Le montant maximum qu\'un individu ou un foyer peut emprunter à la banque, en tenant compte de ses revenus et du taux d\'endettement autorisé', 'Le montant total des dettes du pays', 'Le seuil à partir duquel on est déclaré en faillite personnelle'],
      correct: 1, rationale: 'Elle permet de savoir, avant même de visiter un bien, quel est le budget maximum de l\'acheteur.' },
    { q: 'Actuellement (et suite aux directives du HCSF), quel est le taux d\'endettement maximum généralement imposé par les banques ?',
      options: ['20 %', '33 %', '35 % (assurance emprunteur incluse)', '50 %'],
      correct: 2, rationale: 'Le Haut Conseil de Stabilité Financière a fixé ce plafond. Pour 1000 € de revenus nets, les mensualités globales ne doivent pas dépasser 350 €.' },
    { q: 'Dans le calcul du taux d\'endettement, quels éléments sont considérés comme des "charges fixes" par la banque ?',
      options: ['Les factures d\'électricité et d\'eau', 'La nourriture et les loisirs', 'Les crédits en cours (auto, conso, immo) et les pensions alimentaires versées', 'L\'abonnement à la salle de sport'],
      correct: 2, rationale: 'La banque ne regarde pas vos dépenses courantes de vie, mais vos obligations financières contractuelles à long terme (et parfois le loyer si vous restez locataire).' },
    { q: 'Qu\'est-ce que le "reste à vivre" que la banque va également vérifier ?',
      options: ['Le montant des courses au supermarché', 'La somme d\'argent qu\'il reste au foyer pour vivre au quotidien, une fois que la mensualité du prêt et les charges fixes ont été payées', 'L\'argent de poche des enfants', 'Les économies placées sur un livret A'],
      correct: 1, rationale: 'Même avec un taux à 35%, si le "reste à vivre" est trop faible pour payer la nourriture et l\'énergie du foyer (souvent estimé autour de 800-1000€ pour un célibataire), la banque refusera le prêt.' },
    { q: 'Quel est l\'impact d\'une hausse générale des taux d\'intérêts sur votre capacité d\'emprunt ?',
      options: ['Elle augmente votre capacité d\'emprunt', 'Elle fait baisser mécaniquement votre capacité d\'emprunt (à revenus identiques, vous pourrez emprunter moins de capital)', 'Elle n\'a aucun impact', 'Elle oblige la banque à prêter sans intérêts'],
      correct: 1, rationale: 'Plus le taux est élevé, plus la part d\'intérêts dans la mensualité est forte. Pour ne pas dépasser le plafond de 35%, il faut donc baisser le montant du capital emprunté.' },
    { q: 'Comment la durée du crédit influence-t-elle la capacité d\'endettement ?',
      options: ['Plus le crédit est court, plus on peut emprunter une grosse somme', 'Plus le crédit est long (ex: 25 ans), plus on peut emprunter un capital important, car la mensualité est étalée dans le temps', 'La durée n\'a aucune influence', 'Un crédit long annule l\'apport personnel'],
      correct: 1, rationale: 'Étaler la dette permet de baisser la mensualité pour qu\'elle passe sous les 35%. Revers de la médaille : le coût total du crédit (les intérêts) explose.' },
    { q: 'En analyse de risque, qu\'est-ce que le "saut de charge" (ou saut de loyer) surveillé par les banques ?',
      options: ['La différence d\'imposition entre deux années', 'L\'écart entre le loyer actuel payé par le locataire et la future mensualité de son crédit immobilier', 'Le coût du déménagement', 'Les frais d\'agence immobilière'],
      correct: 1, rationale: 'Si un client paie 800€ de loyer sans difficulté d\'épargne, et que sa future mensualité est de 850€, le "saut" est faible (50€). La banque est rassurée sur sa capacité à assumer le crédit.' },
    { q: 'Pourquoi l\'apport personnel (l\'épargne injectée par l\'emprunteur) est-il crucial pour débloquer la capacité d\'endettement ?',
      options: ['Il sert à soudoyer le banquier', 'Il finance généralement les frais de notaire et de garantie, évitant à la banque de prêter plus que la valeur réelle du bien (ce qui serait un risque pour elle)', 'Il annule les intérêts du prêt', 'L\'apport personnel est illégal en France'],
      correct: 1, rationale: 'C\'est la règle des "110%". Sans apport, on demande à la banque de financer la maison (100%) + les frais (10%), ce qui bloque très souvent les dossiers actuels.' },
    { q: '(Challenge) Un célibataire gagne 3 000 € nets par mois. Il n\'a aucun crédit en cours et ne verse pas de pension alimentaire. Si la banque applique strictement le taux d\'endettement de 35 %, quelle est la mensualité maximale (assurance incluse) qu\'il peut rembourser ?',
      options: ['850 €', '1 050 €', '1 500 €', '3 000 €'],
      correct: 1, rationale: 'Calcul simple : 3 000 € x 35 % = 1 050 €. Il pourra donc chercher un financement où la mensualité globale ne dépasse pas cette somme.' },
    { q: '(Challenge) Un couple gagne au total 4 000 € nets par mois. Ils remboursent déjà un crédit automobile de 400 € / mois. Quelle est leur capacité de mensualité restante pour leur projet immobilier (au plafond de 35%) ?',
      options: ['1 400 €', '1 000 €', '400 €', '1 800 €'],
      correct: 1, rationale: 'Capacité d\'endettement globale du foyer : 4 000 € x 35 % = 1 400 € d\'enveloppe totale. On soustrait le crédit auto (1 400 - 400) : il reste 1 000 € de mensualité disponible pour la maison.' },
  ],
};
