/* Questions de la semaine 7. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w7-d0': [
    { q: 'Dans une opération de crédit (emprunt), que représente l\'intérêt ?',
      options: ['Une taxe gouvernementale', 'Le remboursement du capital', 'Le "prix de l\'argent" : la somme que l\'emprunteur paie au prêteur', 'L\'assurance du prêt'],
      correct: 2, rationale: 'Vous louez l\'argent de la banque, et l\'intérêt est ce loyer.' },
    { q: 'Dans un produit d\'épargne (placement), que représente l\'intérêt ?',
      options: ['La "rémunération" versée par la banque à l\'épargnant en échange de son argent', 'Les frais de dossier', 'Un don de l\'État', 'Le solde du compte'],
      correct: 0, rationale: 'C\'est vous qui prêtez de l\'argent à la banque, elle vous paie donc un intérêt.' },
    { q: 'Qu\'est-ce qu\'un taux d\'intérêt "fixe" ?',
      options: ['Il change tous les jours', 'Il est fixé par l\'inflation', 'Il est fixé au hasard', 'Il est défini à la signature et reste strictement le même pendant toute l\'opération'],
      correct: 3, rationale: 'Il offre une sécurité absolue.' },
    { q: 'Qu\'est-ce qu\'un taux d\'intérêt "variable" (ou révisable) ?',
      options: ['Il dépend de l\'âge de l\'épargnant', 'Il varie selon la banque visitée', 'Il évolue à la hausse comme à la baisse, souvent indexé sur un indice de référence', 'Il varie selon les saisons'],
      correct: 2, rationale: 'Il fait peser un risque financier sur l\'emprunteur.' },
    { q: 'Qu\'est-ce que "l\'intérêt simple" ?',
      options: ['Les intérêts sont calculés chaque année UNIQUEMENT sur le capital initial, sans se rajouter au capital pour le futur', 'Un intérêt calculé uniquement les années paires', 'Un intérêt sans impôts', 'Un intérêt très compliqué à comprendre'],
      correct: 0, rationale: '100€ à 5% d\'intérêts simples donnent 5€ par an à l\'infini.' },
    { q: 'Comment appelle-t-on le taux d\'intérêt fixé par la Banque Centrale Européenne (BCE) ?',
      options: ['Le taux d\'usure', 'Le taux directeur', 'Le taux marginal', 'Le taux de change'],
      correct: 1, rationale: 'C\'est la boussole de l\'économie qui influence crédits et livrets.' },
    { q: 'Dans un crédit immobilier classique, comment sont calculés les intérêts mensuels ?',
      options: ['Sur la totalité du montant emprunté au départ', 'Uniquement sur la valeur de la maison', 'Sur le salaire de l\'emprunteur', 'Sur le "Capital restant dû" (la base de calcul diminue avec les remboursements)'],
      correct: 3, rationale: 'C\'est pourquoi en début de prêt, la mensualité paie surtout des intérêts.' },
    { q: 'Quel lien logique justifie qu\'un taux d\'intérêt soit plus élevé qu\'un autre ?',
      options: ['La sympathie du banquier', 'Le code postal', 'La prime de risque : plus le risque de défaut est élevé, plus le taux exigé sera fort', 'La quantité de papier imprimé'],
      correct: 2, rationale: 'Prêter à une entreprise fragile nécessitera un taux fort pour compenser le risque.' },
    { q: '(Challenge) Comment sont calculés les intérêts sur le Livret A s\'il y a des dépôts et retraits ?',
      options: ['Selon la "règle des quinzaines" (tout retrait annule la quinzaine en cours)', 'Au jour le jour', 'Selon le solde du 1er janvier uniquement', 'Par tirage au sort mensuel'],
      correct: 0, rationale: 'Il faut déposer le 14/30 du mois, et retirer le 2/16 pour optimiser.' },
    { q: '(Challenge) Que traduit la notion de "taux d\'intérêt réel" face à l\'inflation ?',
      options: ['Il s\'agit du taux brut', 'C\'est le taux payé en billets réels', 'C\'est l\'usure de la monnaie', 'C\'est le taux nominal moins l\'inflation anticipée'],
      correct: 3, rationale: 'L\'investisseur ne regarde que l\'intérêt réel pour jauger son enrichissement.' },
  ],
  'w7-d1': [
    { q: 'À quelle période de l\'année les contribuables français doivent-ils obligatoirement remplir et valider leur déclaration de revenus ?',
      options: ['En janvier (hiver)', 'Au printemps (généralement entre avril et début juin)', 'En août (été)', 'En décembre (fin d\'année)'],
      correct: 1, rationale: 'La campagne déclarative s\'ouvre mi-avril. Les dates limites varient selon le département de résidence du contribuable (fin mai ou début juin).' },
    { q: 'Si vous remplissez votre déclaration au printemps de l\'année 2024, sur quelle période portent les revenus que vous déclarez ?',
      options: ['Les revenus estimés de toute l\'année 2024', 'Les revenus perçus du 1er janvier au 31 décembre 2023 (Année N-1)', 'Les revenus des 10 dernières années', 'Les revenus de juillet 2023 à juin 2024'],
      correct: 1, rationale: 'On fait toujours le bilan de l\'année civile écoulée, car c\'est la seule qui est clôturée et dont on connaît l\'exactitude des montants.' },
    { q: 'À quel moment l\'administration fiscale met-elle à disposition le document officiel appelé "Avis d\'imposition" ?',
      options: ['Dès la validation sur internet au printemps', 'Pendant l\'été (généralement fin juillet / août)', 'Le 31 décembre', 'En janvier de l\'année suivante'],
      correct: 1, rationale: 'Après la campagne de déclaration du printemps, le fisc traite les millions de dossiers et édite les avis officiels pendant l\'été dans l\'espace Particulier.' },
    { q: 'Si suite à la déclaration du printemps, il s\'avère que vos prélèvements à la source n\'ont pas été suffisants et qu\'il vous reste un solde d\'impôt à payer. Quand ce paiement est-il réclamé ?',
      options: ['Immédiatement en mai', 'En septembre (en une fois si le montant est inférieur à 300 €, ou étalé sur 4 mois si supérieur)', 'Il est reporté à l\'année suivante', 'À la retraite'],
      correct: 1, rationale: 'La régularisation des "restes à charge" se fait toujours à la rentrée de septembre, après réception de l\'avis d\'imposition.' },
    { q: 'À quelle date le NOUVEAU taux de prélèvement à la source (calculé d\'après votre déclaration du printemps) entre-t-il officiellement en vigueur sur vos fiches de paie ?',
      options: ['Le 1er janvier', 'Le 1er juin', 'Le 1er septembre de l\'année de la déclaration', 'Le jour de votre anniversaire'],
      correct: 2, rationale: 'Le taux est actualisé chaque 1er septembre et restera valable pendant un an, jusqu\'au 31 août de l\'année suivante (sauf si vous signalez un changement de situation).' },
    { q: 'Que se passe-t-il généralement à la mi-janvier pour les foyers employant une femme de ménage ou faisant des dons réguliers ?',
      options: ['Ils doivent payer une taxe supplémentaire', 'Ils reçoivent l\'avance de 60 % de leurs crédits et réductions d\'impôts (calculée sur la base de la déclaration de l\'année précédente)', 'Leur taux à la source passe à 0%', 'Leurs avantages fiscaux sont annulés'],
      correct: 1, rationale: 'Ce versement de trésorerie en janvier permet aux familles de ne pas attendre l\'été pour bénéficier de leurs avantages fiscaux récurrents.' },
    { q: 'Concernant la fiscalité locale, à quelle période les propriétaires doivent-ils généralement payer la Taxe Foncière ?',
      options: ['En janvier', 'À Pâques', 'En automne (mi-octobre)', 'Le 31 décembre'],
      correct: 2, rationale: 'Les impôts locaux tombent traditionnellement à l\'automne (sauf si le contribuable a opté pour la mensualisation sur 10 mois, de janvier à octobre).' },
    { q: 'Bien que supprimée pour les résidences principales, la Taxe d\'Habitation existe toujours pour les résidences secondaires. Quand est-elle généralement à payer ?',
      options: ['En même temps que l\'impôt sur le revenu (septembre)', 'En fin d\'année (novembre / décembre)', 'Le jour de l\'achat de la maison', 'Le 14 juillet'],
      correct: 1, rationale: 'C\'est le dernier grand rendez-vous fiscal de l\'année pour les propriétaires de résidences secondaires.' },
    { q: '(Challenge) Vous vous mariez ou avez un enfant le 10 février. Au lieu d\'attendre la déclaration de l\'année suivante, de combien de temps disposez-vous pour déclarer ce changement au fisc afin que votre taux de prélèvement à la source soit ajusté immédiatement ?',
      options: ['Vous n\'avez pas le droit de le faire', '60 jours (via l\'outil "Gérer mon prélèvement à la source")', '6 mois', 'Vous devez envoyer un courrier recommandé avant le 31 décembre'],
      correct: 1, rationale: 'Tout changement de situation familiale (mariage, divorce, naissance, décès) doit être signalé dans les 60 jours. Le fisc recalculera immédiatement votre quotient familial et baissera votre taux à la source pour le mois suivant.' },
    { q: '(Challenge) Un contribuable s\'aperçoit en septembre qu\'il s\'est trompé en remplissant sa déclaration de revenus au printemps (il a oublié de déclarer un crédit d\'impôt). Le service de déclaration est fermé. Est-ce perdu ?',
      options: ['Oui, la déclaration validée au printemps est définitive et non modifiable', 'Non, il peut utiliser le service de "correction en ligne" qui ouvre de début août à mi-décembre pour rectifier sa déclaration', 'Oui, il doit aller au tribunal pour faire modifier le document', 'Non, mais il paiera une amende forfaitaire de 200 €'],
      correct: 1, rationale: 'Le droit à l\'erreur permet de corriger soi-même sa déclaration sur Internet. L\'administration éditera ensuite un nouvel avis d\'imposition corrigé (et procédera au remboursement s\'il y a lieu).' },
  ],
  'w7-d2': [
    { q: 'Que signifie le sigle CNAV ?',
      options: ['Caisse Nationale d\'Assurances Vacances', 'Centre National des Avocats Vétérans', 'Caisse Nationale d\'Assurance Vieillesse', 'Caisse Nationale de l\'Amortissement Variable'],
      correct: 2, rationale: 'C\'est l\'organisme gérant le régime de retraite de base (la "Sécu") pour la très grande majorité des travailleurs français.' },
    { q: 'Quelle catégorie de travailleurs est principalement couverte par le régime général de la CNAV ?',
      options: ['Les fonctionnaires de l\'État (enseignants, policiers)', 'Les salariés du secteur privé, du commerce et de l\'industrie', 'Les professions libérales (médecins, avocats)', 'Les exploitants agricoles'],
      correct: 1, rationale: 'Les autres catégories ont leurs propres régimes de base (ex: la MSA pour les agriculteurs, le SRE pour les fonctionnaires d\'État).' },
    { q: 'Dans le calcul de la pension de la CNAV, quel est le pourcentage appliqué pour obtenir le "taux plein" ?',
      options: ['100 % du dernier salaire', '75 % (comme pour les fonctionnaires)', '50 % du Salaire Annuel Moyen (SAM)', '25 % du salaire de la première année'],
      correct: 2, rationale: 'Le régime de base du privé plafonne son taux à 50%. Ce taux sera minoré (décote) s\'il manque des trimestres. C\'est pour cela qu\'il y a la retraite complémentaire (Agirc-Arrco) pour compléter le reste.' },
    { q: 'Comment la CNAV calcule-t-elle le Salaire Annuel Moyen (SAM) servant de référence pour la pension ?',
      options: ['Elle prend le dernier salaire du mois de décembre', 'Elle fait la moyenne des 10 meilleures années de salaire', 'Elle fait la moyenne des 25 meilleures années de salaire (revalorisées de l\'inflation)', 'Elle fait la moyenne de toutes les années travaillées depuis 18 ans'],
      correct: 2, rationale: 'Contrairement aux fonctionnaires (6 derniers mois), le privé lisse les revenus sur une très longue période de la carrière.' },
    { q: 'Le salaire pris en compte par la CNAV pour faire cette moyenne (SAM) est-il illimité si vous gagnez très bien votre vie ?',
      options: ['Oui, tout le salaire est pris en compte', 'Non, chaque année, le salaire retenu est plafonné à la limite du Plafond Annuel de la Sécurité Sociale (PASS) (soit environ 46 368 € en 2024)', 'Non, il est limité strictement au SMIC', 'Oui, mais seulement pour les cadres dirigeants'],
      correct: 1, rationale: 'Si vous gagnez 100 000 €/an, la CNAV ne retiendra qu\'environ 46 000 € pour sa moyenne. C\'est pourquoi les cadres subissent une forte baisse de revenus à la retraite (la part au-dessus du plafond n\'est couverte que par l\'Agirc-Arrco).' },
    { q: 'Combien de trimestres un assuré de la CNAV peut-il valider au MAXIMUM sur une seule année civile ?',
      options: ['1', '4', '6', '12 (un par mois)'],
      correct: 1, rationale: 'Qu\'il gagne le SMIC ou un million d\'euros, personne ne peut valider plus de 4 trimestres de retraite pour une même année.' },
    { q: 'Sur quel grand principe financier repose la CNAV ?',
      options: ['La capitalisation individuelle (l\'argent est placé sur un compte personnel)', 'La répartition (les cotisations des actifs d\'aujourd\'hui paient les retraites de ceux qui sont déjà à la retraite)', 'La spéculation immobilière', 'Le financement exclusif par l\'impôt sur la fortune'],
      correct: 1, rationale: 'C\'est le principe de solidarité intergénérationnelle. Les actifs paient pour les inactifs. D\'où le problème démographique (papy-boom) actuel.' },
    { q: 'Que se passe-t-il sur la pension CNAV d\'un assuré s\'il décide de prendre sa retraite à 64 ans (l\'âge légal) mais qu\'il lui manque 8 trimestres par rapport à ce que la loi exige pour sa génération ?',
      options: ['La CNAV lui offre les trimestres', 'Sa pension subit une "décote" (minoration) définitive : le taux de 50% est réduit par un coefficient lié au nombre de trimestres manquants', 'L\'assuré doit rembourser les trimestres manquants en espèces', 'Il est interdit de partir s\'il manque un seul trimestre'],
      correct: 1, rationale: 'La décote pénalise à la fois le taux (qui tombe sous les 50%) et la proportionnalité, faisant chuter le montant de la pension à vie.' },
    { q: '(Challenge) Aujourd\'hui, quelle est la règle (hors chômage/maladie) pour valider UN trimestre cotisé à la CNAV ?',
      options: ['Avoir travaillé exactement 3 mois civils consécutifs', 'Avoir perçu dans l\'année un revenu brut soumis à cotisations au moins égal à 150 fois le SMIC horaire', 'Avoir été en CDI pendant 90 jours', 'Il faut payer 1000 € à la Sécurité Sociale'],
      correct: 1, rationale: 'On ne compte pas en "temps de travail" mais en "salaire cotisé". Avec un job étudiant intense payé l\'équivalent de 600 fois le SMIC horaire sur deux mois d\'été, on valide ses 4 trimestres pour l\'année !' },
    { q: '(Challenge) Un assuré atteint l\'âge légal. Il a déjà validé tous ses trimestres requis (il a le taux plein). Mais il adore son travail et décide de continuer 2 ans de plus. Comment la CNAV va-t-elle valoriser cet effort ?',
      options: ['En lui versant le Minimum Contributif', 'En ne prélevant plus aucune cotisation', 'En lui accordant une "surcote", c\'est-à-dire une augmentation définitive de sa pension (généralement +1,25 % par trimestre supplémentaire travaillé au-delà du taux plein et de l\'âge légal)', 'La CNAV ne valorise rien, les cotisations sont perdues'],
      correct: 2, rationale: 'La surcote récompense ceux qui, bien qu\'ayant le droit de partir à taux plein, décident de prolonger leur activité professionnelle.' },
  ],
  'w7-d3': [
    { q: 'Que sont les "droits de succession" ?',
      options: ['L\'argent payé au notaire pour son travail', 'Un impôt prélevé par l\'État sur la part du patrimoine transmise à chaque héritier lors d\'un décès', 'Les dettes laissées par le défunt', 'Une taxe foncière spéciale'],
      correct: 1, rationale: 'L\'État taxe l\'enrichissement de l\'héritier. Cet impôt se calcule après l\'application d\'un abattement.' },
    { q: 'Quel est le montant de l\'abattement (la somme sur laquelle on ne paie aucun impôt) accordé par l\'État à un ENFANT lors du décès de l\'un de ses parents ?',
      options: ['10 000 €', '31 865 €', '100 000 €', '1 000 000 €'],
      correct: 2, rationale: 'Chaque enfant a droit à 100 000 € d\'abattement par parent. Si un enfant hérite de 150 000 € de son père, il ne paiera des impôts que sur les 50 000 € restants.' },
    { q: 'Quel est le montant de l\'abattement accordé au CONJOINT SURVIVANT (marié, ou pacsé avec testament) sur la succession ?',
      options: ['80 000 €', '1594 €', 'Il n\'y a pas d\'abattement, il bénéficie d\'une exonération totale (0 € d\'impôt), quel que soit le montant de l\'héritage', '100 000 € comme pour les enfants'],
      correct: 2, rationale: 'Depuis 2007, le conjoint survivant (marié ou pacsé) est totalement protégé de la fiscalité sur les successions. Il ne paie jamais de droits.' },
    { q: 'Quel est l\'abattement légal entre frères et sœurs (hors conditions de handicap ou cohabitation très stricte) ?',
      options: ['100 000 €', '15 932 €', '50 000 €', '1 594 €'],
      correct: 1, rationale: 'La fiscalité se durcit très vite dès qu\'on s\'éloigne de la ligne directe (parents/enfants). Au-delà de ces ~16 000 €, le frère ou la sœur sera lourdement taxé (à 35% puis 45%).' },
    { q: 'Comment est calculé l\'impôt sur la somme qui dépasse l\'abattement (la part taxable) pour un enfant ?',
      options: ['C\'est un taux fixe de 20% pour tout le monde', 'C\'est un taux progressif par tranches (allant de 5% à 45%), de la même manière que l\'impôt sur le revenu', 'La banque décide du taux', 'C\'est un taux unique de 60%'],
      correct: 1, rationale: 'Les premiers milliers d\'euros taxables le sont à 5%, puis 10%, puis 20% (la tranche la plus courante), etc., jusqu\'à 45% pour les immenses patrimoines.' },
    { q: 'Quel est le taux d\'imposition (après un micro-abattement de 1594 €) pour une personne n\'ayant AUCUN lien de parenté avec le défunt (ex: un concubin, un ami, un neveu par alliance) ?',
      options: ['20 %', '30 %', '60 %', '0 %'],
      correct: 2, rationale: 'C\'est le taux "punitif" pour les tiers. Si vous léguez un bien de 100 000 € à votre ami, l\'État prendra environ 60 000 € d\'impôts.' },
    { q: 'L\'abattement de 100 000 € par enfant s\'applique lors d\'une succession, mais aussi lors d\'une "donation de son vivant". Tous les combien d\'années cet abattement se renouvelle-t-il (se remet à zéro) ?',
      options: ['Tous les 5 ans', 'Tous les 15 ans', 'Tous les 30 ans', 'Il ne se renouvelle jamais, c\'est une fois dans sa vie'],
      correct: 1, rationale: 'C\'est la base de l\'optimisation fiscale en gestion de patrimoine. Un parent peut donner 100 000 € nets d\'impôts à son enfant aujourd\'hui, et recommencer 15 ans plus tard.' },
    { q: 'Pourquoi l\'assurance-vie est-elle souvent qualifiée de "paradis fiscal de la succession" ?',
      options: ['Car elle est gérée en Suisse', 'Car les sommes placées avant 70 ans bénéficient d\'un abattement de 152 500 € par bénéficiaire (impôt à 0%), totalement HORS succession (en plus des 100 000 € légaux)', 'Car l\'assureur paie les impôts à la place du défunt', 'Car elle annule les dettes'],
      correct: 1, rationale: 'C\'est l\'outil numéro 1 pour transmettre sans impôt. On peut désigner qui on veut (enfant, concubin, ami) et lui transmettre jusqu\'à 152 500 € sans qu\'il ne paie le moindre droit de succession.' },
    { q: '(Challenge) De combien de temps disposent les héritiers pour payer les droits de succession à l\'État après le décès (sauf paiement différé/fractionné accordé par les impôts) ?',
      options: ['1 mois', '6 mois', '2 ans', '10 ans'],
      correct: 1, rationale: 'La déclaration de succession et le paiement des droits doivent intervenir dans les 6 mois suivant le décès. Si le patrimoine est bloqué dans l\'immobilier, les héritiers peuvent se retrouver en difficulté de trésorerie (d\'où l\'importance de prévoir de la liquidité ou un paiement fractionné).' },
    { q: '(Challenge) Un parent donne la "Nue-Propriété" d\'un appartement de 200 000 € à son fils, et en conserve l\'Usufruit. Le parent a 65 ans. Selon le barème de l\'article 669 du Code Général des Impôts, sur quelle base fiscale le fils sera-t-il taxé ?',
      options: ['Sur 200 000 €', 'Sur la valeur de la nue-propriété déterminée par l\'âge de l\'usufruitier (à 65 ans, la nue-propriété vaut 60 %, l\'assiette taxable sera donc de 120 000 €)', 'Sur zéro euro', 'Sur le montant du loyer annuel'],
      correct: 1, rationale: 'Plus l\'usufruitier donne jeune, plus la nue-propriété est fiscalement "dévaluée", ce qui permet de transmettre un gros bien immobilier en payant très peu (ou pas) d\'impôts de donation.' },
  ],
  'w7-d4': [
    { q: 'Qu\'est-ce qu\'une Garantie Accidents de la Vie (GAV) ?',
      options: ['Une assurance automobile pour les passagers', 'Un contrat de prévoyance qui indemnise l\'assuré et sa famille des conséquences corporelles et financières d\'un accident grave survenu dans le cadre de la vie PRIVÉE', 'Une assurance décès obligatoire pour un crédit', 'La garantie qui paie les obsèques'],
      correct: 1, rationale: 'C\'est une couverture essentielle pour tous les accidents du quotidien qui laissent des séquelles (handicap, perte de revenus).' },
    { q: 'Lequel de ces événements est typiquement COUVERT par un contrat GAV standard ?',
      options: ['Un accident de trajet domicile-travail (au volant de sa voiture)', 'Un licenciement économique', 'Un accident de bricolage (ex: doigt coupé par une scie), une brûlure grave au barbecue, ou une morsure de chien', 'Une maladie professionnelle (ex: burn-out)'],
      correct: 2, rationale: 'La GAV couvre les accidents domestiques, médicaux, les sports de loisir, et les catastrophes naturelles.' },
    { q: 'Pourquoi les accidents de la circulation (conducteur) sont-ils EXCLUS (non couverts) par la quasi-totalité des contrats GAV ?',
      options: ['Parce qu\'ils sont trop mortels', 'Parce qu\'ils sont déjà couverts par la "Garantie Conducteur" du contrat d\'assurance Automobile', 'Parce que l\'État les prend en charge', 'Parce que la GAV ne couvre pas la route'],
      correct: 1, rationale: 'L\'assurance ne paie pas deux fois pour le même risque. La GAV intervient là où l\'assurance auto n\'agit pas (chez vous, en forêt, au ski).' },
    { q: 'L\'un des grands avantages de la GAV est-il de fonctionner "sans tiers responsable" ?',
      options: ['Non, il faut obligatoirement qu\'une autre personne soit en tort (ex: un cycliste qui vous renverse)', 'Oui, la GAV vous indemnise même si vous vous blessez tout seul (ex: vous tombez du toit de votre maison) ou si l\'auteur est inconnu', 'Non, il faut porter plainte pour être indemnisé', 'Seulement si la police est intervenue'],
      correct: 1, rationale: 'C\'est la force de ce contrat. Si vous tombez de votre propre escabeau, il n\'y a personne contre qui se retourner. La GAV pallie ce manque.' },
    { q: 'Qu\'est-ce que le seuil de l\'AIPP (Atteinte à l\'Intégrité Physique et Psychique), appelé aussi "franchise d\'invalidité", dans un contrat GAV ?',
      options: ['L\'âge limite pour souscrire', 'Le délai d\'attente avant d\'être remboursé', 'Le taux de handicap (séquelles définitives) à partir duquel l\'assurance commence à verser une indemnisation (généralement fixé à 5 %, 10 % ou 30 %)', 'Le montant maximal remboursé'],
      correct: 2, rationale: 'La GAV n\'est pas là pour un petit bobo sans séquelle. Elle intervient si l\'accident laisse des traces à vie. Plus le seuil est bas (ex: 5%), plus le contrat est protecteur (et cher).' },
    { q: 'Quelle est la grande différence entre la "Mutuelle Santé" et la "GAV" ?',
      options: ['Il n\'y a pas de différence', 'La Mutuelle rembourse les frais médicaux (médecin, médicaments). La GAV indemnise les conséquences de l\'accident (perte de salaire, aménagement de la maison, préjudice moral et esthétique)', 'La GAV rembourse uniquement les médicaments non pris en charge', 'La mutuelle est payée par l\'employeur, la GAV par l\'État'],
      correct: 1, rationale: 'Si vous devenez paraplégique, la mutuelle paiera l\'hôpital. Mais c\'est la GAV qui paiera l\'ascenseur pour votre maison et compensera votre impossibilité de reprendre votre travail.' },
    { q: 'Les accidents survenus sur le lieu de TRAVAIL sont-ils pris en charge par la GAV ?',
      options: ['Oui, toujours', 'Non, ils relèvent de la sphère professionnelle et sont pris en charge par la Sécurité Sociale (Accident du Travail) et la prévoyance de l\'entreprise', 'Uniquement pour les artisans', 'Oui, si l\'accident a lieu pendant la pause déjeuner'],
      correct: 1, rationale: 'La GAV est strictement limitée aux accidents de la vie PRIVÉE.' },
    { q: 'La souscription à une GAV est-elle obligatoire ?',
      options: ['Oui, si on a des enfants', 'Oui, depuis 2015', 'Non, c\'est un contrat de prévoyance purement facultatif', 'Uniquement pour les propriétaires'],
      correct: 2, rationale: 'Contrairement à l\'assurance auto ou habitation, personne ne vous obligera à la prendre. C\'est une démarche personnelle de protection du foyer.' },
    { q: '(Challenge) En matière d\'indemnisation de la GAV, que signifie le principe "Indemnitaire" par opposition au principe "Forfaitaire" ?',
      options: ['"Indemnitaire" signifie que l\'indemnité est fixe et connue d\'avance', '"Indemnitaire" (le cas de la vraie GAV) signifie que l\'indemnisation est calculée sur mesure par un expert, en fonction des préjudices réels subis par la victime (financiers, esthétiques), dans la limite d\'un plafond (souvent 1 million d\'euros)', 'L\'indemnitaire annule les impôts', 'Le forfaitaire demande d\'avancer les frais'],
      correct: 1, rationale: 'Un chirurgien et un employé de bureau ne toucheront pas la même somme s\'ils perdent un doigt (le préjudice professionnel du chirurgien étant immense). L\'indemnisation s\'adapte au préjudice réel.' },
    { q: '(Challenge) Une infection nosocomiale (contractée à l\'hôpital lors d\'une opération) ou une erreur médicale entraînant un handicap lourd sont-elles couvertes par la GAV ?',
      options: ['Non, c\'est le problème exclusif de l\'hôpital', 'Oui, les bons contrats GAV labellisés incluent explicitement les "accidents médicaux" dans leurs garanties', 'Uniquement si l\'hôpital est privé', 'Non, car ce n\'est pas un accident de la route'],
      correct: 1, rationale: 'Se retourner contre un hôpital peut prendre 10 ans de procédure. La GAV avance les fonds et indemnise l\'assuré, puis l\'assureur se retourne lui-même contre l\'hôpital.' },
  ],
  'w7-d5': [
    { q: 'Quelle est la TOUTE PREMIÈRE étape indispensable AVANT même de commencer à visiter des biens immobiliers ?',
      options: ['Acheter des meubles', 'Aller voir sa banque ou un courtier pour calculer précisément sa capacité d\'emprunt (son budget max)', 'Signer chez le notaire', 'Ouvrir un compteur EDF'],
      correct: 1, rationale: 'C\'est l\'erreur de beaucoup de débutants : visiter des biens à 300 000 € alors qu\'ils ne peuvent emprunter que 220 000 €. Connaître son budget cible la recherche.' },
    { q: 'Le bien vous plaît, vous rédigez une "Offre d\'achat". De quoi s\'agit-il juridiquement ?',
      options: ['D\'un contrat qui oblige le propriétaire à vous vendre le bien', 'D\'une proposition écrite d\'acheter le bien à un prix défini. Si le vendeur l\'accepte et la contresigne, la vente est en théorie formée', 'D\'un simple brouillon sans valeur légale', 'D\'une reconnaissance de dettes'],
      correct: 1, rationale: 'L\'offre d\'achat engage l\'acheteur. Si le vendeur signe l\'offre "au prix" ou accepte votre offre négociée, il y a "accord sur la chose et sur le prix". L\'étape suivante est le compromis.' },
    { q: 'Qu\'est-ce que "l\'avant-contrat" (souvent appelé compromis de vente ou promesse de vente) ?',
      options: ['Un contrat signé uniquement par l\'agent immobilier', 'Un document officiel signé chez le notaire (ou en agence) fixant toutes les conditions de la vente (prix, délais, conditions suspensives), en attendant l\'acte définitif', 'Le contrat de prêt de la banque', 'Le devis pour les travaux'],
      correct: 1, rationale: 'Le compromis scelle l\'engagement des deux parties. C\'est à ce moment-là que l\'on verse généralement le "dépôt de garantie" (l\'acompte de 5 à 10%).' },
    { q: 'Après avoir signé le compromis de vente et reçu tous les documents officiels, de quel délai de "rétractation" légal bénéficie l\'acheteur (non professionnel) ?',
      options: ['2 jours ouvrés', '10 jours incompressibles (pendant lesquels il peut annuler sans motif et récupérer son acompte)', '30 jours', 'Il n\'y a aucun droit de rétractation dans l\'immobilier'],
      correct: 1, rationale: 'Ce délai, instauré par la loi SRU/Macron, protège l\'acheteur des achats d\'impulsion. Il peut se retirer par courrier recommandé, sans se justifier, et récupérer son argent.' },
    { q: 'Qu\'est-ce que la "Condition suspensive d\'obtention de prêt" obligatoirement inscrite dans le compromis ?',
      options: ['Une clause qui suspend les mensualités du prêt', 'Une clause qui protège l\'acheteur : s\'il n\'obtient pas son financement bancaire dans le délai imparti, la vente est annulée et il récupère son dépôt de garantie', 'Le droit de payer le bien plus tard', 'Une taxe bancaire'],
      correct: 1, rationale: 'Si la banque refuse le crédit (et que l\'acheteur présente l\'attestation de refus), il n\'est pas forcé d\'acheter un bien qu\'il ne peut pas payer, et il n\'est pas pénalisé.' },
    { q: 'Combien de temps (minimum légal) est généralement laissé à l\'acheteur dans le compromis pour obtenir son accord de prêt (la fameuse condition suspensive) ?',
      options: ['15 jours', 'Souvent fixé entre 45 et 60 jours (la loi impose 1 mois minimum, mais les banques sont lentes)', '6 mois', '1 semaine'],
      correct: 1, rationale: 'Ce délai permet à l\'acheteur de démarcher plusieurs banques, de négocier son taux, de faire valider l\'assurance et d\'obtenir l\'édition de l\'offre de prêt.' },
    { q: 'Une fois l\'offre de prêt éditée par la banque et reçue par la poste, l\'acheteur est soumis à la loi Scrivener. Que lui impose-t-elle ?',
      options: ['De signer et renvoyer l\'offre le jour même', 'D\'attendre un délai de réflexion obligatoire de 10 jours incompressibles avant d\'accepter et de renvoyer l\'offre (à partir du 11ème jour)', 'De faire un chèque à la banque immédiatement', 'De refuser la première offre'],
      correct: 1, rationale: 'La loi interdit au banquier d\'accepter l\'offre signée avant l\'expiration de ces 10 jours pleins, pour éviter les signatures sous la pression.' },
    { q: 'Quelle est l\'ultime étape qui transfère officiellement la propriété du bien et déclenche la remise des clés ?',
      options: ['L\'accord de la banque', 'La signature de l\'Offre d\'Achat', 'La signature de l\'Acte Authentique de Vente chez le notaire', 'L\'état des lieux'],
      correct: 2, rationale: 'C\'est la ligne d\'arrivée. Le notaire lit l\'acte, les fonds sont transférés au vendeur, et vous recevez les clés et l\'attestation de propriété.' },
    { q: '(Challenge) Lors de la signature de l\'Acte Authentique, vous venez sans chéquier. Comment l\'argent de la banque et votre apport personnel sont-ils transférés au vendeur ?',
      options: ['L\'acheteur fait un virement direct sur le compte du vendeur', 'L\'acheteur amène des espèces', 'C\'est "l\'appel de fonds" : le notaire a demandé à la banque et à l\'acheteur de virer l\'argent sur le compte séquestre du notaire quelques jours avant. Le notaire transfèrera ensuite lui-même les fonds au vendeur', 'La banque donne l\'argent en liquide au notaire'],
      correct: 2, rationale: 'Tout passe par la comptabilité (ultra-sécurisée) du notaire. Il collecte l\'argent du prêt et l\'apport, puis se charge de désintéresser le vendeur, l\'État (taxes) et l\'agence immobilière.' },
    { q: '(Challenge) Entre le compromis et l\'acte de vente (souvent 3 mois d\'attente), le notaire vérifie le "Droit de préemption". De quoi s\'agit-il ?',
      options: ['Le droit du locataire d\'annuler la vente', 'La priorité accordée légalement à la Commune (la Mairie) pour acheter le bien à votre place, si elle a un projet d\'intérêt général (ex: construire une route ou une école à cet endroit)', 'Le droit de la banque de refuser le taux', 'Le droit des voisins d\'acheter le jardin'],
      correct: 1, rationale: 'Le notaire envoie une "DIA" (Déclaration d\'Intention d\'Aliéner) à la mairie. La mairie a 2 mois pour répondre. Si elle préempte, l\'acheteur est évincé de la vente.' },
  ],
};
