/* Questions de la semaine 23. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w23-d0': [
    { q: 'En économie, quelle est la fonction première de la Bourse (le marché financier) ?',
      options: ['Permettre à l\'État de prélever des impôts', 'Financer l\'économie réelle : permettre aux entreprises, aux États et aux collectivités de trouver des capitaux pour se développer, en échange de l\'émission de titres (actions, obligations)', 'Fixer le prix de l\'immobilier physique', 'Vendre des devises étrangères aux touristes'],
      correct: 1, rationale: 'La Bourse est le point de rencontre entre ceux qui ont besoin d\'argent pour des projets (les entreprises) et ceux qui ont de l\'épargne à placer (les investisseurs).' },
    { q: 'Qu\'est-ce que "l\'Introduction en Bourse" (IPO - Initial Public Offering) ?',
      options: ['La première fois qu\'un particulier ouvre un PEA', 'L\'opération par laquelle une entreprise privée vend pour la première fois une partie de son capital au public sur le marché financier pour lever des fonds massifs', 'La faillite d\'une entreprise', 'Le paiement du premier dividende'],
      correct: 1, rationale: 'L\'entreprise passe du statut "non-cotée" (fermée) au statut "cotée" (ouverte à tous les investisseurs).' },
    { q: 'Pour acheter ou vendre une action en Bourse, vous ne pouvez pas le faire directement. Par qui devez-vous OBLIGATOIREMENT passer ?',
      options: ['Un courtier (Broker) ou une banque, qui joue le rôle d\'intermédiaire agréé pour transmettre vos ordres sur le marché', 'Le directeur de l\'entreprise', 'Un notaire', 'Un commissaire-priseur'],
      correct: 0, rationale: 'Le courtier (en ligne ou physique) exécute votre ordre d\'achat/vente sur la place boursière en échange de "frais de courtage".' },
    { q: 'Qu\'est-ce que le "Carnet d\'ordres" d\'une action en Bourse ?',
      options: ['Un livre d\'or pour les actionnaires', 'Le document récapitulant les dettes de l\'entreprise', 'La liste confidentielle des dirigeants', 'Le registre électronique transparent qui regroupe en temps réel tous les ordres d\'achat (les prix proposés par les acheteurs) et tous les ordres de vente (les prix exigés par les vendeurs)'],
      correct: 3, rationale: 'Lorsque le prix proposé par un acheteur rencontre le prix exigé par un vendeur dans ce carnet, la transaction est instantanément exécutée.' },
    { q: 'En France, quel organisme public joue le rôle de "gendarme de la bourse" pour protéger les épargnants et surveiller les marchés ?',
      options: ['Le FMI (Fonds Monétaire International)', 'L\'URSSAF', 'L\'AMF (Autorité des Marchés Financiers)', 'La Cour de Cassation'],
      correct: 2, rationale: 'L\'AMF traque les délits d\'initiés, les fraudes, et s\'assure que les entreprises cotées communiquent des informations transparentes au grand public.' },
    { q: 'Que se passe-t-il mécaniquement sur le cours (le prix) d\'une action le matin précis où l\'entreprise "détache" (verse) son dividende annuel aux actionnaires ?',
      options: ['L\'entreprise fait faillite', 'Le prix de l\'action baisse d\'un montant strictement identique au dividende versé', 'Le prix de l\'action double automatiquement', 'Le prix de l\'action reste exactement le même'],
      correct: 1, rationale: 'C\'est une erreur classique des débutants. Si l\'action vaut 100€ et paie 5€ de dividende, une part de la richesse quitte la société pour aller dans votre poche. L\'action ne vaudra donc plus que 95€ à l\'ouverture.' },
    { q: 'Quel est l\'indice boursier majeur qui regroupe les 500 plus grandes entreprises américaines et sert de boussole à la finance mondiale ?',
      options: ['Le CAC 40', 'Le Nikkei 225', 'Le S&P 500 (Standard & Poor\'s 500)', 'Le DAX'],
      correct: 2, rationale: 'Cet indice est réputé pour sa croissance historique solide. C\'est l\'indice le plus répliqué au monde par les ETF (Trackers).' },
    { q: 'En Bourse, qu\'est-ce qu\'une OPA (Offre Publique d\'Achat) ?',
      options: ['L\'interdiction d\'acheter des actions', 'L\'opération par laquelle une entreprise (ou un prédateur financier) propose publiquement d\'acheter les actions d\'une autre entreprise, souvent à un prix supérieur au marché, pour en prendre le contrôle', 'Une augmentation du capital social', 'Le remboursement des dettes de l\'État'],
      correct: 1, rationale: 'Si la cible accepte ou si les actionnaires vendent massivement, l\'entreprise prédatrice absorbe sa cible.' },
    { q: '(Challenge) Qu\'est-ce que le "Délit d\'initié" en Bourse (lourdement condamné au pénal) ?',
      options: ['Le fait d\'utiliser une information privilégiée, secrète et non encore connue du grand public (ex: fusion imminente, faillite) pour acheter ou vendre des titres et réaliser un profit déloyal', 'Le fait de créer un faux compte bancaire', 'Le fait de perdre de l\'argent volontairement', 'Le fait de trader en dehors des heures d\'ouverture'],
      correct: 0, rationale: 'Les cadres dirigeants et leurs proches ont interdiction stricte de trader sur leur propre entreprise s\'ils ont connaissance d\'un futur communiqué qui fera varier les prix.' },
    { q: '(Challenge) Une technique boursière spéculative s\'appelle "La Vente à découvert" (Short Selling). En quoi consiste-t-elle ?',
      options: ['Payer ses actions à crédit sur 10 ans', 'Vendre une action que l\'on ne possède pas encore (en l\'empruntant) parce que l\'on parie que son prix va S\'EFFONDRER, afin de la racheter plus tard à un prix inférieur et empocher la différence', 'Vendre toutes ses actions à la fin du mois', 'Acheter des actions sans avoir d\'argent sur son compte'],
      correct: 1, rationale: 'Si l\'action baisse, le parieur s\'enrichit. Mais si l\'action monte (ex: l\'affaire GameStop), le parieur doit la racheter beaucoup plus cher, subissant des pertes théoriquement illimitées.' },
  ],
  'w23-d1': [
    { q: 'Qu\'est-ce qu\'une "plus-value mobilière" en fiscalité ?',
      options: ['La revente d\'une maison de campagne', 'Le dividende perçu en fin d\'année', 'Le gain réalisé (la différence positive) lors de la VENTE d\'actifs financiers (actions, obligations, ETF, OPCVM) sur un compte titres', 'Le salaire versé par la banque'],
      correct: 2, rationale: 'Si vous achetez une action 100 € et la revendez 150 €, vous réalisez une plus-value mobilière de 50 €, qui sera taxable.' },
    { q: 'Quel est le régime fiscal appliqué PAR DÉFAUT par l\'administration française sur ces plus-values mobilières (sur un CTO classique) ?',
      options: ['Un taux fixe de 60 %', 'Le Prélèvement Forfaitaire Unique (PFU / Flat Tax) au taux global de 30 %', 'L\'exonération totale d\'impôt', 'La taxation à 5 % par année de détention'],
      correct: 1, rationale: 'Sans démarche de votre part, la banque ou le fisc prélèvera ces 30 % (12,8 % d\'IR + 17,2 % de CSG) sur vos gains de vente.' },
    { q: 'Vous avez réalisé 1 000 € de plus-values, mais aussi vendu d\'autres actions à perte (moins-value de 400 €) dans la même année sur votre Compte-Titres. Que faites-vous fiscalement ?',
      options: ['Vous compensez (imputez) la perte sur le gain. L\'impôt ne sera calculé QUE sur le gain net final de 600 €', 'Vous payez 30 % sur 1 000 €, la perte est ignorée', 'L\'État vous rembourse les 400 €', 'Vous déduisez les 400 € de votre taxe foncière'],
      correct: 0, rationale: 'Les plus-values et moins-values mobilières de la même année s\'annulent entre elles.' },
    { q: 'Que se passe-t-il si vos pertes boursières de l\'année DÉPASSENT vos gains boursiers (le solde de l\'année est négatif) ?',
      options: ['La moins-value globale est reportable pendant les 10 années suivantes pour venir annuler de futures plus-values mobilières', 'Le compte est bloqué par la banque', 'Vous avez le droit d\'effacer vos revenus fonciers', 'La perte est définitivement perdue fiscalement'],
      correct: 0, rationale: 'C\'est un puissant bouclier fiscal. C\'est pourquoi il faut toujours déclarer ses pertes en bourse (Formulaire 2074).' },
    { q: 'Le contribuable peut renoncer au PFU (30 %) et cocher la case pour opter pour le "Barème progressif" de l\'Impôt sur le Revenu. Quel est le DANGER de cette option ?',
      options: ['L\'option "Barème progressif" est globale : elle s\'appliquera à l\'INTÉGRALITÉ des revenus du capital de l\'année (toutes plus-values, livrets et dividendes confondus), sans pouvoir choisir', 'La banque prend des frais de dossier', 'Elle rend les pertes boursières non reportables', 'Elle double les prélèvements sociaux'],
      correct: 0, rationale: 'Impossible de choisir le PFU pour ses dividendes et le barème pour ses plus-values. C\'est un "tout ou rien".' },
    { q: 'Si vous faites une plus-value sur une cryptomonnaie (Bitcoin), obéit-elle aux mêmes règles de report de pertes que la Bourse classique ?',
      options: ['Oui, c\'est identique en tous points', 'Seulement si la crypto a plus de 5 ans', 'Non. Les plus/moins values en cryptomonnaies forment une catégorie isolée. Une perte en crypto ne peut PAS effacer un gain sur des actions (CTO)', 'La crypto n\'est pas taxée en France'],
      correct: 2, rationale: 'Les pertes en actions n\'effacent que les gains en actions. Les pertes en cryptos n\'effacent que les gains en cryptos.' },
    { q: 'Quelle "enveloppe fiscale" permet de contourner totalement cette fiscalité en exonérant les plus-values mobilières d\'Impôt sur le Revenu après 5 ans ?',
      options: ['Le Compte-Titres Ordinaire (CTO)', 'Le Livret de Développement Durable (LDDS)', 'Le Plan d\'Épargne en Actions (PEA)', 'Le Compte Courant'],
      correct: 2, rationale: 'Au bout de 5 ans, l\'Impôt sur le Revenu (12,8%) disparaît. Ne restent que les prélèvements sociaux (17,2%) applicables au moment du retrait.' },
    { q: 'Une moins-value boursière (perte à la vente) peut-elle être utilisée pour effacer l\'impôt à payer sur un DIVIDENDE reçu la même année ?',
      options: ['Uniquement sur les actions européennes', 'Oui, les flux sont fongibles', 'Non. Une moins-value en capital ne peut s\'imputer QUE sur une plus-value en capital. Elle ne peut JAMAIS annuler l\'impôt sur un revenu distribué (dividende)', 'Oui, si on opte pour le barème progressif'],
      correct: 2, rationale: 'C\'est le piège classique. Vous pouvez avoir 1 000€ de dividendes et 5 000€ de pertes à la revente : vous paierez quand même des impôts sur les 1 000€ de dividendes !' },
    { q: '(Challenge) Un épargnant très riche quitte la France pour installer sa résidence fiscale à l\'étranger (Dubaï, Suisse). Il possède un Compte-Titres avec 1 million d\'euros de plus-values "latentes" (non vendues). À quelle taxe française (destinée à limiter l\'évasion fiscale) risque-t-il d\'être soumis lors de son départ ?',
      options: ['La taxe de séjour', 'L\'Exit Tax : le fisc va imposer virtuellement ses plus-values latentes (comme s\'il avait tout vendu le jour de son départ) pour garantir le paiement de l\'impôt français', 'La TVA douanière à 20 %', 'Le droit de douane sur la fortune'],
      correct: 1, rationale: 'Ce mécanisme évite que les grands actionnaires quittent le territoire juste pour revendre leurs actions sans impôts. La France prend une "garantie" sur ces gains virtuels.' },
    { q: '(Challenge) Si le contribuable opte pour le Barème Progressif, il peut parfois bénéficier d\'un "Abattement pour durée de détention" sur ses plus-values. Quelle est la condition REDOUTABLE pour y avoir droit aujourd\'hui ?',
      options: ['Il faut que l\'action ait été acquise AVANT le 1er janvier 2018 (avant la réforme Macron/PFU). Les actions achetées après 2018 n\'y ont plus droit', 'Il faut être retraité', 'Il faut l\'autorisation de l\'entreprise', 'L\'action doit valoir plus de 100 000 €'],
      correct: 0, rationale: 'Cet ancien avantage (abattant jusqu\'à 65% de la plus-value si l\'action était gardée 8 ans) a été gelé. Il survit uniquement pour les "vieux" titres.' },
  ],
  'w23-d2': [
    { q: 'Dans le système de retraite français, quel est le but du dispositif "Carrières Longues" ?',
      options: ['Obliger les fonctionnaires à travailler plus longtemps', 'Permettre à ceux qui ont commencé à travailler très jeune (et qui ont réuni tous leurs trimestres) de partir à la retraite AVANT l\'âge légal (ex: à 60 ou 62 ans au lieu de 64 ans)', 'Multiplier par deux la pension de la Sécurité Sociale', 'Racheter des années d\'études'],
      correct: 1, rationale: 'C\'est une mesure de justice sociale pour ne pas forcer ceux qui travaillent depuis l\'âge de 16 ou 18 ans à faire des carrières de 46 ou 47 ans.' },
    { q: 'Quelles sont les DEUX conditions CUMULATIVES pour avoir droit au départ anticipé pour Carrière Longue ?',
      options: ['Avoir commencé à travailler avant un certain âge (le palier) ET justifier d\'un nombre très précis de trimestres STRICTEMENT "cotisés" (le travail réel)', 'Être marié et avoir 3 enfants', 'Avoir été cadre pendant 10 ans et avoir 62 ans', 'Avoir le baccalauréat et payer une taxe'],
      correct: 0, rationale: 'Il ne suffit pas d\'avoir commencé tôt, il faut aussi avoir travaillé (presque) sans interruption toute sa vie.' },
    { q: 'Suite à la réforme des retraites de 2023, quels sont les 4 "paliers d\'âge" de début d\'activité qui ouvrent différents droits au départ anticipé ?',
      options: ['Avoir commencé avant 25, 30, 35 ou 40 ans', 'Avoir commencé avant 16 ans, avant 18 ans, avant 20 ans, ou avant 21 ans', 'Avoir commencé à 10, 12, 14 ou 15 ans', 'Le seul palier est 18 ans'],
      correct: 1, rationale: 'La réforme a instauré ce nouveau palier (avant 21 ans), qui permet souvent à ces assurés de partir à 63 ans (au lieu de 64).' },
    { q: 'Pour prouver que vous avez bien "commencé avant" un certain âge (ex: avant 20 ans), quelle exigence la caisse de retraite vérifie-t-elle ?',
      options: ['Avoir obtenu son diplôme avant cet âge', 'La présentation d\'un contrat d\'apprentissage', 'Avoir validé au moins 5 trimestres à la fin de l\'année civile de cet âge (ou 4 trimestres si né le dernier trimestre de l\'année)', 'La déclaration des parents'],
      correct: 2, rationale: 'C\'est la règle d\'or d\'appréciation du début d\'activité. Un petit job d\'été à 19 ans ne suffit pas s\'il ne génère qu\'un seul trimestre.' },
    { q: 'Le dispositif Carrière Longue exige un nombre de trimestres "Cotisés". Quelle est la différence par rapport aux trimestres "Validés" classiques ?',
      options: ['Les trimestres cotisés comptent double', 'Les trimestres "cotisés" reflètent les périodes de TRAVAIL RÉEL ayant donné lieu à versement de cotisations. Beaucoup de trimestres "assimilés" (ex: années entières de chômage ou maladie) sont donc EXCLUS du calcul', 'Il n\'y a aucune différence', 'Les trimestres cotisés sont ceux donnés pour les enfants'],
      correct: 1, rationale: 'Le dispositif récompense l\'effort de travail. Un chômeur de longue durée aura du mal à réunir ces trimestres cotisés.' },
    { q: 'Face à cette exigence stricte de "travail réel", la loi tolère tout de même un petit "panier" de trimestres assimilés qui peuvent être comptés comme "cotisés". Que contient cette tolérance ?',
      options: ['Rien, tolérance zéro', 'Maximum 4 trimestres de chômage, 4 de maladie, 4 pour service militaire, et tous les trimestres de maternité', '20 trimestres de chômage pour tout le monde', 'Le droit de racheter 10 ans d\'études'],
      correct: 1, rationale: 'Cette soupape évite qu\'un salarié ayant commencé à 16 ans perde son droit de partir tôt juste parce qu\'il a eu un accident de santé ou 6 mois de chômage dans sa vie.' },
    { q: 'Quel est l\'avantage (ou l\'inconvénient) financier d\'une retraite prise de façon anticipée via le dispositif Carrière Longue ?',
      options: ['La pension est diminuée (décote) de 10 %', 'Il n\'y a aucune pénalité. La pension est calculée à "Taux plein" (50 %), exactement comme si l\'assuré avait atteint l\'âge légal', 'La pension est doublée', 'L\'assuré doit payer la première année de sa poche'],
      correct: 1, rationale: 'C\'est un droit acquis. Vous partez à 60 ans avec la même retraite que si vous aviez attendu 64 ans, car vous avez déjà cotisé le nombre d\'années exigé par la loi.' },
    { q: 'Que se passe-t-il concernant la Retraite Complémentaire (Agirc-Arrco) si l\'on part en Carrière Longue (taux plein) au régime de base ?',
      options: ['L\'Agirc-Arrco supprime la complémentaire', 'L\'Agirc-Arrco s\'aligne : elle accorde elle aussi la retraite complémentaire sans minoration (sans décote) liée à l\'anticipation d\'âge', 'La complémentaire est divisée par deux', 'Il faut attendre 67 ans pour toucher la complémentaire'],
      correct: 1, rationale: 'Les deux régimes se coordonnent parfaitement pour protéger les carrières longues.' },
    { q: '(Challenge) Un assuré de 60 ans a 170 trimestres VALIDÉS au total. Pour sa génération, le taux plein nécessite 170 trimestres. Il a commencé à travailler à 18 ans. MAIS, sur ses 170 trimestres, 20 sont liés au chômage. Peut-il partir en Carrière Longue à 60 ans ?',
      options: ['Oui, car 170 = 170', 'Non. Bien qu\'il ait la "durée validée" pour le taux plein normal, il n\'a pas assez de trimestres "COTISÉS" (le chômage n\'étant toléré que dans la limite de 4). Il lui manquera 16 trimestres cotisés. Il devra attendre l\'âge légal', 'Oui, car le chômage compte double', 'Seulement si Pôle Emploi donne l\'accord'],
      correct: 1, rationale: 'C\'est le drame de nombreux assurés qui confondent relevé de carrière global (trimestres validés) et exigence stricte de la Carrière Longue (trimestres cotisés).' },
    { q: '(Challenge) Afin de booster les chances des jeunes mamans de bénéficier des Carrières Longues, la réforme de 2023 a ajouté un élément au "panier de tolérance" des trimestres cotisés. Lequel ?',
      options: ['L\'achat gratuit de trimestres', 'Les trimestres liés au congé sans solde', 'La prise en compte, jusqu\'à 4 trimestres, des "Majorations de trimestres liées à l\'éducation des enfants" (Majoration Éducation/Adoption), autrefois totalement exclues du décompte des trimestres cotisés', 'Le doublement du salaire'],
      correct: 2, rationale: 'C\'était une grande injustice : les femmes perdaient souvent le droit à la carrière longue car leurs trimestres liés à l\'éducation n\'étaient pas reconnus comme du "travail" (cotisé) par le système.' },
  ],
  'w23-d3': [
    { q: 'En assurance-vie, qu\'est-ce que le principe d\'une "Clause bénéficiaire démembrée" ?',
      options: ['Déchirer le contrat d\'assurance en deux parties', 'Séparer la propriété du capital décès : au décès de l\'assuré, le conjoint (souvent) recevra "l\'Usufruit" du capital, et les enfants recevront la "Nue-propriété" de ce même capital', 'Donner l\'argent à la banque et les intérêts à l\'État', 'Une clause qui exclut les enfants de la succession'],
      correct: 1, rationale: 'C\'est le summum de l\'optimisation patrimoniale. Cela permet de protéger le conjoint sa vie durant, puis de transmettre le capital aux enfants hors fiscalité au second décès.' },
    { q: 'Concrètement, s\'agissant d\'une somme d\'argent, l\'usufruit du conjoint devient un "Quasi-usufruit". Que peut faire le conjoint survivant de l\'argent de l\'assurance-vie ?',
      options: ['Il a le droit de dépenser (consommer) librement l\'intégralité du capital pour maintenir son train de vie, comme s\'il en était plein propriétaire', 'Il ne peut toucher qu\'aux intérêts générés (ex: 2 % par an), l\'argent est bloqué', 'Il doit tout donner aux enfants immédiatement', 'Il doit obligatoirement acheter une maison'],
      correct: 0, rationale: 'Le conjoint est totalement protégé financièrement, il a les mains libres.' },
    { q: 'Puisque le conjoint (quasi-usufruitier) peut tout dépenser, que possèdent réellement les enfants (les nus-propriétaires) ?',
      options: ['Le droit de porter plainte', 'Rien, ils sont déshérités', 'Ils détiennent une "Créance de Restitution" : une dette que le conjoint survivant a envers eux. Au décès de ce conjoint, les enfants récupéreront cette somme en se servant en priorité sur son héritage', 'Les meubles de la maison'],
      correct: 2, rationale: 'C\'est le génie du montage. Si le papa a dépensé tout le capital de l\'assurance-vie, à son propre décès, les enfants prendront la valeur équivalente sur la maison ou les livrets du papa pour se rembourser.' },
    { q: 'Quel est l\'AVANTAGE FISCAL de cette "créance de restitution" au DEUXIÈME DÉCÈS (lorsque le conjoint usufruitier meurt et que les enfants récupèrent leur dû) ?',
      options: ['L\'État prend 50 % de la créance', 'Le montant de cette dette (la créance) vient diminuer l\'actif de la succession du conjoint décédé. Les enfants récupèrent cette somme avec ZÉRO Droit de succession à payer', 'Les impôts locaux doublent', 'La banque prélève 10 %'],
      correct: 1, rationale: 'L\'argent a déjà été fiscalisé au 1er décès. Le remboursement de cette dette au 2ème décès échappe donc totalement aux fourches caudines du notaire et du fisc.' },
    { q: 'Au PREMIER DÉCÈS (lorsque l\'assurance-vie est versée), comment est calculée la fiscalité de l\'enfant (Nu-propriétaire) au regard de l\'abattement classique de 152 500 € ?',
      options: ['L\'enfant n\'a droit à aucun abattement', 'Le conjoint prend tout l\'abattement', 'Le fisc calcule la valeur de la Nue-propriété (selon l\'âge du conjoint usufruitier). L\'enfant ne sera taxé QUE SI cette valeur en Nue-propriété dépasse sa part d\'abattement de 152 500 €', 'L\'enfant paie 20 % sur l\'intégralité du contrat'],
      correct: 2, rationale: 'La transmission se fait à un coût fiscal dérisoire (souvent nul), puisque la valeur de la nue-propriété (ex: 60% d\'un capital de 200 000€) rentre facilement dans le gros abattement de l\'assurance-vie.' },
    { q: 'Que doit payer le conjoint survivant (Usufruitier) comme impôt au premier décès ?',
      options: ['30 % de Flat Tax', 'Absolument RIEN. En tant que conjoint marié (ou partenaire de PACS), il est totalement exonéré de prélèvement sur l\'assurance-vie', 'L\'impôt sur la plus-value', 'Les dettes du défunt uniquement'],
      correct: 1, rationale: 'Le montage est donc parfait : 0 impôt pour le conjoint, très peu (ou 0) pour les enfants sur la nue-propriété.' },
    { q: 'Lors de la rédaction d\'une clause démembrée, quel acte indispensable le notaire et l\'assureur conseillent-ils aux familles de signer pour "sécuriser" la dette des enfants ?',
      options: ['Un contrat d\'assurance vie séparé', 'Une "Convention de Quasi-Usufruit" (enregistrée aux impôts), qui formalise noir sur blanc l\'existence de la dette du conjoint envers les enfants pour que le fisc l\'accepte sans discuter au 2ème décès', 'Une lettre d\'excuses', 'Un bail d\'habitation'],
      correct: 1, rationale: 'Sans ce papier officiel signé, le fisc pourrait refuser la déduction de la dette au second décès, considérant que c\'est une magouille pour éviter l\'impôt.' },
    { q: 'Pourquoi le démembrement de clause bénéficiaire est-il redoutablement plus efficace que la simple désignation "Mon conjoint, à défaut mes enfants" ?',
      options: ['Parce que la clause standard est illégale', 'Si le conjoint reçoit tout en "pleine propriété" (clause standard), l\'argent gonfle son patrimoine. À sa propre mort, cet argent subira les féroces droits de succession normaux lors de la transmission aux enfants. Le démembrement évite cette "double taxation"', 'Car le conjoint ne sait pas gérer l\'argent', 'Car l\'assureur bloque les comptes'],
      correct: 1, rationale: 'C\'est le but premier : éviter que le même argent ne soit taxé lourdement une deuxième fois quand il passera des mains de la maman vers celles des enfants.' },
    { q: '(Challenge) Lors du premier décès, si le conjoint usufruitier a 75 ans, comment calcule-t-on le "poids" fiscal de la part de l\'enfant (Nu-propriétaire) ?',
      options: ['On divise le capital par deux, forfaitairement', 'On applique le barème de l\'Art. 669 du CGI : à 75 ans, l\'usufruit vaut 30 %. La part de l\'enfant (Nue-Propriété) vaut donc 70 %. Le fisc analysera cette valeur de 70 % face à l\'abattement de 152 500 €', 'On calcule selon le salaire de l\'enfant', 'On taxe 100 % du capital'],
      correct: 1, rationale: 'Plus l\'usufruitier est vieux au jour du décès, plus la Nue-propriété (la part fiscale de l\'enfant) est élevée, et plus l\'impôt (prélèvement) risque d\'être lourd si l\'abattement est dépassé.' },
    { q: '(Challenge) Pour protéger les enfants au cas où le conjoint usufruitier "flamberait" tout le capital de manière irresponsable (ils ne pourraient plus récupérer leur dette au second décès faute d\'argent), que peut insérer le souscripteur dans la clause démembrée ?',
      options: ['Le blocage du compte bancaire', 'Une "Obligation de Remploi" : le conjoint ne touche pas le cash, il a l\'obligation de réinvestir les fonds sur un actif démembré (ex : achat d\'une maison ou d\'un compte-titres démembré), protégeant ainsi physiquement le capital des enfants', 'Une taxe sur la consommation', 'L\'interdiction d\'aller au casino'],
      correct: 1, rationale: 'Cela annule le "quasi-usufruit" (le droit de tout dépenser). L\'argent est tracé et réinvesti, les enfants sont certains de récupérer le bien intact à la fin.' },
  ],
  'w23-d4': [
    { q: 'Dans un contrat d\'assurance automobile, à quelle "Garantie" la franchise kilométrique est-elle liée ?',
      options: ['La garantie Bris de glace', 'La garantie Responsabilité Civile', 'La garantie Assistance (Dépannage / Remorquage)', 'La garantie Protection Juridique'],
      correct: 2, rationale: 'C\'est le service qui envoie une dépanneuse si votre véhicule est immobilisé suite à une panne ou un accident.' },
    { q: 'Que signifie concrètement une "Franchise de 50 kilomètres" sur la garantie assistance ?',
      options: ['Vous ne pouvez pas rouler plus de 50 km par jour', 'L\'assurance prend en charge le dépannage UNIQUEMENT si le véhicule est immobilisé à PLUS de 50 kilomètres de votre domicile déclaré', 'Le dépanneur vous facture 50 €', 'L\'assurance vous paie 50 km de taxi'],
      correct: 1, rationale: 'C\'est le seuil de déclenchement. En dessous de cette distance, l\'assureur considère que vous pouvez vous débrouiller.' },
    { q: 'Vous avez un contrat standard avec une franchise de 50 km. Un matin, votre voiture refuse de démarrer devant votre garage (Panne de batterie). Que se passe-t-il si vous appelez l\'assistance de l\'assurance ?',
      options: ['L\'assurance envoie un garagiste gratuit', 'L\'assurance annule votre contrat pour négligence', 'L\'assurance peut organiser le remorquage, mais les frais d\'intervention (souvent 150 à 250 €) seront TOTALEMENT à votre charge, car le sinistre a lieu sous la franchise kilométrique', 'L\'État paie le dépannage'],
      correct: 2, rationale: 'C\'est la pire surprise des assurés. La dépanneuse viendra, mais c\'est vous qui paierez la facture rubis sur l\'ongle.' },
    { q: 'Quelle option ultra-recommandée permet d\'annuler cette contrainte de distance ?',
      options: ['La garantie Tous Risques', 'L\'option "Assistance 0 km" (ou sans franchise kilométrique) : la dépanneuse est prise en charge même si vous tombez en panne dans votre propre allée de garage', 'Le bonus 50 %', 'Le tiers payant garage'],
      correct: 1, rationale: 'Pour quelques dizaines d\'euros de plus par an, c\'est l\'option "tranquillité d\'esprit" absolue pour partir travailler le matin.' },
    { q: 'Attention aux "fausses" pannes : souvent, les garanties d\'assistance (même à 0 km) EXCLUENT certaines causes d\'immobilisation liées à l\'inattention du conducteur. Lesquelles ?',
      options: ['La casse de la courroie de distribution', 'Le vol des essuie-glaces', 'La crevaison, l\'erreur de carburant ou la perte des clés du véhicule', 'L\'usure des freins'],
      correct: 2, rationale: 'L\'assurance est là pour l\'aléa mécanique. Si vous mettez du gasoil dans une essence ou perdez vos clés, beaucoup de contrats refuseront de payer la dépanneuse.' },
    { q: 'Généralement, les contrats auto font une différence de traitement majeure entre une "PANNE" et un "ACCIDENT". Laquelle ?',
      options: ['L\'accident supprime la garantie d\'assistance', 'Même si votre contrat a une "Franchise 50 km" pour la PANNE, la plupart des assureurs appliquent une Assistance 0 km d\'office (sans franchise) s\'il s\'agit d\'un ACCIDENT de la circulation', 'La panne est remboursée double', 'L\'accident exige de payer une caution'],
      correct: 1, rationale: 'Si votre moteur lâche à 2km de chez vous, vous payez le remorquage. Si vous percutez un mur à 2km de chez vous (accident), le remorquage sera couvert.' },
    { q: 'En cas d\'immobilisation de la voiture loin de chez vous (et couverte par l\'assistance), que finance également le service d\'Assistance en plus de la dépanneuse ?',
      options: ['L\'achat d\'une voiture neuve', 'Le retour des passagers à leur domicile (taxi, train) ou leur hébergement à l\'hôtel le temps de la réparation (soumis à plafond)', 'Les amendes de vitesse', 'Le salaire perdu'],
      correct: 1, rationale: 'C\'est le volet "Assistance aux personnes" de l\'assurance. Si vous cassez le moteur à 800 km de chez vous, Mondial Assistance ou Fidelia vous paiera le train pour rentrer.' },
    { q: 'Le rapatriement "sanitaire" (ex: vous vous cassez la jambe en Espagne et ne pouvez plus conduire) est-il conditionné à cette franchise kilométrique ?',
      options: ['Non, il est toujours illégal', 'Oui, 50 km obligatoire', 'Non. Les urgences médicales et le rapatriement des personnes blessées ou malades ne sont pas soumis à la franchise kilométrique auto (l\'assistance médicale intervient souvent dès 0 km ou à l\'étranger)', 'Uniquement si la voiture est détruite'],
      correct: 2, rationale: 'Ne confondez pas le dépannage de la tôle (la voiture) et le sauvetage humain (le conducteur blessé).' },
    { q: '(Challenge) Un accident survient, votre voiture est au garage pour 10 jours. L\'assistance "Véhicule de remplacement" (souvent une option) est incluse dans votre contrat. Le délai de prêt de la voiture de location dépend-il du type de sinistre ?',
      options: ['Non, c\'est toujours 30 jours', 'Oui : l\'assureur prête souvent le véhicule 7 jours en cas de panne, 14 jours en cas d\'accident, et 30 jours (voire 40) en cas de vol du véhicule', 'Le prêt est facturé 100 €/jour', 'Non, on garde la voiture de prêt jusqu\'à l\'achat d\'une nouvelle'],
      correct: 1, rationale: 'Le prêt n\'est jamais illimité. Les plafonds sont inscrits noir sur blanc dans les conditions particulières. Si le garage traîne 2 mois pour réparer votre moteur, l\'assureur arrêtera de payer la location au bout de 7 jours.' },
    { q: '(Challenge) L\'option "Assistance 0 km" paie le plateau de la dépanneuse jusqu\'au garage. Paie-t-elle également LA RÉPARATION MÉCANIQUE de la voiture (les pièces et la main d\'œuvre) ?',
      options: ['Oui, le garage est payé par l\'assurance', 'Oui, mais seulement la main d\'œuvre', 'NON ! L\'assistance ne paie que le REMORQUAGE. Pour que l\'assurance paie le changement du moteur ou de la pièce cassée, il faut avoir souscrit une garantie spécifique "Panne Mécanique"', 'L\'État paie les réparations de plus de 500 €'],
      correct: 2, rationale: 'C\'est l\'incompréhension majeure des assurés. L\'assurance vous amène au garage gratuitement, mais la facture du garagiste pour la courroie de distribution cassée reste 100% à votre charge !' },
  ],
  'w23-d5': [
    { q: 'Avant même de rédiger une annonce de location immobilière, quelle est la toute première étape indispensable pour le bailleur ?',
      options: ['Demander l\'accord au maire', 'Faire le ménage', 'Définir précisément le "profil cible" de locataire (étudiant, famille, cadre) et ajuster le montant du loyer au prix du marché pour éviter une vacance prolongée', 'Acheter des meubles neufs obligatoirement'],
      correct: 2, rationale: 'Proposer un F1 sans parking à 800€ dans une ville moyenne est une erreur d\'étude de marché. Si vous ciblez un étudiant, le bien et le prix doivent correspondre à son budget.' },
    { q: 'Sur l\'annonce de location (LeBonCoin, SeLoger), une information officielle et technique est OBLIGATOIRE depuis plusieurs années sous peine d\'amende. Laquelle ?',
      options: ['L\'année de construction de la rue', 'Le classement énergétique (les lettres A à G issues du fameux DPE - Diagnostic de Performance Énergétique) et l\'estimation des coûts annuels d\'énergie', 'Le nom de l\'ancien propriétaire', 'Le plan des canalisations d\'eau'],
      correct: 1, rationale: 'Le locataire a le droit de savoir s\'il s\'engage à louer une "passoire thermique" (classée F ou G) qui lui coûtera une fortune en chauffage l\'hiver.' },
    { q: 'Dans les zones "Tendues" (Paris, Lyon, Lille...), le propriétaire peut-il fixer le prix de son loyer totalement librement dans son annonce ?',
      options: ['Non, il est soumis au dispositif d\'"Encadrement des loyers" (ou plafonnement) : la mairie/préfecture fixe un "loyer de référence majoré" au mètre carré qu\'il est légalement interdit de dépasser (sauf complément de loyer justifié)', 'Oui, la liberté des prix est absolue', 'Seulement s\'il loue à un étranger', 'Le prix est fixé par l\'agent immobilier'],
      correct: 0, rationale: 'Mettre une annonce avec un loyer abusif dans ces villes expose le propriétaire à une amende de 5 000 € et au remboursement des sommes perçues.' },
    { q: 'Un propriétaire reçoit des candidats locataires. Laquelle de ces pièces est STRICTEMENT INTERDITE par la loi (décret de 2015) dans le dossier de candidature ?',
      options: ['Le contrat de travail', 'Un relevé de compte bancaire (faisant apparaître les dépenses privées), un dossier médical, ou un extrait de casier judiciaire', 'Les 3 derniers bulletins de salaire', 'Une pièce d\'identité'],
      correct: 1, rationale: 'Le bailleur n\'a le droit de demander qu\'une liste fermée de pièces justifiant de l\'identité et de la solvabilité du candidat. Toute incursion dans la vie privée est un délit pénal.' },
    { q: 'Quel ratio de "solvabilité" est traditionnellement réclamé par les bailleurs (et les assurances GLI) aux locataires pour valider un dossier rassurant ?',
      options: ['Le locataire doit gagner le même salaire que le propriétaire', 'Le revenu net mensuel du locataire (ou des garants) doit être égal à environ 3 fois (ou 2,7 fois minimum) le montant du loyer charges comprises', 'Le revenu doit être de 10 fois le loyer', 'Le locataire doit avoir 10 000 € sur son compte'],
      correct: 1, rationale: 'Avec un loyer de 600€, on cherchera un locataire gagnant au moins 1 800€ nets pour s\'assurer qu\'il ne sera pas pris à la gorge par le coût de la vie.' },
    { q: 'Face à un locataire jeune ou précaire (sans CDI, étudiant) qui n\'a pas les fameux "3 fois le loyer", quelle garantie gratuite de l\'État permet souvent de débloquer la signature du bail et de rassurer le propriétaire ?',
      options: ['Le prêt de la CAF', 'La garantie de l\'assurance maladie', 'Le Crédit Logement', 'La Garantie VISALE (gérée par Action Logement), qui se porte caution solidaire gratuitement à la place des parents et rembourse jusqu\'à 36 mois de loyers impayés'],
      correct: 3, rationale: 'Visale remplace l\'assurance GLI (payante) et le garant physique (père/mère). C\'est le sésame pour les moins de 30 ans.' },
    { q: 'Lors de la visite, pour s\'assurer que le candidat intéressé ne se désistera pas, le propriétaire a-t-il le droit de réclamer un "Chèque de réservation" ?',
      options: ['Oui, s\'il rend le chèque le jour de la signature', 'Non, la loi interdit formellement de réclamer la moindre somme d\'argent (chèque de réservation, acompte, espèces) AVANT la signature effective du contrat de bail', 'Uniquement pour les locations meublées', 'Oui, 500 € maximum'],
      correct: 1, rationale: 'Ce type de pratique relève de l\'escroquerie. Le dépôt de garantie et le premier mois de loyer ne se versent qu\'au moment où le stylo signe le contrat.' },
    { q: 'En matière de sélection, un propriétaire refuse un candidat parce qu\'il n\'aime pas sa religion, son origine, son âge ou son orientation sexuelle. Quel est le risque juridique ?',
      options: ['Une simple annulation du bail', 'Il s\'agit d\'une Discrimination réprimée par le Code pénal, passible de 3 ans d\'emprisonnement et 45 000 € d\'amende (le refus de location doit toujours être justifié sur des critères de solvabilité financière objectifs)', 'Le propriétaire est dans son droit absolu', 'Une taxe foncière majorée'],
      correct: 1, rationale: 'Le Testing (envoyer deux faux dossiers de locataires pour piéger le bailleur) est légal en France et est souvent utilisé par des associations pour condamner les propriétaires racistes ou homophobes.' },
    { q: '(Challenge) Lors de la réception de dizaines de dossiers PDF, le risque de fraude (fausses fiches de paie modifiées sur Photoshop) a explosé. Quel service public gratuit et sécurisé l\'État a-t-il mis en place pour certifier les dossiers des locataires et rassurer les bailleurs ?',
      options: ['La plateforme "DossierFacile" (dossierfacile.logement.gouv.fr), qui vérifie l\'authenticité des pièces fiscales et appose des filigranes en travers des documents pour éviter l\'usurpation d\'identité', 'Le fichier de la Banque de France', 'L\'application "Loca-sûr"', 'L\'intervention de la police municipale'],
      correct: 0, rationale: 'Le candidat y télécharge ses pièces, l\'État vérifie qu\'elles correspondent bien aux bases fiscales, et envoie un dossier validé et inaltérable au propriétaire. Une arme redoutable contre les fraudeurs au logement.' },
    { q: '(Challenge) En cas de "Colocation", la recherche de locataires demande un critère RH (Ressources Humaines) supplémentaire souvent négligé. Lequel ?',
      options: ['La taille des candidats', 'Assurer la "cohésion" (le fit) entre les colocataires actuels et le nouveau candidat. Une mauvaise entente provoque un turnover (rotation) important, multipliant la vacance locative et l\'usure de l\'appartement', 'Qu\'ils aient la même banque', 'Obliger les colocataires à travailler ensemble'],
      correct: 1, rationale: 'Le propriétaire malin laisse souvent les colocataires déjà "en place" interviewer et choisir leur futur colocataire. Une colocation en paix d\'esprit est une colocation très rentable.' },
  ],
};
