/* Questions de la semaine 16. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w16-d0': [
    { q: 'En gestion de patrimoine, pourquoi l\'immobilier est-il souvent qualifié de classe d\'actifs "tangible" ?',
      options: ['Parce qu\'il est liquide et facile à vendre', 'Parce qu\'il s\'agit d\'un bien physique (des murs, un terrain) ayant une valeur d\'usage réelle, contrairement aux actifs financiers dématérialisés', 'Parce qu\'il est garanti par l\'État', 'Parce qu\'il génère toujours des plus-values'],
      correct: 1, rationale: 'La pierre rassure. Même en cas de crise financière majeure ou d\'hyperinflation, une maison conserve sa valeur d\'usage : on peut toujours y habiter.' },
    { q: 'Quel est "l\'effet de levier", véritable super-pouvoir exclusif de l\'investissement immobilier ?',
      options: ['Le droit d\'emprunter l\'argent de la banque pour acquérir un actif de grande valeur, dont les loyers rembourseront tout ou partie des mensualités', 'La capacité à revendre plus cher', 'Le fait de pouvoir louer à sa famille', 'L\'exonération totale de la taxe foncière'],
      correct: 0, rationale: 'On ne peut pas emprunter 200 000 € pour les placer en bourse. Mais on peut le faire pour l\'immobilier, ce qui démultiplie la rentabilité du capital (l\'apport) réellement investi par l\'acheteur.' },
    { q: 'Qu\'est-ce que "la pierre-papier" (les SCPI) ?',
      options: ['Des appartements construits avec des matériaux écologiques', 'Un contrat de location papier', 'Une taxe sur les propriétaires', 'L\'achat de parts d\'une société qui acquiert et gère un parc immobilier (bureaux, commerces). L\'investisseur touche sa part des loyers sans gérer aucun locataire'],
      correct: 3, rationale: 'La Société Civile de Placement Immobilier (SCPI) permet d\'investir en immobilier dès quelques centaines d\'euros, avec une diversification totale et zéro souci de gestion.' },
    { q: 'Quel est le principal inconvénient de l\'investissement immobilier physique direct ?',
      options: ['L\'impossibilité de contracter un crédit', 'Le rendement qui est toujours plafonné à 1 %', 'Son illiquidité et sa lourdeur de gestion (trouver des locataires, gérer les travaux, payer la taxe foncière, délais notariaux pour la revente)', 'La forte volatilité quotidienne des prix'],
      correct: 2, rationale: 'L\'immobilier demande du temps, de l\'énergie et de la trésorerie pour faire face aux imprévus (chaudière en panne, vacance locative).' },
    { q: 'Historiquement, comment l\'immobilier locatif réagit-il face à l\'inflation ?',
      options: ['Il s\'effondre systématiquement', 'Il offre une bonne protection, car l\'IRL (Indice de Référence des Loyers) permet d\'augmenter les loyers chaque année en suivant globalement le coût de la vie', 'Les loyers sont plafonnés par la BCE', 'Il stagne'],
      correct: 1, rationale: 'C\'est un actif qui permet de maintenir son pouvoir d\'achat face à la hausse des prix.' },
    { q: 'Dans l\'immobilier, que signifie le "risque de vacance locative" ?',
      options: ['La période pendant laquelle le bien n\'a pas de locataire (et donc ne génère aucun revenu), alors que les charges et le crédit continuent de courir', 'Le fait de louer à des étudiants pendant l\'été', 'Le risque que la maison de vacances perde de la valeur', 'Le vol des meubles par le locataire'],
      correct: 0, rationale: 'C\'est la hantise du bailleur. Un mois de vacance fait lourdement chuter le rendement annuel de l\'investissement.' },
    { q: 'Quel est l\'impact des "frais de mutation" (frais de notaire) sur un achat immobilier ?',
      options: ['Ils sont remboursés au bout de 2 ans', 'Ils annulent les impôts locaux', 'Ils augmentent la valeur de revente de la maison', 'Ils obligent l\'investisseur à conserver le bien à long terme (souvent plus de 7 ans) pour amortir ce coût "à fonds perdus" (environ 8% du prix dans l\'ancien)'],
      correct: 3, rationale: 'Revendre un bien immobilier 2 ans après son achat se solde très souvent par une perte financière à cause de ces frais initiaux non récupérables.' },
    { q: 'Pourquoi dit-on que l\'emplacement ("Location, location, location") est la règle d\'or en immobilier ?',
      options: ['Parce que ça détermine la couleur des murs', 'Car un bon emplacement (proche transports, universités, commerces) garantit la demande locative, limite la vacance et sécurise la valeur de revente du bien', 'Car c\'est l\'agence qui choisit', 'Pour éviter les impôts locaux'],
      correct: 1, rationale: 'Un bien magnifique au milieu de nulle part ne se louera pas. Un studio moyen en centre-ville ne sera jamais vide.' },
    { q: '(Challenge) Lors d\'un investissement locatif avec crédit, que se passe-t-il si l\'on applique l\'effet de levier en période de "taux d\'intérêts très élevés" ?',
      options: ['L\'effet de levier est multiplié par deux', 'Le loyer est automatiquement doublé', 'L\'effet de levier devient "négatif" (ou destructeur) : le coût de l\'argent emprunté dépasse la rentabilité du bien, ce qui appauvrit l\'investisseur chaque mois', 'La banque annule la dette'],
      correct: 2, rationale: 'Si la banque vous prête à 5% et que l\'appartement ne rapporte que 3%, vous perdez de l\'argent tous les mois. Le levier ne fonctionne que si la rentabilité excède le coût du crédit.' },
    { q: '(Challenge) Un investisseur achète en "Nue-propriété" des parts de SCPI ou un appartement. Quel est le mécanisme financier de ce montage ?',
      options: ['Il paie les parts plein tarif mais les loue nues', 'Il doit habiter dans le bien', 'L\'État paie les loyers', 'Il achète avec une forte décote de prix (ex: -30%), renonce à percevoir les loyers pendant une durée fixée (ex: 10 ans), et récupère la pleine propriété (et les loyers) à l\'échéance sans fiscalité'],
      correct: 3, rationale: 'Montage fiscalement puissant pour ceux qui n\'ont pas besoin de revenus immédiats et veulent éviter d\'alourdir leurs impôts actuels.' },
  ],
  'w16-d1': [
    { q: 'Sur un Compte Titres Ordinaire (CTO), comment sont imposés par défaut les dividendes et les plus-values boursières ?',
      options: ['Ils sont exonérés après 5 ans', 'Ils sont taxés à 0 %', 'Ils sont soumis l\'année de leur réalisation au Prélèvement Forfaitaire Unique (PFU ou Flat Tax) de 30 %', 'Ils sont taxés uniquement au moment de la retraite'],
      correct: 2, rationale: 'Le CTO n\'est pas une "enveloppe fiscale" comme le PEA. Chaque gain engrangé sur l\'année est immédiatement soumis à l\'impôt (12,8% d\'IR + 17,2% de prélèvements sociaux).' },
    { q: 'Le PFU (30 %) est la règle par défaut sur le CTO. Le contribuable a-t-il le droit de refuser ce PFU ?',
      options: ['Non, c\'est formellement interdit', 'Uniquement pour les dividendes, pas les plus-values', 'Oui, il peut "opter" globalement pour l\'imposition au barème progressif de l\'impôt sur le revenu si sa TMI (Tranche Marginale) est faible (ex: 0 % ou 11 %)', 'Oui, il peut demander un abattement de 50 %'],
      correct: 2, rationale: 'Ce choix se fait lors de la déclaration de revenus annuelle et permet aux ménages modestes (TMI 0 ou 11%) de payer beaucoup moins d\'impôts que les 30% fixes de la Flat Tax.' },
    { q: 'Vous possédez une action sur votre CTO qui a pris +50 % de valeur cette année. Vous NE LA VENDEZ PAS. Devez-vous payer des impôts sur cette hausse ?',
      options: ['Non, l\'impôt sur les plus-values n\'est déclenché QU\'À LA REVENTE (lorsque la plus-value devient "réalisée")', 'Oui, à la fin de l\'année', 'Oui, mais seulement la moitié de l\'impôt', 'Seulement si la hausse dépasse 1000 €'],
      correct: 0, rationale: 'Tant que vous conservez vos titres (Hold), la croissance latente de votre portefeuille n\'est pas taxée.' },
    { q: 'Sur un CTO, un investisseur vend des titres et réalise une moins-value (perte) de 1 000 €. Peut-il utiliser cette perte fiscalement ?',
      options: ['Non, le fisc ne s\'occupe que des gains', 'Oui, cette moins-value viendra obligatoirement se déduire de ses plus-values boursières réalisées la même année', 'Oui, pour payer sa taxe foncière', 'La banque rembourse la perte'],
      correct: 1, rationale: 'L\'impôt se calcule toujours sur le "solde net" annuel de vos opérations de l\'année (Gains - Pertes).' },
    { q: 'Que se passe-t-il si, sur l\'année complète, vos pertes dépassent vos plus-values boursières sur votre CTO ?',
      options: ['Vous déduisez la perte de votre salaire', 'L\'État vous verse 30 % de la perte', 'Le CTO est clôturé pour incompétence', 'La perte nette (le déficit) est reportable pendant les 10 années suivantes pour venir gommer les futures plus-values boursières'],
      correct: 3, rationale: 'C\'est pour cela qu\'il faut toujours bien déclarer ses pertes. Elles constituent une "réserve d\'impôt gratuit" pour effacer l\'impôt sur vos gains de l\'année prochaine.' },
    { q: 'Une moins-value boursière (perte en capital à la revente) constatée sur un CTO peut-elle être utilisée pour effacer l\'impôt dû sur les DIVIDENDES perçus la même année ?',
      options: ['Non, le fisc sépare les flux. Une moins-value en capital ne s\'impute QUE sur des plus-values en capital, jamais sur des revenus de dividendes', 'Oui, c\'est le principe de la compensation globale', 'Uniquement pour les actions françaises', 'Seulement si on est au barème progressif'],
      correct: 0, rationale: 'C\'est une règle fiscale stricte et un piège fréquent. Le capital se compense avec le capital.' },
    { q: 'Concernant l\'imposition des dividendes, quelle est la grande différence fiscale en cours de vie entre le CTO et le PEA ?',
      options: ['Le CTO ne verse pas de dividendes', 'Le dividende perçu sur le CTO est taxé l\'année de son versement (frottement fiscal), alors que dans le PEA, le dividende n\'est pas taxé tant qu\'il reste dans l\'enveloppe', 'Le PEA taxe les dividendes à 50%', 'Aucune différence'],
      correct: 1, rationale: 'C\'est pourquoi, pour profiter pleinement des intérêts composés (réinvestir 100% de son dividende), le PEA est supérieur au CTO.' },
    { q: 'Qu\'est-ce que la TTF (Taxe sur les Transactions Financières) prélevée sur votre CTO lors de certains achats ?',
      options: ['Un abonnement annuel à la banque', 'Une taxe de 20 % sur les ETF américains', 'Un impôt européen sur les cryptomonnaies', 'Une taxe de l\'État français (actuellement 0,3 %) prélevée sur l\'achat d\'actions de grandes entreprises françaises dont la capitalisation dépasse 1 milliard d\'euros'],
      correct: 3, rationale: 'Si vous achetez des actions Total ou LVMH, vous paierez cette taxe supplémentaire (qui ne s\'applique pas à la revente).' },
    { q: '(Challenge) Lors de l\'ouverture d\'un compte, quel atout juridique le CTO possède-t-il que le PEA n\'a absolument pas ?',
      options: ['Il peut être anonyme', 'Il est exonéré de frais de succession', 'Il peut être ouvert en "Compte Joint" (aux deux noms d\'un couple) ou en indivision, facilitant la gestion familiale', 'Il donne le droit de voter deux fois'],
      correct: 2, rationale: 'Le PEA est strictement individuel. Un couple marié gérant son argent ensemble optera souvent pour un CTO joint.' },
    { q: '(Challenge) Un parent possède sur son CTO des actions Apple achetées 10 000 €, qui valent aujourd\'hui 30 000 €. S\'il fait une "Donation" de ces titres à son enfant via un notaire, que devient l\'impôt sur la plus-value latente de 20 000 € ?',
      options: ['L\'enfant devra payer les 30 % d\'impôts immédiatement', 'La plus-value latente est purement et simplement "purgée" (effacée). Personne ne paiera jamais d\'impôt sur le revenu sur ces 20 000 € de gains passés', 'Le parent doit payer l\'impôt avant de donner', 'La banque saisit les titres'],
      correct: 1, rationale: 'C\'est une niche fiscale incroyable de la donation de compte-titres. Le compteur fiscal de l\'enfant repartira à zéro sur la base de 30 000 €. Le gain de 20 000 € échappe définitivement à l\'impôt sur la plus-value boursière.' },
  ],
  'w16-d2': [
    { q: 'Quelle est la règle de base (le principe de fonctionnement) du Plan d\'Épargne Retraite (PER) concernant la disponibilité de l\'argent ?',
      options: ['Il est retirable tous les 5 ans', 'Il est bloqué pendant 8 ans maximum', 'L\'épargne est bloquée ("tunnel de placement") jusqu\'à la liquidation de la retraite ou l\'âge légal, sauf cas de déblocage anticipé prévus par la loi', 'Il est retirable tous les mois sans motif'],
      correct: 2, rationale: 'Le législateur veut vous empêcher de dépenser cette épargne pour la consommation courante afin de garantir un complément de revenus pour vos vieux jours.' },
    { q: 'La loi PACTE a introduit un motif majeur de déblocage très apprécié des jeunes actifs. Lequel permet de récupérer son PER à tout moment ?',
      options: ['L\'achat d\'une voiture neuve', 'Le paiement des impôts sur le revenu', 'Le financement d\'un mariage', 'L\'acquisition de la résidence principale'],
      correct: 3, rationale: 'C\'est l\'argument numéro un du PER pour les moins de 40 ans : pouvoir défiscaliser ses revenus aujourd\'hui et utiliser l\'enveloppe comme apport personnel pour acheter sa maison.' },
    { q: 'Outre l\'achat de la résidence principale, les autres cas de déblocage anticipé du PER concernent les "accidents de la vie". Lequel en fait partie ?',
      options: ['Une mutation professionnelle', 'L\'invalidité (de catégorie 2 ou 3) du titulaire, de son conjoint/partenaire de PACS, ou de ses enfants', 'Un divorce', 'La baisse de son salaire'],
      correct: 1, rationale: 'Un handicap grave rend la préparation à la retraite secondaire face à l\'urgence financière immédiate.' },
    { q: 'Un titulaire de PER est licencié. Peut-il débloquer son PER immédiatement au premier jour de son chômage ?',
      options: ['Non, le motif valable n\'est pas le licenciement, mais "l\'expiration des droits aux allocations chômage" (la fin de l\'indemnisation par Pôle Emploi/France Travail)', 'Oui, une simple lettre de licenciement suffit', 'Uniquement s\'il a plus de 50 ans', 'Oui, s\'il a été licencié pour faute'],
      correct: 0, rationale: 'Le PER agit comme l\'ultime filet de sécurité. Tant que le chômage vous paie, le PER reste bloqué.' },
    { q: 'Le décès d\'un proche est un motif de déblocage. De qui parle-t-on précisément ?',
      options: ['Du décès d\'un enfant', 'Du décès d\'un parent (père/mère)', 'Du décès du conjoint marié ou du partenaire de PACS', 'Du décès d\'un frère ou d\'une sœur'],
      correct: 2, rationale: 'Le décès de celui qui partage les charges du foyer justifie le besoin urgent de récupérer le capital.' },
    { q: 'Un travailleur indépendant (TNS) fait faillite. Peut-il débloquer son PER ?',
      options: ['Oui, dans le cadre d\'un jugement de liquidation judiciaire de son entreprise (ou procédure de surendettement validée par la Banque de France pour un particulier)', 'Uniquement si la banque est d\'accord', 'Non, les entreprises ne sont pas concernées par le PER', 'Seulement s\'il a une hypothèque'],
      correct: 0, rationale: 'Le juge peut autoriser ou exiger le déblocage pour effacer les dettes.' },
    { q: 'Est-il possible de débloquer son PER pour acquérir une résidence SECONDAIRE (ex : maison de vacances) ?',
      options: ['Oui, après 10 ans de détention', 'Non, le déblocage immobilier est strictement et exclusivement limité à l\'acquisition de la résidence PRINCIPALE', 'Oui, si elle est en France', 'Seulement si c\'est pour du locatif'],
      correct: 1, rationale: 'L\'État accepte de faire une exception pour le toit où vous vivez, mais pas pour l\'immobilier de loisir ou d\'investissement.' },
    { q: 'FISCALITÉ : Lors d\'un déblocage pour "Accident de la vie / Coup dur" (ex : invalidité, fin de chômage), comment le capital retiré est-il taxé ?',
      options: ['Il est lourdement taxé à 30 %', 'Le capital ET les plus-values sont totalement EXONÉRÉS d\'Impôt sur le Revenu. (Seuls les prélèvements sociaux de 17,2 % s\'appliquent sur les plus-values)', 'Il est réintégré aux revenus de l\'année', 'Il y a une pénalité de 10 %'],
      correct: 1, rationale: 'C\'est la beauté du système. L\'État ne punit pas celui qui subit un drame. L\'épargne récupérée l\'est en totale franchise d\'impôt (alors qu\'elle avait été déduite à l\'entrée !).' },
    { q: '(Challenge) FISCALITÉ : À l\'inverse, lors d\'un déblocage pour "Acquisition de la Résidence Principale" (choix de confort), quelle est la lourde conséquence fiscale (si les versements avaient été déduits à l\'entrée) ?',
      options: ['C\'est exonéré d\'impôt comme pour les coups durs', 'La banque annule ses intérêts', 'On paie juste la TVA', 'Le capital retiré est réintégré aux revenus de l\'année (et taxé au barème progressif de la TMI), et les plus-values sont taxées au PFU (30 %)'],
      correct: 3, rationale: 'Si vous débloquez 30 000€ pour votre maison, votre revenu imposable bondit de 30 000€. L\'avantage fiscal obtenu à l\'entrée est donc "remboursé" à la sortie.' },
    { q: '(Challenge) Un salarié possède un "PER d\'Entreprise Obligatoire" (alimenté par les cotisations obligatoires de l\'employeur). Peut-il le débloquer pour acheter sa résidence principale ?',
      options: ['Oui, la résidence principale est valable pour tous les PER', 'Non, le "Compartiment 3" (versements obligatoires de l\'employeur) ne peut JAMAIS être débloqué pour l\'achat de la résidence principale. Il reste bloqué jusqu\'à la retraite', 'Oui, avec l\'accord du patron', 'Seulement si la maison est neuve'],
      correct: 1, rationale: 'Le déblocage pour achat immobilier ne concerne que l\'argent que vous avez versé volontairement (PER Individuel) ou l\'intéressement/abondement (PER Collectif). L\'argent obligatoire de l\'entreprise est bloqué à vie.' },
  ],
  'w16-d3': [
    { q: 'En droit de la famille, qu\'est-ce qu\'une "donation-partage" ?',
      options: ['Un don fait à une association caritative', 'Un acte par lequel un parent donne de son vivant une partie ou la totalité de ses biens à ses enfants, ET procède immédiatement au partage matériel de ces biens entre eux', 'Le fait de prêter sa maison', 'Une séparation de biens lors d\'un divorce'],
      correct: 1, rationale: 'La donation simple donne un bien. La donation-partage donne ET attribue définitivement les lots à chacun pour éviter les indivisions.' },
    { q: 'Quelle condition de forme est ABSOLUMENT OBLIGATOIRE pour qu\'une donation-partage soit valable ?',
      options: ['Il suffit d\'un repas de famille', 'Elle doit être signée à la mairie', 'Elle doit être faite en secret', 'Elle doit obligatoirement être réalisée par "Acte Authentique" devant un notaire, sous peine de nullité absolue'],
      correct: 3, rationale: 'Vu l\'impact définitif sur l\'héritage, le législateur impose le filtre du notaire pour garantir l\'équilibre et le consentement de tous.' },
    { q: 'Quel est l\'AVANTAGE MAJEUR de la donation-partage par rapport à des "donations simples" faites à plusieurs enfants à des dates différentes ?',
      options: ['Elle coûte moins cher en notaire', 'Elle fige définitivement la valeur des biens au jour de la donation. Il n\'y aura aucune réévaluation (pas de rapport à la succession) au décès du parent', 'Elle est exonérée d\'impôts locaux', 'Elle permet d\'annuler les dettes du parent'],
      correct: 1, rationale: 'Si Pierre reçoit un appartement qui prend de la valeur et Paul reçoit du cash qu\'il dépense, il n\'y aura aucun compte à rendre entre eux au décès. La paix des familles est préservée.' },
    { q: 'Un parent ayant 3 enfants peut-il faire une donation-partage en ne donnant des biens qu\'à 2 de ses enfants (le 3ème ne recevant rien) ?',
      options: ['Oui, le parent fait ce qu\'il veut', 'Uniquement si le 3ème enfant est mineur', 'Oui, mais il paiera plus d\'impôts', 'Non, pour que la donation-partage soit valable et fige les valeurs, tous les enfants doivent obligatoirement participer à l\'acte et recevoir un lot'],
      correct: 3, rationale: 'Si un enfant est exclu de l\'acte, l\'acte est rétrogradé juridiquement en "donations simples" avec tous les risques de réévaluation et de conflits futurs.' },
    { q: 'Dans une donation-partage, les parents sont-ils obligés de donner des lots de valeur strictement identique (ex : 100 000 € chacun) ?',
      options: ['Non, les lots peuvent être inégaux. L\'enfant qui reçoit plus devra alors verser une "soulte" (une compensation financière) à ses frères et sœurs pour rééquilibrer le partage', 'Oui, l\'égalité au centime près est imposée par la loi', 'Oui, sinon l\'État saisit la différence', 'Non, et le parent n\'a pas à compenser'],
      correct: 0, rationale: 'Si la maison vaut 200k€ et qu\'il n\'y a que 100k€ en cash, Pierre prend la maison, Paul prend le cash, et Pierre donne 50k€ de sa poche à Paul. Tout le monde a bien 150k€.' },
    { q: 'Que devient "l\'Action en réduction" (la contestation d\'un enfant qui s\'estimerait lésé sur sa réserve héréditaire) suite à une donation-partage bien faite ?',
      options: ['Elle est ouverte pendant 30 ans', 'Elle est virtuellement éteinte. Ayant accepté son lot et signé l\'acte notarié figeant les valeurs, l\'héritier ne peut plus remettre en cause ce partage lors du décès', 'Elle est automatique', 'Elle passe au tribunal pénal'],
      correct: 1, rationale: 'C\'est le but recherché par les parents : organiser leur succession de leur vivant pour que les enfants ne se déchirent pas devant le juge après leur mort.' },
    { q: 'Une donation-partage est-elle possible en "démembrement" de propriété ?',
      options: ['Non, la pleine propriété est requise', 'Oui, les parents peuvent donner la "Nue-propriété" de leurs biens partagés à leurs enfants tout en conservant "l\'Usufruit" (le droit d\'y habiter ou de toucher les loyers) jusqu\'à leur mort', 'Uniquement pour l\'argent liquide', 'Seulement si la maison est neuve'],
      correct: 1, rationale: 'C\'est la technique patrimoniale reine : on partage les biens, on fixe les valeurs, on évite les impôts, et les parents restent protégés chez eux.' },
    { q: 'Que permet la "Donation-partage transgénérationnelle" introduite en 2006 ?',
      options: ['De donner aux enfants du voisin', 'De donner uniquement aux arrière-grands-parents', 'À un grand-parent de sauter une génération et de distribuer des biens directement à ses petits-enfants (avec l\'accord exprès de ses propres enfants qui renoncent à leur part)', 'De transmettre des gènes'],
      correct: 2, rationale: 'Avec l\'allongement de l\'espérance de vie, les enfants héritent souvent à 65 ans (quand ils n\'en ont plus besoin). Ce mécanisme permet d\'aider les petits-enfants de 30 ans qui s\'installent.' },
    { q: '(Challenge) Un père a fait de nombreuses "donations simples" en numéraire (cash) à ses enfants tout au long de sa vie. Arrivé à 70 ans, il s\'inquiète des conflits lors de son décès. Que peut lui proposer le notaire ?',
      options: ['De réclamer le remboursement du cash', 'D\'annuler les donations', 'D\'ignorer le problème', 'De faire une "réincorporation" : réunir toutes les anciennes donations simples dans une nouvelle donation-partage globale, afin de transformer leur statut et de figer enfin leurs valeurs pour la succession'],
      correct: 3, rationale: 'Le notaire remet tous les compteurs à plat, officialise le partage passé et présent, et sécurise la future succession.' },
    { q: '(Challenge) Fiscalement, la donation-partage bénéficie-t-elle d\'un avantage supérieur à la donation simple ?',
      options: ['Oui, il n\'y a aucun impôt', 'Non, la fiscalité est exactement la même (application de l\'abattement de 100 000 € par enfant, puis barème progressif). L\'avantage de la donation-partage est purement juridique et civil (paix des familles)', 'Oui, l\'abattement est doublé', 'La donation-partage coûte le double en impôts'],
      correct: 1, rationale: 'Le fisc ne fait pas de différence tarifaire entre vous donner un bien ou vous le partager. La différence se fait au niveau du droit de la famille (fonds gelés, action en réduction).' },
  ],
  'w16-d4': [
    { q: 'Dans le domaine de la Prévoyance, quelle est la différence fondamentale entre "Incapacité" et "Invalidité" ?',
      options: ['L\'incapacité est physique, l\'invalidité est mentale', 'L\'invalidité ne concerne que la voiture', 'L\'incapacité est un arrêt de travail temporaire (maladie). L\'invalidité est un état définitif, déclaré après consolidation médicale, où la capacité de travail et de gain de la personne est irrémédiablement réduite', 'Il n\'y a aucune différence'],
      correct: 2, rationale: 'Après souvent 3 ans d\'incapacité (arrêt maladie), la Sécurité sociale déclare l\'assuré en invalidité si son état ne peut plus s\'améliorer.' },
    { q: 'La Sécurité sociale classe les invalides en 3 catégories. À quoi correspond la "Catégorie 1" ?',
      options: ['Un invalide alité H24', 'Un invalide capable d\'exercer une activité rémunérée, mais dont la capacité de gain est réduite d\'au moins 2/3 (il peut souvent travailler à temps partiel)', 'Un invalide qui a perdu un doigt', 'Un invalide nécessitant une aide pour manger'],
      correct: 1, rationale: 'La personne perçoit une petite pension de la Sécu (30% de son ancien salaire) et complète souvent en travaillant à mi-temps.' },
    { q: 'À quoi correspond la "Catégorie 2" d\'invalidité de la Sécurité sociale ?',
      options: ['Invalide absolument incapable d\'exercer une profession quelconque. (Pension fixée à 50% de l\'ancien salaire)', 'Invalide ayant besoin d\'une tierce personne pour se laver', 'Invalide pouvant travailler à plein temps', 'Une personne à la retraite'],
      correct: 0, rationale: 'C\'est le cas lourd classique. L\'assuré ne peut plus travailler. La Sécu ne lui donne que 50% de son ancien salaire (plafonné), ce qui engendre une perte de niveau de vie violente.' },
    { q: 'C\'est ici qu\'intervient le "Contrat de Prévoyance Invalidité" (souscrit par l\'entreprise ou à titre privé). Quel est son rôle ?',
      options: ['Rembourser les médicaments', 'Payer les réparations de la voiture', 'Venir compléter la faible pension de la Sécurité sociale en versant une "Rente d\'invalidité" mensuelle pour ramener le revenu de l\'assuré à un niveau proche de son ancien salaire (souvent 80 à 100%)', 'Assurer la maison'],
      correct: 2, rationale: 'La prévoyance agit comme un bouclier de revenus. Sans elle, un salarié de catégorie 2 bascule souvent dans la précarité.' },
    { q: 'Plutôt qu\'une Rente mensuelle, que prévoit parfois le contrat de prévoyance en cas de "PTIA" (Perte Totale et Irréversible d\'Autonomie / Catégorie 3) ?',
      options: ['Le versement d\'un Capital important en une seule fois pour aménager le logement ou le véhicule (fauteuil roulant, rampe d\'accès)', 'L\'envoi d\'une infirmière gratuite', 'Une réduction d\'impôts', 'La résiliation de la mutuelle'],
      correct: 0, rationale: 'En cas de handicap gravissime, il faut souvent faire de lourds travaux chez soi de façon urgente.' },
    { q: 'Dans les contrats individuels (souvent pour les indépendants/TNS), l\'assureur n\'utilise pas toujours les catégories de la Sécurité sociale. Comment évalue-t-il l\'invalidité ?',
      options: ['À vue d\'œil', 'En croisant un "Taux d\'invalidité fonctionnelle" (le handicap physique dans la vie de tous les jours) et un "Taux d\'invalidité professionnelle" (l\'impact de ce handicap sur la profession exacte de l\'assuré)', 'En demandant l\'avis du maire', 'Par un test sportif'],
      correct: 1, rationale: 'C\'est la table à double entrée, base de toute expertise d\'assurance.' },
    { q: 'Pourquoi le "Barème Professionnel" est-il VITAL pour des métiers comme Chirurgien ou Pianiste ?',
      options: ['Parce qu\'ils sont célèbres', 'Car perdre un doigt (invalidité fonctionnelle faible : 10%) entraîne une invalidité professionnelle totale (100%) pour un chirurgien. Avec un barème pro, l\'assureur le paiera à 100%. Sans ce barème, l\'assureur ne lui verserait presque rien', 'Pour payer moins cher l\'assurance', 'C\'est exigé par l\'Ordre des médecins'],
      correct: 1, rationale: 'Un employé de bureau qui perd un index peut continuer à travailler. Pour un chirurgien, la carrière est terminée. L\'assurance doit juger l\'impact SUR LE MÉTIER PRÉCIS.' },
    { q: 'À partir de quel seuil global (taux d\'invalidité) la majorité des assurances prévoyance commencent-elles à verser une rente partielle ?',
      options: ['1 %', '66 %', 'Généralement à partir de 33 % (Invalidité de 1ère catégorie). En dessous de 33 %, l\'assureur ne verse strictement rien', '100 %'],
      correct: 2, rationale: 'C\'est le "seuil d\'intervention". Les petits handicaps qui n\'empêchent pas de gagner sa vie ne sont pas couverts par la rente d\'invalidité.' },
    { q: '(Challenge) Jusqu\'à quel âge la "Rente d\'invalidité" de la prévoyance est-elle généralement versée à l\'assuré ?',
      options: ['À vie (jusqu\'au décès)', 'Jusqu\'à l\'âge légal de départ à la retraite (souvent 62 ou 64 ans). Ensuite, c\'est la pension de retraite "pour inaptitude" qui prend le relais définitif', 'Pendant 10 ans maximum', 'Jusqu\'à la guérison'],
      correct: 1, rationale: 'La prévoyance compense la perte du salaire de la vie active. Une fois l\'âge de la retraite atteint, vous sortez de la vie active, le contrat s\'arrête.' },
    { q: '(Challenge) Vous souscrivez un contrat de prévoyance invalidité à titre individuel. Qu\'est-ce que le "Délai de Franchise" ?',
      options: ['La période (souvent 30, 60 ou 90 jours) d\'arrêt de travail ininterrompu PENDANT LAQUELLE l\'assureur ne verse pas encore d\'indemnités', 'Le délai pour payer la cotisation', 'La somme qui reste à votre charge à l\'hôpital', 'Le délai d\'annulation du contrat'],
      correct: 0, rationale: 'Plus vous choisissez une franchise courte (ex: l\'assureur paie dès le 15ème jour d\'arrêt), plus le contrat coûtera cher. Un salarié très protégé par son entreprise prendra une franchise longue (90 jours).' },
  ],
  'w16-d5': [
    { q: 'En location NUE, vous relevez automatiquement du régime fiscal "Micro-foncier" si vos revenus fonciers (loyers bruts) annuels ne dépassent pas un certain plafond. Quel est ce plafond ?',
      options: ['5 000 €', '15 000 € par an', '50 000 €', '100 000 €'],
      correct: 1, rationale: 'Si vous encaissez plus de 15 000 € de loyers hors charges dans l\'année, le régime micro vous est interdit, vous basculez obligatoirement au Régime Réel.' },
    { q: 'Quel est le fonctionnement (l\'avantage de simplicité) du régime Micro-foncier ?',
      options: ['Vos impôts sont annulés', 'Vous devez justifier toutes vos dépenses de travaux avec des factures', 'L\'administration fiscale applique un abattement forfaitaire automatique de 30 %. Vous n\'êtes imposé que sur 70 % de vos loyers, sans avoir à garder ou fournir la moindre facture de charges', 'La taxe foncière est divisée par deux'],
      correct: 2, rationale: 'C\'est le régime de la tranquillité d\'esprit pour ceux qui ont des appartements récents ne nécessitant aucun travaux.' },
    { q: 'En quoi consiste l\'option pour le "Régime Réel" d\'imposition ?',
      options: ['À payer l\'impôt en argent liquide', 'L\'abattement forfaitaire est supprimé. À la place, le propriétaire déduit de ses loyers le montant EXACT (au centime près) des charges qu\'il a réellement payées dans l\'année', 'À laisser le locataire payer les impôts', 'À être imposé sur la valeur de la maison'],
      correct: 1, rationale: 'C\'est un travail comptable plus lourd, mais indispensable pour défiscaliser de gros travaux.' },
    { q: 'Dans quel cas mathématique un investisseur a-t-il INTÉRÊT à renoncer au Micro-foncier pour "opter" volontairement pour le Régime Réel ?',
      options: ['S\'il n\'a fait aucune dépense dans l\'année', 'Si le total de ses charges déductibles de l\'année (intérêts du prêt, travaux, taxe foncière, assurance) SUPÉRIE à 30 % de ses loyers', 'S\'il habite dans le logement', 'S\'il vend le bien'],
      correct: 1, rationale: 'Si vos charges valent 50% de vos loyers, rester au micro-foncier (qui ne vous déduit que 30%) serait une erreur fiscale, vous paieriez trop d\'impôts.' },
    { q: 'Quelle est la grande contrepartie (le piège) à connaître si vous "optez" volontairement pour le Régime Réel alors que vous étiez sous les 15 000 € ?',
      options: ['L\'option est irrévocable (bloquée) pour une durée de 3 ans. Vous ne pourrez pas revenir au Micro-foncier avant 3 ans, même si vos charges retombent à zéro l\'année d\'après', 'Vous paierez la taxe foncière en double', 'Le loyer est bloqué', 'La banque augmente votre taux'],
      correct: 0, rationale: 'Le fisc vous accorde l\'avantage des frais réels, mais exige de la stabilité. Il faut donc être sûr d\'avoir assez de charges sur les 3 prochaines années pour que l\'option soit rentable sur la durée.' },
    { q: 'Au Régime Réel, que se passe-t-il si vos charges (les travaux) sont tellement élevées qu\'elles dépassent le montant de vos loyers de l\'année ?',
      options: ['La banque rembourse la différence', 'Vous créez un "Déficit Foncier". La partie des pertes liées aux travaux viendra se déduire directement de votre SALAIRE (revenu global), faisant baisser votre impôt sur le revenu', 'L\'excédent est perdu', 'Le loyer est augmenté par l\'État'],
      correct: 1, rationale: 'C\'est l\'un des mécanismes de défiscalisation les plus puissants en France pour les cadres supérieurs.' },
    { q: 'Parmi ces dépenses, laquelle est DÉDUCTIBLE de vos loyers au Régime Réel ?',
      options: ['La taxe d\'habitation payée par le locataire', 'Les factures d\'eau et d\'électricité consommées par le locataire', 'La Taxe Foncière, les primes d\'assurance PNO, les frais d\'agence de gestion et les intérêts de votre crédit immobilier', 'L\'agrandissement de la maison (nouvelle pièce)'],
      correct: 2, rationale: 'Toutes les charges supportées par le propriétaire pour la conservation et l\'administration de son bien loué sont déductibles.' },
    { q: 'Et concernant les TRAVAUX, lesquels sont déductibles au Régime Réel ?',
      options: ['Les travaux de réparation, d\'entretien et d\'amélioration (ex: changer les fenêtres, refaire la cuisine, réparer le toit)', 'La construction d\'une nouvelle véranda ou piscine (agrandissement)', 'La décoration de la résidence principale du propriétaire', 'Les meubles de salon'],
      correct: 0, rationale: 'Le fisc refuse la déduction des travaux de construction, d\'agrandissement et de reconstruction.' },
    { q: '(Challenge) Lors de la création d\'un "Déficit foncier" (les charges dépassent les loyers), l\'État impose un PLAFOND d\'imputation sur le revenu global (votre salaire). Quel est ce plafond par défaut ?',
      options: ['1 000 € par an', '10 700 € par an', '50 000 € par an', 'Illimité'],
      correct: 1, rationale: 'Si votre déficit de travaux est de 30 000 €, vous déduirez 10 700 € de votre salaire l\'année 1, et l\'excédent (19 300 €) sera mis en réserve pour gommer vos futurs loyers pendant 10 ans.' },
    { q: '(Challenge) Dans le calcul du déficit foncier, une règle stricte encadre les INTÉRÊTS D\'EMPRUNT. Laquelle ?',
      options: ['Ils se déduisent directement du salaire', 'Ils sont interdits de déduction', 'Ils sont multipliés par deux', 'Ils ne peuvent se déduire qu\'exclusivement des revenus fonciers (loyers). Ils ne peuvent JAMAIS créer un déficit déductible du salaire (revenu global)'],
      correct: 3, rationale: 'L\'emprunt sert à absorber le loyer. Si les intérêts dépassent le loyer, cette perte se reporte 10 ans sur l\'immobilier, mais ne fait jamais baisser l\'impôt de votre salaire.' },
  ],
};
