/* Questions de la semaine 26. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w26-d0': [
    { q: 'En finance, qu\'est-ce qu\'une "classe d\'actifs" ?',
      options: ['Un logiciel pour analyser la bourse', 'Un impôt sur le capital', 'Un groupe d\'investissements présentant des caractéristiques financières et des comportements économiques similaires (actions, obligations, immobilier, etc.)', 'Le classement des banques mondiales'],
      correct: 2, rationale: 'Classer les actifs permet de structurer un portefeuille. Chaque classe réagit différemment à l\'inflation, aux taux d\'intérêts ou à la croissance.' },
    { q: 'Laquelle de ces classes d\'actifs est considérée comme la plus "sécurisée" et la plus liquide, mais offrant le rendement le plus faible ?',
      options: ['L\'immobilier physique', 'Les placements monétaires (liquidités, livrets réglementés, fonds euros)', 'Le Private Equity (non-coté)', 'Les actions des pays émergents'],
      correct: 1, rationale: 'Le cash et les placements à court terme garantissent le capital pour faire face aux urgences, mais souffrent face à l\'inflation.' },
    { q: 'Quelle classe d\'actifs représente des "titres de propriété" d\'entreprises et capte directement la croissance économique, au prix d\'une forte volatilité ?',
      options: ['Le marché de l\'art', 'Les matières premières', 'Les obligations d\'État', 'Les actions (Equities)'],
      correct: 3, rationale: 'L\'investisseur en actions est copropriétaire de l\'entreprise. C\'est la classe d\'actifs la plus performante sur le très long terme.' },
    { q: 'Qu\'est-ce qui caractérise la classe d\'actifs des "Obligations" (la dette) ?',
      options: ['Le rendement dépend uniquement du prix du pétrole', 'L\'investisseur est un créancier (un prêteur) qui perçoit des intérêts réguliers (coupons) en attendant le remboursement du capital à une date fixée', 'C\'est un placement qui permet d\'annuler les impôts', 'L\'investisseur obtient le droit de diriger l\'entreprise'],
      correct: 1, rationale: 'Moins volatiles que les actions, les obligations servent souvent d\'amortisseur dans un portefeuille, bien qu\'elles soient sensibles aux taux d\'intérêt.' },
    { q: 'Quel est l\'atout principal de la classe d\'actifs "Immobilier" par rapport aux actions et aux obligations ?',
      options: ['C\'est un actif tangible, souvent décorrélé des marchés financiers purs, qui peut générer des revenus indexés sur l\'inflation et permet l\'utilisation du crédit (effet de levier)', 'C\'est le seul actif totalement exonéré d\'impôts', 'Il offre la meilleure liquidité du marché', 'Il ne nécessite aucun apport personnel'],
      correct: 0, rationale: 'C\'est le pilier de la construction patrimoniale des Français grâce à la possibilité de l\'acheter avec l\'argent de la banque.' },
    { q: 'On parle souvent des "Actifs Alternatifs". Lequel de ces investissements en fait partie ?',
      options: ['Un Livret A', 'Une action LVMH', 'Les cryptomonnaies, le Private Equity (non-coté), l\'art, les montres ou les grands crus', 'Un compte courant'],
      correct: 2, rationale: 'Les actifs alternatifs sortent des circuits boursiers ou bancaires traditionnels. Ils visent de hauts rendements mais sont souvent illiquides et risqués.' },
    { q: 'Pourquoi un gestionnaire de patrimoine mélange-t-il obligatoirement plusieurs classes d\'actifs (Allocation d\'actifs) dans un portefeuille ?',
      options: ['Pour profiter de la "décorrélation" : si la bourse baisse, les obligations ou l\'or peuvent monter ou stagner, lissant ainsi la volatilité globale et protégeant le portefeuille', 'Uniquement pour faire payer plus de frais de gestion', 'Pour cacher l\'argent au fisc', 'Parce que la loi européenne l\'y oblige sous peine d\'amende'],
      correct: 0, rationale: 'C\'est la base de la diversification. On ne mélange pas que des entreprises (diversification sectorielle), on mélange surtout des MOTEURS de performance différents.' },
    { q: 'Selon les études financières historiques, quel facteur détermine à plus de 90 % la performance et le niveau de risque d\'un portefeuille sur le long terme ?',
      options: ['Le "Stock picking" (le talent à choisir l\'action gagnante)', 'L\'Allocation d\'actifs (le choix de la répartition globale : ex. 60% actions / 40% obligations)', 'Les diplômes du gérant', 'Le "Market timing" (savoir quand acheter et vendre au jour près)'],
      correct: 1, rationale: 'Choisir d\'être exposé à 80% aux actions plutôt qu\'aux obligations aura un impact infiniment plus massif sur votre patrimoine final que de savoir s\'il valait mieux acheter Apple ou Microsoft.' },
    { q: '(Challenge) Mécaniquement, que se passe-t-il pour la classe d\'actifs "Obligations" lorsque la Banque Centrale DÉCIDE DE BAISSER fortement ses taux d\'intérêt directeurs ?',
      options: ['La valeur des anciennes obligations déjà émises (et leurs cours) AUGMENTE, car elles offrent un rendement supérieur aux nouvelles conditions du marché', 'Les obligations sont annulées par l\'État', 'La valeur des anciennes obligations S\'EFFONDRE', 'Leurs taux s\'ajustent automatiquement à zéro'],
      correct: 0, rationale: 'C\'est la balance des taux. Si vous avez une obligation qui paie 4%, et que les nouveaux taux chutent à 1%, tout le monde voudra vous racheter votre obligation à 4%. Son prix montera donc en flèche.' },
    { q: '(Challenge) Quelle classe d\'actifs est particulièrement sensible au "risque de liquidité" et nécessite de bloquer son épargne pendant 5 à 10 ans minimum pour espérer une forte prime de rendement ?',
      options: ['Le Private Equity (Capital-Investissement)', 'Les actions du CAC 40', 'Les ETF monde', 'L\'Or papier'],
      correct: 0, rationale: 'Investir dans des PME non cotées empêche de récupérer son argent sur un simple clic. La prime de rendement (le TRI visé) est la récompense de ce sacrifice de liquidité.' },
  ],
  'w26-d1': [
    { q: 'Quelle est la grande différence fiscale entre une "Déduction" et une "Réduction" d\'impôt ?',
      options: ['Il n\'y en a aucune', 'La réduction est remboursée en argent liquide', 'La déduction baisse le REVENU imposable (son impact dépend de votre tranche d\'imposition/TMI). La réduction baisse directement L\'IMPÔT final calculé (son impact est le même pour tous)', 'La déduction est réservée aux entreprises, la réduction aux particuliers'],
      correct: 2, rationale: 'Faire un versement PER (déduction) profite énormément à un cadre taxé à 41%. Faire un don (réduction) fait économiser 66% du don à tout le monde, qu\'on soit riche ou modeste.' },
    { q: 'La case 2OP de la déclaration de revenus concerne le Prélèvement Forfaitaire Unique (PFU - Flat Tax) de 30 % sur les gains boursiers et dividendes. À quoi sert-elle ?',
      options: ['À opter pour l\'imposition au "Barème Progressif" de l\'IR. C\'est indispensable pour payer MOINS d\'impôts si l\'on est non imposable ou si notre TMI est faible (11 %)', 'À doubler les prélèvements sociaux', 'À annuler totalement l\'impôt', 'À accepter volontairement le PFU'],
      correct: 0, rationale: 'Sans cette case, le fisc prélèvera 30% d\'office, même à un étudiant non imposable ! Cocher cette case lui permet de ne payer que la part sociale (17,2%).' },
    { q: 'Vous avez de lourds frais kilométriques (trajet domicile-travail). Pour optimiser votre déclaration, que devez-vous faire ?',
      options: ['Refuser votre salaire', 'Ne rien faire, l\'administration calcule tout au mieux', 'Remplir la case des dons aux associations', 'Renoncer à l\'abattement forfaitaire de 10 % (appliqué par défaut) et déclarer le montant de vos "Frais Réels" calculés via le barème kilométrique'],
      correct: 3, rationale: 'Il faut toujours calculer ce qui est le plus avantageux. Si vos frais réels dépassent 10% de votre salaire, l\'option frais réels vous fera économiser beaucoup d\'impôts.' },
    { q: 'Un enfant majeur de 20 ans, étudiant, n\'a pas de revenus. Pour optimiser ses impôts, ses parents doivent-ils le détacher de leur foyer fiscal ?',
      options: ['Ils n\'ont pas le choix, c\'est obligatoire à 18 ans', 'L\'enfant doit s\'exiler fiscalement', 'Non, il est souvent plus avantageux de demander le "Rattachement" de l\'enfant majeur (jusqu\'à 21 ans, ou 25 ans si étudiant) pour conserver sa "demi-part fiscale" (ou part entière) et faire baisser l\'impôt global du foyer', 'Oui, pour toucher une prime de la CAF'],
      correct: 2, rationale: 'Diviser les revenus des parents par 2,5 ou 3 parts permet de redescendre dans des tranches d\'imposition beaucoup plus faibles.' },
    { q: 'Vous louez un appartement VIDE (nu) et encaissez 12 000 € de loyers/an. Vous avez fait 6 000 € de réparations de toiture. Allez-vous rester au régime "Micro-Foncier" (appliqué par défaut) ?',
      options: ['Non. Il faut opter pour le "Régime Réel", car les charges réelles (50% du loyer) sont très supérieures à l\'abattement automatique du Micro-foncier (30%), ce qui fera baisser massivement l\'impôt', 'Oui, car le Micro-foncier annule les impôts locaux', 'Oui, c\'est obligatoire en dessous de 15 000 € de loyers', 'L\'option dépend du maire'],
      correct: 0, rationale: 'Le choix du régime fiscal en immobilier est l\'un des plus puissants leviers d\'optimisation (création de déficit foncier).' },
    { q: 'Un contribuable s\'aperçoit en septembre qu\'il a oublié de déclarer son crédit d\'impôt pour garde d\'enfants au printemps. Est-ce trop tard ?',
      options: ['Oui, le fisc ne revient jamais en arrière', 'Non. Il dispose du "Droit à l\'erreur" et peut utiliser le service de "Correction en ligne" (ouvert d\'août à décembre) pour modifier sa déclaration validée', 'Oui, il paiera une amende de 150 €', 'Il doit poursuivre son comptable'],
      correct: 1, rationale: 'L\'administration fiscale a grandement facilité la rectification a posteriori pour éviter de pénaliser la bonne foi.' },
    { q: 'Que permet de faire un "Déficit Foncier" (des charges locatives supérieures aux loyers) issu de l\'immobilier nu au Régime Réel ?',
      options: ['Gommer les revenus GLOBAUX (comme le salaire) dans la limite de 10 700 € par an, générant une baisse massive de l\'impôt pour les cadres supérieurs', 'Annuler la TVA', 'Annuler la taxe foncière', 'Payer le syndic de copropriété avec l\'argent de l\'État'],
      correct: 0, rationale: 'L\'investisseur efface non seulement ses impôts immobiliers, mais réduit aussi ses impôts sur le travail.' },
    { q: 'Si l\'un de vos enfants a quitté le foyer fiscal, comment pouvez-vous optimiser vos impôts si vous l\'aidez financièrement tous les mois à payer son loyer ou ses études ?',
      options: ['L\'enfant doit vous embaucher', 'Vous pouvez déduire ces aides au titre de la "Pension alimentaire versée à un enfant majeur" (plafonnée à environ 6 500 €/an). Attention, l\'enfant devra les déclarer de son côté', 'Vous devez acheter une maison avec lui', 'C\'est interdit et considéré comme une fraude'],
      correct: 1, rationale: 'C\'est très souvent oublié. Plutôt que de le rattacher (ce qui est impossible après 25 ans), lui verser une pension permet aux parents de déduire plusieurs milliers d\'euros de leurs revenus imposables.' },
    { q: '(Challenge) Lors de la déclaration, comment pouvez-vous optimiser le "Plafond Épargne Retraite" pour faire un énorme versement déductible sur votre PER ?',
      options: ['Il suffit d\'emprunter à la consommation', 'En demandant un dépassement officiel à l\'URSSAF', 'L\'assurance vie permet d\'annuler le plafond', 'En utilisant la "Mutualisation des plafonds" (utiliser le plafond non consommé de son conjoint marié/pacsé) ET en rachetant ses propres "plafonds non utilisés des 3 années précédentes"'],
      correct: 3, rationale: 'C\'est la manœuvre absolue pour un chef d\'entreprise qui vient de faire une année record et qui veut effacer 30 000 ou 40 000 € de son revenu net imposable d\'un seul coup.' },
    { q: '(Challenge) Vous avez fait 15 000 € de dons à une association (taux 66%), ce qui vous ouvre droit à près de 10 000 € de réduction d\'impôt. Mais votre impôt calculé n\'est que de 3 000 €. Perdez-vous les 7 000 € de réduction restants ?',
      options: ['Non, le solde non utilisé l\'année du don est "reportable" sur vos impôts des 5 années suivantes', 'Oui, les réductions d\'impôts excédentaires sont toujours perdues', 'L\'association doit vous rendre l\'argent', 'L\'État vous fera un virement sur votre compte'],
      correct: 0, rationale: 'C\'est l\'un des rares cas où une réduction d\'impôt non consommée n\'est pas jetée à la poubelle. (À l\'inverse, l\'excédent d\'un crédit d\'impôt vous aurait été viré sur votre compte).' },
  ],
  'w26-d2': [
    { q: 'Dans le système de retraite français, la naissance et l\'éducation des enfants donnent-elles des droits supplémentaires pour la retraite des parents ?',
      options: ['Uniquement pour le père', 'Oui, le système offre des majorations de "Trimestres" (pour atteindre le taux plein) et parfois des majorations de "Montant" (une augmentation financière de la pension)', 'Seulement pour les familles très riches', 'Non, le système est strictement individuel'],
      correct: 1, rationale: 'Ces dispositifs compensent les carrières souvent freinées ou interrompues des parents (historiquement, les mères).' },
    { q: 'Dans le régime général (salariés), combien de trimestres sont classiquement accordés au titre de la naissance et de l\'éducation pour UN enfant (pour les enfants nés après 2010) ?',
      options: ['Jusqu\'à 8 trimestres par enfant (4 pour la maternité/adoption + 4 pour l\'éducation)', '1 trimestre par enfant', '20 trimestres par enfant', 'Aucun trimestre, c\'est juste un bonus financier'],
      correct: 0, rationale: 'Ces trimestres s\'ajoutent gratuitement à la durée d\'assurance de l\'assuré pour l\'aider à atteindre le taux plein plus vite.' },
    { q: 'Depuis 2010, à qui sont obligatoirement attribués les 4 trimestres liés à la MATERNITÉ (la grossesse/l\'accouchement) ?',
      options: ['Ils sont partagés 50/50 entre le père et la mère', 'Ils sont donnés au parent qui gagne le plus', 'Ils sont attribués EXCLUSIVEMENT à la mère biologique', 'Au père'],
      correct: 2, rationale: 'Ils compensent l\'impact physiologique de la grossesse. Le père biologique n\'y a jamais droit.' },
    { q: 'Qu\'en est-il des 4 autres trimestres liés à "l\'ÉDUCATION" de l\'enfant (pour les enfants nés après 2010) ?',
      options: ['Ils sont toujours exclusifs à la mère', 'Ils sont supprimés', 'Ils peuvent être partagés librement entre les deux parents (père/mère), à condition d\'en faire la déclaration officielle à la caisse de retraite dans un délai strict (souvent avant les 4 ans et demi de l\'enfant)', 'L\'État décide à la retraite'],
      correct: 2, rationale: 'Si les parents ne font pas le choix dans les temps, ces 4 trimestres d\'éducation sont, par défaut, attribués intégralement à la mère.' },
    { q: 'Qu\'est-ce que l\'AVPF (Assurance Vieillesse des Parents au Foyer) ?',
      options: ['Une assurance habitation pour les mères au foyer', 'Un dispositif de la CAF qui paie les cotisations retraite (et valide des trimestres) pour le parent qui réduit ou cesse son activité professionnelle pour élever un ou plusieurs enfants, sous conditions de ressources', 'La caisse de retraite des crèches', 'Une taxe sur les familles nombreuses'],
      correct: 1, rationale: 'C\'est une aide vitale. La mère (ou le père) qui prend un congé parental de 3 ans ne créera pas de "trou" dans sa carrière retraite, la CAF cotisant à sa place.' },
    { q: 'Au-delà des trimestres, il existe un formidable "Bonus Financier" pour les familles nombreuses. De quoi s\'agit-il ?',
      options: ['Une augmentation de 10 % du montant total de la pension de retraite pour les parents ayant eu ou élevé au moins 3 enfants', 'Le droit de prendre sa retraite à 50 ans', 'Un doublement de la retraite complémentaire', 'Une prime unique de 5 000 € au départ à la retraite'],
      correct: 0, rationale: 'Ce "bonus de 10 %" s\'applique sur la retraite de base de la mère ET du père. (L\'Agirc-Arrco propose également un bonus similaire de 10 % maximum).' },
    { q: 'Cette majoration financière de 10 % pour "3 enfants et plus" est-elle soumise à l\'Impôt sur le Revenu ?',
      options: ['Oui, depuis une réforme de 2014, cette majoration est réintégrée au revenu imposable du retraité (elle n\'est plus défiscalisée)', 'Uniquement si on a plus de 5 enfants', 'Non, elle est totalement nette d\'impôts à vie', 'Oui, taxée à 50 %'],
      correct: 0, rationale: 'L\'État a mis fin à cette niche fiscale historique pour renflouer les caisses. Ce bonus de 10% gonfle donc l\'impôt du retraité.' },
    { q: 'Les enfants ADOPTÉS ou RECUEILLIS (ex: les enfants du conjoint d\'un premier mariage) ouvrent-ils droit à la majoration de 10% pour les 3 enfants ?',
      options: ['Oui, s\'ils ont été élevés par le retraité et à sa charge pendant au moins 9 ans avant leur 16ème anniversaire', 'Uniquement s\'ils ont été adoptés avant 1 an', 'Non, seuls les enfants biologiques comptent', 'La majoration est divisée par deux'],
      correct: 0, rationale: 'La loi valorise "l\'éducation" et la charge financière autant que le lien du sang.' },
    { q: '(Challenge) Quelle "Surcote" (bonus) inédite la réforme des retraites de 2023 a-t-il créée spécifiquement pour les mères de famille ?',
      options: ['Si la mère atteint les trimestres requis (taux plein) à 63 ans grâce à ses "trimestres enfants", elle bénéficiera d\'une "surcote parentale" anticipée (jusqu\'à +5 % sur sa pension) pour l\'année travaillée jusqu\'à l\'âge légal (64 ans)', 'L\'annulation de la CSG', 'Un trimestre offert pour le premier petit-enfant', 'Une rente viagère gratuite payée par l\'hôpital'],
      correct: 0, rationale: 'Le gouvernement a été accusé de pénaliser les mères avec le recul de l\'âge légal à 64 ans (car beaucoup avaient déjà leurs trimestres à 62 ans grâce aux enfants). Cette surcote vise à compenser cet effet.' },
    { q: '(Challenge) Un assuré n\'a pas atteint la durée d\'assurance requise et subit une "Décote". Le "bonus familial de 10 % pour 3 enfants" se calcule-t-il AVANT ou APRÈS l\'application de la décote ?',
      options: ['La décote annule le bonus enfant', 'Il se calcule sur la pension BRUTE de base', 'Le bonus est un forfait fixe', 'Il se calcule APRÈS. La pension est d\'abord minorée par la décote, et c\'est sur ce montant raboté que l\'on applique les +10 %'],
      correct: 3, rationale: 'L\'ordre des calculs est strict. Les majorations familiales s\'appliquent toujours tout à la fin du calcul, sur la pension définitive (minoration incluse).' },
  ],
  'w26-d3': [
    { q: 'Qu\'est-ce qu\'un testament "olographe" (le plus courant en France) ?',
      options: ['Un testament enregistré en vidéo (smartphone)', 'Un testament rédigé entièrement à la main, daté et signé par le testateur (celui qui rédige), sans l\'intervention obligatoire d\'un notaire lors de la rédaction', 'Un testament tapé à l\'ordinateur et imprimé', 'Un document verbal devant trois témoins'],
      correct: 1, rationale: 'C\'est la forme la plus simple, la plus secrète et la moins coûteuse (gratuite).' },
    { q: 'Quelle est la conséquence d\'un testament "olographe" qui serait tapé à l\'ordinateur, même s\'il est daté et signé au stylo ?',
      options: ['Il est parfaitement valable', 'Il perd sa valeur pour l\'immobilier', 'Il n\'est valable que s\'il fait moins d\'une page', 'Il est frappé de nullité absolue. L\'écriture manuscrite (de la main) de l\'intégralité du texte est une condition "ad validitatem" (vitale)'],
      correct: 3, rationale: 'L\'écriture manuscrite est le seul moyen pour le juge de vérifier que c\'est bien la personne elle-même qui a rédigé le document (expertise graphologique), sans contrainte.' },
    { q: 'Quel est l\'inconvénient majeur du testament olographe conservé chez soi (dans un tiroir ou un livre) ?',
      options: ['Il expire au bout de 5 ans', 'Il est lourdement taxé', 'Le risque de perte, de destruction (incendie) ou de dissimulation malveillante par un héritier lésé qui le trouverait en premier après le décès', 'La mairie l\'invalide'],
      correct: 2, rationale: 'C\'est le drame de nombreux testaments cachés. S\'il n\'est pas trouvé, ce sont les règles légales par défaut qui s\'appliqueront, ruinant les volontés du défunt.' },
    { q: 'Qu\'est-ce qu\'un testament "authentique" ?',
      options: ['Un testament vérifié par la gendarmerie', 'Le vrai testament (le premier), par opposition aux copies', 'Un testament rédigé sur du papier timbré', 'Un testament DICTÉ par le testateur à un notaire, en présence de deux témoins (ou d\'un deuxième notaire), qui le lit à voix haute avant signature'],
      correct: 3, rationale: 'C\'est le testament "blindé". Le notaire s\'assure que la personne a toute sa tête, n\'est pas sous la menace, et que le vocabulaire juridique utilisé est parfait.' },
    { q: 'Quel est l\'inconvénient principal du testament authentique ?',
      options: ['Il est nul en cas de déménagement', 'Il coûte de l\'argent (frais de notaire) et son formalisme est lourd (présence de témoins, impossibilité de garder le contenu totalement secret lors de la rédaction)', 'On ne peut pas le modifier', 'Il ne s\'applique qu\'aux riches'],
      correct: 1, rationale: 'Payer une centaine d\'euros et devoir expliquer ses choix devant des témoins rebute certaines personnes préférant la confidentialité du testament olographe.' },
    { q: 'Comment éviter de perdre un testament "olographe" (manuscrit) tout en gardant sa simplicité ?',
      options: ['L\'envoyer à sa banque', 'L\'enterrer dans le jardin', 'Le rédiger chez soi, puis le confier à un notaire qui le gardera dans son coffre-fort et l\'inscrira au FCDDV (Fichier Central des Dispositions de Dernières Volontés)', 'Le poster sur Facebook'],
      correct: 2, rationale: 'Moyennant un coût dérisoire (~30€), le notaire enregistre l\'existence de votre testament. Au décès, N\'IMPORTE QUEL notaire interrogeant le fichier national saura où il est rangé.' },
    { q: 'Si une personne rédige plusieurs testaments olographes au fil des années, lequel sera appliqué à son décès ?',
      options: ['Tous s\'appliquent en même temps', 'Seul le premier (le plus ancien) est valable', 'Le plus long', 'C\'est le plus RÉCENT (le dernier en date) qui prévaut. Il annule toutes les dispositions contraires des testaments précédents'],
      correct: 3, rationale: 'Un testament est une volonté "jusqu\'à la mort". On peut changer d\'avis 100 fois. C\'est pour cela que la DATE (jour/mois/année) est obligatoire sur le document.' },
    { q: 'En droit français, a-t-on le droit de faire un testament pour léguer tout son argent à un ami, en déshéritant totalement ses enfants ?',
      options: ['Oui, le testament a une valeur supérieure à la loi', 'Non. Les enfants sont des héritiers "réservataires". Le testament ne peut porter QUE sur la "Quotité Disponible" (la part libre du patrimoine). Le testament sera réduit pour restituer leur réserve aux enfants', 'Uniquement s\'ils sont majeurs', 'Oui, si c\'est un testament authentique'],
      correct: 1, rationale: 'Contrairement au droit anglo-saxon, le droit français interdit de déshériter ses enfants.' },
    { q: '(Challenge) Un homme séparé de fait (mais non divorcé) veut priver sa femme de son fameux "Droit viager au logement" (le droit d\'occuper la maison jusqu\'à sa mort). Quel type de testament est OBLIGATOIREMENT exigé par la loi pour cet acte d\'une gravité extrême ?',
      options: ['Un testament olographe très précis', 'Le testament authentique (devant notaire). Un simple testament olographe n\'a aucune valeur pour priver le conjoint de ce droit d\'ordre public', 'Un testament mystique', 'Le juge doit signer'],
      correct: 1, rationale: 'C\'est la protection ultime du conjoint. Il faut la lourde solennité du notaire et des témoins pour qu\'un époux puisse mettre sa femme "à la rue" post-mortem.' },
    { q: '(Challenge) Il existe un 3ème type de testament, le "Testament Mystique". De quoi s\'agit-il ?',
      options: ['Un testament religieux', 'Un document verbal', 'Un acte de magie', 'Le testateur remet un document CLOS, CACHETÉ et SCELLÉ à un notaire en présence de 2 témoins, en affirmant que c\'est son testament. Personne (pas même le notaire) ne connaît son contenu avant le décès'],
      correct: 3, rationale: 'Ce format, rarissime, combine la sécurité de conservation du notaire avec le secret le plus absolu du testament olographe.' },
  ],
  'w26-d4': [
    { q: 'Lors de la souscription d\'un crédit immobilier à DEUX (ex : un couple), qu\'appelle-t-on la "Quotité" d\'assurance emprunteur ?',
      options: ['La marge de négociation de l\'agence', 'La répartition du pourcentage de couverture d\'assurance (du capital emprunté) sur la "tête" de chaque co-emprunteur', 'Le prix mensuel de l\'assurance', 'Le taux d\'intérêt de la banque'],
      correct: 1, rationale: 'L\'assurance va couvrir le remboursement du prêt en cas de décès/invalidité. La quotité définit QUELLE PART de la dette sera effacée si l\'un des deux disparaît.' },
    { q: 'Quelle est la quotité d\'assurance GLOBALE (l\'addition des deux têtes) MINIMALE systématiquement exigée par la banque pour valider le prêt ?',
      options: ['100 % (la totalité du crédit doit être couverte)', '50 %', '200 %', '0 % si les revenus sont bons'],
      correct: 0, rationale: 'La banque veut la garantie que si les deux emprunteurs décèdent dans un accident de voiture, la totalité de sa créance lui sera remboursée par l\'assureur.' },
    { q: 'Un couple choisit une répartition classique "50 / 50" (couverture globale = 100 %). Que se passe-t-il si l\'emprunteur A décède ?',
      options: ['L\'assurance rembourse 100 % du crédit', 'La banque annule le crédit', 'La banque saisit la maison', 'L\'assurance rembourse 50 % du capital restant dû à la banque. L\'emprunteur B (survivant) devra continuer à rembourser seul la moitié de la mensualité restante'],
      correct: 3, rationale: 'Le conjoint survivant voit sa charge divisée par deux, mais il a perdu le salaire de son conjoint pour l\'aider.' },
    { q: 'Un couple choisit une répartition "100 / 100" (couverture globale = 200 %). Que se passe-t-il si l\'emprunteur A décède ?',
      options: ['Le survivant est poursuivi', 'L\'assurance rembourse INTÉGRALEMENT (100 %) le crédit à la banque. Le survivant garde la maison totalement payée et n\'a plus aucune mensualité de crédit à verser', 'La banque gagne le double', 'L\'assurance rembourse la moitié'],
      correct: 1, rationale: 'C\'est la protection "confort" et prévoyance maximale. Au drame du décès ne s\'ajoute pas le stress du crédit.' },
    { q: 'Quel est l\'inconvénient (le coût) du choix "100 / 100" (couverture à 200 %) ?',
      options: ['La banque refuse de prêter', 'C\'est illégal', 'Les impôts doublent', 'Il faut payer DEUX cotisations d\'assurance complètes (le coût de l\'assurance est logiquement deux fois plus cher qu\'une couverture à 50/50)'],
      correct: 3, rationale: 'Vous couvrez le double du risque pour la banque, vous payez donc deux fois l\'assureur.' },
    { q: 'Un couple a des revenus très déséquilibrés : Madame gagne 4 000 € (70% des revenus) et Monsieur gagne 1 500 € (30%). Ils veulent une couverture à 100 % globale pour payer moins cher. Quel est le choix de quotité le plus intelligent (sur mesure) ?',
      options: ['100% sur Monsieur et 0% sur Madame', 'Répartir la couverture sur leurs "poids financiers" : 70 % sur Madame et 30 % sur Monsieur', 'Ne pas prendre d\'assurance', 'Obligatoirement 50 / 50'],
      correct: 1, rationale: 'Si Madame meurt, l\'assurance rembourse 70% de la maison. Il ne restera que 30% de la mensualité à la charge de Monsieur, ce qu\'il pourra payer avec son petit salaire de 1500€.' },
    { q: 'Vous achetez une résidence principale. Pouvez-vous "imposer" une couverture 50 / 50 à votre banquier ?',
      options: ['La loi interdit le 50 / 50', 'Oui, le client décide toujours', 'Seulement pour les prêts sur 10 ans', 'Non. Si le banquier juge qu\'un des deux conjoints gagne très peu (ou si un seul travaille), il EXIGERA une couverture à 100 % sur la tête de celui qui amène le revenu principal (voire 100/100) pour sécuriser le prêt'],
      correct: 3, rationale: 'L\'assurance est la garantie de la banque. Si le seul qui ramène un salaire décède et n\'était couvert qu\'à 50%, la banque sait pertinemment que le conjoint sans revenu ne pourra jamais payer la moitié restante.' },
    { q: 'Les quotités (ex: 50 / 50) s\'appliquent en cas de décès, mais elles s\'appliquent aussi à d\'autres garanties cruciales. Lesquelles ?',
      options: ['Les garanties "Bris de glace"', 'L\'invalidité et l\'incapacité de travail (arrêts maladie). (Si un emprunteur est en arrêt longue maladie, l\'assurance ne prendra en charge que 50% de la mensualité du crédit)', 'Le risque de chômage uniquement', 'Les dégâts des eaux'],
      correct: 1, rationale: 'Le conjoint en bonne santé devra payer l\'autre moitié de la mensualité, alors même que le conjoint malade a perdu une partie de son salaire ! (D\'où l\'importance de bien réfléchir à ces quotités).' },
    { q: '(Challenge) Lors d\'une "Délégation d\'assurance" externe (Loi Lemoine), vous quittez la banque qui vous avait assuré à 100 / 100 pour aller chez un concurrent moins cher. Avez-vous le droit de redescendre votre couverture à 50 / 50 chez le nouvel assureur ?',
      options: ['L\'État s\'en fiche', 'Oui, car on change de contrat', 'Non. La loi exige un "Niveau de Garantie Équivalent". Le nouveau contrat devra respecter EXACTEMENT la même quotité d\'assurance globale (200 %) qui était exigée par la banque dans son offre de prêt initiale', 'Uniquement avec l\'accord de la Mairie'],
      correct: 2, rationale: 'La banque refusera la délégation si vous dégradez la protection financière qu\'elle avait exigée.' },
    { q: '(Challenge) Un couple assuré à 100 / 100 (deux cotisations complètes) voit ses revenus chuter suite à une perte d\'emploi. L\'assurance coûte trop cher. Peuvent-ils modifier les quotités de leur prêt en cours pour passer à 50 / 50 ?',
      options: ['Oui, par simple e-mail', 'Oui, MAIS cela nécessite un "Avenant" au contrat de crédit et l\'ACCORD formel de la banque. La banque va réétudier le dossier financier et peut tout à fait refuser de diminuer ses garanties', 'C\'est interdit, la prison est risquée', 'Non, le contrat est gravé dans le marbre'],
      correct: 1, rationale: 'Vous ne pouvez pas baisser la couverture de la banque unilatéralement. C\'est une négociation de gré à gré (parfois acceptée si l\'encours du crédit a beaucoup baissé).' },
  ],
  'w26-d5': [
    { q: 'Dans une copropriété, qu\'est-ce que l\'Assemblée Générale (AG) ?',
      options: ['L\'organe "souverain" (le parlement) de la copropriété, où tous les propriétaires se réunissent pour voter les décisions importantes de l\'immeuble (budget, travaux, choix du syndic)', 'Une fête des voisins obligatoire', 'Le syndicat de défense des locataires', 'La réunion de la Mairie pour les impôts'],
      correct: 0, rationale: 'C\'est le pouvoir législatif. Le Syndic n\'est que l\'exécutant de ce qui est décidé (voté) lors de cette AG.' },
    { q: 'Quelle est la fréquence MINIMALE obligatoire de tenue de l\'Assemblée Générale ordinaire ?',
      options: ['Au moins une fois par AN', 'Une fois par mois', 'Tous les 3 ans', 'Seulement quand il y a des travaux'],
      correct: 0, rationale: 'La loi impose ce rendez-vous annuel pour approuver les comptes de l\'année passée et voter le budget de l\'année à venir.' },
    { q: 'Combien de temps AVANT la tenue de la réunion les copropriétaires doivent-ils recevoir la convocation (et les devis des travaux à voter) ?',
      options: ['Au moins 21 JOURS francs avant la date de l\'AG', 'La veille', '3 mois', '5 jours'],
      correct: 0, rationale: 'Ce délai d\'ordre public laisse le temps aux propriétaires d\'étudier les comptes et les devis très complexes avant de voter (sauf AG d\'urgence absolue).' },
    { q: 'Un propriétaire possède un tout petit studio de 10m², et un autre possède un grand T5 de 150m². Comment leurs votes "pèsent-ils" lors de l\'AG ?',
      options: ['Chaque propriétaire a exactement "1 voix" (1 homme = 1 vote)', 'Seuls les propriétaires y habitant ont le droit de vote', 'Leurs votes pèsent proportionnellement au nombre de "tantièmes/millièmes" détenus (liés à la taille/valeur de leur lot). Le T5 aura un poids de vote beaucoup plus lourd que le studio', 'Le syndic décide pour eux'],
      correct: 2, rationale: 'C\'est un vote censitaire : vous votez à hauteur de ce que vous payez dans les charges de l\'immeuble.' },
    { q: 'Pour les décisions de "gestion courante" (approuver les comptes, voter le budget prévisionnel), quelle majorité (dite de l\'Article 24) est requise ?',
      options: ['L\'unanimité de tout l\'immeuble (100 %)', 'L\'accord exclusif du président', 'La majorité absolue de tous les copropriétaires', 'La majorité "simple" : majorité des voix des copropriétaires PRÉSENTS ou REPRÉSENTÉS le jour de l\'AG (les absents ne bloquent pas le vote)'],
      correct: 3, rationale: 'C\'est la majorité la plus facile à obtenir, car on ne compte pas les absentéistes qui paralyseraient sinon le fonctionnement quotidien de l\'immeuble.' },
    { q: 'Pour des décisions plus lourdes (ex: désigner un nouveau syndic, faire des travaux d\'amélioration énergétique, installer un portail), la loi exige la "Majorité Absolue" (Article 25). Qu\'est-ce que cela signifie ?',
      options: ['La majorité des voix de la MOITIÉ PLUS UN de la totalité des propriétaires de l\'immeuble (qu\'ils soient présents, représentés, ou ABSENTS lors de l\'AG)', 'L\'accord du juge du tribunal', '100 % des voix', 'La majorité des présents'],
      correct: 0, rationale: 'Ici, les absents "comptent" techniquement comme des "Non". Cette majorité est donc beaucoup plus difficile à réunir.' },
    { q: 'Un propriétaire vit très loin et ne peut pas venir à l\'AG. Que peut-il faire ?',
      options: ['Son vote est compté comme "Oui" d\'office', 'Il perd son appartement', 'Donner un "Pouvoir" (mandat) à une autre personne de son choix (un voisin, ou même un tiers) pour voter à sa place', 'Envoyer un SMS au syndic le jour J'],
      correct: 2, rationale: 'Ce "vote par procuration" est la clé de la vie en copropriété pour atteindre les majorités absolues malgré l\'absentéisme.' },
    { q: 'Qui OBLIGATION de convoquer l\'Assemblée Générale Ordinaire ?',
      options: ['La police', 'L\'artisan du chantier', 'Le Syndic de copropriété', 'Le locataire du rez-de-chaussée'],
      correct: 2, rationale: 'C\'est son devoir légal de tenir le registre, d\'envoyer les recommandés, et de faire le secrétariat lors de la réunion.' },
    { q: '(Challenge) Lors d\'un vote important nécessitant la "Majorité Absolue" (Art. 25, comme les travaux d\'isolation), les copropriétaires présents votent "Oui" mais, à cause des nombreux absents, on n\'atteint pas la barre des 50% de la totalité de l\'immeuble. Tout est bloqué ?',
      options: ['Non. Le mécanisme de la "passerelle" (Art. 25-1) permet de refaire le vote IMMÉDIATEMENT à la majorité "simple" (Art. 24) si le premier vote a quand même réuni au moins un tiers (1/3) des voix de l\'immeuble', 'Oui, les travaux sont annulés à vie', 'L\'immeuble est mis sous tutelle de l\'État', 'La mairie paie la différence'],
      correct: 0, rationale: 'C\'est un mécanisme juridique vital inventé pour lutter contre la paralysie des copropriétés causée par l\'absentéisme chronique (les fameux immeubles qui tombent en ruine).' },
    { q: '(Challenge) L\'AG vote une décision qui vous semble totalement illégale ou abusive (ex: on vous interdit de louer à des étudiants). Quel est votre recours ?',
      options: ['Ne plus payer vos charges', 'Casser les boîtes aux lettres', 'Refuser d\'appliquer la décision sans rien faire', 'En tant que propriétaire "Opposant" ou "Défaillant" (absent), vous disposez d\'un délai strict de 2 MOIS (à compter de la notification du procès-verbal) pour contester et demander l\'annulation de la décision devant le Tribunal Judiciaire'],
      correct: 3, rationale: 'Une décision d\'AG n\'est JAMAIS suspendue si vous arrêtez de payer. Elle s\'impose à tous. La seule façon de l\'annuler est de saisir la justice civile dans ce délai ultra-court de 2 mois. Retour STEPH : les Avis ca fait trop fake, et c’est peut etre un peu tot ? mieux vaut tester le concept et avoir des avis de proches ? Logo : le logo on peut garder la fusée mais il faudrait le refaire (éviter les degradé c\'est galère si demain on fait des plaquettes de communication ou autre version imprimable) Compte Google a créer pour le référencement + fiche google ? Juridique : RGPD / SIRET' },
  ],
};
