/* Questions de la semaine 20. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w20-d0': [
    { q: 'En finance, à quoi correspond le "Private Equity" (Capital-Investissement) ?',
      options: ['Acheter des actions de grandes entreprises du CAC 40', 'Prêter de l\'argent à des banques centrales', 'Investir au capital d\'entreprises qui ne sont PAS cotées en bourse (PME, ETI)', 'Acheter des obligations d\'État'],
      correct: 2, rationale: 'Le Private Equity finance l\'économie réelle en apportant des capitaux propres à des entreprises privées pour accélérer leur développement, en dehors des marchés financiers publics.' },
    { q: 'Au sein du non-coté, qu\'est-ce que le "Capital-Risque" (Venture Capital / VC) ?',
      options: ['Le rachat d\'entreprises en faillite', 'L\'investissement dans de jeunes start-ups innovantes à très fort potentiel de croissance (et très fort risque)', 'Un prêt garanti par l\'État', 'L\'investissement exclusif dans l\'immobilier d\'entreprise'],
      correct: 1, rationale: 'L\'investisseur (le VC) parie sur des entreprises émergentes. 8 sur 10 feront faillite, mais les 2 qui réussissent (les "licornes") compenseront largement les pertes.' },
    { q: 'Quel est le principal DEFAUT (contrainte) du Private Equity pour l\'investisseur ?',
      options: ['C\'est un actif extrêmement "illiquide" : les fonds sont bloqués pendant une très longue période (souvent 5 à 10 ans) avant de pouvoir revendre ses parts', 'Il verse des dividendes trop élevés', 'Il est interdit en France', 'L\'État prélève 80 % de la plus-value'],
      correct: 0, rationale: 'L\'entreprise a besoin de temps pour se développer avant d\'être revendue. Vous ne pouvez pas récupérer votre argent en un clic comme en bourse.' },
    { q: 'Quel est le niveau de risque du capital-investissement (Private Equity) ?',
      options: ['Risque nul, garanti par la Banque de France', 'Risque très faible, comme le Livret A', 'Risque modéré', 'Risque très élevé (risque de perte en capital totale ou partielle)'],
      correct: 3, rationale: 'Une PME ou une start-up non cotée est beaucoup plus fragile qu\'une multinationale. La faillite entraîne la perte de 100% de la somme investie.' },
    { q: 'Face à cette illiquidité et ce risque élevé, que doit mathématiquement offrir le Private Equity pour attirer les investisseurs ?',
      options: ['Des places gratuites pour les conseils d\'administration', 'Une "Prime d\'illiquidité" : une promesse de rendement (TRI) beaucoup plus élevé que la bourse traditionnelle (souvent ciblé entre 10 et 15 % par an)', 'Le remboursement des frais de notaire', 'Un prêt à taux zéro'],
      correct: 1, rationale: 'L\'investisseur exige d\'être grassement rémunéré pour accepter de bloquer son argent 10 ans sur un projet risqué.' },
    { q: 'Comment un particulier peut-il investir facilement dans le non-coté sans avoir des millions d\'euros ?',
      options: ['En achetant des actions Apple', 'En ouvrant un compte courant', 'Via des fonds spécialisés (FCPR, FIP, FCPI), des plateformes de crowdfunding en equity, ou via l\'Assurance-Vie/PER (loi Pacte)', 'En allant au guichet de la mairie'],
      correct: 2, rationale: 'Ces fonds collectent l\'épargne de milliers de particuliers pour investir dans un panier diversifié de dizaines d\'entreprises non cotées, diluant ainsi le risque.' },
    { q: 'Quel avantage fiscal massif l\'État offre-t-il souvent pour inciter les Français à investir dans les FIP (Fonds d\'Investissement de Proximité) ou FCPI (Fonds Communs de Placement dans l\'Innovation) ?',
      options: ['Une forte réduction d\'impôt sur le revenu (souvent 18 à 25 % du montant investi) accordée l\'année de l\'investissement', 'L\'annulation de la taxe foncière', 'Le droit de ne pas payer la TVA', 'Un chèque direct de la CAF'],
      correct: 0, rationale: 'Cet avantage fiscal est la "carotte" pour convaincre les particuliers de prendre le risque d\'injecter de l\'argent dans les jeunes PME françaises.' },
    { q: 'Dans le jargon de la création d\'entreprise, qu\'appelle-t-on la "Love Money" ?',
      options: ['Le budget pour le pot de départ', 'Les prêts des banques d\'affaires', 'Les subventions européennes', 'Les tout premiers fonds levés par l\'entrepreneur auprès de sa famille et de ses amis (qui investissent par amour/confiance plus que par pur calcul financier)'],
      correct: 3, rationale: 'C\'est la toute première étape du non-coté (l\'amorçage), avant même l\'intervention des "Business Angels" et des fonds d\'investissement.' },
    { q: '(Challenge) Qu\'est-ce que le LBO (Leveraged Buy-Out), la technique reine des grands fonds de Private Equity ?',
      options: ['Une faillite volontaire', 'Le rachat d\'une entreprise saine en utilisant un maximum de dette (emprunt bancaire). Les bénéfices de la cible serviront à rembourser cette dette, démultipliant ainsi la rentabilité du fonds', 'L\'introduction de l\'entreprise en bourse', 'L\'investissement 100 % en fonds propres'],
      correct: 1, rationale: 'Le fonds apporte peu de capital, emprunte beaucoup, et se sert de la trésorerie de l\'entreprise rachetée pour payer le crédit. La plus-value à la revente est décuplée.' },
    { q: '(Challenge) Historiquement réservé aux institutionnels (minimum 100 000 € d\'entrée), que s\'est-il passé récemment pour la "Démocratisation" du Private Equity en France ?',
      options: ['Il est devenu un placement public d\'État', 'Il a été interdit aux particuliers', 'La loi PACTE et des acteurs comme Bpifrance ont permis la création de fonds accessibles dès quelques centaines ou milliers d\'euros, logeables dans une assurance-vie avec une liquidité partiellement assurée', 'Il est devenu gratuit'],
      correct: 2, rationale: 'L\'objectif est d\'orienter l\'énorme épargne dormante des Français vers l\'économie productive des PME non cotées.' },
  ],
  'w20-d1': [
    { q: 'Comment s\'appelle le principal dispositif (la prime) de l\'État qui a remplacé le CITE (Crédit d\'Impôt pour la Transition Énergétique) ?',
      options: ['Action Logement', 'MaPrimeRénov\'', 'Le chèque énergie', 'La prime de Noël'],
      correct: 1, rationale: 'C\'est le dispositif phare de l\'Agence Nationale de l\'Habitat (Anah) pour financer les travaux de rénovation (isolation, pompes à chaleur, poêles).' },
    { q: 'À quels propriétaires le dispositif MaPrimeRénov\' s\'adresse-t-il ?',
      options: ['Uniquement aux propriétaires bailleurs', 'Seulement aux locataires', 'Uniquement aux résidences secondaires', 'À tous les propriétaires (occupants, bailleurs et copropriétaires), mais le montant de l\'aide varie fortement en fonction de leurs niveaux de revenus (tranches de couleurs)'],
      correct: 3, rationale: 'Depuis 2021, tous les propriétaires y ont droit, mais les ménages très modestes (Bleu) toucheront beaucoup plus d\'aides que les ménages aisés (Rose).' },
    { q: 'Quel document officiel, noté de A à G, est devenu central (et souvent obligatoire) pour cibler et obtenir les aides à la rénovation ?',
      options: ['Le Diagnostic de Performance Énergétique (DPE)', 'L\'état des risques naturels', 'Le permis de construire', 'Le devis du banquier'],
      correct: 0, rationale: 'Le DPE cartographie la perte d\'énergie de la maison. Les aides massives sont désormais conditionnées à un gain "global" de plusieurs classes (ex : passer de F à D).' },
    { q: 'Pour bénéficier des aides de l\'État (MaPrimeRénov\', CEE), il y a une obligation stricte concernant l\'entreprise qui réalise les travaux. Laquelle ?',
      options: ['Elle doit avoir plus de 50 salariés', 'Elle doit être étrangère', 'L\'artisan doit obligatoirement détenir le label RGE ("Reconnu Garant de l\'Environnement") à la date d\'acceptation du devis', 'L\'entreprise doit être gérée par la mairie'],
      correct: 2, rationale: 'C\'est la condition sine qua non. Un devis fait par un artisan non-RGE vous exclut de la totalité des aides écologiques de l\'État.' },
    { q: 'Qu\'est-ce que la prime des CEE (Certificats d\'Économies d\'Énergie) ?',
      options: ['Une taxe sur l\'essence', 'Une aide financière versée directement par les "pollueurs" (fournisseurs d\'énergie et de carburant comme EDF, Total, Leclerc) qui y sont obligés par l\'État sous peine d\'amendes', 'Une aide de l\'Union Européenne', 'Un prêt à taux zéro'],
      correct: 1, rationale: 'Les gros pollueurs rachètent leurs "fautes" en finançant vos travaux d\'isolation (la fameuse "Prime Énergie" ou "Coup de pouce"). Elle est cumulable avec MaPrimeRénov\'.' },
    { q: 'Face aux "Passoires thermiques" (les logements notés F et G au DPE), quelle interdiction radicale l\'État met-il progressivement en place (Loi Climat et Résilience) ?',
      options: ['L\'interdiction (progressive) de louer ces biens immobiliers ("gel" des loyers, puis indécence du logement)', 'L\'interdiction d\'y dormir', 'La confiscation par la mairie', 'L\'interdiction de les vendre'],
      correct: 0, rationale: 'C\'est le grand stress des propriétaires bailleurs. Un bien classé G (2025) ou F (2028) ne pourra plus être mis sur le marché locatif sans lourds travaux de rénovation.' },
    { q: 'En matière de TVA, quel avantage fiscal direct s\'applique sur les travaux de rénovation de performance énergétique ?',
      options: ['La TVA passe de 20 % à 10 %', 'La TVA est supprimée (0 %)', 'L\'artisan paie la TVA à votre place', 'Une TVA à taux très réduit de 5,5 % s\'applique directement sur la facture de l\'artisan (matériel et main d\'œuvre)'],
      correct: 3, rationale: 'Dès que les travaux touchent à l\'économie d\'énergie (ex: chaudière à granulés, isolation des combles), la facture globale est allégée par ce taux réduit (au lieu des 10 % de la rénovation classique ou des 20 % du neuf).' },
    { q: 'Comment s\'appelle le prêt bancaire (dont les intérêts sont payés par l\'État) destiné à financer le "reste à charge" des travaux d\'économie d\'énergie ?',
      options: ['Le prêt étudiant', 'L\'éco-PTZ (Éco-Prêt à Taux Zéro), qui peut aller jusqu\'à 50 000 € pour les rénovations globales', 'Le crédit revolving vert', 'Le prêt relais'],
      correct: 1, rationale: 'Il se cumule avec les aides (MaPrimeRénov\', CEE) pour permettre aux ménages de faire les travaux sans avoir d\'épargne.' },
    { q: '(Challenge) Qu\'est-ce que le dispositif "Mon Accompagnateur Rénov\'" devenu obligatoire ?',
      options: ['Un contrôleur fiscal qui visite la maison', 'Un ami qui vous aide à peindre', 'Un professionnel agréé par l\'État dont l\'accompagnement (audit, aide aux devis et aux aides) est OBLIGATOIRE pour obtenir MaPrimeRénov\' Parcours Accompagné (les rénovations globales importantes)', 'Un site internet pour choisir ses meubles'],
      correct: 2, rationale: 'L\'État veut sécuriser les aides massives (jusqu\'à 90% du chantier financé) en imposant un "tiers de confiance" neutre pour éviter les arnaques.' },
    { q: '(Challenge) En régime réel (location nue), les dépenses d\'amélioration énergétique sont déductibles et créent du "Déficit Foncier" (imputable sur le salaire). Temporairement (jusqu\'en 2025), quel avantage spécifique a été voté pour les passoires thermiques ?',
      options: ['Le plafond d\'imputation sur le revenu global a été exceptionnellement doublé (de 10 700 € à 21 400 € par an) pour inciter les bailleurs à faire de lourds travaux de rénovation énergétique', 'Le déficit foncier est supprimé', 'Les impôts sont remboursés par chèque', 'L\'État multiplie par trois la facture de l\'artisan'],
      correct: 0, rationale: 'Un propriétaire fortement imposé qui rénove sa passoire thermique peut ainsi faire baisser massivement son impôt sur son salaire.' },
  ],
  'w20-d2': [
    { q: 'Dans l\'architecture de l\'épargne retraite (Loi PACTE), qu\'est-ce que le "PER Obligatoire" (PERO) ?',
      options: ['Une assurance vie imposée par la banque', 'L\'obligation de cotiser à la Sécurité Sociale', 'Le successeur de l\'ancien "Article 83" : un plan de retraite souscrit par l\'entreprise, avec une affiliation OBLIGATOIRE pour tous les salariés (ou une catégorie précise de salariés, ex: les cadres)', 'Le PER Individuel'],
      correct: 2, rationale: 'L\'entreprise met en place ce contrat comme un "plus" social (rémunération différée). Le salarié visé ne peut pas le refuser.' },
    { q: 'Qui alimente PRINCIPALEMENT le "Compartiment 3" (le cœur) de ce PER Obligatoire ?',
      options: ['Les dons des syndicats', 'L\'employeur, via des cotisations obligatoires prélevées tous les mois (dont une partie peut aussi être à la charge du salarié sur sa fiche de paie)', 'Le salarié avec ses économies personnelles', 'L\'État'],
      correct: 1, rationale: 'L\'entreprise "force" l\'épargne retraite. Elle verse par exemple 3 % du salaire brut chaque mois sur ce compte bloqué.' },
    { q: 'Arrivé à la retraite, comment le salarié récupère-t-il obligatoirement l\'argent issu de ces cotisations patronales (le Compartiment 3 du PERO) ?',
      options: ['En actions de l\'entreprise', 'Sous forme de cryptomonnaie', 'En capital, versé en une seule fois', 'STRICTEMENT sous forme de Rente Viagère (un revenu versé tous les mois jusqu\'au décès). La sortie en capital est interdite pour ce compartiment (sauf micro-rentes)'],
      correct: 3, rationale: 'Contrairement au PER Individuel où le choix est libre, l\'argent "forcé" par l\'entreprise est destiné exclusivement à garantir un revenu à vie.' },
    { q: 'Un salarié ayant un PER Obligatoire peut-il effectuer des "Versements Volontaires" (de son propre compte en banque) dessus ?',
      options: ['Non, c\'est interdit', 'Oui (Compartiment 1). Il bénéficiera alors de la même déductibilité fiscale sur son impôt sur le revenu que s\'il avait un PER Individuel', 'Uniquement à l\'ouverture du compte', 'Oui, mais les versements sont plafonnés à 100 €'],
      correct: 1, rationale: 'Un PERO est un contrat "3 en 1". Il accueille la part obligatoire du patron, mais peut aussi servir de PER personnel et défiscalisant pour le salarié.' },
    { q: 'Le salarié quitte son entreprise (démission, licenciement). Que devient son PER Obligatoire ?',
      options: ['Il est bloqué à vie dans l\'ancienne entreprise', 'L\'employeur récupère les fonds', 'Le salarié peut (et a fortement intérêt à) le TRANSFÉRER vers le PER Obligatoire de son nouvel employeur, ou vers son PER Individuel (PERin), pour éviter la multiplication des petits contrats dormants', 'Le compte est détruit'],
      correct: 2, rationale: 'La portabilité est le grand apport de la loi PACTE. L\'épargne retraite suit le travailleur.' },
    { q: 'Peut-on débloquer de manière anticipée la "part obligatoire" (Compartiment 3) du PERO pour ACHETER SA RÉSIDENCE PRINCIPALE ?',
      options: ['Uniquement pour une maison neuve', 'Oui, comme pour tous les PER', 'Oui, si le conjoint est d\'accord', 'NON. Le déblocage pour achat de la résidence principale est formellement EXCLU pour les versements obligatoires de l\'employeur'],
      correct: 3, rationale: 'Seuls les versements volontaires ou l\'intéressement (PER Collectif) peuvent servir à acheter la maison. L\'argent obligatoire reste scellé.' },
    { q: 'En revanche, quels cas permettent de débloquer le Compartiment 3 du PERO avant la retraite ?',
      options: ['Les graves accidents de la vie (Invalidité, surendettement, décès du conjoint, fin de droit au chômage, liquidation judiciaire)', 'Un divorce', 'Le mariage', 'Le paiement des impôts'],
      correct: 0, rationale: 'L\'urgence sociale absolue prime sur la constitution de la retraite.' },
    { q: 'Quel est le bénéfice (social et fiscal) majeur pour le SALARIÉ concernant les versements obligatoires de l\'employeur (Compartiment 3) ?',
      options: ['C\'est versé directement en espèces', 'Ces cotisations patronales sont exonérées d\'impôt sur le revenu (dans une certaine limite) au moment du versement', 'Ils annulent la taxe d\'habitation', 'Ils doublent les trimestres de la Sécu'],
      correct: 1, rationale: 'L\'employé s\'enrichit (création de capital retraite) sans que son revenu net imposable ne bondisse.' },
    { q: '(Challenge) Et pour l\'ENTREPRISE, pourquoi est-il souvent plus rentable de mettre en place un PER Obligatoire plutôt que de donner une augmentation de salaire équivalente ?',
      options: ['L\'entreprise peut reprendre l\'argent', 'Le salaire est trop compliqué à calculer', 'L\'entreprise bénéficie d\'avantages sociaux : les sommes versées sont déductibles de l\'impôt sur les sociétés et échappent en grande partie aux charges sociales (soumises à un "forfait social" réduit de 16%)', 'L\'entreprise évite les syndicats'],
      correct: 2, rationale: 'Donner 100€ de salaire coûte souvent 150€ à l\'entreprise. Verser 100€ sur un PERO lui coûte beaucoup moins cher.' },
    { q: '(Challenge) Que se passe-t-il si le salarié DÉCÈDE pendant la phase d\'épargne (avant sa retraite) ?',
      options: ['Le compte est gelé', 'Le capital constitué est reversé aux bénéficiaires désignés (ou au conjoint). Mais ATTENTION, pour le compartiment obligatoire (C3), le versement se fera OBLIGATOIREMENT sous forme de rente (ou rente éducation pour les enfants) et non en capital', 'L\'argent retourne à l\'entreprise', 'L\'argent est détruit'],
      correct: 1, rationale: 'C\'est un point de vigilance souvent ignoré. Le conjoint survivant ne touchera pas un chèque global de 50 000€, mais une rente viagère mensuelle calculée sur ce capital.' },
  ],
  'w20-d3': [
    { q: 'En quoi consiste le mécanisme de la "Donation avec réserve d\'usufruit" ?',
      options: ['Donner le droit de louer un bien à un locataire', 'Le parent donne la maison, et paie un loyer à ses enfants', 'Donner tous ses biens à une association', 'Le donateur (ex: un parent) transmet la NUE-PROPRIÉTÉ (les murs) d\'un bien à un bénéficiaire (ex: son enfant), mais en CONSERVE L\'USUFRUIT (le droit de l\'habiter ou d\'en percevoir les loyers) sa vie durant'],
      correct: 3, rationale: 'C\'est l\'outil patrimonial par excellence. Les parents préparent la transmission tout en se protégeant : les enfants possèdent les murs, mais ne peuvent pas les mettre à la porte.' },
    { q: 'Pendant la durée du démembrement (tant que le parent est vivant), l\'enfant (Nu-propriétaire) a-t-il le droit de vendre la maison sans l\'accord de son parent ?',
      options: ['Non, il faut obligatoirement l\'accord conjoint (unanimité) de l\'usufruitier et du nu-propriétaire pour vendre le bien', 'Oui, mais seulement s\'il en a besoin pour vivre', 'Oui, car il possède les murs', 'La vente est strictement interdite par la loi'],
      correct: 0, rationale: 'Les droits sont divisés. Personne ne peut vendre la pleine propriété sans l\'accord de l\'autre.' },
    { q: 'Quel est l\'AVANTAGE FISCAL majeur de cette technique lors de la donation chez le notaire ?',
      options: ['Les impôts locaux sont supprimés', 'La mairie verse une subvention', 'Les droits de donation sont calculés UNIQUEMENT sur la valeur de la Nue-propriété, qui représente une fraction réduite de la valeur du bien (calculée selon l\'âge du parent usufruitier). L\'impôt est donc massivement réduit', 'La donation est totalement exonérée par défaut'],
      correct: 2, rationale: 'Si la maison vaut 200 000€ et que la nue-propriété est évaluée à 60%, vous ne payez des impôts que sur 120 000€.' },
    { q: 'Que se passe-t-il mécaniquement au DÉCÈS de l\'usufruitier (le parent) ?',
      options: ['Les enfants paient 20% d\'impôts sur l\'usufruit', 'L\'usufruit s\'éteint naturellement et rejoint la nue-propriété. L\'enfant devient Plein Propriétaire IMMÉDIATEMENT ET SANS PAYER LE MOINDRE IMPÔT de succession supplémentaire', 'L\'usufruit passe à l\'État', 'La maison doit être vendue'],
      correct: 1, rationale: 'C\'est le coup de maître de l\'opération. L\'État a été payé lors de la donation, le remembrement au décès est gratuit (art 1133 CGI).' },
    { q: 'Durant le démembrement, comment sont réparties les charges ? Qui paie les travaux d\'entretien courant et la Taxe Foncière ?',
      options: ['L\'État paie l\'entretien', 'Le Nu-propriétaire (l\'enfant)', 'Le notaire', 'L\'Usufruitier (le parent)'],
      correct: 3, rationale: 'C\'est logique, celui qui profite de l\'usage du bien et de ses revenus en paie les charges courantes et la taxe foncière.' },
    { q: 'Selon l\'article 605 du Code Civil, à qui incombent les "Grosses réparations" (ex: la toiture s\'effondre, les murs porteurs se fissurent) ?',
      options: ['À l\'Usufruitier', 'À l\'assurance', 'À la copropriété', 'Au Nu-propriétaire (l\'enfant)'],
      correct: 3, rationale: 'Les enfants possèdent la "substance" du bien, ils doivent donc payer pour sauver la structure de l\'immeuble. (Attention : dans l\'acte notarié, les parents usufruitiers insèrent souvent une clause pour continuer à payer eux-mêmes ces gros travaux).' },
    { q: 'Concernant l\'Impôt sur la Fortune Immobilière (IFI), qui doit déclarer la valeur du bien ?',
      options: ['Personne', 'Le Nu-propriétaire pour 50 %', 'C\'est une obligation légale pour l\'Usufruitier (le parent) de déclarer le bien pour 100 % de sa valeur (en Pleine Propriété), bien qu\'il n\'ait plus les murs', 'Le Nu-propriétaire déclare tout'],
      correct: 2, rationale: 'Le fisc retient le "profit" : celui qui a l\'usage du bien paie l\'impôt sur la fortune pour la totalité du bien.' },
    { q: 'Lors de la donation, comment est calculée la valeur de la nue-propriété et de l\'usufruit ?',
      options: ['C\'est un taux fixe de 50/50 pour tout le monde', 'Selon le barème légal de l\'article 669 du CGI, strictement basé sur L\'ÂGE DE L\'USUFRUITIER (par tranches de 10 ans). Plus il donne jeune, plus l\'usufruit vaut cher, et donc moins l\'impôt sur la nue-propriété sera élevé', 'Selon le revenu des enfants', 'Selon la taille de la maison'],
      correct: 1, rationale: 'Exemple : si le parent a 55 ans, l\'usufruit vaut 50 %. S\'il a 75 ans, l\'usufruit ne vaut plus que 30 % (la nue-propriété vaut 70 %, l\'impôt sera donc plus lourd).' },
    { q: '(Challenge) Lors de la donation de la nue-propriété d\'une maison de famille par un couple marié à ses enfants, quelle "clause" vitale le notaire doit-il absolument insérer pour protéger le parent qui vivra le plus longtemps ?',
      options: ['La clause de réversion d\'usufruit (ou usufruit successif) : au décès du premier conjoint, le conjoint survivant récupèrera la totalité de l\'usufruit et pourra rester seul dans la maison', 'La clause de divorce', 'La clause d\'aliénation', 'La clause d\'accroissement de tontine'],
      correct: 0, rationale: 'Sans cette clause, au décès de Monsieur, sa moitié d\'usufruit s\'éteindrait, et les enfants deviendraient pleins propriétaires de 50% de la maison, privant Madame de l\'usufruit total.' },
    { q: '(Challenge) Le démembrement s\'applique-t-il aussi à des sommes d\'argent (liquidités) ? Qu\'est-ce que le "Quasi-usufruit" ?',
      options: ['C\'est interdit', 'L\'usufruitier ne peut toucher qu\'aux intérêts générés par la somme', 'Oui, sur de l\'argent (bien consomptible), le parent usufruitier a le droit de DÉPENSER librement l\'intégralité de la somme. Au décès, le nu-propriétaire bénéficiera d\'une "créance de restitution" à récupérer sur la succession', 'C\'est un usufruit sur un bien étranger'],
      correct: 2, rationale: 'C\'est très fréquent lors du versement d\'une assurance-vie. Le conjoint (quasi-usufruitier) profite de tout l\'argent. À sa mort, la somme est déduite de la succession avant le calcul des impôts, rendant l\'argent aux enfants.' },
  ],
  'w20-d4': [
    { q: 'Quel est l\'objectif principal de la loi Badinter votée en 1985 ?',
      options: ['Imposer la ceinture de sécurité', 'Protéger et accélérer l\'indemnisation des VICTIMES d\'accidents de la circulation, en instaurant un régime de responsabilité très favorable (qui évite les batailles juridiques sans fin)', 'Supprimer les assurances automobiles', 'Punir les conducteurs alcoolisés'],
      correct: 1, rationale: 'Avant 1985, pour être indemnisé, la victime devait prouver la faute du conducteur (souvent impossible). La loi Badinter a inversé la logique : on indemnise la victime par principe.' },
    { q: 'Quelles sont les victimes "super-privilégiées" par la loi Badinter (qui sont indemnisées presque automatiquement de leurs dommages corporels) ?',
      options: ['Les piétons, les cyclistes, et les passagers des véhicules', 'Les voleurs de voitures', 'Uniquement les enfants', 'Les conducteurs responsables'],
      correct: 0, rationale: 'C\'est la pierre angulaire de la loi. Tous les "non-conducteurs" sont considérés comme des victimes à protéger absolument face aux machines.' },
    { q: 'Une exception rarissime permet au conducteur d\'une voiture de ne PAS indemniser un piéton adulte écrasé. Quelle est cette exception ?',
      options: ['Si le piéton était habillé en sombre la nuit', 'Si le piéton traversait hors du passage clouté', 'S\'il n\'y avait pas de témoin', 'Si la victime a commis une "Faute Inexcusable, cause exclusive de l\'accident" (ex: acte suicidaire jeté délibérément sous les roues)'],
      correct: 3, rationale: 'Traverser au rouge n\'est pas une faute inexcusable pour la loi. L\'assureur du véhicule devra indemniser le piéton.' },
    { q: 'La loi va encore plus loin dans la protection de certaines victimes. Pour qui la notion de "faute inexcusable" (l\'exception ci-dessus) est-elle DÉSACTIVÉE (ils sont toujours indemnisés, quoi qu\'ils fassent) ?',
      options: ['Pour les ministres', 'Pour les femmes enceintes', 'Les victimes de MOINS de 16 ans, de PLUS de 70 ans, et les grands invalides (taux > 80%). Leurs dommages corporels sont systématiquement indemnisés (sauf s\'ils ont recherché volontairement le dommage)', 'Pour les fonctionnaires'],
      correct: 2, rationale: 'Un enfant de 10 ans qui traverse l\'autoroute en courant sans regarder sera intégralement indemnisé de ses blessures.' },
    { q: 'Qu\'en est-il du CONDUCTEUR du véhicule fautif qui se blesse dans l\'accident ?',
      options: ['Il est lui aussi indemnisé systématiquement', 'Il sort du régime de protection totale. L\'indemnisation de ses blessures par l\'assurance sera réduite ou totalement exclue s\'il a commis une faute de conduite', 'L\'État paie ses blessures', 'Le passager doit l\'indemniser'],
      correct: 1, rationale: 'Si le conducteur percute un arbre seul (ou brûle un feu), la loi Badinter ne le protège pas de sa propre erreur. D\'où l\'importance vitale de souscrire l\'option "Garantie personnelle du conducteur".' },
    { q: 'Pour que la loi Badinter s\'applique, le véhicule impliqué doit être un "VTAM" (Véhicule Terrestre à Moteur). Qu\'est-ce qui entre dans cette catégorie ?',
      options: ['Les vélos non électriques et les trains sur rails propres (TGV)', 'Uniquement les voitures et les camions', 'Seulement les véhicules de plus de 500 kg', 'Les voitures, motos, tracteurs, tondeuses autoportées, et désormais les trottinettes électriques (EDPM)'],
      correct: 3, rationale: 'Tout engin motorisé avec un siège/guidon évoluant sur le sol est un VTAM, et doit donc posséder une assurance Responsabilité Civile dédiée.' },
    { q: 'Faut-il qu\'il y ait eu un "contact physique" (un choc) entre la voiture et la victime pour que la loi Badinter oblige l\'assurance de la voiture à payer ?',
      options: ['Seulement si la voiture allait très vite', 'Oui, pas de choc = pas de Badinter', 'Non. Il suffit que le véhicule soit "Impliqué" dans l\'accident (ex: une voiture freine brusquement, forçant un cycliste à faire un écart et à chuter, sans se toucher)', 'Uniquement avec des piétons'],
      correct: 2, rationale: 'Le véhicule est intervenu, à quelque titre que ce soit, dans la survenance de l\'accident.' },
    { q: 'La loi Badinter s\'applique-t-elle avec la même protection absolue pour les "Dommages MATÉRIELS" (la carrosserie écrasée, les vêtements déchirés) de la victime ?',
      options: ['Non. Le régime de faveur s\'applique uniquement aux dommages CORPORELS (les blessures). Pour les dégâts matériels, on revient au droit classique (qui est en tort ?)', 'Uniquement pour la valeur à neuf', 'Oui, tout est remboursé sans discuter', 'L\'État paie le matériel'],
      correct: 0, rationale: 'Le piéton fautif sera indemnisé pour sa jambe cassée (corporel), mais l\'assurance ne remboursera pas son téléphone écrasé (matériel) puisqu\'il était en tort.' },
    { q: '(Challenge) Lors d\'un accident grave, quel "délai de rigueur" la loi Badinter impose-t-elle à l\'assureur pour faire une OFFRE d\'indemnisation à la victime, sous peine de lourdes pénalités ?',
      options: ['Il n\'y a aucun délai', 'L\'assureur a 5 ans', 'L\'assureur doit présenter une offre d\'indemnisation dans un délai maximum de 8 mois à compter de l\'accident', 'Dans les 24 heures'],
      correct: 2, rationale: 'Le but était d\'arrêter les procédures d\'assurances qui laissaient les victimes lourdement blessées sans argent pendant des années.' },
    { q: '(Challenge) Deux voitures (A et',
      options: ['entrent en collision frontale. Le passager de la voiture A est grièvement blessé. Que dit la loi Badinter sur l\'indemnisation du passager ?', 'Il doit attendre que la police trouve le coupable', 'Il paie sa propre assurance maladie', 'Le passager s\'adresse à l\'assureur du véhicule dans lequel il se trouvait (A). Cet assureur l\'indemnise intégralement immédiatement, puis se chargera lui-même du recours contre l\'assureur de l\'autre voiture (', 'si l\'autre était en tort', 'Il doit poursuivre le conducteur'],
      correct: 2, rationale: 'C\'est le triomphe de la loi Badinter : simplifier la vie de la victime. Elle n\'a pas à chercher qui a causé l\'accident, l\'assurance de son "véhicule transporteur" gère tout.' },
  ],
  'w20-d5': [
    { q: 'Comment la loi (loi Alur) définit-elle juridiquement la "Colocation" ?',
      options: ['Le fait de prêter son canapé pour une nuit', 'La location d\'un même logement par plusieurs locataires, constituant leur résidence principale, formalisée par un bail unique ou plusieurs baux entre les locataires et le bailleur', 'La location de locaux commerciaux à plusieurs start-ups', 'Le fait qu\'un propriétaire habite avec son locataire'],
      correct: 1, rationale: 'La colocation est très réglementée. (Si le propriétaire vit avec le locataire, on appelle cela la cohabitation intergénérationnelle ou location de chambre chez l\'habitant, pas la colocation).' },
    { q: 'Laquelle de ces pratiques est l\'argument principal pour un propriétaire qui décide de louer son T4 (4 pièces) en colocation plutôt qu\'à une seule famille classique ?',
      options: ['Pour ne pas payer d\'impôts locaux', 'Louer "à la chambre" permet souvent de générer un loyer global bien SUPÉRIEUR (une meilleure rentabilité) que le loyer d\'un bien loué en entier', 'Pour éviter la paperasse', 'Car l\'État verse une subvention colocation'],
      correct: 1, rationale: 'Un T4 loué entier rapportera 900€. S\'il a 3 chambres louées 400€ chacune, il rapportera 1 200€.' },
    { q: 'Dans le cas de la signature d\'un "BAIL UNIQUE" (un seul contrat signé par tous les colocataires), quelle clause le propriétaire exige-t-il systématiquement pour se protéger des impayés ?',
      options: ['La clause de non-concurrence', 'La clause d\'hébergement familial', 'La Clause de Solidarité (ou clause d\'indivisibilité) : chaque colocataire est redevable de la TOTALITÉ du loyer. Si un ne paie pas, le propriétaire peut exiger le loyer entier à n\'importe quel autre colocataire', 'La clause d\'expulsion express'],
      correct: 2, rationale: 'C\'est le bouclier du bailleur. Les colocataires sont liés financièrement. Si Pierre ne paie pas sa part, Paul et Jacques devront payer à sa place.' },
    { q: 'Lorsqu\'un colocataire (sous bail unique avec clause de solidarité) donne son préavis (congé) et quitte l\'appartement, quand prend fin sa solidarité financière avec les autres ?',
      options: ['Elle s\'éteint immédiatement lors de la remise de ses clés ou de la notification du congé au bailleur', 'Elle s\'éteint au moment de la signature d\'un nouveau locataire remplaçant. Si personne ne le remplace, sa solidarité perdure au MAXIMUM 6 mois après la fin de son préavis', 'Elle est à vie', 'Elle s\'éteint au départ du dernier colocataire'],
      correct: 1, rationale: 'La loi Alur (2014) a mis fin aux dérives où un ancien colocataire restait caution solidaire des années après son départ.' },
    { q: 'Qu\'est-ce que le système des "Baux Multiples" (ou baux individuels) en colocation ?',
      options: ['Le locataire a le droit d\'avoir plusieurs appartements', 'Le loyer est multiplié par deux', 'Le propriétaire signe un contrat différent avec chaque locataire, lui attribuant la jouissance exclusive d\'une chambre précise et l\'accès partagé aux parties communes', 'Les locataires doivent changer de chambre chaque mois'],
      correct: 2, rationale: 'C\'est très prisé par les étudiants qui ne se connaissent pas. Il n\'y a PAS de clause de solidarité entre eux. Si l\'un part, les autres ne paient pas sa part.' },
    { q: 'Concernant les surfaces minimales imposées par la loi. Dans le cas des "Baux multiples" (un bail par chambre), quelle est la taille MINIMALE obligatoire de la chambre privative louée ?',
      options: ['9 m² de surface et un volume de 20 m³ minimum (hors parties communes)', '16 m²', '5 m²', 'Il n\'y a pas de taille minimale'],
      correct: 0, rationale: 'Un propriétaire ne peut pas louer un placard de 6m2 en colocation à baux multiples, c\'est interdit par le code de la santé publique.' },
    { q: 'Comment gère-t-on le Dépôt de Garantie (la caution) dans un "Bail Unique" lorsqu\'un colocataire quitte les lieux mais que la colocation continue avec les autres ?',
      options: ['Le propriétaire lui rend sa part immédiatement', 'Le propriétaire ne lui rend RIEN. Le dépôt de garantie n\'est restitué par le bailleur qu\'à la restitution totale des clés (fin complète du bail). C\'est souvent le nouveau colocataire entrant qui arrange ça avec le sortant (à l\'amiable)', 'Le sortant prend des meubles en compensation', 'Le dépôt de garantie n\'existe pas en colocation'],
      correct: 1, rationale: 'La colocation solidaire se gère en bloc. Le bailleur ne fait pas les comptes à chaque mouvement.' },
    { q: 'Quelle est l\'obligation légale de la colocation vis-à-vis de l\'assurance Habitation (MRH - Risques Locatifs) ?',
      options: ['Ils n\'ont pas besoin d\'assurance si c\'est meublé', 'Seul le propriétaire s\'assure', 'Au moins un des colocataires doit être assuré pour le logement (bien que l\'idéal soit qu\'ils le soient tous). La loi Alur permet même au propriétaire de souscrire l\'assurance pour eux et de répercuter le coût (majoré) sur les charges', 'L\'État assure les étudiants'],
      correct: 2, rationale: 'Un oubli d\'assurance dans une colocation à 5 peut virer au cauchemar en cas d\'incendie, la loi protège donc le bien.' },
    { q: '(Challenge) Un groupe de 3 amis signe un "Bail unique" pour louer une maison. Ils veulent percevoir les APL (Aides Personnalisées au Logement). Comment cela fonctionne-t-il ?',
      options: ['Seul celui dont le nom est en premier sur le bail touche l\'APL', 'L\'APL est interdite en colocation', 'Ils font une demande collective à la mairie', 'Chaque colocataire fait sa propre demande individuelle à la CAF, qui calculera l\'aide en divisant le loyer total par le nombre de colocataires inscrits sur le bail'],
      correct: 3, rationale: 'Les aides au logement sont personnalisées selon les revenus de chaque étudiant/jeune actif.' },
    { q: '(Challenge) En matière de charges locatives (eau, électricité, poubelles, internet), quelle option "simplifiée" le bailleur peut-il choisir EXCLUSIVEMENT pour la colocation et la location meublée ?',
      options: ['Le "Forfait de charges". Le montant mensuel est fixe. Le propriétaire n\'a pas à faire de régularisation en fin d\'année (ni rendre le trop-perçu, ni réclamer le dépassement)', 'Faire payer la mairie', 'Supprimer les charges', 'Exiger le remboursement complet en fin de bail uniquement'],
      correct: 0, rationale: 'En location nue classique, la "provision pour charges" nécessite une fastidieuse régularisation annuelle sur factures réelles. Le forfait est une paix d\'esprit pour le gérant de coloc.' },
  ],
};
