/* Questions de la semaine 14. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w14-d0': [
    { q: 'En finance, qu\'est-ce qu\'une "action" ?',
      options: ['Un prêt d\'argent à une entreprise', 'Un titre de propriété représentant une fraction du capital d\'une société', 'Une assurance contre la faillite', 'Une taxe boursière obligatoire'],
      correct: 1, rationale: 'En achetant une action, vous devenez copropriétaire (actionnaire) de l\'entreprise, assumant une part de ses risques et de ses succès.' },
    { q: 'Quel est le droit politique fondamental accordé par la détention d\'une action classique ?',
      options: ['Le droit de voter lors des Assemblées Générales', 'Le droit de licencier les employés', 'Le droit de ne pas payer d\'impôts', 'Le droit d\'obtenir des produits gratuits'],
      correct: 0, rationale: 'Une action = une voix (le plus souvent). Les actionnaires votent la stratégie, les comptes et l\'élection des dirigeants.' },
    { q: 'Comment s\'appelle la part des bénéfices que l\'entreprise décide de redistribuer à ses actionnaires ?',
      options: ['La plus-value', 'Le coupon', 'La prime d\'émission', 'Le dividende'],
      correct: 3, rationale: 'Si l\'entreprise est rentable, son Assemblée Générale peut voter le versement d\'un dividende pour rémunérer les actionnaires qui lui ont fait confiance.' },
    { q: 'Quel est le risque maximum encouru lorsque l\'on achète une action ?',
      options: ['Perdre l\'intégralité de la somme investie (perte en capital totale) en cas de faillite', 'Devoir rembourser les dettes de l\'entreprise sur ses deniers personnels', 'Perdre 50 % de sa mise au maximum', 'Aucun, le capital est garanti par l\'État'],
      correct: 0, rationale: 'La responsabilité de l\'actionnaire est limitée à son apport. Si l\'entreprise fait faillite, l\'action vaut 0 €, mais on ne viendra pas saisir votre maison.' },
    { q: 'Qu\'est-ce que le marché "primaire" des actions ?',
      options: ['Le marché de l\'occasion', 'Le marché réservé aux banques', 'Le marché des matières premières', 'Le marché où les actions "neuves" sont émises et vendues pour la première fois (Introduction en Bourse / IPO)'],
      correct: 3, rationale: 'Le marché primaire finance directement l\'entreprise. Le marché secondaire (la bourse au quotidien) n\'est que le marché de l\'occasion où les investisseurs s\'échangent les titres existants.' },
    { q: 'Que se passe-t-il lors d\'une "augmentation de capital" pour un actionnaire qui ne réinvestit pas ?',
      options: ['Il gagne de l\'argent', 'Son droit de vote est doublé', 'Il subit une "dilution" : sa part en pourcentage de l\'entreprise diminue car de nouvelles actions sont créées', 'L\'entreprise rachète ses actions de force'],
      correct: 2, rationale: 'Si vous possédez 10 actions sur 100 (10%). Que l\'entreprise émet 100 nouvelles actions, vous n\'avez plus que 10 actions sur 200 (5%). Votre pouvoir est dilué.' },
    { q: 'En jargon boursier, qu\'est-ce qu\'une OPA ?',
      options: ['Offre Publique d\'Achat (un acquéreur propose publiquement de racheter toutes les actions d\'une cible à un prix fixé)', 'Obligation Privée Anonyme', 'Organisation des Petits Actionnaires', 'Ordre de Paiement Anticipé'],
      correct: 0, rationale: 'Lors d\'une OPA, le prix proposé est généralement supérieur au cours de bourse actuel pour convaincre les actionnaires de céder leurs titres.' },
    { q: 'Pourquoi dit-on que les actions des grandes entreprises (comme LVMH ou Total) sont très "liquides" ?',
      options: ['Parce qu\'elles versent des dividendes mensuels', 'Parce qu\'on peut les acheter et les revendre instantanément en bourse grâce au très grand nombre d\'acheteurs et de vendeurs', 'Parce que leurs prix chutent facilement', 'Parce qu\'elles sont garanties en cash'],
      correct: 1, rationale: 'La liquidité est l\'avantage majeur de la bourse par rapport à l\'immobilier.' },
    { q: '(Challenge) Qu\'est-ce que le PER (Price Earning Ratio), un ratio incontournable pour évaluer une action ?',
      options: ['La différence entre le prix et la dette', 'Le ratio mesurant le cours de l\'action divisé par le bénéfice net par action (il indique combien d\'années de bénéfices l\'investisseur est prêt à payer)', 'Le Plan d\'Épargne Retraite de l\'entreprise', 'Le Pourcentage d\'Émission Réel'],
      correct: 1, rationale: 'Un PER de 15 signifie que l\'entreprise est valorisée 15 fois ses bénéfices annuels. Un PER de 50 indique souvent une entreprise jugée très chère (ou avec de très fortes attentes de croissance).' },
    { q: '(Challenge) Une entreprise décide de faire un "Split" (division) de ses actions par 4. Si vous aviez 10 actions valant 400 € l\'unité, que possédez-vous après l\'opération ?',
      options: ['10 actions valant 100 €', '40 actions valant 400 €', '40 actions valant 100 € (la valeur totale de votre portefeuille ne change pas)', '4 actions valant 1000 €'],
      correct: 2, rationale: 'Le split ne rend pas l\'entreprise plus riche. Il rend juste l\'action plus "accessible" aux petits porteurs en baissant le prix unitaire, tout en multipliant le nombre d\'actions.' },
  ],
  'w14-d1': [
    { q: 'Dans une assurance-vie, sur quelle base exacte sont calculés les impôts lors d\'un rachat (retrait) ?',
      options: ['Uniquement sur la "plus-value" (les intérêts/gains) comprise dans le retrait, le capital retiré n\'étant jamais taxé', 'Sur la totalité du retrait (capital + gains)', 'Uniquement sur les primes versées', 'Il n\'y a jamais d\'impôt sur un retrait'],
      correct: 0, rationale: 'L\'État ne taxe que la richesse créée. Si vous retirez 10 000 € composés de 8 000 € de vos versements et 2 000 € de gains, seuls les 2 000 € seront soumis à l\'impôt.' },
    { q: 'Pour les versements effectués depuis fin 2017, quelle est la fiscalité par défaut si vous faites un retrait AVANT le 8ème anniversaire du contrat ?',
      options: ['Le PFU (Flat Tax) de 30 % sur les gains (12,8 % d\'impôt + 17,2 % de prélèvements sociaux)', 'Une taxe forfaitaire de 50 %', 'Zéro impôt, uniquement les prélèvements sociaux', 'Le barème progressif majoré de 10 %'],
      correct: 0, rationale: 'Avant 8 ans, l\'assurance-vie est alignée sur la fiscalité classique des comptes titres et livrets non réglementés.' },
    { q: 'Quel événement déclenche l\'avantage fiscal majeur de l\'assurance-vie de son vivant ?',
      options: ['Le 5ème anniversaire du contrat', 'Le 8ème anniversaire de l\'ouverture du contrat', 'Le passage à la retraite', 'L\'atteinte de 100 000 € de capital'],
      correct: 1, rationale: 'L\'antériorité fiscale de 8 ans s\'apprécie à partir de la date du premier versement à l\'ouverture.' },
    { q: 'Après 8 ans de détention, de quel avantage bénéficiez-vous sur vos retraits ?',
      options: ['Une exonération totale de prélèvements sociaux', 'Un taux d\'impôt bloqué à 0 % sans limite', 'Un abattement annuel sur les intérêts de 4 600 € (personne seule) ou 9 200 € (couple marié/pacsé), l\'excédent éventuel étant taxé à un taux réduit (souvent 7,5 %)', 'L\'assureur paie les impôts à votre place'],
      correct: 2, rationale: 'C\'est la force du contrat. Vous pouvez retirer des sommes importantes chaque année en étant totalement exonéré d\'impôt sur le revenu (dans la limite de cet abattement des gains).' },
    { q: 'Même si vos intérêts sont couverts par l\'abattement de 4 600 € après 8 ans (donc 0 € d\'impôt sur le revenu), quelle taxe restera TOUJOURS prélevée ?',
      options: ['La taxe foncière', 'Les Prélèvements Sociaux (17,2 %)', 'La TVA', 'La taxe sur les transactions financières'],
      correct: 1, rationale: 'L\'avantage fiscal des 8 ans ne concerne que l\'Impôt sur le Revenu (IR). La part sociale (CSG/CRDS) est incontournable.' },
    { q: 'Dans quel cas spécifique un retrait sur une assurance-vie (même avant 8 ans) est-il TOTALEMENT exonéré d\'impôt sur le revenu ?',
      options: ['Pour acheter une voiture', 'Lors d\'un coup dur : licenciement (fin de CDD exclue), mise à la retraite anticipée, ou invalidité grave du souscripteur ou de son conjoint', 'Pour payer ses impôts', 'Si le retrait a lieu le mois de son anniversaire'],
      correct: 1, rationale: 'La loi protège les contribuables frappés par un grave accident de la vie, en effaçant l\'impôt sur les plus-values retirées pour faire face.' },
    { q: 'Que se passe-t-il fiscalement chaque année sur la poche "Fonds en Euros" de l\'assurance-vie, sans même faire de retrait ?',
      options: ['L\'assureur prélève directement les prélèvements sociaux (17,2 %) sur les intérêts de l\'année avant de vous les verser (inscription en compte)', 'L\'État saisit 10 % du capital', 'Rien, la fiscalité n\'intervient qu\'au retrait', 'Les impôts doublent'],
      correct: 0, rationale: 'Contrairement aux Unités de Compte où les prélèvements sociaux ne sont dus qu\'au retrait (ou au décès), le fonds euros paie la Sécurité sociale tous les 31 décembre.' },
    { q: 'Lors d\'un rachat, avez-vous le choix de la méthode d\'imposition sur le revenu ?',
      options: ['Oui, vous pouvez opter pour l\'imposition au barème progressif (si votre TMI est faible) au lieu du prélèvement forfaitaire de la banque', 'Non, la banque impose son taux', 'Oui, mais seulement pour les vieux contrats', 'Non, le prélèvement à la source est définitif'],
      correct: 0, rationale: 'Si vous êtes non imposable (TMI à 0%), il est plus judicieux de choisir le barème progressif plutôt que de subir la Flat Tax (12,8%).' },
    { q: '(Challenge) Lors d\'un rachat partiel, l\'assureur doit calculer la part de capital et la part d\'intérêts dans la somme retirée. Quelle méthode mathématique obligatoire utilise-t-il ?',
      options: ['La méthode FIFO (Premier entré, premier sorti)', 'Il considère que les 10 000 premiers euros retirés sont 100% du capital', 'Une formule de proportionnalité stricte : Montant du retrait - [Montant du retrait x (Total des versements / Valeur totale du contrat)]', 'Il vous laisse choisir'],
      correct: 2, rationale: 'Si votre contrat est composé globalement de 80% de versements et 20% de gains, tout retrait que vous ferez sera fiscalement composé de 80% de capital non taxé et 20% d\'intérêts imposables.' },
    { q: '(Challenge) Pour les très gros contrats d\'assurance-vie, que se passe-t-il si l\'encours total (primes versées tous contrats confondus) dépasse 150 000 € par assuré ?',
      options: ['Le contrat est gelé', 'Les plus-values des versements excédant 150 000 € (réalisés après 2017) perdent l\'avantage du taux réduit à 7,5% après 8 ans, et sont taxées à 12,8% (PFU global à 30%)', 'L\'excédent est saisi', 'L\'assuré doit clôturer un contrat'],
      correct: 1, rationale: 'La loi Macron a raboté l\'avantage fiscal historique pour les très riches, en imposant le PFU plein sur les très gros encours, même après 8 ans.' },
  ],
  'w14-d2': [
    { q: 'Que signifie le sigle PER ?',
      options: ['Prêt d\'Épargne Réservé', 'Plan d\'Épargne Retraite', 'Prime d\'État Réglementée', 'Programme d\'Enrichissement Rentable'],
      correct: 1, rationale: 'Lancé en 2019 par la loi PACTE, il vise à simplifier et harmoniser tous les anciens dispositifs de retraite supplémentaire.' },
    { q: 'Quels anciens contrats le PER Individuel (PERin) est-il venu remplacer ?',
      options: ['Le Livret A et le LDD', 'Le PERP (pour les salariés) et le contrat Madelin (pour les indépendants/TNS)', 'Le PEA et le Compte Titres', 'L\'Assurance-Vie et le PEL'],
      correct: 1, rationale: 'Ces anciens contrats ne sont plus commercialisés depuis 2020. Le PERin réunit les avantages des deux statuts en un seul produit.' },
    { q: 'Quel est le principal AVANTAGE FISCAL lors de la phase d\'épargne (versements volontaires) sur un PER ?',
      options: ['L\'État abonde 100 % des versements', 'Les versements sont totalement exonérés de TVA', 'Les sommes versées sont déductibles du revenu imposable (dans une certaine limite), ce qui génère une économie d\'impôt immédiate proportionnelle à la TMI (Tranche Marginale d\'Imposition) de l\'épargnant', 'Les frais de gestion sont gratuits'],
      correct: 2, rationale: 'Si vous avez une TMI à 30 % et versez 1 000 €, vous économisez 300 € d\'impôts sur le revenu. C\'est l\'argument numéro un du PER.' },
    { q: 'Quelle est la grande contrepartie de cet avantage fiscal (la contrainte du PER) ?',
      options: ['L\'argent est investi uniquement dans les banques publiques', 'L\'argent est "bloqué" (tunnel de placement) jusqu\'à l\'âge de départ à la retraite, sauf cas de déblocage anticipé prévus par la loi', 'Les héritiers ne touchent rien en cas de décès', 'Il faut verser 500 € par mois obligatoirement'],
      correct: 1, rationale: 'C\'est une épargne "tunnel". On ne peut pas s\'en servir comme d\'un livret pour partir en vacances l\'année suivante.' },
    { q: 'Avant la loi PACTE (sur le PERP), la sortie se faisait presque obligatoirement en rente viagère. Quelle grande nouveauté offre le nouveau PER au moment de la retraite ?',
      options: ['Il permet de transmettre le capital à la banque', 'L\'épargnant a la liberté totale de sortir en capital (en une fois ou de façon fractionnée), en rente viagère, ou un mix des deux', 'La sortie se fait obligatoirement en actions', 'La sortie est plafonnée à 1 000 €/mois'],
      correct: 1, rationale: 'Cette nouveauté a rendu le produit extrêmement populaire, car les Français sont souvent réticents à "aliéner" leur capital en rente viagère.' },
    { q: 'Est-il possible de RENONCER à la déduction fiscale à l\'entrée (lors du versement) ?',
      options: ['Oui, le choix est possible. Dans ce cas, la fiscalité à la sortie (à la retraite) sera beaucoup plus légère, ne taxant que les plus-values et non le capital', 'Non, la déduction est obligatoire', 'Seulement pour les revenus inférieurs au SMIC', 'Oui, mais on perd l\'argent investi'],
      correct: 0, rationale: 'C\'est utile pour les personnes non imposables. S\'ils déduisaient à l\'entrée (gain = 0), ils se feraient quand même taxer à la sortie (double peine). L\'option permet d\'éviter cela.' },
    { q: 'Un indépendant (TNS) verse sur son PER. Sur quel plafond spécifique la déduction fiscale est-elle calculée ?',
      options: ['10 % du Plafond de la Sécurité Sociale pour tous', 'Soit le plafond général (10 % du PASS ou des revenus), soit le plafond spécifique des indépendants (l\'ex-plafond Madelin), souvent beaucoup plus généreux (jusqu\'à 85 000 €)', '50 % de son chiffre d\'affaires', 'Il n\'y a pas de plafond pour les indépendants'],
      correct: 1, rationale: 'Le PER a conservé l\'avantage du Madelin pour encourager les artisans et commerçants (qui ont peu de retraite de base) à cotiser massivement.' },
    { q: 'Que se passe-t-il en cas de décès du titulaire du PER Individuel avant sa retraite ?',
      options: ['Le capital est perdu et conservé par la banque', 'L\'État saisit l\'intégralité du compte', 'Le PER est clôturé et le capital est transmis aux bénéficiaires désignés (clause bénéficiaire), avec une fiscalité très proche de celle de l\'assurance-vie (abattement de 152 500 € si décès avant 70 ans)', 'Les bénéficiaires héritent des impôts'],
      correct: 2, rationale: 'Le PER Assurance est un excellent outil de prévoyance en cas de décès prématuré.' },
    { q: '(Challenge) Un cadre verse 5 000 € sur son PER en 2024. Il les déduit de ses impôts (TMI 30 %). À la retraite, il décide de sortir ces 5 000 € (le capital) en une seule fois. Quelle sera la fiscalité applicable SUR LE CAPITAL retiré ?',
      options: ['0 %, car il a déjà été taxé', 'Il sera soumis au Prélèvement Forfaitaire Unique (30 %)', 'Le capital retiré sera réintégré dans ses revenus de l\'année et taxé au barème progressif de l\'impôt sur le revenu (selon sa TMI à la retraite)', 'Il paiera une taxe forfaitaire de 10 %'],
      correct: 2, rationale: 'C\'est le principe du PER : "Ceinture aujourd\'hui, Bretelles demain". On vous défiscalise quand vous êtes actif (TMI haute), mais on vous taxe à la sortie quand vous êtes retraité (TMI souvent plus basse).' },
    { q: '(Challenge) Où le contribuable peut-il trouver le montant exact de son "Plafond Épargne Retraite" disponible pour l\'année en cours ?',
      options: ['En demandant à sa mairie', 'Sur la page 3 de son avis d\'imposition reçu à la fin de l\'été, qui indique le plafond calculé sur les revenus de l\'année N-1, ainsi que les plafonds non utilisés des 3 années précédentes', 'C\'est un calcul secret du gouvernement', 'Il faut appeler l\'URSSAF'],
      correct: 1, rationale: 'L\'astuce majeure est la "mutualisation". Vous pouvez utiliser vos plafonds non consommés des 3 dernières années pour faire un énorme versement déductible cette année.' },
  ],
  'w14-d3': [
    { q: 'Dans un contrat d\'assurance-vie, à quoi sert la "Clause bénéficiaire" ?',
      options: ['À choisir le type de placements (actions ou obligations)', 'À désigner nominativement (ou par leur qualité) la ou les personnes qui recevront le capital accumulé au moment du décès du souscripteur', 'À annuler les frais de gestion', 'À désigner l\'héritier de la maison'],
      correct: 1, rationale: 'C\'est le cœur juridique du contrat. Sans cette clause, l\'argent retombe dans la succession classique.' },
    { q: 'Quelle est la formulation classique de la clause "standard" (ou par défaut) pré-imprimée par les assureurs ?',
      options: ['"À mon voisin, à défaut l\'État"', '"Mon conjoint ou partenaire de PACS, à défaut mes enfants nés ou à naître, vivants ou représentés, par parts égales, à défaut mes héritiers"', '"À ma femme, et rien aux enfants"', '"À mon chat"'],
      correct: 1, rationale: 'Cette clause standard est conçue pour correspondre à 80 % des schémas familiaux et "sécuriser" la transmission sans faille juridique.' },
    { q: 'Dans la clause standard, que signifie la mention vitale "À défaut" ?',
      options: ['Que le bénéficiaire est en faute', 'Elle instaure un ordre de priorité (une hiérarchie). Si le conjoint est décédé avant ou s\'il renonce au bénéfice, c\'est le rang suivant (les enfants) qui touchera le capital, évitant ainsi un vide juridique', 'Qu\'il faut payer une taxe de défaut', 'Que l\'argent va à l\'État'],
      correct: 1, rationale: 'Si la clause disait juste "Mon conjoint", et qu\'il décède dans le même accident que vous, le contrat devient "sans bénéficiaire désigné" et perd tous ses avantages fiscaux.' },
    { q: 'Pourquoi est-il souvent préférable de désigner "Mon conjoint" (par sa qualité) plutôt que "Madame [Prénom] [Nom]" dans un contrat ouvert jeune ?',
      options: ['Car les assureurs interdisent les noms propres', 'En cas de divorce et de remariage 10 ans plus tard, la qualité de "conjoint" désignera automatiquement la nouvelle épouse au moment du décès. Un nom propre figerait le capital pour l\'ex-épouse si on oublie de modifier la clause', 'Pour éviter de payer des impôts', 'Car un nom de famille change chaque année'],
      correct: 1, rationale: 'L\'appréciation de la qualité (conjoint, enfants) se fait "au jour de l\'exigibilité" (au décès du souscripteur), pas au jour de la signature.' },
    { q: 'Sur le plan strict du droit civil des assurances, si la clause stipule "Mon conjoint", cela englobe-t-il un partenaire de PACS ou un concubin ?',
      options: ['Oui, c\'est exactement pareil', 'Non, la jurisprudence civile est stricte : le terme "conjoint" ne désigne QUE la personne unie par les liens du mariage. Le partenaire de PACS et le concubin en sont exclus', 'Oui, si l\'assurance l\'accepte', 'Uniquement après 5 ans de vie commune'],
      correct: 1, rationale: 'C\'est le piège classique. Des concubins cochent la clause standard "Mon conjoint" pensant se protéger, et au décès, l\'argent va directement aux enfants (rang 2).' },
    { q: 'Que couvre la mention "mes enfants nés ou à naître" dans la clause standard ?',
      options: ['Les enfants des voisins', 'Elle permet d\'inclure automatiquement les enfants qui naîtraient APRÈS la souscription du contrat (y compris ceux conçus mais pas encore nés au jour du décès) sans avoir à refaire le contrat', 'Uniquement les jumeaux', 'Les enfants adoptés illégalement'],
      correct: 1, rationale: 'L\'assureur divisera le capital par le nombre d\'enfants vivants au jour du décès, sans que le parent n\'ait eu besoin de mettre à jour le contrat à chaque naissance.' },
    { q: 'Que permet la mention "vivants ou représentés" lorsqu\'elle s\'applique aux enfants ?',
      options: ['L\'enfant doit avoir un avocat (représentant)', 'Si l\'un des enfants est malheureusement pré-décédé, sa part ne sera pas absorbée par ses frères et sœurs, mais ira à ses propres descendants (les petits-enfants du souscripteur)', 'Le droit de vote par procuration', 'L\'intervention de la police'],
      correct: 1, rationale: 'Sans le mot "représentés", la part d\'un fils décédé irait grossir celle des autres enfants survivants, lésant totalement les petits-enfants de cette branche.' },
    { q: 'Pourquoi la clause standard finit-elle toujours par "à défaut, mes héritiers" ?',
      options: ['C\'est la signature de l\'assureur', 'C\'est la clause "balai" ultime. Si le conjoint et les enfants sont morts (ou refusent), le capital est versé aux héritiers légaux en conservant le cadre fiscal avantageux de l\'assurance-vie, évitant que l\'argent ne revienne à l\'État', 'Pour payer les dettes du notaire', 'Pour annuler le contrat'],
      correct: 1, rationale: 'C\'est le filet de sécurité absolu pour que le contrat ne tombe pas dans le droit commun.' },
    { q: '(Challenge) Qu\'est-ce que "l\'acceptation de la clause bénéficiaire" par un bénéficiaire du vivant du souscripteur ?',
      options: ['Il signe un papier pour dire merci', 'Il s\'engage à payer les cotisations', 'Un acte officiel (nécessitant l\'accord de l\'assuré) par lequel le bénéficiaire accepte la clause. Une fois acceptée, le souscripteur est "bloqué" : il ne peut plus modifier la clause ni faire de retraits sans l\'accord de l\'acceptant', 'Le paiement d\'une taxe d\'acceptation'],
      correct: 2, rationale: 'C\'est très lourd de conséquences. On ne prévient donc pas toujours un bénéficiaire de son vivant pour conserver sa liberté de gérer son épargne.' },
    { q: '(Challenge) Est-il possible de rédiger une clause bénéficiaire TOTALEMENT LIBRE sur feuille blanche au lieu de cocher la case standard ?',
      options: ['Non, c\'est interdit', 'Oui, mais avec une limite de 10 mots', 'Oui, on peut désigner qui l\'on veut (amis, fondation, répartition en pourcentages inégaux), à condition d\'être très précis sur les identités (nom, prénom, date et lieu de naissance) pour éviter les litiges lors de la recherche', 'Uniquement avec l\'accord d\'un juge'],
      correct: 2, rationale: 'La clause standard est sécurisante, mais la clause libre est l\'outil du "sur-mesure" patrimonial.' },
  ],
  'w14-d4': [
    { q: 'Quel est le sujet central (le domaine d\'application) de la Loi Lemoine promulguée en 2022 ?',
      options: ['L\'assurance des trottinettes électriques', 'L\'assurance Emprunteur (l\'assurance de prêt immobilier)', 'L\'assurance Multirisque Habitation', 'L\'assurance des animaux'],
      correct: 1, rationale: 'La loi Lemoine a révolutionné le marché de l\'assurance de prêt immobilier en France, jusqu\'alors dominé par les banques.' },
    { q: 'Quelle est l\'avancée majeure (et très attendue) de la loi Lemoine concernant la "résiliation" de l\'assurance emprunteur ?',
      options: ['Elle permet de résilier l\'assurance à tout moment, sans aucun frais ni pénalité, dès le lendemain de la signature du crédit (Résiliation Infra-Annuelle - RIA)', 'Elle interdit la résiliation pendant 10 ans', 'Elle permet de résilier uniquement le jour de la date anniversaire du contrat (loi Bourquin)', 'Elle permet de résilier uniquement si on vend la maison'],
      correct: 0, rationale: 'Avant, changer d\'assurance était un parcours du combattant rythmé par des dates d\'anniversaires complexes. Aujourd\'hui, on peut changer quand on veut.' },
    { q: 'Une des mesures chocs de la loi Lemoine est la SUPPRESSION du "Questionnaire médical". Sous quelle condition de montant de crédit cette suppression s\'applique-t-elle ?',
      options: ['Pour tous les crédits sans limite', 'Pour les parts assurées inférieures à 200 000 € par emprunteur (soit 400 000 € pour un couple assuré à 50/50)', 'Uniquement pour les crédits de moins de 50 000 €', 'Seulement si la maison est neuve'],
      correct: 1, rationale: 'Cela permet aux anciens malades, qui subissaient des surprimes énormes ou des refus, d\'emprunter au tarif normal si leur projet ne dépasse pas ce plafond.' },
    { q: 'Outre le plafond de 200 000 €, quelle est la condition d\'ÂGE pour bénéficier de la suppression du questionnaire médical ?',
      options: ['Le prêt doit être remboursé avant le 60ème anniversaire de l\'emprunteur', 'Il faut avoir plus de 65 ans', 'Il faut être mineur', 'L\'âge n\'a aucune importance'],
      correct: 0, rationale: 'Si vous empruntez sur 20 ans à 41 ans, le prêt se termine à 61 ans : vous devrez remplir le questionnaire médical.' },
    { q: 'Que fait la Loi Lemoine concernant le "Droit à l\'oubli" pour les anciens malades du cancer ou de l\'hépatite C ?',
      options: ['Elle le supprime', 'Elle réduit le délai du droit à l\'oubli de 10 ans à 5 ans après la fin du protocole thérapeutique (sans rechute). Passé ce délai, ils n\'ont plus à déclarer leur ancienne maladie à l\'assureur', 'Elle l\'allonge à 20 ans', 'Elle oblige à payer une surprime à vie'],
      correct: 1, rationale: 'C\'est une grande victoire pour les associations de patients. Une personne guérie depuis 5 ans est considérée par l\'assureur comme une personne n\'ayant jamais été malade.' },
    { q: 'Face à une demande de substitution (changement) d\'assurance par l\'emprunteur, de quel délai dispose la banque pour répondre ?',
      options: ['3 mois', '10 jours ouvrés à réception du dossier complet', 'Elle n\'est pas obligée de répondre', '48 heures'],
      correct: 1, rationale: 'La loi force les banques à être réactives. Si elle dépasse ce délai, elle s\'expose à des sanctions administratives.' },
    { q: 'Sur quel motif unique la banque a-t-elle le droit légal de REFUSER la nouvelle assurance (délégation) proposée par le client ?',
      options: ['Si l\'assurance ne vient pas de la banque', 'Si le client a de mauvais revenus', 'Uniquement si la nouvelle assurance ne présente pas un "Niveau de Garantie Équivalent" à l\'ancienne (les garanties décès, invalidité, etc. doivent être au moins aussi bonnes)', 'La banque ne peut jamais refuser'],
      correct: 2, rationale: 'L\'objectif de la banque est d\'être bien protégée. Si la nouvelle assurance couvre moins bien le risque de dos/psy par exemple, la banque refusera le changement.' },
    { q: 'La banque a-t-elle le droit d\'augmenter le taux d\'intérêt de votre crédit immobilier (ou de facturer des frais d\'avenant) parce que vous décidez de changer d\'assurance ?',
      options: ['Oui, une pénalité de 500 € est classique', 'Non, la loi interdit formellement à la banque de modifier les conditions du crédit (taux) ou d\'exiger des frais pour cette substitution d\'assurance', 'Oui, elle augmente le taux de 0,5 %', 'Uniquement la première année'],
      correct: 1, rationale: 'La banque ne peut pas se "venger" de la perte de ce produit financier très lucratif pour elle.' },
    { q: '(Challenge) Lors de la mise en place d\'un crédit de 300 000 € (plus de 200k), vous devez remplir le questionnaire de santé. Quel est le risque de faire une "Fausse déclaration intentionnelle" pour éviter une surprime ?',
      options: ['Une simple hausse de la cotisation', 'La déchéance de garantie : en cas de décès (même non lié à la maladie dissimulée), l\'assureur peut annuler le contrat et refuser de payer le capital restant dû à la banque, laissant la dette aux héritiers', 'Un avertissement du médecin', 'La banque annule ses intérêts'],
      correct: 1, rationale: 'Le mensonge à l\'assureur détruit le contrat. C\'est le pire calcul à faire, car le sinistre ne sera pas couvert.' },
    { q: '(Challenge) Quel est le document standardisé (instauré par le CCSF) qui permet à l\'emprunteur de comparer facilement les garanties exigées par sa banque avec celles proposées par l\'assureur externe ?',
      options: ['Le DPE (Diagnostic de Performance Énergétique)', 'Le RIB', 'La FSI (Fiche Standardisée d\'Information)', 'L\'avis d\'imposition'],
      correct: 2, rationale: 'Ce document liste des critères précis (ex: couverture des maladies du dos avec ou sans hospitalisation). Il suffit de donner cette fiche au nouvel assureur pour qu\'il propose un contrat 100% "équivalent" et inattaquable par la banque.' },
  ],
  'w14-d5': [
    { q: 'Qu\'est-ce qu\'une location "nue" ?',
      options: ['Une location pour les nudistes', 'Un logement loué non meublé (le locataire apporte ses propres meubles, électroménagers et literie)', 'Un logement sans fenêtres', 'Un terrain vague'],
      correct: 1, rationale: 'C\'est le bail classique par excellence en France. L\'appartement doit comporter les équipements de base (eau, chauffage, électricité, sanitaires), mais pas de mobilier.' },
    { q: 'Quelle est la durée standard d\'un bail de location nue (lorsque le propriétaire est un particulier physique) ?',
      options: ['1 an renouvelable', '3 ans renouvelable par tacite reconduction', '9 ans', '6 mois'],
      correct: 1, rationale: 'La loi de 89 offre une grande stabilité au locataire en nu (si le bailleur est une société / personne morale, le bail est de 6 ans).' },
    { q: 'Dans quelle catégorie de revenus le propriétaire bailleur d\'une location nue doit-il déclarer ses loyers aux impôts ?',
      options: ['Les Bénéfices Industriels et Commerciaux (BIC)', 'Les Revenus Fonciers', 'Les salaires et traitements', 'Les Bénéfices Agricoles (BA)'],
      correct: 1, rationale: 'C\'est la catégorie fiscale reine de l\'immobilier "nu". (La catégorie BIC est réservée à la location meublée).' },
    { q: 'Si vos revenus fonciers sont inférieurs à 15 000 € par an, vous relevez automatiquement du régime fiscal "Micro-foncier". Quel est son avantage ?',
      options: ['Les impôts sont nuls', 'Vous bénéficiez d\'un abattement forfaitaire de 30 % sur vos loyers bruts. Vous n\'êtes imposé que sur 70 % des loyers, sans avoir à garder ni justifier aucune facture de charges', 'La taxe foncière est offerte', 'Les loyers sont versés par la CAF'],
      correct: 1, rationale: 'L\'État simplifie la vie des petits bailleurs. Il estime que vos charges (assurances, petits travaux) représentent 30% du loyer.' },
    { q: 'Quel est l\'intérêt de renoncer au Micro-foncier pour choisir l\'option du "Régime Réel" (en location nue) ?',
      options: ['Avoir un abattement de 50 %', 'Pouvoir déduire le montant EXACT de ses charges réelles (gros travaux, intérêts d\'emprunt, assurances, taxe foncière) de ses loyers. Si ces charges dépassent 30 %, le régime réel est plus rentable pour faire baisser l\'impôt', 'Ne pas payer de CSG', 'Augmenter le loyer'],
      correct: 1, rationale: 'L\'investisseur qui achète à crédit et fait des travaux a des charges colossales la première année. Le régime réel lui permet même de créer un "déficit foncier".' },
    { q: 'Quel est le délai de préavis qu\'un locataire (en location nue) doit donner à son propriétaire s\'il veut quitter le logement (dans un secteur normal / détendu) ?',
      options: ['1 mois', '3 mois', '6 mois', 'Aucun préavis, il part quand il veut'],
      correct: 1, rationale: 'Le préavis standard est de 3 mois. Cependant, s\'il se trouve en "zone tendue" (grandes villes) ou s\'il perd son emploi, ce délai est réduit à 1 mois.' },
    { q: 'À l\'inverse, si le propriétaire veut donner "congé" (préavis de départ) à son locataire, quel délai doit-il respecter ?',
      options: ['1 mois à tout moment', '6 mois AVANT la date d\'échéance (date d\'anniversaire) des 3 ans du bail', '3 mois', '1 an après la signature'],
      correct: 1, rationale: 'Le propriétaire ne peut pas mettre le locataire dehors au milieu du bail. Il doit attendre la fin du cycle de 3 ans, et le prévenir très en avance.' },
    { q: 'Le propriétaire ne peut donner congé à son locataire que pour trois motifs très stricts et légaux. Lesquels ?',
      options: ['Refaire la décoration, augmenter le loyer, loger un ami', 'La vente du bien, la reprise pour y habiter lui-même (ou un parent proche), ou un motif légitime et sérieux (ex: loyers impayés, nuisances graves)', 'Le changement d\'agence, la fin de l\'année, le manque de soleil', 'La vente, la location Airbnb, la flemme'],
      correct: 1, rationale: 'Le droit au logement est très protégé en France. Les abus (faux congés pour vente) sont lourdement sanctionnés par les juges.' },
    { q: '(Challenge) Lors de l\'entrée dans les lieux d\'une location NUE, quel est le montant maximum que le bailleur peut exiger au titre du Dépôt de Garantie (la "caution") ?',
      options: ['2 mois de loyer charges comprises', '1 mois de loyer (hors charges)', '3 mois de loyer', 'Il n\'y a pas de limite'],
      correct: 1, rationale: 'Le locataire a d\'ailleurs un mois pour signaler un défaut de chauffe après son entrée.' },
    { q: '(Challenge) En cas d\'impayé de loyer, la loi impose au bailleur d\'envoyer un document officiel au locataire avant de lancer la clause résolutoire du bail. Quel est ce document ?',
      options: ['Un SMS de menace', 'Un Commandement de Payer délivré obligatoirement par un Commissaire de Justice (huissier)', 'Un e-mail en recommandé', 'Une lettre du maire'],
      correct: 1, rationale: 'Ce document laisse deux mois au locataire pour régler sa dette (ou saisir le FSL/juge) avant que la procédure d\'expulsion (très longue) ne démarre.' },
  ],
};
