/* Questions de la semaine 12. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w12-d0': [
    { q: 'Pourquoi la détermination de "l\'objectif" est primordiale avant de placer son argent ?',
      options: ['Pour pouvoir remplir sa déclaration d\'impôt', 'Pour que le banquier touche sa prime', 'Car c\'est l\'objectif de vie (maison, retraite) qui va imposer le risque, l\'horizon et la liquidité de l\'investissement', 'C\'est inutile, le but est juste d\'être riche'],
      correct: 2, rationale: 'On ne place pas 20 000€ pareil pour 1 an ou 30 ans.' },
    { q: 'Lequel de ces placements est INADAPTÉ pour "préparer un apport immobilier dans 18 mois" ?',
      options: ['Un ETF actions mondiales (Bourse) ou SCPI', 'Le Livret A', 'Un Compte à terme sur 1 an', 'Le PEL'],
      correct: 0, rationale: 'La bourse est trop volatile à court terme.' },
    { q: 'Quel est l\'objectif de "l\'épargne de précaution" ?',
      options: ['Viser le meilleur rendement possible', 'Se constituer une réserve hyper-liquide et sécurisée pour absorber les chocs imprévus', 'Défiscaliser', 'Devenir rentier'],
      correct: 1, rationale: 'Disponibilité et tranquillité priment sur le rendement.' },
    { q: 'Quelle enveloppe permet "d\'optimiser la transmission de son patrimoine sans droits de succession" ?',
      options: ['Le LDDS', 'Le CTO', 'Le PEA', 'L\'Assurance-vie'],
      correct: 3, rationale: 'Elle offre 152 500 € d\'abattement par bénéficiaire.' },
    { q: 'Quel est l\'objectif de "l\'investissement en capitalisation" ?',
      options: ['Faire grossir le patrimoine sur le long terme en réinvestissant la totalité des gains (intérêts composés)', 'Générer un revenu mensuel immédiat', 'Défiscaliser le salaire', 'Perdre de l\'argent pour l\'ISF'],
      correct: 0, rationale: 'On ne touche pas à l\'argent pour faire "boule de neige".' },
    { q: 'Quel est l\'objectif des investissements "de distribution" (SCPI, dividendes) ?',
      options: ['Geler le capital 40 ans', 'Viser exclusivement la plus-value', 'Générer des "cash-flows" réguliers (loyers, rentes) pour compléter ses fins de mois', 'Exonérer la succession'],
      correct: 2, rationale: 'Utile à la retraite pour pallier la baisse de revenus.' },
    { q: 'Un étudiant veut "se créer un très gros capital pour sa retraite dans 40 ans", que doit-il faire ?',
      options: ['Tout conserver sur des livrets réglementés', 'Accepter une exposition majeure aux actifs risqués (Bourse, ETF) en DCA, car l\'horizon très long efface la volatilité et offre le rendement', 'Souscrire uniquement des fonds euros', 'Acheter des voitures de collection'],
      correct: 1, rationale: 'L\'horizon long autorise et exige la prise de risque.' },
    { q: 'Pourquoi fixer un "objectif quantifié et temporel" (5 000€ dans 2 ans) est plus efficace ?',
      options: ['Cela oblige la banque à augmenter le taux', 'C\'est exigé par le banquier', 'Les impôts font une réduction', 'Cela permet de calculer l\'effort d\'épargne précis, d\'automatiser les virements et de maintenir la motivation'],
      correct: 3, rationale: 'Un objectif abstrait mène rarement au succès.' },
    { q: '(Challenge) Pour "abaisser son impôt sur le revenu" lourd (TMI 41%), quel produit regarder en priorité ?',
      options: ['Le Plan d\'Épargne Retraite (PER), car les versements sont déductibles du revenu imposable', 'Une Assurance-Vie', 'Un PEA', 'Un livret A'],
      correct: 0, rationale: 'Allège la pression fiscale immédiate tout en préparant la retraite.' },
    { q: '(Challenge) Comment la "gestion pilotée à horizon" gère-t-elle l\'objectif financier ?',
      options: ['Elle vend tous les actifs', 'Force l\'épargnant à payer plus', 'Bascule automatiquement l\'épargne des supports risqués vers des supports sécurisés à mesure que la date de l\'objectif approche, pour figer les gains', 'Transfère l\'argent sur compte courant'],
      correct: 2, rationale: 'Protège le capital d\'un krach final.' },
  ],
  'w12-d1': [
    { q: 'Qu\'est-ce qu\'un "déficit foncier" en immobilier locatif ?',
      options: ['Le fait de ne pas trouver de locataire', 'Le fait que le bien perde de la valeur à la revente', 'Le résultat comptable obtenu lorsque les charges déductibles (travaux, intérêts, taxes) sont SUPÉRIEURES aux loyers encaissés sur l\'année', 'Le montant de la taxe foncière'],
      correct: 2, rationale: 'Si vous encaissez 10 000 € de loyers mais que vous avez payé 15 000 € de travaux et d\'assurances, vous êtes en déficit foncier de 5 000 €.' },
    { q: 'Pour pouvoir créer et utiliser un déficit foncier, sous quel régime fiscal l\'investisseur (en location nue) doit-il obligatoirement déclarer ses loyers ?',
      options: ['Le régime Micro-foncier (déduction forfaitaire de 30 %)', 'Le régime du Réel (déduction des charges au centime près)', 'Le régime de la Flat Tax', 'Le régime agricole'],
      correct: 1, rationale: 'Le régime micro-foncier applique un abattement automatique. Pour déclarer une perte, il faut prouver comptablement ses charges via le régime réel.' },
    { q: 'Quel est le grand avantage (la "magie") du déficit foncier pour le propriétaire ?',
      options: ['L\'État lui rembourse les travaux', 'Ce déficit (hors intérêts d\'emprunt) vient se soustraire de ses REVENUS GLOBAUX (comme son salaire), ce qui fait baisser massivement son impôt sur le revenu', 'La banque annule ses intérêts', 'Le locataire doit payer la différence'],
      correct: 1, rationale: 'C\'est un puissant outil de défiscalisation. Si vous gagnez 50 000 € de salaire et avez 10 000 € de déficit foncier, les impôts vous taxeront comme si vous n\'aviez gagné que 40 000 €.' },
    { q: 'L\'imputation du déficit foncier sur le revenu global est-elle illimitée ?',
      options: ['Oui', 'Non, elle est strictement plafonnée par la loi à 10 700 € par an', 'Non, elle est limitée à 50 000 € par an', 'Elle est limitée à la valeur de la maison'],
      correct: 1, rationale: 'Si votre déficit est de 10 700 € (ou moins), tout vient gommer votre salaire. (Exception : un récent dispositif temporaire de rénovation énergétique pouvait monter ce plafond à 21 400 €).' },
    { q: 'Que se passe-t-il si votre déficit foncier de l\'année s\'élève à 15 000 € (dépassant ainsi le plafond de 10 700 €) ?',
      options: ['Les 4 300 € excédentaires sont définitivement perdus', 'Vous déduisez 10 700 € de votre salaire. L\'excédent de 4 300 € est "mis de côté" (reportable) et pourra servir à effacer vos bénéfices fonciers des 10 années suivantes', 'L\'État vous fait un chèque de 4 300 €', 'Le plafond est annulé'],
      correct: 1, rationale: 'Rien n\'est perdu ! L\'excédent servira de bouclier fiscal pour vos futurs loyers.' },
    { q: 'Laquelle de ces charges N\'EST PAS déductible pour créer du déficit foncier (en location nue) ?',
      options: ['Les frais de réparation de la toiture', 'Les primes d\'assurance PNO (Propriétaire Non Occupant)', 'Les travaux d\'agrandissement (ex: construction d\'une nouvelle pièce ou d\'une piscine)', 'La taxe foncière'],
      correct: 2, rationale: 'Le fisc accepte les travaux de réparation, d\'entretien et d\'amélioration. Il refuse formellement de déduire des travaux qui ajoutent du volume ou de la surface (construction/agrandissement).' },
    { q: 'Concernant les INTÉRÊTS D\'EMPRUNT du crédit immobilier, une règle spécifique s\'applique dans le déficit foncier. Laquelle ?',
      options: ['Ils sont déductibles du salaire', 'Ils sont interdits de déduction', 'Ils ne peuvent se déduire QU\'EXCLUSIVEMENT des revenus fonciers (les loyers). Ils ne peuvent JAMAIS créer un déficit imputable sur le revenu global (le salaire)', 'Ils sont remboursés par l\'assurance'],
      correct: 2, rationale: 'Le fisc fait le calcul en deux temps. Les intérêts effacent d\'abord les loyers. Seuls les "autres frais" (les travaux) peuvent ensuite créer le déficit qui viendra gommer votre salaire.' },
    { q: 'En contrepartie de cet avantage fiscal, quelle obligation le propriétaire a-t-il envers l\'État s\'il impute un déficit foncier sur son revenu global ?',
      options: ['Il doit baisser le loyer de moitié', 'Il a l\'obligation de louer le bien (en location nue) de façon continue pendant au moins 3 ans (jusqu\'au 31 décembre de la 3ème année suivant l\'imputation)', 'Il doit loger des étudiants', 'Il ne peut plus jamais vendre le bien'],
      correct: 1, rationale: 'Si vous faites de gros travaux en 2024 et profitez du déficit, vous ne pouvez pas vendre ou récupérer le bien pour y habiter avant le 31 décembre 2027. Sinon, le fisc annule votre avantage rétroactivement.' },
    { q: '(Challenge) Un contribuable réalise 30 000 € de travaux en 2024. Ses loyers sont de 10 000 €. Son déficit foncier total est donc de 20 000 €. Comment va-t-il l\'utiliser ?',
      options: ['Il déduit 20 000 € de son salaire', 'Il déduit 10 700 € de son salaire en 2024, et il reporte 9 300 € pour effacer ses bénéfices fonciers des 10 années suivantes', 'Il étale les 20 000 € sur 3 ans', 'Il perd tout'],
      correct: 1, rationale: 'C\'est la mécanique exacte du déficit foncier. L\'année des travaux crée le gros du déficit, le reste sert de réserve pour ne pas payer d\'impôts sur les loyers futurs.' },
    { q: '(Challenge) Le déficit foncier est-il soumis au "Plafonnement global des niches fiscales" de 10 000 € ?',
      options: ['Oui', 'Non, il échappe totalement à ce plafond car il s\'agit d\'une règle de détermination du revenu, et non d\'une "réduction d\'impôt" au sens strict', 'Uniquement pour les cadres', 'Oui, et il bloque les autres réductions'],
      correct: 1, rationale: 'C\'est l\'un des rares leviers de défiscalisation massive qui permet aux investisseurs de contourner le plafond des 10 000 €, tout en cumulant par exemple une femme de ménage et une loi Pinel.' },
  ],
  'w12-d2': [
    { q: 'Lorsqu\'un salarié part travailler à l\'étranger, ses années de travail compteront-elles obligatoirement pour sa retraite française ?',
      options: ['Oui, le monde entier cotise pour la France', 'Non, cela dépend de son statut (détaché ou expatrié) et du pays d\'accueil (présence d\'accords internationaux)', 'Oui, mais seulement s\'il parle français', 'Non, l\'expatriation annule tous les trimestres'],
      correct: 1, rationale: 'Partir à l\'étranger modifie profondément les règles de la protection sociale. Rien n\'est automatique.' },
    { q: 'Qu\'est-ce que le statut de travailleur "Détaché" ?',
      options: ['Un employé qui a été licencié', 'Un salarié envoyé à l\'étranger pour une mission temporaire par son employeur français. Il reste soumis à la Sécurité sociale française et continue de cotiser normalement pour sa retraite en France', 'Un indépendant travaillant seul', 'Un salarié engagé par une entreprise étrangère'],
      correct: 1, rationale: 'Le détachement est ultra-sécurisant. Pour la retraite, c\'est exactement comme s\'il travaillait à Paris, il accumule ses trimestres et points français.' },
    { q: 'À l\'inverse, qu\'est-ce que le statut d\'"Expatrié" stricto sensu ?',
      options: ['Un travailleur de l\'ONU', 'Un salarié (embauché localement ou envoyé par son entreprise) qui ne relève plus de la Sécurité sociale française. Il cotise au régime du pays où il travaille', 'Un retraité qui vit au soleil', 'Un étudiant en échange'],
      correct: 1, rationale: 'L\'expatrié quitte le système français. Si le pays d\'accueil n\'a pas d\'accord avec la France, ses années travaillées là-bas créent un "trou" dans sa carrière française.' },
    { q: 'Un Français s\'expatrie pour travailler en Allemagne (Union Européenne). Que se passe-t-il pour sa retraite ?',
      options: ['Il perd ses droits français', 'Grâce aux règlements européens de coordination, les trimestres travaillés en Allemagne seront reconnus par la France pour le calcul du "taux plein" (durée d\'assurance totale)', 'Il devra payer des impôts en double', 'L\'Allemagne paiera la retraite française'],
      correct: 1, rationale: 'L\'Europe facilite la mobilité. À la retraite, il touchera une pension française (pour ses années en France) et une pension allemande (pour ses années en Allemagne).' },
    { q: 'Que se passe-t-il si le Français s\'expatrie dans un pays HORS d\'Europe AVEC lequel la France a signé une "convention bilatérale de Sécurité sociale" (ex : Canada, États-Unis, Japon) ?',
      options: ['La France ignore ces années', 'Comme pour l\'Europe, les années de travail dans ce pays seront généralement prises en compte par la France pour vérifier si l\'assuré a ses trimestres pour le taux plein', 'La convention oblige à prendre la nationalité', 'Le salaire étranger est ajouté au salaire français'],
      correct: 1, rationale: 'Les conventions bilatérales évitent aux expatriés d\'être pénalisés sur leur durée de cotisation au moment de faire valoir leurs droits en France.' },
    { q: 'Que faire si le pays d\'expatriation n\'a AUCUN accord avec la France (ex : de nombreux pays d\'Asie ou du Moyen-Orient) ?',
      options: ['Les années sont perdues pour le régime français. L\'expatrié a alors intérêt à souscrire une assurance volontaire (ex : à la CFE) pour continuer à cotiser "à ses frais" au système français', 'L\'ambassade française donne des trimestres gratuits', 'L\'expatrié devra travailler jusqu\'à 75 ans', 'L\'ONU s\'occupe de la retraite'],
      correct: 0, rationale: 'La CFE permet de "racheter" son appartenance à la Sécurité sociale française en payant soi-même les cotisations.' },
    { q: 'Une fois à la retraite, peut-on percevoir sa pension de retraite française tout en habitant à l\'étranger ?',
      options: ['Non, il faut obligatoirement résider en France 6 mois par an', 'Oui, les caisses de retraite françaises versent la pension dans presque tous les pays du monde, directement sur un compte bancaire étranger', 'Uniquement dans l\'Union Européenne', 'Seulement si on garde une maison en France'],
      correct: 1, rationale: 'Le droit à la retraite est acquis. Que vous viviez en Espagne ou en Thaïlande, la France vous paiera votre pension.' },
    { q: 'Quelle démarche administrative ANNUELLE est strictement obligatoire pour les retraités vivant à l\'étranger afin de continuer à percevoir leur pension française ?',
      options: ['Venir en France passer un examen médical', 'Envoyer un "Certificat d\'existence" (certificat de vie) rempli par une autorité locale compétente (mairie, police, ambassade), prouvant qu\'ils sont toujours vivants', 'Renouveler leur passeport', 'Payer une taxe d\'expatriation'],
      correct: 1, rationale: 'Sans ce document de preuve de vie, les caisses suspendent immédiatement le paiement de la pension pour éviter les fraudes (familles cachant le décès pour toucher la retraite).' },
    { q: '(Challenge) Concernant la fiscalité (Prélèvements Sociaux), quel avantage ont les retraités fiscalement "non-résidents" français vivant à l\'étranger par rapport à un retraité vivant en France ?',
      options: ['Ils paient le double de CSG', 'Leurs pensions françaises sont généralement exonérées de la CSG, de la CRDS et de la CASA (soit plus de 9 % d\'économies) s\'ils ne sont pas à la charge de l\'assurance maladie française', 'L\'État français leur offre 10 % de bonus', 'Ils ne paient jamais d\'impôt sur le revenu'],
      correct: 1, rationale: 'Ne bénéficiant plus (par défaut) du système de santé français au quotidien, ils ne paient plus ces lourds prélèvements sociaux.' },
    { q: '(Challenge) Lors du calcul "européen" de la retraite (pour un salarié ayant fait sa carrière en France et en Italie), comment la France calcule-t-elle le montant final à verser ?',
      options: ['La France paie la totalité et demande le remboursement à l\'Italie', 'Par le calcul de la "Proratisation" : la France calcule une retraite théorique comme si toute la carrière avait été faite en France, puis ne paie que le pourcentage correspondant aux années réellement travaillées en France', 'La France paie le forfait SMIC', 'L\'Italie paie tout'],
      correct: 1, rationale: 'Si vous avez fait 10 ans en France et 30 ans en Italie (40 ans au total), la France calcule ce qu\'elle vous devrait pour 40 ans, puis vous en verse seulement le quart (10/40).' },
  ],
  'w12-d3': [
    { q: 'En droit de la propriété, qu\'est-ce que le "démembrement" ?',
      options: ['Le fait de détruire une maison', 'La séparation de la Pleine Propriété en deux droits distincts : l\'Usufruit d\'une part, et la Nue-Propriété d\'autre part', 'La vente d\'un terrain à un promoteur', 'Le partage des meubles lors d\'un divorce'],
      correct: 1, rationale: 'Propriété = Usufruit (usus + fructus) + Nue-propriété (abusus).' },
    { q: 'Quels sont les droits exclusifs de l\'Usufruitier ?',
      options: ['Il peut utiliser le bien (y habiter) et en percevoir les fruits (toucher les loyers s\'il le loue), mais il ne peut pas le vendre', 'Il peut vendre le bien seul', 'Il possède les murs mais ne peut pas y entrer', 'Il doit payer un loyer'],
      correct: 0, rationale: 'C\'est le statut parfait pour un conjoint survivant ou un retraité : il garde le contrôle sur l\'usage et les revenus de sa maison.' },
    { q: 'Quels sont les droits du Nu-Propriétaire ?',
      options: ['Il touche les loyers', 'Il détient le droit de disposition ("l\'abusus" - les murs) : il a la certitude de devenir un jour Plein Propriétaire. En attendant, il n\'a ni le droit d\'utiliser le bien, ni le droit d\'en tirer des revenus', 'Il doit habiter le bien', 'Il est le locataire'],
      correct: 1, rationale: 'Le Nu-Propriétaire est souvent un enfant. Il attend le décès de l\'usufruitier (son parent) pour récupérer le bien entier.' },
    { q: 'Que se passe-t-il obligatoirement à la mort de l\'usufruitier ?',
      options: ['Le bien est vendu aux enchères', 'L\'usufruit "s\'éteint" naturellement et rejoint la nue-propriété. Le nu-propriétaire devient automatiquement et immédiatement le Plein Propriétaire du bien', 'L\'usufruit est transmis aux héritiers de l\'usufruitier', 'L\'État saisit la maison'],
      correct: 1, rationale: 'C\'est la mécanique implacable du démembrement viager. Le droit s\'éteint avec la mort de la personne.' },
    { q: 'Quel est l\'immense AVANTAGE FISCAL lors de ce décès (quand le nu-propriétaire récupère l\'usufruit) ?',
      options: ['L\'État donne une subvention', 'Le "remembrement" de la pleine propriété se fait avec zéro impôt (les héritiers ne paient aucun droit de succession sur l\'usufruit qu\'ils récupèrent)', 'Les héritiers doivent payer 20 % d\'impôts', 'Les impôts locaux sont annulés à vie'],
      correct: 1, rationale: 'C\'est la raison pour laquelle les notaires encouragent les parents à donner la nue-propriété de leur vivant. Au décès, les enfants n\'auront rien à payer.' },
    { q: 'Durant le démembrement (la vie de l\'usufruitier), qui doit payer la Taxe Foncière et l\'entretien courant du bien (ex: peinture, plomberie courante) ?',
      options: ['Le Nu-Propriétaire (les enfants)', 'L\'Usufruitier (le parent qui habite ou loue)', 'Le notaire', 'Moitié/Moitié'],
      correct: 1, rationale: 'Celui qui profite de la maison paie les charges du quotidien et la taxe foncière. (Toutefois, une convention écrite peut parfois répartir les charges autrement).' },
    { q: 'En revanche, selon l\'article 605 du Code Civil, à qui incombent les "Grosses Réparations" (ex: refaire toute la toiture ou les murs porteurs) ?',
      options: ['À l\'Usufruitier', 'Au Nu-Propriétaire', 'À l\'assurance', 'À l\'État'],
      correct: 1, rationale: 'Les enfants, possédant la structure (les murs), doivent théoriquement payer pour la sauvegarde du bâtiment. (Dans la pratique familiale, les parents usufruitiers paient souvent, mais la loi désigne les nu-propriétaires).' },
    { q: 'L\'Usufruitier et le Nu-Propriétaire veulent vendre la maison. Comment cela se passe-t-il ?',
      options: ['L\'Usufruitier décide seul de la vente', 'Ils doivent vendre ensemble. Le prix de vente sera partagé entre eux en fonction de la valeur de l\'usufruit et de la nue-propriété au jour de la vente', 'Il est interdit de vendre avant le décès', 'L\'argent de la vente est bloqué à la banque'],
      correct: 1, rationale: 'L\'accord unanime est requis pour vendre (l\'un ne peut pas forcer l\'autre). Si la nue-propriété vaut 60% et l\'usufruit 40%, ils se partageront le chèque selon ces pourcentages.' },
    { q: '(Challenge) Lors d\'une donation de son vivant, comment le notaire et le fisc déterminent-ils la valeur financière de l\'Usufruit et de la Nue-Propriété ?',
      options: ['Au hasard', 'Selon le barème officiel de l\'Article 669 du Code Général des Impôts, qui se base uniquement sur l\'ÂGE de l\'usufruitier (plus l\'usufruitier est jeune, plus son usufruit a de la valeur, et moins la nue-propriété coûte cher fiscalement)', 'Selon l\'état de santé du parent', 'Selon les revenus des enfants'],
      correct: 1, rationale: 'Si le parent a 55 ans, l\'usufruit vaut 50% de la maison. S\'il a 85 ans, l\'usufruit ne vaut plus que 20%. Donner tôt est donc fiscalement très rentable.' },
    { q: '(Challenge) Concernant l\'Impôt sur la Fortune Immobilière (IFI), qui doit déclarer la valeur totale de la maison dans sa déclaration d\'impôts ?',
      options: ['Le Nu-Propriétaire (car il a les murs)', 'L\'Usufruitier (le parent), qui doit déclarer la maison pour sa valeur en PLEINE PROPRIÉTÉ, comme s\'il possédait tout', 'Personne, le démembrement annule l\'IFI', 'Chacun déclare sa quote-part (ex: 60/40)'],
      correct: 1, rationale: 'C\'est la règle fiscale (sauf quelques rares exceptions). L\'usufruitier, ayant la jouissance du bien, supporte le fardeau de l\'Impôt sur la Fortune Immobilière sur 100% de la valeur de la maison.' },
  ],
  'w12-d4': [
    { q: 'Vous êtes salarié et télétravaillez depuis chez vous. Devez-vous en informer votre assureur "Multirisque Habitation" (MRH) ?',
      options: ['Non, l\'assureur n\'a pas à le savoir', 'Oui, c\'est vivement recommandé (et souvent obligatoire), bien que le télétravail administratif (bureau) classique soit généralement couvert sans surprime par les contrats modernes', 'Uniquement si vous habitez en appartement', 'Non, c\'est l\'employeur qui appelle votre assureur'],
      correct: 1, rationale: 'Travailler chez soi modifie (légèrement) le risque (ordinateur branché toute la journée, risque d\'incendie). Il faut toujours prévenir son assureur d\'un changement d\'usage.' },
    { q: 'Que demande fréquemment l\'employeur au salarié pour autoriser le télétravail ?',
      options: ['Les factures de chauffage', 'Une "attestation d\'assurance habitation télétravail" fournie par l\'assureur MRH du salarié, prouvant que son logement est bien assuré', 'La facture de l\'ordinateur', 'Le contrat de location'],
      correct: 1, rationale: 'L\'entreprise veut s\'assurer que si un incendie ravage votre bureau à domicile, votre responsabilité civile et vos murs sont couverts.' },
    { q: 'L\'entreprise vous fournit un ordinateur et un écran pour télétravailler. En cas de vol (cambriolage) ou d\'incendie chez vous, quelle assurance remboursera ce matériel professionnel ?',
      options: ['L\'assurance habitation du salarié', 'C\'est l\'employeur (via son assurance professionnelle ou en assumant la perte) qui est responsable de son matériel confié au salarié. La MRH du salarié exclut généralement le matériel professionnel', 'La Sécurité sociale', 'Le salarié devra racheter le matériel'],
      correct: 1, rationale: 'Les contrats habitation classiques des particuliers excluent (ou limitent fortement) le matériel "à usage professionnel" appartenant à un tiers.' },
    { q: 'Vous glissez sur le câble de votre ordinateur et vous vous cassez le bras pendant vos heures de télétravail. Comment cet accident est-il considéré ?',
      options: ['Comme un accident domestique (non couvert par l\'employeur)', 'Comme un Accident du Travail (AT), pris en charge à 100 % par la Sécurité sociale et l\'employeur, car vous étiez sur votre lieu et temps de travail', 'Comme une maladie', 'Comme une faute grave de l\'employé'],
      correct: 1, rationale: 'La loi (Code du travail) stipule que tout accident survenu au domicile pendant les horaires de télétravail est présumé être un accident du travail, exactement comme si vous étiez au bureau.' },
    { q: 'Pendant votre télétravail, vous recevez un client ou un fournisseur chez vous. Il glisse et se blesse. Votre assurance habitation (MRH) classique le couvre-t-elle ?',
      options: ['Oui, c\'est un invité comme un autre', 'Non, la Responsabilité Civile "Vie Privée" de la MRH exclut formellement les activités professionnelles. Il faut une extension de garantie spécifique ou que l\'assurance de l\'entreprise intervienne', 'Oui, car il a ses chaussures', 'L\'État paiera l\'indemnisation'],
      correct: 1, rationale: 'Recevoir du public chez soi pour le travail transforme le domicile en local professionnel. Sans extension, l\'assurance refusera tout dédommagement.' },
    { q: 'Un salarié renverse du café sur son PROPRE ordinateur personnel qu\'il utilisait exceptionnellement pour travailler (BYOD). Qui paie ?',
      options: ['L\'employeur le rembourse à neuf', 'Si c\'est son propre matériel, c\'est l\'assurance habitation du salarié (si elle inclut une garantie dommage accidentel/casse) qui devra intervenir. L\'employeur n\'est pas responsable du matériel personnel de l\'employé', 'Le fabricant de l\'ordinateur', 'L\'assurance chômage'],
      correct: 1, rationale: 'L\'employeur n\'est responsable que du matériel qu\'il fournit. C\'est pourquoi utiliser son ordinateur personnel pour le travail est déconseillé sans une couverture adéquate.' },
    { q: 'Concernant le piratage informatique (Cyber-risque) lors du télétravail. Si les données de l\'entreprise sont volées via le wifi du salarié, l\'assurance habitation du salarié couvre-t-elle les préjudices ?',
      options: ['Oui, le wifi est assuré', 'Non, le risque Cyber professionnel est totalement exclu de la MRH des particuliers. L\'entreprise doit avoir sa propre assurance Cyber', 'Oui, mais l\'amende est pour le salarié', 'Seulement si le salarié a un VPN payant'],
      correct: 1, rationale: 'C\'est un des plus gros risques actuels. L\'entreprise doit sécuriser la connexion (VPN) et assumer le risque informatique.' },
    { q: 'Vous décidez de faire du "télétravail nomade" (ex: travailler depuis un café ou un Airbnb à l\'étranger). Que devez-vous vérifier ?',
      options: ['Uniquement la connexion internet', 'Si l\'assurance de l\'employeur (ou son accord formel) vous couvre en dehors de votre domicile déclaré, et si votre Responsabilité Civile est valable à l\'étranger', 'Si le pays accepte les euros', 'Rien, le télétravail est mondial'],
      correct: 1, rationale: 'Si l\'attestation de télétravail indique "au domicile principal", un accident survenu à Bali ne sera pas reconnu comme accident du travail.' },
    { q: '(Challenge) Fiscalement, si l\'employeur verse une "allocation forfaitaire" de télétravail (ex: 20 € par mois) pour dédommager le salarié (électricité, chauffage, internet). Cette somme est-elle soumise à l\'impôt sur le revenu pour le salarié ?',
      options: ['Oui, elle s\'ajoute au salaire', 'Non, cette allocation forfaitaire est exonérée d\'impôt sur le revenu (dans une certaine limite, souvent 2,50 € par jour de télétravail), car c\'est un remboursement de frais', 'Oui, elle est taxée à 30 %', 'Uniquement si on est cadre'],
      correct: 1, rationale: 'L\'administration fiscale considère que c\'est un remboursement de frais professionnels, ce n\'est donc pas un "gain" imposable.' },
    { q: '(Challenge) Un indépendant (freelance) travaille à domicile. Sa maison brûle, son matériel professionnel avec, l\'empêchant de travailler pendant 3 mois. Sa MRH classique "Vie privée" va-t-elle compenser sa perte de salaire ?',
      options: ['Oui, la MRH compense tout', 'Non. Sans contrat spécifique "Multirisque Professionnelle" avec une garantie "Perte d\'exploitation", il ne sera jamais indemnisé de sa perte de revenus', 'L\'État lui versera le chômage', 'La mairie paie l\'indemnisation'],
      correct: 1, rationale: 'La MRH d\'un particulier ne couvrira ni le stock, ni le manque à gagner professionnel d\'un indépendant. Il doit impérativement avoir un contrat Pro.' },
  ],
  'w12-d5': [
    { q: 'Pourquoi la banque exige-t-elle une "garantie" lorsqu\'elle vous accorde un crédit immobilier ?',
      options: ['Pour que vous payiez plus de frais', 'Pour s\'assurer de récupérer son argent si vous ne payez plus vos mensualités', 'Pour vérifier l\'état de la maison', 'C\'est une taxe de l\'État'],
      correct: 1, rationale: 'La banque ne prête des centaines de milliers d\'euros que si elle a un moyen juridique et financier de se rembourser en cas de défaillance de l\'emprunteur.' },
    { q: 'Quelles sont les deux grandes familles de garanties sur le marché immobilier français ?',
      options: ['Le Livret A et le PEA', 'Les garanties réelles (l\'hypothèque / le privilège) et le cautionnement mutuel (sociétés de caution)', 'Le CDD et le CDI', 'L\'usufruit et la nue-propriété'],
      correct: 1, rationale: 'Soit on prend le bien en garantie (hypothèque), soit on demande à une entreprise financière de se porter garante pour l\'emprunteur (caution).' },
    { q: 'Qu\'est-ce qu\'une "Hypothèque" ?',
      options: ['Un prêt à taux zéro', 'Un acte notarié qui donne le droit à la banque, si l\'emprunteur ne paie plus, de faire saisir le bien immobilier et de le vendre aux enchères judiciaires pour se rembourser', 'Un contrat de location', 'L\'assurance du crédit'],
      correct: 1, rationale: 'C\'est une garantie "réelle" car elle pèse directement sur "la chose" (la maison).' },
    { q: 'Par quel intermédiaire obligatoire doit passer la mise en place d\'une hypothèque ?',
      options: ['L\'agent immobilier', 'La mairie', 'Le notaire (qui rédige l\'acte authentique et l\'inscrit au Service de la Publicité Foncière)', 'Le tribunal'],
      correct: 2, rationale: 'L\'hypothèque exige un formalisme lourd et coûteux, ce qui implique des "frais de garantie" à payer par l\'acheteur lors de la signature chez le notaire.' },
    { q: 'Qu\'est-ce que le "Cautionnement" (ex: caution Crédit Logement) qui équipe la très grande majorité des prêts aujourd\'hui ?',
      options: ['La banque demande à vos parents de payer', 'Une société financière (la caution) s\'engage auprès de la banque à payer à votre place si vous êtes défaillant. La caution se retournera ensuite contre vous pour récupérer les fonds (à l\'amiable ou par revente du bien)', 'C\'est une assurance annulation', 'C\'est la caution versée au locataire'],
      correct: 1, rationale: 'Il n\'y a pas d\'hypothèque notariée. Le fonds de garantie mutuel gère le risque financièrement, ce qui évite à la banque de s\'occuper d\'une saisie immobilière.' },
    { q: 'Au moment de la signature du crédit, l\'emprunteur paie des frais pour cette société de Caution. Quel est le gros avantage financier de la Caution par rapport à l\'hypothèque à la fin du prêt ?',
      options: ['Elle est gratuite au début', 'Une partie de la somme versée initialement (souvent 60 % de la participation au Fonds Mutuel) est "restituable" (remboursée) à l\'emprunteur à la fin du crédit s\'il n\'a eu aucun incident de paiement', 'La caution rembourse le notaire', 'La caution annule les impôts'],
      correct: 1, rationale: 'C\'est l\'argument numéro 1 des cautions comme Crédit Logement. L\'hypothèque, elle, est à "fonds perdus" (vous ne récupérez jamais les frais payés au notaire).' },
    { q: 'Vous avez fait un crédit sur 25 ans garanti par une Hypothèque. Finalement, vous vendez la maison au bout de 5 ans pour déménager. Devez-vous payer des "Frais de mainlevée" ?',
      options: ['Non, l\'hypothèque disparaît toute seule', 'Oui. Pour effacer l\'hypothèque du registre et rassurer le nouvel acheteur, le notaire doit faire un acte de "mainlevée", ce qui engendre des frais importants (environ 0,5 à 1 % du crédit)', 'C\'est la banque qui paie les frais', 'Seulement si la maison a perdu de la valeur'],
      correct: 1, rationale: 'C\'est le grand inconvénient de l\'hypothèque si l\'on revend son bien avant la fin du crédit. (Avec une caution, il n\'y a aucun frais de mainlevée).' },
    { q: 'Pourquoi une banque préfère-t-elle souvent que vous passiez par une "Caution" plutôt qu\'une Hypothèque ?',
      options: ['Parce que ça coûte plus cher', 'Parce que si le client ne paie plus, la banque est remboursée financièrement et immédiatement par l\'organisme de caution, évitant ainsi des années de procédure judiciaire lourde pour saisir et vendre la maison', 'Parce qu\'elle n\'aime pas les notaires', 'Parce que la loi l\'oblige'],
      correct: 1, rationale: 'L\'organisme de caution absorbe la gestion du recouvrement. La banque a son argent sans s\'encombrer de la revente d\'une maison.' },
    { q: '(Challenge) Un acheteur monte un dossier de prêt. L\'organisme de caution (qui est très strict sur les taux d\'endettement) REFUSE de se porter garant de son dossier. Que se passe-t-il alors ?',
      options: ['Le prêt est définitivement impossible', 'L\'acheteur doit prendre une assurance vie', 'La banque, si elle veut quand même accorder le prêt, n\'aura d\'autre choix que d\'exiger une "Hypothèque" ou un "Privilège" en garantie de substitution', 'La banque prêtera sans aucune garantie'],
      correct: 2, rationale: 'Les sociétés de caution sont indépendantes des banques. Un refus de caution n\'est pas un refus de prêt, mais cela oblige la banque à prendre le bien lui-même en garantie matérielle.' },
    { q: '(Challenge) Dans le cadre des garanties "réelles", qu\'est-ce que le Privilège de Prêteur de Deniers (PPD) (récemment réformé sous le nom d\'"Hypothèque légale spéciale du prêteur de deniers") ?',
      options: ['C\'est un taux d\'usure', 'C\'est une variante de l\'hypothèque, moins chère, mais qui ne peut garantir QUE l\'achat de l\'existant (maison ou appartement ancien). Elle ne peut pas garantir le financement de travaux ou de la construction', 'C\'est une garantie offerte par l\'État', 'Une garantie pour prêter à ses enfants'],
      correct: 1, rationale: 'Son avantage principal était d\'être exonéré de la taxe de publicité foncière. Si vous faites construire une maison, ce privilège ne s\'applique pas, ce sera l\'hypothèque classique' },
  ],
};
