/* Questions de la semaine 13. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w13-d0': [
    { q: 'Qu\'est-ce que le "profil d\'investisseur" ?',
      options: ['L\'évaluation de la situation, des objectifs et de la "tolérance au risque" (capacité psychologique et financière à subir une perte) du client', 'La profession de l\'investisseur', 'Le score de la Banque de France', 'Le montant de l\'héritage'],
      correct: 0, rationale: 'Détermine les produits adaptés.' },
    { q: 'Est-ce une obligation de définir le profil d\'un investisseur ?',
      options: ['Non, c\'est juste amusant', 'Uniquement pour les personnes âgées', 'Oui, c\'est une obligation légale stricte (MIF 2/DDA) : le conseiller doit s\'assurer que le produit "convient" au client', 'Seulement si on emprunte'],
      correct: 2, rationale: 'Le KYC protège contre la vente de produits toxiques.' },
    { q: 'Dans le questionnaire (KYC), que mesure : "Que feriez-vous si votre portefeuille perdait 20% ?"',
      options: ['Votre capacité d\'emprunt', 'Vos revenus annuels', 'Votre espérance de vie', 'Votre Tolérance Psychologique au Risque (les émotions face à la perte)'],
      correct: 3, rationale: 'Détecte la propension à paniquer.' },
    { q: 'Quel est le comportement d\'un profil "Prudent" ?',
      options: ['Accepte 30% de perte', 'Privilégie la protection absolue de son capital, quitte à avoir un rendement très faible (inférieur à l\'inflation)', 'Investit dans les start-ups', 'Ne garde jamais d\'épargne'],
      correct: 1, rationale: 'Le fonds euros et les livrets sont privilégiés.' },
    { q: 'Qu\'est-ce qu\'un profil "Équilibré" ?',
      options: ['Cherche le compromis : protège une partie, et accepte un risque modéré sur le reste (ex: 50% fonds euros / 50% ETF)', 'Investit 50% France / 50% USA', 'Change d\'avis tous les jours', 'Sans dettes'],
      correct: 0, rationale: 'Profil par défaut de nombreux épargnants.' },
    { q: 'Que caractérise un profil "Dynamique" ?',
      options: ['En mouvement géographique', 'Fait du trading toutes les 5 min', 'Privilégie le rendement à long terme et accepte de fortes fluctuations boursières (souvent 80-100% actions)', 'Emprunte massivement'],
      correct: 2, rationale: 'L\'horizon long permet cette volatilité.' },
    { q: 'Quel élément FACTUEL bloque mathématiquement le profil sur "Prudent" même si on aime le risque ?',
      options: ['Être étudiant', 'La couleur de la carte bancaire', 'Le lieu d\'habitation', 'Un "Horizon de placement" très court (besoin de l\'argent dans 1 an)'],
      correct: 3, rationale: 'On ne joue pas l\'argent d\'un achat de maison imminent.' },
    { q: 'Pourquoi le conseiller évalue-t-il vos "Connaissances financières" ?',
      options: ['Pour une embauche', 'Il lui est interdit de vendre un produit complexe (structuré, private equity) que le client ne comprend pas', 'Pour vérifier les diplômes', 'Sondage de l\'État'],
      correct: 1, rationale: 'Évite la mauvaise surprise.' },
    { q: '(Challenge) Un client dit être "dynamique" mais n\'a AUCUNE épargne de précaution. Le conseiller doit-il le valider en dynamique ?',
      options: ['Oui, le client est roi', 'Oui, car il a un gros salaire', 'Non. La "capacité financière à subir une perte" est nulle. S\'il a un coup dur, il vendra à perte. Il faut d\'abord l\'épargne d\'urgence', 'L\'AMF décidera'],
      correct: 2, rationale: 'L\'adéquation budget/risque est primordiale.' },
    { q: '(Challenge) Dans l\'assurance-vie, quelle solution technique délègue la gestion de votre profil ?',
      options: ['La "Gestion sous mandat" (gestion pilotée) : une société anime le portefeuille en respectant strictement votre Profil initial', 'Le Livret A', 'La clôture des comptes', 'La rente anticipée'],
      correct: 0, rationale: 'Option "tranquillité" par défaut de nombreux PER.' },
  ],
  'w13-d1': [
    { q: 'Par défaut, comment l\'administration fiscale prend-elle en compte les dépenses professionnelles d\'un salarié (trajet, repas) sur sa déclaration de revenus ?',
      options: ['Elle n\'en tient pas compte du tout', 'Elle demande tous les tickets de caisse', 'Elle applique un "abattement forfaitaire de 10 %" sur le salaire déclaré (dans une certaine limite)', 'Elle rembourse 500 € à tous les salariés'],
      correct: 2, rationale: 'L\'État suppose que le salarié dépense environ 10 % de son salaire pour aller travailler et s\'alimenter. Ce montant est automatiquement déduit du revenu imposable sans que le contribuable n\'ait rien à justifier.' },
    { q: 'Qu\'est-ce que "l\'option pour les frais réels" ?',
      options: ['Le droit d\'utiliser la voiture de fonction le week-end', 'Une option fiscale permettant au salarié de renoncer à l\'abattement forfaitaire de 10 % s\'il estime que ses dépenses professionnelles ont été SUPÉRIEURES à ces 10 %, afin de déduire le montant exact de ses frais de son revenu imposable', 'L\'obligation de manger à la cantine', 'Une taxe sur les déplacements'],
      correct: 1, rationale: 'C\'est très avantageux pour les personnes qui habitent loin de leur travail et qui font beaucoup de kilomètres.' },
    { q: 'Quelle est la dépense numéro 1 qui justifie généralement le passage aux "frais réels" ?',
      options: ['L\'achat de costumes/vêtements de travail', 'Les frais kilométriques (les trajets aller-retour entre le domicile et le lieu de travail avec son véhicule personnel)', 'Les frais de repas', 'L\'achat d\'un ordinateur'],
      correct: 1, rationale: 'Les frais de voiture (essence, assurance, usure) représentent un budget énorme, souvent bien supérieur à l\'abattement automatique de 10 %.' },
    { q: 'Sur quelle distance maximale (trajet aller) le fisc accepte-t-il la déduction des frais kilométriques sans exiger de justificatifs exceptionnels ?',
      options: ['10 km', '40 km (soit 80 km aller-retour par jour)', '100 km', 'Il n\'y a aucune limite'],
      correct: 1, rationale: 'Si vous habitez à 60 km de votre travail, le fisc ne retiendra que 40 km pour le calcul, à moins que vous puissiez justifier de circonstances particulières (difficulté à trouver un emploi près de chez vous, mutation du conjoint).' },
    { q: 'Pour calculer les frais liés à l\'utilisation de son véhicule personnel, que propose le fisc au salarié pour lui simplifier la vie ?',
      options: ['De fournir toutes les factures d\'essence et de garage de l\'année', 'D\'utiliser le "barème kilométrique" officiel, qui calcule une déduction globale (incluant carburant, assurance, entretien, dépréciation) en fonction de la puissance fiscale du véhicule et des kilomètres parcourus', 'De déduire le prix d\'achat de la voiture', 'De demander à son patron'],
      correct: 1, rationale: 'C\'est beaucoup plus simple que de garder chaque ticket d\'essence. Vous multipliez les kilomètres pros de l\'année par un taux défini par le fisc.' },
    { q: 'Concernant les frais de repas du midi, quelle est la règle si le salarié est obligé de manger au restaurant ou à la cantine ?',
      options: ['Il peut déduire l\'intégralité de l\'addition (même un repas gastronomique)', 'Il ne peut déduire que la différence entre le coût réel du repas payé et la valeur d\'un repas pris à domicile (fixée forfaitairement à environ 5,35 € en 2024), en déduisant les tickets restaurants fournis par l\'employeur', 'Les repas ne sont jamais déductibles', 'Il peut déduire 50 € par jour'],
      correct: 1, rationale: 'Manger est un besoin vital (professionnel ou non). Le fisc n\'accepte donc de déduire que le SURCOÛT lié à l\'obligation de manger hors de chez soi.' },
    { q: 'Quelles sont les obligations du contribuable vis-à-vis des impôts s\'il opte pour les frais réels ?',
      options: ['Il doit envoyer un dossier papier tous les mois', 'Il doit détailler ses calculs sur une note jointe à sa déclaration et CONSERVER tous les justificatifs (factures, attestations d\'employeur, devis) pendant 3 ans en cas de contrôle fiscal', 'Il doit faire valider son calcul par un expert-comptable', 'Aucune obligation'],
      correct: 1, rationale: 'Les frais réels font l\'objet de très nombreux redressements fiscaux. Si vous ne pouvez pas prouver vos kilomètres (ex: attestation de l\'employeur sur le nombre de jours travaillés) ou vos achats de matériel, le fisc annulera la déduction.' },
    { q: 'Les frais liés au Télétravail à domicile (chauffage, électricité de la pièce, achat de mobilier de bureau) peuvent-ils être déduits en frais réels ?',
      options: ['Non, jamais', 'Oui, s\'ils ne sont pas déjà remboursés par une allocation forfaitaire de l\'employeur (le contribuable peut soit déduire ses factures au prorata de la surface du bureau, soit opter pour un forfait télétravail admis par le fisc)', 'Oui, mais seulement la box internet', 'Seulement si la maison appartient à l\'entreprise'],
      correct: 1, rationale: 'Avec le boom du télétravail, le fisc a clarifié les règles : les coûts de la pièce bureau sont déductibles au prorata du temps et de l\'espace.' },
    { q: '(Challenge) Un couple marié remplit une seule déclaration de revenus. Monsieur a beaucoup de route et veut passer aux frais réels. Madame travaille à côté de chez elle et préfère garder l\'abattement de 10 %. Est-ce possible ?',
      options: ['Non, le choix doit être identique pour les deux conjoints', 'Oui, l\'option pour les frais réels est strictement INDIVIDUELLE. Chaque salarié du foyer fiscal choisit la méthode la plus avantageuse pour lui', 'Non, les frais réels ne sont que pour les célibataires', 'Le fisc fera une moyenne des deux'],
      correct: 1, rationale: 'Dans un même foyer, on peut parfaitement mixer l\'abattement de 10 % pour l\'un et les frais réels pour l\'autre.' },
    { q: '(Challenge) Un salarié fait le calcul : ses frais réels de l\'année s\'élèvent à 2 500 €. S\'il garde l\'abattement automatique de 10 %, cela représente une déduction de 3 000 €. Que doit-il faire lors de sa déclaration ?',
      options: ['Coche la case des frais réels par honnêteté', 'Il ne déclare aucun frais réel. L\'administration lui appliquera automatiquement la déduction de 3 000 € (les 10 %), ce qui est plus avantageux pour lui', 'Il additionne les deux (5 500 €)', 'Il déclare un déficit'],
      correct: 1, rationale: 'Les impôts appliquent par défaut le régime de l\'abattement de 10 %. On n\'opte pour les frais réels QUE si cela permet de déduire PLUS que les 10 %.' },
  ],
  'w13-d2': [
    { q: 'Dans le système de retraite, qu\'appelle-t-on le "rachat de trimestres" (ou VPL - Versement Pour la Retraite) ?',
      options: ['Le fait d\'acheter la retraite d\'une autre personne', 'Un dispositif légal permettant à un assuré de verser volontairement de l\'argent à la Sécurité sociale pour acquérir des trimestres manquants, afin d\'éviter une décote et/ou d\'améliorer le montant de sa future pension', 'Le paiement d\'une amende pour travail non déclaré', 'L\'obligation de rembourser ses allocations chômage'],
      correct: 1, rationale: 'Si l\'on n\'atteint pas la durée d\'assurance requise pour le taux plein, on peut acheter des trimestres "fictifs" pour combler le trou.' },
    { q: 'Quelles sont les deux principales raisons (les deux grands cas de figure) qui autorisent légalement un rachat de trimestres ?',
      options: ['Les années de vacances et le chômage', 'Les années d\'études supérieures sanctionnées par un diplôme, ET les années civiles incomplètes (où l\'on a travaillé, mais pas assez gagné pour valider 4 trimestres)', 'Le travail à l\'étranger et les arrêts maladie', 'La naissance d\'enfants et les accidents'],
      correct: 1, rationale: 'Ce sont les deux grands motifs de rachat prévus par la loi pour réparer une entrée tardive sur le marché du travail ou des temps partiels.' },
    { q: 'Quel est le nombre MAXIMUM de trimestres qu\'un assuré est autorisé à racheter au cours de sa vie (tous régimes confondus) ?',
      options: ['4 trimestres (1 an)', '12 trimestres (soit 3 ans)', '20 trimestres (soit 5 ans)', 'Illimité'],
      correct: 1, rationale: 'L\'État limite le rachat à 3 années pleines (12 trimestres) pour ne pas déséquilibrer financièrement le système par répartition.' },
    { q: 'Sur quels critères la Sécurité sociale calcule-t-elle le "PRIX" d\'un trimestre à racheter ?',
      options: ['C\'est un prix fixe de 1000 € pour tout le monde', 'Le prix dépend de 3 éléments : l\'ÂGE de l\'assuré au moment du rachat, son NIVEAU DE REVENU des 3 dernières années, et l\'OPTION de rachat choisie', 'Il dépend uniquement du nombre d\'enfants', 'Le prix est fixé par l\'employeur'],
      correct: 1, rationale: 'Plus vous achetez tard (ex : à 60 ans plutôt qu\'à 30 ans), plus c\'est cher. Plus vous êtes riche, plus c\'est cher. Un trimestre peut coûter de 1 000 € à près de 6 000 € !' },
    { q: 'Il existe deux options de rachat. L\'Option 1 s\'appelle "Taux seul". Quel est son but exact ?',
      options: ['Elle augmente le taux ET la durée de cotisation', 'Elle agit uniquement pour atténuer ou annuler la "Décote" (la baisse du pourcentage) sur le calcul de la pension, mais elle n\'améliore pas le montant au prorata des années travaillées', 'Elle permet de doubler la pension', 'Elle donne des trimestres gratuits'],
      correct: 1, rationale: 'C\'est l\'option la moins chère. Elle répare la "pénalité" du taux qui s\'éloigne des 50%, mais la pension reste calculée sur les seules années réellement cotisées.' },
    { q: 'Quel est le principal AVANTAGE FISCAL lié au coût très élevé du rachat de trimestres ?',
      options: ['Il annule la taxe foncière', 'L\'intégralité des sommes versées pour racheter des trimestres est 100 % DÉDUCTIBLE de vos revenus bruts imposables l\'année du paiement (sans plafonnement)', 'Il permet d\'avoir 2 parts fiscales', 'La TVA est remboursée'],
      correct: 1, rationale: 'C\'est ce qui rend l\'opération parfois très rentable pour les cadres supérieurs (TMI à 30 ou 41 %). S\'ils achètent pour 10 000 € de trimestres, ils peuvent économiser 4 100 € d\'impôts sur le revenu la même année.' },
    { q: 'D\'un point de vue stratégique, à quel âge les experts conseillent-ils généralement de procéder au rachat de trimestres ?',
      options: ['À 25 ans', 'Autour de 40 ans', 'Le plus tard possible (souvent vers 58-60 ans), lorsque la carrière est stabilisée, qu\'on connaît la date exacte de son départ et ses vrais revenus, afin d\'être certain que le rachat sera rentable', 'Après la liquidation de la retraite'],
      correct: 2, rationale: 'Bien que le trimestre coûte moins cher à 30 ans, racheter jeune est un pari à l\'aveugle. Une réforme des retraites ou une période de chômage imprévue pourrait rendre ces trimestres achetés totalement inutiles 30 ans plus tard.' },
    { q: 'Pour inciter les jeunes actifs, quel "cadeau" l\'État accorde-t-il s\'ils rachètent leurs années d\'études (jusqu\'à 4 trimestres) dans les 10 ans suivant l\'obtention de leur diplôme ?',
      options: ['Ils sont gratuits', 'Ils bénéficient d\'un abattement forfaitaire (une réduction importante, souvent de l\'ordre de 400 €) sur le prix de chaque trimestre', 'Ils obtiennent 2 trimestres pour le prix d\'un', 'La banque paie le crédit'],
      correct: 1, rationale: 'C\'est la seule exception où il peut être intéressant de racheter jeune (grâce au rabais + au coût initial bas dû au jeune âge et au salaire souvent de début de carrière).' },
    { q: '(Challenge) Un rachat de trimestre au régime de base (CNAV) permet-il également de gagner des points sur la retraite complémentaire (Agirc-Arrco) ?',
      options: ['Jamais, ce sont deux caisses totalement distinctes', 'Oui, automatiquement et gratuitement', 'Seulement si on a choisi l\'Option 2 (Taux + Durée d\'assurance). L\'Agirc-Arrco n\'accordera pas de nouveaux points gratuits, mais le rachat évitera l\'application de la décote Agirc-Arrco', 'Oui, l\'Agirc-Arrco double les trimestres'],
      correct: 2, rationale: 'Racheter pour la base sauve votre "taux plein". Du coup, l\'Agirc-Arrco ne vous appliquera pas de décote. Mais elle ne vous versera pas d\'argent supplémentaire car vous n\'avez pas acheté de "points" chez elle.' },
    { q: '(Challenge) Un assuré a commencé à travailler tard (22 ans). Il veut partir en retraite anticipée via le dispositif "Carrières Longues" à 60 ans. Il rachète 8 trimestres d\'études pour atteindre la durée requise. Que va-t-il se passer ?',
      options: ['Il partira à 60 ans', 'Le rachat sera refusé', 'Le dispositif "Carrières longues" refusera son départ anticipé, car les trimestres rachetés NE SONT PAS considérés comme des "trimestres cotisés" valables pour le départ anticipé (seul le travail réel compte)', 'Il touchera une surcote'],
      correct: 2, rationale: 'C\'est le piège absolu ! Le départ anticipé exige du vrai travail (l\'effort contributif). On ne peut pas "s\'acheter" un départ en retraite anticipée.' },
  ],
  'w13-d3': [
    { q: 'En droit de la transmission (succession et donation), qu\'est-ce qu\'un "abattement" ?',
      options: ['La destruction de la maison avant la vente', 'Une somme forfaitaire déduite de la part d\'héritage ou de la donation, sur laquelle le bénéficiaire ne paiera AUCUN impôt', 'Les frais pris par le notaire', 'Un impôt payé par l\'État'],
      correct: 1, rationale: 'L\'État autorise de transmettre de l\'argent ou des biens "en franchise d\'impôt" jusqu\'à un certain montant.' },
    { q: 'Quel est le montant de l\'abattement classique applicable entre un PARENT et un ENFANT ?',
      options: ['31 865 €', '80 724 €', '100 000 €', '152 500 €'],
      correct: 2, rationale: 'Chaque parent peut transmettre jusqu\'à 100 000 € à chaque enfant sans aucun droit de succession ou de donation. Un couple peut donc donner 200 000 € à un enfant sans impôt.' },
    { q: 'En matière de "donation" (du vivant), tous les combien d\'années ces abattements légaux (notamment les 100 000 € parent-enfant) se "rechargent-ils" (se remettent à zéro) ?',
      options: ['Tous les 5 ans', 'Tous les 10 ans', 'Tous les 15 ans', 'Jamais, c\'est une seule fois dans la vie'],
      correct: 2, rationale: 'C\'est l\'essence même de l\'anticipation successorale. Donner tôt permet de purger le délai de 15 ans pour recommencer plus tard ou avoir un abattement neuf pour le décès.' },
    { q: 'En cas de DÉCÈS (succession), quel est le montant de l\'abattement pour le CONJOINT SURVIVANT (marié ou pacsé avec testament) ?',
      options: ['100 000 €', '80 724 €', 'Il n\'y a pas d\'abattement : il bénéficie d\'une EXONÉRATION TOTALE (0 € d\'impôt sur 100 % de son héritage)', '1 594 €'],
      correct: 2, rationale: 'Depuis la loi TEPA de 2007, le veuf ou la veuve (marié ou pacsé) ne paie jamais d\'impôt sur la succession, que l\'héritage soit de 10 000 € ou de 10 millions d\'euros.' },
    { q: 'Quel est l\'abattement légal lors d\'une succession entre un GRAND-PARENT et un PETIT-ENFANT ?',
      options: ['100 000 €', '31 865 € (dans le cas d\'une donation, 1 594 € pour une succession classique hors représentation)', 'Il n\'y a aucun abattement', '15 932 €'],
      correct: 1, rationale: 'Pour sauter une génération sans douleur fiscale, il faut le faire de son vivant (donation) pour profiter de l\'abattement de 31 865 €.' },
    { q: 'Quel est l\'abattement légal entre FRÈRES et SŒURS (hors conditions très restrictives de cohabitation et d\'âge) ?',
      options: ['100 000 €', '80 724 €', '15 932 €', '1 594 €'],
      correct: 2, rationale: 'Dès que l\'on quitte la ligne directe (parents/enfants), la protection fiscale s\'effondre. Au-delà de ces ~16 000 €, le frère sera lourdement taxé à 35% ou 45%.' },
    { q: 'Outre les abattements de parenté, il existe le "Don familial de sommes d\'argent" (loi TEPA). Quel est son montant maximum exonéré ?',
      options: ['10 000 €', '31 865 € (pour un don strictement en argent cash/virement)', '100 000 €', '152 500 €'],
      correct: 1, rationale: 'C\'est un abattement supplémentaire spécifiquement créé pour faciliter la circulation de l\'argent vers les jeunes générations.' },
    { q: 'Quelles sont les deux conditions strictes liées à l\'âge pour pouvoir utiliser cet abattement supplémentaire de 31 865 € (Don familial de sommes d\'argent) ?',
      options: ['Le donateur doit être en bonne santé', 'Le donateur doit avoir MOINS de 80 ans au jour du don, ET le bénéficiaire (l\'enfant/petit-enfant) doit être MAJEUR (avoir au moins 18 ans)', 'Le donateur doit être retraité', 'L\'enfant doit s\'en servir pour acheter une maison'],
      correct: 1, rationale: 'Ce coup de pouce fiscal est interdit si le parent a plus de 80 ans ou si l\'enfant est mineur.' },
    { q: '(Challenge) Un père de 60 ans donne à sa fille de 25 ans un appartement valant 100 000 €, plus un virement bancaire de 31 865 €. Combien d\'impôts vont-ils payer ?',
      options: ['0 €, car les deux abattements se cumulent parfaitement', 'Ils paieront des impôts sur les 31 865 €', 'Ils paieront 60 % d\'impôts sur le total', 'La donation est annulée'],
      correct: 0, rationale: 'C\'est l\'optimisation fiscale classique. L\'appartement absorbe l\'abattement classique (100k) et le cash absorbe l\'abattement spécifique "loi TEPA" (31.8k). Le transfert de 131 865 € est totalement net d\'impôt.' },
    { q: '(Challenge) Que se passe-t-il fiscalement sur la somme qui DÉPASSE l\'abattement (ex: un parent donne 150 000 € à son enfant. Les premiers 100 000 € sont exonérés. Que deviennent les 50 000 € restants) ?',
      options: ['Ils sont confisqués par l\'État', 'Ils sont taxés à un taux fixe de 30 % (PFU)', 'Ils sont soumis au "barème progressif" des droits de donation/succession, qui fonctionne par tranches (allant de 5 % à 45 % pour les enfants)', 'Le notaire les garde en garantie'],
      correct: 2, rationale: 'Comme pour l\'impôt sur le revenu, le reliquat (les 50 000 €) va franchir les petites tranches à 5%, puis 10%, puis 20% (qui est la tranche la plus vaste de 15 932 € à 552 324 €).' },
  ],
  'w13-d4': [
    { q: 'En assurance habitation ou automobile, qu\'est-ce qu\'une déclaration de sinistre ?',
      options: ['La résiliation du contrat', 'L\'acte par lequel l\'assuré informe formellement sa compagnie d\'assurance qu\'un événement dommageable (accident, vol, dégât des eaux) prévu au contrat vient de se produire', 'Le paiement de la cotisation annuelle', 'La demande de modification de l\'adresse'],
      correct: 1, rationale: 'C\'est le point de départ de tout processus d\'indemnisation. Sans déclaration officielle, l\'assureur n\'interviendra pas.' },
    { q: 'Quel est le délai légal standard (le plus courant) imposé à l\'assuré pour déclarer un sinistre classique (dégât des eaux, incendie, accident de voiture) ?',
      options: ['24 heures', '5 jours ouvrés à compter de la date où l\'assuré en a eu connaissance', '14 jours', '3 mois'],
      correct: 1, rationale: 'C\'est le délai d\'ordre public prévu par le Code des assurances. Il laisse le temps de gérer l\'urgence tout en prévenant l\'assureur assez tôt pour qu\'il puisse vérifier les faits.' },
    { q: 'Dans le cas précis d\'un VOL (cambriolage, vol de voiture), le délai de déclaration est-il le même ?',
      options: ['Oui, 5 jours', 'Non, il est beaucoup plus court : l\'assuré a seulement 2 jours ouvrés pour faire sa déclaration à l\'assureur', 'Il est de 10 jours', 'Il n\'y a pas de délai pour le vol'],
      correct: 1, rationale: 'Le vol nécessite une enquête rapide (tentative de retrouver les biens, traces d\'effraction). L\'assureur veut agir vite.' },
    { q: 'Par quel moyen pouvez-vous déclarer un sinistre à votre assureur pour être sûr que cela soit pris en compte ?',
      options: ['Uniquement par lettre recommandée avec accusé de réception', 'Par téléphone, via l\'application mobile de l\'assureur, sur l\'espace client en ligne, en agence, ou par courrier', 'Seulement par un commissaire de justice (huissier)', 'Uniquement à la police'],
      correct: 1, rationale: 'La loi n\'impose aucun formalisme lourd. Aujourd\'hui, la déclaration via application mobile (avec envoi direct des photos) est la norme.' },
    { q: 'Lors d\'un dégât des eaux, quelle est l\'obligation absolue de l\'assuré JUSTE AVANT ou PENDANT la déclaration à l\'assureur ?',
      options: ['Tout jeter à la poubelle', 'Repeindre le mur endommagé immédiatement', 'Prendre des mesures d\'urgence pour limiter l\'aggravation des dégâts (couper l\'eau) et CONSERVER toutes les pièces endommagées pour l\'expertise', 'Couper l\'électricité du quartier'],
      correct: 2, rationale: 'L\'assuré a l\'obligation de "sauvetage". S\'il regarde l\'eau couler sans rien faire, l\'assureur peut refuser d\'indemniser l\'aggravation. De plus, sans pièce endommagée à montrer, l\'expert ne rembourse rien.' },
    { q: 'Si vous déclarez un vol (cambriolage), quel document l\'assureur va-t-il obligatoirement vous réclamer en premier lieu ?',
      options: ['La facture de la porte', 'Un récépissé de dépôt de plainte délivré par la police ou la gendarmerie (le dépôt de plainte doit généralement être fait dans les 24 ou 48h)', 'Le témoignage du maire', 'Une prise de sang'],
      correct: 1, rationale: 'La plainte atteste juridiquement de l\'infraction. Sans cela, l\'assureur ne déclenchera pas la garantie Vol.' },
    { q: 'Récemment modifiée par la loi, quel est le nouveau délai pour déclarer un sinistre relevant de l\'état de "Catastrophe Naturelle" (inondation, sécheresse) ?',
      options: ['5 jours', '10 jours', '30 jours à compter de la publication de l\'arrêté interministériel au Journal Officiel', '1 an'],
      correct: 2, rationale: 'Une réforme fin 2023 a allongé ce délai (qui était auparavant de 10 jours) pour laisser plus de temps aux sinistrés souvent traumatisés et désorganisés par la catastrophe.' },
    { q: 'Que se passe-t-il juridiquement si vous déclarez un sinistre EN RETARD (hors délai) ?',
      options: ['L\'assureur annule toujours le contrat', 'Vous payez une amende à l\'État', 'L\'assureur ne peut refuser de vous indemniser (déchéance de garantie) QUE s\'il arrive à prouver que ce retard lui a causé un "préjudice" financier (ex: impossibilité d\'expertiser les dégâts effacés par le temps)', 'L\'assurance paie le double'],
      correct: 2, rationale: 'La jurisprudence protège le consommateur. Un retard d\'un jour sur un sinistre mineur n\'entraîne presque jamais l\'annulation de l\'indemnisation.' },
    { q: '(Challenge) Lors de la déclaration, pour obtenir un meilleur remboursement, l\'assuré gonfle artificiellement le prix de sa télévision détruite et falsifie une facture. Quel est le risque ?',
      options: ['L\'assureur refusera juste de payer la télé', 'La "Fausse déclaration intentionnelle" lors d\'un sinistre entraîne la déchéance TOTALE des garanties (zéro remboursement pour tout le sinistre), la résiliation du contrat, et des poursuites pénales (escroquerie)', 'L\'assureur diminue le remboursement de 10 %', 'C\'est légal, c\'est de la négociation'],
      correct: 1, rationale: 'Frauder à l\'assurance n\'est pas un jeu. Une fausse facture annule votre droit à TOUTE l\'indemnisation du sinistre en cours, même pour les biens légitimement détruits.' },
    { q: '(Challenge) Suite à votre déclaration de sinistre (un incendie), l\'expert mandaté par votre assurance vous propose 10 000 € d\'indemnisation. Vous estimez avec vos artisans qu\'il faut 20 000 €. Êtes-vous obligé d\'accepter ?',
      options: ['Oui, la parole de l\'expert d\'assurance est définitive', 'Non. Vous avez le droit de recourir à une "Contre-expertise" en mandatant votre propre "expert d\'assuré" (à vos frais ou via votre garantie honoraires d\'expert). Les deux experts devront alors s\'accorder', 'Oui, mais vous pouvez demander au maire d\'intervenir', 'Non, vous devez réparer vous-même et envoyer la facture'],
      correct: 1, rationale: 'L\'expert de l\'assurance défend (aussi) les intérêts de l\'assurance. Faire intervenir un expert indépendant rééquilibre le rapport de force en cas de litige financier lourd.' },
  ],
  'w13-d5': [
    { q: 'Dans la location immobilière, qu\'est-ce qu\'un état des lieux ?',
      options: ['Une visite de courtoisie du propriétaire', 'Un document obligatoire, rédigé conjointement par le bailleur et le locataire, qui décrit minutieusement l\'état du logement et de ses équipements à l\'entrée puis à la sortie du locataire', 'Le contrat de bail lui-même', 'L\'estimation de l\'agent immobilier pour vendre'],
      correct: 1, rationale: 'C\'est la photographie juridique du logement. La comparaison entre l\'entrée et la sortie permettra de savoir si le locataire a dégradé le bien.' },
    { q: 'La réalisation d\'un état des lieux est-elle obligatoire ?',
      options: ['Non, c\'est facultatif', 'Uniquement pour les locations meublées', 'Oui, la loi (loi Alur) rend l\'état des lieux d\'entrée et de sortie OBLIGATOIRE pour toutes les locations constituant la résidence principale du locataire (vide ou meublée)', 'Seulement si le loyer dépasse 1000 €'],
      correct: 2, rationale: 'Il doit être joint au contrat de bail. Il protège les deux parties.' },
    { q: 'Comment se répartissent les frais si l\'état des lieux d\'entrée est réalisé à l\'amiable, directement entre le propriétaire et le locataire (sans agence) ?',
      options: ['Le locataire paie 50 €', 'Il est totalement gratuit', 'Le propriétaire paie une taxe à l\'État', 'C\'est interdit, il faut un huissier'],
      correct: 1, rationale: 'S\'ils le font eux-mêmes, aucun frais ne peut être facturé. Si une agence s\'en charge, la loi plafonne la part facturable au locataire (3 € TTC / m² de surface habitable).' },
    { q: 'Que dit la loi si AUCUN état des lieux d\'entrée n\'est réalisé lors de la remise des clés ?',
      options: ['Le bail est annulé', 'Le locataire est présumé avoir reçu le logement en "bon état de réparations locatives" et devra le rendre en bon état (ce qui est très dangereux pour lui s\'il y avait déjà des trous dans les murs)', 'Le propriétaire doit rembourser la caution immédiatement', 'Le locataire ne paie pas le premier mois'],
      correct: 1, rationale: 'Sans preuve du contraire à l\'entrée, tout défaut constaté à la sortie sera imputé au locataire. L\'état des lieux d\'entrée protège donc surtout le locataire !' },
    { q: 'Le locataire vient de signer l\'état des lieux d\'entrée. Le lendemain, il s\'aperçoit que le volet roulant de la chambre est cassé (ce qui n\'a pas été noté). Que peut-il faire ?',
      options: ['Rien, c\'est trop tard, sa signature bloque tout', 'Il dispose d\'un délai légal de 10 jours à compter de la signature pour demander au propriétaire de compléter/modifier l\'état des lieux d\'entrée', 'Il doit réparer le volet à ses frais', 'Il peut annuler le contrat de bail'],
      correct: 1, rationale: 'La loi Alur donne un droit de repentir au locataire. Pour les éléments de chauffage (radiateurs), ce délai s\'étend même au premier mois de la période de chauffe.' },
    { q: 'Lors de l\'état des lieux de sortie, une distinction fondamentale doit être faite entre "Vétusté" et "Dégradation". Qui paie les travaux liés à la Vétusté (l\'usure normale du temps) ?',
      options: ['Le locataire', 'La CAF', 'Le propriétaire (bailleur)', 'L\'assurance du locataire'],
      correct: 2, rationale: 'Si la peinture a jauni après 10 ans de location, c\'est de l\'usure normale (vétusté), le propriétaire ne peut rien retenir sur la caution. S\'il y a un trou de poing dans la porte, c\'est une dégradation (faute du locataire).' },
    { q: 'À la sortie du locataire, si l\'état des lieux de sortie est STRICTEMENT IDENTIQUE à l\'état des lieux d\'entrée (aucune dégradation constatée), de quel délai dispose le propriétaire pour rendre le Dépôt de Garantie (la caution) ?',
      options: ['1 semaine', '1 mois maximum', '2 mois', '6 mois'],
      correct: 1, rationale: 'Si tout est conforme, la loi impose au bailleur de rendre l\'argent sous 1 mois. Si des dégradations justifient une retenue, le délai est porté à 2 mois.' },
    { q: 'Que se passe-t-il si, le jour de la sortie, le propriétaire et le locataire sont en conflit ouvert et refusent de signer conjointement l\'état des lieux ?',
      options: ['Le locataire garde les clés', 'Il faut faire appel à un "Commissaire de justice" (anciennement Huissier), dont les frais (réglementés) seront partagés à 50/50 entre le bailleur et le locataire', 'C\'est la police qui fait l\'état des lieux', 'Le propriétaire encaisse toute la caution par défaut'],
      correct: 1, rationale: 'L\'huissier convoque les deux parties et rédige un constat neutre et incontestable juridiquement.' },
    { q: '(Challenge) Pour éviter les conflits interminables sur le niveau d\'usure des peintures ou des moquettes, quel outil contractuel la loi Alur recommande-t-elle de joindre au bail dès la signature ?',
      options: ['Une photo du mur de la cuisine', 'Une "grille de vétusté", qui définit à l\'avance la durée de vie théorique des matériaux (ex : peinture = 7 ans) et le taux d\'abattement annuel, pour objectiver le calcul financier à la sortie', 'Un devis de Leroy Merlin', 'Le témoignage du dernier locataire'],
      correct: 1, rationale: 'Si un locataire détruit une moquette au bout de 5 ans, et que la grille fixait la vie de la moquette à 10 ans, le locataire ne paiera que 50 % du prix de remplacement (car il a détruit une moquette déjà usée à moitié).' },
    { q: '(Challenge) L\'état des lieux de sortie mentionne une porte cassée. Le propriétaire veut retenir l\'argent sur le dépôt de garantie. Quelle preuve DOIT-IL fournir au locataire pour justifier la somme retenue ?',
      options: ['Aucune, il fixe le prix arbitrairement', 'Uniquement la photo de la porte', 'Il doit fournir un justificatif financier : un Devis OU une Facture d\'un professionnel correspondant exactement aux dégradations relevées (même s\'il décide au final de faire les travaux lui-même ou de ne pas les faire)', 'Il doit obligatoirement présenter une facture acquittée (preuve que les travaux ont été faits)'],
      correct: 2, rationale: 'Le propriétaire n\'a pas le droit d\'inventer un montant ("je te retiens 200€ au hasard"). Il doit justifier la perte de valeur du bien par le devis d\'un artisan, mais la jurisprudence l\'autorise à garder la somme sans être obligé de réaliser la réparation physique. SEMAINE 14 à 26' },
  ],
};
