/* Questions de la semaine 8. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w8-d0': [
    { q: 'Quel est le principe fondamental des "intérêts composés" ?',
      options: ['Les intérêts gagnés sont réinvestis, s\'ajoutent au capital initial, et produisent à leur tour de nouveaux intérêts', 'Payer des impôts composés', 'Les intérêts sont versés et dépensés chaque mois', 'C\'est un intérêt payé à deux banques différentes'],
      correct: 0, rationale: 'Le capital grossit mécaniquement.' },
    { q: 'Comment appelle-t-on familièrement ce mécanisme dans l\'investissement ?',
      options: ['L\'effet papillon', 'L\'effet de levier', 'L\'effet de serre', 'L\'effet "boule de neige"'],
      correct: 3, rationale: 'Plus la boule roule longtemps, plus elle s\'élargit vite.' },
    { q: 'Albert Einstein aurait décrit les intérêts composés par cette citation :',
      options: ['"C\'est l\'invention du diable"', '"La théorie de la relativité s\'y applique"', '"C\'est la huitième merveille du monde. Celui qui les comprend s\'enrichit..."', '"L\'argent n\'a pas d\'odeur"'],
      correct: 2, rationale: 'Cela illustre la puissance exponentielle de ce concept.' },
    { q: 'Quelle est la variable LA PLUS IMPORTANTE dans la formule mathématique pour obtenir un résultat final explosif ?',
      options: ['Le taux d\'imposition', 'Le temps (la durée de l\'investissement, exprimée en puissance)', 'Le montant du versement initial uniquement', 'La banque choisie'],
      correct: 1, rationale: 'Dans les dernières décennies, la courbe devient exponentielle.' },
    { q: 'Pour bénéficier des intérêts composés en bourse, que devez-vous faire des "dividendes" ?',
      options: ['Les virer sur votre compte courant', 'Les donner aux impôts', 'Les bloquer sur un Livret A', 'Les réinvestir immédiatement pour racheter de nouvelles actions'],
      correct: 3, rationale: 'Sans réinvestissement, c\'est de l\'intérêt simple.' },
    { q: 'Sur une assurance-vie "Fonds euros", profitez-vous des intérêts composés ?',
      options: ['Oui, car l\'assureur intègre chaque année les intérêts au capital garanti (effet cliquet)', 'Non, jamais', 'Oui, mais seulement si on verse 1000 €/mois', 'Seulement si on a des Unités de Compte'],
      correct: 0, rationale: 'Les intérêts de l\'année N sont acquis et rapportent en N+1.' },
    { q: 'Quel est l\'ennemi numéro un de l\'investisseur face aux intérêts composés ?',
      options: ['Les jours fériés', 'Le plafond du Livret A', 'L\'attentisme (commencer à investir trop tard dans sa vie)', 'Les taux fixes'],
      correct: 2, rationale: 'Commencer à 25 ans génère beaucoup plus de capital final qu\'à 45 ans.' },
    { q: 'En finance, que permet de calculer "la règle des 72" ?',
      options: ['L\'espérance de vie', 'Une astuce pour estimer en combien d\'années un capital va DOUBLER grâce aux intérêts composés', 'Le nombre de jours pour ouvrir un PEA', 'Le montant de l\'usure'],
      correct: 1, rationale: '72 / 6% = 12 ans pour doubler.' },
    { q: '(Challenge) Investir 10 000 € à 7 % par an sans y toucher pendant 40 ans donnera environ :',
      options: ['12 800 €', '38 000 €', '1 million d\'euros', 'Près de 150 000 €'],
      correct: 3, rationale: 'La majorité du capital final est constituée des intérêts générés par les intérêts passés.' },
    { q: '(Challenge) Pourquoi les frais d\'un contrat (ex: 2%) sont-ils destructeurs avec les intérêts composés ?',
      options: ['Car ils annulent le contrat', 'Car l\'assureur double les impôts', 'Car les frais se capitalisent à la baisse, amputant la base et détruisant les futurs intérêts composés sur 20 ans', 'Ils ne sont pas destructeurs'],
      correct: 2, rationale: 'L\'intérêt composé démultiplie aussi le manque à gagner.' },
  ],
  'w8-d1': [
    { q: 'Qu\'est-ce que le "quotient conjugal" en fiscalité française ?',
      options: ['Une taxe sur les célibataires', 'Le système d\'imposition commune appliqué aux couples mariés ou pacsés, qui permet d\'atténuer la progressivité de l\'impôt en divisant les revenus par 2 parts', 'La pension alimentaire versée après un divorce', 'L\'obligation d\'avoir des comptes bancaires séparés'],
      correct: 1, rationale: 'À l\'instar du quotient familial pour les enfants, le quotient conjugal protège le couple en additionnant leurs revenus puis en les divisant par le nombre de parts du couple (2 parts).' },
    { q: 'Deux personnes vivent en union libre (concubinage) depuis 10 ans et ont un compte joint. Bénéficient-elles du quotient conjugal ?',
      options: ['Oui, le concubinage de longue durée équivaut au mariage', 'Non, la fiscalité française considère les concubins comme deux étrangers (chacun remplit sa propre déclaration avec 1 seule part)', 'Oui, si elles déclarent l\'union à la mairie', 'Uniquement si elles ont un enfant'],
      correct: 1, rationale: 'Le quotient conjugal est un avantage strictement réservé par la loi aux couples unis par le mariage ou le PACS.' },
    { q: 'Dans quelle situation mathématique le mariage/PACS (quotient conjugal) offre-t-il le PLUS GRAND gain fiscal (baisse de l\'impôt) par rapport à deux célibataires ?',
      options: ['Quand les deux partenaires gagnent exactement le même salaire', 'Quand les deux gagnent le SMIC', 'Lorsqu\'il y a une très forte disparité (un gros écart) de revenus entre les deux membres du couple', 'Quand ils sont tous les deux chômeurs'],
      correct: 2, rationale: 'Si l\'un gagne 80 000€ (tranche à 41%) et l\'autre 0€, la division par 2 (moyenne à 40 000€) va faire redescendre le plus riche dans une tranche d\'imposition beaucoup plus basse (30%). L\'économie est massive.' },
    { q: 'Si les deux conjoints gagnent EXACTEMENT le même salaire (ex: 30 000 € chacun), quel est l\'impact de l\'imposition commune sur leur impôt global ?',
      options: ['L\'impôt est divisé par deux', 'L\'impôt global sera exactement le même que s\'ils étaient restés célibataires (zéro gain fiscal lié au mariage)', 'Ils paieront 10% d\'impôts en plus', 'Leurs impôts sont annulés'],
      correct: 1, rationale: '30k imposé sur 1 part + 30k imposé sur 1 part = exactement le même calcul que 60k imposés sur 2 parts. Le mariage n\'enrichit (fiscalement) que les couples aux revenus inégaux.' },
    { q: 'Contrairement au "quotient familial" (les demi-parts liées aux enfants) qui est plafonné pour les riches, le "quotient conjugal" (la 2ème part du conjoint) est-il plafonné ?',
      options: ['Oui, au-delà de 50 000 € d\'économie, c\'est plafonné', 'Non, l\'avantage fiscal lié au partage des revenus entre époux n\'est soumis à AUCUN plafonnement, quelle que soit la fortune du couple', 'Oui, il est plafonné à 1 759 € comme pour un enfant', 'Il est plafonné à 0 si le couple n\'a pas d\'enfant'],
      correct: 1, rationale: 'Un grand patron gagnant des millions peut faire d\'immenses économies d\'impôts en épousant quelqu\'un sans revenus, sans aucune limite légale.' },
    { q: 'L\'année où un couple se marie ou se pacse, quelle souplesse l\'administration fiscale leur accorde-t-elle ?',
      options: ['Ils sont exonérés d\'impôts pour l\'année', 'Ils ont l\'obligation stricte de faire une déclaration commune', 'Ils peuvent choisir (option irrévocable) entre faire une déclaration commune OU conserver deux déclarations séparées pour l\'année entière, selon ce qui est le plus avantageux pour eux', 'Ils doivent payer l\'impôt en double'],
      correct: 2, rationale: 'Parfois, à cause du jeu de certaines réductions d\'impôts plafonnées, il est plus avantageux de rester séparés l\'année du mariage. L\'État laisse le choix.' },
    { q: 'En matière de recouvrement de l\'impôt, quelle lourde contrepartie pèse sur le couple soumis au quotient conjugal ?',
      options: ['L\'obligation de payer en espèces', 'La "solidarité fiscale" : les deux conjoints sont co-responsables de l\'intégralité de la dette fiscale du foyer. Si l\'un ne paie pas, le fisc peut saisir le salaire de l\'autre', 'L\'annulation de la carte vitale en cas de retard', 'Il n\'y a aucune solidarité'],
      correct: 1, rationale: 'En signant une déclaration commune, vous devenez responsable des impôts de votre conjoint. Même après un divorce, le fisc peut vous réclamer un redressement lié aux années communes.' },
    { q: 'Que se passe-t-il fiscalement pour le quotient conjugal l\'année d\'un divorce ou d\'une rupture de PACS ?',
      options: ['Le couple fait une dernière déclaration commune jusqu\'au 31 décembre', 'Dès l\'année de la séparation, le couple doit remplir deux déclarations séparées couvrant chacune l\'année entière (du 1er janvier au 31 décembre)', 'Le fisc demande le remboursement des économies passées', 'Ils restent solidaires pendant 10 ans'],
      correct: 1, rationale: 'Peu importe que le divorce soit prononcé en février ou en novembre, l\'année civile est traitée comme si le couple était séparé depuis le 1er janvier.' },
    { q: '(Challenge) Un couple très inégal (Monsieur gagne 80k, Madame gagne 20k) opte pour le "Taux de prélèvement à la source individualisé". Vont-ils perdre l\'avantage du quotient conjugal ?',
      options: ['Oui, c\'est le principe de l\'individualisation', 'Non, l\'impôt global ANNUEL calculé par le fisc restera exactement le même (avec l\'avantage du quotient conjugal). L\'individualisation ne sert qu\'à répartir la charge mensuelle pour que le plus pauvre ne soit pas lourdement prélevé sur son petit salaire', 'Ils paieront 10% de plus pour ce service', 'C\'est interdit en France'],
      correct: 1, rationale: 'Le taux individualisé permet une équité au sein du couple chaque mois, sans casser le gain fiscal de la déclaration commune annuelle.' },
    { q: '(Challenge) Un couple marié vit sous la séparation de biens et n\'habite plus sous le même toit depuis 2 ans, mais sans avoir entamé de procédure de divorce. Doivent-ils déclarer ensemble ?',
      options: ['Oui, le mariage oblige toujours à déclarer ensemble', 'Non, l\'imposition séparée est OBLIGATOIRE si les époux sont séparés de biens ET ne vivent pas sous le même toit', 'Ils peuvent choisir', 'Le plus riche déclare pour les deux'],
      correct: 1, rationale: 'C\'est une des rares exceptions au principe d\'imposition commune du mariage. La séparation matérielle et patrimoniale (séparation de biens + résidences séparées) casse le foyer fiscal.' },
  ],
  'w8-d2': [
    { q: 'Dans le jargon des retraites (CNAV/Régime de base), qu\'est-ce que la "décote" ?',
      options: ['Une taxe supplémentaire pour les hauts revenus', 'Une minoration définitive (une baisse) du taux de calcul de la pension, appliquée si l\'assuré part à la retraite avant d\'avoir validé le nombre de trimestres requis', 'L\'interdiction de travailler à la retraite', 'La baisse automatique des retraites liée à l\'inflation'],
      correct: 1, rationale: 'Si vous partez à l\'âge légal sans avoir réuni tous vos trimestres, votre retraite sera lourdement pénalisée (à vie).' },
    { q: 'La décote réduit le taux de calcul. Quel est le taux "plein" (maximum) auquel s\'applique cette réduction dans le régime de base ?',
      options: ['100 % du salaire', '75 % du salaire', '50 % du salaire annuel moyen', '10 % du salaire'],
      correct: 2, rationale: 'Sans décote, on multiplie votre salaire moyen par 50%. Avec décote, ce pourcentage baisse (ex: 45%, 40%...), ce qui réduit mécaniquement la pension.' },
    { q: 'Comment l\'administration calcule-t-elle le nombre de trimestres manquants qui serviront à appliquer la décote ?',
      options: ['Elle retient le nombre d\'années depuis le dernier emploi', 'Elle compte les trimestres manquants pour atteindre la durée requise, OU les trimestres manquants pour atteindre l\'âge du taux plein automatique (67 ans), et retient le chiffre le PLUS FAVORABLE à l\'assuré (le plus petit)', 'Elle divise l\'âge par 4', 'Elle donne une décote forfaitaire de 10 trimestres à tout le monde'],
      correct: 1, rationale: 'Ce double calcul permet de protéger les assurés qui ont commencé à travailler très tard. Le malus est limité.' },
    { q: 'Existe-t-il une limite (un plafond) au nombre de trimestres manquants retenus pour calculer la décote maximale ?',
      options: ['Non, aucune limite', 'Oui, la décote est plafonnée à 20 trimestres manquants maximum', 'Oui, 4 trimestres maximum', 'Oui, 50 trimestres'],
      correct: 1, rationale: 'Même s\'il vous manque 30 trimestres, l\'ordinateur ne retiendra que 20 trimestres manquants (soit 5 ans) pour ne pas réduire la pension à néant.' },
    { q: 'Qu\'est-ce que "l\'âge d\'annulation de la décote" (ou taux plein automatique) ?',
      options: ['62 ans', '64 ans', '67 ans (pour toutes les générations nées depuis 1955) : à cet âge, la décote est interdite, même s\'il manque beaucoup de trimestres', '70 ans'],
      correct: 2, rationale: 'À 67 ans, vous obtenez le taux de 50%. Mais attention, la pension sera quand même proratisée (réduite) en fonction du nombre de trimestres réellement effectués par rapport à ceux requis.' },
    { q: 'Qu\'est-ce que la "surcote" ?',
      options: ['L\'obligation de cotiser plus cher', 'Une majoration définitive du montant de la pension pour les assurés qui continuent à travailler ALORS QU\'ils ont déjà l\'âge légal ET le nombre de trimestres requis', 'Une prime de départ payée par l\'employeur', 'Le nom donné à la retraite complémentaire'],
      correct: 1, rationale: 'C\'est la récompense (le bonus) pour allonger sa carrière alors qu\'on aurait pu partir sans malus.' },
    { q: 'Quel est le taux actuel de la surcote dans le régime général (pour chaque trimestre civil supplémentaire travaillé) ?',
      options: ['+ 0,5 % par trimestre', '+ 1,25 % par trimestre (soit + 5 % pour une année entière de travail supplémentaire)', '+ 10 % par trimestre', '+ 50 € par trimestre'],
      correct: 1, rationale: 'Si vous travaillez deux ans de plus (8 trimestres) alors que vous aviez déjà le taux plein, votre retraite de base sera augmentée de 10 % à vie.' },
    { q: 'Pour commencer à générer de la surcote, est-il suffisant d\'avoir validé tous ses trimestres avant l\'âge légal (ex: à 60 ans) ?',
      options: ['Oui, le travail supplémentaire compte immédiatement', 'Non, la surcote ne se déclenche que pour les trimestres travaillés APRÈS avoir atteint l\'âge légal (64 ans) ET la durée d\'assurance requise. Les deux conditions doivent être réunies simultanément', 'Oui, la surcote commence à 55 ans', 'Seulement si on demande l\'autorisation'],
      correct: 1, rationale: 'Si vous avez tous vos trimestres à 62 ans mais que l\'âge légal est à 64 ans, travailler entre 62 et 64 ans ne vous donne aucune surcote. C\'est du travail normal pour atteindre l\'âge d\'ouverture des droits.' },
    { q: '(Challenge) La décote appliquée au régime de base (Sécurité sociale) a-t-elle un impact sur la retraite complémentaire Agirc-Arrco ?',
      options: ['Aucun impact', 'Oui, les deux régimes sont solidaires. Si l\'assuré part avec une décote au régime de base, l\'Agirc-Arrco appliquera également un "coefficient d\'anticipation" (une décote) sur la pension complémentaire', 'La décote augmente l\'Agirc-Arrco pour compenser', 'L\'Agirc-Arrco est supprimée'],
      correct: 1, rationale: 'C\'est la double peine. Partir trop tôt ou sans les trimestres ampute le socle de base ET la complémentaire.' },
    { q: '(Challenge) Un assuré a 67 ans. Il lui fallait 170 trimestres. Il n\'en a validé que 100 dans sa vie. L\'ordinateur affiche : "Taux = 50% (Taux plein)". Pourquoi n\'a-t-il pas de décote alors qu\'il lui manque 70 trimestres ?',
      options: ['C\'est une erreur informatique', 'Car à 67 ans, la décote sur le TAUX (50%) est annulée par la loi. Cependant, sa pension sera très faible car le montant sera "proratisé" (multiplié par 100/170)', 'Parce qu\'il a été au chômage', 'Parce qu\'il a acheté ses trimestres sans le savoir'],
      correct: 1, rationale: 'C\'est une nuance vitale. Il garde le meilleur taux (50%), mais on ne lui paie que la proportion de sa carrière (100 trimestres sur 170). Taux plein ne veut pas dire pension complète !' },
  ],
  'w8-d3': [
    { q: 'Quel est le rôle principal d\'un testament ?',
      options: ['Nommer un tuteur pour les adultes', 'Exprimer ses dernières volontés et organiser la transmission de ses biens, afin de déroger (dans les limites de la loi) à l\'ordre des héritiers prévu par défaut par le Code Civil', 'Annuler ses dettes auprès de la banque', 'Rédiger une biographie pour ses enfants'],
      correct: 1, rationale: 'Sans testament, c\'est la loi qui décide qui hérite. Le testament permet d\'avantager un conjoint, un ami, ou une association.' },
    { q: 'Quelle est la définition d\'un testament "olographe" ?',
      options: ['Un testament enregistré sur une clé USB', 'Un testament obligatoirement écrit en entier de la main du testateur (manuscrit), daté et signé par lui', 'Un testament tapé à l\'ordinateur et imprimé', 'Un testament rédigé par un médecin'],
      correct: 1, rationale: 'L\'article 970 du Code civil est très strict. L\'écriture manuscrite est la preuve irréfutable de l\'identité et du consentement du testateur.' },
    { q: 'Vous rédigez votre testament à l\'ordinateur car vous écrivez mal, vous l\'imprimez, vous mettez la date au stylo et vous signez. Quelle est sa valeur juridique ?',
      options: ['Il est parfaitement valable', 'Il est nul et sans aucune valeur juridique (le juge l\'annulera car il n\'est pas manuscrit)', 'Il n\'est valable que s\'il est validé par la mairie', 'Il ne s\'applique qu\'au mobilier'],
      correct: 1, rationale: 'La nullité pour un testament tapé à la machine ou à l\'ordinateur est absolue. Seul l\'acte authentique chez le notaire peut être dactylographié.' },
    { q: 'Qu\'est-ce qu\'un testament "authentique" ?',
      options: ['Le vrai testament d\'origine, par opposition aux copies', 'Un testament dicté par le testateur à un notaire, en présence de deux témoins (ou d\'un second notaire), qui le rédige et le fait signer', 'Un testament certifié conforme à la mairie', 'Un testament écrit avec du sang'],
      correct: 1, rationale: 'C\'est la forme la plus sûre (impossible à falsifier, difficile à contester sur la santé mentale), indispensable pour certains actes comme priver son conjoint de son droit viager au logement.' },
    { q: 'Comment un notaire ou des héritiers peuvent-ils savoir, le jour du décès, que le défunt avait rédigé un testament des années auparavant ?',
      options: ['En fouillant systématiquement toute la maison', 'En consultant le FCDDV (Fichier Central des Dispositions de Dernières Volontés), un registre national où les notaires inscrivent l\'existence et le lieu de conservation des testaments', 'En passant une annonce dans le journal', 'En demandant à la banque'],
      correct: 1, rationale: 'Si vous faites un testament olographe chez vous, il est vivement conseillé de payer quelques dizaines d\'euros à un notaire pour qu\'il le garde au coffre et l\'inscrive au FCDDV (Fichier des Testaments).' },
    { q: 'Un testament est-il révocable (modifiable ou annulable) ?',
      options: ['Non, un testament signé est définitif à vie', 'Uniquement si le juge l\'autorise', 'Oui, le testateur peut le révoquer ou le modifier librement, seul et à tout moment jusqu\'à son décès, le dernier testament en date annulant les précédents s\'ils sont contradictoires', 'Seulement tous les 10 ans'],
      correct: 2, rationale: 'Le testament n\'est qu\'une "promesse" post-mortem. Tant que la personne est vivante et saine d\'esprit, elle peut déchirer son testament ou en refaire un autre.' },
    { q: 'En droit français, a-t-on la liberté totale de donner tout son patrimoine à un ami ou à une association via son testament ?',
      options: ['Oui, la liberté testamentaire est absolue', 'Non, si l\'on a des enfants, le testament ne peut porter QUE sur la "quotité disponible". Il est interdit de priver ses enfants de leur "réserve héréditaire"', 'Seulement si on paie une taxe spéciale', 'Oui, si l\'ami est dans le besoin'],
      correct: 1, rationale: 'Contrairement aux États-Unis, le droit français protège les enfants (et le conjoint s\'il n\'y a pas d\'enfant). Le testament ne permet de jouer qu\'avec la part libre (la quotité disponible).' },
    { q: 'Un couple très uni veut faire un testament unique : "Nous, M. et Mme Dupont, léguons tous nos biens à notre neveu". Est-ce légal ?',
      options: ['Oui, c\'est un testament solidaire', 'Non, le "testament conjonctif" (fait par deux personnes sur un même document) est formellement interdit en France. Chacun doit rédiger son propre testament séparé', 'Oui, mais seulement s\'ils sont mariés sous la communauté universelle', 'Oui, c\'est même obligatoire'],
      correct: 1, rationale: 'L\'article 968 du Code civil l\'interdit pour protéger la liberté individuelle (l\'un pourrait se sentir forcé par l\'autre). Ce document commun serait frappé de nullité absolue.' },
    { q: '(Challenge) En vocabulaire testamentaire, qu\'est-ce qu\'un "Légataire universel" ?',
      options: ['Une association caritative mondiale', 'La personne désignée par le testament pour recevoir l\'intégralité du patrimoine disponible du défunt', 'Quelqu\'un qui hérite uniquement des meubles', 'L\'héritier qui paie toutes les dettes'],
      correct: 1, rationale: 'On distingue le légataire universel (qui a vocation à tout recevoir), le légataire à titre universel (qui reçoit une fraction, ex: "la moitié de mes biens"), et le légataire particulier (qui reçoit un bien précis, ex: "ma montre en or").' },
    { q: '(Challenge) Outre les testaments olographe et authentique, il existe une 3ème forme, très rare, combinant le secret et l\'intervention du notaire. Comment s\'appelle-t-elle ?',
      options: ['Le testament numérique', 'Le testament secret défense', 'Le testament mystique', 'Le testament clérical'],
      correct: 2, rationale: 'Le testateur remet un document clos, cacheté et scellé à un notaire en présence de deux témoins, en déclarant que le contenu est son testament. Personne (pas même le notaire) ne connaît son contenu avant le décès.' },
  ],
  'w8-d4': [
    { q: 'À quoi sert principalement une "mutuelle" ou complémentaire santé ?',
      options: ['À remplacer totalement la Sécurité Sociale', 'À rembourser le "ticket modérateur" et les dépassements d\'honoraires (c\'est-à-dire la part des frais médicaux qui n\'est pas prise en charge par le régime obligatoire de la Sécurité Sociale)', 'À payer l\'assurance automobile en cas d\'accident', 'À verser un salaire en cas d\'arrêt maladie'],
      correct: 1, rationale: 'La Sécu ne rembourse presque jamais 100% de la facture du médecin ou de l\'hôpital. La mutuelle vient "compléter" ce remboursement pour limiter le reste à charge du patient.' },
    { q: 'Depuis la loi ANI de 2016, quelle obligation pèse sur tous les employeurs du secteur privé concernant la mutuelle de leurs salariés ?',
      options: ['Aucune, c\'est facultatif', 'Ils ont l\'obligation de proposer une complémentaire santé collective à tous leurs salariés et de financer au minimum 50 % de la cotisation', 'Ils doivent payer 100 % de la mutuelle', 'Ils doivent rembourser les médicaments de l\'infirmerie'],
      correct: 1, rationale: 'C\'est une grande avancée sociale. Avant, beaucoup de salariés n\'avaient pas les moyens de se payer une mutuelle. Désormais, l\'employeur en paie la moitié (voire plus selon la convention collective).' },
    { q: 'Dans les tableaux de garanties d\'une mutuelle, que signifie l\'abréviation "BRSS" (ou "BR") ?',
      options: ['Bilan de Réduction de la Sécurité Sociale', 'Base de Remboursement de la Sécurité Sociale (le tarif de référence sur lequel se basent la Sécu et la mutuelle pour calculer leurs remboursements)', 'Bureau de Recouvrement Santé et Soins', 'Bonification pour Réduction des Soins Spécialisés'],
      correct: 1, rationale: 'Si la consultation est à 25€ (BRSS), la Sécu rembourse 70% de ces 25€. Si vous allez voir un médecin qui facture 50€, le calcul des remboursements se fera toujours sur la base de ces 25€, jamais sur les 50€.' },
    { q: 'Si votre mutuelle indique un remboursement à "100 % de la BRSS" pour les consultations. Qu\'est-ce que cela signifie concrètement ?',
      options: ['Elle rembourse absolument tout, quel que soit le prix du médecin', 'Le remboursement cumulé (Sécu + Mutuelle) atteindra exactement le tarif de référence de la Sécu (ex: 25€). Si le médecin pratique des dépassements d\'honoraires, la différence sera de votre poche', 'La mutuelle vous rembourse 100 € par visite', 'Elle double le remboursement de la Sécu'],
      correct: 1, rationale: '"100% BRSS" est le niveau de base. Il rembourse le ticket modérateur, mais ne couvre aucun dépassement.' },
    { q: 'Qu\'est-ce que la réforme "100 % Santé" (ou reste à charge zéro) mise en place par le gouvernement ?',
      options: ['L\'hôpital gratuit pour tous', 'L\'obligation pour les mutuelles de rembourser intégralement (0€ de votre poche) une sélection de lunettes, de prothèses dentaires et d\'aides auditives, si vous choisissez des équipements dans le "panier" 100% Santé', 'La suppression des franchises sur les boîtes de médicaments', 'Le remboursement du dentifrice'],
      correct: 1, rationale: 'Cela permet aux personnes modestes d\'avoir accès à des équipements essentiels de qualité, sans avoir à débourser des milliers d\'euros.' },
    { q: 'Qu\'appelle-t-on le "Tiers payant" ?',
      options: ['Le fait de faire payer son voisin', 'Un mécanisme qui permet au patient de ne pas avancer les frais médicaux (à la pharmacie, au labo) : la Sécu et la mutuelle paient directement le professionnel de santé', 'Une taxe prélevée par les pharmacies', 'L\'obligation de payer en trois fois'],
      correct: 1, rationale: 'C\'est la fameuse présentation de la "Carte Vitale" et de la "Carte Mutuelle" au comptoir, qui vous évite de débourser 100€ de médicaments et d\'attendre le remboursement.' },
    { q: 'Dans un contrat de mutuelle (souvent individuel), qu\'est-ce qu\'un "délai de carence" (ou délai de stage) ?',
      options: ['La période pendant laquelle la mutuelle rembourse le double', 'Une période de plusieurs mois (souvent 3 à 6 mois) suivant la signature du contrat, pendant laquelle certaines garanties coûteuses (ex: couronnes dentaires, maternité) ne sont pas encore actives', 'L\'obligation d\'avoir une carence en vitamines pour être remboursé', 'Le délai pour changer d\'avis et annuler le contrat'],
      correct: 1, rationale: 'Les mutuelles mettent cela en place pour éviter les "effets d\'aubaine" (un client s\'abonne un lundi, se fait poser des implants à 3000€ le mardi, et résilie le mercredi).' },
    { q: 'À quoi sert le dispositif "Portabilité" pour la mutuelle d\'entreprise ?',
      options: ['À l\'utiliser sur son smartphone', 'À permettre à un salarié dont le contrat s\'arrête (licenciement, fin de CDD) et qui a droit au chômage, de conserver les garanties de la mutuelle de l\'entreprise gratuitement pendant une durée maximale de 12 mois', 'À transférer la mutuelle à son chien', 'À utiliser sa mutuelle à l\'étranger'],
      correct: 1, rationale: 'C\'est un filet de sécurité énorme pour éviter qu\'une personne au chômage ne se retrouve sans couverture santé.' },
    { q: '(Challenge) Un médecin spécialiste de "Secteur 2" (honoraires libres) facture sa consultation 60 €. La BRSS (tarif de base) est de 23 €. Pour être remboursé quasi-intégralement (hors participation forfaitaire d\'1€), que doit indiquer votre contrat de mutuelle ?',
      options: ['Remboursement à 100% BRSS', 'Remboursement à 200% BRSS ou 300% BRSS', 'L\'option "Tiers payant"', 'L\'option "Chambre particulière"'],
      correct: 1, rationale: 'Si la mutuelle rembourse "200% de la base", cela fait 200% de 23€ = un plafond de remboursement (Sécu incluse) de 46€. Avec "300%", le plafond monte à 69€, ce qui couvre les 60€ facturés par le médecin.' },
    { q: '(Challenge) Depuis la loi de 2020 (Loi RIA), quelle est la règle concernant la résiliation d\'un contrat de complémentaire santé individuel ?',
      options: ['On est engagé à vie', 'Il faut attendre l\'échéance annuelle (date d\'anniversaire) avec un préavis de 2 mois', 'On peut résilier son contrat à tout moment et sans frais (résiliation infra-annuelle), dès lors que le contrat a plus d\'un an d\'ancienneté', 'Il faut payer une pénalité de 6 mois de cotisations'],
      correct: 2, rationale: 'Comme pour l\'assurance auto (loi Hamon), cette mesure facilite la concurrence. Si votre mutuelle devient trop chère, vous pouvez en changer quand vous voulez après la première année.' },
  ],
  'w8-d5': [
    { q: 'Dans le processus d\'achat immobilier, quelle est la définition exacte d\'une "offre d\'achat" ?',
      options: ['La publicité passée par l\'agence immobilière', 'Un acte juridique par lequel un candidat acquéreur propose d\'acheter un bien à un prix fixé et sous certaines conditions, constituant le premier véritable engagement de sa part', 'Le contrat final signé chez le notaire', 'L\'estimation de la maison par la banque'],
      correct: 1, rationale: 'C\'est le point de départ de la négociation. Tant qu\'il n\'y a pas d\'écrit, les discussions orales n\'ont aucune valeur juridique.' },
    { q: 'Une offre d\'achat verbale (faite à l\'oral pendant la visite) a-t-elle une valeur légale contraignante ?',
      options: ['Oui, la parole suffit en droit civil', 'Non, pour être valable et engager les parties, l\'offre d\'achat doit obligatoirement être rédigée par écrit (papier ou email formel)', 'Oui, s\'il y a des témoins', 'Seulement si on donne de l\'argent de la main à la main'],
      correct: 1, rationale: 'Les paroles s\'envolent, les écrits restent. Un vendeur ne peut pas s\'engager sur un "je vous la prends" lancé dans le salon.' },
    { q: 'Dans une vente directe (de particulier à particulier), vous visitez un bien affiché à 200 000 €. Vous rédigez sur place une offre d\'achat écrite exactement "au prix" (200 000 €). Le vendeur peut-il refuser ?',
      options: ['Oui, il fait ce qu\'il veut jusqu\'au notaire', 'Non, en théorie juridique, une offre faite exactement au prix demandé (sans négociation) forme la vente. Le vendeur est tenu de l\'accepter', 'Oui, s\'il trouve un autre acheteur plus sympathique', 'Il peut demander 210 000 €'],
      correct: 1, rationale: 'En affichant son bien à 200 000 €, le vendeur a exprimé publiquement son intention de vendre à ce prix. Si un acheteur accepte ces exactes conditions, l\'accord est juridiquement trouvé (attention, c\'est plus nuancé si le bien est en agence avec un mandat simple).' },
    { q: 'Que se passe-t-il si vous rédigez une offre d\'achat "inférieure au prix" (une négociation à la baisse) ?',
      options: ['Le vendeur doit porter plainte', 'L\'offre annule la vente', 'L\'offre initiale du vendeur tombe. Il a alors le choix : accepter, refuser, ou formuler une "contre-proposition" (contre-offre)', 'L\'acheteur est condamné à payer le prix fort'],
      correct: 2, rationale: 'Dès que vous proposez un prix inférieur, le vendeur n\'a plus aucune obligation envers vous. Les compteurs de la négociation sont lancés.' },
    { q: 'Qu\'est-ce qu\'une "contre-proposition" ou "contre-offre" de la part du vendeur ?',
      options: ['Un refus poli', 'Une proposition du vendeur avec un nouveau prix (intermédiaire). Cela annule juridiquement l\'offre de l\'acheteur. C\'est désormais à l\'acheteur de l\'accepter ou de la refuser', 'Un papier de la mairie', 'L\'obligation de payer les frais de notaire'],
      correct: 1, rationale: 'Si vous proposez 180k (pour 200k), et qu\'il répond "D\'accord pour 190k", votre offre à 180k est morte. Vous êtes libre de refuser ses 190k et de partir.' },
    { q: 'Un agent immobilier ou un vendeur vous demande un chèque "d\'acompte" ou de "réservation" (ex: 1 000 €) pour bloquer le bien au moment où vous rédigez votre offre d\'achat. Est-ce normal ?',
      options: ['Oui, c\'est la règle pour montrer son sérieux', 'Non, c\'est totalement et strictement illégal en France. Aucun paiement ne peut être exigé à l\'étape de l\'offre d\'achat', 'Uniquement pour les maisons neuves', 'Oui, si le chèque n\'est pas encaissé'],
      correct: 1, rationale: 'L\'article L.271-2 du Code de la construction est formel. Les fonds (le dépôt de garantie) ne seront versés QU\'AU MOMENT du compromis de vente chez le notaire ou en agence.' },
    { q: 'Une offre d\'achat bien rédigée doit obligatoirement comporter un "délai de validité" (souvent de 1 à 2 semaines). Pourquoi ?',
      options: ['Pour accélérer le travail de la banque', 'Parce que sans ce délai d\'expiration, l\'acheteur resterait engagé indéfiniment. Passé ce délai, si le vendeur n\'a pas répondu, l\'offre devient nulle et l\'acheteur est libéré', 'Pour payer moins d\'impôts', 'C\'est une obligation du cadastre'],
      correct: 1, rationale: 'Si vous laissez une offre sans date limite, le vendeur pourrait revenir vous voir 6 mois plus tard pour l\'accepter, alors que vous avez peut-être acheté autre chose entre temps.' },
    { q: 'L\'acheteur a-t-il le droit de se rétracter (d\'annuler) son offre d\'achat AVANT que le vendeur ne l\'ait acceptée ?',
      options: ['Non, une offre envoyée est définitive', 'Oui, la jurisprudence autorise l\'acheteur à retirer son offre tant que celle-ci n\'a pas été réceptionnée et acceptée formellement par le vendeur', 'Uniquement en payant 10% du prix', 'Seulement si l\'offre était verbale'],
      correct: 1, rationale: 'Tant qu\'il n\'y a pas eu "rencontre des volontés" (l\'acceptation du vendeur), l\'acheteur peut faire marche arrière.' },
    { q: '(Challenge) Le vendeur a signé et accepté votre offre par écrit. Finalement, vous paniquez et vous voulez annuler. Êtes-vous coincé ?',
      options: ['Oui, l\'acceptation force la vente immédiatement', 'Non, car la loi accorde à tout acheteur non professionnel un délai de rétractation légal et incompressible de 10 jours qui démarrera UNIQUEMENT le lendemain de la signature du futur compromis de vente', 'Vous devez payer le notaire pour annuler', 'Vous êtes forcé d\'acheter mais avec 50% de remise'],
      correct: 1, rationale: 'Même si l\'offre vous engage théoriquement, le droit de l\'immobilier français est ultra-protecteur pour l\'acquéreur. Vous pourrez vous retirer sans frais lors de l\'étape du compromis.' },
    { q: '(Challenge) Lors de la rédaction de l\'offre d\'achat, pourquoi est-il stratégique et conseillé d\'y inscrire d\'ores et déjà votre "plan de financement" (le montant de votre apport et du prêt demandé) ?',
      options: ['Parce que c\'est imposé par la police', 'Pour rassurer le vendeur sur votre solvabilité et pour préparer l\'intégration des "conditions suspensives d\'obtention de prêt" qui figureront dans le compromis', 'Pour obtenir une réduction des impôts locaux', 'Pour que l\'agent immobilier prenne moins de commission'],
      correct: 1, rationale: 'Un vendeur préfèrera souvent une offre à 190 000€ d\'un acheteur qui a un gros apport et un dossier solide, plutôt qu\'une offre à 200 000€ d\'un acheteur qui doit financer à 110% et risque de se voir refuser son prêt.' },
  ],
};
