/* Questions de la semaine 24. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w24-d0': [
    { q: 'En finance, quelle est la définition stricte d\'un "dividende" ?',
      options: ['Un emprunt réalisé par l\'entreprise', 'La fraction des bénéfices nets de l\'entreprise qui est distribuée aux actionnaires en rémunération de leur investissement', 'La hausse du prix de l\'action en bourse', 'Les frais payés au courtier'],
      correct: 1, rationale: 'Quand une entreprise fait des profits, elle peut soit les réinvestir pour se développer, soit en reverser une partie à ses copropriétaires (les actionnaires).' },
    { q: 'Qui prend la décision officielle de verser (ou de ne pas verser) un dividende, et d\'en fixer le montant ?',
      options: ['L\'État français', 'Le directeur général seul', 'L\'Assemblée Générale des actionnaires, sur proposition du Conseil d\'administration', 'L\'Autorité des Marchés Financiers'],
      correct: 2, rationale: 'Ce sont les propriétaires de l\'entreprise (qui votent lors de l\'AG) qui valident le détachement de la richesse de l\'entreprise vers leurs poches.' },
    { q: 'Comment calcule-t-on le "Taux de rendement" (ou Rendement du dividende) d\'une action à un instant T ?',
      options: ['(Montant du dividende versé / Cours actuel de l\'action) x 100', 'Dividende multiplié par le nombre de salariés', 'Le prix de l\'action divisé par le dividende', 'Le dividende divisé par la dette'],
      correct: 0, rationale: 'Si l\'action Total vaut 50 € et verse 3 € de dividende, le rendement est de 6 %. Si l\'action monte à 100 € et verse toujours 3 €, le rendement chute à 3 %.' },
    { q: 'Que se passe-t-il mécaniquement sur le prix de l\'action en bourse le jour exact où le dividende est versé (jour de détachement) ?',
      options: ['Le prix de l\'action reste identique', 'Le prix double', 'Le prix de l\'action augmente du montant du dividende', 'Le cours de l\'action BAISSE d\'un montant théoriquement exact à celui du dividende détaché'],
      correct: 3, rationale: 'C\'est logique : la trésorerie quitte l\'entreprise pour aller sur les comptes des actionnaires. L\'entreprise "vaut" donc instantanément moins cher de ce montant.' },
    { q: 'Pour profiter de la puissance des "intérêts composés" sur un portefeuille boursier, que doit faire l\'investisseur avec ses dividendes ?',
      options: ['Les transférer sur un Livret A', 'Les réinvestir immédiatement pour racheter de nouvelles actions de cette même entreprise ou du même ETF', 'Les dépenser pour ses loisirs', 'Payer ses impôts en avance'],
      correct: 1, rationale: 'Sans ce réinvestissement (qui achètera des actions générant elles-mêmes de futurs dividendes), la croissance exponentielle du portefeuille est impossible.' },
    { q: 'Plutôt que de verser un dividende lourdement taxé pour l\'investisseur, quelle "autre" méthode les entreprises (notamment américaines) utilisent-elles pour enrichir leurs actionnaires ?',
      options: ['Elles offrent des produits gratuits', 'Elles paient l\'impôt sur le revenu des actionnaires', 'Le "Rachat d\'actions" (Buyback) : l\'entreprise rachète ses propres actions en bourse et les détruit, ce qui augmente mécaniquement la valeur et la part des actions restantes', 'Elles divisent le prix des actions'],
      correct: 2, rationale: 'S\'il y a moins d\'actions en circulation pour un même bénéfice, la valeur de chaque action augmente. Cela crée une plus-value latente non taxée immédiatement.' },
    { q: 'En jargon boursier, comment appelle-t-on les "Aristocrates du dividende" ?',
      options: ['Des entreprises très solides qui ont versé et AUGMENTÉ leur dividende chaque année, de manière ininterrompue, pendant au moins 25 ans', 'Les actionnaires qui portent la particule', 'Les entreprises du secteur du luxe', 'Les entreprises qui versent 100 % de leurs bénéfices'],
      correct: 0, rationale: 'Ces entreprises (souvent américaines, comme Coca-Cola ou Johnson & Johnson) rassurent énormément les investisseurs cherchant des rentes fiables.' },
    { q: 'Le versement d\'un dividende par une entreprise est-il une obligation légale garantie ?',
      options: ['Oui, s\'il a été versé l\'année précédente', 'Oui, la loi impose 2 % minimum', 'Uniquement pour les banques', 'Non. L\'entreprise peut décider de réduire, de suspendre ou de supprimer totalement (couper) le dividende si elle traverse une crise ou si elle préfère réinvestir l\'argent'],
      correct: 3, rationale: 'Lors de la crise du Covid-19 en 2020, des dizaines de fleurons mondiaux ont suspendu leur dividende pour protéger leur trésorerie.' },
    { q: '(Challenge) Qu\'est-ce que le "Piège du haut rendement" (Yield Trap) auquel doivent faire très attention les chasseurs de dividendes ?',
      options: ['Un dividende versé en monnaie étrangère', 'L\'obligation de garder l\'action 10 ans', 'Une action affiche un rendement facial énorme (ex : 15 %) UNIQUEMENT parce que le prix de l\'action s\'est effondré en bourse (signe que l\'entreprise va mal et va probablement bientôt couper ce dividende)', 'Un dividende taxé à 50 %'],
      correct: 2, rationale: 'Rappel : Rendement = Dividende / Prix. Si le prix divise par 3 parce que l\'entreprise est en quasi-faillite, le rendement facial triple. Mais acheter serait une erreur grave.' },
    { q: '(Challenge) Sur un Compte Titres Ordinaire (CTO), si le contribuable choisit l\'option d\'imposition au "Barème progressif" (pour échapper aux 30 % de la Flat Tax), de quel avantage fiscal majeur bénéficiera le DIVIDENDE reçu ?',
      options: ['Le remboursement des prélèvements sociaux', 'Un abattement forfaitaire de 40 % sur le montant du dividende imposable (pour éviter la double imposition des bénéfices de l\'entreprise)', 'Le dividende est totalement exonéré', 'Le courtier offre les frais de bourse'],
      correct: 1, rationale: 'Si vous touchez 1 000 € de dividendes et choisissez le barème progressif, le fisc n\'intègrera que 600 € à vos revenus pour calculer l\'impôt.' },
  ],
  'w24-d1': [
    { q: 'En droit fiscal français, comment sont officiellement qualifiées les cryptomonnaies (Bitcoin, Ethereum) ?',
      options: ['Des devises étrangères', 'Des bons de caisse', 'Des titres de propriété immobilière', 'Des "Actifs Numériques" (ou crypto-actifs)'],
      correct: 3, rationale: 'Elles ne sont pas reconnues comme des monnaies légales (monnaie fiat) mais comme des actifs immatériels soumis à un régime d\'imposition spécifique.' },
    { q: 'Quel est "l\'événement déclencheur" (le fait générateur) qui rend vos gains en cryptomonnaies IMPOSABLES à l\'impôt sur le revenu ?',
      options: ['La simple hausse du cours sur la plateforme', 'Le transfert de cryptos vers une clé Ledger', 'La revente de la crypto contre une monnaie "Fiat" (Euros, Dollars) OU l\'utilisation de la crypto pour acheter un bien ou un service réel (ex : une voiture payée en Bitcoin)', 'L\'ouverture du compte chez Binance'],
      correct: 2, rationale: 'Tant que la richesse reste confinée dans l\'univers de la blockchain, le fisc considère qu\'aucun gain réel (utilisable dans l\'économie) n\'a été matérialisé.' },
    { q: 'Une règle fiscale exceptionnelle concerne les "Échanges purs" (Crypto contre Crypto). Que se passe-t-il si vous vendez un Bitcoin pour acheter directement de l\'Ethereum ?',
      options: ['C\'est une opération blanche (neutralité fiscale) : il n\'y a aucun calcul ni paiement d\'impôt à faire sur ce type de transaction', 'Il faut payer la TVA à 20 %', 'On paie l\'impôt sur la plus-value du Bitcoin', 'L\'échange est interdit'],
      correct: 0, rationale: 'C\'est la force de l\'écosystème. L\'astuce majeure des investisseurs est de vendre leurs cryptos contre des "Stablecoins" (ex: USDT, indexés sur le dollar) pour sécuriser leurs gains en évitant l\'Euro et donc l\'impôt.' },
    { q: 'Quel est le taux d\'imposition par DÉFAUT des plus-values sur actifs numériques pour un investisseur occasionnel (particulier) ?',
      options: ['10 %', 'Le PFU (Flat Tax) de 30 % (soit 12,8 % d\'IR + 17,2 % de CSG)', '50 %', 'Le barème progressif obligatoire'],
      correct: 1, rationale: 'Les cryptomonnaies ont été alignées sur la fiscalité classique du capital (la Bourse) pour simplifier le système.' },
    { q: 'Il existe une "Franchise d\'imposition" (un seuil de tolérance) très précis par année civile. Quel est-il ?',
      options: ['Pas d\'impôt si la plus-value est inférieure à 10 000 €', 'Pas d\'impôt la première année', 'Pas d\'impôt pour les étudiants', 'Si le total des CESSIONS (ventes) en devises réelles (Euros) de l\'année ne dépasse pas 305 €, les plus-values éventuelles sont totalement exonérées d\'impôt'],
      correct: 3, rationale: 'Attention, on parle du total des VENTES, pas de la plus-value. Si vous vendez pour 306 €, vous devrez calculer et payer l\'impôt sur la plus-value de cette vente.' },
    { q: 'Même si vous n\'avez fait AUCUNE vente de crypto dans l\'année (pas de plus-value), quelle obligation annuelle LOURDE avez-vous envers le fisc ?',
      options: ['Déclarer obligatoirement, sur le Cerfa n°3916-BIS, tous vos comptes de cryptomonnaies ouverts, détenus ou clos à L\'ÉTRANGER (ex: Binance, Kraken), sous peine d\'une amende de 750 € par compte non déclaré', 'Payer une taxe de stockage', 'Envoyer votre historique de transactions', 'Déclarer vos clés privées'],
      correct: 0, rationale: 'C\'est le piège numéro 1. Le fisc veut cartographier l\'évasion fiscale. Oublier de déclarer ses comptes étrangers coûte très cher lors des contrôles.' },
    { q: 'Concernant le choix du taux d\'imposition des cryptos (PFU à 30 %), une grande nouveauté est intervenue depuis les revenus 2023. Laquelle ?',
      options: ['L\'exonération totale après 5 ans', 'Le taux est passé à 60 %', 'Le particulier a désormais le droit d\'"opter" pour le Barème Progressif de l\'impôt sur le revenu (si sa TMI est faible) au lieu du PFU, comme pour la bourse', 'Les pertes sont remboursées'],
      correct: 2, rationale: 'Avant 2023, le PFU de 30% était une punition inévitable pour un chômeur ou un étudiant qui faisait une plus-value crypto. Désormais, ils peuvent choisir d\'être taxés à 0% ou 11% (plus la CSG de 17,2%).' },
    { q: 'Que se passe-t-il fiscalement si vous enregistrez une MOINS-VALUE globale (perte) sur les cryptos à la fin de l\'année ?',
      options: ['L\'État rembourse 30 %', 'La perte est perdue : les moins-values sur actifs numériques NE SONT PAS REPORTABLES sur les années suivantes (contrairement à la bourse)', 'Elle efface l\'impôt sur le salaire', 'Elle s\'impute sur les plus-values immobilières'],
      correct: 1, rationale: 'C\'est une grande injustice du système actuel. Si vous perdez 10 000€ en 2023 et gagnez 10 000€ en 2024, le fisc ignorera votre perte et vous taxera 3 000€ sur votre gain de 2024.' },
    { q: '(Challenge) Lors d\'une vente en Euros, la formule de calcul de la plus-value crypto du fisc est un cauchemar mathématique (Formulaire 2086). Sur quoi se base-t-elle ?',
      options: ['Sur la règle stricte de la proportionnalité : on déduit du prix de revente une fraction du prix d\'acquisition total (Prix achat x [Prix de vente / Valeur totale du portefeuille crypto au jour de la vente])', 'Le fisc prend 10 % forfaitaires de la vente', 'L\'impôt se base uniquement sur le dernier Bitcoin acheté (LIFO)', 'L\'impôt est fixé par la plateforme'],
      correct: 0, rationale: 'Ce calcul ultra-complexe oblige le déclarant à connaître la valeur de TOUS ses comptes cryptos à la seconde précise de sa vente pour évaluer la part de plus-value latente retirée. (Des logiciels d\'aide à la déclaration sont devenus indispensables).' },
    { q: '(Challenge) Si le fisc considère (lors d\'un contrôle) que vous n\'êtes pas un investisseur "occasionnel" mais un investisseur "PROFESSIONNEL" (vous faites du day-trading complexe, utilisez des bots, réalisez énormément de transactions). Que risquez-vous ?',
      options: ['L\'obligation de former les agents du fisc', 'L\'interdiction d\'utiliser internet', 'La prison', 'La requalification des gains en Bénéfices Non Commerciaux (BNC) ou Bénéfices Industriels et Commerciaux (BIC), taxés au barème progressif ET soumis aux lourdes cotisations sociales (URSSAF)'],
      correct: 3, rationale: 'L\'impôt global peut alors bondir à 40 % ou 50 %. Les critères de requalification restent flous, mais l\'utilisation d\'outils professionnels ou la fréquence démesurée des ordres éveillent l\'attention du fisc.' },
  ],
  'w24-d2': [
    { q: 'Que signifie le sigle C2P (anciennement C3P) en droit du travail et de la retraite ?',
      options: ['Caisse des Pensions Publiques', 'Compte Professionnel de Prévention (souvent appelé compte pénibilité)', 'Contrat Personnel de Préretraite', 'Compte Partagé de Performance'],
      correct: 1, rationale: 'Ce dispositif vise à compenser la difficulté de certains métiers "usants" en accordant des avantages pour la fin de carrière des salariés concernés.' },
    { q: 'Comment le Compte Professionnel de Prévention est-il alimenté pour le salarié ?',
      options: ['Par une prime de la mairie', 'Par des versements volontaires du salarié', 'En points : le salarié exposé à un ou plusieurs facteurs de risques professionnels cumule des points sur son compte à la fin de chaque année d\'exposition', 'En trimestres gratuits offerts par l\'Assurance Maladie'],
      correct: 2, rationale: 'L\'exposition à 1 facteur de risque permet de cumuler 4 points par an. L\'exposition simultanée à plusieurs facteurs donne 8 points par an.' },
    { q: 'Lequel de ces facteurs EST TOUJOURS RECONNU comme un critère de pénibilité alimentant le C2P en 2024 ?',
      options: ['Le travail de nuit, le travail en équipes successives alternantes (les 3x8), le bruit, les températures extrêmes ou le travail en milieu hyperbare', 'Le stress au bureau', 'Les trajets longs en voiture', 'L\'utilisation prolongée d\'un écran d\'ordinateur'],
      correct: 0, rationale: 'Ces facteurs, liés à des rythmes ou environnements physiquement dangereux, doivent dépasser des seuils stricts définis par la loi (ex: 120 nuits par an) pour déclencher l\'attribution de points.' },
    { q: 'Par souci de simplification pour les employeurs (réforme de 2017), quels facteurs de pénibilité très courants ONT ÉTÉ RETIRÉS du Compte C2P (ils ne génèrent plus de points) ?',
      options: ['Le travail de nuit et le bruit', 'Les missions à l\'étranger', 'Les contrats à durée déterminée (CDD)', 'Le port de charges lourdes, les postures pénibles, les vibrations mécaniques et l\'exposition aux agents chimiques dangereux'],
      correct: 3, rationale: 'Ces facteurs ont été jugés trop complexes à mesurer individuellement par les PME. Ils sont sortis du C2P (mais donnent droit à un départ anticipé sous d\'autres conditions si une maladie professionnelle survient).' },
    { q: 'Quel est le plafond MAXIMUM de points qu\'un salarié peut cumuler sur son Compte Professionnel de Prévention tout au long de sa carrière ?',
      options: ['10 points', '100 points', '500 points', 'Il n\'y a aucune limite'],
      correct: 1, rationale: 'Ce plafond limite mécaniquement le coût du dispositif et empêche des départs en retraite excessivement précoces.' },
    { q: 'Concernant la RETRAITE, à quoi peuvent servir les points cumulés sur le C2P ?',
      options: ['À partir à la retraite jusqu\'à 2 ans AVANT l\'âge légal (8 points = 1 trimestre de majoration, qui sera considéré comme cotisé)', 'À doubler le montant de la pension', 'À payer les impôts de la succession', 'À annuler la décote à 60 ans'],
      correct: 0, rationale: 'C\'est la récompense ultime de l\'usure au travail. Le salarié utilise ses points pour acheter des trimestres lui permettant d\'échapper aux dernières années de son emploi.' },
    { q: 'Outre l\'anticipation de l\'âge de la retraite, quelles sont les DEUX autres utilisations possibles des points C2P ?',
      options: ['Acheter une voiture ou rénover sa maison', 'Prendre des congés payés ou payer la cantine', 'Financer une formation professionnelle (pour changer de métier vers un poste moins pénible) ET/OU financer un passage à temps partiel en fin de carrière sans perte de salaire', 'Donner ses points à son conjoint ou à l\'État'],
      correct: 2, rationale: 'L\'objectif de la loi n\'est pas seulement de faire partir les gens plus tôt, mais de faire de la "prévention" en les aidant à quitter les postes usants pendant leur carrière.' },
    { q: 'Qui est chargé de déclarer à l\'administration que le salarié dépasse les seuils de pénibilité (et déclenche donc la création des points) ?',
      options: ['Le médecin du travail', 'Le médecin traitant du salarié', 'Le salarié lui-même via un formulaire CERFA', 'L\'employeur, via la Déclaration Sociale Nominative (DSN) envoyée chaque année'],
      correct: 3, rationale: 'C\'est la responsabilité légale du chef d\'entreprise d\'évaluer, de tracer et de déclarer l\'exposition de ses ouvriers/employés aux facteurs de risque.' },
    { q: '(Challenge) Afin d\'encourager la reconversion professionnelle (et d\'éviter que tout le monde n\'utilise ses points pour partir plus tôt), quelle "Règle des 20 premiers points" s\'applique au C2P (sauf pour les salariés proches de la retraite) ?',
      options: ['Ils sont annulés après 5 ans', 'Les 20 premiers points cumulés sont obligatoirement RÉSERVÉS au financement d\'une formation de reconversion (1 point = 500 €). On ne peut utiliser ses points pour la retraite qu\'à partir du 21ème point acquis', 'Ils sont versés en espèces', 'Ils sont donnés à la Sécurité Sociale'],
      correct: 1, rationale: '(Ceux nés avant 1960 ou 1963 sont exemptés de cette règle pour des raisons d\'âge). Le législateur "force" ainsi la formation pour sortir le salarié de la pénibilité le plus tôt possible.' },
    { q: '(Challenge) Comme vu plus haut, le "Port de charges lourdes" a été retiré du C2P. Toutefois, un dispositif de départ anticipé pour pénibilité subsiste pour ces travailleurs (les maçons, déménageurs...). Quelle est la condition dramatique pour en bénéficier ?',
      options: ['Demander l\'accord de l\'employeur', 'Avoir 150 trimestres validés', 'L\'assuré doit justifier d\'une Incapacité Permanente (maladie professionnelle ou accident du travail) d\'au moins 10 % directement liée à ces charges lourdes, reconnue par un médecin-conseil', 'Payer une surcotisation de 10 %'],
      correct: 2, rationale: 'Pour ces facteurs exclus, on ne compte plus les "points" d\'exposition. Il faut malheureusement que la santé de l\'employé soit "déjà brisée" (le corps médical constatant les séquelles définitives) pour qu\'il puisse partir à 60 ou 62 ans.' },
  ],
  'w24-d3': [
    { q: 'Dans les montages patrimoniaux, qu\'est-ce qu\'une clause de "Réversion d\'usufruit" (ou usufruit successif) ?',
      options: ['L\'obligation de vendre l\'usufruit à un tiers', 'L\'annulation de l\'usufruit', 'Lors d\'une donation de la nue-propriété aux enfants (les parents conservant l\'usufruit), cette clause prévoit qu\'au décès du premier parent, l\'usufruit ne s\'éteint pas, mais est transféré (réversé) dans sa totalité au conjoint survivant', 'Le partage de l\'usufruit avec les voisins'],
      correct: 2, rationale: 'C\'est le bouclier ultime entre époux. Sans cette clause, la moitié de l\'usufruit s\'éteindrait, et les enfants pourraient interférer dans la jouissance de la maison.' },
    { q: 'Quel est l\'objectif premier pour des parents d\'insérer cette clause lors d\'une donation à leurs enfants ?',
      options: ['Protéger le conjoint survivant, qui gardera la jouissance entière du bien (et/ou de ses revenus locatifs) jusqu\'à son propre décès, sans dépendre de l\'accord des enfants', 'Augmenter la valeur de la maison', 'Éviter la taxe foncière', 'Payer le notaire moins cher'],
      correct: 0, rationale: 'Le conjoint survivant reste "le maître" de la maison. Il peut y vivre ou la louer pour payer son éventuelle maison de retraite.' },
    { q: 'Juridiquement (et c\'est une subtilité vitale), la réversion d\'usufruit au bénéfice du conjoint est-elle considérée comme une "nouvelle donation" au moment du premier décès ?',
      options: ['Oui, le notaire doit refaire l\'acte', 'Oui, mais seulement si le mariage est récent', 'Uniquement pour les partenaires de PACS', 'Non. Elle est analysée comme une modalité (une simple conséquence) de la donation initiale. Le droit du conjoint survivant naît le jour de la signature de l\'acte notarié de départ, mais son exercice est juste "retardé" au jour du décès'],
      correct: 3, rationale: 'Le conjoint a déjà son droit en poche depuis 10 ans, il attendait juste le décès de l\'autre pour s\'en servir. Cela a un impact massif sur les conflits d\'héritage.' },
    { q: 'Sur le plan FISCAL, que doit payer le CONJOINT SURVIVANT (marié ou pacsé) lorsqu\'il récupère la part d\'usufruit de son défunt époux grâce à cette clause ?',
      options: ['Il paie 20 % d\'impôts', 'Il ne paie strictement AUCUN droit de mutation (impôt). La loi protège le conjoint et le partenaire de PACS, les exonérant totalement de droits de succession', 'Il doit payer la Flat Tax (30 %)', 'Il est taxé selon l\'âge des enfants'],
      correct: 1, rationale: 'Entre époux ou partenaires pacsés, la mise en œuvre de la réversion d\'usufruit est une opération fiscalement indolore (zéro impôt).' },
    { q: 'Que se passe-t-il pour les enfants (Nus-propriétaires) au moment de ce premier décès (lorsque le deuxième parent prend l\'usufruit successif) ?',
      options: ['La nue-propriété est annulée', 'Ils sont obligés d\'acheter l\'usufruit', 'Rien. Ils restent nus-propriétaires (ils doivent encore attendre). L\'usufruit ne s\'éteindra et ne rejoindra la nue-propriété qu\'au DEUXIÈME décès', 'Ils deviennent pleins propriétaires'],
      correct: 2, rationale: 'Le démembrement de propriété est simplement "prolongé" sur la tête du second parent.' },
    { q: 'Peut-on annuler une clause de réversion d\'usufruit en cas de grave crise de couple avant le décès ?',
      options: ['Oui. Entre époux, la réversion d\'usufruit est analysée comme une donation de biens à venir. Elle est donc généralement révocable "ad nutum" (librement et à tout moment) par celui qui l\'a consentie', 'Seulement si les enfants signent', 'Non, c\'est irrévocable comme toute donation', 'Uniquement avec l\'accord de la banque'],
      correct: 0, rationale: 'C\'est une soupape de sécurité du droit de la famille pour éviter qu\'un époux en instance de divorce ne conserve l\'usufruit d\'un bien appartenant à la famille de l\'autre.' },
    { q: 'Si l\'on n\'est pas marié ni pacsé (ex: deux concubins achètent une maison), quelle alternative juridique offre le même résultat de protection de la jouissance du bien que la réversion d\'usufruit ?',
      options: ['Le Livret A', 'Le crédit in fine', 'Le viager classique', 'La clause d\'accroissement (Pacte Tontinier), ou un montage via une SCI démembrée'],
      correct: 3, rationale: 'Les concubins étant des étrangers juridiques, la clause d\'usufruit successif les exposerait à la ruine fiscale.' },
    { q: 'Quel est le danger si l\'usufruit successif est consenti à une personne QUI N\'EST PAS LE CONJOINT ou le partenaire de PACS (ex : entre deux frères) ?',
      options: ['La mairie préemptera le bien', 'La fiscalité sera écrasante. Sans la protection du mariage/PACS, le frère survivant devra payer des droits de mutation (impôts) à 45% ou 60% sur la valeur de l\'usufruit qu\'il récupère', 'Le frère perd son droit de vote', 'La banque bloque la maison'],
      correct: 1, rationale: 'La réversion d\'usufruit n\'est un outil magique qu\'à la condition que le bénéficiaire soit protégé par la loi fiscale (conjoint/pacs).' },
    { q: '(Challenge) Lors du second et dernier décès (le parent survivant s\'éteint), que paieront les enfants (nus-propriétaires) pour récupérer enfin la maison en pleine propriété ?',
      options: ['Ils paieront le notaire en double', '20 % du prix de la maison', '0 €. L\'usufruit s\'éteignant par la mort de son titulaire (article 1133 CGI), le remembrement est totalement gratuit. Les enfants récupèrent le bien sans aucun impôt de succession', 'Ils devront rembourser les impôts impayés du premier décès'],
      correct: 2, rationale: 'C\'est la finalité triomphale du montage. Les parents ont été protégés jusqu\'à la fin de leurs jours, et les enfants évitent le massacre fiscal de la succession.' },
    { q: '(Challenge) En droit strict, la Cour de cassation fait la distinction entre la "réversion d\'usufruit" et "l\'usufruit éventuel". Qu\'est-ce qui les sépare ?',
      options: ['La date de l\'ouverture des droits et son analyse fiscale : la réversion est un droit déjà constitué (favorable au conjoint), l\'usufruit éventuel est un droit soumis à une condition de survie', 'L\'usufruit éventuel s\'applique aux voitures', 'C\'est le même mot en anglais', 'La réversion est interdite en France'],
      correct: 0, rationale: 'C\'est de la haute ingénierie notariale. Les notaires utilisent l\'expression "réversion" pour s\'assurer que le fisc traite l\'avantage comme une condition intégrée de la donation initiale et non comme un nouvel héritage distinct.' },
  ],
  'w24-d4': [
    { q: 'En assurance de dommages, qu\'est-ce que la "vétusté" ?',
      options: ['La garantie vol', 'La dépréciation (la perte de valeur) d\'un bien causée par son âge, son usage, ou son usure normale', 'Une taxe pour les bâtiments anciens', 'Le fait de reconstruire un bien à l\'identique'],
      correct: 1, rationale: 'Un canapé de 10 ans vaut moins cher qu\'un canapé neuf sorti du magasin. L\'assureur tiendra compte de cette perte de valeur pour vous indemniser.' },
    { q: 'Si votre contrat habitation ne prévoit que l\'indemnisation classique de base en "Valeur d\'Usage", comment l\'assureur calcule-t-il votre remboursement pour un meuble brûlé ?',
      options: ['Il paie le prix exact du meuble neuf d\'aujourd\'hui', 'Il ne paie rien si le meuble a plus de 2 ans', 'Il rembourse la Valeur de Remplacement (prix du neuf), à laquelle il SOUSTRAIT le taux de vétusté (l\'usure). La somme versée sera donc très inférieure au prix en magasin', 'Il vous donne un meuble d\'occasion'],
      correct: 2, rationale: 'Vous ne pourrez pas racheter un meuble neuf avec l\'argent reçu.' },
    { q: 'Qu\'est-ce que l\'option "Valeur à Neuf" (sur les biens immobiliers ou le mobilier) très vendue dans les contrats Multirisque Habitation ?',
      options: ['Le remplacement du canapé tous les ans', 'Une option qui permet d\'annuler les franchises', 'Un bonus de l\'État', 'Une garantie où l\'assureur compense (prend en charge) la vétusté, afin de vous permettre de racheter ou de reconstruire un bien NEUF équivalent. (Cependant, cette garantie est souvent plafonnée, ex : elle ne couvre la vétusté que jusqu\'à 25 %)'],
      correct: 3, rationale: 'Si la vétusté retenue par l\'expert est de 20%, l\'option "Valeur à Neuf" vous paiera ces 20% supplémentaires pour atteindre le prix du neuf.' },
    { q: 'Qu\'est-ce que la garantie spécifique "Rééquipement à Neuf" (souvent appliquée à l\'électroménager ou l\'audiovisuel) ?',
      options: ['Elle remplace votre bien sans appliquer AUCUNE déduction de vétusté, quel que soit son âge (dans la limite de durée de la garantie, ex: les biens de moins de 5 ans ou 7 ans). L\'assureur vous paie le bien neuf au prix d\'aujourd\'hui', 'Elle vous donne accès à un catalogue de meubles', 'Elle vous force à racheter d\'occasion', 'C\'est un crédit à la consommation'],
      correct: 0, rationale: 'Si la télévision achetée il y a 3 ans brûle, l\'assureur vous versera de quoi racheter le modèle équivalent sorti cette année au magasin.' },
    { q: 'Pourquoi la loi encadre-t-elle strictement l\'option Valeur à Neuf (Principe Indemnitaire) ?',
      options: ['Pour protéger les magasins de meubles', 'Pour augmenter les prix des assurances', 'Pour éviter que l\'assurance ne soit un moyen de s\'enrichir (ou une incitation à la fraude). L\'assuré ne doit pas se retrouver dans une situation financière "meilleure" après l\'incendie qu\'avant', 'Parce que les assureurs refusent de payer'],
      correct: 2, rationale: 'Si un hangar pourri pouvait être remplacé par un entrepôt hyper-moderne grâce à l\'assurance, le taux d\'incendies criminels exploserait !' },
    { q: 'Qui décide du taux de vétusté (ex: -30%, -50%) appliqué à vos biens endommagés ?',
      options: ['La mairie', 'L\'Expert mandaté par l\'assurance, qui se base sur l\'âge du bien, les factures d\'achat, son entretien et des grilles de dépréciation internes', 'L\'assuré lui-même', 'Le magasin où a été acheté le bien'],
      correct: 1, rationale: 'C\'est souvent l\'objet des litiges. Conserver ses factures d\'entretien (ou d\'achat récent) permet de démontrer à l\'expert que le bien n\'était pas si usé que cela.' },
    { q: 'Concernant le bâti (les murs, la toiture de la maison), la vétusté s\'applique-t-elle ?',
      options: ['Seulement en cas d\'inondation', 'Uniquement sur les toits', 'Non, les maisons ne perdent jamais de valeur', 'Oui. Comme les meubles, la construction subit l\'usure du temps (une vieille charpente de 40 ans ne sera remboursée qu\'avec une forte décote si l\'option Valeur à Neuf Bâtiment n\'est pas souscrite)'],
      correct: 3, rationale: 'Reconstruire une vieille maison brûlée avec des matériaux neufs coûte beaucoup plus cher. Sans l\'option, l\'assuré devra ajouter un lourd "reste à charge" de sa poche au maçon.' },
    { q: 'Pour éviter les fraudes, quelle est la condition IMPÉRATIVE imposée par l\'assureur pour vous verser le complément "Valeur à Neuf" (les 20 ou 25 % supplémentaires) pour la reconstruction de votre maison détruite ?',
      options: ['La maison doit obligatoirement être reconstruite au MÊME ENDROIT (ou réparée) dans un délai de 2 ans suivant le sinistre', 'La maison doit être construite en bois', 'Vous devez acheter une voiture', 'Il faut l\'accord de tous les voisins'],
      correct: 0, rationale: 'Si l\'assuré décide d\'empocher l\'argent pour partir vivre aux Bahamas, il ne recevra que la valeur d\'usage (la valeur au jour du sinistre, usure déduite).' },
    { q: '(Challenge) Qu\'est-ce que la "Vétusté absolue" (ou Vétusté résiduelle) en cas de sinistre lourd ?',
      options: ['C\'est la vétusté qui annule le contrat', 'C\'est une décote inventée par le courtier', 'C\'est la part d\'usure qui dépasse le plafond de la garantie Valeur à Neuf et qui RESTERA à la charge de l\'assuré. (Ex : le bien est usé à 40 %, l\'assurance compense 25 %. Les 15 % restants sont la vétusté absolue due par l\'assuré)', 'La vétusté des œuvres d\'art'],
      correct: 2, rationale: 'Une maison quasi en ruines (usée à 60%) ne sera jamais remboursée intégralement pour faire du neuf. L\'assuré devra payer sa part.' },
    { q: '(Challenge) En assurance Automobile, ne confondez pas "Valeur Vénale" et "Valeur de Remplacement À Dire d\'Expert" (VRADE) lors d\'un vol ou destruction totale. Quelle est la différence utilisée par les experts auto ?',
      options: ['Il n\'y en a aucune, c\'est le même terme', 'La VRADE est le prix qu\'il vous faudrait débourser AUJOURD\'HUI pour racheter exactement le même véhicule d\'occasion (même âge, kilométrage). La valeur vénale est souvent le simple prix de rachat d\'un garagiste (plus bas)', 'La valeur vénale inclut le plein d\'essence', 'La VRADE est le prix du neuf'],
      correct: 1, rationale: 'C\'est pour cela qu\'en cas d\'accident, l\'assureur doit vous indemniser à hauteur de la VRADE pour que vous ne soyez pas lésé (Principe de la Réparation Intégrale du préjudice).' },
  ],
  'w24-d5': [
    { q: 'En investissement immobilier, qu\'est-ce que "la gestion locative déléguée" ?',
      options: ['Le locataire gère l\'appartement lui-même', 'C\'est la gestion d\'un parking', 'L\'État prend le contrôle de l\'appartement', 'Le propriétaire confie l\'administration complète de son bien (recherche de locataire, rédaction des baux, encaissement des loyers, gestion des travaux) à un professionnel de l\'immobilier (agence)'],
      correct: 3, rationale: 'C\'est la solution de tranquillité (ou de nécessité si l\'on vit loin du bien), qui transforme l\'immobilier physique en produit presque passif.' },
    { q: 'Quel est le nom du document (contrat) obligatoire qui lie le propriétaire bailleur et l\'agence immobilière pour encadrer cette mission ?',
      options: ['Le Mandat de Gestion', 'La Promesse de Vente', 'L\'état des lieux', 'Le bail d\'habitation'],
      correct: 0, rationale: 'Ce mandat écrit détermine l\'étendue exacte des pouvoirs du gérant (jusqu\'à quel montant de travaux il peut engager sans demander l\'accord du propriétaire, par exemple).' },
    { q: 'Combien coûte en moyenne la prestation d\'une agence (frais de gestion courante) pour gérer un appartement loué ?',
      options: ['C\'est toujours 1 % du loyer', 'Environ 20 % à 25 % des loyers', 'Entre 5 % et 10 % (TTC) du montant des loyers et charges encaissés', 'C\'est un forfait fixe de 500 € par mois'],
      correct: 2, rationale: 'Ce taux doit absolument être intégré dans le calcul de votre rendement net si vous ne souhaitez pas gérer vous-même.' },
    { q: 'Les frais de gestion locative payés à l\'agence présentent un avantage FISCAL. Lequel ?',
      options: ['Ils ouvrent droit au crédit d\'impôt CESU', 'Ils sont INTÉGRALEMENT DÉDUCTIBLES de vos revenus locatifs bruts (si vous êtes au régime Réel, foncier ou LMNP), ce qui fait baisser vos impôts', 'Ils annulent la taxe foncière', 'Ils sont remboursés par la CAF'],
      correct: 1, rationale: 'La gestion déléguée est donc "subventionnée" en partie par vos économies d\'impôts.' },
    { q: 'Attention aux "frais cachés" ou supplémentaires. Quel grand service (qui n\'est pas de la gestion quotidienne) est systématiquement facturé EN PLUS des 8% de gestion courante ?',
      options: ['Le ménage de la copropriété', 'Le contrôle de l\'assurance PNO', 'L\'envoi des quittances de loyer', 'Les honoraires de LOCATION (la recherche du locataire, les visites, la vérification du dossier et la rédaction du nouveau bail), souvent égaux à environ 1 mois de loyer'],
      correct: 3, rationale: 'C\'est l\'acte commercial de trouver le locataire. Les frais de "gestion", eux, ne couvrent que l\'intendance (encaisser le chèque tous les mois).' },
    { q: 'Face au risque d\'impayés, que vous propose (et conseille) massivement l\'agence de gestion à la signature du mandat ?',
      options: ['De souscrire au "contrat de groupe" de l\'agence pour la Garantie Loyers Impayés (GLI). Étant mutualisé pour tout son parc, le tarif est souvent beaucoup plus compétitif (entre 2 et 2,5%) qu\'un contrat pris seul par un particulier', 'De demander l\'aide de l\'État', 'D\'augmenter le loyer de 15 %', 'D\'engager un service de recouvrement musclé'],
      correct: 0, rationale: 'En confiant la gestion à l\'agence, vous accédez à ses conditions négociées d\'assurances.' },
    { q: 'En cas de réparation nécessaire dans l\'appartement (ex: la chaudière tombe en panne), quel est le rôle du gestionnaire ?',
      options: ['Il paie la chaudière avec son propre argent', 'Il fait les réparations lui-même avec une caisse à outils', 'Il fait intervenir un artisan (souvent de son réseau), gère le devis, et prélève le montant de la réparation directement sur le loyer perçu avant de reverser le solde au propriétaire', 'Il donne le numéro de téléphone au locataire pour qu\'il se débrouille'],
      correct: 2, rationale: 'Le gestionnaire est l\'interface (le tampon) entre les plaintes du locataire et le portefeuille du bailleur.' },
    { q: 'Quelle est généralement la durée d\'engagement d\'un mandat de gestion (loi Hoguet / Chatel) ?',
      options: ['10 ans obligatoirement', 'Souvent conclu pour 1 an renouvelable par tacite reconduction. Le propriétaire peut le résilier à l\'échéance en respectant un préavis (souvent de 1 à 3 mois)', '1 mois d\'essai', 'Il est valable à vie'],
      correct: 1, rationale: 'Grâce à la loi Chatel, l\'agence est même obligée de vous envoyer un courrier vous rappelant votre droit de résilier avant que le mandat ne se renouvelle automatiquement.' },
    { q: '(Challenge) Comment s\'appelle le document financier récapitulatif que l\'agence vous envoie chaque mois (ou chaque trimestre) accompagné de votre virement bancaire ?',
      options: ['Le DPE', 'La quittance de loyer', 'Le bilan comptable global', 'Le Compte Rendu de Gestion (CRG). Il liste le loyer brut, les honoraires prélevés, la TVA, et l\'éventuelle assurance déduite'],
      correct: 3, rationale: 'Ce document est indispensable pour remplir votre déclaration d\'impôts l\'année suivante sans faire d\'erreurs sur les sommes réellement perçues et les frais déductibles.' },
    { q: '(Challenge) Lors de TRES GROS travaux de rénovation (ex : refaire tout le toit ou toute l\'électricité), l\'agence peut réclamer des "Frais de suivi de travaux". De quoi s\'agit-il ?',
      options: ['Une facturation supplémentaire exceptionnelle (souvent de 1% à 3% du montant du chantier) pour rémunérer le temps passé par le gestionnaire à coordonner les différents corps de métier, car cela sort de la gestion locative ordinaire', 'Une caution de garantie de bonne fin', 'Le salaire de l\'artisan', 'L\'obligation de payer les taxes de la mairie'],
      correct: 0, rationale: 'Une simple panne de robinet rentre dans le forfait de gestion. Mais superviser la réfection d\'un appartement entier est chronophage. Vérifiez bien cette clause dans votre mandat !' },
  ],
};
