/* Questions de la semaine 21. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w21-d0': [
    { q: 'Qu\'est-ce qu\'une "Cryptomonnaie" (ou cryptoactif) ?',
      options: ['La nouvelle monnaie officielle de l\'Union Européenne', 'Une monnaie numérique (virtuelle) émise de pair à pair (sans banque centrale), reposant sur la cryptographie et la technologie de la blockchain', 'L\'argent stocké sur votre carte bancaire classique', 'Un lingot d\'or virtuel'],
      correct: 1, rationale: 'L\'objectif originel était de créer un système de transfert de valeur mondial échappant au contrôle des banques traditionnelles.' },
    { q: 'Qu\'est-ce que la "Blockchain", la technologie sous-jacente des cryptomonnaies ?',
      options: ['Le siège social de Bitcoin', 'Une banque d\'investissement chinoise', 'Une puce informatique insérée dans l\'ordinateur', 'Un grand registre public (livre de comptes) informatique, sécurisé, décentralisé et infalsifiable, qui trace et stocke la totalité des transactions effectuées depuis le début'],
      correct: 3, rationale: 'Chaque "bloc" de transactions est vérifié par le réseau puis lié (chainé) au précédent, empêchant toute modification a posteriori.' },
    { q: 'Quelle est la principale spécificité économique du Bitcoin (la reine des cryptos) qui suscite l\'intérêt des investisseurs face à l\'inflation ?',
      options: ['Son offre est mathématiquement plafonnée : il n\'y aura jamais plus de 21 millions de Bitcoins en circulation (rareté intrinsèque), contrairement aux monnaies classiques (Euros, Dollars) qui peuvent être imprimées à l\'infini', 'Il est soutenu par les réserves d\'or américaines', 'Il garantit un rendement de 5 % par an', 'Le gouvernement fixe son prix'],
      correct: 0, rationale: 'Cette rareté algorithmique (le code informatique) lui donne son statut "d\'Or Numérique" aux yeux des investisseurs.' },
    { q: 'Quel est le RISQUE majeur de l\'investissement en cryptomonnaie ?',
      options: ['La volatilité extrême (le cours peut s\'effondrer de 50 % en quelques jours) et le risque de perte totale en capital (piratage, perte de mots de passe, absence de régulation forte)', 'L\'obligation de payer les transactions en or physique', 'La lourdeur administrative pour en acheter', 'L\'impossibilité de les revendre le week-end'],
      correct: 0, rationale: 'Le marché des cryptos est ouvert 24h/24, 7j/7, et n\'est adossé à aucun actif physique ni garantie d\'État.' },
    { q: 'Qu\'est-ce qu\'un "Wallet" en crypto ?',
      options: ['Un portefeuille physique (application, clé USB type Ledger, logiciel) indispensable pour stocker en sécurité les clés cryptographiques privées permettant de dépenser ses cryptomonnaies', 'Une taxe boursière sur les monnaies virtuelles', 'Le nom des traders professionnels', 'Un logiciel de la banque de France'],
      correct: 0, rationale: 'C\'est le coffre-fort de la crypto. Sans lui, vos actifs numériques sont à la merci de votre plateforme d\'échange.' },
    { q: 'Que signifie l\'adage fondamental des puristes de la crypto : "Not your keys, not your coins" (Pas vos clés, pas vos pièces) ?',
      options: ['Si vous ne stockez pas VOS cryptos sur un Wallet physique dont vous possédez seul la clé privée, mais que vous les laissez sur la plateforme d\'échange (ex: Binance), vous ne les possédez pas vraiment (si la plateforme fait faillite, vous perdez tout)', 'Qu\'il faut toujours laisser son argent à la banque', 'Qu\'il faut acheter des clés USB en or', 'C\'est un code pour payer moins de frais'],
      correct: 0, rationale: 'C\'est la leçon tragique de la faillite de FTX (2022). Les clients ont perdu leurs fonds car c\'était la plateforme qui détenait les clés d\'accès.' },
    { q: 'En France, comment l\'Autorité des Marchés Financiers (AMF) tente-t-elle de sécuriser et réguler l\'achat de cryptos pour les particuliers ?',
      options: ['En créant le statut de PSAN (Prestataire de Services sur Actifs Numériques) : les plateformes doivent s\'enregistrer auprès de l\'AMF (vérification d\'identité, lutte contre le blanchiment) pour avoir le droit d\'opérer en France', 'En interdisant l\'achat de Bitcoins', 'En remboursant les pertes boursières', 'En taxant chaque connexion internet'],
      correct: 0, rationale: 'Utiliser une plateforme non enregistrée PSAN expose le particulier à des risques d\'arnaques majeurs sans aucun recours légal en France.' },
    { q: 'Comment s\'appellent les plateformes où l\'on convertit ses Euros en Cryptomonnaies (et inversement) ?',
      options: ['Les Brokers traditionnels', 'Les Exchanges (ex : Binance, Kraken, Coinbase, Coinhouse)', 'Les Banques Centrales', 'Les SCPI numériques'],
      correct: 1, rationale: 'Ce sont les "bureaux de change" de l\'écosystème crypto, facturant des frais sur chaque transaction d\'achat/vente.' },
    { q: '(Challenge) Qu\'est-ce qu\'un "Stablecoin" (comme l\'USDT ou l\'USDC) par opposition aux cryptomonnaies classiques ?',
      options: ['Une cryptomonnaie dont le cours n\'est pas volatil, car il est "adossé" (ancré) à la valeur d\'une monnaie physique (le plus souvent 1 Stablecoin = 1 Dollar américain), servant de refuge aux traders pendant les baisses de marché', 'Une crypto qui ne s\'achète qu\'une fois par an', 'Une monnaie garantie par l\'ONU', 'La monnaie utilisée dans les banques européennes'],
      correct: 0, rationale: 'Le Stablecoin est la "monnaie d\'échange et de parking" de la blockchain. Au lieu de retirer ses euros à la banque, le trader vend ses bitcoins contre des stablecoins pour sécuriser ses gains.' },
    { q: '(Challenge) Quelle est la stratégie d\'investissement (DCA) la plus recommandée par les conseillers pour investir sur un actif aussi ultra-volatil que le Bitcoin ?',
      options: ['La stratégie DCA (Dollar Cost Averaging) : investir la MÊME SOMME à intervalles réguliers (ex: 50€/mois) pour lisser le coût d\'achat et éviter le risque d\'acheter tout son capital le jour où le cours est au plus haut (all-in)', 'Acheter uniquement quand ça baisse', 'Vendre dès qu\'on gagne 5 %', 'Emprunter à la banque pour acheter un Bitcoin entier'],
      correct: 0, rationale: 'C\'est la seule méthode rationnelle face à un actif qui fait le "yoyo", protégeant l\'investisseur du stress et des erreurs de market-timing.' },
  ],
  'w21-d1': [
    { q: 'En finance, à quoi correspondent les "Droits de garde" (ou frais de garde) ?',
      options: ['Les frais de nounou pour les enfants', 'Les impôts payés sur les dividendes', 'Des frais facturés annuellement par une banque classique pour la simple conservation de vos titres financiers (actions, obligations) sur un Compte Titres (CTO) ou un PEA', 'L\'assurance du banquier'],
      correct: 2, rationale: 'Ces frais, très fréquents dans les réseaux bancaires traditionnels, s\'ajoutent aux frais de transaction (courtage).' },
    { q: 'Quelle est la particularité des "frais de courtage" par opposition aux droits de garde ?',
      options: ['Ils sont gratuits', 'Ils sont prélevés tous les mois, quoi qu\'il arrive', 'Les frais de courtage ne sont facturés QU\'À LA TRANSACTION (lorsque vous achetez ou vendez une action), alors que les droits de garde sont un coût fixe récurrent de conservation', 'Ils sont prélevés par l\'État'],
      correct: 2, rationale: 'Acheter une action engendre des frais de courtage. La garder 10 ans sans y toucher engendre des droits de garde annuels (si votre banque en pratique).' },
    { q: 'De plus en plus d\'investisseurs quittent les banques traditionnelles pour des courtiers en ligne (Bourse Direct, Fortuneo, Boursorama, Trade Republic). Quel est leur principal argument marketing ?',
      options: ['Ils ont de très belles agences', 'Ils offrent des actions de leur entreprise', 'Ils offrent les repas', 'L\'absence totale de "droits de garde" et de frais de tenue de compte'],
      correct: 3, rationale: 'Sur 20 ans, éviter ces frais récurrents de conservation permet d\'économiser des milliers d\'euros.' },
    { q: 'FISCALITÉ : Sur un Compte-Titres (CTO), les droits de garde que vous payez à la banque sont-ils DÉDUCTIBLES de vos impôts ?',
      options: ['Non, jamais', 'Oui, déductibles de vos revenus boursiers de l\'année, UNIQUEMENT SI vous optez pour le "Barème progressif" de l\'impôt sur le revenu sur votre déclaration (case 2OP)', 'Oui, dans 100 % des cas', 'Uniquement si on les donne à une association'],
      correct: 1, rationale: 'C\'est une subtilité fiscale majeure. Le PFU (Flat Tax) est un prélèvement "sur le brut", aucune déduction de frais n\'est possible.' },
    { q: 'Que se passe-t-il pour ces frais de garde si vous restez, par défaut, soumis à la Flat Tax (PFU de 30 %) sur vos gains ?',
      options: ['Les frais sont remboursés par la CAF', 'La banque annule les frais', 'Les frais de garde NE SONT ABSOLUMENT PAS DÉDUCTIBLES fiscalement. Vous êtes taxé sur le montant brut de vos gains', 'Les impôts baissent de 50 %'],
      correct: 2, rationale: 'L\'investisseur soumis au PFU paie l\'impôt plein pot, il a donc tout intérêt à utiliser un courtier sans droits de garde.' },
    { q: 'Dans une Assurance-Vie, comment s\'appellent les frais récurrents (souvent entre 0,5 % et 1 % par an) prélevés par l\'assureur pour administrer le contrat ?',
      options: ['Les frais de notaire', 'La taxe sur la valeur ajoutée', 'L\'impôt de solidarité', 'Les frais de gestion'],
      correct: 3, rationale: 'Ils sont prélevés annuellement en grignotant une petite partie de votre capital ou de vos intérêts (le fameux nombre de parts en UC qui diminue légèrement chaque année).' },
    { q: 'Concernant le Plan d\'Épargne en Actions (PEA), que stipule la loi PACTE (2020) pour protéger les épargnants des frais bancaires abusifs ?',
      options: ['Les frais d\'entrée (courtage) sont limités à 0,5 % (pour un ordre en ligne), et les droits de garde sont PLAFONNÉS à 0,4 % de la valeur du portefeuille par an', 'La banque doit verser une prime', 'Tous les frais sont formellement interdits', 'Les frais sont fixés librement par le directeur d\'agence'],
      correct: 0, rationale: 'L\'État voulait relancer l\'attrait du PEA en stoppant le matraquage tarifaire des banques traditionnelles.' },
    { q: 'Si vous déléguez votre épargne (Assurance-vie, PER) à un expert qui choisit les actifs à votre place, comment s\'appelle ce service payant (souvent +0,2 % à +0,5 % de frais annuels) ?',
      options: ['La gestion passive', 'Le Livret A', 'Le dépôt de garantie', 'La gestion sous mandat (ou gestion pilotée)'],
      correct: 3, rationale: 'La tranquillité se paie. L\'expert prend les commandes de votre portefeuille en fonction de votre profil de risque (équilibré, dynamique).' },
    { q: '(Challenge) Qu\'est-ce que la pratique très controversée des "Rétrocessions de commissions" (Kickbacks) dans le monde des conseillers bancaires ?',
      options: ['Le remboursement des crédits', 'Le client paie un abonnement mensuel au banquier', 'C\'est de l\'argent public détourné', 'Le conseiller (ou la banque) touche une "commission occulte" de la part du créateur du fonds d\'investissement (ex: Amundi, Carmignac) à chaque fois qu\'il place l\'argent du client sur ce fonds précis'],
      correct: 3, rationale: 'Cela génère un conflit d\'intérêts majeur. Le banquier peut être tenté de vous conseiller le produit qui lui rapporte la plus grosse commission, plutôt que le meilleur produit pour vous (d\'où l\'essor des ETF sans rétrocession).' },
    { q: '(Challenge) Lors de l\'achat d\'un fonds classique (OPCVM) via votre banque, on vous facture des "Frais d\'entrée" (ou frais de versement) de 2 %. Qu\'est-ce que cela signifie concrètement ?',
      options: ['Vous commencez l\'investissement avec une perte de -2 % : sur 1 000 € versés, seuls 980 € seront réellement investis pour travailler sur les marchés', 'Le fonds promet de gagner 2 % l\'année suivante', 'La banque vous offre 2 % de bonus', 'Le rendement final sera amputé de 2 % à la sortie'],
      correct: 0, rationale: 'Ces frais, quasiment supprimés sur internet, sont un énorme frein à l\'investissement. Il vous faudra attendre que le fonds gagne +2 % juste pour retrouver votre mise de départ de 1000 €.' },
  ],
  'w21-d2': [
    { q: 'Arrivé à la retraite avec un Plan d\'Épargne Retraite (PER), vous choisissez la sortie en "Rente Viagère". Qu\'est-ce que cela signifie ?',
      options: ['Vous touchez la totalité de votre argent en une fois, sans impôts', 'Le compte est saisi par l\'État', 'La banque annule vos intérêts', 'L\'assureur conserve l\'épargne que vous avez accumulée (aliénation du capital), et s\'engage en échange à vous verser un revenu fixe régulier (mensuel/trimestriel) garanti JUSQU\'À VOTRE DÉCÈS'],
      correct: 3, rationale: 'C\'est le principe de l\'assurance contre le risque de "vivre trop vieux" (risque de longévité). Vous ne manquerez jamais d\'argent.' },
    { q: 'À l\'inverse, vous choisissez la "Sortie en Capital" (la grande nouveauté du PERin). De quoi s\'agit-il ?',
      options: ['Vous récupérez vous-même l\'intégralité de l\'argent accumulé sur votre compte, soit en un seul versement (one-shot), soit de manière "fractionnée" (vous piochez la somme que vous voulez chaque année)', 'L\'argent est bloqué pour vos enfants', 'Vous devez acheter une maison avec cet argent', 'Vous transférez l\'argent à la Sécurité Sociale'],
      correct: 0, rationale: 'Vous reprenez la main sur votre patrimoine. Si vous voulez acheter un camping-car ou aider vos petits-enfants, vous disposez d\'un gros "cash" immédiat.' },
    { q: 'Quel est l\'inconvénient (le risque) majeur pour l\'épargnant lorsqu\'il choisit la Rente Viagère simple ?',
      options: ['La rente est payée en monnaie étrangère', '"L\'Aliénation du capital" : s\'il meurt très tôt (ex: 6 mois après la retraite), le capital accumulé pendant 30 ans est "perdu" pour sa famille (conservé par l\'assureur)', 'Le juge interdit cette sortie', 'La rente s\'arrête au bout de 10 ans'],
      correct: 1, rationale: 'En contrepartie, si l\'épargnant vit jusqu\'à 110 ans, l\'assureur sera très perdant car il devra payer la rente pendant 45 ans.' },
    { q: 'Pour pallier cette peur de "perdre le capital" en cas de décès prématuré, quelle OPTION (légèrement coûteuse) peut-on ajouter à sa Rente Viagère ?',
      options: ['L\'option Rente de Réversion (versement d\'une partie de la rente au conjoint survivant après le décès) ou l\'option Annuités Garanties (l\'assureur paiera la rente X années quoiqu\'il arrive, aux héritiers si décès)', 'L\'option "Assurance tous risques voiture"', 'La garantie de remboursement par la mairie', 'L\'option de paiement en cash uniquement'],
      correct: 0, rationale: 'En échange d\'une rente mensuelle légèrement plus faible pour vous, vous garantissez la sécurité financière de votre conjoint si vous mourez tôt.' },
    { q: 'Quel est l\'inconvénient (le risque) majeur de la "Sortie en Capital" ?',
      options: ['La banque bloque les fonds 5 ans', 'Le "Risque de longévité" : l\'épargnant peut dépenser son capital trop vite. S\'il vit très vieux (ex: 95 ans), il risque de se retrouver sans un centime pour payer la maison de retraite (EHPAD)', 'La perte de la nationalité', 'L\'obligation de payer l\'ISF'],
      correct: 1, rationale: 'Vous reprenez la main, mais vous reprenez aussi la gestion du risque. C\'est à vous de budgétiser cet argent pour ne pas manquer de fonds à la fin de votre vie.' },
    { q: 'Sur quoi se base l\'assureur pour calculer le montant de la rente viagère qu\'il vous versera ?',
      options: ['Sur la table de "mortalité" (votre espérance de vie statistique), et l\'âge auquel vous demandez la rente (plus vous la demandez tard, plus la rente mensuelle sera élevée)', 'Sur le prix de l\'immobilier', 'Sur le nombre de vos enfants', 'Sur un tirage au sort national'],
      correct: 0, rationale: 'C\'est le "taux de conversion". À 65 ans, ce taux est d\'environ 3%. Pour un capital de 100 000€ accumulé, l\'assureur vous versera donc environ 3 000€ par an.' },
    { q: 'En matière de Fiscalité, pourquoi une sortie en "Capital Unique" (retirer tout d\'un coup) est-elle souvent un très mauvais calcul pour un PER dont les versements ont été déduits à l\'entrée ?',
      options: ['Car l\'État confisque la moitié', 'Parce que l\'énorme capital retiré (ex : 80 000 €) va être ajouté brutalement à vos revenus de l\'année, vous propulsant dans les "Tranches" d\'imposition (TMI) très lourdes (30 % ou 41 %)', 'Car cela annule le droit à la retraite de base', 'C\'est interdit par la banque'],
      correct: 1, rationale: 'Le remède classique est la "Sortie en capital fractionné" : on retire l\'argent petit à petit sur plusieurs années (ex: 8000 €/an) pour ne jamais franchir la tranche d\'imposition supérieure.' },
    { q: 'Les "Versements obligatoires de l\'employeur" (Compartiment 3 du PERO) peuvent-ils sortir en Capital ?',
      options: ['Uniquement pour la maison', 'Oui, mais avec une forte amende', 'Oui, comme tous les PER', 'NON. Ce compartiment a pour obligation absolue et stricte de sortir en "Rente Viagère"'],
      correct: 3, rationale: 'L\'entreprise veut s\'assurer que vous aurez un revenu pérenne. Seule exception : si la rente calculée est minime (souvent moins de 110 € / mois), on vous verse le capital en une fois (micro-rente).' },
    { q: '(Challenge) Lors d\'une "Sortie en Rente", comment cette rente est-elle taxée sur le plan de l\'impôt sur le revenu (pour un PER dont les versements ont été déduits) ?',
      options: ['Exonération totale d\'impôts', 'Soumise au régime fiscal des "Pensions et Retraites" classiques : taxée au barème progressif après un abattement forfaitaire de 10 %', 'Taxée à 50 % forfaitairement', 'Soumise aux plus-values immobilières'],
      correct: 1, rationale: 'Le fisc la traite exactement comme votre retraite de la Sécurité sociale.' },
    { q: '(Challenge) Et si l\'épargnant AVAIT RENONCÉ à la déduction fiscale de ses versements pendant sa carrière, comment sa Rente Viagère serait-elle taxée ?',
      options: ['La rente est confisquée', 'L\'impôt est doublé', 'De manière très favorable : soumise au régime de la "Rente Viagère à Titre Onéreux" (RVTO). Seule une FRACTION de la rente est imposable (ex : 40 % si la rente démarre entre 60 et 69 ans), le reste est net d\'impôt', 'Taxée au PFU de 30%'],
      correct: 2, rationale: 'C\'est logique. L\'État ne va pas retaxer lourdement à la sortie des sommes sur lesquelles l\'épargnant a déjà payé l\'impôt à l\'entrée.' },
  ],
  'w21-d3': [
    { q: 'Pour faciliter la transmission d\'entreprises familiales sans ruiner les héritiers avec les droits de succession, quel "Pacte" célèbre le législateur a-t-il mis en place ?',
      options: ['Le Pacte de Varsovie', 'Le Pacte Dutreil', 'Le Pacte de Solidarité', 'Le Pacte Civil'],
      correct: 1, rationale: 'Sans ce pacte, les héritiers seraient souvent obligés de vendre l\'entreprise de leurs parents ou de la vider de sa trésorerie juste pour payer les impôts colossaux du notaire/fisc.' },
    { q: 'Quel est l\'avantage fiscal faramineux offert par le Pacte Dutreil lors d\'une donation ou succession d\'entreprise ?',
      options: ['Une exonération de taxe foncière', 'Il permet d\'annuler les impôts de tous les salariés', 'Le donateur reçoit un chèque de l\'État', 'Un "abattement de 75 %" sur la valeur des titres de l\'entreprise. Les héritiers ne paieront des droits de mutation (impôts) que sur les 25 % restants'],
      correct: 3, rationale: 'Si la PME familiale vaut 4 millions d\'euros, le calcul de l\'impôt ne se fera que sur 1 million. C\'est le Graal de l\'optimisation professionnelle.' },
    { q: 'Pour bénéficier de cet abattement de 75 %, l\'engagement principal (la contrainte) repose sur "la durée de conservation". Que dit la loi ?',
      options: ['Il faut s\'engager (Engagement collectif puis individuel) à conserver les titres de la société pendant une durée totale minimum de 6 ans (2 ans collectif + 4 ans individuel)', 'L\'entreprise doit fermer dans les 5 ans', 'Il faut vendre 50 % des parts à l\'État', 'L\'héritier doit vendre l\'entreprise immédiatement'],
      correct: 0, rationale: 'Le fisc accorde un énorme cadeau, mais en échange, il exige la pérennité de l\'entreprise et la préservation de l\'emploi (interdiction de faire un "coup financier" et de revendre l\'entreprise le lendemain de la donation).' },
    { q: 'Outre la conservation des titres, quelle condition concerne la "Direction" de l\'entreprise (Pacte Dutreil) ?',
      options: ['Un avocat doit être embauché', 'Les bénéfices doivent être redistribués aux associations', 'L\'un des signataires du pacte (le donateur) ou l\'un des héritiers bénéficiaires DOIT exercer la fonction de DIRIGEANT dans la société pendant l\'engagement collectif et les 3 années qui suivent', 'L\'entreprise doit changer de nom'],
      correct: 2, rationale: 'L\'objectif de la loi est la transmission du "pouvoir" et du savoir-faire entrepreneurial, pas juste du patrimoine inerte.' },
    { q: 'Qu\'est-ce qu\'une "Holding Animatrice", souvent au cœur des montages de transmission (Dutreil) ?',
      options: ['Une entreprise agricole', 'Une société qui ne fait qu\'encaisser passivement des loyers', 'Une entreprise étrangère', 'Une société "mère" qui participe activement à la conduite de la politique du groupe et au contrôle de ses filiales (PME). Elle est éligible au Pacte Dutreil, contrairement à la holding purement passive'],
      correct: 3, rationale: 'Les montages patrimoniaux s\'articulent souvent autour d\'une Holding. Mais le fisc est impitoyable : pour bénéficier du Dutreil, la Holding doit prouver son activité "d\'animation" du groupe (marketing, compta, stratégie centralisés).' },
    { q: 'Que se passe-t-il si les héritiers revendent l\'entreprise avant la fin de l\'engagement des 4 années individuelles (rupture du Pacte Dutreil) ?',
      options: ['Remise en cause TOTALE de l\'avantage fiscal. Ils devront payer le complément de droits de succession/donation (les 75% effacés), majorés de lourdes pénalités et intérêts de retard', 'L\'État s\'approprie la vente', 'L\'acheteur doit payer la différence', 'Il y a une petite amende administrative'],
      correct: 0, rationale: 'Le pacte Dutreil est un contrat strict avec le fisc. La moindre erreur (ex: démissionner de la direction trop tôt) détruit le montage.' },
    { q: 'Le patron donateur a deux enfants. L\'un veut reprendre la direction de l\'entreprise, l\'autre ne s\'y intéresse pas du tout et veut du cash. Quel montage est la spécialité des avocats d\'affaires pour ce cas de figure ?',
      options: ['Le "Family Buy Out" (FBO) : l\'enfant repreneur utilise une nouvelle Holding (société) qui va s\'endetter à la banque. Cet argent servira à acheter la part de l\'entreprise due au frère non-repreneur (la "soulte"), tout en profitant du Pacte Dutreil', 'Le pacte de non-agression', 'La liquidation judiciaire', 'Le don aux œuvres de bienfaisance'],
      correct: 0, rationale: 'Le FBO combine le Pacte Dutreil, la donation-partage, et l\'effet de levier du crédit d\'une Holding pour payer "la part" de l\'enfant qui ne veut pas travailler dans la PME familiale.' },
    { q: 'Lors de la transmission de son entreprise (Dutreil), pourquoi le patron a-t-il intérêt à ne donner QUE la "Nue-Propriété" des actions/parts à ses enfants ?',
      options: ['Pour éviter la gestion du personnel', 'Cela lui permet de conserver "l\'Usufruit" (et donc de continuer à toucher les dividendes pour sa retraite), tout en sécurisant la transmission des titres avec l\'abattement Dutreil sur une valeur réduite', 'C\'est interdit par le Pacte Dutreil', 'Pour que la banque paie la TVA'],
      correct: 1, rationale: 'C\'est le beurre et l\'argent du beurre. Le patron transmet sa PME avec le super cadeau du fisc (Dutreil 75%), garde ses revenus, et lors de son décès, le remembrement sera sans impôts.' },
    { q: '(Challenge) Un avantage SUPPLÉMENTAIRE est accordé si le donateur (le patron) donne en Pleine Propriété les parts de son entreprise AVANT d\'atteindre un âge limite. Quel est cet âge et cet avantage ?',
      options: ['Avant 70 ans : l\'impôt (les droits de donation déjà réduits par le Dutreil) bénéficiera ENCORE d\'une réduction de 50 % !', 'Avant 85 ans : suppression de la taxe foncière', 'Avant 50 ans : annulation totale des impôts', 'Avant la naissance du premier enfant'],
      correct: 0, rationale: 'C\'est le "super jackpot" fiscal. Pour inciter les vieux patrons à passer la main avant le déclin cognitif de l\'entreprise, l\'État divise par deux la facture de la donation (s\'ajoutant aux 75% du Dutreil).' },
    { q: '(Challenge) Un patron n\'a pas d\'enfant. Il souhaite donner son entreprise (un fonds de commerce/artisanat) directement à ses SALARIÉS. Un dispositif spécial existe-t-il ?',
      options: ['Non, ils seront taxés à 60% comme des étrangers (Tiers)', 'Oui, la mairie rachète l\'entreprise', 'Oui. En cas de donation d\'entreprise aux salariés (CDI > 2 ans), il existe un abattement spécifique très puissant de 300 000 € sur la valeur des fonds transmis, pour sauver l\'emploi local', 'Les salariés sont obligés de payer le prix fort'],
      correct: 2, rationale: 'Sans ce cadeau fiscal, l\'artisan qui donne son atelier gratuit à son apprenti le verrait condamné à payer 60 % de sa valeur en taxes. Cet abattement rend la transmission "salariée" possible.' },
  ],
  'w21-d4': [
    { q: 'En gestion immobilière locative, qu\'est-ce que la GLI (Garantie Loyers Impayés) ?',
      options: ['Un dépôt de la Caisse d\'Allocations Familiales', 'Le salaire de l\'agent immobilier', 'Une assurance facultative souscrite par le propriétaire bailleur qui le rembourse des loyers si le locataire cesse de payer, et qui prend en charge les frais de procédure', 'Une amende pour le locataire'],
      correct: 2, rationale: 'Les procédures d\'expulsion en France pouvant durer des années sans aucun loyer perçu, la GLI protège l\'investisseur du désastre financier.' },
    { q: 'Quelle est LA condition fondamentale exigée par les assureurs GLI AVANT de garantir un locataire (le "critère de solvabilité") ?',
      options: ['Le locataire doit souvent être en CDI (hors période d\'essai) et justifier d\'un revenu net mensuel fixe d\'au moins "2,7 à 3 fois" le montant du loyer charges comprises', 'Le locataire doit avoir 50 ans', 'Le locataire doit être propriétaire d\'une maison', 'Le locataire doit payer un an d\'avance'],
      correct: 0, rationale: 'L\'assurance ne s\'engage que si le risque initial est très faible. Il est donc très difficile d\'obtenir une GLI pour des locataires en CDD, intérimaires ou freelances (souvent classés "profils atypiques").' },
    { q: 'Une rumeur ou mauvaise habitude prétend qu\'un propriétaire peut demander la Garantie Loyers Impayés (GLI) ET demander en même temps aux parents du locataire de se porter "Cautions Solidaires" (Garant physique). Que dit la loi ?',
      options: ['C\'est parfaitement légal et recommandé pour 2 fois plus de sécurité', 'C\'est obligatoire', 'C\'est STRICTEMENT INTERDIT pour les locations nues ou meublées classiques (la caution physique est alors nulle), SAUF si le locataire a le statut d\'ÉTUDIANT ou d\'apprenti', 'L\'assurance l\'exige'],
      correct: 2, rationale: 'Le législateur interdit le "ceinture et bretelles" pour faciliter l\'accès au logement. Le propriétaire doit choisir : l\'assurance payante (GLI) OU la caution gratuite des parents.' },
    { q: 'Quel est le coût (la prime) généralement constaté pour la souscription d\'une GLI sur le marché ?',
      options: ['Entre 10 et 15 % du loyer', 'Entre 2,5 % et 3 % du montant annuel du loyer charges comprises', '500 € par mois', 'C\'est gratuit et pris en charge par l\'État'],
      correct: 1, rationale: 'Pour un loyer de 600€, l\'assurance coûtera environ 15€ par mois. L\'investisseur doit l\'intégrer dans le calcul de sa rentabilité nette.' },
    { q: 'Quel avantage FISCAL atténue fortement le coût de la prime d\'assurance GLI pour l\'investisseur (en location nue au Régime Réel) ?',
      options: ['Elle est déduite de la taxe foncière', 'Elle annule la TVA', 'La prime payée est intégralement DÉDUCTIBLE des revenus fonciers, venant diminuer le bénéfice et donc baisser l\'impôt sur le revenu du propriétaire', 'Elle donne droit à un abattement de 50 %'],
      correct: 2, rationale: 'En enlevant la prime de ses loyers imposables, le bailleur fortement taxé "récupère" fiscalement une grande partie du coût de l\'assurance.' },
    { q: 'Au-delà du seul remboursement du loyer impayé, la GLI propose souvent la "Protection Juridique / Recours". À quoi sert-elle ?',
      options: ['À embaucher un détective privé', 'À appeler la police pour défoncer la porte', 'Elle prend financièrement en charge la lourde et coûteuse procédure judiciaire pour récupérer la dette et expulser le locataire (frais de commandement, de Commissaire de justice/huissier, avocat de l\'assureur)', 'À obliger le locataire à repeindre la maison'],
      correct: 2, rationale: 'L\'assureur gère l\'expulsion. Une procédure qui coûterait plusieurs milliers d\'euros au bailleur est absorbée par le contrat d\'assurance.' },
    { q: 'Une garantie (souvent optionnelle ou plafonnée) appelée "Détériorations Immobilières" est souvent couplée à la GLI. Que couvre-t-elle ?',
      options: ['L\'usure de la moquette (vétusté)', 'Les dégradations matérielles causées volontairement ou involontairement par le locataire à l\'intérieur du logement, constatées à sa sortie (et dépassant le dépôt de garantie)', 'Les fuites du toit', 'Les tremblements de terre'],
      correct: 1, rationale: 'Si le locataire a détruit la cuisine, l\'assureur couvrira la réparation et le nettoyage à la place du locataire indélicat.' },
    { q: 'Concernant l\'indemnisation de la GLI, qu\'est-ce que le "Délai de Carence" concernant la VACANCE locative ?',
      options: ['La GLI garantit toujours les mois où l\'appartement est vide', 'La GLI classique (hors options rares) ne couvre PAS la "vacance locative" (le fait de ne pas trouver de locataire entre deux baux). L\'indemnisation ne fonctionne qu\'en cas d\'impayé avec un locataire "dans les murs"', 'La GLI paie double en cas de vacance', 'L\'État paie si l\'appartement est vide'],
      correct: 1, rationale: 'L\'assurance ne pallie pas la difficulté commerciale du propriétaire à louer un bien mal placé.' },
    { q: '(Challenge) Lors du premier impayé de loyer, l\'indemnisation par l\'assureur GLI arrive-t-elle sur le compte du propriétaire dès le mois suivant ?',
      options: ['Oui, le jour même', 'Oui, c\'est l\'huissier qui vient avec du liquide', 'Non. La phase de constatation amiable et les délais du contrat font que la première indemnisation tombe souvent 3 à 4 MOIS APRÈS le premier impayé (l\'assureur verse alors rétroactivement les loyers manquants)', 'L\'assureur attend la fin de l\'année'],
      correct: 2, rationale: 'Le propriétaire doit quand même avoir une "épargne de précaution" pour payer le crédit de la banque pendant ces 3 mois de "trou de trésorerie" en attendant que la GLI se déclenche.' },
    { q: '(Challenge) Il existe une alternative 100 % gratuite à la GLI privée, mise en place par l\'État/Action Logement, très utile pour louer à des profils atypiques (CDD, apprentis, moins de 30 ans). Comment s\'appelle-t-elle ?',
      options: ['La Prime CEE', 'La Garantie VISALE', 'Le Chèque Énergie', 'Le Livret Locataire'],
      correct: 1, rationale: 'C\'est Action Logement qui se porte "caution gratuite" pour le locataire, couvrant jusqu\'à 36 mois d\'impayés de loyers. C\'est l\'outil roi pour les propriétaires voulant sécuriser leur location étudiante ou jeune travailleur.' },
  ],
  'w21-d5': [
    { q: 'Comment définit-on juridiquement la Location Courte Durée (souvent qualifiée de "Location saisonnière" ou "Meublé de tourisme") ?',
      options: ['Un bail de 3 ans avec meubles', 'La location d\'un local vide pour un an', 'La location d\'un local à usage professionnel', 'La location d\'un logement meublé, à la nuitée, à la semaine ou au mois, à une clientèle de passage qui n\'y élit PAS Domicile'],
      correct: 3, rationale: 'C\'est la distinction clé. Le client (touriste ou professionnel) a sa résidence principale ailleurs.' },
    { q: 'La réglementation encadrant Airbnb est très stricte. Si le logement loué est la "RÉSIDENCE PRINCIPALE" du propriétaire (il y vit l\'année, mais loue sa chambre lors de ses vacances), quelle limite légale de location s\'applique ?',
      options: ['Il ne peut le louer que 120 jours (4 mois) par an MAXIMUM', 'Il peut le louer toute l\'année s\'il dort dans le canapé', 'C\'est interdit, la résidence principale ne se loue pas', '30 jours par an maximum'],
      correct: 0, rationale: 'Au-delà de ces 120 jours de location courte durée, le bien n\'est plus considéré comme la résidence principale de l\'hôte aux yeux de la loi.' },
    { q: 'Si le logement loué en Airbnb est un simple "investissement locatif" (une résidence secondaire, l\'hôte n\'y habite pas). Que doit faire OBLIGATOIREMENT le propriétaire (dans toutes les communes de France) avant le premier locataire ?',
      options: ['Payer 10 000 € à l\'État', 'Une "Déclaration préalable" en mairie en tant que meublé de tourisme', 'Demander l\'accord des pompiers', 'S\'inscrire à l\'Office du tourisme'],
      correct: 1, rationale: 'Si la déclaration n\'est pas faite, l\'amende peut monter à 5 000 €.' },
    { q: 'Qu\'est-ce que le "Changement d\'Usage", exigé par de plus en plus de grandes villes "tendues" (ex: Paris, Bordeaux, Lyon) pour louer sa résidence secondaire en Airbnb ?',
      options: ['C\'est juste un formulaire sur internet', 'L\'obligation d\'obtenir l\'accord des voisins', 'L\'obligation de changer les serrures', 'L\'autorisation lourde accordée (ou souvent refusée) par la mairie de transformer juridiquement un "local d\'habitation" classique en "local commercial/touristique". C\'est souvent mission impossible'],
      correct: 3, rationale: 'Les mairies utilisent cette arme pour limiter l\'explosion des Airbnb et rendre les logements aux habitants locaux.' },
    { q: 'Qu\'est-ce que la règle de la "Compensation" imposée dans l\'hyper-centre de ces grandes villes pour obtenir ce fameux changement d\'usage ?',
      options: ['La plateforme Airbnb paie la compensation', 'L\'investisseur (qui veut transformer 50m2 d\'habitation en Airbnb) doit OBLIGATOIREMENT acheter 50m2 de locaux commerciaux dans le même quartier et les transformer en habitation pour "compenser" la perte de logement. (Cela coûte extrêmement cher)', 'Payer le double de la taxe d\'habitation', 'Loger un SDF pendant un mois'],
      correct: 1, rationale: 'C\'est ce qui tue techniquement l\'investissement Airbnb classique dans Paris intra-muros pour les petits particuliers.' },
    { q: 'Sur de nombreuses annonces de réservation en ligne (comme Airbnb), un "Numéro d\'enregistrement" à 13 chiffres est obligatoirement affiché. Pourquoi ?',
      options: ['C\'est le numéro de Siret de l\'hôte', 'Il est exigé par certaines communes. La plateforme de réservation a l\'obligation de bloquer automatiquement le calendrier de l\'annonce si l\'hôte dépasse la limite légale des 120 jours, grâce à ce numéro de suivi', 'Pour payer la TVA européenne', 'C\'est le code de la porte'],
      correct: 1, rationale: 'Les villes luttent activement contre les multipropriétaires non déclarés agissant sous les radars.' },
    { q: 'Qui est responsable de la collecte et du versement de la "Taxe de Séjour" due à la commune ?',
      options: ['Le locataire doit l\'envoyer à la mairie', 'L\'État', 'Le propriétaire, MAIS dans 95% des cas, ce sont les plateformes (Airbnb, Booking) qui la collectent directement sur la carte bancaire du voyageur et la reversent automatiquement aux mairies', 'Le syndic de copropriété'],
      correct: 2, rationale: 'Cela a permis de simplifier la vie des hôtes et d\'assurer de colossales rentrées fiscales pour les municipalités touristiques.' },
    { q: 'Avant de lancer son projet Airbnb, le propriétaire a l\'obligation ABSOLUE de vérifier le Règlement de Copropriété de son immeuble. Quel type de clause pourrait ruiner son projet ?',
      options: ['La clause d\'habitation bourgeoise (stricte) : elle interdit la présence d\'activités commerciales et donc formellement la location meublée de tourisme "de passage" dans l\'immeuble', 'La clause de nettoyage de l\'escalier', 'La clause des animaux interdits', 'La clause interdisant les clefs électroniques'],
      correct: 0, rationale: 'Si le règlement de copropriété l\'interdit pour éviter les nuisances sonores des "touristes à valises à roulettes", le syndicat des copropriétaires peut faire cesser votre activité en justice.' },
    { q: '(Challenge) Fiscalement, dans quelle catégorie un petit hôte déclarant ses revenus locatifs de location saisonnière (ex: 10 000 €/an) doit-il les inscrire sur sa déclaration de revenus ?',
      options: ['Revenus Fonciers', 'Revenus exceptionnels', 'BIC (Bénéfices Industriels et Commerciaux), avec la possibilité d\'utiliser le très avantageux régime forfaitaire (Micro-BIC), ou le régime Réel (avec amortissement LMNP)', 'L\'argent est non imposable'],
      correct: 2, rationale: 'Le meublé touristique obéit aux mêmes règles d\'imposition sur le revenu que le LMNP longue durée (bien que les taux d\'abattements du Micro puissent varier).' },
    { q: '(Challenge) Le législateur a récemment durci le volet SOCIAL de la location courte durée. Si l\'activité prend de l\'ampleur et que les recettes annuelles dépassent 23 000 € (et quelques conditions annexes), quelle charge s\'abat sur le loueur ?',
      options: ['La prison', 'Il devient soumis obligatoirement aux cotisations sociales (SSI/URSSAF), ce qui prélève environ 35 à 40 % de ses bénéfices nets pour financer la sécurité sociale', 'Il doit recruter un salarié', 'L\'interdiction d\'utiliser Airbnb'],
      correct: 1, rationale: 'Si vous générez plus de 23 000€ par an en Airbnb, l\'État considère que c\'est une véritable activité économique de parahôtellerie. Ce n\'est plus juste du "patrimoine privé", c\'est une entreprise soumise à charges sociales.' },
  ],
};
