/* Questions de la semaine 18. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w18-d0': [
    { q: 'En finance, comment est traditionnellement perçu l\'or physique ?',
      options: ['Comme un actif générant de forts dividendes annuels', 'Comme l\'investissement privilégié des banques pour créer des crédits', 'Comme une "Valeur refuge" : un actif tangible qui conserve sa valeur en temps de crise ou d\'incertitude', 'Comme une devise officielle acceptée dans les supermarchés européens'],
      correct: 2, rationale: 'Depuis des millénaires, l\'or rassure. Les investisseurs s\'y ruent lorsque les marchés boursiers s\'effondrent ou que la confiance envers la monnaie fiduciaire vacille.' },
    { q: 'Comment le cours de l\'or réagit-il généralement en période de forte inflation (hyperinflation) ?',
      options: ['Il s\'effondre car les banques le revendent', 'Il a tendance à monter (ou à se maintenir), protégeant le pouvoir d\'achat de l\'investisseur', 'Il est divisé par deux par décision de l\'État', 'Il ne bouge jamais, son cours est fixe'],
      correct: 1, rationale: 'Contrairement à la monnaie papier (billets) dont on peut imprimer des milliards d\'exemplaires (créant l\'inflation), l\'or est rare et physique. Il conserve donc sa valeur d\'échange intrinsèque.' },
    { q: 'Quel est le principal DEFAUT mathématique de l\'or physique (lingots, pièces) en termes d\'enrichissement ?',
      options: ['Il ne produit aucun rendement : il ne verse ni intérêt, ni loyer, ni dividende. Le gain ne provient que de la revente plus chère', 'L\'État s\'approprie 50% de la plus-value chaque année', 'Il perd 1% de son poids tous les ans par oxydation', 'Il est interdit à la vente aux particuliers'],
      correct: 0, rationale: 'Un immeuble verse des loyers, une action verse des dividendes. Un lingot d\'or reste un lingot d\'or. Il dort dans un coffre en attendant que son prix monte.' },
    { q: 'Par opposition à l\'or physique, qu\'est-ce que "l\'or papier" ?',
      options: ['Des billets de banque de couleur dorée', 'De fausses pièces d\'or utilisées pour tromper le fisc', 'L\'achat de certificats ou de fonds cotés en bourse (ETC) qui répliquent le cours de l\'or sans que l\'investisseur ne détienne le métal physique', 'Des contrats d\'assurance-vie'],
      correct: 2, rationale: 'L\'or papier permet de profiter de la hausse du cours de l\'or facilement depuis un compte-titres, avec très peu de frais et une liquidité instantanée.' },
    { q: 'Quel est l\'inconvénient logistique majeur de l\'achat d\'or physique ?',
      options: ['Les pièces sont trop lourdes à porter', 'Son stockage et sa sécurisation : il faut payer un coffre à la banque ou assumer un fort risque de vol à domicile', 'Les douanes interdisent de le transporter', 'Il change de couleur avec le temps'],
      correct: 1, rationale: 'C\'est le revers de la médaille de l\'actif tangible. Garder 50 000 € d\'or chez soi sans coffre-fort ni alarme est extrêmement dangereux.' },
    { q: 'Quel est le rôle principal de l\'or dans une stratégie de gestion de portefeuille moderne ?',
      options: ['La pure diversification et la "décorrélation" : il sert de bouclier (assurance) car il a tendance à monter quand les actions s\'effondrent', 'Le rendement mensuel pour la retraite', 'Remplacer totalement le Livret A', 'Financer l\'industrie technologique française'],
      correct: 0, rationale: 'Les experts conseillent souvent d\'avoir 5 à 10% d\'or dans son patrimoine. Si la bourse plonge de 40%, l\'or montera sûrement, amortissant la chute globale.' },
    { q: 'Sur quelle place financière et dans quelle devise le cours de référence mondial de l\'or est-il fixé historiquement ?',
      options: ['À Paris, en euros', 'À Londres (LBMA), en onces et en dollars américains', 'À Tokyo, en Yens', 'À Dubaï, en dirhams'],
      correct: 1, rationale: 'Un investisseur européen supporte donc, en plus du cours de l\'or, un "risque de change" (la variation de la valeur de l\'Euro face au Dollar).' },
    { q: 'En France, quelle est la règle concernant la TVA lors de l\'Achat d\'Or d\'Investissement (lingots, pièces cotées) ?',
      options: ['La TVA est de 20 %', 'Il y a une TVA réduite à 5,5 %', 'L\'Achat d\'Or d\'Investissement est totalement exonéré de TVA', 'La TVA dépend du lieu d\'achat'],
      correct: 2, rationale: 'L\'Europe considère l\'or d\'investissement comme un produit financier, et non comme un bien de consommation classique (à la différence des bijoux).' },
    { q: '(Challenge) Lors de la revente de pièces d\'or d\'investissement, le vendeur a le choix entre deux régimes fiscaux (s\'il possède une preuve d\'achat nominative). Lesquels ?',
      options: ['Il a le choix entre payer la Flat Tax (30%) ou ne rien payer', 'Il a le choix entre la Taxe Forfaitaire sur les Métaux Précieux (11,5 % sur le montant total de la vente) OU l\'Imposition sur la plus-value (36,2 %) avec une décote de 5 % par année de détention', 'Il a le choix entre donner la moitié à l\'État ou à la Mairie', 'Il a le choix entre l\'impôt sur la fortune ou la taxe d\'habitation'],
      correct: 1, rationale: 'C\'est pour cela qu\'il faut TOUJOURS garder les scellés intacts et la facture nominative. Si vous prouvez que vous avez l\'or depuis plus de 22 ans, la taxe sur la plus-value tombe à 0 %.' },
    { q: '(Challenge) Au niveau macro-économique, quel facteur est traditionnellement très DÉFAVORABLE au cours de l\'or ?',
      options: ['La baisse du chômage', 'Une crise géopolitique majeure', 'La forte hausse des taux d\'intérêt RÉELS (rendement des obligations d\'État)', 'L\'impression massive de billets de banque'],
      correct: 2, rationale: 'L\'or ne rapportant aucun intérêt, si la banque centrale propose soudainement 5% garantis et sans risque sur la monnaie, les investisseurs vendront leur or pour placer leur argent sur les comptes rémunérés.' },
  ],
  'w18-d1': [
    { q: 'Quel est l\'avantage fiscal accordé à un particulier qui fait un don en argent à une association d\'intérêt général ou d\'utilité publique ?',
      options: ['Une augmentation de son plafond de découvert', 'Le remboursement de sa taxe foncière', 'Une réduction d\'impôt sur le revenu', 'Le droit de déduire le don de ses contraventions'],
      correct: 2, rationale: 'L\'État encourage la générosité des citoyens en diminuant directement le montant des impôts qu\'ils doivent payer.' },
    { q: 'Pour une association "classique" d\'intérêt général (ex : SPA, Médecins Sans Frontières, recherche médicale), quel est le taux standard de cette réduction d\'impôt ?',
      options: ['10 % du montant du don', '66 % du montant du don', '100 % du montant du don', '33 % du montant du don'],
      correct: 1, rationale: 'Si vous donnez 100 € à une association classique d\'utilité publique, l\'État réduit vos impôts de 66 €. Le don ne vous "coûte" réellement que 34 €.' },
    { q: 'Pour les organismes venant en aide aux personnes en difficulté (repas, soins, logement gratuits - ex : Restos du Cœur, Croix-Rouge), quel est le taux majoré (dit "loi Coluche") ?',
      options: ['90 %', '50 %', '66 %', '75 % du montant du don'],
      correct: 3, rationale: 'L\'État soutient prioritairement l\'urgence sociale. Un don de 100 € aux Restos du Cœur ne vous coûte réellement que 25 € après réduction.' },
    { q: 'Cette superbe réduction de 75 % (Loi Coluche) est-elle illimitée ?',
      options: ['Oui, sans aucune limite', 'Non, elle s\'applique dans la limite d\'un plafond strict fixé par l\'État (autour de 1 000 €/an). La fraction du don qui dépasse ce plafond bénéficie du taux normal de 66 %', 'Non, on ne peut donner qu\'une fois dans sa vie', 'Oui, mais seulement pour les foyers ayant des enfants'],
      correct: 1, rationale: 'Si vous donnez 2 000 € aux Restos du Cœur, les 1 000 premiers euros ouvrent droit à 75 % de réduction (750 €), et les 1 000 suivants ouvrent droit à 66 % (660 €).' },
    { q: 'Quel document strict le contribuable doit-il conserver (pendant 3 ans) pour prouver son don en cas de contrôle de l\'administration fiscale ?',
      options: ['Le chèque barré', 'Le reçu fiscal officiel émis par l\'association (Cerfa n° 11580)', 'Un e-mail de remerciement du président de l\'association', 'Une capture d\'écran du site internet'],
      correct: 1, rationale: 'Seules les associations habilitées par les services fiscaux peuvent délivrer ce reçu. Un simple relevé bancaire ne suffit pas en cas de contrôle.' },
    { q: 'Cette aide est une "Réduction d\'impôt" et NON un "Crédit d\'impôt". Que se passe-t-il si un étudiant qui NE PAIE AUCUN IMPÔT (impôt à zéro) donne 100 € à la Croix-Rouge ?',
      options: ['L\'État lui verse un chèque de 75 € sur son compte en banque', 'L\'avantage financier immédiat est nul (l\'impôt reste à 0). Il ne recevra aucun chèque du fisc', 'L\'étudiant est remboursé par l\'université', 'Le don est refusé par l\'association'],
      correct: 1, rationale: 'Contrairement au crédit d\'impôt (ex: emploi à domicile) qui vous rembourse même si vous n\'êtes pas imposable, la "réduction" ne fait que diminuer un impôt existant.' },
    { q: 'Le bénéfice de cette réduction pour don est-il soumis au terrible "Plafond global des niches fiscales" de 10 000 € par an ?',
      options: ['Oui, il l\'entame directement', 'Oui, mais le plafond passe à 15 000 €', 'Non, les dons aux œuvres échappent TOTALEMENT au plafonnement global des niches fiscales', 'Uniquement pour les cadres dirigeants'],
      correct: 2, rationale: 'L\'État ne veut surtout pas limiter la générosité des philanthropes. On peut donner massivement même si on a déjà saturé ses 10 000 € d\'avantages avec la loi Pinel.' },
    { q: 'Peut-on bénéficier d\'une réduction d\'impôt en donnant des biens matériels (des œuvres d\'art, du matériel informatique, de la nourriture) plutôt que de l\'argent ?',
      options: ['Non, seuls les chèques comptent', 'Oui, les "dons en nature" sont éligibles à la réduction d\'impôt, à condition que le bien soit évalué financièrement à sa juste valeur lors de la remise', 'Uniquement pour les vêtements', 'Oui, mais le taux tombe à 10 %'],
      correct: 1, rationale: 'L\'association émettra un reçu fiscal correspondant à la valeur estimée du bien (ex: 500 € pour des ordinateurs offerts à une école).' },
    { q: '(Challenge) Un donateur hyper-généreux donne 100 000 € à un institut de recherche médicale (taux 66%). Cependant, son impôt total cette année n\'est que de 20 000 €. La loi plafonnant la déduction à 20 % de ses revenus, la réduction calculée ne peut pas être absorbée cette année. Que se passe-t-il ?',
      options: ['Le solde de l\'avantage fiscal est définitivement perdu', 'L\'association doit lui rendre la différence', 'L\'excédent de la réduction d\'impôt non utilisé est reportable et pourra s\'imputer sur ses impôts lors des 5 années suivantes', 'Il est sanctionné pour excès de générosité'],
      correct: 2, rationale: 'L\'État protège les grands dons exceptionnels (legs, successions, grosses ventes) en permettant d\'étaler la défiscalisation sur plusieurs années.' },
    { q: '(Challenge) Sur la déclaration de revenus, les dons faits à un PARTI POLITIQUE ou lors d\'une campagne électorale ouvrent-ils droit au même taux de réduction de 66 % ?',
      options: ['Non, c\'est interdit', 'Oui, ils offrent exactement la même réduction de 66 % (mais avec des plafonds de versements stricts contrôlés par la CNCCFP)', 'Ils offrent un crédit d\'impôt de 100 %', 'Ils annulent la CSG'],
      correct: 1, rationale: 'Le financement de la vie politique est encouragé fiscalement, mais très encadré (ex: 7 500 € par parti politique par an) pour éviter l\'achat d\'influence.' },
  ],
  'w18-d2': [
    { q: 'Qu\'est-ce que l\'ancien PERCO (produit encore détenu par de nombreux Français) ?',
      options: ['Un programme d\'État pour l\'embauche des seniors', 'Le Plan d\'Épargne pour la Retraite Collectif : un dispositif mis en place par l\'entreprise pour aider ses salariés à se constituer une épargne retraite', 'Le Plan d\'Épargne Retraite du Conjoint', 'Un livret d\'épargne réglementé de la Poste'],
      correct: 1, rationale: 'C\'est l\'ancêtre du "PER Collectif" actuel. Des millions de salariés en ont encore un actif dans leur ancienne ou actuelle entreprise.' },
    { q: 'Comment le salarié peut-il alimenter son PERCO de la manière la plus avantageuse (sans sortir d\'argent de son propre compte bancaire) ?',
      options: ['En jouant à la bourse interne', 'En demandant un prêt à la banque', 'En y affectant sa prime d\'intéressement, sa prime de participation, ou la monétisation de ses jours de congés non pris (CET)', 'En détournant les frais professionnels'],
      correct: 2, rationale: 'Si vous touchez la participation sur votre compte, vous payez l\'impôt sur le revenu. Si vous la placez sur le PERCO, elle est totalement exonérée d\'impôt !' },
    { q: 'Quel est le "moteur principal" du PERCO, souvent mis en avant par les Ressources Humaines ?',
      options: ['Le taux garanti par l\'État à 10 %', 'Le droit d\'aller au cinéma', 'L\'Abondement : l\'entreprise peut décider de rajouter de l\'argent de sa poche (souvent un pourcentage, ex: 100% ou 200%) pour chaque euro versé par le salarié', 'La suppression des heures supplémentaires'],
      correct: 2, rationale: 'C\'est de l\'argent "gratuit" offert par le patron pour récompenser l\'effort de préparation à la retraite du salarié.' },
    { q: 'Quelle est la règle principale concernant la disponibilité des sommes bloquées sur le PERCO ?',
      options: ['On peut retirer l\'argent tous les 5 ans', 'Les sommes sont bloquées jusqu\'à l\'âge de départ à la retraite, sauf cas exceptionnels de déblocage anticipé', 'Elles sont disponibles avec un simple coup de fil', 'Elles sont bloquées à vie, même à la retraite'],
      correct: 1, rationale: 'Le but exclusif est la constitution d\'un capital pour les vieux jours.' },
    { q: 'Lequel de ces motifs est un cas de "déblocage anticipé" majeur permettant au salarié de récupérer l\'argent de son PERCO avant la retraite ?',
      options: ['L\'achat d\'une voiture', 'L\'acquisition de sa résidence principale', 'Le financement de l\'école des enfants', 'Le paiement d\'une lourde facture fiscale'],
      correct: 1, rationale: 'C\'est la raison numéro 1 d\'utilisation du PERCO par les jeunes salariés : se constituer un énorme apport immobilier grâce à l\'aide de l\'entreprise.' },
    { q: 'Suite à la grande loi PACTE de 2019, que s\'est-il passé concernant le "PERCO" traditionnel ?',
      options: ['L\'État a confisqué l\'argent', 'Il a été remplacé par le nouveau "PER Collectif". Depuis fin 2020, les entreprises ne peuvent plus ouvrir de nouveaux PERCO, mais les anciens continuent de fonctionner s\'ils ne sont pas transformés', 'Il a été rendu obligatoire pour les chômeurs', 'Il est devenu un compte courant classique'],
      correct: 1, rationale: 'Le but était d\'harmoniser et de simplifier l\'épargne retraite (le vieux PERCO avait de gros défauts de transfert).' },
    { q: 'Arrivé à la retraite, comment l\'employé pouvait-il récupérer l\'argent accumulé sur son vieux PERCO ?',
      options: ['Obligatoirement en rente viagère', 'L\'argent était versé à l\'entreprise', 'Il avait le choix de sortir en capital (en une seule fois) ou en rente viagère', 'Il devait obligatoirement acheter des actions de son entreprise'],
      correct: 2, rationale: 'Contrairement au vieux PERP (bloqué en rente), le PERCO offrait déjà la liberté de prendre son chèque et de partir.' },
    { q: 'En cas de sortie en CAPITAL à la retraite, quelle est la fiscalité ultra-attractive du PERCO (concernant les primes de participation et l\'abondement) ?',
      options: ['Le capital récupéré est totalement exonéré d\'Impôt sur le Revenu. Seules les plus-values (les gains boursiers) subissent les prélèvements sociaux de 17,2 %', 'Le capital est taxé à 30 %', 'On paie 50 % d\'impôts sur l\'abondement', 'La somme est réintégrée au salaire et taxée à la TMI'],
      correct: 0, rationale: 'C\'est une niche fiscale monstrueuse. L\'argent est rentré sans impôt, et il sort sans impôt.' },
    { q: '(Challenge) Un salarié souhaite faire un "Versement Volontaire" (tiré de son propre compte bancaire, sans prime) sur son vieux PERCO. A-t-il droit de déduire cette somme de ses impôts sur le revenu ?',
      options: ['Oui, le PERCO l\'a toujours permis', 'Non ! C\'est la grande différence avec le NOUVEAU PER Collectif. Les versements volontaires sur un vieux PERCO ne sont pas déductibles des impôts à l\'entrée', 'Oui, il déduit 100 % de son revenu', 'Oui, mais seulement si son patron est d\'accord'],
      correct: 1, rationale: 'C\'est la raison principale pour laquelle il faut absolument demander à son entreprise de transformer son vieux PERCO en nouveau "PER Collectif".' },
    { q: '(Challenge) Un salarié quitte une entreprise A (où il avait un vieux PERCO) pour rejoindre une entreprise B. Que peut-il faire de son vieux PERCO ?',
      options: ['Il est obligé de le clôturer et de payer une amende', 'Il le perd', 'Il a le droit de le transférer vers le PER Collectif de sa nouvelle entreprise B (ou vers son PER Individuel personnel) pour tout regrouper', 'L\'entreprise A garde la moitié de la somme'],
      correct: 2, rationale: 'La loi encourage le regroupement pour éviter les comptes "dortoirs" abandonnés et facturés par les banques.' },
  ],
  'w18-d3': [
    { q: 'Quelle est la règle ABSOLUE de forme exigée par le Code Civil pour faire la donation d\'une maison ou d\'un appartement de son vivant ?',
      options: ['Une simple lettre signée des deux parties', 'Un transfert de l\'acte de propriété par la poste', 'La déclaration verbale devant le maire', 'L\'acte doit obligatoirement être passé devant un notaire (Acte Authentique) sous peine de nullité absolue'],
      correct: 3, rationale: 'Pour l\'immobilier, impossible de faire un "don manuel" sous le manteau. Le notaire assure la sécurité juridique et la publication au service de la publicité foncière (ex-hypothèques).' },
    { q: 'Un père donne un appartement à sa fille. Quel est le montant de l\'abattement fiscal (franchise d\'impôt) dont ils bénéficient pour cette opération ?',
      options: ['100 000 € (par parent et par enfant)', '31 865 €', '500 000 €', 'L\'immobilier n\'a aucun abattement'],
      correct: 0, rationale: 'Si la maison vaut 150 000 €, la fille ne paiera les droits de donation (au barème progressif) que sur la part excédentaire, soit 50 000 €.' },
    { q: 'Quelle est la technique patrimoniale reine pour transmettre sa maison de son vivant tout en conservant la certitude de ne jamais être mis à la porte ?',
      options: ['La donation avec clause de retour', 'La tontine', 'La vente viagère à un inconnu', 'La donation avec réserve d\'usufruit : le parent donne la Nue-Propriété à l\'enfant, mais garde l\'Usufruit (le droit d\'y habiter ou de louer jusqu\'à sa mort)'],
      correct: 3, rationale: 'Le parent se dépouille de la propriété des murs, mais conserve le pouvoir total sur l\'utilisation du bien, sécurisant sa vieillesse.' },
    { q: 'Quel est l\'immense intérêt FISCAL de donner en démembrement (nue-propriété) plutôt qu\'en pleine propriété ?',
      options: ['La mairie ne perçoit plus la taxe foncière', 'Les droits de donation sont calculés UNIQUEMENT sur la valeur de la nue-propriété (selon un barème lié à l\'âge du parent), et non sur la valeur totale du bien. Cela réduit massivement les impôts', 'Les impôts sont reportés à 50 ans', 'Les droits de donation sont totalement annulés'],
      correct: 1, rationale: 'Si un parent de 65 ans donne un appartement de 200 000€. L\'usufruit vaut 40%, la nue-propriété vaut 60%. L\'enfant ne sera taxé que sur la base de 120 000€.' },
    { q: 'Que se passe-t-il pour l\'enfant (le nu-propriétaire) au DÉCÈS de son parent usufruitier ?',
      options: ['L\'enfant devient Plein Propriétaire sans avoir aucun droit de succession (impôt) supplémentaire à payer sur ce bien', 'L\'enfant doit racheter l\'usufruit à l\'État', 'La maison doit être vendue', 'L\'enfant paie 20 % de la valeur de la maison'],
      correct: 0, rationale: 'L\'usufruit s\'éteint avec la mort. Le démembrement se termine et la famille échappe totalement à l\'impôt de transmission au moment du décès.' },
    { q: 'Si un parent donne la nue-propriété de sa maison à son fils, peuvent-ils décider de VENDRE la maison quelques années plus tard ?',
      options: ['Oui, le parent décide seul', 'Oui, l\'enfant décide seul', 'Non, la vente est interdite jusqu\'au décès', 'Oui, mais il faut obligatoirement l\'accord conjoint (unanimité) de l\'usufruitier ET du nu-propriétaire. Ils se partageront ensuite l\'argent de la vente selon la valeur de leurs droits'],
      correct: 3, rationale: 'Donner la nue-propriété signifie perdre le droit de vendre seul son bien (l\'abusus appartient à l\'enfant).' },
    { q: 'Lors d\'une donation immobilière, il faut payer des "frais de notaire" (taxes, droits d\'enregistrement, émoluments). Qui doit les payer selon la loi ?',
      options: ['La mairie', 'L\'assurance', 'Le donataire (celui qui reçoit le don), mais le donateur (le parent) peut tout à fait décider de les prendre à sa charge sans que ce soit considéré comme une donation supplémentaire', 'La banque'],
      correct: 2, rationale: 'C\'est une grande faveur de l\'administration. Le parent paie les impôts pour son enfant, et ce cadeau n\'est pas taxé comme un don supplémentaire.' },
    { q: 'Qu\'est-ce que le danger du "Rapport à la succession" si un père a fait une "Donation SIMPLE" (non-partage) d\'un appartement de 100 000 € à son fils unique, et qu\'au décès 20 ans plus tard, l\'appartement vaut 400 000 € ?',
      options: ['L\'appartement est vendu aux enchères', 'Le fils n\'a aucun problème car il est enfant unique', 'Lors du calcul du patrimoine pour les impôts de succession, l\'appartement sera réévalué (rapporté) à sa valeur AU JOUR DU DÉCÈS (400 000 €), ce qui gonflera fictivement l\'héritage et l\'impôt final', 'L\'État saisit la plus-value'],
      correct: 2, rationale: 'C\'est la mécanique civile. L\'avance sur héritage est recalculée le jour de la mort pour s\'assurer que personne n\'est lésé et que le fisc prend sa part.' },
    { q: '(Challenge) Pour éviter les conflits si le parent a DEUX enfants et transmet une maison, pourquoi est-il vivement conseillé d\'utiliser la forme de la "Donation-partage" plutôt que la "Donation simple" ?',
      options: ['Elle est totalement gratuite', 'La donation-partage permet de "figer" (cristalliser) définitivement la valeur des lots au jour de l\'acte. Si la maison de l\'un prend de la valeur, l\'autre enfant ne pourra rien lui réclamer au jour du décès', 'Elle permet d\'annuler les impôts de l\'enfant', 'Elle exclut un enfant'],
      correct: 1, rationale: 'C\'est l\'assurance-paix des familles. Il n\'y aura aucun compte à rendre entre frères et sœurs lors de l\'ouverture du testament ou de la succession.' },
    { q: '(Challenge) Un parent donne un appartement locatif à son fils, mais intègre une clause de "Droit de retour conventionnel". Quel est l\'effet de cette clause ?',
      options: ['Le parent peut reprendre le bien quand il veut', 'Le fils est obligé de louer le bien à ses parents', 'Si l\'enfant (donataire) décède AVANT le parent (donateur), l\'appartement retourne automatiquement dans le patrimoine du parent, échappant ainsi aux droits de succession et à la belle-famille', 'L\'appartement est saisi par la banque'],
      correct: 2, rationale: 'C\'est une clause de prévoyance magistrale. Aucun parent ne souhaite que le bien donné à sa fille finisse dans les mains de son gendre (ou de ses frères) si la fille meurt tragiquement la première.' },
  ],
  'w18-d4': [
    { q: 'Dans un contrat de Prévoyance, quel est le but principal de la "Garantie Décès" ?',
      options: ['Financer les obsèques (le cercueil)', 'Verser un capital ou une rente aux bénéficiaires désignés, afin de compenser la perte de revenus brutale et protéger financièrement la famille suite au décès prématuré de l\'assuré', 'Rembourser uniquement le prêt immobilier', 'Remplacer l\'assurance-vie'],
      correct: 1, rationale: 'Si le pilier financier de la famille disparaît, ce contrat permet au conjoint de payer le loyer, la nourriture et de ne pas sombrer dans la misère.' },
    { q: 'Quelle est la différence majeure de fonctionnement entre une "Assurance-Vie" classique (placement) et une "Assurance Décès" (prévoyance) ?',
      options: ['Il n\'y a aucune différence, c\'est le même contrat', 'L\'assurance-vie est un compte d\'épargne. L\'assurance décès est "à fonds perdus" (comme une assurance auto) : vous payez pour vous couvrir d\'un risque. Si vous ne décédez pas pendant le contrat, les cotisations sont conservées par l\'assureur', 'L\'assurance décès est pour l\'employeur', 'L\'assurance-vie rembourse la Sécurité sociale'],
      correct: 1, rationale: 'C\'est pour cela qu\'une assurance décès pour un homme jeune coûte très peu cher (quelques dizaines d\'euros pour garantir 100 000 €).' },
    { q: 'Dans de nombreux contrats de prévoyance d\'entreprise, la garantie décès inclut le versement d\'une "Rente de Conjoint". Qu\'est-ce que c\'est ?',
      options: ['Un abonnement de cinéma pour le conjoint', 'Une somme versée à la banque', 'Un revenu mensuel ou trimestriel versé au conjoint survivant, généralement jusqu\'à ce qu\'il atteigne lui-même l\'âge de la retraite (pour pallier l\'absence de réversion avant 55 ans)', 'Le remboursement des frais médicaux'],
      correct: 2, rationale: 'C\'est extrêmement protecteur, surtout si le conjoint ne travaille pas ou a de faibles revenus.' },
    { q: 'Qu\'est-ce que la "Rente Éducation" souvent proposée en complément de la garantie décès ?',
      options: ['Le remboursement des fournitures scolaires', 'Une rente périodique versée aux enfants du défunt, conçue pour financer leur vie et leurs études (souvent versée jusqu\'à leur 18 ans, ou 25 ans s\'ils font des études supérieures)', 'Une aide pour les professeurs', 'Une taxe sur l\'école'],
      correct: 1, rationale: 'Cela garantit au parent que, quoiqu\'il arrive, ses enfants auront les moyens financiers de poursuivre de longues études.' },
    { q: 'À la souscription d\'une assurance décès individuelle (capital important), que demande quasi-systématiquement l\'assureur pour accepter le risque ?',
      options: ['Le bulletin de notes des enfants', 'Le permis de conduire', 'Le remplissage précis d\'un questionnaire médical (et souvent un examen de santé avec prise de sang) pour vérifier que l\'assuré n\'a pas déjà une maladie grave mortelle', 'Le relevé d\'imposition'],
      correct: 2, rationale: 'L\'assureur vérifie le risque. S\'il y a un risque lourd, il appliquera une surprime ou refusera d\'assurer (exclusion).' },
    { q: 'Que se passe-t-il juridiquement en cas de suicide de l\'assuré dans les contrats de prévoyance décès ?',
      options: ['L\'assurance double le capital', 'Il est généralement exclu de la garantie durant la PREMIÈRE ANNÉE de couverture. Passé ce délai de 1 an, le décès par suicide est pris en charge et le capital est versé', 'Il n\'est jamais couvert, c\'est formellement interdit', 'Le contrat est transmis aux enfants'],
      correct: 1, rationale: 'Cette règle vise à éviter l\'effet d\'aubaine (une personne désespérée qui s\'assure juste avant de passer à l\'acte pour enrichir sa famille).' },
    { q: 'Qui sont les bénéficiaires du capital d\'une assurance décès ?',
      options: ['Exclusivement la Sécurité Sociale', 'Uniquement les enfants mineurs', 'Les personnes expressément désignées par le souscripteur dans la "clause bénéficiaire" (conjoint, enfants, ami, association), qui doit être rédigée avec un très grand soin', 'Obligatoirement l\'employeur'],
      correct: 2, rationale: 'Comme pour l\'assurance-vie, si la clause est vide, le capital tombe dans la succession normale avec tous ses inconvénients (et impôts).' },
    { q: 'En entreprise, les employeurs ont l\'OBLIGATION de cotiser à un contrat de prévoyance décès (souvent appelé le "1,50% Tranche A"). Mais pour quelle catégorie stricte de salariés ?',
      options: ['Les apprentis', 'Les cadres (loi issue de l\'accord de 1947). Si l\'employeur oublie de souscrire, il devra payer lui-même une sanction colossale (3 fois le plafond de la Sécu) à la famille en cas de décès', 'Les travailleurs de nuit', 'Les salariés au SMIC'],
      correct: 1, rationale: 'Cette disposition historique de 1947 oblige les entreprises à assurer un capital décès lourd pour leurs salariés cadres.' },
    { q: '(Challenge) Une option très fréquente dans la prévoyance individuelle est le "Doublement du capital en cas d\'accident". Qu\'est-ce que cela signifie ?',
      options: ['Si l\'assuré meurt dans l\'année de signature, le capital double', 'Si le décès est la conséquence directe d\'un accident soudain (ex : crash de voiture, chute) et non d\'une maladie (ex : cancer, arrêt cardiaque), l\'assureur versera 200 000 € au lieu des 100 000 € prévus pour la maladie', 'L\'assureur double la mensualité', 'Les impôts sont doublés'],
      correct: 1, rationale: 'Un décès accidentel, souvent très jeune, ne laisse pas le temps à la famille de s\'organiser financièrement, d\'où ce doublement.' },
    { q: '(Challenge) Fiscalement, le capital décès versé aux proches via le contrat Prévoyance d\'ENTREPRISE (financé par l\'employeur) est-il soumis aux redoutables Droits de succession ?',
      options: ['Il est taxé à 100 %', 'Il est réintégré au salaire', 'Non. Il est hors succession. Il peut toutefois subir, comme l\'assurance-vie, un prélèvement forfaitaire de 20 % (article 990 I) sur la dernière prime annuelle versée (très faible impact)', 'La mairie perçoit une taxe'],
      correct: 2, rationale: 'Le capital décès d\'une prévoyance groupe est une pure transmission de richesse "net d\'impôts" vers la famille éplorée.' },
  ],
  'w18-d5': [
    { q: 'En investissement immobilier locatif, qu\'est-ce que le "Cash-Flow" (flux de trésorerie) ?',
      options: ['La différence entre le prix d\'achat et le prix de revente', 'L\'argent de poche donné par l\'agent immobilier', 'L\'eau consommée par le locataire', 'La différence réelle, calculée mensuellement ou annuellement, entre les ENTRÉES d\'argent (les loyers perçus) et les SORTIES d\'argent (mensualité de crédit, charges, taxes, travaux)'],
      correct: 3, rationale: 'C\'est le juge de paix. Il détermine si l\'appartement remplit vos poches ou les vide chaque mois.' },
    { q: 'Que signifie avoir un "Cash-flow positif" ?',
      options: ['Les loyers encaissés sont SUPÉRIEURS à toutes les dépenses cumulées. L\'investissement s\'autofinance totalement et dégage même un bénéfice (un excédent) chaque mois sur le compte du propriétaire', 'Le locataire est gentil', 'La banque refuse de prêter de l\'argent', 'Le bien nécessite des travaux urgents'],
      correct: 0, rationale: 'C\'est le Saint Graal de l\'investisseur. La maison se paie toute seule et vous enrichit financièrement en temps réel.' },
    { q: 'À l\'inverse, qu\'est-ce qu\'un "Cash-flow négatif" (ou effort d\'épargne) ?',
      options: ['Les loyers NE SUFFISENT PAS à couvrir la mensualité de crédit et les charges. Le propriétaire doit donc injecter de sa poche une certaine somme (ex: 200 €) tous les mois pour maintenir l\'investissement à flot', 'La maison perd de sa valeur', 'Le locataire refuse de payer le loyer', 'Les taux d\'intérêts tombent à zéro'],
      correct: 0, rationale: 'Ce n\'est pas forcément mauvais (on capitalise sur un beau patrimoine avec un effort forcé), mais cela limite la capacité d\'endettement future.' },
    { q: 'Pourquoi de nombreux débutants croient-ils, à tort, avoir un cash-flow positif sur le papier ?',
      options: ['Ils oublient que le locataire peut peindre les murs', 'Ils regardent uniquement la différence "Loyer - Mensualité de crédit", oubliant totalement d\'inclure les charges cachées lourdes : la taxe foncière, les frais de copropriété, les impôts sur le revenu, et la vacance locative', 'Ils se fient aux astrologues', 'Ils ne savent pas utiliser de calculatrice'],
      correct: 1, rationale: '700€ de loyer pour 500€ de crédit = +200€ virtuels. Mais si on ajoute 150€ d\'impôts, 80€ de foncier et 50€ de charges... le vrai cash-flow est de -80€/mois !' },
    { q: 'Quel paramètre bancaire lors de l\'achat peut augmenter MASSIVEMENT votre Cash-flow mensuel ?',
      options: ['Rallonger au maximum la DURÉE de l\'emprunt (ex : 25 ans au lieu de 15 ans). Cela baisse mécaniquement le montant de la mensualité, ce qui laisse respirer la trésorerie (même si ça coûte plus cher en intérêts au final)', 'Emprunter à taux variable', 'Emprunter sur 5 ans', 'Refuser l\'assurance de prêt'],
      correct: 0, rationale: 'Pour l\'investisseur focalisé sur le cash-flow, l\'obsession est d\'écraser la sortie d\'argent mensuelle.' },
    { q: 'La fiscalité a-t-elle un rôle majeur dans le Cash-flow ?',
      options: ['Oui. L\'impôt et la CSG (17,2 %) à payer sur les revenus locatifs peuvent détruire totalement la rentabilité mensuelle. D\'où l\'importance vitale du statut LMNP ou du Déficit Foncier pour effacer la fiscalité', 'Oui, elle augmente les loyers', 'Non, l\'immobilier n\'est pas taxé', 'Non, le locataire paie l\'impôt'],
      correct: 0, rationale: 'Gagner 200€ de cash-flow brut, mais devoir sortir 2000€ d\'impôt foncier à l\'automne, plonge l\'opération dans le rouge foncé.' },
    { q: 'Quel type de bien immobilier (souvent boudé par le grand public) est historiquement prisé des investisseurs pour dégager de gros Cash-flows positifs ?',
      options: ['La chambre de bonne à Paris', 'Le château historique', 'L\'Immeuble de Rapport (acheter un petit immeuble entier en province avec 4 ou 5 appartements). Pas de syndic, prix de gros, forte rentabilité', 'L\'appartement neuf en loi Pinel'],
      correct: 2, rationale: 'Acheter "en gros" permet de négocier le prix du mètre carré. De plus, détenir les murs entiers supprime les coûteuses charges de copropriété.' },
    { q: 'Faut-il toujours, en toutes circonstances, fuir un "Cash-flow négatif" (effort d\'épargne) ?',
      options: ['Oui, c\'est le signe d\'une arnaque', 'Non. Un bel appartement Haussmannien à Paris aura un très fort cash-flow négatif (loyers faibles vs prix d\'achat énorme), mais il garantit un placement ultra-sécurisé, pérenne, et une grosse plus-value à la revente. C\'est un placement "Patrimonial"', 'Seulement le dimanche', 'Oui, car la banque le saisira'],
      correct: 1, rationale: 'C\'est le trilemme financier. On sacrifie le cash-flow immédiat pour obtenir une sécurité et une plus-value majestueuse sur le long terme.' },
    { q: '(Challenge) À l\'inverse, quel est le danger majeur de cibler une stratégie EXCLUSIVEMENT basée sur des "Méga-rentabilités" et un énorme Cash-flow positif (+300 € / mois sur un studio) ?',
      options: ['Le gouvernement confisque le bien', 'Les banques refusent de voir les investisseurs s\'enrichir', 'Il faut payer la taxe d\'habitation', 'Ces biens se trouvent obligatoirement dans des villes économiquement sinistrées ou des quartiers difficiles. Le risque d\'impayés, de squats, de vacances locatives et de très lourde moins-value à la revente est colossal'],
      correct: 3, rationale: 'Le haut rendement rémunère le haut risque. Un cash-flow sur le papier (Excel) ne vaut rien si le locataire arrête de payer le loyer.' },
    { q: '(Challenge) Un investisseur gagne 1 000 € de loyer mensuel et rembourse 700 € de mensualité. Quel autre levier bancaire (souvent demandé au démarrage du projet) permet d\'exploser le Cash-flow positif pendant les 2 premières années ?',
      options: ['Demander un "Différé d\'amortissement" au banquier. On encaisse les 1 000 € de loyers, mais on ne rembourse que l\'assurance et les intérêts (ex: 150 €) le temps de faire les travaux, dégageant une trésorerie massive', 'Annuler le crédit', 'Faire un crédit revolving', 'Payer la totalité au comptant'],
      correct: 0, rationale: 'Cette technique permet de se constituer un lourd matelas de trésorerie (la fameuse épargne de sécurité immobilière) grâce aux locataires, avant que la pleine mensualité (capital + intérêts) ne tombe.' },
  ],
};
