/* Questions de la semaine 15. Chargé à la demande par loadWeekQuestions()
   (src/pages/Academy/weeks.js) : les 26 semaines pèsent ensemble ~950 Ko,
   soit dix fois le reste de la page. */
export default {
  'w15-d0': [
    { q: 'En finance, qu\'est-ce qu\'une "obligation" ?',
      options: ['Une action d\'entreprise qui verse un dividende garanti', 'Une taxe prélevée par l\'État sur les bénéfices boursiers', 'Un titre de créance représentant une part d\'un emprunt : l\'investisseur prête de l\'argent à l\'émetteur en échange d\'un taux d\'intérêt', 'L\'obligation de conserver ses titres pendant 5 ans'],
      correct: 2, rationale: 'Contrairement à l\'actionnaire qui devient propriétaire, l\'obligataire devient le banquier (le créancier) d\'un État ou d\'une entreprise.' },
    { q: 'Comment s\'appelle la rémunération périodique (les intérêts) versée à l\'investisseur qui détient une obligation ?',
      options: ['Le coupon', 'Le dividende', 'La prime d\'émission', 'La plus-value'],
      correct: 0, rationale: 'Ce terme historique vient de l\'époque où les obligations étaient des documents papier : les investisseurs découpaient littéralement un "coupon" en bas de la page pour aller l\'échanger contre leurs intérêts à la banque.' },
    { q: 'Une entreprise fait faillite. Que se passe-t-il lors de la liquidation ?',
      options: ['Les actionnaires sont remboursés avant les obligataires', 'L\'État rembourse tout le monde', 'Personne n\'est jamais remboursé', 'Les obligataires (créanciers) sont remboursés en priorité AVANT les actionnaires'],
      correct: 3, rationale: 'L\'obligation est donc un investissement théoriquement moins risqué que l\'action, car la dette passe avant le capital en cas de liquidation.' },
    { q: 'Quel est le principal risque lié à l\'achat d\'une obligation (hors variation des taux) ?',
      options: ['Le risque de surperformance', 'Le risque de défaut (ou risque de crédit) : l\'émetteur fait faillite et ne peut plus rembourser le capital ni payer les coupons', 'Le risque d\'illiquidité', 'Le risque de nationalisation'],
      correct: 1, rationale: 'Si vous prêtez de l\'argent à un État en faillite ou une entreprise très fragile, vous risquez de ne jamais revoir votre capital.' },
    { q: 'Qu\'est-ce que la "maturité" d\'une obligation ?',
      options: ['Le moment où elle rapporte le plus d\'argent', 'La durée de vie de l\'emprunt (la date à laquelle l\'émetteur s\'engage à rembourser le capital initial à l\'investisseur)', 'Le taux d\'imposition du coupon', 'L\'âge minimum pour l\'acheter'],
      correct: 1, rationale: 'Une obligation à 10 ans vous paiera des coupons pendant 10 ans, puis vous rendra votre mise de départ à la fin de la 10ème année.' },
    { q: 'Comment appelle-t-on les obligations émises par l\'État français pour financer sa dette ?',
      options: ['Les SICAV', 'Les ETF France', 'Les OAT (Obligations Assimilables du Trésor)', 'Les Bons de Souscription'],
      correct: 2, rationale: 'C\'est le socle de l\'épargne sécurisée en France. Les OAT composent la majorité des fonds en euros de vos assurances-vie.' },
    { q: 'Que sont les obligations "High Yield" (à Haut Rendement) ?',
      options: ['Des obligations sans aucun risque', 'Des obligations émises par des États ultra-solides (comme l\'Allemagne)', 'Des obligations émises par des banques centrales', 'Des obligations émises par des entreprises fragiles (ou très endettées), qui offrent un taux d\'intérêt très élevé pour compenser leur fort risque de défaut'],
      correct: 3, rationale: 'On les appelle aussi "Junk bonds" (obligations pourries). Le haut rendement vient rémunérer une prise de risque importante.' },
    { q: 'Il existe une règle mathématique absolue concernant le cours (le prix de revente) d\'une obligation déjà émise sur le marché secondaire. Laquelle ?',
      options: ['Si les taux d\'intérêt des Banques Centrales MONTENT, le prix de revente de votre ancienne obligation BAISSE', 'Si les taux d\'intérêt montent, le prix de l\'obligation monte', 'Le prix de revente est toujours garanti et bloqué à 100 %', 'L\'inflation annule la valeur de l\'obligation'],
      correct: 0, rationale: 'C\'est le risque de taux. Si vous avez une obligation qui rapporte 2% et que les nouveaux taux montent à 4%, personne ne voudra vous racheter votre vieille obligation à 2%, sauf si vous baissez son prix de vente.' },
    { q: '(Challenge) Qui évalue la solidité financière (le risque de défaut) des États et des entreprises émettant des obligations ?',
      options: ['Les agences de notation financière (comme Standard & Poor\'s, Moody\'s, Fitch) qui attribuent des notes allant de AAA (ultra sûr) à D (en défaut)', 'L\'Union Européenne', 'L\'Autorité des Marchés Financiers (AMF)', 'Le Fonds Monétaire International (FMI)'],
      correct: 0, rationale: 'Plus la note est mauvaise, plus l\'émetteur devra promettre un coupon élevé pour réussir à emprunter de l\'argent sur les marchés.' },
    { q: '(Challenge) Qu\'est-ce qu\'une obligation "Verte" (Green Bond) ?',
      options: ['Une obligation réservée au secteur de l\'agriculture', 'Une obligation sans aucun impôt', 'Une obligation classique dont les fonds levés s\'engagent à financer exclusivement des projets ayant un impact environnemental positif (énergies renouvelables, efficacité énergétique)', 'Une obligation émise par les partis politiques écologistes'],
      correct: 2, rationale: 'Le fonctionnement financier est identique à une obligation classique, c\'est uniquement la destination stricte des fonds qui la rend "verte".' },
  ],
  'w15-d1': [
    { q: 'Quel est l\'avantage fiscal du Plan d\'Épargne en Actions (PEA) si vous effectuez un retrait (rachat) APRÈS le 5ème anniversaire de son ouverture ?',
      options: ['Une réduction de la taxe foncière', 'Les plus-values et dividendes générés à l\'intérieur du plan sont totalement EXONÉRÉS d\'Impôt sur le Revenu', 'Les prélèvements sociaux sont annulés', 'Le capital est doublé par l\'État'],
      correct: 1, rationale: 'C\'est ce qui en fait l\'enveloppe boursière la plus puissante en France. L\'impôt de 12,8% disparaît totalement.' },
    { q: 'Même après 5 ans, et malgré l\'exonération d\'Impôt sur le Revenu, quelle taxe reste obligatoirement due sur vos gains lors d\'un retrait du PEA ?',
      options: ['L\'Impôt sur la Fortune', 'La Taxe sur la Valeur Ajoutée (TVA)', 'Les Prélèvements Sociaux (actuellement 17,2 %)', 'La taxe sur les transactions boursières'],
      correct: 2, rationale: 'Il n\'y a pas d\'échappatoire à la Sécurité Sociale (CSG/CRDS). L\'imposition globale passe donc de 30 % (PFU) à 17,2 % après 5 ans.' },
    { q: 'Quelle est la conséquence fiscale et bancaire d\'un retrait (même partiel) effectué AVANT les 5 ans du PEA (hors cas exceptionnels prévus par la loi) ?',
      options: ['Le retrait provoque la clôture immédiate et définitive du PEA, et les gains sont taxés au PFU (Flat Tax de 30 %)', 'Il y a une simple pénalité de 50 €', 'Le retrait est bloqué par la banque', 'L\'argent retiré est taxé à 50 %'],
      correct: 0, rationale: 'Retirer trop tôt casse l\'engagement de fidélité. Le PEA est détruit et vous êtes imposé comme sur un compte-titres normal.' },
    { q: 'Vous possédez des actions sur votre PEA qui versent des dividendes. Tant que vous NE RETIREZ PAS cet argent du PEA (l\'argent reste sur le compte espèces du PEA), comment sont taxés ces dividendes ?',
      options: ['Ils sont taxés à 30 % chaque année', 'Ils subissent uniquement les prélèvements sociaux de 17,2 %', 'Ils sont taxés à votre TMI', 'Ils ne subissent absolument AUCUNE taxation. Ils capitalisent "en franchise d\'impôt" à l\'intérieur de l\'enveloppe'],
      correct: 3, rationale: 'C\'est la force des intérêts composés. Le dividende brut vous sert à racheter d\'autres actions sans subir le "frottement fiscal" annuel.' },
    { q: 'Il existe des exceptions permettant de faire un retrait sur son PEA AVANT 5 ans SANS clôturer le plan. Laquelle de ces situations est un motif valable selon la loi PACTE ?',
      options: ['L\'achat de sa résidence principale', 'Le paiement des impôts annuels', 'Le licenciement, l\'invalidité ou la mise à la retraite anticipée de vous-même ou de votre conjoint', 'Le mariage'],
      correct: 2, rationale: 'La loi protège les épargnants victimes d\'un coup dur. Dans ce cas, le plan reste ouvert et les gains sont même exonérés d\'IR.' },
    { q: 'Depuis la loi PACTE (2019), que se passe-t-il si vous faites un retrait partiel APRÈS les 5 ans de votre PEA ?',
      options: ['Le plan est clôturé', 'Le plan reste ouvert, l\'avantage fiscal est conservé pour les fonds restants, ET vous pouvez même continuer à faire de NOUVEAUX versements par la suite', 'Le plan reste ouvert mais les nouveaux versements sont interdits', 'Le taux d\'imposition remonte à 30 %'],
      correct: 1, rationale: 'Avant 2019, tout retrait après 8 ans bloquait les versements. Aujourd\'hui, le PEA de plus de 5 ans est une enveloppe extrêmement souple et liquide.' },
    { q: 'Lors d\'un retrait partiel sur le PEA, l\'impôt/les taxes s\'appliquent-ils sur la totalité de la somme retirée ?',
      options: ['Non, comme pour l\'assurance-vie, l\'imposition (les prélèvements sociaux) ne frappe QUE la part de GAIN (plus-value/dividende) contenue dans le retrait. La part de capital n\'est jamais taxée', 'Oui, sur les 100 % retirés', 'Uniquement sur les dividendes, pas sur les plus-values', 'La banque choisit le montant taxable'],
      correct: 0, rationale: 'Le fisc utilise une règle de proportionnalité. On ne taxe jamais l\'argent que vous avez vous-même apporté.' },
    { q: 'Que se passe-t-il si, après 5 ans, vous clôturez votre PEA en étant "en moins-value" globale (vous avez perdu de l\'argent par rapport à vos versements) ?',
      options: ['L\'État vous rembourse 17,2 % de la perte', 'La banque annule ses frais de gestion', 'La perte est ignorée fiscalement', 'Cette perte définitive est considérée comme une moins-value boursière et peut être déduite de vos autres plus-values réalisées sur un Compte-Titres (CTO) pendant les 10 années suivantes'],
      correct: 3, rationale: 'Consolation fiscale : la perte d\'un PEA peut servir de bouclier fiscal pour vos autres investissements non défiscalisés.' },
    { q: '(Challenge) Lors de la clôture d\'un très vieux PEA de 20 ans, comment l\'administration calcule-t-elle les prélèvements sociaux (17,2 % aujourd\'hui) sur les gains réalisés les premières années du contrat ?',
      options: ['Au taux de 0 % pour les 10 premières années', 'Au taux de 30 %', 'Grâce au mécanisme des "Taux historiques" : les gains réalisés avant 2018 restent taxés au taux de prélèvements sociaux en vigueur à l\'époque où ils ont été constatés (souvent plus bas, ex: 15,5 % ou 12,1 %)', 'Tout est taxé à 17,2 % par simplification'],
      correct: 2, rationale: 'Bien que la règle générale soit passée au taux en vigueur au jour du retrait (17,2%), les PEA ouverts avant 2018 bénéficient d\'une "cristallisation" des anciens taux plus favorables pour les gains passés.' },
    { q: '(Challenge) Vous détenez des actions "NON COTÉES" (start-up) au sein de votre PEA pour éviter l\'impôt sur la revente. Si cette start-up vous verse des dividendes, sont-ils exonérés d\'impôt sur le revenu dans le PEA ?',
      options: ['Non, les titres non cotés sont interdits dans le PEA', 'L\'exonération d\'impôt sur les dividendes de titres non cotés est PLAFONNÉE chaque année à 10 % du montant de votre investissement dans ces titres. L\'excédent sort du PEA et est taxé', 'Oui, de manière totalement illimitée', 'Ils sont taxés à 50 %'],
      correct: 1, rationale: 'L\'État a mis ce plafond pour éviter les abus massifs d\'optimisation fiscale des chefs d\'entreprise qui logeaient leur propre société dans leur PEA pour se verser d\'énormes dividendes sans impôt.' },
  ],
  'w15-d2': [
    { q: 'Dans l\'univers de l\'épargne retraite en entreprise, que signifie "PER Collectif" (ou PER COL) ?',
      options: ['Un PER géré par la mairie', 'Un PER ouvert par les syndicats', 'Un produit réservé uniquement aux fonctionnaires', 'Le Plan d\'Épargne Retraite d\'entreprise collectif, qui a succédé à l\'ancien PERCO. Il est ouvert à tous les salariés d\'une entreprise pour les aider à se constituer une retraite'],
      correct: 3, rationale: 'Créé par la loi PACTE, il est proposé de manière facultative aux salariés par leur employeur pour préparer la retraite dans un cadre fiscal très avantageux.' },
    { q: 'Le PER Collectif est alimenté par le salarié. Mais quel est l\'immense avantage financier offert par l\'entreprise (sous conditions) ?',
      options: ['L\'entreprise double le salaire du salarié', 'L\'entreprise peut verser un "Abondement", c\'est-à-dire une contribution financière supplémentaire qui vient s\'ajouter aux versements du salarié (ex : 300 % du versement, dans la limite d\'un plafond)', 'L\'entreprise paie la taxe foncière du salarié', 'L\'entreprise garantit le capital à 100 %'],
      correct: 1, rationale: 'C\'est le moteur principal de l\'épargne salariale. C\'est de "l\'argent gratuit" donné par le patron pour encourager l\'effort d\'épargne du salarié.' },
    { q: 'Parmi ces sources de revenus professionnels, laquelle est LA PLUS INTÉRESSANTE fiscalement à verser sur un PER Collectif ?',
      options: ['La prime d\'intéressement ou de participation', 'Son salaire de base', 'Ses frais kilométriques', 'Sa prime de Noël'],
      correct: 0, rationale: 'Si vous touchez ces primes directement sur votre compte bancaire, elles sont taxées à l\'impôt sur le revenu. Si vous les placez sur votre PER Collectif, elles sont totalement exonérées d\'impôt.' },
    { q: 'Un salarié dispose de jours de congés payés non pris sur son CET (Compte Épargne Temps). Peut-il les basculer sur son PER Collectif ?',
      options: ['Non, c\'est interdit', 'Uniquement s\'il a plus de 55 ans', 'Oui, dans la limite de 10 jours par an. Ces jours monétisés bénéficient alors d\'une exonération d\'impôt sur le revenu et alimentent son capital retraite', 'Oui, mais la banque garde 50 % de la valeur'],
      correct: 2, rationale: 'C\'est un excellent moyen de transformer de la fatigue en capital retraite sans passer par la case "impôts".' },
    { q: 'Comment est taxé "l\'abondement" versé par l\'employeur sur le PER Collectif du salarié ?',
      options: ['Il est lourdement taxé à 45 %', 'Il est taxé au barème progressif', 'Il est totalement exonéré d\'Impôt sur le Revenu pour le salarié (seuls la CSG/CRDS à un taux spécifique s\'appliquent)', 'L\'employé doit rembourser l\'abondement s\'il démissionne'],
      correct: 2, rationale: 'L\'abondement est le revenu d\'activité le moins taxé qui soit pour le salarié. C\'est une rémunération différée nette d\'impôt.' },
    { q: 'Vous quittez votre entreprise (démission, licenciement). Que devient votre PER Collectif ?',
      options: ['L\'employeur le récupère', 'Il vous appartient définitivement. Vous pouvez le laisser chez l\'ancien employeur, ou le transférer vers votre nouveau PER Collectif (nouvel employeur) ou vers votre PER Individuel (PERin)', 'Vous devez le clôturer et payer 30 % de pénalités', 'L\'État le gèle jusqu\'à vos 64 ans'],
      correct: 1, rationale: 'La "portabilité" est la grande force de la loi PACTE. Votre retraite vous suit tout au long de votre carrière dans un compte unique.' },
    { q: 'Par défaut, comment l\'argent du PER Collectif est-il investi si le salarié ne donne aucune consigne ?',
      options: ['En "Gestion pilotée à horizon" : l\'argent est investi sur des actifs risqués (actions) quand la retraite est loin, puis sécurisé progressivement vers des actifs garantis à l\'approche de la retraite', '100 % sur un compte courant sans rendement', '100 % sur des obligations russes', 'En Bitcoins'],
      correct: 0, rationale: 'Cela évite qu\'un salarié inactif ne laisse son argent sur un fonds monétaire peu rentable pendant 30 ans, ou ne subisse un krach boursier à 63 ans.' },
    { q: 'Comme tous les PER, les fonds sont bloqués jusqu\'à la retraite. Mais quel motif de "déblocage anticipé" rend le PER Collectif très attractif pour les jeunes actifs ?',
      options: ['Le paiement du permis de conduire', 'Le financement d\'un mariage', 'Le paiement des impôts', 'L\'acquisition de la résidence principale'],
      correct: 3, rationale: 'Cette soupape de sécurité permet aux salariés d\'utiliser l\'épargne de l\'entreprise (et l\'abondement !) pour acheter leur première ou nouvelle maison sans attendre 64 ans.' },
    { q: '(Challenge) Un salarié fait des "Versements Volontaires" (son propre argent) sur son PER Collectif d\'entreprise. Peuvent-ils être déduits de ses impôts ?',
      options: ['Non, la déduction est réservée au PER Individuel', 'Uniquement si l\'employeur donne son accord', 'Oui, les versements volontaires sur un PER Collectif bénéficient de la même déductibilité fiscale à l\'entrée que sur un PER Individuel', 'La déduction est obligatoire mais plafonnée à 100 €'],
      correct: 2, rationale: 'Le compartiment "Versements volontaires" du PER Collectif agit exactement comme un PERin.' },
    { q: '(Challenge) Pour une Petite ou Moyenne Entreprise (PME de moins de 50 salariés), quel est le cadeau fiscal majeur fait par l\'État pour l\'inciter à verser de l\'Abondement à ses salariés sur le PER Collectif ?',
      options: ['L\'entreprise ne paie plus l\'URSSAF', 'L\'entreprise est totalement exonérée du "Forfait Social" (une lourde taxe patronale de 16% à 20%) sur l\'abondement versé sur le PER Collectif', 'La PME reçoit une subvention de 10 000 €', 'L\'impôt sur les sociétés est divisé par deux'],
      correct: 1, rationale: 'C\'est ce qui rend la mise en place d\'un PER COL extrêmement rentable pour le chef d\'entreprise d\'une TPE/PME (y compris pour lui-même !).' },
  ],
  'w15-d3': [
    { q: 'En droit successoral, quelle est la règle d\'or (le statut exceptionnel) de l\'assurance-vie lors du décès de l\'assuré ?',
      options: ['Elle est transmise "Hors succession" : le capital n\'est pas soumis aux règles civiles du partage successoral (ordre des héritiers) et bénéficie d\'une fiscalité totalement dérogatoire', 'Elle entre dans la succession classique avec les meubles', 'Elle est taxée au barème progressif de l\'impôt sur le revenu', 'Elle est confisquée par l\'assureur pour payer les frais'],
      correct: 0, rationale: 'C\'est le paradis de la transmission. Vous donnez à qui vous voulez, hors du calcul notarié classique (sauf primes manifestement exagérées).' },
    { q: 'La fiscalité décès de l\'assurance-vie est séparée en deux grands régimes très différents. Quel est le critère qui bascule d\'un régime à l\'autre ?',
      options: ['La date du mariage de l\'assuré', 'Le fait que le bénéficiaire soit un enfant ou un ami', 'Le rendement de l\'assurance', 'L\'âge de l\'assuré au moment où il a VERSÉ les primes (avant 70 ans ou après 70 ans)'],
      correct: 3, rationale: 'L\'État est très généreux si vous placez votre argent tôt. Passé 70 ans, l\'avantage fiscal est drastiquement réduit pour éviter l\'évasion fiscale de dernière minute.' },
    { q: 'Pour toutes les primes versées AVANT l\'âge de 70 ans, quel est l\'abattement fiscal (somme sans aucun impôt) accordé PAR BÉNÉFICIAIRE désigné ?',
      options: ['31 865 €', '152 500 € par bénéficiaire', '100 000 € globalement', 'Il n\'y a pas d\'abattement'],
      correct: 1, rationale: 'Si vous avez 3 enfants et les désignez tous les trois, vous pouvez transmettre 457 500 € (3 x 152 500 €) sans qu\'ils ne paient 1 seul euro d\'impôt à votre décès.' },
    { q: 'Que se passe-t-il pour la somme qui DÉPASSE cet abattement de 152 500 € (primes versées avant 70 ans) ?',
      options: ['La somme excédentaire est saisie', 'Elle est taxée au taux normal des droits de succession', 'Elle est soumise à un prélèvement forfaitaire de 20 % (jusqu\'à 700 000 €), puis de 31,25 % au-delà', 'Le bénéficiaire paie 60 %'],
      correct: 2, rationale: 'Ce taux plat de 20 % reste extrêmement avantageux par rapport aux droits de succession classiques (qui peuvent monter à 45% pour un enfant, ou 60% pour un tiers).' },
    { q: 'Pour les primes versées APRÈS l\'âge de 70 ans, la règle est beaucoup moins généreuse. Quel est le montant de l\'abattement applicable ?',
      options: ['152 500 € par bénéficiaire, comme avant 70 ans', '100 000 € par enfant', 'Un abattement GLOBAL ET UNIQUE de 30 500 € (à se partager entre tous les bénéficiaires). Au-delà, l\'argent est soumis aux droits de succession classiques', 'Zéro abattement'],
      correct: 2, rationale: 'Passé 70 ans, le filet fiscal se referme. Si vous versez 200 000 € à 75 ans pour deux enfants, l\'abattement ne sera que de 15 250 € par enfant. Le reste sera taxé par le notaire.' },
    { q: 'MAIS, concernant ces versements après 70 ans, quelle est l\'excellente nouvelle fiscale concernant les INTÉRÊTS (gains) générés par le contrat jusqu\'au décès ?',
      options: ['Les intérêts (les plus-values) générés par ces primes versées après 70 ans sont TOTALEMENT EXONÉRÉS de droits de succession, quel que soit leur montant', 'Ils sont taxés à 60 %', 'Ils sont soumis à la Flat Tax', 'L\'assureur les conserve'],
      correct: 0, rationale: 'Si vous versez 30 500 € à 72 ans. Au décès, le contrat vaut 60 000 € (grâce à 29 500 € de gains boursiers). Vos enfants ne paieront AUCUN droit sur les 60 000 € !' },
    { q: 'Quel privilège absolu est accordé au CONJOINT SURVIVANT (marié ou pacsé avec testament) lorsqu\'il est désigné bénéficiaire d\'une assurance-vie ?',
      options: ['Il paie 20 % de taxes', 'L\'abattement passe à 200 000 €', 'Il doit la partager avec les enfants', 'Il est TOTALEMENT EXONÉRÉ de droits de succession ou de prélèvements, quel que soit l\'âge de versement des primes ou le montant du contrat'],
      correct: 3, rationale: 'Le conjoint (ou partenaire de PACS) échappe à la règle des 152 500 € et à la règle des 70 ans.' },
    { q: 'Lors du décès, l\'assureur va fermer le compte et verser le capital aux bénéficiaires. Que va-t-il prélever au passage pour le compte de l\'État (sur les gains générés sur les Unités de Compte) ?',
      options: ['La CSG est annulée au décès', 'Les prélèvements sociaux (17,2 %) sur les intérêts latents (qui n\'avaient pas encore été purgés)', '50 % du capital', 'Les frais d\'obsèques'],
      correct: 1, rationale: 'On échappe aux droits de succession, mais pas à la dette envers la Sécurité Sociale.' },
    { q: '(Challenge) Un père a versé 100 000 € sur son contrat à 60 ans. Au décès, le contrat vaut 180 000 €. Il a désigné son fils et sa fille à parts égales (50/50). Combien vont-ils payer d\'impôt au décès ?',
      options: ['0 €, car chaque part (90 000 €) est inférieure à l\'abattement individuel de 152 500 €', 'Ils paieront sur les 27 500 € excédentaires', 'Ils paieront 20 % sur la totalité', 'Ils sont taxés car la plus-value dépasse l\'abattement'],
      correct: 0, rationale: 'On juge l\'abattement par bénéficiaire en englobant le capital + les intérêts. 180k divisé par 2 = 90k chacun. C\'est inférieur à 152.5k, donc aucun impôt.' },
    { q: '(Challenge) Un couple marié sous la communauté (sans contrat) a utilisé l\'argent commun pour ouvrir une assurance-vie au nom de Monsieur seul. Madame décède la première. Que précise la "Réponse ministérielle Ciot" concernant l\'assurance-vie de Monsieur, toujours en vie ?',
      options: ['Le contrat est clôturé de force', 'Le contrat appartient à la banque', 'La moitié de la valeur du contrat de Monsieur intègre l\'actif de la succession de Madame (civilement), mais cette moitié est FISCALEMENT EXONÉRÉE de droits de succession pour tous les héritiers', 'Les enfants doivent payer 60 % d\'impôts sur la part'],
      correct: 2, rationale: 'Longtemps un casse-tête (arrêt Praslicka/Bacquet), la réponse Ciot de 2016 a pacifié la situation. La moitié du contrat fait bien partie du patrimoine commun transmissible, mais le fisc accepte de ne pas la taxer au moment du premier décès.' },
  ],
  'w15-d4': [
    { q: 'Dans le cadre d\'un crédit immobilier, que signifie le terme "Délégation d\'assurance" ?',
      options: ['Le fait de déléguer la signature à son conjoint', 'Le fait de payer la banque pour qu\'elle assure le bien', 'Le droit pour l\'emprunteur de souscrire son assurance de prêt (décès/invalidité) auprès d\'une compagnie d\'assurance EXTÉRIEURE (concurrente), plutôt que de prendre le contrat "groupe" proposé par sa banque', 'L\'annulation de l\'assurance obligatoire'],
      correct: 2, rationale: 'Ce libre choix permet de faire jouer la concurrence.' },
    { q: 'Quel est le principal objectif pour un emprunteur de recourir à une délégation d\'assurance ?',
      options: ['Diminuer le taux d\'intérêt du crédit', 'Réaliser des économies massives (souvent plusieurs milliers d\'euros) car les assurances externes sont généralement beaucoup moins chères que les contrats groupes des banques à garanties égales', 'Payer l\'agence immobilière', 'Rallonger la durée du crédit'],
      correct: 1, rationale: 'L\'assurance bancaire repose sur une tarification globale (les jeunes paient pour les vieux). La délégation propose un tarif "sur-mesure" basé sur votre âge et santé, ultra rentable pour les jeunes actifs.' },
    { q: 'Une banque refuse votre assurance externe. Selon la loi (Loi Lagarde / Lemoine), quel est l\'UNIQUE motif valable de refus ?',
      options: ['Que vous ayez moins de 30 ans', 'Que l\'assurance vienne d\'un courtier', 'Que le nouveau contrat ne présente pas un "Niveau de Garantie Équivalent" à celui exigé par la banque (les couvertures ne sont pas aussi protectrices)', 'La banque peut refuser sans motif'],
      correct: 2, rationale: 'La banque veut que son risque de non-remboursement soit parfaitement couvert. Si le contrat concurrent est moins bon sur la couverture invalidité, elle refusera à juste titre.' },
    { q: 'Grâce à la loi Lemoine de 2022, À QUEL MOMENT pouvez-vous procéder à une délégation d\'assurance (changer d\'assureur) pour votre crédit immobilier en cours ?',
      options: ['À tout moment (Résiliation Infra-Annuelle), dès le lendemain de la signature du crédit, sans aucun frais ni préavis complexe', 'Uniquement dans la première année', 'Uniquement à la date d\'anniversaire du contrat avec 2 mois de préavis', 'Seulement si on vend la maison'],
      correct: 0, rationale: 'C\'est la libération totale du marché. Vous n\'avez plus besoin de guetter des dates d\'anniversaires piégeuses.' },
    { q: 'La banque a-t-elle le droit de vous facturer des "Frais de délégation" ou d\'augmenter le taux d\'intérêt de votre crédit en représailles de votre changement d\'assurance ?',
      options: ['Seulement la première année', 'Oui, c\'est prévu dans les conditions générales', 'Non, c\'est strictement interdit par la loi. Les conditions du crédit (taux, frais) doivent rester exactement les mêmes', 'Oui, 500 € de frais de dossier'],
      correct: 2, rationale: 'La loi punit lourdement le "chantage au taux". La banque ne peut en aucun cas modifier son offre parce que vous refusez son assurance.' },
    { q: 'Comment s\'appelle le document, obligatoirement remis par la banque, qui liste précisément les garanties minimales que votre contrat délégué devra comporter pour être accepté ?',
      options: ['L\'attestation de dépôt', 'La FSI (Fiche Standardisée d\'Information)', 'Le tableau d\'amortissement', 'Le relevé de carrière'],
      correct: 1, rationale: 'C\'est la grille de lecture. Elle comporte une vingtaine de critères (ex: garantie des affections psychiatriques). Le courtier n\'a plus qu\'à cocher "oui" à tous les critères sur son devis pour que la banque ne puisse pas refuser.' },
    { q: 'L\'assurance déléguée (externe) a été envoyée à la banque. De quel délai dispose cette dernière pour analyser le contrat et vous donner sa réponse (acceptation ou refus motivé) ?',
      options: ['3 mois', 'Elle n\'est pas obligée de répondre', '48 heures', '10 jours ouvrés'],
      correct: 3, rationale: 'Si la banque laisse traîner le dossier pour décourager le client (technique de la montre), elle s\'expose à une amende.' },
    { q: 'En matière de tarification de l\'assurance emprunteur (et c\'est souvent ce qui fait la différence entre la banque et la délégation), qu\'est-ce qu\'une prime calculée sur le "Capital Restant Dû" (CRD) ?',
      options: ['La prime (la mensualité d\'assurance) baisse au fil des années, car elle est calculée sur le capital qu\'il reste à rembourser, contrairement à une prime fixe calculée sur le capital initial', 'La prime augmente chaque mois', 'La prime est fixe sur 25 ans', 'La prime est payée en une seule fois au début'],
      correct: 0, rationale: 'Le contrat groupe de la banque est souvent "fixe" (ex: 50€/mois pendant 25 ans). En délégation CRD, vous paierez 60€ au début, puis 30€, puis 5€ à la fin, ce qui est souvent plus rentable.' },
    { q: '(Challenge) Dans l\'analyse d\'une offre de prêt, que révèle l\'indicateur appelé "TAEA" ?',
      options: ['Le taux des agios en cas de retard', 'Le Taux de la banque sans assurance', 'Le Taux Annuel Effectif de l\'Assurance : il permet de voir immédiatement la part que représente l\'assurance (en pourcentage) dans le coût total du crédit', 'La taxe sur l\'assurance environnementale'],
      correct: 2, rationale: 'Si le crédit est à 3% et le TAEA à 1%, l\'assurance vous coûte l\'équivalent d\'un tiers des intérêts bancaires. C\'est l\'indicateur parfait pour comparer deux devis.' },
    { q: '(Challenge) Un couple emprunte en délégation d\'assurance externe. La banque exigeait que le crédit soit couvert à "100 % sur la tête de chacun" (soit 200 % de couverture). La délégation d\'assurance externe doit-elle respecter cette exigence ?',
      options: ['Non, la délégation limite à 50/50', 'Oui, l\'exigence des quotités d\'assurance (la répartition de la couverture entre les conjoints) fait partie intégrante du critère de "niveau de garantie équivalent"', 'Le conjoint ne doit pas être assuré', 'L\'État s\'assure pour 50 %'],
      correct: 1, rationale: 'Si la banque exige que le prêt soit remboursé en totalité si Madame ou Monsieur décède (quotité 100/100), le contrat délégué devra reproduire exactement ce niveau de sécurité.' },
  ],
  'w15-d5': [
    { q: 'Que signifie le sigle LMNP ?',
      options: ['Logement Modeste Nationalement Protégé', 'Loueur en Meublé Non Professionnel', 'Location Mensuelle Négociée entre Particuliers', 'Loi Macron des Nouveaux Propriétaires'],
      correct: 1, rationale: 'C\'est un statut fiscal et juridique majeur de l\'investissement immobilier, permettant de louer des appartements tout équipés avec une fiscalité adoucie.' },
    { q: 'Pour qu\'un logement soit qualifié de "meublé" au regard de la loi (décret de 2015), que doit-il contenir ?',
      options: ['Juste un matelas au sol et un frigo', 'Strictement tout le mobilier (canapé, table) payé par l\'agence', 'Une liste stricte et obligatoire d\'équipements permettant au locataire d\'y dormir, manger et vivre convenablement (literie, plaques de cuisson, vaisselle, luminaires, table, sièges...)', 'Uniquement des meubles de collection'],
      correct: 2, rationale: 'Si la passoire ou les rideaux manquent, le juge ou le fisc peut requalifier le bail en location "nue", ce qui détruit le modèle fiscal.' },
    { q: 'Dans quelle catégorie fiscale les revenus d\'une location meublée (LMNP) doivent-ils être déclarés ?',
      options: ['Les Bénéfices Industriels et Commerciaux (BIC)', 'Les Revenus Fonciers', 'Les Bénéfices Agricoles (BA)', 'Les plus-values mobilières'],
      correct: 0, rationale: 'La location nue relève du "civil" (Revenus fonciers). La location meublée relève de la prestation de service "commerciale" (BIC).' },
    { q: 'Si le propriétaire choisit le régime "Micro-BIC" (régime forfaitaire), de quel abattement bénéficie-t-il sur ses loyers avant l\'impôt ?',
      options: ['10 %', '30 % (comme la location nue)', '0 %', '50 % (il n\'est taxé que sur la moitié de ses loyers perçus)'],
      correct: 3, rationale: 'C\'est le premier grand atout du meublé. Sans aucune facture à fournir, l\'État efface la moitié de vos loyers avant d\'appliquer l\'impôt (contre 30% en location nue).' },
    { q: 'Quel est l\'avantage massif de renoncer au micro-BIC pour opter pour le "Régime Réel" en LMNP ?',
      options: ['Il annule la taxe foncière', 'Il permet "l\'amortissement comptable" du bien immobilier et des meubles. En déduisant chaque année une fraction de la valeur de l\'appartement des loyers, le propriétaire peut ramener son impôt à ZÉRO pendant de très nombreuses années', 'Il interdit au locataire de partir', 'Il permet de payer la TVA à 5 %'],
      correct: 1, rationale: 'C\'est la magie comptable du LMNP. Sur le papier, votre immeuble "s\'use" sur 30 ans. Cette usure (l\'amortissement) est déduite de vos loyers comme une charge, effaçant ainsi vos bénéfices taxables.' },
    { q: 'Sous le régime réel LMNP, que se passe-t-il si vos amortissements sont supérieurs à vos loyers et créent un résultat comptable négatif (un déficit) ?',
      options: ['Le déficit est effacé', 'Il vient se déduire de votre salaire pour annuler l\'impôt sur le revenu', 'La fraction de l\'amortissement non utilisée est "mise en réserve" (reportable sans limite de temps) pour gommer les futurs loyers bénéficiaires', 'L\'État vous rembourse l\'amortissement'],
      correct: 2, rationale: 'Contrairement à la location nue (déficit foncier), un déficit issu d\'amortissements LMNP ne se déduit JAMAIS du salaire global, il s\'accumule pour faire un bouclier fiscal sur les futurs loyers.' },
    { q: 'En location meublée classique (résidence principale), quelle est la durée standard du bail ?',
      options: ['1 an (réductible à 9 mois si le locataire est étudiant)', '3 ans', '6 mois', '9 ans'],
      correct: 0, rationale: 'C\'est une grande souplesse pour le propriétaire par rapport à la location nue (3 ans).' },
    { q: 'Quel préavis le locataire d\'un meublé doit-il respecter pour donner congé (partir) ?',
      options: ['3 mois', '6 mois', '2 semaines', '1 mois, quelle que soit la ville'],
      correct: 3, rationale: 'C\'est la flexibilité du meublé. Il est fait pour la mobilité professionnelle ou étudiante.' },
    { q: '(Challenge) Lors de la revente d\'un bien exploité en LMNP au régime réel (avec des amortissements), comment se calcule la plus-value immobilière ?',
      options: ['Selon le régime des plus-values professionnelles (très taxé)', 'Selon le régime très avantageux des plus-values des "Particuliers" (comme en location nue) : les amortissements déduits pendant l\'exploitation NE SONT PAS rajoutés à la plus-value, et les abattements pour durée de détention s\'appliquent', 'La vente est interdite avant 15 ans', 'L\'État récupère les amortissements'],
      correct: 1, rationale: 'C\'est l\'anomalie fiscale hyper rentable du LMNP (qui pourrait être réformée). On défiscalise pendant l\'exploitation (règles pro), mais on profite de l\'effacement de l\'impôt à la revente (règles particuliers).' },
    { q: '(Challenge) Quelle est la condition (le seuil) fixée par la loi pour basculer du statut non professionnel (LMNP) au statut PROFESSIONNEL (LMP) ?',
      options: ['Avoir un numéro SIRET', 'Avoir au moins 3 appartements', 'Il faut que les recettes (loyers perçus) dépassent 23 000 € TTC par an ET que ces recettes soient SUPÉRIEURES aux autres revenus d\'activité (salaires) du foyer fiscal', 'C\'est un choix libre sur un formulaire'],
      correct: 2, rationale: 'Si vous gagnez 40 000€ de salaire et 25 000€ de loyers meublés, vous restez LMNP. Si vous gagnez 20 000€ de salaire et 25 000€ de loyers, vous basculez LMP (avec de lourdes conséquences sur les cotisations sociales URSSAF et les plu' },
  ],
};
